### ISSUE TITLE
Backend failed to start up Error: Cannot find module 'app/package.json'

### ISSUE THREAD

**Issue by j021006** [backstage/backstage#10093]
## Expected Behavior

Able to run container

## Actual Behavior

I am getting the following error when i upgraded to the latest release when trying to run my container but unable to replicate the error locally...

```
Backend failed to start up Error: Cannot find module 'app/package.json'
Require stack:
- /app/node_modules/@backstage/backend-common/dist/index.cjs.js
- /app/packages/backend/dist/index.cjs.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.resolvePackagePath (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:1524:35)
    at Object.createRouter (/app/node_modules/@backstage/plugin-app-backend/dist/index.cjs.js:178:36)
    at createPlugin$3 (/app/packages/backend/dist/index.cjs.js:83748:33)
    at main (/app/packages/backend/dist/index.cjs.js:90959:180)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@backstage/backend-common/dist/index.cjs.js',
    '/app/packages/backend/dist/index.cjs.js'
  ]
}
```

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- Browser Information: 
- Chrome

- Output of `yarn backstage-cli info`: 

```
OS:   Windows_NT 10.0.18363 - win32/x64
node: v16.13.0
yarn: 1.22.1
cli:  0.15.1 (installed)

Dependencies:
  @backstage/app-defaults                                  0.2.0
  @backstage/backend-common                                0.10.9, 0.12.1
  @backstage/backend-tasks                                 0.1.10
  @backstage/catalog-client                                0.5.5, 0.8.0
  @backstage/catalog-model                                 0.12.1, 0.9.10
  @backstage/cli-common                                    0.1.8
  @backstage/cli                                           0.15.1
  @backstage/config-loader                                 0.9.6
  @backstage/config                                        0.1.15
  @backstage/core-app-api                                  0.6.0
  @backstage/core-components                               0.9.0
  @backstage/core-plugin-api                               0.8.0
  @backstage/errors                                        0.2.2
  @backstage/integration-react                             0.1.24
  @backstage/integration                                   0.7.5, 0.8.0
  @backstage/plugin-api-docs                               0.8.1
  @backstage/plugin-app-backend                            0.3.28
  @backstage/plugin-auth-backend                           0.12.0
  @backstage/plugin-auth-node                              0.1.4
  @backstage/plugin-badges-backend                         0.1.22
  @backstage/plugin-badges                                 0.2.25
  @backstage/plugin-catalog-backend-module-ldap            0.3.15
  @backstage/plugin-catalog-backend                        0.23.1
  @backstage/plugin-catalog-common                         0.2.1
  @backstage/plugin-catalog-graph                          0.2.13
  @backstage/plugin-catalog-import                         0.8.4
  @backstage/plugin-catalog-react                          0.8.1
  @backstage/plugin-catalog                                0.9.1
  @backstage/plugin-code-coverage-backend                  0.1.26
  @backstage/plugin-code-coverage                          0.1.28
  @backstage/plugin-explore-react                          0.0.14
  @backstage/plugin-explore                                0.3.32
  @backstage/plugin-home                                   0.4.17
  @backstage/plugin-jenkins-backend                        0.1.17
  @backstage/plugin-jenkins-common                         0.1.0
  @backstage/plugin-jenkins                                0.7.0
  @backstage/plugin-kafka-backend                          0.2.21
  @backstage/plugin-kafka                                  0.3.1
  @backstage/plugin-kubernetes-backend                     0.4.11
  @backstage/plugin-kubernetes-common                      0.2.6
  @backstage/plugin-kubernetes                             0.6.1
  @backstage/plugin-org                                    0.5.1
  @backstage/plugin-permission-backend                     0.5.3
  @backstage/plugin-permission-common                      0.5.2
  @backstage/plugin-permission-node                        0.5.3
  @backstage/plugin-permission-react                       0.3.3
  @backstage/plugin-proxy-backend                          0.2.22
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.2.3
  @backstage/plugin-scaffolder-backend                     0.17.3
  @backstage/plugin-scaffolder-common                      0.2.3
  @backstage/plugin-scaffolder                             0.14.0
  @backstage/plugin-search-backend-module-pg               0.3.0
  @backstage/plugin-search-backend-node                    0.5.0
  @backstage/plugin-search-backend                         0.4.6
  @backstage/plugin-search                                 0.7.2
  @backstage/plugin-sonarqube                              0.3.1
  @backstage/plugin-tech-insights-backend-module-jsonfc    0.1.12
  @backstage/plugin-tech-insights-backend                  0.1.5
  @backstage/plugin-tech-insights-common                   0.2.0, 0.2.3
  @backstage/plugin-tech-insights-node                     0.1.2, 0.2.6
  @backstage/plugin-tech-insights                          0.1.11
  @backstage/plugin-tech-radar                             0.5.8
  @backstage/plugin-techdocs-backend                       0.14.1
  @backstage/plugin-techdocs                               0.15.0
  @backstage/plugin-todo-backend                           0.1.25
  @backstage/plugin-todo                                   0.2.3
  @backstage/plugin-user-settings                          0.4.0
  @backstage/release-manifests                             0.0.2
  @backstage/search-common                                 0.3.0
  @backstage/techdocs-common                               0.11.11
  @backstage/test-utils                                    0.3.0
  @backstage/theme                                         0.2.15
  @backstage/types                                         0.1.3
  @backstage/version-bridge                                0.1.2
Done in 0.90s.
```

**Comment by benjdlambert** [comment]
Going to close this as it should be fixed with `v0.71.1`. Re-open if needed!

**Comment by kallusakar** [comment]
Hi, just starting to get grasp on Backstage and when I wanted to create a docker image from it, I got the same error. I'm on version 1.0.0 (created by npx @backstage/create-app) and despite me trying very hard was unable to solve it. 

could someone please point me in right direction? My guess is that during build, frontend(app) isn't properly bundled with backend when using @backstage/plugin-app-backend but my insight into the problem is somewhat limited. 

Error message:
```
Backend failed to start up, Error: Cannot find module 'app/package.json'
Require stack:
- /app/node_modules/@backstage/backend-common/dist/index.cjs.js
- /app/packages/backend/dist/index.cjs.js
```

My output of yarn backstage-cli info follows
```
OS:   Linux 5.9.6-050906-generic - linux/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.16.0 (installed)

Dependencies:
  @backstage/app-defaults                            1.0.0
  @backstage/backend-common                          0.13.1
  @backstage/backend-tasks                           0.2.1
  @backstage/catalog-client                          1.0.0
  @backstage/catalog-model                           1.0.0
  @backstage/cli-common                              0.1.8
  @backstage/cli                                     0.16.0
  @backstage/config-loader                           1.0.0
  @backstage/config                                  1.0.0
  @backstage/core-app-api                            1.0.0
  @backstage/core-components                         0.9.2
  @backstage/core-plugin-api                         1.0.0
  @backstage/errors                                  1.0.0
  @backstage/integration-react                       1.0.0
  @backstage/integration                             1.0.0
  @backstage/plugin-api-docs                         0.8.3
  @backstage/plugin-app-backend                      0.3.30
  @backstage/plugin-auth-backend                     0.12.3
  @backstage/plugin-auth-node                        0.1.6
  @backstage/plugin-catalog-backend-module-bitbucket 0.1.1
  @backstage/plugin-catalog-backend                  1.0.0
  @backstage/plugin-catalog-common                   1.0.0
  @backstage/plugin-catalog-graph                    0.2.15
  @backstage/plugin-catalog-import                   0.8.6
  @backstage/plugin-catalog-react                    1.0.0
  @backstage/plugin-catalog                          1.0.0
  @backstage/plugin-github-actions                   0.5.3
  @backstage/plugin-kafka-backend                    0.2.23
  @backstage/plugin-kafka                            0.3.3
  @backstage/plugin-kubernetes-backend               0.4.13
  @backstage/plugin-kubernetes-common                0.2.8
  @backstage/plugin-kubernetes                       0.6.3
  @backstage/plugin-org                              0.5.3
  @backstage/plugin-permission-common                0.5.3
  @backstage/plugin-permission-node                  0.5.5
  @backstage/plugin-permission-react                 0.3.4
  @backstage/plugin-proxy-backend                    0.2.24
  @backstage/plugin-scaffolder-backend               1.0.0
  @backstage/plugin-scaffolder-common                1.0.0
  @backstage/plugin-scaffolder                       1.0.1
  @backstage/plugin-search-backend-node              0.5.2
  @backstage/plugin-search-backend                   0.4.8
  @backstage/plugin-search-common                    0.3.2
  @backstage/plugin-search                           0.7.4
  @backstage/plugin-shortcuts                        0.2.4
  @backstage/plugin-tech-radar                       0.5.10
  @backstage/plugin-techdocs-backend                 1.0.0
  @backstage/plugin-techdocs-node                    1.0.0
  @backstage/plugin-techdocs                         1.0.1
  @backstage/plugin-user-settings                    0.4.2
  @backstage/release-manifests                       0.0.2
  @backstage/search-common                           0.3.2
  @backstage/test-utils                              1.0.0
  @backstage/theme                                   0.2.15
  @backstage/types                                   1.0.0
  @backstage/version-bridge                          1.0.0
Done in 0.57s.
```

**Comment by cal5barton** [comment]
This is happening for me for version `1.11.0`

**Comment by Remyapraveen** [comment]
Hi, I am using the backstage version of backstage:  1.12.1. I am currently trying to deploy my app into AWS EC2 instance after an integration with Authentication Providers. The app is working well in the local environment, but getting this error when I am trying to deploy it in AWS environment. 

```
app_1     | node:internal/modules/cjs/loader:444
app_1     |       throw err;
app_1     |       ^
app_1     |
app_1     | Error: Cannot find module '/app/packages/backend/dist\index.cjs.js'. Please verify that the package.json has a valid "main" entry
app_1     |     at tryPackage (node:internal/modules/cjs/loader:436:19)
app_1     |     at Module._findPath (node:internal/modules/cjs/loader:678:18)
app_1     |     at resolveMainPath (node:internal/modules/run_main:19:25)
app_1     |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:75:24)
app_1     |     at node:internal/main/run_main_module:23:47 {
app_1     |   code: 'MODULE_NOT_FOUND',
app_1     |   path: '/app/packages/backend/package.json',
app_1     |   requestPath: '/app/packages/backend'
app_1     | }
app_1     |
app_1     | Node.js v18.15.0

````

My .dockerignore file looks as default with following elements.

```

.git
.yarn/cache
.yarn/install-state.gz
node_modules
packages/*/src
packages/*/node_modules
plugins
*.local.yaml

**Comment by Remyapraveen** [comment]
Hi @tsteele , not yet. Still figuring out the issue.

**Comment by regicsolutions** [comment]
same here

**Comment by Remyapraveen** [comment]
HI @tsteele & @regicsolutions , there was a patch on backstage/cli done a couple of days ago. So if you replace the backsatge/cli to the latest version, you can get this thing working. Please do refer to this https://github.com/backstage/backstage/issues/17123

**Comment by AndrewTtofi** [comment]
had a similar one in version 1.12.0 but bumping to 1.12.1 resolved this as @Remyapraveen mentioned.

**Comment by quike** [comment]
Having same issue on AWS ECS, v1.13.0 and v1.13.2 both tested. The generated docker image fails in there but run perfectly in local.

**Comment by Remyapraveen** [comment]
@quike, May I check if your Backstage cli version is the same as this @backstage/cli  0.22.6-next.1 ?? Otherwise you might need upgrade to that then. Please do check on the following thread in Discord community. "https://discord.com/channels/687207715902193673/687235481154617364/threads/1088637782693531750"

**Comment by quike** [comment]
thanks @Remyapraveen I added a comment there https://discord.com/channels/687207715902193673/1088637782693531750/1102974731495415808

I tried with  0.22.6-next.1, 0.22.6 and 0.22.7-next.0 all same behavior.

**Comment by Umoren** [comment]
Whenever i add `config.d.ts` to `packages/app`, i get same error. Very strange bug.

**Comment by benjdlambert** [comment]
@Umoren can you make sure you're on the latest version of backstage? What version are you currently running?

**Comment by Umoren** [comment]
{
  "version": "1.15.0"
}

**Comment by Umoren** [comment]
@benjdlambert this:
```json
{
  "version": "1.15.0"
}
```

**Comment by Umoren** [comment]
@benjdlambert also if you have the time, please help check out this issue
https://github.com/backstage/backstage/issues/18595
Thanks.

**Comment by piatkiewicz** [comment]
Had the same issue with just freshly created app, but running `npx @backstage/cli versions:bump` as [cal5barton mentioned](https://github.com/backstage/backstage/issues/10093#issuecomment-1452363835) bumped the version from `1.29.0` to `1.29.2` and fixed that.

**Comment by ShayMeshGit** [comment]
The same issue with version 1.30.2

**_ForwardedError: Plugin 'app' startup failed; caused by Error: Cannot find module 'app/package.json'_**

I'm using the multi-stage Dockerfile
