### ISSUE TITLE
Onelogin Authentication Fails with message "Refresh failed; caused by InputError: Missing session cookie"

### ISSUE THREAD

**Issue by debuggerpk** [backstage/backstage#10107]
Have been following the [docs](https://backstage.io/docs/auth/onelogin/provider) for Onelogin, My App.tsx looks like this

```tsx
const oneloginProver: SignInProviderConfig = {
  id: 'onelogin-auth-provider',
  title: 'OneLogin',
  message: 'Signin Using OneLogin',
  apiRef: oneloginAuthApiRef,
};

const app = createApp({
  apis,
  components: {
    SignInPage: props => (
      <SignInPage {...props} auto provider={oneloginProver} />
    ),
  },
 ...
})
```

and my app-config.yaml looks like this.

```yaml
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    onelogin:
      development:
        clientId: ${ONELOGIN_CLIENT_ID}
        clientSecret: ${ONELOGIN_CLIENT_SECRET}
        issuer: ${ONELOGIN_ISSUER}
```

## Expected Behavior
We should be able to signin normally at this point, but we aren't. 

## Actual Behavior

Instead, we get an error message .. 

> Authentication failed, client authentication failed

## Steps to Reproduce

As explained above.

## Context

The error that I get on frontend

```json
{
    "error": {
        "name": "AuthenticationError",
        "message": "Refresh failed; caused by InputError: Missing session cookie",
        "cause": {
            "name": "InputError",
            "message": "Missing session cookie",
            "stack": "InputError: Missing session cookie\n    at OAuthAdapter.refresh (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:411:15)\n    at OAuthEnvironmentHandler.refresh (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:188:58)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at /app/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/app/node_modules/express/lib/router/index.js:275:10)\n    at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)\n    at router (/app/node_modules/express/lib/router/index.js:47:12)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)"
        }
    },
    "request": {
        "method": "GET",
        "url": "/api/auth/onelogin/refresh?optional&env=development"
    },
    "response": {
        "statusCode": 401
    }
}
```
and the backend stacktrace is

```text
[1] 2022-03-10T13:26:26.086Z backstage info ::1 - - [10/Mar/2022:13:26:26 +0000] "GET /api/auth/onelogin/refresh?optional&env=development HTTP/1.1" 401 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36" type=incomingRequest
[1] 2022-03-10T13:26:47.138Z backstage info ::1 - - [10/Mar/2022:13:26:47 +0000] "GET /api/auth/onelogin/start?scope=openid%20email%20profile%20offline_access&origin=http%3A%2F%2Flocalhost%3A3000&env=development HTTP/1.1" 302 0 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36" type=incomingRequest
[1] 2022-03-10T13:26:52.528Z backstage info ::1 - - [10/Mar/2022:13:26:52 +0000] "GET /api/auth/onelogin/handler/frame?code=6OFasxBIT546aQNnm9PFmPOYkQK&state=6e6f6e63653d45654539535a6543673958495662586e544878684c7725334425334426656e763d646576656c6f706d656e74266f726967696e3d687474702533412532462532466c6f63616c686f737425334133303030 HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36" type=incomingRequest
[1] 2022-03-10T13:27:46.097Z backstage info ::1 - - [10/Mar/2022:13:27:46 +0000] "GET /api/auth/onelogin/refresh?optional&env=development HTTP/1.1" 401 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36" type=incomingRequest
[1] 2022-03-10T13:27:57.214Z backstage info ::1 - - [10/Mar/2022:13:27:57 +0000] "GET /api/auth/onelogin/refresh?optional&env=development HTTP/1.1" 401 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36" type=incomingRequest
```

## Your Environment
- Browser Information: 

Google Chrome 99.0.4844.51 (Official Build) (x86_64)

- Output of `yarn backstage-cli info`: 

```text
  @backstage/app-defaults                                  0.2.0
  @backstage/backend-common                                0.12.1
  @backstage/backend-tasks                                 0.1.10
  @backstage/catalog-client                                0.7.1, 0.8.0
  @backstage/catalog-model                                 0.10.1, 0.12.1
  @backstage/cli-common                                    0.1.8
  @backstage/cli                                           0.15.1
  @backstage/config-loader                                 0.9.6
  @backstage/config                                        0.1.15
  @backstage/core-app-api                                  0.6.0
  @backstage/core-components                               0.8.9, 0.9.0
  @backstage/core-plugin-api                               0.6.1, 0.8.0
  @backstage/errors                                        0.2.2
  @backstage/integration-react                             0.1.24
  @backstage/integration                                   0.7.4, 0.8.0
  @backstage/plugin-api-docs                               0.8.1
  @backstage/plugin-app-backend                            0.3.28
  @backstage/plugin-auth-backend                           0.12.0
  @backstage/plugin-auth-node                              0.1.4
  @backstage/plugin-catalog-backend                        0.23.1
  @backstage/plugin-catalog-common                         0.2.1
  @backstage/plugin-catalog-graph                          0.2.13
  @backstage/plugin-catalog-import                         0.8.4
  @backstage/plugin-catalog-react                          0.6.15, 0.8.1
  @backstage/plugin-catalog                                0.9.1
  @backstage/plugin-github-actions                         0.5.1
  @backstage/plugin-org                                    0.5.1
  @backstage/plugin-permission-common                      0.5.2
  @backstage/plugin-permission-node                        0.5.3
  @backstage/plugin-permission-react                       0.3.3
  @backstage/plugin-proxy-backend                          0.2.22
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.2.3
  @backstage/plugin-scaffolder-backend                     0.17.3
  @backstage/plugin-scaffolder-common                      0.2.3
  @backstage/plugin-scaffolder                             0.14.0
  @backstage/plugin-search-backend-node                    0.5.0
  @backstage/plugin-search-backend                         0.4.6
  @backstage/plugin-search                                 0.7.2
  @backstage/plugin-tech-radar                             0.5.8
  @backstage/plugin-techdocs-backend                       0.14.1
  @backstage/plugin-techdocs                               0.15.0
  @backstage/plugin-user-settings                          0.4.0
  @backstage/release-manifests                             0.0.2
  @backstage/search-common                                 0.3.0
  @backstage/techdocs-common                               0.11.11
  @backstage/test-utils                                    0.3.0
  @backstage/theme                                         0.2.15
  @backstage/types                                         0.1.3
  @backstage/version-bridge                                0.1.2
```

**Comment by debuggerpk** [comment]
After investigating furthur, The response to url `http://localhost:7007/api/auth/onelogin/refresh?optional&env=development`
gives 401 even before the oauth dialog is done processing. Shouldn't this wait for oauth login process to finish.

**Comment by debuggerpk** [comment]
The error appears to come from this line https://github.com/backstage/backstage/blob/dd77b5eb1285f77a2511d128811eaae12b94d922/plugins/auth-backend/src/lib/oauth/OAuthAdapter.ts#L140

Looking at `this.handler`, there is no key by the name "handler" .. so the flow does not continue from here. Investigating further.

```ts
{
  signInResolver: [AsyncFunction: defaultSignInResolver],
  authHandler: [AsyncFunction (anonymous)],
  tokenIssuer: TokenFactory {
    issuer: 'http://localhost:7007/api/auth',
    logger: DerivedLogger {},
    keyStore: DatabaseKeyStore { database: [Function] },
    keyDurationSeconds: 3600
  },
  catalogIdentityClient: CatalogIdentityClient {
    catalogApi: CatalogClient {
      discoveryApi: [SingleHostDiscovery],
      fetchApi: [Object]
    },
    tokenManager: NoopTokenManager { isInsecureServerTokenManager: true }
  },
  logger: DerivedLogger {},
  _strategy: Strategy {
    name: 'onelogin',
    _verify: [Function (anonymous)],
    _oauth2: {
      _clientId: '7643f550-8118-013a-58cd-069bacdc12af142412',
      _clientSecret: 'https://pwpush.com/en/p/n_ah2i4qxxpijng/preview',
      _baseSite: '',
      _authorizeUrl: 'https://hd-sso.onelogin.com/oidc/2/auth',
      _accessTokenUrl: 'https://hd-sso.onelogin.com/oidc/2/token',
      _accessTokenName: 'access_token',
      _authMethod: 'Bearer',
      _customHeaders: {},
      _useAuthorizationHeaderForGET: true,
      _agent: undefined
    },
    _callbackURL: 'http://localhost:7007/api/auth/onelogin/handler/frame',
    _scope: undefined,
    _scopeSeparator: ' ',
    _pkceMethod: undefined,
    _key: 'oauth2:hd-sso.onelogin.com',
    _stateStore: NullStore {},
    _trustProxy: undefined,
    _passReqToCallback: false,
    _skipUserProfile: false,
    _userInfoUrl: 'https://hd-sso.onelogin.com/oidc/2/me',
    _idp: undefined
  }
}
```

**Comment by debuggerpk** [comment]
closing, false alarm.

**Comment by vellanki550** [comment]
@debuggerpk..we've tried it exactly the same way..but facing the missing session cookie..how did you get it resolved?
