### ISSUE TITLE
[jenkins-backend] If Jenkins returns 'null' for an action, backend stops working

### ISSUE THREAD

**Issue by yarodinD** [backstage/backstage#10176]
## Expected Behavior
When retrieving Jenkins job, the property "actions" might contain null values. These should be handled gracefully by the plugin, not affecting the functionality.

## Actual Behavior
When a jenkins job returns a 'null' value for an action, an error is shown in the server log.

The frontend then just shows the loading animation endlessly.

## Steps to Reproduce

My Jenkins (Version 2.303.2) returns "null" as a value in the `actions` array for some jobs, like this:
```json
    "actions": [
        {
            "_class": "hudson.model.ParametersDefinitionProperty",
            "parameterDefinitions": [
                {
                    "_class": "hudson.model.StringParameterDefinition",
                    "defaultParameterValue": {
                        "_class": "hudson.model.StringParameterValue",
                        "value": "master"
                    },
                    "description": "",
                    "name": "BRANCH",
                    "type": "StringParameterDefinition"
                }
            ]
        },
        {},
        {},
        {},
        null,
        {},
        {},
        {},
        {
            "_class": "hudson.plugins.jobConfigHistory.JobConfigHistoryProjectAction"
        },
        {},
        {},
        {},
        {},
        {
            "_class": "org.jenkinsci.plugins.displayurlapi.actions.JobDisplayAction"
        },
        {
            "_class": "org.jenkinsci.plugins.testresultsanalyzer.TestResultsAnalyzerAction"
        },
        {},
        {
            "_class": "com.cloudbees.plugins.credentials.ViewCredentialsAction"
        }
    ],
```
This leads to the error above.

## Context
This behavior leads to no jobs being shown.

The error log:
```
[1] 2022-03-14T15:08:11.602Z backstage error Cannot read properties of null (reading '_class') type=errorHandler stack=TypeError: Cannot read properties of null (reading '_class')
[1]     at /home/sanders/backstage/backstage/backstage-service/node_modules/@backstage/plugin-jenkins-backend/dist/index.cjs.js:229:63
[1]     at Array.filter (<anonymous>)
[1]     at Function.extractScmDetailsFromJob (/home/sanders/backstage/backstage/backstage-service/node_modules/@backstage/plugin-jenkins-backend/dist/index.cjs.js:229:37)
[1]     at _JenkinsApiImpl.augmentProject (/home/sanders/backstage/backstage/backstage-service/node_modules/@backstage/plugin-jenkins-backend/dist/index.cjs.js:190:40)
[1]     at _JenkinsApiImpl.getProjects (/home/sanders/backstage/backstage/backstage-service/node_modules/@backstage/plugin-jenkins-backend/dist/index.cjs.js:142:30)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]     at async /home/sanders/backstage/backstage/backstage-service/node_modules/@backstage/plugin-jenkins-backend/dist/index.cjs.js:314:22

```

## Your Environment

- Browser Information: all browsers (Chrome, Firefox...)

- Output of `yarn backstage-cli info`: 

```text
OS:   Linux 5.13.0-28-generic - linux/x64
node: v16.13.0
yarn: 1.22.17
cli:  0.15.3 (installed)

Dependencies:
  @backstage/app-defaults                               0.2.1
  @backstage/backend-common                             0.13.0
  @backstage/catalog-client                             0.8.0, 0.9.0
  @backstage/catalog-model                              0.12.1, 0.13.0
  @backstage/cli-common                                 0.1.8
  @backstage/cli                                        0.15.3
  @backstage/config-loader                              0.9.7
  @backstage/config                                     0.1.15
  @backstage/core-app-api                               0.6.0
  @backstage/core-components                            0.9.1
  @backstage/core-plugin-api                            0.8.0
  @backstage/errors                                     0.2.2
  @backstage/integration-react                          0.1.25
  @backstage/integration                                0.8.0
  @backstage/plugin-api-docs                            0.8.2
  @backstage/plugin-app-backend                         0.3.29
  @backstage/plugin-auth-backend                        0.12.1
  @backstage/plugin-auth-node                           0.1.5
  @backstage/plugin-catalog-backend-module-bitbucket    0.1.0
  @backstage/plugin-catalog-backend                     0.24.0
  @backstage/plugin-catalog-common                      0.2.2
  @backstage/plugin-catalog-graph                       0.2.14
  @backstage/plugin-catalog-import                      0.8.5
  @backstage/plugin-catalog-react                       0.8.1, 0.9.0
  @backstage/plugin-catalog                             0.10.0
  @backstage/plugin-github-actions                      0.5.2
  @backstage/plugin-jenkins-backend                     0.1.18
  @backstage/plugin-jenkins-common                      0.1.1
  @backstage/plugin-jenkins                             0.7.1
  @backstage/plugin-kubernetes-backend                  0.4.12
  @backstage/plugin-kubernetes-common                   0.2.7
  @backstage/plugin-kubernetes                          0.6.2
  @backstage/plugin-org                                 0.5.2
  @backstage/plugin-permission-common                   0.5.2
  @backstage/plugin-permission-node                     0.5.4
  @backstage/plugin-permission-react                    0.3.3
  @backstage/plugin-proxy-backend                       0.2.23
  @backstage/plugin-scaffolder-backend                  0.18.0
  @backstage/plugin-scaffolder-common                   0.3.0
  @backstage/plugin-scaffolder                          0.15.0
  @backstage/plugin-search-backend-node                 0.5.1
  @backstage/plugin-search-backend                      0.4.7
  @backstage/plugin-search-common                       0.3.1
  @backstage/plugin-search                              0.7.3
  @backstage/plugin-sonarqube                           0.3.2
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.13
  @backstage/plugin-tech-insights-backend               0.2.9
  @backstage/plugin-tech-insights-common                0.2.3
  @backstage/plugin-tech-insights-node                  0.2.7
  @backstage/plugin-tech-insights                       0.1.12
  @backstage/plugin-tech-radar                          0.5.9
  @backstage/plugin-techdocs-backend                    0.14.2
  @backstage/plugin-techdocs-node                       0.11.12
  @backstage/plugin-techdocs                            0.15.1
  @backstage/plugin-user-settings                       0.4.1
  @backstage/release-manifests                          0.0.2
  @backstage/search-common                              0.3.1
  @backstage/test-utils                                 0.3.0
  @backstage/theme                                      0.2.15
  @backstage/types                                      0.1.3
  @backstage/version-bridge                             0.1.2

```

**Comment by yarodinD** [comment]
Jenkins backend iterates over the actions array in several places and there's no null check in place, causing the error and disrupting the backend so that no jobs are shown, even if there are other jobs in the same jenkins folder which are not affected.

**Comment by yarodinD** [comment]
Here is the diff with the proposed solution:
```
diff --git a/plugins/jenkins-backend/src/service/jenkinsApi.ts b/plugins/jenkins-backend/src/service/jenkinsApi.ts
index da16bbc553..c42051af84 100644
--- a/plugins/jenkins-backend/src/service/jenkinsApi.ts
+++ b/plugins/jenkins-backend/src/service/jenkinsApi.ts
@@ -14,9 +14,9 @@
  * limitations under the License.
  */
 
-import type { JenkinsInfo } from './jenkinsInfoProvider';
+import { JenkinsInfo } from './jenkinsInfoProvider';
 import jenkins from 'jenkins';
-import type {
+import {
   BackstageBuild,
   BackstageProject,
   JenkinsBuild,
@@ -211,7 +211,7 @@ export class JenkinsApiImpl {
       build.actions
         .filter(
           (action: any) =>
-            action._class === 'hudson.plugins.git.util.BuildData',
+            action?._class === 'hudson.plugins.git.util.BuildData',
         )
         .map((action: any) => {
           const [first]: any = Object.values(action.buildsByBranchName);
@@ -253,7 +253,7 @@ export class JenkinsApiImpl {
     const scmInfo: ScmDetails | undefined = project.actions
       .filter(
         (action: any) =>
-          action._class === 'jenkins.scm.api.metadata.ObjectMetadataAction',
+          action?._class === 'jenkins.scm.api.metadata.ObjectMetadataAction',
       )
       .map((action: any) => {
         return {
@@ -272,7 +272,7 @@ export class JenkinsApiImpl {
     const author = project.actions
       .filter(
         (action: any) =>
-          action._class ===
+          action?._class ===
           'jenkins.scm.api.metadata.ContributorMetadataAction',
       )
       .map((action: any) => {
@@ -287,7 +287,9 @@ export class JenkinsApiImpl {
     return scmInfo;
   }
 
-  private getTestReport(build: JenkinsBuild): {
+  private getTestReport(
+    build: JenkinsBuild,
+  ): {
     total: number;
     passed: number;
     skipped: number;
@@ -297,7 +299,7 @@ export class JenkinsApiImpl {
     return build.actions
       .filter(
         (action: any) =>
-          action._class === 'hudson.tasks.junit.TestResultAction',
+          action?._class === 'hudson.tasks.junit.TestResultAction',
       )
       .map((action: any) => {
         return {
```

**Comment by yarodinD** [comment]
An upgrade to Jenkins 2.332.1 didn't solve the problem, either.

**Comment by freben** [comment]
Oh wow, that response shape looks terrible, what a mixed bag.

We'd love to get help addressing those null checks - we the maintainers don't have a test bed for jenkins so we'd be running a bit blind in trying to address all places where the problem might crop up. Contributions would be super welcome, and we are happy to review and try to push them through afterwards.

**Comment by yarodinD** [comment]
@freben as you see in the diff, I added a simple null pointer check. I even created a changeset on my local machine, including tests. However, I can't seem to create a branch on the repository, hence I can't create a pull request.
Can you help me out here?

**Comment by jhaals** [comment]
@yarodinD you need to [fork the repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and then create a pull request towards the backstage.

**Comment by yarodinD** [comment]
PR with fix was merged: https://github.com/backstage/backstage/pull/10455
