### ISSUE TITLE
Error when registering a component from a self-hosted BitBucket instance

### ISSUE THREAD

**Issue by benader1** [backstage/backstage#10280]
## Expected Behavior

Component successfully imported.

## Actual Behavior

As in screen shot (Screenshot 2022-03-17 at 14.35.28)

{"error":{"name":"Error","message":"Error: Unable to read url, NotAllowedError: Reading from 'https://stash.trusted/.<organisation-name>.com:7990/projects/OP/repos/ovn_lineage/browse/catalog-info.yaml' is not allowed","level":"error","service":"backstage"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":500}}

## Steps to Reproduce

1. Create catalog-info.yaml with content as in screen shot (Screenshot 2022-03-17 at 14.36.59) at a BitBucket repo root level.

2. Open Backstage UI; Create menu option; Register a new component and then enter the full BitBucket link to the catalog-info.yaml created in step 1 earlier.

3. Click on Analyse

## Your environment

Output of yarn backstage-cli info:

yarn run v1.22.17

$ /root/backstageapp/node_modules/.bin/backstage-cli info

OS: Linux 3.10.0-1160.49.1.el7.x86_64 - linux/x64

node: v14.17.1

yarn: 1.22.17

cli: 0.12.0 (installed)
![image002](https://user-images.githubusercontent.com/45359109/158843663-354b06b1-dc28-44e9-9372-46b149d2bae3.png)
![image001](https://user-images.githubusercontent.com/45359109/158843668-1fb75cc8-4512-45a5-9247-2dd2be1556df.png)

**Comment by benader1** [comment]
we are using Atlassian Bitbucket v7.15.3

Error log from the server where Backstage is hosted: 

[1] 2022-03-17T17:31:48.203Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/tests-api

[1] 2022-03-17T17:32:10.186Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/mcfs-api

[1] 2022-03-17T17:32:10.222Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/a2-api

[1] 2022-03-17T17:32:10.224Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/e2-api

[1] 2022-03-17T17:32:10.225Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/ex-api

[1] 2022-03-17T17:32:12.177Z catalog warn Policy check failed; caused by Error: Malformed envelope, /metadata/description should be string type=plugin entity=api:default/merchantcentralfileinterface-api

[1] 2022-03-17T17:32:12.178Z catalog warn Policy check failed; caused by Error: Malformed envelope, /metadata/description should be string type=plugin entity=api:default/merchantcentralfile-api

[1] 2022-03-17T17:32:19.176Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/aerospike-api

[1] 2022-03-17T17:32:24.198Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/lifecycleinfo-api

[1] 2022-03-17T17:32:25.164Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/activity-api

[1] 2022-03-17T17:32:35.169Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/st-api

[1] 2022-03-17T17:32:41.234Z backstage error Error: Unable to read url, NotAllowedError: Reading from 'https://stash.trusted.visa.com:7990/projects/OP/repos/ovn_lineage/browse/catalog-info.yaml' is not allowed type=errorHandler stack=Error: Error: Unable to read url, NotAllowedError: Reading from 'https://stash.trusted.visa.com:7990/projects/OP/repos/ovn_lineage/browse/catalog-info.yaml' is not allowed

[1]     at DefaultLocationService.processEntities (/root/backstageapp/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3490:15)

[1]     at async DefaultLocationService.dryRunCreateLocation (/root/backstageapp/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3519:22)

[1]     at async /root/backstageapp/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:2665:22

[1] 2022-03-17T17:32:41.237Z backstage info ::ffff:10.170.164.165 - - [17/Mar/2022:17:32:41 +0000] "POST /api/catalog/locations?dryRun=true HTTP/1.1" 500 330 "http://sl73ovapd072.visa.com:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36" type=incomingRequest

[1] 2022-03-17T17:32:53.164Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/main-api

[1] 2022-03-17T17:32:53.165Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/testing-api

[1] 2022-03-17T17:33:04.170Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec/definition should NOT have fewer than 1 characters - limit: 1 type=plugin entity=api:default/wsinfo-api

[1] 2022-03-17T17:33:20.077Z catalog warn Detected conflicting entityRef api:default/accountlevelprocessing-api already referenced by url:http://stash.trusted.visa.com/projects/OP/repos/ovn_backstageapp/browse/deployment/apis/api-AccountLevelProcessing.yaml and now also url:http://stash.trusted.visa.com/projects/OP/repos/ovn_backstageapp/browse/deployment/apis/api-visa.com-ovn-components-dataaccess-datastores-accountlevelprocessing.yaml type=plugin

[1] 2022-03-17T17:33:20.080Z catalog warn Detected conflicting entityRef

**Comment by pjungermann** [comment]
As of 
```
[1] 2022-03-17T17:32:41.234Z backstage error Error: Unable to read url, NotAllowedError: Reading from 'https://stash.trusted.visa.com:7990/projects/OP/repos/ovn_lineage/browse/catalog-info.yaml' is not allowed type=errorHandler stack=Error: Error: Unable to read url, NotAllowedError: Reading from 'https://stash.trusted.visa.com:7990/projects/OP/repos/ovn_lineage/browse/catalog-info.yaml' is not allowed
```
you seem to receive a 401 from the API.

Unfortunately, there is not more information in the logs

It fails at https://github.com/Bonial-International-GmbH/backstage/blob/31436ffcadc7d319cccd31d6c895594ac506f239/packages/backend-common/src/reading/BitbucketUrlReader.ts
https://github.com/backstage/backstage/blob/31436ffcadc7d319cccd31d6c895594ac506f239/packages/backend-common/src/reading/BitbucketUrlReader.ts#L103

Can you recheck your integration config? And/or share it obscured?

**Comment by pjungermann** [comment]
@benader1 This is not your config (app-config.yaml), but the config schema

**Comment by benader1** [comment]
@pjungermann - sure thanks. I am now posting the content of app-config.yaml.

Cat app-config.yaml

app:
  title: Scaffolded Backstage App
  baseUrl: http://<backstage-app-host>:3000

organization:
  name: <My Org Name>

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See backend-to-backend-auth.md in the docs for information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://<backstage-app-host>:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    img-src:
      # "'self'" and 'data' are from the backstage default but must be set since img-src is overriden
      - "'self'"
      - 'data:'
      # Allow your Jira instance for @roadiehq/backstage-plugin-jira
      - 'https://<jira-base-url>/‘
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://<backstage-app-host>:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: sqlite3
    connection: ':memory:'
  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  bitbucket:
    - host: <stash-base-url>
      token: <token-value>
      username: <user-id>
      apiBaseUrl: https://<stash-base-url>/rest/api/1.0
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}

proxy:
  '/sonarqube':
    secure: false
    target: https://<sonarqube-base-url>/api
    allowedMethods: ['GET']
    auth: "5f418d3152e7ba2e42b8eb1d15f566f40c092b38:"
  '/test':
    target: 'https://example.com'
    changeOrigin: true

sonarQube:
  baseUrl: https://<sonarqube-base-url>

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  requestUrl: http://localhost:7000/api/techdocs
  storageUrl: http://localhost:7000/api/techdocs/static/docs
  builder: 'external' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'docker'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers: {}

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  locations:
    - type: url
      target: http://<stash-base-url>/projects/OP/repos/ovn_backstageapp/browse/deployment/all-squads.yaml
    - type: url
      target: http://<stash-base-url>/projects/OP/repos/ovn_backstageapp/browse/deployment/all-users.yaml
    - type: url
      target: http://<stash-base-url>/projects/OP/repos/ovn_backstageapp/browse/deployment/all-components.yaml
    - type: url
      target: http://<stash-base-url>/projects/OP/repos/ovn_backstageapp/browse/deployment/all-resources.yaml
    - type: url
      target: http://<stash-base-url>/projects/OP/repos/ovn_backstageapp/browse/deployment/all-systems.yaml
    - type: url
      target: http://<stash-base-url>/projects/OP/repos/ovn_backstageapp/browse/deployment/all-apis.yaml

**Comment by pjungermann** [comment]
hint: code formatting will helps with reading.

It was also only about the integrations part, not all the config is relevant ;-) 

As of (not sure if the formatting is the same/correct as it is impossible to see this from your comment):
```
integrations:
  bitbucket:
    - host:
      token:
      username:
      apiBaseUrl: https:///rest/api/1.0
```
-> Is not properly set up.

**Comment by dmdeepkp** [comment]
[commenting on behalf of Raj] . This is current bitbucket config with actual user and token obviously.

integrations:
  bitbucket:
    - host: stash.trusted.visa.com
      username: myuser
      token: hdhdjjdjdjjdjdjdjjdjdhfhdjjdj
      apiBaseUrl: https://stash.trusted.visa.com/rest/api/1.0

**Comment by pjungermann** [comment]
@dmdeepkp I assume the indentation is correct (not visible without code formatting)

The host is missing the port though. Same for the apiBaseUrl. At least judging from the URL used at the original description above.

I think it needs to be

```
host: stash.trusted.visa.com:7990
apiBaseUrl: https://stash.trusted.visa.com:7990/rest/api/1.0
```

**Comment by benader1** [comment]
Thanks a lot @pjungermann. Let us check those details. btw. apologies for not sending the info in a useful format and state. we are bounded by some corporate restrictions and not always able to share everything that we would have liked to and in the format (like attachment etc). Appreciate your help so far.

**Comment by benader1** [comment]
@pjungermann  - As such without even that port number, the BitBucket integration is currently working. The following lines from app-config are able to show up the list of all catalog items in the UI.

catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  locations:
    - type: url
      target: http://stash.trusted.visa.com/projects/OP/repos/ovn_backstageapp/browse/deployment/all-squads.yaml
    - type: url
      target: http://stash.trusted.visa.com/projects/OP/repos/ovn_backstageapp/browse/deployment/all-users.yaml
    - type: url
      target: http://stash.trusted.visa.com/projects/OP/repos/ovn_backstageapp/browse/deployment/all-components.yaml
    - type: url
      target: http://stash.trusted.visa.com/projects/OP/repos/ovn_backstageapp/browse/deployment/all-resources.yaml
    - type: url
      target: http://stash.trusted.visa.com/projects/OP/repos/ovn_backstageapp/browse/deployment/all-systems.yaml
    - type: url
      target: http://stash.trusted.visa.com/projects/OP/repos/ovn_backstageapp/browse/deployment/all-apis.yaml

However, when we tried after adding port number, it broke the integration and none of the above catalog items showed up in the UI

**Comment by pjungermann** [comment]
ok. But at the error message you have used an URL *with* port (see your description and screenshots). Maybe that was the mistake and you should have used it *without* port

**Comment by dmdeepkp** [comment]
It worked after removing the port number from the URL used to register component. Thanks a lot.
