### ISSUE TITLE
Backstage container crash reboots when clicked on techdocs

### ISSUE THREAD

**Issue by ldmonkey** [backstage/backstage#10574]
## Expected Behavior

Published techdocs are displayed.

## Actual Behavior

The backstage container (not the pod) crash restarts.

## Steps to Reproduce

1. Click on Docs from the menu on the left.
2. Click on a component whose documentation you'd like to see.

## Context

- Techdocs are generated and published to S3 compatible object storage by a CI/CD pipeline. 
- The documentation shows up correctly when a component is selected and Docs tab is clicked.
- Log data 
```
2022-04-01T13:20:42.300Z backstage info ::ffff:10.42.0.29 - - [01/Apr/2022:13:20:42 +0000] "GET /api/search/query?term=&filters%5Bkind%5D=component&filters%5Bnamespace%5D=default&filters%5Bname%5D=backstage&pageCursor=&types%5B0%5D=techdocs HTTP/1.1" 200 14 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36" type=incomingRequest
/app/node_modules/@backstage/errors/dist/index.cjs.js:29
    throw new Error(`Encountered error object without a message, got '${value}'`);
          ^

Error: Encountered error object without a message, got 'NoSuchKey: null'
    at Object.assertError (/app/node_modules/@backstage/errors/dist/index.cjs.js:29:11)
    at /app/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:770:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Your Environment

Backstage is deployed in a kubernetes cluster.
Requests:{"cpu":"500m","memory":"2Gi"}
Limits:{"cpu":"8","memory":"2Gi"}

- Browser Information: 
Google Chrome - Version 100.0.4896.60 (Official Build) (x86_64)

- Output of `yarn backstage-cli info`: 
```
OS:   Darwin 21.1.0 - darwin/x64
node: v14.17.6
yarn: 1.22.17
cli:  0.16.0 (installed)

Dependencies:
  @backstage/app-defaults                            1.0.0
  @backstage/backend-common                          0.13.1
  @backstage/backend-tasks                           0.2.1
  @backstage/catalog-client                          1.0.0
  @backstage/catalog-model                           1.0.0
  @backstage/cli-common                              0.1.8
  @backstage/cli                                     0.16.0
  @backstage/config-loader                           1.0.0
  @backstage/config                                  1.0.0
  @backstage/core-app-api                            1.0.0
  @backstage/core-components                         0.9.2
  @backstage/core-plugin-api                         1.0.0
  @backstage/errors                                  1.0.0
  @backstage/integration-react                       1.0.0
  @backstage/integration                             1.0.0
  @backstage/plugin-api-docs                         0.8.3
  @backstage/plugin-app-backend                      0.3.30
  @backstage/plugin-auth-backend                     0.12.3
  @backstage/plugin-auth-node                        0.1.6
  @backstage/plugin-catalog-backend-module-bitbucket 0.1.1
  @backstage/plugin-catalog-backend-module-ldap      0.4.1
  @backstage/plugin-catalog-backend                  1.0.0
  @backstage/plugin-catalog-common                   1.0.0
  @backstage/plugin-catalog-graph                    0.2.15
  @backstage/plugin-catalog-import                   0.8.6
  @backstage/plugin-catalog-react                    1.0.0
  @backstage/plugin-catalog                          1.0.0
  @backstage/plugin-github-actions                   0.5.3
  @backstage/plugin-org                              0.5.3
  @backstage/plugin-permission-common                0.5.3
  @backstage/plugin-permission-node                  0.5.5
  @backstage/plugin-permission-react                 0.3.4
  @backstage/plugin-proxy-backend                    0.2.24
  @backstage/plugin-scaffolder-backend               1.0.0
  @backstage/plugin-scaffolder-common                1.0.0
  @backstage/plugin-scaffolder                       1.0.0
  @backstage/plugin-search-backend-node              0.5.2
  @backstage/plugin-search-backend                   0.4.8
  @backstage/plugin-search-common                    0.3.2
  @backstage/plugin-search                           0.7.4
  @backstage/plugin-sonarqube                        0.3.3
  @backstage/plugin-tech-radar                       0.5.10
  @backstage/plugin-techdocs-backend                 1.0.0
  @backstage/plugin-techdocs-node                    1.0.0
  @backstage/plugin-techdocs                         1.0.0
  @backstage/plugin-user-settings                    0.4.2
  @backstage/release-manifests                       0.0.2
  @backstage/search-common                           0.3.2
  @backstage/test-utils                              1.0.0
  @backstage/theme                                   0.2.15
  @backstage/types                                   1.0.0
  @backstage/version-bridge                          1.0.0
```

**Comment by garyniemen** [comment]
@idmonkey are you still having this problem?

**Comment by ldmonkey** [comment]
Yes, this is still a problem for us. We are currently in an Backstage evaluation phase and we've put it on hold until we can fix it.

**Comment by soapraj** [comment]
Hi! @idmonkey - do you see any more warn/debug/error logs after this line `Error: Encountered error object without a message, got 'NoSuchKey: null'`? Would you be able to post some more log lines before and after?

**Comment by ldmonkey** [comment]
hi @soapraj,
After this message the container crashes and there are no more logs. Here are some log messages before this happens.
```
2022-05-10T09:19:00.570Z backstage info ::ffff:10.42.7.242 - - [10/May/2022:09:19:00 +0000] "GET /api/techdocs/sync/default/component/backstage HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
2022-05-10T09:19:00.572Z backstage info ::ffff:10.42.6.123 - - [10/May/2022:09:19:00 +0000] "GET /api/techdocs/metadata/entity/default/component/backstage HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
2022-05-10T09:19:00.607Z backstage info ::ffff:10.42.0.189 - - [10/May/2022:09:19:00 +0000] "GET /api/techdocs/static/docs/default/component/backstage/index.html HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
2022-05-10T09:19:00.715Z backstage info ::ffff:10.42.7.242 - - [10/May/2022:09:19:00 +0000] "GET /api/techdocs/static/docs/default/component/backstage/assets/stylesheets/main.fe0cca5b.min.css HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
2022-05-10T09:19:00.730Z search info Search request received: term="", filters={"kind":"component","namespace":"default","name":"backstage"}, types=techdocs, pageCursor= type=plugin
2022-05-10T09:19:00.740Z backstage info ::ffff:10.42.0.189 - - [10/May/2022:09:19:00 +0000] "GET /api/search/query?term=&filters%5Bkind%5D=component&filters%5Bnamespace%5D=default&filters%5Bname%5D=backstage&pageCursor=&types%5B0%5D=techdocs HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
/app/node_modules/@backstage/errors/dist/index.cjs.js:29
    throw new Error(`Encountered error object without a message, got '${value}'`);
          ^

Error: Encountered error object without a message, got 'NoSuchKey: null'
    at Object.assertError (/app/node_modules/@backstage/errors/dist/index.cjs.js:29:11)
    at /app/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:770:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by garyniemen** [comment]
@camilaibs are you able to follow on here

**Comment by manuelstein** [comment]
I'm seeing the same problem with these versions.
```
  @backstage/plugin-techdocs-backend                    1.1.2
  @backstage/plugin-techdocs-module-addons-contrib      1.0.1
  @backstage/plugin-techdocs-node                       1.1.2
  @backstage/plugin-techdocs-react                      1.0.1
  @backstage/plugin-techdocs                            1.2.0
```

It seems that the S3 library is the origin of the [NoSuchKey error](https://aws.amazon.com/premiumsupport/knowledge-center/404-error-nosuchkey-s3/) and maybe it's just not being caught properly.

Here's the try clause from which the 'malformed error' comes:
https://github.com/backstage/backstage/blob/b473f8f8feeda229ec2491d31b3b2176b9e78dd9/plugins/techdocs-node/src/stages/publish/awsS3.ts#L342-L355

And I'm suspecting it's not treated correctly in 'streamToBuffer': https://github.com/backstage/backstage/blob/b473f8f8feeda229ec2491d31b3b2176b9e78dd9/plugins/techdocs-node/src/stages/publish/awsS3.ts#L47-L58

Could it be the `on('error', ...)` line?

**Comment by manuelstein** [comment]
Unfortunately I don't know how to test a fix. I've copied `techdocs-node` into my `plugins/` folder, applied what I think fixes it, but when I run `yarn workspace backend start --config ../../dev/app-config.yaml`, the build succeeds and then it complains `
```
/app/plugins/techdocs-node/src/index.ts:23
export * from './stages';
^^^^^^
```

**Comment by manuelstein** [comment]
Ok, I've put both techdocs-node and techdocs-backend in my plugin path and was able to at least cover the "Encountered error with no message", but the container is still dying.

**Comment by manuelstein** [comment]
@benjdlambert has this become stale because the fix is already in?

**Comment by benjdlambert** [comment]
No apologies, I marked this as `stale` accidentally by the looks of things. Too many tabs open 😱

**Comment by garyniemen** [comment]
@camilaibs Another one for your PR review list - if you have time
