### ISSUE TITLE
Issue with /catalog-import and the newly refactored Bitbucket Cloud Integration 

### ISSUE THREAD

**Issue by msperrin** [backstage/backstage#11700]
In 1.2.0 the Bitbucket integration was refactored into separate integrations between Bitbucket Cloud and Bitbucket Server. During testing after upgrading and changing the values in app-config.yaml an error is encountered on the /catalog-import page. 

We believe this is because on the page the integrations are usually loaded by the host value of the integration. As the Bitbucket Cloud integration does not specify a host, it is not detected when making a call to config reader. If Bitbucket Cloud is the only integration configured the below error is displayed. Note that having any other integration with a host works, including the old Bitbucket and Github integrations - this can be used as a work around.

## Expected Behaviour

The page loads without error.

## Actual Behaviour

Error is displayed:

![Capture](https://user-images.githubusercontent.com/12173161/170794840-c52a4280-94c4-402e-b9f8-c8d52e1f722d.PNG)

Message
Missing required config value at 'integrations'

Stack Trace
Error: Missing required config value at 'integrations'
    at ConfigReader.getConfig (webpack-internal:///../../node_modules/@backstage/config/dist/index.esm.js:109:13)
    at ImportInfoCard (webpack-internal:///../../node_modules/@backstage/plugin-catalog-import/dist/index.esm.js:405:34)
    at renderWithHooks (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:14986:18)
    at mountIndeterminateComponent (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:17812:13)
    at beginWork (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:19050:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:3946:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:3995:16)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:4057:31)
    at beginWork$1 (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:23960:7)
    at performUnitOfWork (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:22775:12)

With only Bitbucket Cloud integration configured, ConfigReader cannot see the integration:

this: ConfigReader
key: "integrations"
parts: ['integrations']
value:
app: {title: 'Scaffolded Backstage App', baseUrl: 'http://localhost:3000'}
backend: {baseUrl: 'http://localhost:7007'}
catalog: {import: {…}}
organization: {name: 'My Company'}
techdocs: {builder: 'local'}
[[Prototype]]: Object

Compared to having both Github and Bitbucket Cloud integration configured:

configApi: ConfigReader
context: "app-config.yaml"
data:
app: {title: 'Scaffolded Backstage App', baseUrl: 'http://localhost:3000'}
backend: {baseUrl: 'http://localhost:7007'}
catalog: {import: {…}}
integrations:
github: Array(1)
0: {host: 'github.com'}
length: 1
[[Prototype]]: Array(0)
[[Prototype]]: Object
organization: {name: 'My Company'}
techdocs: {builder: 'local'}
[[Prototype]]: Object

## Steps to Reproduce

1. Scaffold a new Backstage instance using create-app.
2. Add configuration as per the Bitbucket Cloud integration docs and comment out the GitHub integration.
3. Generate an app Password and pass this values as normal via env vars.
4. Run yarn && yarn dev
5. attempt to access the /catalog-import endpoint, the error will be displayed.
6. Uncomment the Github Integration configuration and restart Backstage.
7. /catalog-import will now load correctly.

## Context

This occurred for us after performing upgrading steps from 1.0.1 to 1.2.0 and running local dev.

**Comment by benjdlambert** [comment]
@pjungermann do you have any idea here?

**Comment by pjungermann** [comment]
@benjdlambert feel free to assign the issue to me

**Comment by Hanyman8** [comment]
We had the same issue with `bitbucketCloud` integration and adding empty github integration helped for now, thanks

**Comment by pjungermann** [comment]
@msperrin @Hanyman8 Do you use any entity processor or entity provider for ingesting entities from Bitbucket Cloud? Or only manual via catalog import?

**Comment by msperrin** [comment]
@Hanyman8 Same here, still manual import at this point.

**Comment by pjungermann** [comment]
I found an easy way to solve this. I will create a PR later today.

**Comment by pjungermann** [comment]
or even two improvements which both would fix it. I will link both to this issue.
