### ISSUE TITLE
[TechDocs] Images not rendered consistently from docs and entity page

### ISSUE THREAD

**Issue by ivangonzalezacuna** [backstage/backstage#12000]
## Expected Behavior

When adding some docs, you might need to insert images on it and be rendered by the techdocs package used by backstage.

## Actual Behavior

After an strange behavior we noticed in our company, I did a couple tests, and I found a misleading behavior depending if the docs are loaded from the docs page (`/docs`), or from the entity page (`/{entity}/docs)`. 

## Steps to Reproduce

1. Inside your `/docs` folder, add an image whose name has white spaces on it, like `image with spaces.jpg`, and another one withour white spaces.
2. In your `index.md` add the following lines:
    ```
      Image without formatting:
      ![image with spaces](./image with spaces.png)

      Image with formatting:
      ![image with spaces formatted](./image%20with%20spaces.png)

      Image without spacing:
      ![image without spacing](./image_without_spaces.png)
    ```
3. When the new documentation is loaded. Go to the docs page and open your new docs. The 3 images are displayed as expected.
4. Now open the entity page and navigate to the docs. In that case, only the last image (the one without white spaces) is loaded successfully.

In these 2 screenshot you can see what we get in each case:

* First, the output when using the docs from the sidebar (as the images are big, you can only see the first one. The order is the same as described in the step 2):
![Screenshot from 2022-06-13 15-03-31](https://user-images.githubusercontent.com/49096359/173360162-ca97aba0-4f9a-4eeb-9ce7-704f639a6034.png)
* And then, from inside the entity page (as you can see, only the one without spaces in the name is rendered properly):
![Screenshot from 2022-06-13 15-03-45](https://user-images.githubusercontent.com/49096359/173360358-372813ee-a63c-4563-8edf-7ba1f5409f68.png)

## Context

Logs when opening the docs tab inside the EntityPage:
```bash
2022-06-13T12:54:13.905Z backstage info GET /api/techdocs/static/docs/default/Component/backstage-empty-project-wizard-test/assets/stylesheets/palette.e6a45f82.min.css 304 type=request status=[object Object] request=[object Object] timings=[object Object] tracing=[object Object]
2022-06-13T12:54:13.913Z backstage info GET /api/techdocs/static/docs/default/Component/backstage-empty-project-wizard-test/image_without_spaces.png 304 type=request status=[object Object] request=[object Object] timings=[object Object] tracing=[object Object]
2022-06-13T12:54:13.914Z backstage info GET /api/techdocs/static/docs/default/Component/backstage-empty-project-wizard-test/assets/stylesheets/main.50e68009.min.css 304 type=request status=[object Object] request=[object Object] timings=[object Object] tracing=[object Object]
2022-06-13T12:54:14.018Z backstage error Encountered error object without a message, got 'InvalidAccessKeyId: null' type=errorHandler stack=Error: Encountered error object without a message, got 'InvalidAccessKeyId: null'
    at Object.assertError (/app/node_modules/@backstage/errors/dist/index.cjs.js:29:11)
    at /app/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:808:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-06-13T12:54:14.019Z backstage info GET /api/techdocs/static/docs/default/Component/backstage-empty-project-wizard-test/image%2520with%2520spaces.png 500 type=request status=[object Object] request=[object Object] timings=[object Object] tracing=[object Object]
```

When accessing via the Docs, no logs are displayed in `info` mode.

## Your Environment

- Browser Information: Mozilla Firefox 100.0.2 (64-bit)

- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.19
$ /home/ivgo/backstage/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.16.2-051602-generic - linux/x64
node: v16.14.2
yarn: 1.22.19
cli:  0.17.1 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.2
  @backstage/backend-common                        0.13.5
  @backstage/backend-tasks                         0.3.1
  @backstage/backend-test-utils                    0.1.24
  @backstage/catalog-client                        1.0.2
  @backstage/catalog-model                         1.0.2
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.17.1
  @backstage/config-loader                         1.1.1
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.2
  @backstage/core-components                       0.9.4
  @backstage/core-plugin-api                       1.0.2
  @backstage/dev-utils                             1.0.2
  @backstage/errors                                1.0.0
  @backstage/integration-react                     1.1.0
  @backstage/integration                           1.2.0
  @backstage/plugin-api-docs                       0.8.5
  @backstage/plugin-app-backend                    0.3.32
  @backstage/plugin-auth-backend                   0.14.0
  @backstage/plugin-auth-node                      0.2.1
  @backstage/plugin-catalog-backend-module-gitlab  0.1.3
  @backstage/plugin-catalog-backend-module-ldap    0.4.3
  @backstage/plugin-catalog-backend                1.1.2
  @backstage/plugin-catalog-common                 1.0.2
  @backstage/plugin-catalog-graph                  0.2.17
  @backstage/plugin-catalog-import                 0.8.8
  @backstage/plugin-catalog-react                  1.1.0
  @backstage/plugin-catalog                        1.2.0
  @backstage/plugin-github-actions                 0.5.5
  @backstage/plugin-home                           0.4.21
  @backstage/plugin-kubernetes-backend             0.5.1
  @backstage/plugin-kubernetes-common              0.2.10
  @backstage/plugin-kubernetes                     0.6.5
  @backstage/plugin-org                            0.5.5
  @backstage/plugin-permission-backend             0.5.7
  @backstage/plugin-permission-common              0.6.1
  @backstage/plugin-permission-node                0.6.1
  @backstage/plugin-permission-react               0.4.1
  @backstage/plugin-proxy-backend                  0.2.26
  @backstage/plugin-scaffolder-backend             1.2.0
  @backstage/plugin-scaffolder-common              1.1.0
  @backstage/plugin-scaffolder                     1.2.0
  @backstage/plugin-search-backend-node            0.6.1
  @backstage/plugin-search-backend                 0.5.2
  @backstage/plugin-search-common                  0.3.4
  @backstage/plugin-search-react                   0.2.0
  @backstage/plugin-search                         0.8.1
  @backstage/plugin-stack-overflow                 0.1.1
  @backstage/plugin-techdocs-backend               1.1.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.0
  @backstage/plugin-techdocs-node                  1.1.1
  @backstage/plugin-techdocs-react                 1.0.0
  @backstage/plugin-techdocs                       1.1.1
  @backstage/plugin-user-settings                  0.4.4
  @backstage/release-manifests                     0.0.3
  @backstage/search-common                         0.3.4
  @backstage/test-utils                            1.1.0
  @backstage/theme                                 0.2.15
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 0.60s.
```

**Comment by ivangonzalezacuna** [comment]
Just updated to backstage 1.3.0, now this issue seems to be solved, so I'm closing it.
