### ISSUE TITLE
Failed to load template, ResponseError: Request failed with 500 TypeError

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#12208]
## Expected Behavior

Clicking choose on the template screen should bring you to a parameter entry screen.

## Actual Behavior

An error is shown at the top of the screen "Failed to load template, ResponseError: Request failed with 500 TypeError"

<img width="925" alt="image" src="https://user-images.githubusercontent.com/553697/174968995-24ffaf7c-51e1-4ec0-9146-835418444421.png">

The body of the parameter-schema api call is:

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at parseBearerToken (/usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:3905:37)
    at /usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:3674:23
    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7
    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:15
    at param (/usr/src/app/node_modules/express/lib/router/index.js:365:14)
    at param (/usr/src/app/node_modules/express/lib/router/index.js:376:14)
    at param (/usr/src/app/node_modules/express/lib/router/index.js:376:14)
    at param (/usr/src/app/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:421:3)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:110:7)
    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at jsonParser (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)
```

## Steps to Reproduce

- Start version 1.3.0 of the scaffolder-backend plugin with the backstage backend.
- Load any template into the catalog
- `curl http://localhost:7009/api/scaffolder/v2/templates/default/template/hello-world-template/parameter-schema -H "Authorization: bearer $(uuidgen)"`
- You should not see a 500 error

## Context

The scaffolder is making some assumptions about how the request is authenticated:

- there is a token set on bearer type authorization header
- the token is a jwt token
- the jwt token can be trusted at face value without checking the signature

We provide two backend authentication mechanisms, neither is in the jwt format.

## Your Environment

At this point I think the issue is located in one backend package: Version 1.3.0 of the `@backstage/plugin-scaffolder-backend`.

**Comment by punkle** [comment]
I have provided two different options that would fix this issue for us. Both rely on injecting a function to parse the token from the request. One change is more sophisticated. The other is more minimal.

**Comment by punkle** [comment]
Can I ask, where is the JWT token generated and is it correct to assume it is JWT? I am wondering if we are doing something wrong?

**Comment by freben** [comment]
We use the `Authorization` header to pass the Backstage token from frontend to backend. This is a general mechanism and happens in a lot of places - in the future hopefully all the places. :) Some do it manually by getting the token from the identityApi, some use the fetchApi which does this automatically behind the scenes. What you see here is the scaffolder expecting to receive that token and to decode it to find who you are, and querying the catalog for more contextual information about you.

As part of the backend system work that's ongoing, we may consider making the mechanism configurable of how the Backstage token is conveyed. There was some discussion way back, on whether the use of the Authorization header would constitute a collision risk, vs picking for example an entirely custom header or a different mechanism. Well as you see, Authorization won for the time being.

And yes it's a JWT that's issued by the sign-in resolvers in auth-backend. It's up to the adopter to choose whether to _verify_ incoming Backstage tokens against the auth-backend, preferably at the very top of their express chains - every single plugin is not meant to need to do the whole auth dance themselves.

How come that you are using this header in particular?

**Comment by punkle** [comment]
I think that we are not doing much different here. The token is negotiated by the frontend with the IDP and set in a cookie and that token is passed to the backend via the Authorization header. I think the differences is that our token is not a JWT encoded token.

I think I might not be understanding your question correctly because my answer seems a bit simplistic. Let me know if I am getting the wrong end of the stick.

**Comment by punkle** [comment]
I spoke with @freben and we have a way forward on this. Closing for the moment.
