### ISSUE TITLE
Can't sign-in after using 'Authenticate API requests'

### ISSUE THREAD

**Issue by tonyhsuclrous** [backstage/backstage#12673]
## Expected Behavior

I'm following the tutorial [Authenticate API requests](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md).

After inserting codes into my app and backend, I can't sign-in with google auth provider. It works fine before.

The sign-in page shows `Request failed with 401 Error`
```
{"error":{"name":"AuthenticationError","message":"Invalid X-Requested-With header"},"request":{"method":"GET","url":"/api/auth/google/refresh?optional&env=development"},"response":{"statusCode":401}}
```

`packages/backend/src/index.ts`
```
import Router from 'express-promise-router';
import {
  createServiceBuilder,
  loadBackendConfig,
  getRootLogger,
  useHotMemoize,
  notFoundHandler,
  CacheManager,
  DatabaseManager,
  SingleHostDiscovery,
  UrlReaders,
  ServerTokenManager,
} from '@backstage/backend-common';
import { TaskScheduler } from '@backstage/backend-tasks';
import { Config } from '@backstage/config';
import app from './plugins/app';
import auth from './plugins/auth';
import catalog from './plugins/catalog';
import scaffolder from './plugins/scaffolder';
import proxy from './plugins/proxy';
import techdocs from './plugins/techdocs';
import search from './plugins/search';
import { PluginEnvironment } from './types';
import { ServerPermissionClient } from '@backstage/plugin-permission-node';
import kubernetes from './plugins/kubernetes';
import permission from './plugins/permission';
import cookieParser from 'cookie-parser';
import { Request, Response, NextFunction } from 'express';
import * as JWT from 'jose';
import { URL } from 'url';
import {
  IdentityClient,
  getBearerTokenFromAuthorizationHeader,
} from '@backstage/plugin-auth-node';

function makeCreateEnv(config: Config) {
  const root = getRootLogger();
  const reader = UrlReaders.default({ logger: root, config });
  const discovery = SingleHostDiscovery.fromConfig(config);
  const cacheManager = CacheManager.fromConfig(config);
  const databaseManager = DatabaseManager.fromConfig(config);
  // const tokenManager = ServerTokenManager.noop();
  const tokenManager = ServerTokenManager.fromConfig(config, { logger: root });
  const taskScheduler = TaskScheduler.fromConfig(config);
  const permissions = ServerPermissionClient.fromConfig(config, {
    discovery,
    tokenManager,
  });

  root.info(`Created UrlReader ${reader}`);

  return (plugin: string): PluginEnvironment => {
    const logger = root.child({ type: 'plugin', plugin });
    const database = databaseManager.forPlugin(plugin);
    const cache = cacheManager.forPlugin(plugin);
    const scheduler = taskScheduler.forPlugin(plugin);
    return {
      logger,
      database,
      cache,
      config,
      reader,
      discovery,
      tokenManager,
      scheduler,
      permissions,
    };
  };
}

function setTokenCookie(
  res: Response,
  options: { token: string; secure: boolean; cookieDomain: string },
) {
  try {
    const payload = JWT.decodeJwt(options.token) as object & {
      exp: number;
    };
    res.cookie(`token`, options.token, {
      expires: new Date(payload?.exp ? payload?.exp * 1000 : 0),
      secure: options.secure,
      sameSite: 'lax',
      domain: options.cookieDomain,
      path: '/',
      httpOnly: true,
    });
  } catch (_err) {
    // Ignore
  }
}

async function main() {
  const config = await loadBackendConfig({
    argv: process.argv,
    logger: getRootLogger(),
  });
  const createEnv = makeCreateEnv(config);

  const catalogEnv = useHotMemoize(module, () => createEnv('catalog'));
  const scaffolderEnv = useHotMemoize(module, () => createEnv('scaffolder'));
  const authEnv = useHotMemoize(module, () => createEnv('auth'));
  const proxyEnv = useHotMemoize(module, () => createEnv('proxy'));
  const techdocsEnv = useHotMemoize(module, () => createEnv('techdocs'));
  const searchEnv = useHotMemoize(module, () => createEnv('search'));
  const appEnv = useHotMemoize(module, () => createEnv('app'));
  const kubernetesEnv = useHotMemoize(module, () => createEnv('kubernetes'));
  const permissionEnv = useHotMemoize(module, () => createEnv('permission'));

  const discovery = SingleHostDiscovery.fromConfig(config);
  const identity = IdentityClient.create({
    discovery,
    issuer: await discovery.getExternalBaseUrl('auth'),
  });
  const baseUrl = config.getString('backend.baseUrl');
  const secure = baseUrl.startsWith('https://');
  const cookieDomain = new URL(baseUrl).hostname;
  const authMiddleware = async (
    req: Request,
    res: Response,
    next: NextFunction,
  ) => {
    try {
      const token =
        getBearerTokenFromAuthorizationHeader(req.headers.authorization) ||
        req.cookies['token'];
      req.user = await identity.authenticate(token);
      if (!req.headers.authorization) {
        // Authorization header may be forwarded by plugin requests
        req.headers.authorization = `Bearer ${token}`;
      }
      if (token !== req.cookies['token']) {
        setTokenCookie(res, {
          token,
          secure,
          cookieDomain,
        });
      }
      next();
    } catch (error) {
      res.status(401).send(`Unauthorized`);
    }
  };

  const apiRouter = Router();
  apiRouter.use(cookieParser());
  // The auth route must be publicly available as it is used during login
  apiRouter.use('/auth', await auth(authEnv));
  // Add a simple endpoint to be used when setting a token cookie
  apiRouter.use('/cookie', authMiddleware, (_req, res) => {
    res.status(200).send(`Coming right up`);
  });

  apiRouter.use('/catalog', authMiddleware, await catalog(catalogEnv));
  apiRouter.use('/scaffolder', authMiddleware, await scaffolder(scaffolderEnv));
  apiRouter.use('/techdocs', authMiddleware, await techdocs(techdocsEnv));
  apiRouter.use('/proxy', authMiddleware, await proxy(proxyEnv));
  apiRouter.use('/search', authMiddleware, await search(searchEnv));
  apiRouter.use('/kubernetes', authMiddleware, await kubernetes(kubernetesEnv));
  apiRouter.use('/permission', authMiddleware, await permission(permissionEnv));

  // Add backends ABOVE this line; this 404 handler is the catch-all fallback
  apiRouter.use(authMiddleware, notFoundHandler());

  const service = createServiceBuilder(module)
    .loadConfig(config)
    .addRouter('/api', apiRouter)
    .addRouter('', await app(appEnv));

  await service.start().catch(err => {
    console.log(err);
    process.exit(1);
  });
}

module.hot?.accept();
main().catch(error => {
  console.error(`Backend failed to start up, ${error}`);
  process.exit(1);
});
```

`packages/app/src/App.tsx`
```
import React from 'react';
import { Navigate, Route } from 'react-router';
import { apiDocsPlugin, ApiExplorerPage } from '@backstage/plugin-api-docs';
import {
  CatalogEntityPage,
  CatalogIndexPage,
  catalogPlugin,
} from '@backstage/plugin-catalog';
import {
  CatalogImportPage,
  catalogImportPlugin,
} from '@backstage/plugin-catalog-import';
import { ScaffolderPage, scaffolderPlugin } from '@backstage/plugin-scaffolder';
import { orgPlugin } from '@backstage/plugin-org';
import { SearchPage } from '@backstage/plugin-search';
import { TechRadarPage } from '@backstage/plugin-tech-radar';
import {
  TechDocsIndexPage,
  techdocsPlugin,
  TechDocsReaderPage,
} from '@backstage/plugin-techdocs';
import { TechDocsAddons } from '@backstage/plugin-techdocs-react';
import { ReportIssue } from '@backstage/plugin-techdocs-module-addons-contrib';
import { UserSettingsPage } from '@backstage/plugin-user-settings';
import { apis } from './apis';
import { entityPage } from './components/catalog/EntityPage';
import { searchPage } from './components/search/SearchPage';
import { Root } from './components/Root';

import { AlertDisplay, OAuthRequestDialog } from '@backstage/core-components';
import { createApp } from '@backstage/app-defaults';
import { FlatRoutes } from '@backstage/core-app-api';
import { CatalogGraphPage } from '@backstage/plugin-catalog-graph';
import { PermissionedRoute } from '@backstage/plugin-permission-react';
import { catalogEntityCreatePermission } from '@backstage/plugin-catalog-common/alpha';
import { googleAuthApiRef } from '@backstage/core-plugin-api';
import { SignInPage } from '@backstage/core-components';
import { discoveryApiRef, useApi, IdentityApi } from '@backstage/core-plugin-api';

// Parses supplied JWT token and returns the payload
function parseJwt(token: string): { exp: number } {
  const base64Url = token.split('.')[1];
  const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
  const jsonPayload = decodeURIComponent(
    atob(base64)
      .split('')
      .map(function (c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
      })
      .join(''),
  );

  return JSON.parse(jsonPayload);
}

// Returns milliseconds until the supplied JWT token expires
function msUntilExpiry(token: string): number {
  const payload = parseJwt(token);
  const remaining =
    new Date(payload.exp * 1000).getTime() - new Date().getTime();
  return remaining;
}

// Calls the specified url regularly using an auth token to set a token cookie
// to authorize regular HTTP requests when loading techdocs
async function setTokenCookie(url: string, identityApi: IdentityApi) {
  const { token } = await identityApi.getCredentials();
  if (!token) {
    return;
  }

  await fetch(url, {
    mode: 'cors',
    credentials: 'include',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  // Call this function again a few minutes before the token expires
  const ms = msUntilExpiry(token) - 4 * 60 * 1000;
  setTimeout(
    () => {
      setTokenCookie(url, identityApi);
    },
    ms > 0 ? ms : 10000,
  );
}

const app = createApp({
  apis,
  components: {
    SignInPage: props => {
      const discoveryApi = useApi(discoveryApiRef);
      return (
        <SignInPage
          {...props}
          // auto
          provider={{
            id: 'google-auth-provider',
            title: 'Google',
            message: 'Sign in using Google',
            apiRef: googleAuthApiRef,
          }}
          onSignInSuccess={async (identityApi: IdentityApi) => {
            setTokenCookie(
              await discoveryApi.getBaseUrl('cookie'),
              identityApi,
            );

            props.onSignInSuccess(identityApi);
          }}
        />
      );
    },
  },
  bindRoutes({ bind }) {
    bind(catalogPlugin.externalRoutes, {
      createComponent: scaffolderPlugin.routes.root,
      viewTechDoc: techdocsPlugin.routes.docRoot,
    });
    bind(apiDocsPlugin.externalRoutes, {
      registerApi: catalogImportPlugin.routes.importPage,
    });
    bind(scaffolderPlugin.externalRoutes, {
      registerComponent: catalogImportPlugin.routes.importPage,
    });
    bind(orgPlugin.externalRoutes, {
      catalogIndex: catalogPlugin.routes.catalogIndex,
    });
  },
});

const AppProvider = app.getProvider();
const AppRouter = app.getRouter();

const routes = (
  <FlatRoutes>
    <Navigate key="/" to="catalog" />
    <Route path="/catalog" element={<CatalogIndexPage />} />
    <Route
      path="/catalog/:namespace/:kind/:name"
      element={<CatalogEntityPage />}
    >
      {entityPage}
    </Route>
    <Route path="/docs" element={<TechDocsIndexPage />} />
    <Route
      path="/docs/:namespace/:kind/:name/*"
      element={<TechDocsReaderPage />}
    >
      <TechDocsAddons>
        <ReportIssue />
      </TechDocsAddons>
    </Route>
    <Route path="/create" element={<ScaffolderPage />} />
    <Route path="/api-docs" element={<ApiExplorerPage />} />
    <Route
      path="/tech-radar"
      element={<TechRadarPage width={1500} height={800} pageTitle={''} />}
    />
    <PermissionedRoute
      path="/catalog-import"
      permission={catalogEntityCreatePermission}
      element={<CatalogImportPage />}
    />
    <Route path="/search" element={<SearchPage />}>
      {searchPage}
    </Route>
    <Route path="/settings" element={<UserSettingsPage />} />
    <Route path="/catalog-graph" element={<CatalogGraphPage />} />
  </FlatRoutes>
);

const App = () => (
  <AppProvider>
    <AlertDisplay />
    <OAuthRequestDialog />
    <AppRouter>
      <Root>{routes}</Root>
    </AppRouter>
  </AppProvider>
);

export default App;
```

## Actual Behavior

As shown above.

## Steps to Reproduce

As shown above.

## Context

This tutorial stop me from setting up backstage permission.

## Your Environment

- Browser Information: 
Google Chrome 103.0.5060.114

- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.19
$ /Users/tepisu/tmp/portal/node_modules/.bin/backstage-cli info
OS:   Darwin 21.5.0 - darwin/arm64
node: v16.15.1
yarn: 1.22.19
cli:  0.17.2 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.3
  @backstage/backend-common                        0.14.0
  @backstage/backend-tasks                         0.3.2
  @backstage/catalog-client                        1.0.3
  @backstage/catalog-model                         1.0.3
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.17.2
  @backstage/config-loader                         1.1.2
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.3
  @backstage/core-components                       0.9.5
  @backstage/core-plugin-api                       1.0.3
  @backstage/errors                                1.0.0
  @backstage/integration-react                     1.1.1
  @backstage/integration                           1.2.1
  @backstage/plugin-api-docs                       0.8.6
  @backstage/plugin-app-backend                    0.3.33
  @backstage/plugin-auth-backend                   0.14.1
  @backstage/plugin-auth-node                      0.2.2
  @backstage/plugin-catalog-backend-module-gitlab  0.1.4
  @backstage/plugin-catalog-backend                1.2.0
  @backstage/plugin-catalog-common                 1.0.3
  @backstage/plugin-catalog-graph                  0.2.18
  @backstage/plugin-catalog-import                 0.8.9
  @backstage/plugin-catalog-react                  1.1.1
  @backstage/plugin-catalog                        1.3.0
  @backstage/plugin-github-actions                 0.5.6
  @backstage/plugin-kubernetes-backend             0.6.0
  @backstage/plugin-kubernetes-common              0.3.0
  @backstage/plugin-kubernetes                     0.6.6
  @backstage/plugin-org                            0.5.6
  @backstage/plugin-permission-backend             0.5.8
  @backstage/plugin-permission-common              0.6.2
  @backstage/plugin-permission-node                0.6.2
  @backstage/plugin-permission-react               0.4.2
  @backstage/plugin-proxy-backend                  0.2.27
  @backstage/plugin-scaffolder-backend             1.3.1
  @backstage/plugin-scaffolder-common              1.1.1
  @backstage/plugin-scaffolder                     1.3.0
  @backstage/plugin-search-backend-module-pg       0.3.4
  @backstage/plugin-search-backend-node            0.6.2
  @backstage/plugin-search-backend                 0.5.3
  @backstage/plugin-search-common                  0.3.5
  @backstage/plugin-search-react                   0.2.1
  @backstage/plugin-search                         0.9.0
  @backstage/plugin-tech-radar                     0.5.13
  @backstage/plugin-techdocs-backend               1.1.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.1
  @backstage/plugin-techdocs-node                  1.1.2
  @backstage/plugin-techdocs-react                 1.0.1
  @backstage/plugin-techdocs                       1.2.0
  @backstage/plugin-user-settings                  0.4.5
  @backstage/release-manifests                     0.0.4
  @backstage/test-utils                            1.1.1
  @backstage/theme                                 0.2.15
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
✨  Done in 1.23s.
```

**Comment by tonyhsuclrous** [comment]
This issue is caused by below sign-in resolver code.

```
      google: providers.google.create({
        signIn: {
          resolver: providers.google.resolvers.emailMatchingUserEntityProfileEmail(),
        },
      }),
```

The resolver needs to query EntityProfileEmail before signing in, which is blocked by the `authMiddleware`.

Any suggestion on how to make a query before sign-in success?

**Comment by tonyhsuclrous** [comment]
Closing due to this is an edge case.

**Comment by rankin-tr** [comment]
I am running into this as well. Is there any guidance for authenticating API requests in conjunction with sign-in resolvers?

**Comment by tonyhsuclrous** [comment]
Bypassing sign-in resolver in the authMiddleware is better than nothing.
```
  const authMiddleware = async (
    req: Request,
    res: Response,
    next: NextFunction,
  ) => {
    try {
      // Bypass signIn: resolver: providers.google.resolvers.emailMatchingUserEntityProfileEmail()
      if (req.url.indexOf('entities?filter=spec.profile.email=') == -1) {
        const token =
          getBearerTokenFromAuthorizationHeader(req.headers.authorization) ||
          req.cookies['token'];

        req.user = await identity.authenticate(token);
```

**Comment by freben** [comment]
> Invalid X-Requested-With header

Hm so the catalog client should probably be supplying that one unconditionally.

**Comment by laxmaneppalagudem** [comment]
hey there. i'm a bit new to node and backstage and was implementing the backend API auth following the official README and ran into the same issue mentioned at the beginning. i was able to use @tonyhsuclrous's bypass method to get it up and running. however i do see random 401s in my backend container logs for some official plugins with the stacktrace like below:

```
2022-09-21T22:49:57.718Z search error Collating documents for techdocs failed: ResponseError: Request failed with 401 Error type=plugin
2022-09-21T22:49:57.720Z search error Request failed with 401 Error type=taskManager task=search_index_techdocs name=ResponseError response=[object Response] body=[object Object] cause=Error: Request failed with status 401 Unauthorized, Unauthorized stack=ResponseError: Request failed with 401 Error
    at Function.fromResponse (/app/node_modules/@backstage/errors/dist/index.cjs.js:149:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CatalogClient.requestRequired (/app/node_modules/@backstage/catalog-client/dist/index.cjs.js:166:13)
    at async CatalogClient.getEntities (/app/node_modules/@backstage/catalog-client/dist/index.cjs.js:58:22)
    at async DefaultTechDocsCollatorFactory.execute (/app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:714:25)
    at async next (node:internal/streams/from:85:11)
2022-09-21T22:49:57.722Z search error Collating documents for software-catalog failed: ResponseError: Request failed with 401 Error type=plugin
2022-09-21T22:49:57.722Z search error Request failed with 401 Error type=taskManager task=search_index_software_catalog name=ResponseError response=[object Response] body=[object Object] cause=Error: Request failed with status 401 Unauthorized, Unauthorized stack=ResponseError: Request failed with 401 Error
    at Function.fromResponse (/app/node_modules/@backstage/errors/dist/index.cjs.js:149:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CatalogClient.requestRequired (/app/node_modules/@backstage/catalog-client/dist/index.cjs.js:166:13)
    at async CatalogClient.getEntities (/app/node_modules/@backstage/catalog-client/dist/index.cjs.js:58:22)
    at async DefaultCatalogCollatorFactory.execute (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:983:25)
    at async next (node:internal/streams/from:85:11)
```

@freben is there an official workaround for this issue from backstage? if not, what is the recommendation for broken plugins?

**Comment by VladMasarik** [comment]
@laxmaneppalagudem 
It was awful when I realized that the `tokenManager` is by default NOT initialized. Why that is I have no idea, but as per the [documentation](https://github.com/backstage/backstage/blob/master/docs/auth/service-to-service-auth.md#setup) just initialize it. I couldn't figure out why the search plugin didn't inject any tokens, and spent days searching for an issue that there were no answers for.

**Comment by laxmaneppalagudem** [comment]
thanks @VladMasarik. that resolved my error. i also see the latest documentation explicitly calls out [service-to-service auth](https://backstage.io/docs/auth/service-to-service-auth) which talks about `tokenManager`.

**Comment by bncbodrogi** [comment]
@VladMasarik since the new backend update your link might need to be updated to point to
https://github.com/backstage/backstage/blob/master/docs/auth/service-to-service-auth--old.md
