### ISSUE TITLE
Custom theme error

### ISSUE THREAD

**Issue by damolaobaleke** [backstage/backstage#12862]
## Expected Behavior

The header of my home and documentation page should follow a black pattern with a round sequence after setting the page theme object with the required arguments

## Actual Behavior

After updating backstage to v1.4.0 . The method `genPageTheme()` being used in the `pageTheme{}` object states it expect one argument but received two which shouldn't be the case and even after removing the second argument i get the error it's missing certain properties. That is expected. 

## Steps to Reproduce

1. Update backstage using `yarn backstage-cli versions:bump`
2. Open or create your customTheme file
3. Create the pageTheme object and pass in properties for the home page for example
<img width="844" alt="Screen Shot 2022-07-27 at 10 42 17 AM" src="https://user-images.githubusercontent.com/45045727/181329055-9f2e8875-9849-45c4-93a0-1332e40ca9db.png">

## Context

The front-end wont load unless i take out the pageTheme Object, so i cant customize my headers to my feel.

See below stacktrace on the chrome console as well
`runtime.js:39 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at genPageTheme (index.esm.js:25:1)
    at eval (nytimesTheme.tsx:48:1)`

## Your Environment

- Browser Information: 
Google Chrome Version 103.0.5060.134 (Official Build) (x86_64)

- Output of `yarn backstage-cli info`: 

```OS:   Darwin 21.5.0 - darwin/x64
node: v16.15.1
yarn: 1.22.19
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.4
  @backstage/backend-common                        0.14.1
  @backstage/backend-plugin-api                    0.1.0
  @backstage/backend-tasks                         0.3.3
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.0
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.4
  @backstage/core-components                       0.10.0
  @backstage/core-plugin-api                       1.0.4
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.2
  @backstage/integration                           1.2.2
  @backstage/plugin-api-docs                       0.8.7
  @backstage/plugin-app-backend                    0.3.34
  @backstage/plugin-auth-backend                   0.15.0
  @backstage/plugin-auth-node                      0.2.3
  @backstage/plugin-catalog-backend-module-github  0.1.5
  @backstage/plugin-catalog-backend                1.3.0
  @backstage/plugin-catalog-common                 1.0.4
  @backstage/plugin-catalog-graph                  0.2.19
  @backstage/plugin-catalog-import                 0.8.10
  @backstage/plugin-catalog-node                   1.0.0
  @backstage/plugin-catalog-react                  1.1.2
  @backstage/plugin-catalog                        1.4.0
  @backstage/plugin-cost-insights-common           0.1.0
  @backstage/plugin-cost-insights                  0.11.29
  @backstage/plugin-github-actions                 0.5.7
  @backstage/plugin-home                           0.4.23
  @backstage/plugin-org                            0.5.7
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.3
  @backstage/plugin-permission-react               0.4.3
  @backstage/plugin-proxy-backend                  0.2.28
  @backstage/plugin-scaffolder-backend             1.4.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.4.0
  @backstage/plugin-search-backend-module-pg       0.3.5
  @backstage/plugin-search-backend-node            1.0.0
  @backstage/plugin-search-backend                 1.0.0
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.0
  @backstage/plugin-search                         1.0.0
  @backstage/plugin-stack-overflow                 0.1.3
  @backstage/plugin-tech-radar                     0.5.14
  @backstage/plugin-techdocs-backend               1.2.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2
  @backstage/plugin-techdocs-node                  1.2.0
  @backstage/plugin-techdocs-react                 1.0.2
  @backstage/plugin-techdocs                       1.3.0
  @backstage/plugin-user-settings                  0.4.6
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

```

**Comment by awanlin** [comment]
Hi @damolaobaleke, I'm the one who made this change as part of a PR to clean up some of the Theme object. We are on the latest version and haven't had any issues with this once we updated the syntax. I totally understand that the syntax change wasn't clearly communicated

The syntax would be like this based on the example you posted: 

`genPageTheme({ colors: ['#000000', '#000000'], shape: shapes.round})`

Does that work for you?

**Comment by damolaobaleke** [comment]
Hi @awanlin Yeah it wasn't but thanks i appreciate. Yes it does work now!

**Comment by benjdlambert** [comment]
Closing this as the #12863 has been merged :tada:
