### ISSUE TITLE
Azure DevOps Token issues

### ISSUE THREAD

**Issue by no1melman** [backstage/backstage#13500]
## Expected Behavior

Assign `AZURE_TOKEN` environment variable that is used in the `app-config.yaml` and the provider/processor will happily go about it's business of getting stuff...

## Actual Behavior

I get this

```
2022-09-02T09:39:51.109Z catalog error Azure DevOps search failed with response status 203 type=plugin target=AzureDevOpsEntityProvider:allProjes class=AzureDevOpsEntityProvider taskId=AzureDevOpsEntityProvider:allProjes:refresh taskInstanceId=e3c7c007-9203-41a4-870d-7fced6a5b2e5 stack=Error: Azure DevOps search failed with response status 203
    at codeSearch (/app/node_modules/@backstage/plugin-catalog-backend-module-azure/dist/index.cjs.js:53:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AzureDevOpsEntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-azure/dist/index.cjs.js:231:19)
    at async TaskWorker.fn (/app/node_modules/@backstage/plugin-catalog-backend-module-azure/dist/index.cjs.js:211:13)
    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:289:7)
    at async /app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:242:31
```

## Steps to Reproduce

app-config.local.yaml:

```yaml
catalog:
  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/software-catalog-overview#adding-components-to-the-catalog for more details
  # on how to get entities into the catalog.
  rules:
    - allow: [Component, API, Location, Template]
  
  providers:
    azureDevOps:
      allProjes:
        organization: ...
        project: Tools
        repository: '*'
        path: /catalog-info.yaml
        
integrations:
  azure:
    - host: dev.azure.com
      token: ${AZURE_TOKEN}

azureDevOps:
  host: dev.azure.com
  token: ${AZURE_TOKEN}
  organization: ...
```

Dockerfile used to deploy on local.

```Dockerfile
FROM node:16-bullseye-slim

WORKDIR /app

# install sqlite3 dependencies, you can skip this if you don't use sqlite3 in the image
RUN apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential && \
    rm -rf /var/lib/apt/lists/* && \
    yarn config set python /usr/bin/python3

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)"

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY packages/backend/dist/bundle.tar.gz app-config*.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.local.yaml"]
```

Part of the powershell script which deploys image:

```powershell
docker run -d -p 7007:7007 `
    -e AZURE_TOKEN=$env:AZURE_TOKEN `
    -e POSTGRES_HOST=$pgHost `
    -e POSTGRES_PORT=$pgPort `
    -e POSTGRES_USER=$pgUser `
    -e POSTGRES_PASSWORD=$pgPassword `
    -e PGSSLMODE='disable' `
    --name $backstageContainerName $imageName
```

## Context

**Now Before someone mentions my PAT**

I have done, `:{TOKEN} |> base64`, I have done `{EMAIL}:{TOKEN} |> base64` . When I say base64, I've created this:

```powershell
function Create-AzureToken {
    param (
        [string]$RawToken
    )

    $bytearr = [System.Text.Encoding]::UTF8.GetBytes("`:$RawToken")
    [System.Convert]::ToBase64String($bytearr)
}
```

Which essentially is the above.

They both work with API calls. The PATs have full access (not going to be permanent, but want to rule out).

I have install the Code Search extensions.

**_I'm really not sure where to go from here_**

## Your Environment
 

- Browser Information: `Microsoft Edge | Version 104.0.1293.70 (Official build) (64-bit)`

- Output of `yarn backstage-cli info`: 

```text
OS:   Windows_NT 10.0.22000 - win32/x64
node: v16.17.0
yarn: 1.22.19
cli:  0.18.1 (installed)
backstage:  1.5.1

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0
  @backstage/core-plugin-api                       1.0.5
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-app-backend                    0.3.35
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend-module-azure   0.1.6
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.1
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 2.78s.
```

**Comment by no1melman** [comment]
It appears that the code doesn't want an encoded token - just a raw token... I think it maybe work updating the backstage docs - the place I got confused is that on the link provided by backstage on the matter of AzDo PATs, part way down is this[ information on how to use](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows#use-a-pat)

I will create a PR to update documentation

**Comment by Rugvip** [comment]
@no1melman ah alright, makes sense, thanks! 👍

**Comment by emma-campbell** [comment]
> @no1melman ah alright, makes sense, thanks! 👍

Did you ever get this working using the raw token or do you mind sharing the configuration you used to get this working? I have a similar set up to what you included above, using the raw token, but I am running into the same error message.

**Comment by no1melman** [comment]
Yeah, I believe I did, just did `:{raw_token}`

**Comment by dimitrigeo** [comment]
would someone mind sharing the exact solution?

**Comment by freben** [comment]
@no1melman Did you get the chance to update the docs? 🙏

**Comment by L0wry** [comment]
I'm also sadly struggling with this. 
I've tried in the app-config 
```
 token: {raw_pat}
 token: {base65(raw_pat)}
 token: :{base64(raw_pat)}
 token: {base64(:raw_pat)}
```

I'm also able to clone repositories by setting the auth header and using the base64 pat. 
Would really appreciate some guidance @freben @no1melman 🙏

**Comment by no1melman** [comment]
@freben see the linked PR

**Comment by phil1234567891011** [comment]
so what is the solution for this, I don't use encoded PAT's
