### ISSUE TITLE
TechDocs: Cannot publish to S3 bucket

### ISSUE THREAD

**Issue by arielpacciaroni** [backstage/backstage#13514]
## Expected Behavior

TechDocs should be able to use the S3 bucket

## Actual Behavior

I get the following error:

```
2022-09-02T18:45:49.348Z techdocs error Could not retrieve metadata about the AWS S3 bucket [bucket-name]. Make sure the bucket exists. Also make sure that authentication is setup either by explicitly defining credentials and region in techdocs.publisher.awsS3 in app config or by using environment variables. Refer to https://backstage.io/docs/features/techdocs/using-cloud-storage type=plugin
2022-09-02T18:45:49.349Z techdocs error from AWS client library Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1 type=plugin code=CredentialsError time=Fri Sep 02 2022 18:45:49 GMT+0000 (Coordinated Universal Time) requestId=a0482e95-a07a-450e-b424-6e8d6504dab8 statusCode=403 retryable=false retryDelay=97.85600385199255 originalError=[object Object] stack=CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
```

## Your Environment

**ENV variables**:

```
AWS_DEFAULT_REGION=eu-west-1
AWS_REGION=eu-west-1
AWS_ROLE_ARN=arnRoleAssumedByEKSPod
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_STS_REGIONAL_ENDPOINTS=regional
```

*app-config.yaml*:
```
  publisher:
    type: 'awsS3' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    awsS3:
      bucketName: 'bucket-name'
      region: ${AWS_REGION}
      credentials:
        roleArn: techDocsRoleArn
```

In AWS, `techDocsRoleArn` has the following statement so the pod can assume `techDocsRoleArn`:

```
Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          AWS = "arnRoleAssumedByEKSPod"
        }
      }
    ]
```

and has attached this policy:

```
  policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Action" : ["s3:PutObject",
          "s3:GetObject",
          "s3:DeleteObjectVersion",
          "s3:ListBucket",
          "s3:DeleteObject",
        "s3:PutObjectAcl"],
        "Resource" : ["arn:aws:s3:::${var.techdocs_bucket_name}", "arn:aws:s3:::${var.techdocs_bucket_name}/*"]
      }
    ]
  })
```

**Comment by hillmandj** [comment]
@arielpacciaroni can you give more of a background as to why you closed this issue? How did you resolve this?
