### ISSUE TITLE
BitBucket Server integration no longer works for non-default branches

### ISSUE THREAD

**Issue by DavidZemon** [backstage/backstage#13560]
## Expected Behavior

I should be able to register a software template from a non-default branch and then use that template.

## Actual Behavior

Upon trying to use the template, I encounter this error

```txt
2022-09-06T17:57:02.474Z Beginning step Generate Code
2022-09-06T17:57:02.763Z info: Fetching template content from remote URL {"timestamp":"2022-09-06T17:57:02.719Z"}
2022-09-06T17:57:03.465Z NotFoundError: Failed to retrieve commits from https://our.internal.bitbucket.server.com/rest/api/1.0/projects/APIE/repos/template-ts-aws-cdk-v2/commits/feature/start-template, 404 Not Found
    at _BitbucketServerUrlReader.getLastCommitShortHash (/app/node_modules/@backstage/backend-common/src/reading/BitbucketServerUrlReader.ts:121:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at _BitbucketServerUrlReader.readTree (/app/node_modules/@backstage/backend-common/src/reading/BitbucketServerUrlReader.ts:60:33)
    at UrlReaderPredicateMux.readTree (/app/node_modules/@backstage/backend-common/src/reading/UrlReaderPredicateMux.ts:52:16)
    at fetchContents (/app/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/actions/builtin/fetch/helpers.ts:40:17)
    at Object.handler (/app/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/actions/builtin/fetch/template.ts:108:7)
    at NunjucksWorkflowRunner.execute (/app/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:180:11)
    at TaskWorker.runOneTask (/app/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:43:26)
    at /app/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:32:9
```

## Steps to Reproduce

1. Create a software template with two branch
2. Create a new repo in bitbucket
3. Push software template to bitbucket
4. Register the non-default branch of the new template in Backstage
5. Run the template

## Context

We have Backstage deployed to multiple environments, and I like to test out my template changes in one of these lower environments before submitting my pull request. That implies registering a non-default branch.

## Your Environment

- Google Chrome 104.0.5112.79 (Official Build) (x86_64)

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.6.0 - darwin/x64
node: v14.19.3
yarn: 1.22.19
cli:  0.18.1 (installed)
backstage:  1.5.0

Dependencies:
  @backstage/app-defaults                            1.0.5
  @backstage/backend-common                          0.15.0
  @backstage/backend-plugin-api                      0.1.1
  @backstage/backend-tasks                           0.3.4
  @backstage/catalog-client                          1.0.4
  @backstage/catalog-model                           1.1.0
  @backstage/cli-common                              0.1.9
  @backstage/cli                                     0.18.1
  @backstage/config-loader                           1.1.3
  @backstage/config                                  1.0.1
  @backstage/core-app-api                            1.0.5
  @backstage/core-components                         0.11.0
  @backstage/core-plugin-api                         1.0.5
  @backstage/dev-utils                               1.0.5
  @backstage/errors                                  1.1.0
  @backstage/integration-react                       1.1.3
  @backstage/integration                             1.3.0
  @backstage/plugin-analytics-module-ga              0.1.19
  @backstage/plugin-api-docs                         0.8.8
  @backstage/plugin-app-backend                      0.3.35
  @backstage/plugin-auth-backend                     0.15.1
  @backstage/plugin-auth-node                        0.2.4
  @backstage/plugin-bitbucket-cloud-common           0.1.2
  @backstage/plugin-catalog-backend-module-bitbucket 0.2.2
  @backstage/plugin-catalog-backend                  1.3.1
  @backstage/plugin-catalog-common                   1.0.5
  @backstage/plugin-catalog-graph                    0.2.20
  @backstage/plugin-catalog-import                   0.8.11
  @backstage/plugin-catalog-node                     1.0.1
  @backstage/plugin-catalog-react                    1.1.3
  @backstage/plugin-catalog                          1.5.0
  @backstage/plugin-dynatrace                        0.1.2
  @backstage/plugin-github-actions                   0.5.8
  @backstage/plugin-home                             0.4.24
  @backstage/plugin-jenkins-backend                  0.1.25
  @backstage/plugin-jenkins-common                   0.1.7
  @backstage/plugin-jenkins                          0.7.7
  @backstage/plugin-org                              0.5.8
  @backstage/plugin-permission-common                0.6.3
  @backstage/plugin-permission-node                  0.6.4
  @backstage/plugin-permission-react                 0.4.4
  @backstage/plugin-proxy-backend                    0.2.29
  @backstage/plugin-scaffolder-backend               1.5.0
  @backstage/plugin-scaffolder-common                1.1.2
  @backstage/plugin-scaffolder                       1.5.0
  @backstage/plugin-search-backend-module-pg         0.3.6
  @backstage/plugin-search-backend-node              1.0.1
  @backstage/plugin-search-backend                   1.0.1
  @backstage/plugin-search-common                    1.0.0
  @backstage/plugin-search-react                     1.0.1
  @backstage/plugin-search                           1.0.1
  @backstage/plugin-stack-overflow                   0.1.4
  @backstage/plugin-tech-radar                       0.5.15
  @backstage/plugin-techdocs-backend                 1.2.1
  @backstage/plugin-techdocs-module-addons-contrib   1.0.3
  @backstage/plugin-techdocs-node                    1.3.0
  @backstage/plugin-techdocs-react                   1.0.3
  @backstage/plugin-techdocs                         1.3.1
  @backstage/plugin-user-settings                    0.4.7
  @backstage/release-manifests                       0.0.5
  @backstage/test-utils                              1.1.3
  @backstage/theme                                   0.2.16
  @backstage/types                                   1.0.0
  @backstage/version-bridge                          1.0.1
✨  Done in 1.41s.
```

-----------
 
I'm sure this is related to https://github.com/backstage/backstage/issues/12827. It seems when fixing that one, the problem was just reversed.

**Comment by awanlin** [comment]
@DavidZemon the fix for #12827 was PR #12748 which simply added back handling cases where no branch was provided: https://github.com/backstage/backstage/blob/f1e43bd5df2cb8362878c26cc7e3761d7e7493ef/packages/backend-common/src/reading/BitbucketServerUrlReader.ts#L213-L221

This is done after new logic that was added as part of PR #12485. Can you help me understand where this would be causing you issues?

**Comment by awanlin** [comment]
Looking at this code I'm confused as to how this works: https://github.com/backstage/backstage/blob/f1e43bd5df2cb8362878c26cc7e3761d7e7493ef/packages/backend-common/src/reading/BitbucketServerUrlReader.ts#L191-L192

If you read the doc in the included link - https://docs.atlassian.com/bitbucket-server/rest/7.9.0/bitbucket-rest.html#idp224 - where we have `${branch}` at the end should be a `commitId` as per:

```url
/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/commits/{commitId}
```

I'm pretty confused right now, how did this work?

**Comment by DavidZemon** [comment]
I don't think it's been fully functional since v1.3, before this series of changes started.

For my project, the annotation `backstage.io/managed-by-location` is set to `https://our.internal.bitbucket.server.com/projects/APIE/repos/template-ts-aws-cdk-v2/browse/app-template.yaml?at=feature%2Fstart-template`.

This results in a call to `https://our.internal.bitbucket.server.com/rest/api/1.0/projects/APIE/repos/template-ts-aws-cdk-v2/commits/feature/start-template`, which sends a 404 with response body

```json
{
  "message": "null for uri: https://our.internal.bitbucket.server.com/rest/api/1.0/projects/APIE/repos/template-ts-aws-cdk-v2/commits/feature/start-template",
  "status-code": 404
}
```

**Comment by DavidZemon** [comment]
@awanlin, do you need any more info from me?

**Comment by awanlin** [comment]
@DavidZemon I'm not sure what you mean? I dove into this as I was concerned that this was something I broke. Based on my review and your feedback that's not the case. Feel free to submit a PR with a fix, I'll happily do some testing just tag me on the PR 👍

**Comment by DavidZemon** [comment]
Okay, thank you both for the comments on this and sorry for the slow response. What if we queried for the list of branches (which responds with the commit IDs) and then find the matching branch in that response? I haven't tested this yet (I might do so later this afternoon) but it seems pretty straight forward and should completely bypass this issue with commit IDs from the ".../commits" endpoint.
I started looking for this solution because, upon reading the BB API documentation, I couldn't find _any reference_ to the endpoint for querying commits by branch. I found the ".../commits" endpoint but no documentation and how to add a branch name in there. And in my own testing, I see what you mean about weird behavior for branches with slashes in them. So... I wanted to find a more reliable way to get that commit ID.

Here's what I came up with:

```ts
private async getLastCommitShortHash(url: string): Promise<string> {
  const { name: repoName, owner: project, ref: branch } = parseGitUrl(url);

  const branchListUrl = `${this.integration.config.apiBaseUrl}/projects/${project}/repos/${repoName}/branches?filterText=${encodeURIComponent(branch)}`;

  const branchListResponse = await fetch(
    branchListUrl,
    getBitbucketServerRequestOptions(this.integration.config),
  );
  if (!branchListResponse.ok) {
    const message = `Failed to retrieve branch list from ${branchListUrl}, ${branchListResponse.status} ${branchListResponse.statusText}`;
    if (branchListResponse.status === 404) {
      throw new NotFoundError(message);
    }
    throw new Error(message);
  }

  const branchMatches = await branchListResponse.json();

  if (branchMatches && branchMatches.size > 0) {
    const exactBranchMatch = branchMatches.values.filter(
      (branchDetails: {displayId: string}) => branchDetails.displayId === branch
    )[0];
    return exactBranchMatch.latestCommit.substring(0, 12);
  }

  throw new Error(`Failed to find branch "${branch}" in property "displayId" of response to ${branchListUrl}`);
}
```

**Comment by freben** [comment]
Is it as simple as having to URL encode the branch part of `commits/${branch}`? Sorry I don't have the product at hand to test with.

**Comment by DavidZemon** [comment]
> Is it as simple as having to URL encode the branch part of `.../commits/${branch}`? Sorry I don't have the product at hand to test with.

Unfortunately, no I don't think so. I tried using `%2F%` with the http client built into IntelliJ and got the same error. For completeness though, I will try with curl where I know no magic is happening behind the scenes.

**Comment by DavidZemon** [comment]
@freben, I've confirmed that escaping the `/` doesn't help:

```                                                                                                                                                              
david.zemon@computer:~$ curl -X GET --location 'https://our.internal.bitbucket.server.com/rest/api/1.0/projects/APIE/repos/template-ts-aws-cdk-v2/commits/feature/start-template' \
    -H "Authorization: Bearer ******"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>404</status-code><message>null for uri: https://our.internal.bitbucket.server.com/rest/api/1.0/projects/APIE/repos/template-ts-aws-cdk-v2/commits/feature/start-template</message></status>%
```
```
david.zemon@computer:~$ curl -X GET --location 'https://our.internal.bitbucket.server.com/rest/api/1.0/projects/APIE/repos/template-ts-aws-cdk-v2/commits/feature%2Fstart-template' \
    -H "Authorization: Bearer ******"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /rest/api/1.0/projects/APIE/repos/template-ts-aws-cdk-v2/commits/feature/start-template was not found on this server.</p>
</body></html>
```

And the working example:
```
david.zemon@computer:~$ curl -X GET --location 'https://our.internal.bitbucket.server.com/rest/api/1.0/projects/APIE/repos/template-ts-aws-cdk-v2/branches?filter=feature/start-template' \
    -H "Authorization: Bearer ******"
{"size":1,"limit":25,"isLastPage":true,"values":[{"id":"refs/heads/feature/start-template","displayId":"feature/start-template","type":"BRANCH","latestCommit":"4c5e5fd6754b92f84d08f87c76b231fbf66721a1","latestChangeset":"4c5e5fd6754b92f84d08f87c76b231fbf66721a1","isDefault":false}],"start":0}%        
```
