### ISSUE TITLE
MicrosoftGraphOrgEntityProvider not respecting queryMode option

### ISSUE THREAD

**Issue by nhhagen** [backstage/backstage#13638]
## Expected Behavior

I expected to be able to use Microsoft Graph advanced queries when setting `queryMode: advanced`.

## Actual Behavior

Backstage gave an error and users and groups where not ingested.

## Steps to Reproduce

1. Install the plugin
   ```
   yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-msgraph
   ```

2. Configure the `microsoftGraphOrg` in `app-config.yaml`.
   ```yaml
   catalog:
     providers:
       microsoftGraphOrg:
         default:
           tenantId: ${AZURE_TENANT_ID}
           queryMode: advanced
           user:
             filter: >
               accountEnabled eq true
               and userType eq 'member'
               and startsWith(officeLocation, 'REDACTED')
               and not startsWith(displayName, 'REDACTED')
           group:
             filter: >
               securityEnabled eq true
               and onPremisesSyncEnabled eq null
               and not (groupTypes/any(c:c+eq+'DynamicMembership'))
           rules:
             - allow: [User, Group]
   ```

3. Configure the catalog to use the provider in `packages/backend/src/plugins/catalog.ts`
   ```typescript
   builder.addEntityProvider(
     MicrosoftGraphOrgEntityProvider.fromConfig(env.config, {
       logger: env.logger,
       schedule: env.scheduler.createScheduledTaskRunner({
         frequency: { hours: 1 },
         timeout: { minutes: 50 },
         initialDelay: { seconds: 15}
       }),
     }),
   );
   ```

5. Start backstage
   ```
   yarn dev
   ```

## Context

We are trying to build a catalog of users and groups. Azure AD contains a lot of users and groups that are not relevant to keep in backstage.

Stacktrace and error message:
```
[1] 2022-09-10T10:18:24.733Z catalog info Reading msgraph users and groups type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:default:refresh taskInstanceId=27d61136-aae4-48e7-a52d-467fe08f76ca
[1] 2022-09-10T10:18:25.222Z catalog error Error while reading users from Microsoft Graph: Request_UnsupportedQuery - Unsupported Query. type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:default:refresh taskInstanceId=27d61136-aae4-48e7-a52d-467fe08f76ca stack=Error: Error while reading users from Microsoft Graph: Request_UnsupportedQuery - Unsupported Query.
[1]     at MicrosoftGraphClient.handleError (/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/dist/index.cjs.js:191:11)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]     at async MicrosoftGraphClient.requestCollection (/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/dist/index.cjs.js:68:9)
[1]     at async MicrosoftGraphClient.getUsers (/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/dist/index.cjs.js:127:5)
[1]     at async readMicrosoftGraphUsers (/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/dist/index.cjs.js:440:20)
[1]     at async readMicrosoftGraphOrg (/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/dist/index.cjs.js:736:40)
[1]     at async MicrosoftGraphOrgEntityProvider.read (/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/dist/index.cjs.js:854:31)
[1]     at async TaskWorker.fn (/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/dist/index.cjs.js:896:13)
[1]     at async TaskWorker.runOnce (/backstage/node_modules/@backstage/backend-tasks/dist/index.cjs.js:289:7)
[1]     at async /backstage/node_modules/@backstage/backend-tasks/dist/index.cjs.js:242:31
```

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.19
$ /Users/niels.hagen/code/work/backstage/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.17.0
yarn: 1.22.19
cli:  0.18.1 (installed)
backstage:  1.5.1

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0
  @backstage/core-plugin-api                       1.0.5
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-app-backend                    0.3.35
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend-module-msgraph 0.4.1
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.1
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 0.38s.
```

**Comment by benjdlambert** [comment]
@pjungermann do you want to take a quick look at this :praY:

**Comment by pjungermann** [comment]
The code itself looked fine but I can confirm the bug. I found a regression at the new config structure provided by `readProviderConfigs` at `config.ts`. The legacy config structure as support by `readMicrosoftGraphConfig` contains it. The `queryMode` config option was missed.

It can be fixed easily. @nhhagen do you want to give it a try? see lines 176..183 at the legacy function which need to added to `readProviderConfigs` and `queryMode` added to the returned object similar like at line 213.

I could take care of it, too. I'm working on something else right now though and would rather complete that first.

**Comment by nhhagen** [comment]
@pjungermann I gave it a shot. Thanks for the guidance.
