### ISSUE TITLE
Class constructor Jenkins cannot be invoked without 'new'

### ISSUE THREAD

**Issue by timja** [backstage/backstage#13692]
## Expected Behavior

Jenkins plugin works

## Actual Behavior

Jenkins plugin is broken

```
2022-09-15T14:16:58.915Z backstage error Class constructor Jenkins cannot be invoked without 'new' type=errorHandler stack=TypeError: Class constructor Jenkins cannot be invoked without 'new'
    at Function.getClient (webpack-internal:///../../plugins/jenkins-backend/src/service/jenkinsApi.ts:115:62)
    at JenkinsApiImpl.getProjects (webpack-internal:///../../plugins/jenkins-backend/src/service/jenkinsApi.ts:38:45)
    at eval (webpack-internal:///../../plugins/jenkins-backend/src/service/router.ts:70:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Steps to Reproduce

1. Configure an entity with a Jenkins annotation, e.g. something like https://github.com/hmcts/draft-store/blob/547c9ea2e43a8592a1aa711bfc1e799b8adc57f9/catalog-info.yaml#L7
2. View page in catalog, see error in console / backend logs

## Your Environment

Reproduced on tip of master branch here 535ca54f0e7ccc39eedefe084b94cb8aa42f7df9 
https://github.com/backstage/backstage

**Comment by freben** [comment]
Ouch. Is this something you might want to contribute a fix for?

https://github.com/backstage/backstage/blob/master/plugins/jenkins-backend/src/service/jenkinsApi.ts#L180

**Comment by timja** [comment]
Looking, mis-matched line numbers through me off a bit

**Comment by timja** [comment]
This gets me further:
```diff
-import jenkins from 'jenkins';
+import Jenkins from 'jenkins';

+    // @ts-ignore TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
+    return new Jenkins({
       baseUrl: jenkinsInfo.baseUrl,
       headers: jenkinsInfo.headers,
       promisify: true,
       crumbIssuer: jenkinsInfo.crumbIssuer,
-    }) as any;
+    });
```

 I'm just checking more as I'm getting other errors, but may be things not setup in the example-backend, adding extra debug as I'm getting:

```
AggregateError: All promises were rejected
```

**Comment by timja** [comment]
Likely fine, error reporting is terrible though, I'll try improve that:

```
FAILED to FETCH JOB Error: jenkins: job.get: HMCTS_a_to_c/adoption-cos-api/master not found
    at Jenkins.<anonymous> (/Users/timja/projects/backstage-upstream/node_modules/jenkins/lib/middleware.js:85:19)
    at next (/Users/timja/projects/backstage-upstream/node_modules/papi/lib/client.js:298:12)
    at Jenkins._onResponse (/Users/timja/projects/backstage-upstream/node_modules/jenkins/lib/jenkins.js:92:5)
    at next (/Users/timja/projects/backstage-upstream/node_modules/papi/lib/client.js:298:12)
    at IncomingMessage.<anonymous> (/Users/timja/projects/backstage-upstream/node_modules/papi/lib/client.js:598:9)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  notFound: true
}
```

**Comment by timja** [comment]
Raised https://github.com/backstage/backstage/pull/13699, looking at improving error handling in a separate PR

**Comment by benjdlambert** [comment]
Looks like this was caused by the release of the `1.0.0` of the plugin. Looking back from the previous release the implementation was correct https://github.com/silas/node-jenkins/tree/f1cf921407d7c367c520dcf8b8a5d377bafd2920.

Looks like the Jenkins bump and lack of integrations tests is the reason why we missed this.  #13388 or #13404 were the causes.

**Comment by timja** [comment]
It would have been https://github.com/backstage/backstage/pull/13388, in the change diff (no changelog I can find)

it switched from functions to classes:
https://github.com/silas/node-jenkins/compare/0.28.1...1.0.1
