### ISSUE TITLE
Elasticsearch multi node cluster setup doesn't work 

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#13703]
## Expected Behavior

The config.d.ts under the "search-backend-module-elasticsearch" suggests that multiple elasticsearch nodes can be provided ( ideally required for multi node cluster setup )

"**
             * Node configuration.
             * URL/URLS to ElasticSearch node to connect to.
             * Either direct URL like 'https://localhost:9200' or with credentials like 'https://username:password@localhost:9200'
             */
           node: string | string[];"

But, when we try to use the below config in app-config.yml

search:
  elasticsearch:
    node: ['http://localhost:9200', 'http://localhost:9201']

if fails to start the backend with the below error

[1] Backend failed to start up TypeError: Invalid type in config for key 'search.elasticsearch.node' in 'app-config.yaml', got array, wanted string
[1]     at ConfigReader.readConfigValue (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\config\dist\index.cjs.js:240:13)
[1]     at ConfigReader.getOptionalString (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\config\dist\index.cjs.js:194:17)
[1]     at ConfigReader.getString (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\config\dist\index.cjs.js:187:24)
[1]     at ObservableConfigProxy.getString (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\backend-common\dist\index.cjs.js:396:30)
[1]     at createElasticSearchClientOptions (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\plugin-search-backend-module-elasticsearch\dist\index.cjs.js:449:18)
[1]     at Function.fromConfig (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\plugin-search-backend-module-elasticsearch\dist\index.cjs.js:260:27)
[1]     at createSearchEngine (webpack-internal:///./src/plugins/search.ts:50:127)
[1]     at createPlugin (webpack-internal:///./src/plugins/search.ts:69:30)
[1]     at main (webpack-internal:///./src/index.ts:259:96)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by garyniemen** [comment]
@shanthisagar-dhanya-kumar-db is this still an issue for you?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
@garyniemen : Yes. unfortunately it is not accepting multiple elastic search cluster nodes

**Comment by camilaibs** [comment]
Hi @shanthisagar-dhanya-kumar-db, I was able to reproduce the error. It seems to happen because, in the line below, we are always trying to get a string from config. It seems worth checking if it's an array using `getOptionalStringArray` instead... Would you like to try opening a pull request contributing to us?
https://github.com/backstage/backstage/blob/68360a5fc663d17dc1a0fb699e5e1f50dcf3cfd8/plugins/search-backend-module-elasticsearch/src/engines/ElasticSearchSearchEngine.ts#L444
