### ISSUE TITLE
[Plugin] gitea

### ISSUE THREAD

**Issue by freben** [backstage/backstage#13873]
[gitea](https://gitea.io/) is a self hosted "github clone". Making an integration with gitea would let adopters hook up the catalog and other Backstage products to it.

This would likely involve extending [the `ScmIntegrations`](https://github.com/backstage/backstage/blob/9896e7c2e26b0fcb102d8cd6a79939f493dd4bf5/packages/integration/src/ScmIntegrations.ts#L54
) interface, and making [a `UrlReader`](https://github.com/backstage/backstage/blob/9896e7c2e26b0fcb102d8cd6a79939f493dd4bf5/packages/backend-common/src/reading/types.ts#L27) implementation based on it, for starters. This will enable reading content out of it, from various Backstage plugins that use these standard facilities. If you also want to support publishing to it, there may be some more work to do in individual plugins, for example in techdocs, the scaffolder, etc.

**Comment by atoko** [comment]
Tracked by #14056

Currently only ScmIntegrations and UrlReader interfaces have been implemented, and I'm working on the unit tests for the latter

**Comment by kurtaking** [comment]
@freben should this be closed out or is there additional work? I see https://github.com/backstage/backstage/pull/14056 has been merged.

**Comment by freben** [comment]
The major bit missing might be a scaffolder module that lets you do publishing. A lot of other stuff is automatically in place after #14065, including the catalog and techdocs functionality.

**Comment by cmoulliard** [comment]
> The major bit missing might be a scaffolder module that lets you do publishing

Where can we find documentation about how to implement such a missing scaffolding feature ? @freben

**Comment by pittar** [comment]
@freben , does this mean you can list GPTs hosted in Gitea, but you can't actually use them to create repos in Gitea?

 I was attempting this today.  I was able to see the GPTs from my Gitea repo in Backstage, but when I couldn't figure out how to get the scaffolding to work.  I would only get the following error when trying to scaffold the code:
 
 ```
 [3](https://<url>#line-3)2023-10-25T20:58:06.142Z Error: GiteaUrlReader readTree not implemented.
 [4](<url>/create/tasks/c619866d-4a31-461a-b9ed-b570876de4b4#line-4)    at _GiteaUrlReader.readTree (/remote-source/node_modules/@backstage/backend-common/dist/index.cjs.js:2836:11)
 [5](<url>/create/tasks/c619866d-4a31-461a-b9ed-b570876de4b4#line-5)    at UrlReaderPredicateMux.readTree (/remote-source/node_modules/@backstage/backend-common/dist/index.cjs.js:3270:29)
 [6](<url>/create/tasks/c619866d-4a31-461a-b9ed-b570876de4b4#line-6)    at Object.fetchContents (/remote-source/node_modules/@backstage/plugin-scaffolder-node/dist/index.cjs.js:72:30)
 [7](<url>/create/tasks/c619866d-4a31-461a-b9ed-b570876de4b4#line-7)    at Object.handler (/remote-source/packages/backend/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-4b7489dd.cjs.js:1098:34)
 [8](<url>/create/tasks/c619866d-4a31-461a-b9ed-b570876de4b4#line-8)    at async NunjucksWorkflowRunner.executeStep (/remote-source/packages/backend/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-4b7489dd.cjs.js:5997:9)
 [9](<url>/create/tasks/c619866d-4a31-461a-b9ed-b570876de4b4#line-9)    at async NunjucksWorkflowRunner.execute (/remote-source/packages/backend/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-4b7489dd.cjs.js:6070:9)
 [10](<url>/create/tasks/c619866d-4a31-461a-b9ed-b570876de4b4#line-10)    at async TaskWorker.runOneTask (/remote-source/packages/backend/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-4b7489dd.cjs.js:6292:26)
 [11](<url>/create/tasks/c619866d-4a31-461a-b9ed-b570876de4b4#line-11)    at async run (/remote-source/node_modules/p-queue/dist/index.js:163:29)
 ```

**Comment by cmoulliard** [comment]
> but you can't actually use them to create repos in Gitea?

Correct as no action `publish:gitea` currently exists

Remark: The error you reports is related to the fact that the function `readTree` is not implemented under `GitUrlReader` as this is the case for GitLab by example : https://github.com/ch007m/fork-backstage/blob/master/packages/backend-common/src/reading/GitlabUrlReader.ts#L120

**Comment by freben** [comment]
> > The major bit missing might be a scaffolder module that lets you do publishing
> 
> Where can we find documentation about how to implement such a missing scaffolding feature ? @freben

First thing that is missing is `readTree`, to be able to fetch the original template data out of gitea. The task would be to [implement this method](https://github.com/backstage/backstage/blob/c3f3253b74ade64e200321efd5cd0a6b1ac7a427/packages/backend-common/src/reading/GiteaUrlReader.ts#L116). If you look at all of the classes in the same directory, you'll see a lot of implementations for other systems as inspiration.

The next step would be to implement a `publish:gitea` or similar action for the scaffolder, as needed. Again there's lots of inspiration to look at, check all the publishers [in this folder](https://github.com/backstage/backstage/tree/c3f3253b74ade64e200321efd5cd0a6b1ac7a427/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish).

**Comment by cmoulliard** [comment]
Thanks. Can I create a PR against this issue to track the work to be done around gitea ?

**Comment by twanbeeren** [comment]
This is something I would like to elaborate on as well. If there is a pull request for development let me know.

So we can create a createPublishGiteaAction(options) for the scaffolder-backend
https://backstage.io/docs/reference/plugin-scaffolder-backend

**Comment by cmoulliard** [comment]
I created a draft PR : https://github.com/backstage/backstage/pull/20899 where code to `publish:gerrit` is still missing @twanbeeren

**Comment by twanbeeren** [comment]
I think you mean `publish:gitea` but this is something that I can help with

**Comment by cmoulliard** [comment]
> I think you mean

Yes. I fixed the error in my comment ;-) Remark: RepoUrlPicker does not work too if I test it using this template locally: https://github.com/ch007m/backstage-quarkus-template/blob/main/quarkus-template.yaml

**Comment by twanbeeren** [comment]
When we use our template to deploy to Gitea it also doesn't show a list of hosts

**Comment by ghhenry** [comment]
To get gitea repos in the list of hosts a small change is needed in `ScaffolderClient.getIntegrationsList`. Gitea is missing here.

**Comment by cmoulliard** [comment]
> To get gitea repos in the list of hosts a small change is needed in `ScaffolderClient.getIntegrationsList`. Gitea is missing here.

Many thanks. I pushed the change on the PR -> https://github.com/backstage/backstage/pull/20899/commits/4c71c54d35e344be9149f5ab39dee5e127683b50 but still no luck when I play such a scenario: https://gist.github.com/cmoulliard/6e8aa6838e449db42e97ad1f484912f8
