### ISSUE TITLE
Main branch CI build failing, snyk workflow out of memory

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#14131]
## Expected Behavior

When PRs are merged, all checks pass.

## Actual Behavior

The Snyk sync workflow is failing when a PR is merged. Latest example https://github.com/backstage/backstage/blob/3e2d945826585ac0306e1c00af5bef218e24bc59/.github/workflows/ci.yml#L24 

This is due to Javascript heap our of memory.

## Possible fix

Maybe increase memory limit in GitHub actions workflow like [this](https://github.com/backstage/backstage/blob/3e2d945826585ac0306e1c00af5bef218e24bc59/.github/workflows/ci.yml#L24)?

**Comment by HHogg** [comment]
Reopening as its still an issue

**Comment by Parsifal-M** [comment]
Needs even more memory? :sweat_smile:

**Comment by jhaals** [comment]
Are we sure this is a memory issue? It does look like a compilation issue from the stacktrace

```
/home/runner/work/backstage/backstage/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
Error: scripts/snyk-github-issue-sync.ts(21,28): error TS2307: Cannot find module '../snyk.json' or its corresponding type declarations.
Error: scripts/snyk-github-issue-sync.ts(150,8): error TS7031: Binding element 'projectName' implicitly has an 'any' type.
Error: scripts/snyk-github-issue-sync.ts(150,21): error TS7031: Binding element 'displayTargetFile' implicitly has an 'any' type.
Error: scripts/snyk-github-issue-sync.ts(150,40): error TS7031: Binding element 'vulnerabilities' implicitly has an 'any' type.

    at createTSError (/home/runner/work/backstage/backstage/node_modules/ts-node/src/index.ts:85[9](https://github.com/backstage/backstage/actions/runs/3219153852/jobs/5264168236#step:7:10):12)
    at reportTSError (/home/runner/work/backstage/backstage/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/runner/work/backstage/backstage/node_modules/ts-node/src/index.ts:[10](https://github.com/backstage/backstage/actions/runs/3219153852/jobs/5264168236#step:7:11)77:36)
    at Object.compile (/home/runner/work/backstage/backstage/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/runner/work/backstage/backstage/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:[11](https://github.com/backstage/backstage/actions/runs/3219153852/jobs/5264168236#step:7:12)14:10)
    at Object.require.extensions.<computed> [as .ts] (/home/runner/work/backstage/backstage/node_modules/ts-node/src/index.ts:1621:[12](https://github.com/backstage/backstage/actions/runs/3219153852/jobs/5264168236#step:7:13))
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  diagnosticCodes: [ [23](https://github.com/backstage/backstage/actions/runs/3219153852/jobs/5264168236#step:7:24)07, 7031, 7031, 7031 ]
}
```

from https://github.com/backstage/backstage/actions/runs/3311019667/jobs/5465950950#step:7:31

**Comment by jhaals** [comment]
I tried raising it to 6gb without issues, probably time to open an issue for the snyk workflow job

**Comment by jhaals** [comment]
I'll open a ticket on their site for support 🙏 🤞

**Comment by Rugvip** [comment]
Update on this is that it seems like the Snyk CLI doesn't support Yarn 3 yet
