### ISSUE TITLE
🐛 Bug Report: Bazaar Plugin giving 404 error after installing

### ISSUE THREAD

**Issue by prasoon-pxc** [backstage/backstage#14420]
### 📜 Description

Bazaar Plugin giving 404 error after installing

### 👍 Expected behavior

It should give option to create new project for bazaar

### 👎 Actual Behavior with Screenshots

I tried installing the Bazaar Plugin using it [documentation](https://github.com/backstage/backstage/tree/master/plugins/bazaar), but it is not working after installation and giving below error:
![image](https://user-images.githubusercontent.com/106815018/199684000-6e9af79b-6952-42a7-8234-545aaf9cd86c.png)

---
On checking the logs , I did not found much:

```
[1] 2022-11-03T08:39:57.205Z backstage info 192.168.63.1 - - [03/Nov/2022:08:39:57 +0000] "GET /api/bazaar/projects? HTTP/1.1" 404 - "http://192.168.63.249:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" type=incomingRequest


```

### 👟 Reproduction steps

Follow the below link:
[Link](https://github.com/backstage/backstage/tree/master/plugins/bazaar)

### 🖥️ Your Environment

Output of `yarn backstage-cli info`

---
```
yarn run v1.22.19
$ /home/backstage/backstage-conf-repo_my/node_modules/.bin/backstage-cli info
OS:   Linux 3.10.0-1160.71.1.el7.x86_64 - linux/x64
node: v16.14.0
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  1.7.1

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-app-api                       0.2.2
  @backstage/backend-common                        0.15.2
  @backstage/backend-plugin-api                    0.1.3
  @backstage/backend-tasks                         0.3.6
  @backstage/backend-test-utils                    0.1.29
  @backstage/catalog-client                        1.1.1
  @backstage/catalog-model                         1.1.2
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0
  @backstage/config-loader                         1.1.5
  @backstage/config                                1.0.3
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.10.0, 0.11.2
  @backstage/core-plugin-api                       1.0.7
  @backstage/errors                                1.1.2
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.3.2
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.17.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-bazaar                         0.1.25
  @backstage/plugin-catalog-backend-module-github  0.1.8
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.7
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.9.0
  @backstage/plugin-catalog-node                   1.2.0
  @backstage/plugin-catalog-react                  1.2.0
  @backstage/plugin-catalog                        1.6.0
  @backstage/plugin-gcalendar                      0.3.6
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-home                           0.4.26
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-permission-common              0.7.0
  @backstage/plugin-permission-node                0.7.0
  @backstage/plugin-permission-react               0.4.6
  @backstage/plugin-playlist-backend               0.2.0
  @backstage/plugin-playlist-common                0.1.1
  @backstage/plugin-playlist                       0.1.1
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.1
  @backstage/plugin-search-backend-node            1.0.3
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.0
  @backstage/plugin-search-react                   1.2.0
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-shortcuts                      0.3.2
  @backstage/plugin-stack-overflow                 0.1.6
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-todo-backend                   0.1.34
  @backstage/plugin-todo                           0.2.12
  @backstage/plugin-user-settings                  0.5.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 0.82s.

```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Bit of a gap in the docs if I'm being honest, but you'll need to follow these instructions too: https://github.com/backstage/backstage/tree/master/plugins/bazaar-backend

**Comment by prasoon-pxc** [comment]
Thanks @Rugvip , I think it is major gap in the docs,it is working after installing backend plugin of bazaar

**Comment by prasoon-pxc** [comment]
It started working after adding bazaar-backend but join button is still not working  , on clicking join button it is giving below error 
---
![image](https://user-images.githubusercontent.com/106815018/199896871-79d3c032-30d6-4a54-aae9-1b41820e3562.png)

---
```
[1] 2022-11-04T05:05:55.657Z backstage error Cannot read properties of undefined (reading 'getIdentity') type=errorHandler stack=TypeError: Cannot read properties of undefined (reading 'getIdentity')
[1]     at /home/backstage/backstage-conf-repo_my/node_modules/@backstage/plugin-bazaar-backend/dist/index.cjs.js:161:33
[1]     at handleReturn (/home/backstage/backstage-conf-repo_my/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
[1]     at /home/backstage/backstage-conf-repo_my/node_modules/express-promise-router/lib/express-promise-router.js:64:7
[1]     at handleReturn (/home/backstage/backstage-conf-repo_my/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
[1]     at /home/backstage/backstage-conf-repo_my/node_modules/express-promise-router/lib/express-promise-router.js:64:7
[1]     at Layer.handle [as handle_request] (/home/backstage/backstage-conf-repo_my/node_modules/express/lib/router/layer.js:95:5)
[1]     at next (/home/backstage/backstage-conf-repo_my/node_modules/express/lib/router/route.js:144:13)
[1]     at Route.dispatch (/home/backstage/backstage-conf-repo_my/node_modules/express/lib/router/route.js:114:3)
[1]     at Layer.handle [as handle_request] (/home/backstage/backstage-conf-repo_my/node_modules/express/lib/router/layer.js:95:5)
[1]     at /home/backstage/backstage-conf-repo_my/node_modules/express/lib/router/index.js:284:15

[1] 2022-11-04T05:26:17.246Z backstage info 192.168.63.1 - - [04/Nov/2022:05:26:17 +0000] "PUT /api/bazaar/projects/1/member/prasoon-pxc HTTP/1.1" 500 - "http://192.168.63.249:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" type=incomingRequest

```

**Comment by Rugvip** [comment]
You'll want to run `yarn tsc` to make sure everything is wired up correctly. Gonna close this one since the original issue is resolved.
