### ISSUE TITLE
🐛 Bug Report: "ReferenceError: $RefreshReg$ is not defined" when starting local backend plugin

### ISSUE THREAD

**Issue by clareliguori** [backstage/backstage#14439]
### 📜 Description

I'm upgrading a local plugin + Backstage app to 1.7, and started seeing the following error when I run `yarn workspace backend start`.

```
ReferenceError: $RefreshReg$ is not defined
```

It appears to be related to react-refresh and/or react-refresh-webpack-plugin?  I'm at a bit of a loss on how to debug this - I've been trying re-installing all my node modules, cleaning the workspace, etc, but nothing seems to be working.  I was surprised that anything related to react-refresh would run on a backend plugin.  My only wild guess is that the backstage-cli is not excluding react-refresh-webpack-plugin for backend plugins after this work? https://github.com/backstage/backstage/pull/10394

### 👍 Expected behavior

`yarn workspace backend start` successfully starts.

### 👎 Actual Behavior with Screenshots

Full error:
```
/code/aws-for-backstage/personal-backstage-app/packages/backend/dist/main.js:422
/******/ 			throw e;
         			^

ReferenceError: $RefreshReg$ is not defined
    at eval (webpack-internal:///../../plugins/aws-proton-backend/dist/index.cjs.js:206:1)
    at Object.../../plugins/aws-proton-backend/dist/index.cjs.js (/code/aws-for-backstage/personal-backstage-app/packages/backend/dist/main.js:118:1)
    at __webpack_require__ (/code/aws-for-backstage/personal-backstage-app/packages/backend/dist/main.js:419:33)
    at fn (/code/aws-for-backstage/personal-backstage-app/packages/backend/dist/main.js:579:21)
    at eval (webpack-internal:///./src/plugins/scaffolder.ts:11:102)
    at Module../src/plugins/scaffolder.ts (/code/aws-for-backstage/personal-backstage-app/packages/backend/dist/main.js:85:1)
    at __webpack_require__ (/code/aws-for-backstage/personal-backstage-app/packages/backend/dist/main.js:419:33)
    at fn (/code/aws-for-backstage/personal-backstage-app/packages/backend/dist/main.js:579:21)
    at eval (webpack-internal:///./src/index.ts:11:77)
    at Module../src/index.ts (/code/aws-for-backstage/personal-backstage-app/packages/backend/dist/main.js:19:1)
```

Relevant snippet from `packages/backend/dist/main.js` where I found `RefreshReg`:
```
var Router__default = /*#__PURE__*/ _interopDefaultLegacy(Router);\n_c = Router__default;\nvar fs__default = /*#__PURE__*/ _interopDefaultLegacy(fs);\nclass AwsProtonApi {....ctx.logger.info(`Successfully created service ${resp.service.arn}`);\n                ctx.output(\"arn\", `${resp.service.arn}`);\n            }\n        }\n    });\n};\nexports.createAwsProtonServiceAction = createAwsProtonServiceAction;\nexports.createRouter = createRouter; //# sourceMappingURL=index.cjs.js.map\nvar _c;\n$RefreshReg$(_c, \"Router__default\");
```

Relevant snippet from `plugins/aws-proton-backend/dist/index.cjs.js`:
```
function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var express__default = /*#__PURE__*/_interopDefaultLegacy(express);
var Router__default = /*#__PURE__*/_interopDefaultLegacy(Router);
var fs__default = /*#__PURE__*/_interopDefaultLegacy(fs);

class AwsProtonApi {
....
        ctx.logger.info(`Successfully created service ${resp.service.arn}`);
        ctx.output("arn", `${resp.service.arn}`);
      }
    }
  });
};

exports.createAwsProtonServiceAction = createAwsProtonServiceAction;
exports.createRouter = createRouter;
//# sourceMappingURL=index.cjs.js.map
```

### 👟 Reproduction steps

If it helps, this is how I'm setting up my workspace:
https://github.com/awslabs/aws-proton-plugins-for-backstage/blob/main/docs/developing.md

### 🖥️ Your Environment

```
$ yarn backstage-cli info
yarn run v1.22.18
$ /home/ANT.AMAZON.COM/liguori/code/aws-for-backstage/personal-backstage-app/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.0-52-generic - linux/x64
node: v14.21.0
yarn: 1.22.18
cli:  0.20.0 (installed)
backstage:  1.7.1

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.2
  @backstage/backend-plugin-api                    0.1.3
  @backstage/backend-tasks                         0.3.6
  @backstage/catalog-client                        1.1.1
  @backstage/catalog-model                         1.1.2
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0
  @backstage/config-loader                         1.1.5
  @backstage/config                                1.0.3
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2
  @backstage/core-plugin-api                       1.0.7
  @backstage/dev-utils                             1.0.7
  @backstage/errors                                1.1.2
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.3.2
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.17.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.7
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.9.0
  @backstage/plugin-catalog-node                   1.2.0
  @backstage/plugin-catalog-react                  1.2.0
  @backstage/plugin-catalog                        1.6.0
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-permission-common              0.7.0
  @backstage/plugin-permission-node                0.7.0
  @backstage/plugin-permission-react               0.4.6
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.1
  @backstage/plugin-search-backend-node            1.0.3
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.0
  @backstage/plugin-search-react                   1.2.0
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-user-settings                  0.5.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by jhaals** [comment]
Hi Clare, sorry to hear that you're having trouble. That indeed looks like react refresh is trying to hook into something that it shouldn't. Could it be that you have a plugin without a role or perhaps importing a frontend plugin in the backend? 

Backend plugins should include the following in package.json
```json
  "backstage": {
    "role": "backend-plugin"
  },
```

**Comment by clareliguori** [comment]
This is my package.json:
https://github.com/awslabs/aws-proton-plugins-for-backstage/blob/main/plugins/aws-proton-backend/package.json

I confirmed it does have the `backend-plugin` role declared, and it doesn't look like I'm importing any frontend-related packages:
```json
  "dependencies": {
    "@aws-sdk/client-proton": "^3.63.0",
    "@aws-sdk/client-sts": "^3.63.0",
    "@aws-sdk/credential-provider-node": "^3.63.0",
    "@aws-sdk/util-arn-parser": "^3.52.0",
    "@backstage/backend-common": "^0.15.2",
    "@backstage/config": "^1.0.3",
    "@backstage/plugin-scaffolder-backend": "^1.7.0",
    "@types/express": "*",
    "express": "^4.17.1",
    "express-promise-router": "^4.1.0",
    "fs-extra": "^10.0.1",
    "winston": "^3.7.1",
    "yn": "^4.0.0"
  },
  "devDependencies": {
    "@backstage/cli": "^0.20.0",
    "@backstage/dev-utils": "^1.0.7",
    "@types/fs-extra": "^9.0.13",
    "@types/glob": "^8.0.0",
    "@types/jest": "^29.0.0",
    "@types/mock-fs": "^4.13.1",
    "@types/supertest": "^2.0.8",
    "aws-sdk-client-mock": "^2.0.0",
    "mock-fs": "^5.1.2",
    "msw": "^0.47.3",
    "supertest": "^6.2.2"
  },
```

**Comment by Rugvip** [comment]
This is likely due to the [browser](https://github.com/awslabs/aws-proton-plugins-for-backstage/blob/755d8f597341435b04cdd2d56cd5bf288a20144a/plugins/aws-proton-backend/rollup.config.js#L31) field in your rollup config. In combination with not marking dependencies as external you likely get browser-only code inlined from your dependencies into `plugins/aws-proton-backend/dist/index.cjs.js`.

How come you have a separate rollup config? Is there something you wanted to override from `backstage-cli package build`? Also want to point out that the [main and types](https://github.com/awslabs/aws-proton-plugins-for-backstage/blob/755d8f597341435b04cdd2d56cd5bf288a20144a/plugins/aws-proton-backend/package.json#L5-L6) fields should be pointing to `src/index.ts` instead in our usual setup. There's more info about our build system architecture build process [here](https://backstage.io/docs/local-dev/cli-build-system#building) and publishing details [here](https://backstage.io/docs/local-dev/cli-build-system#publishing).

**Comment by clareliguori** [comment]
Ahhhhhh thank you for finding that!  This repo went through a LOT of hacking to try to get things working initially, so I think it's probably just left over from that.  Will confirm that removing that fixes things

**Comment by clareliguori** [comment]
That did indeed fix the issue, thanks!
