### ISSUE TITLE
🐛 Bug Report: ElasticSearch errors generate orphan indexes

### ISSUE THREAD

**Issue by sakorkko** [backstage/backstage#14810]
### 📜 Description

Created a new CollatorFactory for our documents. 
When the documents are not available, there is no way to stop the schedule or handle the error in ElasticSearch.
This generates an orphan index, and when the new collator run is ran, that old index is not cleaned up because the aliases were not written.
This generates indexes, which generates shards and eventually the max shard count goes over a limit and breaks elastic.

The elasticsearch plugin should handle these errorcases correctly, and cleanup old indices.

A bonus would be to revert to the old index if an error happens when generating a new one.

I can help with a PR, but I'm not good enough yet to see where the problem is. I don't however have the luxury of lots of extra time.

### 👍 Expected behavior

When a collatorfactory has an error, the error should be handled correctly.

### 👎 Actual Behavior with Screenshots

![Screenshot 2022-11-23 at 13 03 21](https://user-images.githubusercontent.com/17155973/203531340-35bfaf62-f4a5-4a3f-8fcf-4e32fadec3c9.png)

Logs:
```typescript
[1] 2022-11-23T11:07:20.185Z search info Collating documents for somedocument via SomeDocumentPipelineCollatorFactory type=plugin documentType=somedocument
[1] 2022-11-23T11:07:20.191Z backstage info Execute SomeDocument Search Collator 
[1] 2022-11-23T11:07:20.192Z search info Started indexing documents for index somedocument type=plugin documentType=somedocument
[1] 2022-11-23T11:07:20.257Z search error Failed to index documents for type somedocument index_not_found_exception: [index_not_found_exception] Reason: no such index [somedocument-index__1669201640187] type=plugin name=ResponseError meta=[object Object] stack=ResponseError: index_not_found_exception: [index_not_found_exception] Reason: no such index [somedocument-index__1669201640187]
[1]     at onBody (/Users/sakorkko/rd/clean-backstage/node_modules/@elastic/elasticsearch/lib/Transport.js:367:23)
[1]     at IncomingMessage.onEnd (/Users/sakorkko/rd/clean-backstage/node_modules/@elastic/elasticsearch/lib/Transport.js:291:11)
[1]     at IncomingMessage.emit (node:events:525:35)
[1]     at IncomingMessage.emit (node:domain:489:12)
[1]     at endReadableNT (node:internal/streams/readable:1358:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[1] 2022-11-23T11:07:20.257Z search error Collating documents for somedocument failed: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [somedocument-index__1669201640187]","resource.type":"index_or_alias","resource.id":"somedocument-index__1669201640187","index_uuid":"_na_","index":"somedocument-index__1669201640187"}],"type":"index_not_found_exception","reason":"no such index [somedocument-index__1669201640187]","resource.type":"index_or_alias","resource.id":"somedocument-index__1669201640187","index_uuid":"_na_","index":"somedocument-index__1669201640187"},"status":404} type=plugin documentType=somedocument
[1] 2022-11-23T11:07:20.258Z search error index_not_found_exception: [index_not_found_exception] Reason: no such index [somedocument-index__1669201640187] type=taskManager task=search_index_somedocument name=ResponseError meta=[object Object] stack=ResponseError: index_not_found_exception: [index_not_found_exception] Reason: no such index [somedocument-index__1669201640187]
[1]     at onBody (/Users/sakorkko/rd/clean-backstage/node_modules/@elastic/elasticsearch/lib/Transport.js:367:23)
[1]     at IncomingMessage.onEnd (/Users/sakorkko/rd/clean-backstage/node_modules/@elastic/elasticsearch/lib/Transport.js:291:11)
[1]     at IncomingMessage.emit (node:events:525:35)
[1]     at IncomingMessage.emit (node:domain:489:12)
[1]     at endReadableNT (node:internal/streams/readable:1358:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[1] 2022-11-23T11:07:25.280Z search info Collating documents for somedocument via SomeDocumentPipelineCollatorFactory type=plugin documentType=somedocument
[1] 2022-11-23T11:07:25.281Z backstage info Execute SomeDocument Search Collator 
[1] 2022-11-23T11:07:25.281Z search info Started indexing documents for index somedocument type=plugin documentType=somedocument
[1] 2022-11-23T11:07:25.373Z search info Indexing completed for index somedocument in 0.1s type=plugin documentType=somedocument total=0 failed=0 retry=0 successful=0 noop=0 time=91 bytes=0 aborted=false
[1] 2022-11-23T11:07:25.405Z search info Removing stale search indices 0=somedocument-index__1669201593280 type=plugin documentType=somedocument
[1] 2022-11-23T11:07:25.441Z search info Collating documents for somedocument succeeded type=plugin documentType=somedocument
```

The errors generate orphan indices and shards.

### 👟 Reproduction steps

I've created a vanilla backstage repo with create-app. The version is 1.8.0.

https://github.com/sakorkko/backstage-example/tree/main
You can reproduce the error there, if needed.

More comments can be found in the file [`packages/backend/src/plugins/documentPipelineFactory.ts`](https://github.com/sakorkko/backstage-example/blob/main/packages/backend/src/plugins/documentPipelineFactory.ts)

The bug is not active, but uncommenting lines activates it.

### 📃 Provide the context for the Bug.

I'm using a VScode extension cweijan.vscode-database-client2 to browse the elasticsearch and postgres database if that helps.

Node 16.17.0
Yarn 1.22.19

### 🖥️ Your Environment

See the reproduce step, it has a repo ready for testing.
It's using version 1.8.0.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by iamEAP** [comment]
Hey @sakorkko! Heads up that I think _some_ of the issues in here will be resolved via #14938, but possibly not all of them.

 I'm going to take a deeper look at your repro repo now.

**Comment by sakorkko** [comment]
#14938 definitely is a relating issue to this one nonetheless. Good to see that's being looked at as well.

**Comment by iamEAP** [comment]
Thanks for the super clear repro @sakorkko!  Think I got to the bottom of things, with a solution here: https://github.com/backstage/backstage/pull/14957.  Feel free to test if you're able.

**Comment by sakorkko** [comment]
Ohh, this makes sense. Tested on our project and it seems to work. Thank you @iamEAP!

**Comment by freben** [comment]
Nice! Closing as fixed. Please let us know if the problem persists.
