### ISSUE TITLE
🐛 Bug Report: Cannot find module '@backstage/plugin-catalog-backend-module-github'

### ISSUE THREAD

**Issue by Ryang20718** [backstage/backstage#15096]
### 📜 Description

Unable to load backend-module-github even adding the module.

### 👍 Expected behavior

We should be able to load the module after adding via yarn add

### 👎 Actual Behavior with Screenshots

```
yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
[1] Build succeeded
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3003/, http://[::1]:3003/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/ryang/repos/backstage/backstage-test/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[1] /Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:323
[1] /******/ 			throw e;
[1]          			^
[1]
[1] Error: Cannot find module '@backstage/plugin-catalog-backend-module-github'
[1]     at webpackMissingModule (webpack-internal:///./src/plugins/catalog.ts:9:50)
[1]     at eval (webpack-internal:///./src/plugins/catalog.ts:9:172)
[1]     at ./src/plugins/catalog.ts (/Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:52:1)
[1]     at __webpack_require__ (/Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:320:33)
[1]     at fn (/Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:480:21)
[1]     at eval (webpack-internal:///./src/index.ts:10:74)
[1]     at ./src/index.ts (/Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:19:1)
[1]     at __webpack_require__ (/Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:320:33)
[1]     at /Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:1299:37
[1]     at Object.<anonymous> (/Users/ryang/repos/backstage/-backstage-test/packages/backend/dist/main.js:1301:12) {
[1]   code: 'MODULE_NOT_FOUND'
[1] }
[1]
```

### 👟 Reproduction steps

Create a new app in the env below

```
npx @backstage/create-app
```

Add github discovery https://backstage.io/docs/integrations/github/discovery

```
yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-github
```

```
yarn dev
```

hit issue when trying to load

```
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
[1] Build succeeded
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3003/, http://[::1]:3003/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/ryang/repos/backstage/backstage-test/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[1] /Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:323
[1] /******/ 			throw e;
[1]          			^
[1]
[1] Error: Cannot find module '@backstage/plugin-catalog-backend-module-github'
[1]     at webpackMissingModule (webpack-internal:///./src/plugins/catalog.ts:9:50)
[1]     at eval (webpack-internal:///./src/plugins/catalog.ts:9:172)
[1]     at ./src/plugins/catalog.ts (/Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:52:1)
[1]     at __webpack_require__ (/Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:320:33)
[1]     at fn (/Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:480:21)
[1]     at eval (webpack-internal:///./src/index.ts:10:74)
[1]     at ./src/index.ts (/Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:19:1)
[1]     at __webpack_require__ (/Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:320:33)
[1]     at /Users/ryang/repos/backstage/backstage-test/packages/backend/dist/main.js:1299:37
[1]     at Object.<anonymous> (/Users/ryang/repos/backstage/-backstage-test/packages/backend/dist/main.js:1301:12) {
[1]   code: 'MODULE_NOT_FOUND'
[1] }
[1]
```

### 📃 Provide the context for the Bug.

I'm trying to test out backstage

### 🖥️ Your Environment

```
yarn backstage-cli info
yarn run v1.22.19
$ /Users/ryang/repos/backstage/backstage-test/node_modules/.bin/backstage-cli info
OS:   Darwin 22.1.0 - darwin/arm64
node: v18.8.0
yarn: 1.22.19
cli:  0.21.1 (installed)
backstage:  1.8.0

Dependencies:
  @backstage/app-defaults                          1.0.8
  @backstage/backend-common                        0.16.0
  @backstage/backend-plugin-api                    0.1.4
  @backstage/backend-tasks                         0.3.7
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.21.1
  @backstage/config-loader                         1.1.6
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.6
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.11
  @backstage/plugin-app-backend                    0.3.38
  @backstage/plugin-auth-backend                   0.17.1
  @backstage/plugin-auth-node                      0.2.7
  @backstage/plugin-catalog-backend-module-github  0.2.1
  @backstage/plugin-catalog-backend                1.5.1
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.23
  @backstage/plugin-catalog-import                 0.9.1
  @backstage/plugin-catalog-node                   1.2.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.1
  @backstage/plugin-github-actions                 0.5.11
  @backstage/plugin-org                            0.6.1
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.1
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.32
  @backstage/plugin-scaffolder-backend             1.8.0
  @backstage/plugin-scaffolder-common              1.2.2
  @backstage/plugin-scaffolder                     1.8.0
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-node            1.0.4
  @backstage/plugin-search-backend                 1.1.1
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.1
  @backstage/plugin-search                         1.0.4
  @backstage/plugin-tech-radar                     0.5.18
  @backstage/plugin-techdocs-backend               1.4.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.6
  @backstage/plugin-techdocs-node                  1.4.2
  @backstage/plugin-techdocs-react                 1.0.6
  @backstage/plugin-techdocs                       1.4.0
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.7
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2
✨  Done in 0.73s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by zodvik** [comment]
@Ryang20718 what was the resolution? running into the same issue.

**Comment by prateek45** [comment]
Can someone please mention the resolution. running into same issue

**Comment by Andrei101Ru** [comment]
Opened another one issue: https://github.com/backstage/backstage/issues/20785
