### ISSUE TITLE
🐛 Bug Report: New version of backstage breaks after install

### ISSUE THREAD

**Issue by ruieloi** [backstage/backstage#15148]
### 📜 Description

Following the steps of https://backstage.io/docs/getting-started/running-backstage-locally

When I try the yarn dev backstage backend breaks on search schedule.

### 👍 Expected behavior

Backstage backend fully working

### 👎 Actual Behavior with Screenshots

` 2022-12-09T16:40:41.708Z search info Starting all scheduled search tasks. type=plugin
[1] Backend failed to start up ReferenceError: AbortController is not defined
[1]     at eval (webpack-internal:///../../plugins/search-backend-node/src/Scheduler.ts:46:37)
[1]     at Array.forEach (<anonymous>)
[1]     at Scheduler.start (webpack-internal:///../../plugins/search-backend-node/src/Scheduler.ts:45:36)
[1]     at createPlugin (webpack-internal:///./src/plugins/search.ts:99:15)
[1]     at async main (webpack-internal:///./src/index.ts:169:30)
[0] webpack compiled successfully`

![image](https://user-images.githubusercontent.com/2378539/206751498-953642d0-0acc-408b-843d-122e844533ca.png)

### 👟 Reproduction steps

1. git clone --depth 1 https://github.com/backstage/backstage.git
2. yarn install
3. yarn dev

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Thank you for reporting! 👍 

We currently support either Node.js v16 or v18, you'll need to be running one of those versions.

**Comment by ruieloi** [comment]
You are right, I had to downgrade for another project and forgot to update again.
Sorry for the trouble.
Thank you!
