### ISSUE TITLE
🐛 Bug Report: Cannot read properties of null (reading '_location') issue on unit tests after upgrade to v1.8.3

### ISSUE THREAD

**Issue by luxliu** [backstage/backstage#15266]
### 📜 Description

I got some weird unit tests issue after upgrade backstage from 1.5.1 to 1.8.3. I followed the instruction and upgrade helper to do this.
The error happens when I run `yarn test:all`, and my own backend plugin `router.test.ts` can't pass the unit tests. I followed the approach from backstage, which is to use `express` and `supertest` to mock the api call. (eg: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/service/router.test.ts#L180)

### 👍 Expected behavior

It should pass the unit tests like before as I didn't change any code except the upgrading part and dependency versions

### 👎 Actual Behavior with Screenshots

Here is the error stack for the error of `router.test.ts`:
```
TypeError: Cannot read properties of null (reading '_location')

      at Window.get location [as location] (../../../node_modules/jsdom/lib/jsdom/browser/Window.js:376:79)
      at getRequestCookies (../../../node_modules/msw/src/utils/request/getRequestCookies.ts:31:14)
      at setRequestCookies (../../../node_modules/msw/src/utils/request/parseIsomorphicRequest.ts:17:26)
      at parseIsomorphicRequest (../../../node_modules/msw/src/utils/getResponse.ts:32:4)
      at NodeClientRequest.resolver (../../../node_modules/msw/src/node/createSetupServer.ts:65:11)
      at NodeClientRequest.<anonymous> (../../../node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:130:28)
      at step (../../../node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js:48:23)
      at Object.next (../../../node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js:29:53)
      at ../../../node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js:23:71
      at Object.<anonymous>.__awaiter (../../../node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js:19:12)
      at ../../../node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:130:11
      at Object.<anonymous>.exports.until (../../../node_modules/@open-draft/until/lib/until.js:10:28)
      at NodeClientRequest.Object.<anonymous>.NodeClientRequest.end (../../../node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:130:5)
      at Test.end [as _end] (../../../node_modules/superagent/src/node/index.js:1261:9)
      at Test._end [as end] (../../../node_modules/superagent/src/node/index.js:987:8)
      at Test.end (../../../node_modules/supertest/lib/test.js:118:11)
      at end (../../../node_modules/superagent/src/request-base.js:285:12)
      at Test.Object.<anonymous>.RequestBase.then (../../../node_modules/superagent/src/request-base.js:267:31)
```

**The weird thing is  that when I run `yarn test:All` most time it happens in one backend plugin, but sometimes another backend plugin also has this issue. Occationally the test can pass.**

### 👟 Reproduction steps

No idea how to reproduce it as we do have a bunch of own plugins.

### 📃 Provide the context for the Bug.

Seems the issue maybe from the race condition of `jest` and `supertest`. So I modified the `test:all` to use `--testNamePattern` to only run those particular router test suits then run the rest unit tests.
```
...
"test:all": "yarn test:all:router && yarn test:all:non-router",
"test:all:router": "backstage-cli repo test --coverage --testNamePattern=RouterTest",
"test:all:non-router": "backstage-cli repo test --coverage --testNamePattern='^(?!.*RouterTest).*$' --testPathIgnorePatterns=packages/componenttest",
...
```
It's working now but I think it's just a temporary solution

### 🖥️ Your Environment

```OS:   Darwin 21.4.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.15
cli:  0.21.1 (installed)
backstage:  1.8.3

Dependencies:
  @backstage/app-defaults                                  1.0.8
  @backstage/backend-common                                0.15.2, 0.16.0
  @backstage/backend-plugin-api                            0.1.4
  @backstage/backend-tasks                                 0.3.7
  @backstage/catalog-client                                1.1.2
  @backstage/catalog-model                                 1.1.3
  @backstage/cli-common                                    0.1.10
  @backstage/cli                                           0.21.1
  @backstage/config-loader                                 1.1.6
  @backstage/config                                        1.0.4
  @backstage/core-app-api                                  1.2.0
  @backstage/core-components                               0.12.0
  @backstage/core-plugin-api                               1.1.0
  @backstage/dev-utils                                     1.0.8
  @backstage/errors                                        1.1.3
  @backstage/integration-react                             1.1.6
  @backstage/integration                                   1.4.0
  @backstage/plugin-api-docs                               0.8.11
  @backstage/plugin-app-backend                            0.3.38
  @backstage/plugin-auth-backend                           0.17.1
  @backstage/plugin-auth-node                              0.2.7
  @backstage/plugin-badges-backend                         0.1.32
  @backstage/plugin-badges                                 0.2.35
  @backstage/plugin-catalog-backend-module-msgraph         0.4.4
  @backstage/plugin-catalog-backend                        1.5.1
  @backstage/plugin-catalog-common                         1.0.8
  @backstage/plugin-catalog-graph                          0.2.23
  @backstage/plugin-catalog-import                         0.9.1
  @backstage/plugin-catalog-node                           1.2.1
  @backstage/plugin-catalog-react                          1.2.1
  @backstage/plugin-catalog                                1.6.1
  @backstage/plugin-explore-react                          0.0.23
  @backstage/plugin-explore                                0.3.42
  @backstage/plugin-github-actions                         0.5.11
  @backstage/plugin-jenkins-backend                        0.1.28
  @backstage/plugin-jenkins-common                         0.1.10
  @backstage/plugin-jenkins                                0.7.10
  @backstage/plugin-kubernetes-backend                     0.8.0
  @backstage/plugin-kubernetes-common                      0.4.4
  @backstage/plugin-kubernetes                             0.7.4
  @backstage/plugin-org                                    0.6.1
  @backstage/plugin-permission-common                      0.7.1
  @backstage/plugin-permission-node                        0.7.1
  @backstage/plugin-permission-react                       0.4.7
  @backstage/plugin-proxy-backend                          0.2.32
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.2.13
  @backstage/plugin-scaffolder-backend                     1.8.0
  @backstage/plugin-scaffolder-common                      1.2.2
  @backstage/plugin-scaffolder                             1.8.0
  @backstage/plugin-search-backend-module-pg               0.4.2
  @backstage/plugin-search-backend-node                    1.0.4
  @backstage/plugin-search-backend                         1.1.1
  @backstage/plugin-search-common                          1.1.1
  @backstage/plugin-search-react                           1.2.1
  @backstage/plugin-search                                 1.0.4
  @backstage/plugin-tech-radar                             0.5.18
  @backstage/plugin-techdocs-backend                       1.4.1
  @backstage/plugin-techdocs-module-addons-contrib         1.0.6
  @backstage/plugin-techdocs-node                          1.4.2
  @backstage/plugin-techdocs-react                         1.0.6
  @backstage/plugin-techdocs                               1.4.0
  @backstage/plugin-user-settings                          0.5.1
  @backstage/release-manifests                             0.0.7
  @backstage/test-utils                                    1.2.2
  @backstage/theme                                         0.2.16
  @backstage/types                                         1.0.1
  @backstage/version-bridge                                1.0.2
```
And I use `"supertest": "^6.3.3"` and `jest@29.3.1` from `@backstage/cli@0.21.1`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Sorry to hear that you're having trouble. From the stacktrace this looks suspiciously "frontend" with jsdom and accessing of location from window. Is there possibly a mix in your tests that can be causing trouble?

**Comment by luxliu** [comment]
> Sorry to hear that you're having trouble. From the stacktrace this looks suspiciously "frontend" with jsdom and accessing of location from window. Is there possibly a mix in your tests that can be causing trouble?


Hi @jhaals , thanks for the reply. Yeah it's weird. 
And I feel there shouldn't be a mix in the test. Following is the unit test of one router:
```import { getVoidLogger } from '@backstage/backend-common';
import { ConfigReader } from '@backstage/config';
import express from 'express';
import request from 'supertest';
import * as snykReport from '../snyk/report';

jest.mock('../snyk/report');
import { createRouter } from './router';

describe('createRouter', () => {
  let app: express.Express;

  beforeAll(async () => {
    const GROUP_ID = 'test-group-id';
    const TOKEN = 'test-token';
    const baseUrl = 'https://localhost:8080';
    const uiBaseUrl = 'https://localhost:80';
    const config = new ConfigReader({
      twg: {
        snyk: {
          baseUrl,
          uiBaseUrl,
          token: TOKEN,
          groupId: GROUP_ID,
        },
      },
    });

    const router = await createRouter({
      logger: getVoidLogger(),
      config,
    });
    app = express().use(router);
  });

  beforeEach(() => {
    jest.resetAllMocks();
  });

  describe('RouterTest', () => {
    describe('GET /snyk/:componentName/report-url', () => {
      it('return response as 200 status', async () => {
        jest.spyOn(snykReport, 'getReportUrl').mockResolvedValue('report-url');
        const response = await request(app).get('/snyk/abc/report-url');
        expect(response.status).toEqual(200);
        expect(response.body).toEqual({ url: 'report-url' });
      });
    });
  });
});```
If you test it individually via `backstage-cli repo test` it's always fine. Tho when I use `backstage-cli repo test --coverage` to test all unit tests, these our own `router.test.ts` test suits MAYBE happen the issues above.

**Comment by freben** [comment]
What is the `role` set to in the `package.json` of the failing test's package?

**Comment by luxliu** [comment]
> What is the `role` set to in the `package.json` of the failing test's package?

It's `backend-plugin`

**Comment by Rugvip** [comment]
I'm feeling this might be related to MSW teardown, perhaps MSW is still active an hooked into the request path when re-using the Jest workers for followup tests?

Are you using the `setupRequestMockHandlers(server)` utility from `@backstage/backend-test-utils` or otherwise calling `server.close()` after the tests are done in all places where you use MSW?

**Comment by luxliu** [comment]
I use `setupRequestMockHandlers` from **`@backstage/test-utils`** and its version is 1.2.3
