### ISSUE TITLE
🐛 Bug Report: backstage error Missing index for techdocs.

### ISSUE THREAD

**Issue by NPhGit** [backstage/backstage#15260]
### 📜 Description

I've successfully setup techdocs as follows

*Run backstage in docker and use techdocs by local mode by follow the guide or github issue I found
-----app-config.yaml-----------------------------------
techdocs:
&nbsp;&nbsp;builder: "local"
&nbsp;&nbsp;generator:
&nbsp;&nbsp;&nbsp;&nbsp;runIn: "local"
&nbsp;&nbsp;publisher:
&nbsp;&nbsp;&nbsp;&nbsp;type: "local"
-----Dockerfile part of installing mkdocs-----------------------------------
RUN set -xe \
&nbsp;&nbsp;&nbsp;&nbsp;&& apt-get update -y \
&nbsp;&nbsp;&nbsp;&nbsp;&& apt-get install -y python3-pip
RUN pip install --upgrade pip && pip install mkdocs-techdocs-core

-----
Repo File Structure
-----
catalog-info.yaml
mkdocs.yml
docs/(index.md,a.md,b.md)

-----
catalog-info.yaml
-----
metadata:
&nbsp;&nbsp;...
&nbsp;&nbsp;annotations:
&nbsp;&nbsp;&nbsp;&nbsp;backstage.io/techdocs-ref: dir:.

-----
mkdocs.yml
-----
site_name: 'Techdocs example'
site_description: 'Description A'

nav:
  \- Introduction: index.md
  \- Page A: a.md
  \- Page B: b.md

plugins:
  \- techdocs-core

markdown file is simple table

### 👍 Expected behavior

There should be no error. Search bar should work.
I'm not sure about "index" in the error. Is it search index or index page/index.md which I have as default in example without changing name. The page is also build&rendered already.

*If it's also possible, I would like to ask how to adjust techdocs style a bit. For example, add cell border. I try to add global css to make vertical line between column. But I cant make it work. Not sure how it should be done in Backstage.

### 👎 Actual Behavior with Screenshots

Document is finally rendered. But there's this error comes up every time I view techdocs.

`
backstage error Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation. type=errorHandler name=MissingIndexError cause=undefined stack=MissingIndexError: Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem 
during index creation.
`

And search bar says "No results found" which I suspect it's because of this error too. I try to search: Pag or Page and it shows "No results found"

![No Index](https://user-images.githubusercontent.com/38721539/207945097-93ed6120-5fe5-4629-96cb-8aa331af8019.PNG)
![No Index2](https://user-images.githubusercontent.com/38721539/207945113-e6d1e2ae-722a-4d2e-b8e7-12c419ea1cc9.PNG)

### 👟 Reproduction steps

1. Setup techdocs follow the guide
2. Create repo structure as default in the guide.

### 🖥️ Your Environment

"@backstage/cli@^0.18.0": version "0.18.1"
"@backstage/plugin-techdocs@^1.3.0": version "1.3.2"
"@backstage/plugin-techdocs-backend@^1.2.0":  version "1.3.0"
"@backstage/plugin-techdocs-node@^1.4.0":  version "1.4.0"
"@backstage/plugin-techdocs-react@^1.0.2", "@backstage/plugin-techdocs-react@^1.0.4":  version "1.0.4"

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ronabet** [comment]
+1

**Comment by rackerchandra** [comment]
+1

**Comment by marct83** [comment]
Did you ever find a resolution to this?

**Comment by ivanaguilario** [comment]
Ok so after debugging I've found the possible problem in my case.

It appears that the `DefaultTechDocsCollator` is [generating](https://github.com/backstage/backstage/blob/49ea9cf086192fa9b9ccc41b595d1307b54c1841/plugins/techdocs-backend/src/search/DefaultTechDocsCollator.ts#L104) a JWT with a [`HS256` algorithm](https://github.com/backstage/backstage/blob/49ea9cf086192fa9b9ccc41b595d1307b54c1841/packages/backend-common/src/tokens/ServerTokenManager.ts#L122). However, by default, the authentication middleware [checks only `ES256`](https://github.com/backstage/backstage/blob/49ea9cf086192fa9b9ccc41b595d1307b54c1841/plugins/auth-node/src/DefaultIdentityClient.ts#L76).

I've tried forcing the auth middleware to check `HS256` too, modifying `packages/backend/src/auth.ts` like so:

```typescript
const identity = IdentityClient.create({
    discovery,
    issuer: await discovery.getExternalBaseUrl('auth'),
    algorithms: ['ES256, 'HS256']
 });
```

However, `jose`, the library checking validity of tokens, [doesn't validate `HS256`](https://github.com/panva/jose/blob/72166fd804dbad797df78b1deda8a9c8189efbd8/src/jwks/local.ts#L18) in this particular instance.

This is as much as I've been able to see. My knowledge of backstage is pretty limited.

**Comment by ivanaguilario** [comment]
I've managed to fix this by updating my `packages/backend/src/auth.ts` as explained [here](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md) (ours was outdated). This was possible because we authenticate API requests.

**Comment by ivanaguilario** [comment]
I was able to successfully fix this by updating our auth middleware that we use to authenticate API requests. Here's the latest version of the docs on that: https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md

**Comment by hamzashoukat94** [comment]
I'm not authenticating but still I'm getting the same issue

**Comment by asthmatic-fejo** [comment]
We are getting the same error but with only ONE user in particular. We will be in production soon and we need solve this first. Any idea ?

**Comment by joaquin386** [comment]
Same issue from my side
```
[1] 2023-10-08T11:36:19.774Z backstage error Request failed with status 500 Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation. type=errorHandler cause=undefined name=MissingIndexError stack=MissingIndexError: Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation.
```

**Comment by dimisjim** [comment]
I am getting this issue, and have followed the guide for a host build + k8s deployment (I anyway get the same MissingIndexError when running the container locally too).

some extra logs:

```
{"documentType":"adr","level":"warn","message":"Index for adr was not created: indexer received 0 documents","plugin":"search","service":"backstage","type":"plugin"}
{"documentType":"adr","level":"info","message":"Collating documents for adr succeeded","plugin":"search","service":"backstage","type":"plugin"}
{"level":"debug","message":"task: search_index_adr will next occur around 2023-11-02T15:26:07.968+00:00","service":"backstage","task":"search_index_adr","type":"taskManager"}
{"documentType":"software-catalog","level":"warn","message":"Index for software-catalog was not created: indexer received 0 documents","plugin":"search","service":"backstage","type":"plugin"}
{"documentType":"software-catalog","level":"info","message":"Collating documents for software-catalog succeeded","plugin":"search","service":"backstage","type":"plugin"}
{"level":"debug","message":"task: search_index_software_catalog will next occur around 2023-11-02T15:26:07.990+00:00","service":"backstage","task":"search_index_software_catalog","type":"taskManager"}
{"documentType":"techdocs","level":"warn","message":"Index for techdocs was not created: indexer received 0 documents","plugin":"search","service":"backstage","type":"plugin"}
```

**Comment by aalexlindner** [comment]
Maybe try importing `DefaultTechDocsCollatorFactory` from `@backstage/plugin-search-backend-module-techdocs` instead of `@backstage/plugin-techdocs-backend` in your packages/backend/src/plugins/search.ts. At least this is what helped me fix this issue.

`import { DefaultTechDocsCollatorFactory } from '@backstage/plugin-search-backend-module-techdocs';`

instead of

`import { DefaultTechDocsCollatorFactory } from '@backstage/plugin-techdocs-backend';`

**Comment by dimisjim** [comment]
@aalexlindner thanks for the pointers but code in search.ts already uses plugin-search-backend-module-techdocs.

**Comment by awanlin** [comment]
I'm reopening this issue as it's still happening with  `1.21.0`. Also, I've found if you disable search then it works, the error specifically notes - `LunrSearchEngine` - which is the default in memory search engine. Not syaing this is the fix but points us in some direction towards one. I haven't tested this using Postgres as the search engine but that would be good to check. I'm also not sure why this is an issue only in Docker and not locally, at least I can't reproduce this locally.

Including the full error and some of the logs before it as they might be helpful as well:

```text
2023-12-28T13:29:59.413Z backstage info ::ffff:192.168.65.1 - - [28/Dec/2023:13:29:59 +0000] "GET /api/techdocs/static/docs/default/component/plant/index.html HTTP/1.1" 404 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" type=incomingRequest
2023-12-28T13:29:59.426Z backstage info ::ffff:127.0.0.1 - - [28/Dec/2023:13:29:59 +0000] "GET /api/catalog/entities/by-name/component/default/plant HTTP/1.1" 200 678 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
2023-12-28T13:29:59.437Z backstage info ::ffff:127.0.0.1 - - [28/Dec/2023:13:29:59 +0000] "GET /api/catalog/entities/by-name/component/default/plant HTTP/1.1" 200 678 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
2023-12-28T13:29:59.438Z backstage info ::ffff:127.0.0.1 - - [28/Dec/2023:13:29:59 +0000] "GET /api/catalog/entities/by-name/component/default/plant HTTP/1.1" 200 678 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
2023-12-28T13:29:59.440Z backstage info ::ffff:192.168.65.1 - - [28/Dec/2023:13:29:59 +0000] "GET /api/techdocs/metadata/entity/default/component/plant HTTP/1.1" 200 728 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" type=incomingRequest
2023-12-28T13:29:59.440Z techdocs info Unable to get metadata for 'component:default/plant' with error Error: Unable to read techdocs_metadata.json at /app/temp-docs/default/component/plant/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory, open '/app/temp-docs/default/component/plant/techdocs_metadata.json'; caused by Error: ENOENT: no such file or directory, open '/app/temp-docs/default/component/plant/techdocs_metadata.json' type=plugin
2023-12-28T13:29:59.443Z backstage info ::ffff:192.168.65.1 - - [28/Dec/2023:13:29:59 +0000] "GET /api/techdocs/metadata/techdocs/default/component/plant HTTP/1.1" 404 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" type=incomingRequest
2023-12-28T13:29:59.460Z backstage info ::ffff:192.168.65.1 - - [28/Dec/2023:13:29:59 +0000] "POST /api/catalog/entities/by-refs HTTP/1.1" 200 616 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" type=incomingRequest
2023-12-28T13:29:59.725Z techdocs info Could not find /app/temp-docs/default/component/plant, creating the directory. type=plugin
2023-12-28T13:29:59.740Z techdocs info Published site stored at /app/temp-docs/default/component/plant type=plugin
2023-12-28T13:29:59.743Z backstage info ::ffff:192.168.65.1 - - [28/Dec/2023:13:29:59 +0000] "GET /api/techdocs/sync/default/component/plant HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" type=incomingRequest
2023-12-28T13:29:59.746Z backstage info ::ffff:192.168.65.1 - - [28/Dec/2023:13:29:59 +0000] "GET /api/techdocs/static/docs/default/component/plant/index.html HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" type=incomingRequest
2023-12-28T13:29:59.763Z backstage info ::ffff:192.168.65.1 - - [28/Dec/2023:13:29:59 +0000] "GET /api/techdocs/static/docs/default/component/plant/assets/stylesheets/main.046329b4.min.css HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" type=incomingRequest
2023-12-28T13:29:59.769Z search info Search request received: term="", filters={"kind":"component","name":"plant","namespace":"default"}, types=techdocs, pageCursor= type=plugin
2023-12-28T13:29:59.770Z backstage error Request failed with status 500 Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation. type=errorHandler cause=undefined name=MissingIndexError stack=MissingIndexError: Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation.
    at LunrSearchEngine.query (/app/node_modules/@backstage/plugin-search-backend-node/dist/index.cjs.js:371:13)
    at /app/node_modules/@backstage/plugin-search-backend/dist/cjs/router-25d5bb35.cjs.js:478:65
    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /app/node_modules/express-promise-router/lib/express-promise-router.js:64:7
    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /app/node_modules/express-promise-router/lib/express-promise-router.js:64:7
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
2023-12-28T13:29:59.770Z backstage info ::ffff:192.168.65.1 - - [28/Dec/2023:13:29:59 +0000] "GET /api/search/query?term=&types%5B0%5D=techdocs&filters%5Bkind%5D=component&filters%5Bname%5D=plant&filters%5Bnamespace%5D=default&pageCursor= HTTP/1.1" 500 375 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" type=incomingRequest
2023-12-28T13:29:59.771Z search info Search request received: term="", filters={"kind":"component","name":"plant","namespace":"default"}, types=techdocs, pageCursor= type=plugin
 ```

**Comment by NeuralEvolution** [comment]
This may help or not, but i only started experiencing this problem when i added in search filters into the app-config
```yaml
search:
  collators:
    catalog:
      filter:
        kind: [API]
    techdocs:
      filter:
        kind: [Component]
```

**Comment by mprinold** [comment]
> This may help or not, but i only started experiencing this problem when i added in search filters into the app-config
> 
> ```yaml
> search:
>   collators:
>     catalog:
>       filter:
>         kind: [API]
>     techdocs:
>       filter:
>         kind: [Component]
> ```

So the search filters seemed to be a red herring. However after some more digging i have found that the issue is a result of this fetch call in the DefaultTechDocsCollatorFactory.
![Screenshot 2024-01-23 at 11 42 19](https://github.com/backstage/backstage/assets/145126051/d41a7ed7-9c1e-4616-a937-2086949186da)

It returns a 404 not found response. Through some trial and error it also appears to be a cold start problem as once i have booted up an instance of backstage and navigated to the docs the problem doesn't seem to appear again after closing down the backstage instance and then rebooting it up again i am getting the search indexes for the tech docs. 

Note: for testing this i've been running it locally with the following techdoc config:
```yaml
techdocs:
  builder: 'local' 
  publisher:
    type: 'local'
  generator:
    runIn: local
```

hope this helps

**Comment by mprinold** [comment]
So setting the initial delay in the scheduler in packages/backend/src/plugins/search.ts at first sight seems to have resolved the cold start issue. Though i think this needs more testing to confirm if this has completely resolved the issue. 

```
  const schedule = env.scheduler.createScheduledTaskRunner({
    frequency: { minutes: 10 },
    timeout: { minutes: 15 },
    initialDelay: { seconds: 15 },
  });
```

**Comment by mprinold** [comment]
Its also worth pointing out that this is only really an issue when using `local` configuration for `generator` and `publisher` as this generates tech doc pages on demand. So there is the possibility that the pages are not generated when trying to index. As such it is worth looking at using an object store for your tech docs so that they are built when published.

**Comment by piatkiewicz** [comment]
any updates?

**Comment by Ijaz1-Mohammed** [comment]
search error Request failed with status 500 Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation. type="errorHandler" cause=undefined name="MissingIndexError" stack="MissingIndexError: Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation.\n    at LunrSearchEngine.query (/app/node_modules/@backstage/plugin-search-backend-node/dist/engines/LunrSearchEngine.cjs.js:115:13)\n    at AuthorizedSearchEngine.query (/app/node_modules/@backstage/plugin-search-backend/dist/service/AuthorizedSearchEngine.cjs.js:88:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/@backstage/plugin-search-backend/dist/service/router.cjs.js:116:25"

i am running inside docker container. Any help is appreciated.
