### ISSUE TITLE
🐛 Bug Report: Github Webhook kills Backstage...

### ISSUE THREAD

**Issue by jrummler** [backstage/backstage#15406]
### 📜 Description

I have setup Gihub Webhooks according to the documentation. Now, when Github sends a notification, Backstage is crashing like this:
```
{"level":"info","message":"::ffff:10.42.66.218 - - [23/Dec/2022:10:02:04 +0000] \"POST /api/events/http/github HTTP/1.1\" 202 21 \"-\" \"GitHub-Hookshot/56371ad\"","service":"backstage","type":"incomingRequest"}
/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:962
      throw new Error("Not initialized");
            ^

Error: Not initialized
    at GithubEntityProvider.onRepoPush (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:962:13)
    at GithubEntityProvider.onEvent (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:954:16)
    at /app/node_modules/@backstage/plugin-events-backend/dist/index.cjs.js:29:51
    at Array.forEach (<anonymous>)
    at InMemoryEventBroker.publish (/app/node_modules/@backstage/plugin-events-backend/dist/index.cjs.js:29:16)
    at GithubEventRouter.onEvent (/app/node_modules/@backstage/plugin-events-node/dist/index.cjs.js:14:51)
    at /app/node_modules/@backstage/plugin-events-backend/dist/index.cjs.js:29:51
    at Array.forEach (<anonymous>)
    at InMemoryEventBroker.publish (/app/node_modules/@backstage/plugin-events-backend/dist/index.cjs.js:29:16)
    at /app/node_modules/@backstage/plugin-events-backend/dist/index.cjs.js:152:30
```
Looks like the connection has not been set:
```
  async onRepoPush(event) {
    var _a;
    if (!this.connection) {
      throw new Error("Not initialized");
    } 
   ...
```

### 👍 Expected behavior

Not crash! ;-)

### 👎 Actual Behavior with Screenshots

Process the change.

### 👟 Reproduction steps

Using Github Apps, configure this event:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/2248141/209311484-9bfbd188-899e-4962-9237-dbcc35e2c39e.png">

Then, enable the event webhook in Backstage (app-config.yml):
```
events:
  http:
    topics:
      - github
  modules:
    github:
      webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
```

### 🖥️ Your Environment

```
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.18.0
yarn: 1.22.19
cli:  0.22.0 (installed)
backstage:  1.9.1

Dependencies:
  @backstage/app-defaults                          1.0.10
  @backstage/backend-common                        0.17.0
  @backstage/backend-plugin-api                    0.2.0
  @backstage/backend-tasks                         0.4.0
  @backstage/catalog-client                        1.2.0
  @backstage/catalog-model                         1.1.4
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.0
  @backstage/config-loader                         1.1.7
  @backstage/config                                1.0.5
  @backstage/core-app-api                          1.3.0
  @backstage/core-components                       0.12.2
  @backstage/core-plugin-api                       1.2.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.0
  @backstage/integration-react                     1.1.8
  @backstage/integration                           1.4.1
  @backstage/plugin-api-docs                       0.8.13
  @backstage/plugin-app-backend                    0.3.39
  @backstage/plugin-auth-backend                   0.17.2
  @backstage/plugin-auth-node                      0.2.8
  @backstage/plugin-catalog-backend-module-github  0.2.2
  @backstage/plugin-catalog-backend                1.6.0
  @backstage/plugin-catalog-common                 1.0.9
  @backstage/plugin-catalog-graph                  0.2.25
  @backstage/plugin-catalog-import                 0.9.3
  @backstage/plugin-catalog-node                   1.3.0
  @backstage/plugin-catalog-react                  1.2.3
  @backstage/plugin-catalog                        1.7.1
  @backstage/plugin-events-backend-module-github   0.1.1
  @backstage/plugin-events-backend                 0.2.0
  @backstage/plugin-events-node                    0.2.0
  @backstage/plugin-github-actions                 0.5.13
  @backstage/plugin-org                            0.6.3
  @backstage/plugin-permission-common              0.7.2
  @backstage/plugin-permission-node                0.7.2
  @backstage/plugin-permission-react               0.4.8
  @backstage/plugin-proxy-backend                  0.2.33
  @backstage/plugin-scaffolder-backend             1.9.0
  @backstage/plugin-scaffolder-common              1.2.3
  @backstage/plugin-scaffolder                     1.9.1
  @backstage/plugin-search-backend-module-pg       0.5.0
  @backstage/plugin-search-backend-node            1.1.0
  @backstage/plugin-search-backend                 1.2.0
  @backstage/plugin-search-common                  1.2.0
  @backstage/plugin-search-react                   1.3.1
  @backstage/plugin-search                         1.0.6
  @backstage/plugin-tech-radar                     0.5.20
  @backstage/plugin-techdocs-backend               1.5.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.8
  @backstage/plugin-techdocs-node                  1.4.3
  @backstage/plugin-techdocs-react                 1.1.1
  @backstage/plugin-techdocs                       1.4.2
  @backstage/plugin-user-settings                  0.6.1
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
✨  Done in 0.90s.

```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by marcus-crane** [comment]
I haven't looked too deep into this but I have the same issue with the plain HTTP event router connecting to the Github catalog module where the connection isn't created, despite everything appearing to be correct.

**Comment by marcus-crane** [comment]
Ah, it seems that I was missing part of the setup required. To be clear, there are a couple of steps that are entirely missing from the current event module setup documentation so I'll probably aim to do a PR for that shortly.

In particular, you'll want to check that `packages/backend/src/index.ts` looks like this:

```typescript
import events from './plugins/events';
import catalogEventBasedProviders from './plugins/catalogEventBasedProviders'

[...]

const eventsEnv = useHotMemoize(module, () => createEnv('events'));

[...]

const eventBasedEntityProviders = await catalogEventBasedProviders(
  catalogEnv,
);

[...]

apiRouter.use(
  '/catalog',
  await catalog(catalogEnv, eventBasedEntityProviders)
);
apiRouter.use('/events', await events(eventsEnv, eventBasedEntityProviders));
```

Passing `eventBasedEntityProviders` into `catalog()` was the bit that I was missing

**Comment by jrummler** [comment]
Hey @marcus-crane! Thanks for the input. I now add the entity providers to the catalog route, but still having the same problem. Maybe I somehow setup the event provider in a wrong way?

My code looks like this:
```
export default async function createCatalogEventBasedProviders(
    env: PluginEnvironment,
): Promise<Array<EntityProvider & EventSubscriber>> {
  const providers: Array<(EntityProvider & EventSubscriber) | Array<EntityProvider & EventSubscriber>> = [];
  providers.push(GithubEntityProvider.fromConfig(env.config, {
    logger: env.logger,
    scheduler: env.scheduler
  }));
  return providers.flat();
}
```

And in `index.ts`:
```
  const eventsEnv = useHotMemoize(module, () => createEnv('events'));
[...]
  const eventBasedEntityProviders = await catalogEventBasedProviders(
      catalogEnv,
  );
[...]
  apiRouter.use('/catalog', await catalog(catalogEnv, eventBasedEntityProviders));
  apiRouter.use('/events', await events(eventsEnv, eventBasedEntityProviders));
```

**Comment by marcus-crane** [comment]
@jrummler I'll see about submitting a PR for the documentation tomorrow

Have you also wired up the providers to the Catalog as well? Doing so look like this:

```diff
// existing imports
+ import { EntityProvider } from '@backstage/plugin-catalog-node';
+ import { GithubEntityProvider, GithubLocationAnalyzer } from '@backstage/plugin-catalog-backend-module-github';

export default async function createPlugin(
  env: PluginEnvironment,
+  providers?: Array<EntityProvider>,
): Promise<Router> {
  const builder = CatalogBuilder.create(env);
  const { config, logger, discovery } = env;
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  builder.addLocationAnalyzers(
    new GithubLocationAnalyzer({
      discovery: env.discovery,
      config: env.config,
      tokenManager: env.tokenManager
    }),
  );
  builder.addProcessor(new EntityLinkProcessor());
+  builder.addEntityProvider(providers ?? []);
```

It probably makes sense that you still get the error if not as the catalog is what creates the connection when registering the entity provider

---

For reference, here are all the various changes to the files that I set up in our working version:

`packages/backend/src/index.ts`

```ts
import events from './plugins/events';
import catalogEventBasedProviders from './plugins/catalogEventBasedProviders'

const eventsEnv = useHotMemoize(module, () => createEnv('events'));

const eventBasedEntityProviders = await catalogEventBasedProviders(
  catalogEnv,
);

apiRouter.use(
  '/catalog',
  await catalog(catalogEnv, eventBasedEntityProviders)
);
apiRouter.use('/events', await events(eventsEnv, eventBasedEntityProviders));
```

`packages/backend/src/plugins/catalog.ts`

```ts
import { EntityProvider } from '@backstage/plugin-catalog-node';
import { GithubEntityProvider, GithubLocationAnalyzer } from '@backstage/plugin-catalog-backend-module-github';

export default async function createPlugin(
  env: PluginEnvironment,
  providers?: Array<EntityProvider>,
): Promise<Router> {
[...]

builder.addEntityProvider(providers ?? []);
```

`packages/backend/src/plugins/catalogEventBasedProviders.ts`

```ts
import { GithubEntityProvider } from '@backstage/plugin-catalog-backend-module-github';
import { EntityProvider } from '@backstage/plugin-catalog-node';
import { EventSubscriber } from '@backstage/plugin-events-node';
import { PluginEnvironment } from '../types';

export default async function createCatalogEventBasedProviders(
  env: PluginEnvironment,
): Promise<Array<EntityProvider & EventSubscriber>> {
  const providers: Array<
    (EntityProvider & EventSubscriber) | Array<EntityProvider & EventSubscriber>
  > = [];
  // add your event-based entity providers here
  providers.push(
    GithubEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 90 },
        timeout: { minutes: 30 },
      }),
      scheduler: env.scheduler,
    }),
  );
  return providers.flat();
}
```

`packages/backend/src/plugins/events.ts`

```ts
import {
    EventsBackend,
    HttpPostIngressEventPublisher,
  } from '@backstage/plugin-events-backend';
  import { EventSubscriber } from '@backstage/plugin-events-node';
  import { Router } from 'express';
  import { PluginEnvironment } from '../types';

  export default async function createPlugin(
    env: PluginEnvironment,
    subscribers: EventSubscriber[],
  ): Promise<Router> {
    const eventsRouter = Router();

    const http = HttpPostIngressEventPublisher.fromConfig({
      config: env.config,
      logger: env.logger,
    });
    http.bind(eventsRouter);

    await new EventsBackend(env.logger)
      .addPublishers(http)
      .addSubscribers(subscribers)
      .start();

    return eventsRouter;
  }
```

**Comment by GuptaNavdeep1983** [comment]
@jrummler, @Rugvip Is there any change in this feature after migrating to new backend. I am assuming that we are sharing the same instance of entity provider with events and catalog plugin to ensure that the catalog is connected by the time events starts pouring in!
