### ISSUE TITLE
🐛 Bug Report: Ident authentication failed for user "postgres"

### ISSUE THREAD

**Issue by vincent-pli** [backstage/backstage#15425]
### 📜 Description

Follow the https://backstage.io/docs/getting-started/configuration to config the DB with Postgrsql.

After Postgrsql installed then update the `password`

then hit the issue:
```
[1] Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, error: Ident authentication failed for user "postgres"
[1]     at /root/workspace/idp/my-backstage-app/node_modules/@backstage/backend-common/dist/index.cjs.js:1024:17
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async CatalogBuilder.build (/root/workspace/idp/my-backstage-app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:4344:22)
[1]     at async createPlugin (webpack-internal:///./src/plugins/catalog.ts:14:44)
[1]     at async main (webpack-internal:///./src/index.ts:96:31)
```

I'm sure the `password` of `postgres` is correct, I can login db with:
`psql -U postgres -W`

### 👍 Expected behavior

DB configuration could works

### 👎 Actual Behavior with Screenshots

Hit the issue and backend of `backstage` cannot startup

### 👟 Reproduction steps

Follow the guide to:
- Install the Postgresql
- Update `password` of user: `postgres`
-  run `yarn add --cwd packages/backend pg`
-  Add entities to `app-config.yaml`:
    ```
    database:
    # config options: https://node-postgres.com/apis/client
    client: pg
    connection:
      host: 127.0.0.1
      port: 5432
      user: postgres
      password: letmein
    ```
- Restart backstage with `yarn dev`

### 📃 Provide the context for the Bug.

N/A

my os is centos 8

### 🖥️ Your Environment

```
[root@experimental my-backstage-app]# yarn backstage-cli info
yarn run v1.22.19
$ /root/workspace/idp/my-backstage-app/node_modules/.bin/backstage-cli info
OS:   Linux 4.18.0-408.el8.x86_64 - linux/x64
node: v18.12.1
yarn: 1.22.19
cli:  0.22.0 (installed)
backstage:  1.9.0

Dependencies:
  @backstage/app-defaults                          1.0.10
  @backstage/backend-common                        0.17.0
  @backstage/backend-plugin-api                    0.2.0
  @backstage/backend-tasks                         0.4.0
  @backstage/catalog-client                        1.2.0
  @backstage/catalog-model                         1.1.4
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.0
  @backstage/config-loader                         1.1.7
  @backstage/config                                1.0.5
  @backstage/core-app-api                          1.3.0
  @backstage/core-components                       0.12.2
  @backstage/core-plugin-api                       1.2.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.0
  @backstage/integration-react                     1.1.8
  @backstage/integration                           1.4.1
  @backstage/plugin-api-docs                       0.8.13
  @backstage/plugin-app-backend                    0.3.39
  @backstage/plugin-auth-backend                   0.17.2
  @backstage/plugin-auth-node                      0.2.8
  @backstage/plugin-catalog-backend                1.6.0
  @backstage/plugin-catalog-common                 1.0.9
  @backstage/plugin-catalog-graph                  0.2.25
  @backstage/plugin-catalog-import                 0.9.3
  @backstage/plugin-catalog-node                   1.3.0
  @backstage/plugin-catalog-react                  1.2.3
  @backstage/plugin-catalog                        1.7.1
  @backstage/plugin-github-actions                 0.5.13
  @backstage/plugin-org                            0.6.3
  @backstage/plugin-permission-common              0.7.2
  @backstage/plugin-permission-node                0.7.2
  @backstage/plugin-permission-react               0.4.8
  @backstage/plugin-proxy-backend                  0.2.33
  @backstage/plugin-scaffolder-backend             1.9.0
  @backstage/plugin-scaffolder-common              1.2.3
  @backstage/plugin-scaffolder                     1.9.1
  @backstage/plugin-search-backend-module-pg       0.5.0
  @backstage/plugin-search-backend-node            1.1.0
  @backstage/plugin-search-backend                 1.2.0
  @backstage/plugin-search-common                  1.2.0
  @backstage/plugin-search-react                   1.3.1
  @backstage/plugin-search                         1.0.6
  @backstage/plugin-tech-radar                     0.5.20
  @backstage/plugin-techdocs-backend               1.5.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.8
  @backstage/plugin-techdocs-node                  1.4.3
  @backstage/plugin-techdocs-react                 1.1.1
  @backstage/plugin-techdocs                       1.4.2
  @backstage/plugin-user-settings                  0.6.1
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vincent-pli** [comment]
Change setting in `pg_hba.conf`:
```
host    all             all             127.0.0.1/32            ident
```

to 
```
host    all             all             127.0.0.1/32            md5
```
fixed the issue...

**Comment by Rugvip** [comment]
Alright, gonna close since it's fixed.

Side note, the indentation in the config example is off, it should be

```yaml
database:
  client: pg
  connection:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: letmein
```
