### ISSUE TITLE
🐛 Bug Report: TypeError: coreTracing.createTracingClient is not a function due to "@azure/identity" update

### ISSUE THREAD

**Issue by cchawn** [backstage/backstage#15601]
### 📜 Description

When upgrading Backstage to `1.9.1`, I began getting the following error when trying to run `yarn dev` locally:

```
TypeError: coreTracing.createTracingClient is not a function
```

I believe this is due to [Azure/azure-sdk-for-js@main/sdk/identity/identity/CHANGELOG.md](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/CHANGELOG.md#210-2022-07-08) moving from `2.0.5 ` to `2.1.0`. The Backstage [kubernetes-backend plugin still depends on `2.0.4`](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/package.json?rgh-link-date=2022-12-21T02%3A51%3A10Z#L37) – which means something might still be resolving to a pre-`2.1.0` version (that depends on this now, non-existent `coreTracing.createTracingClient` function?

### 👍 Expected behavior

After running `yarn dev`, Backstage starts up correctly.

### 👎 Actual Behavior with Screenshots

After running `yarn dev`, I get a `TypeError: coreTracing.createTracingClient is not a function` error, and the backend fails to start up.

Full stack trace:

```sh
$ export NODE_ENV=${NODE_ENV:-development} && concurrently "yarn start" "yarn start-backend"
$ yarn workspace @wealthsimple/backstage-backend start
$ yarn workspace @wealthsimple/backstage-app start
$ backstage-cli package start
$ backstage-cli package start
[1] Build succeeded
[0] Loaded config from app-config.yaml, app-config.local.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/cchan/Workspace/backstage-app/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] /Users/cchan/Workspace/backstage-app/packages/backend/dist/main.js:2655
[1] /******/ 			throw e;
[1]          			^
[1]
[1] TypeError: coreTracing.createTracingClient is not a function
[1]     at Object.<anonymous> (/Users/cchan/Workspace/backstage-app/node_modules/@azure/identity/dist/index.js:238:35)
[1]     at Module._compile (node:internal/modules/cjs/loader:1155:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[1]     at Module.load (node:internal/modules/cjs/loader:1033:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1057:19)
[1]     at require (node:internal/modules/cjs/helpers:103:18)
[1]     at Object.<anonymous> (/Users/cchan/Workspace/backstage-app/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:23:16)
[1]     at Module._compile (node:internal/modules/cjs/loader:1155:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[1]     at Module.load (node:internal/modules/cjs/loader:1033:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1057:19)
[1]     at require (node:internal/modules/cjs/helpers:103:18)
[1]     at Object.<anonymous> (/Users/cchan/Workspace/backstage-app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:8:26)
[1]     at Module._compile (node:internal/modules/cjs/loader:1155:14)
```

### 👟 Reproduction steps

1. have a local instance of Backstage that uses `@backstage/plugin-techdocs-node` (since this is where we're pulling in the `@azure/identity` dependency)
2. upgrade Backstage from v 1.8.3 to v 1.9.1
3. run `yarn dev`
4. get `TypeError: coreTracing.createTracingClient is not a function`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
Hi @cchawn, I'm not able to reproduce this when creating a new installation. `@backstage/plugin-techdocs-node` is used by the techdocs-backend. Could this have been something temporary?

**Comment by cal5barton** [comment]
I'm getting the same behavior. @cchawn what did you do to get past this?

**Comment by mptasinski** [comment]
iv'e got the same error after yarn.lock regenerate

im my case setting resolutions in maim package.json fix the issue

```
  "resolutions": {
    "@azure/storage-blob": "12.17.0"
  },
```

**Comment by michaelgrewal** [comment]
I have been facing this same issue for the past 2 weeks.
I found for me I lock version `"@azure/storage-blob": "12.18.0"` fixes it.
Does anyone know if this was fixed with newer azure sdk versions?

```
"dependencies": {
    "@azure/ai-form-recognizer": "^5.0.0",
    "@azure/cosmos": "^4.0.0",
    "@azure/identity": "^4.0.0",
    "@azure/keyvault-secrets": "^4.7.0",
    "@azure/search-documents": "^12.0.0",
    "@azure/storage-blob": "12.18.0",
    ...
  },
```

**Comment by chrisa-nable** [comment]
Is anybody still having this issue? I've tried the solutions listed in the two comments above but still getting the same error. This is in the process of upgrading to Backstage 1.30.4 from 1.27.5

**Comment by dhowell2000** [comment]
It works fine on my development box (vscode on a mac)

When i push to my Azure Web App it breaks. I opened a Kudo console to the Web App and ran your requested command. This is what i got:
                                          
DEBUG CONSOLE | AZURE APP SERVICE ON LINUX

Documentation: http://aka.ms/webapp-linux
Kudu Version : 20240822.2
Commit       : a86ad9d31002b0e2111a20f21ebaeae4be986b94

kudu_ssh_user@a84d3d69020e:/$ npm ls @azure/core-tracing
/
└── (empty)

kudu_ssh_user@a84d3d69020e:/$ 


Here is the dependency part of my package.json
  "dependencies": {
    "@azure/communication-email": "^1.0.0",
    "@azure/communication-sms": "^1.1.0",
    "@azure/core-tracing": "^1.1.2",
    "@azure/identity": "^4.4.1",
    "@azure/keyvault-keys": "^4.8.0",
    "@azure/keyvault-secrets": "^4.8.0",
    "@azure/monitor-opentelemetry": "^1.7.1",
    "@azure/storage-blob": "^12.25.0",
    "@ffmpeg-installer/ffmpeg": "^1.1.0",
    "apn": "^2.2.0",
    "applicationinsights": "^3.3.0",
    "chalk": "^4.1.2",
    "dayjs": "^1.11.11",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "ffmpeg-static": "^5.2.0",
    "fluent-ffmpeg": "^2.1.3",
    "json5": "^2.2.3",
    "jsonwebtoken": "^9.0.2",
    "mongodb": "^6.8.0",
    "mongoose": "^8.0.3",
    "ms": "^2.1.3",
    "multer": "^1.4.5-lts.1",
    "sharp": "^0.33.4",
    "swagger-jsdoc": "^6.2.8",
    "swagger-ui-express": "^5.0.1",
    "uuid": "^10.0.0",
    "ws": "^8.18.0"
  },
  "devDependencies": {
    "chai": "^5.1.1",
    "jest": "^29.7.0",
    "mocha": "^10.7.3",
    "supertest": "^7.0.0",
    "swagger-autogen": "^2.23.7"
  },
  "pkg": {
    "scripts": [
      "bin/www",
      "api/v1/v1ApiDiscoveryRouter.js"
    ],
    "assets": [
      "public/**/*",
      "views/**/*",
      "config/**/*",
      "bin/**/*",
      "node_modules/sharp/**/*",
      "node_modules/open/xdg-open"
    ],
    "targets": [
      "node16-macos-x64"
    ]
  }
}

**Comment by dhowell2000** [comment]
it works in Azure if i go back to this: 

  "@azure/storage-blob": "12.18.0",
