### ISSUE TITLE
🐛 Bug Report: plugin-azure-devops-backend encoded host breaks readme

### ISSUE THREAD

**Issue by matt-200** [backstage/backstage#15874]
### 📜 Description

When using a port in the host for azure devops, it works fine with pull requests and pipelines. But, the readme card breaks because of a malformed url.

Example host: tfs.myorg.com:8443
Gets encoded to: tfs.myorg.com%3A8443

I'm able to fix it temporarily by changing this block in index.cjs.js:
```
function buildEncodedUrl(host, org, project, repo, path) {
  const encodedHost = encodeURIComponent(host);
  const encodedOrg = encodeURIComponent(org);
  const encodedProject = encodeURIComponent(project);
  const encodedRepo = encodeURIComponent(repo);
  const encodedPath = encodeURIComponent(path);
  return `https://${encodedHost}/${encodedOrg}/${encodedProject}/_git/${encodedRepo}?path=${encodedPath}`;
}
```

to this:
```
function buildEncodedUrl(host, org, project, repo, path) {
  const encodedOrg = encodeURIComponent(org);
  const encodedProject = encodeURIComponent(project);
  const encodedRepo = encodeURIComponent(repo);
  const encodedPath = encodeURIComponent(path);
  return `https://${host}/${encodedOrg}/${encodedProject}/_git/${encodedRepo}?path=${encodedPath}`;
}
```

Error output:
```
{
	"error": {
		"name": "TypeError",
		"message": "Invalid URL",
		"input": "https://tfs.myorg.com%3A8443/tfs%2Fmyorg/myorg/_git/my-app?path=README.md",
		"code": "ERR_INVALID_URL",
		"stack": "TypeError [ERR_INVALID_URL]: Invalid URL
                  at new NodeError (node:internal/errors:387:5)
                  at URL.onParseError (node:internal/url:565:9)
                  at parse (<anonymous>)
                  at new URL (node:internal/url:641:5)
                  at UrlReaderPredicateMux.readUrl ({{backstage_root}}\node_modules\@backstage\backend-common\dist\index.cjs.js:3115:20)
                  at AzureDevOpsApi.getReadme ({{backstage_root}}\node_modules\@backstage\plugin-azure-devops-backend\dist\index.cjs.js:488:43)
                  at {{backstage_root}}\node_modules\@backstage\plugin-azure-devops-backend\dist\index.cjs.js:771:41
                  at handleReturn ({{backstage_root}}\node_modules\express-promise-router\lib\express-promise-router.js:24:23)
                  at {{backstage_root}}\node_modules\express-promise-router\lib\express-promise-router.js:64:7
                  at handleReturn ({{backstage_root}}\node_modules\express-promise-router\lib\express-promise-router.js:24:23)"
	},
	"request": {
		"method": "GET",
		"url": "/readme/myorg/my-app"
	},
	"response": {
		"statusCode": 500
	}
}
```

### 👍 Expected behavior

The readme card should not break when the host has a port in it and should display the readme.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/123186429/213744192-a83d9256-3be7-4620-b967-8a610287efcf.png)

### 👟 Reproduction steps

In app-config.yaml, setup azureDevops similar to this, important part being the port in the host:

```
azureDevOps:
  host: tfs.myorg.com:8443
  token: ${AZURE_TOKEN}
  organization: tfs/myorg
```

### 🖥️ Your Environment

```
OS:   Windows_NT 10.0.19042 - win32/x64
node: v16.19.0
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.1

Dependencies:
  @backstage/app-defaults                          1.1.0
  @backstage/backend-app-api                       0.3.1
  @backstage/backend-common                        0.17.0, 0.18.1
  @backstage/backend-plugin-api                    0.3.1
  @backstage/backend-tasks                         0.4.2
  @backstage/backend-test-utils                    0.1.33
  @backstage/catalog-client                        1.3.0
  @backstage/catalog-model                         1.1.5
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.1
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.4.0
  @backstage/core-components                       0.12.3
  @backstage/core-plugin-api                       1.3.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.9
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.41
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.10
  @backstage/plugin-azure-devops-backend           0.3.20
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.5
  @backstage/plugin-catalog-backend-module-azure   0.1.12
  @backstage/plugin-catalog-backend                1.7.1
  @backstage/plugin-catalog-common                 1.0.10
  @backstage/plugin-catalog-graph                  0.2.26
  @backstage/plugin-catalog-import                 0.9.4
  @backstage/plugin-catalog-node                   1.3.2
  @backstage/plugin-catalog-react                  1.2.4
  @backstage/plugin-catalog                        1.7.2
  @backstage/plugin-github-actions                 0.5.14
  @backstage/plugin-jenkins-backend                0.1.31
  @backstage/plugin-jenkins-common                 0.1.12
  @backstage/plugin-jenkins                        0.7.13
  @backstage/plugin-kubernetes-backend             0.9.2
  @backstage/plugin-kubernetes-common              0.5.1
  @backstage/plugin-kubernetes                     0.7.7
  @backstage/plugin-org                            0.6.4
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.4
  @backstage/plugin-permission-react               0.4.9
  @backstage/plugin-proxy-backend                  0.2.35
  @backstage/plugin-scaffolder-backend             1.10.1
  @backstage/plugin-scaffolder-common              1.2.4
  @backstage/plugin-scaffolder-react               1.0.1
  @backstage/plugin-scaffolder                     1.10.1
  @backstage/plugin-search-backend-module-pg       0.5.2
  @backstage/plugin-search-backend-node            1.1.2
  @backstage/plugin-search-backend                 1.2.2
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-sonarqube-backend              0.1.6
  @backstage/plugin-sonarqube-react                0.1.1
  @backstage/plugin-sonarqube                      0.6.2
  @backstage/plugin-tech-radar                     0.6.0
  @backstage/plugin-techdocs-backend               1.5.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.9
  @backstage/plugin-techdocs-node                  1.4.5
  @backstage/plugin-techdocs-react                 1.1.2
  @backstage/plugin-techdocs                       1.4.3
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.4
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Yep your suggested fix looks good! 👍

**Comment by matt-200** [comment]
@Rugvip I opened PR: #15980
