### ISSUE TITLE
🐛 Bug Report: Backend communication fails in Helm deployment

### ISSUE THREAD

**Issue by emichaf** [backstage/backstage#15894]
### 📜 Description

Trying the Backstage Helm charts with ingress and postgresql.enabled: true!

Getting "Failed to load entity kinds".

Access to fetch at 'http://localhost:7007/api/catalog/entity-facets?facet=kind' from origin 'https://backstage.mydomain.com/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

It's working of I do port forwarding directly to K8S SVC. (http://localhost:7007/)

### 👍 Expected behavior

No error msg, possible to configure CORS

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/2071801/214000033-d5b408cc-3a65-441d-9e1f-b3d8b6d47720.png)

### 👟 Reproduction steps

Deploy Backstage with latest Helm charts and activate ingress!

### 📃 Provide the context for the Bug.

Tried adding CORS config in value file-> appConfig, but then POD is not starting.. error: Backend failed to start up Error: Missing required config value at 'backend.database'

image

POD log:
Loaded config from app-config-from-configmap.yaml, env
{"level":"info","message":"Found 1 new secrets in config that will be redacted","service":"backstage"}
{"level":"info","message":"Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{}","service":"backstage"}
Backend failed to start up Error: Missing required config value at 'backend.database'
at ConfigReader.getConfig (/app/node_modules/@backstage/config/dist/index.cjs.js:130:13)
at ObservableConfigProxy.select (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:105:41)
at ObservableConfigProxy.getString (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:158:17)
at DatabaseManager.getClientType (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:971:36)
at DatabaseManager.getConfigForPlugin (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:1043:29)
at /app/node_modules/@backstage/backend-common/dist/index.cjs.js:1083:14

### 🖥️ Your Environment

Regular K8S instance

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Could you attach the complete app-config.yaml? The error message indicates you are missing the database config for backend so for example:

```yaml
backend:
    database:
      client: pg
      connection:
        host: localhost
        port: 5432
        user: postgresql
        password: postgresql
```

**Comment by benjdlambert** [comment]
I don't think that this is a postgres issue, I think that the `backend.baseUrl` config option is set incorrectly. You will need to provide the public facing URL for this - looks like it's defaulting to localhost?

**Comment by benjdlambert** [comment]
@emichaf actually ignore what I said, yeah it looks like @drodil has the right idea. I wonder if you're using env variables that aren't present or if the config is not in the deployed container or something? Might be worth running the container locally to inspect what config is present and see if it lines up with the error message that `backend.database` is not present.

**Comment by lsoica** [comment]
I have the same problem. My backend database config looks right to me:
```
      database:
        client: pg
        connection:
          host: backstage-postgresql
          port: 5432
          user: backstage
          password: <redacted>
```

**Comment by benjdlambert** [comment]
@lsoica do you also get this error message:

```sh
Backend failed to start up Error: Missing required config value at 'backend.database'
at ConfigReader.getConfig (/app/node_modules/@backstage/config/dist/index.cjs.js:130:13)
at ObservableConfigProxy.select (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:105:41)
at ObservableConfigProxy.getString (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:158:17)
at DatabaseManager.getClientType (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:971:36)
at DatabaseManager.getConfigForPlugin (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:1043:29)
at /app/node_modules/@backstage/backend-common/dist/index.cjs.js:1083:14
```

**Comment by lsoica** [comment]
Nope, backend log is clean. Just info logs there.

**Comment by lsoica** [comment]
Although I configured appConfig.backend.baseUrl, I can't find it in the /static/module-backstage.<redacted>.js

**Comment by JBrejnholt** [comment]
It might be related - I follow the tutorial to set up postgres cluster as the backend db. If I run 'yarn dev' to spin up both frontend and backend, backstage loads properly. When I run 'yarn start' and 'yarn start-backend' separately, I have following error for the backend:

```

 yarn start-backend
yarn run v1.22.19
$ yarn workspace backend start
$ backstage-cli package start
Build succeeded
Loaded config from app-config.yaml, app-config.local.yaml
2023-03-20T11:54:02.579Z backstage info Found 1 new secrets in config that will be redacted
2023-03-20T11:54:02.583Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{}
Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, error: password authentication failed for user "postgres"
    at /Users/jinhong_brejnholt/Git/GitHub/backstage-playground/demo/node_modules/@backstage/backend-common/dist/index.cjs.js:985:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CatalogBuilder.build (/Users/jinhong_brejnholt/Git/GitHub/backstage-playground/demo/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:4952:22)
    at async createPlugin (webpack-internal:///./src/plugins/catalog.ts:14:44)
    at async main (webpack-internal:///./src/index.ts:96:31)
```
