### ISSUE TITLE
🚀 Feature: Make page size for getOrganizationRepositories configurable

### ISSUE THREAD

**Issue by roelywoely** [backstage/backstage#15982]
### 🔖 Feature description

Make the page size in the repository queries configurable. It's currently hardcoded to be 100: https://github.com/backstage/backstage/blob/7c0a33390a818af213ec8ea694a4fcbe118d9d6c/plugins/catalog-backend-module-github/src/lib/github.ts#L426

### 🎤 Context

This query randomly fails:
```json
{"class":"GithubEntityProvider","level":"error","message":"Unknown error: {\"data\":null,\"errors\":[{\"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `XXXXXXXXXXXXXXXX` when reporting this issue.\"}]}","name":"HttpError","plugin":"catalog","request":{"body":"{\"query\":\"\\n    query repositories($org: String!, $catalogPathRef: String!, $cursor: String) {\\n      repositoryOwner(login: $org) {\\n        login\\n        repositories(first: 100, after: $cursor) {\\n          nodes {\\n            name\\n            catalogInfoFile: object(expression: $catalogPathRef) {\\n              __typename\\n              ... on Blob {\\n                id\\n                text\\n              }\\n            }\\n            url\\n            isArchived\\n            repositoryTopics(first: 100) {\\n              nodes {\\n                ... on RepositoryTopic {\\n                  topic {\\n                    name\\n                  }\\n                }\\n              }\\n            }\\n            defaultBranchRef {\\n              name\\n            }\\n          }\\n          pageInfo {\\n            hasNextPage\\n            endCursor\\n          }\\n        }\\n      }\\n    }\",\"variables\":{\"org\":\"myorg\",\"catalogPathRef\":\"HEAD:.backstage/**/*.yaml\",\"cursor\":\"Y3Vyc29yOnYyOpHOElzwKQ==\"}}","headers":{"accept":"application/vnd.github.v3+json","authorization":"Bearer [REDACTED]","content-type":"application/json; charset=utf-8","user-agent":"octokit-graphql.js/5.0.1 Node.js/16.19.0 (linux; x64)"},"method":"POST","url":"https://api.github.com/graphql"},"response":{"data":{"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `XXXXXXXXXXXXXXXX` when reporting this issue."}]},"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset","connection":"close","content-type":"application/json","date":"Sun, 22 Jan 2023 11:47:25 GMT","server":"GitHub.com","transfer-encoding":"chunked","vary":"Accept-Encoding, Accept, X-Requested-With","x-github-request-id":"XXXXXXXXXXXXXXXX"},"status":502,"url":"https://api.github.com/graphql"},"service":"backstage","stack":"HttpError: Unknown error: {\"data\":null,\"errors\":[{\"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `XXXXXXXXXXXXXXXX` when reporting this issue.\"}]}\n    at /app/node_modules/@octokit/request/dist-node/index.js:88:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async queryWithPaging (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:346:22)\n    at async getOrganizationRepositories (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:304:24)\n    at async GithubEntityProvider.findCatalogFiles (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:907:54)\n    at async GithubEntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:879:21)\n    at async TaskWorker.fn (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:867:13)\n    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:349:7)\n    at async /app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:302:31","status":502,"target":"github-provider:myorg_services","taskId":"github-provider:myorg_services:refresh","taskInstanceId":"fa122bd6-5c1e-4b43-a560-ceb9de5356a7","type":"plugin"}
```
It's timing out on Github side, probably because too much data is requested.
I reached out to Github support and the only solution they provided was to decrease the items per page.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Can you make this change in `node_modules` and see if it fixes it? And then if it doesn't I would suggest doing as the error message says and contacting GitHub. Not seen this before. Would be good to get some more information before we start creating features that might not help this ticket :pray:

It could be potentially something to do with the 100 repos and then fetching 100 repo topics which could be too much for the request.

**Comment by JedGilbert** [comment]
Hello, we are experiencing the same issue as described above in our organization. We also reached out to Github support and provided the request id output in the debug logs, the support team suggested that the result was due to a timeout due to processing too much data.

As suggested in the comments I updated GithubEntityProvider in the node modules folder and changed the query to use `repositories(first: 50, after: $cursor)` after this we do not see the same problem and catalog entities are being populated.

Is there any advice on what might be causing the issue and any options to provide a fix/workaround please?

**Comment by gstamp** [comment]
We're also getting hit by this one. After reducing the page size directly in node_modules it also fixed the issue.
