### ISSUE TITLE
🐛 Bug Report: <title>

### ISSUE THREAD

**Issue by kamenskiyyyy** [backstage/backstage#16049]
### 📜 Description

Hello! 

I'm try to connect sync with LDAP. 

My config:
```
ldap:
  providers:
    - target: ldap://${LDAP_SERVER}
      bind:
        dn: sonar-tools-r00
        secret: 123456
      users:
        dn: ou=FGUP,dc=main,dc=russianpost,dc=ru
        map:
          rdn: distinguishedName
          name: sAMAccountName
          displayName: displayName
          email: mail
          memberOf: memberOf
      groups:
        dn: OU=PT-TOOLZ,OU=Почтовые технологии,OU=Groups,OU=R00,OU=FGUP,DC=main,DC=russianpost,DC=ru
```

### 👍 Expected behavior

Sync LDAP without errors.
[The documentation states that](https://backstage.io/docs/integrations/ldap/org#usersset) the `set` parameter is optional. But in our case, an error appears.

### 👎 Actual Behavior with Screenshots

<img width="1755" alt="image" src="https://user-images.githubusercontent.com/72261703/215507212-80f1bfe6-5cb3-4582-afbc-4ab808654b95.png">

```
[1] 2023-01-30T14:51:44.611Z catalog error LdapOrgEntityProvider:our-ldap-master refresh failed Malformed entity envelope, TypeError: /metadata/name must NOT have fewer than 1 characters - limit: 1 type=plugin target=ldap://(hide-ldap-server) class=LdapOrgEntityProvider taskId=LdapOrgEntityProvider:our-ldap-master:refresh taskInstanceId=8f5d6f35-b4f1-40a9-b3c5-42b60cf7df6d stack=TypeError: Malformed entity envelope, TypeError: /metadata/name must NOT have fewer than 1 characters - limit: 1
[1]     at Connection.check (/Users/mac/WebstormProjects/pochtatech/backstage/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3850:15)
[1]     at Connection.applyMutation (/Users/mac/WebstormProjects/pochtatech/backstage/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3809:12)
[1]     at LdapOrgEntityProvider.read (/Users/mac/WebstormProjects/pochtatech/backstage/node_modules/@backstage/plugin-catalog-backend-module-ldap/dist/index.cjs.js:833:27)
[1]     at runMicrotasks (<anonymous>)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]     at async TaskWorker.fn (/Users/mac/WebstormProjects/pochtatech/backstage/node_modules/@backstage/plugin-catalog-backend-module-ldap/dist/index.cjs.js:857:13)
[1]     at async TaskWorker.runOnce (/Users/mac/WebstormProjects/pochtatech/backstage/node_modules/@backstage/backend-tasks/dist/index.cjs.js:360:7)
[1]     at async /Users/mac/WebstormProjects/pochtatech/backstage/node_modules/@backstage/backend-tasks/dist/index.cjs.js:308:31
^C[0] <i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...

```

### 👟 Reproduction steps

Everything was done according to the instructions https://backstage.io/docs/integrations/ldap/org#using-a-processor-instead-of-a-provider

### 🖥️ Your Environment

OS:   Darwin 22.3.0 - darwin/arm64
node: v16.15.0
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.9.0

Dependencies:
  @backstage/app-defaults                          1.1.0
  @backstage/backend-app-api                       0.3.1
  @backstage/backend-common                        0.17.0, 0.18.1
  @backstage/backend-plugin-api                    0.3.1
  @backstage/backend-tasks                         0.4.2
  @backstage/catalog-client                        1.3.0
  @backstage/catalog-model                         1.1.5
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.1
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.4.0
  @backstage/core-components                       0.12.3
  @backstage/core-plugin-api                       1.3.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.9
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.41
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.10
  @backstage/plugin-catalog-backend-module-ldap    0.5.8
  @backstage/plugin-catalog-backend                1.7.1
  @backstage/plugin-catalog-common                 1.0.10
  @backstage/plugin-catalog-graph                  0.2.26
  @backstage/plugin-catalog-import                 0.9.4
  @backstage/plugin-catalog-node                   1.3.2
  @backstage/plugin-catalog-react                  1.2.4
  @backstage/plugin-catalog                        1.7.2
  @backstage/plugin-github-actions                 0.5.14
  @backstage/plugin-org                            0.6.4
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.4
  @backstage/plugin-permission-react               0.4.9
  @backstage/plugin-proxy-backend                  0.2.35
  @backstage/plugin-scaffolder-backend             1.10.1
  @backstage/plugin-scaffolder-common              1.2.4
  @backstage/plugin-scaffolder-react               1.0.1
  @backstage/plugin-scaffolder                     1.10.1
  @backstage/plugin-search-backend-module-pg       0.5.2
  @backstage/plugin-search-backend-node            1.1.2
  @backstage/plugin-search-backend                 1.2.2
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-tech-radar                     0.5.20
  @backstage/plugin-techdocs-backend               1.5.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.9
  @backstage/plugin-techdocs-node                  1.4.5
  @backstage/plugin-techdocs-react                 1.1.2
  @backstage/plugin-techdocs                       1.4.3
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.4
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by sennyeya** [comment]
This is due to the default RegEx to validate names, related to Kubernetes' name format which is used in URLs as DNS names. Unfortunately, URLs only support ASCII characters so the [A-Za-z0-9] regex makes sense in those cases.

You can update these validation rules on your end though. Take a look at https://backstage.io/docs/features/software-catalog/extending-the-model. Your implementation would be similar to https://github.com/backstage/backstage/blob/44aa394c354a9166c90e53b9de7cf739a23739f8/packages/catalog-model/src/validation/KubernetesValidatorFunctions.ts#L53, using https://github.com/backstage/backstage/blob/44aa394c354a9166c90e53b9de7cf739a23739f8/plugins/catalog-backend/src/service/CatalogBuilder.ts#L269.

**Comment by sennyeya** [comment]
@kamenskiyyyy In `packages/backend/plugins/catalog.ts`, you'd add something like
```
builder.setFieldFormatValidators({
    isValidEntityName: (value: unknown) => {
      // Pulled from https://github.com/sennyeya/backstage/blob/master/packages/catalog-model/src/validation/KubernetesValidatorFunctions.ts#L48.
      return (
        typeof value === 'string' &&
        value.length >= 1 &&
        value.length <= 64 &&
        // From https://stackoverflow.com/questions/50059755/how-can-i-match-unicode-characters-and-non-digits-using-regex.
        /^([a-zA-Z\u0080-\uFFFF0-9][-a-zA-Z\u0080-\uFFFF0-9_.]*)?[a-zA-Z\u0080-\uFFFF0-9]$/.test(value)
      );
    },
  });
```

**Comment by kamenskiyyyy** [comment]
thank you very much! it works🤗🤗🤗
