### ISSUE TITLE
🐛 Bug Report: Google based OIDC provider from scratch redirect to login page when I refresh the page after I logged in

### ISSUE THREAD

**Issue by myplaybooks** [backstage/backstage#16043]
### 📜 Description

I am redirecting to the login page on refresh, I am aware that there are several discussions regarding redirecting to the login page in this channel. But I am not sure if it is a new issue or an issue due to configuration. 

I am facing a similar issue for my "OIDC provider from scratch" as others. I have followed the steps mentioned in https://backstage.io/docs/auth/oidc. But instead of azureOIDC, I am using a custom google provider (called "googlecustom") for testing. After the implementation, I can login to the portal, but when I refresh it, it redirects to the login page. 

What I have observed is, I am not getting a refresh token after I logged in (googlecustom-refresh-token). So whenever I refresh the page I get 401 Unauthorized. 
Request URL: http://localhost:7007/api/auth/googlecustom/refresh?optional&env=development

I have followed the following steps as mentioned by @Rugvip in GitHub. 
https://github.com/backstage/backstage/pull/13695?#pullrequestreview-1123807546

### 👍 Expected behavior

Refresh page should not redirect to login page instead it has to stay on that page. 

### 👎 Actual Behavior with Screenshots

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/52525394/215492429-e17139f0-1202-4281-9c56-ea7c4fc7f079.png">

{
  "error": {
    "name": "AuthenticationError",
    "message": "Refresh failed; caused by InputError: Missing session cookie",
    "cause": {
      "name": "InputError",
      "message": "Missing session cookie",
      "stack": "InputError: Missing session cookie
    at OAuthAdapter.refresh (...../backstage-google-auth-latest/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:446:15)
    at OAuthEnvironmentHandler.refresh (...../backstage-google-auth-latest/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:206:58)
    at handleReturn (...../backstage-google-auth-latest/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at bound refresh (...../backstage-google-auth-latest/node_modules/express-promise-router/lib/express-promise-router.js:64:7)
    at handleReturn (...../backstage-google-auth-latest/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at bound refresh (...../backstage-google-auth-latest/node_modules/express-promise-router/lib/express-promise-router.js:64:7)
    at Layer.handle [as handle_request] (...../backstage-google-auth-latest/node_modules/express/lib/router/layer.js:95:5)
    at next (...../backstage-google-auth-latest/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (...../backstage-google-auth-latest/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (...../backstage-google-auth-latest/node_modules/express/lib/router/layer.js:95:5)"
    },
    "stack": "AuthenticationError: Refresh failed; caused by InputError: Missing session cookie
    at OAuthAdapter.refresh (...../backstage-google-auth-latest/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:464:13)
    at OAuthEnvironmentHandler.refresh (...../backstage-google-auth-latest/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:206:58)
    at handleReturn (...../backstage-google-auth-latest/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at bound refresh (...../backstage-google-auth-latest/node_modules/express-promise-router/lib/express-promise-router.js:64:7)
    at handleReturn (...../backstage-google-auth-latest/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at bound refresh (...../backstage-google-auth-latest/node_modules/express-promise-router/lib/express-promise-router.js:64:7)
    at Layer.handle [as handle_request] (...../backstage-google-auth-latest/node_modules/express/lib/router/layer.js:95:5)
    at next (...../backstage-google-auth-latest/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (...../backstage-google-auth-latest/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (...../backstage-google-auth-latest/node_modules/express/lib/router/layer.js:95:5)"
  },
  "request": {
    "method": "GET",
    "url": "/api/auth/googlecustom/refresh?optional&env=development"
  },
  "response": {
    "statusCode": 401
  }
}

### 👟 Reproduction steps

I have followed the section [OIDC provider from scratch](https://backstage.io/docs/auth/oidc) and instead of azureOIDC I have used google.

My implementation is similar to this: 
https://github.com/backstage/backstage/pull/13695?#pullrequestreview-1123807546

### 📃 Provide the context for the Bug.

Page refresh is not working. 

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.22.0 (installed)
backstage:  1.9.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
How come you need to implement a custom google provider, what's wrong with the existing one? 😁 

Regarding the actual issue, verify that you're actually getting a refresh token back in the auth result. You might for example need to request `offline` scope or similar.

**Comment by myplaybooks** [comment]
I am testing how we can use the OIDC provider instead of implementing a new one. So thought of implementing google one as you have shown in the https://github.com/backstage/backstage/pull/13695 to understand what's happening. I agree that issue is due to missing refresh token. Even after put access_type='offline' I am not getting refresh token. Tried via rest client too. I think I need to do bit research on google oauth. 
Anyway thanks for the help ;)

**Comment by LZING** [comment]
May I ask if you have solved this problem, do you have any ideas?

**Comment by markussiebert** [comment]
I have the same problem with cognito. Want to use this provider with Kubernetes Plugin. But on every refresh I have to login again. With local running kubelogin I see cognito providing refresh tokens - but don't know how to make this work in backstage.
