### ISSUE TITLE
Failed to create app! Couldn't find package "@swagger-api/apidom-core@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#16594]
### 📜 Description

error Couldn't find package "@swagger-api/apidom-core@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
Error: Couldn't find package "@swagger-api/apidom-reference@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@swagger-api/apidom-ns-openapi-3-1@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@swagger-api/apidom-json-pointer@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/lalitkumar/.nvm/versions/node/v16.13.1/lib/node_modules/yarn/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  executing     yarn install ✖ 

Error: Could not execute command yarn install

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!

### 👍 Expected behavior

should create app successfully

### 👎 Actual Behavior with Screenshots

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/225961/221219767-a0f69ccc-2723-4b90-a63d-647296d04fae.png">

### 👟 Reproduction steps

Step 1: npx @backstage/create-app

Step 2: : enter app name

Step 3: get error message Couldn't find package "@swagger-api/apidom-core@=0.68.1"

### 🖥️ Your Environment

node v16.13.1
yarn 1.22.17

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by lalit774** [comment]
duplicate
https://github.com/backstage/backstage/issues/16589
