### ISSUE TITLE
🐛 Bug Report: Getting Route error in entity page  #Helpwanted

### ISSUE THREAD

**Issue by aswathysen** [backstage/backstage#16840]
### 📜 Description

_**### `Error: useRoutes() may be used only in the context of a <Router> component.`**_

```    
<EntityLayout.Route
  path="/pull-requests"
  title="Pull Requests"
  if={isGithubPullRequestsAvailable}
>
  <EntityGithubPullRequestsContent />
</EntityLayout.Route>
```

### 👍 Expected behavior

Properly Display the card for pull request.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/81619825/224975742-c06f151c-8689-4552-a9b0-b451341ea0aa.png)
![image](https://user-images.githubusercontent.com/81619825/224975803-f9948461-52af-4e67-9f7e-2ca45c9ec3ba.png)

### 👟 Reproduction steps

```
// packages/app/src/components/catalog/EntityPage.tsx
import {
  EntityGithubPullRequestsContent,
  isGithubPullRequestsAvailable,
} from '@roadiehq/backstage-plugin-github-pull-requests';
...

const serviceEntityPage = (
  <EntityLayout>
    ...
    <EntityLayout.Route
      path="/pull-requests"
      title="Pull Requests"
      // Uncomment the line below if you'd like to only show the tab on entities with the correct annotations already set
      // if={isGithubPullRequestsAvailable}
    >
      <EntityGithubPullRequestsContent />
    </EntityLayout.Route>
    ...
  </EntityLayout>
```

### 🖥️ Your Environment

   "@roadiehq/backstage-plugin-github-pull-requests": "^2.5.1",
    "react": "^17.0.2",
    "react-cookie": "^4.1.1",
    "react-dom": "^17.0.2",
    "react-router": "6.8.1",
    "react-router-dom": "^6.9.0",
    "react-use": "^17.2.4",

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by aswathysen** [comment]
Cool I'll have a check on these then.

**Comment by Remyapraveen** [comment]
Hi I am having a similar issue while trying to integrate the GitHub app for Authentication in Backstage. I am getting an error of multiple versions of React to be found. Any suggestions on how to rectify it. 

![image](https://user-images.githubusercontent.com/93478132/225636775-76e4e69a-18a3-42a8-8a4b-bb5f28682433.png)


Error
Error

Message
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

Stack Trace
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (webpack-internal:///../../node_modules/use-memo-one/node_modules/react/cjs/react.development.js:1465:13)
    at useState (webpack-internal:///../../node_modules/use-memo-one/node_modules/react/cjs/react.development.js:1496:20)
    at useMemoOne (webpack-internal:///../../node_modules/use-memo-one/dist/use-memo-one.esm.js:26:64)
    at useInstanceCount (webpack-internal:///../../node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:6973:63)
    at DragDropContext (webpack-internal:///../../node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:6983:19)
    at renderWithHooks (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3994:16)

**Comment by RobotSail** [comment]
I'm also running into this error when attempting to create a component with a `subRouteRef`.
