### ISSUE TITLE
🐛 Bug Report: Techdocs Collator Fail

### ISSUE THREAD

**Issue by marct83** [backstage/backstage#17059]
### 📜 Description

Search backend tries to collate the techdocs there are many errors. No techdocs results are showing in search results.

### 👍 Expected behavior

Search should show the techdocs results.

### 👎 Actual Behavior with Screenshots

This error is being emitted for every entity in the catalog with docs

```[1] 023-03-23T22:34:28.603Z backstage info ::ffff:127.0.0.1 - - [23/Mar/2023:22:34:28 +0000] "GET /api/techdocs/static/docs/toolbox/component/toolbox-pgw-api/search/search_index.json HTTP/1.1" 404 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 023-03-23T22:34:28.603Z search debug Failed to retrieve tech docs search index for entity toolbox/component/toolbox-pgw-api invalid json response body at http://localhost:7007/api/techdocs/static/docs/toolbox/component/toolbox-pgw-api/search/search_index.json reason: Unexpected end of JSON input type=invalid-json documentType=techdocs stack=FetchError: invalid json response body at http://localhost:7007/api/techdocs/static/docs/toolbox/component/toolbox-pgw-api/search/search_index.json reason: Unexpected end of JSON input
[1]     at /Users/marctremblay/toolbox/technology-division/node_modules/node-fetch/lib/index.js:273:32
[1]     at runMicrotasks (<anonymous>)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]     at async /Users/marctremblay/toolbox/technology-division/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:775:33
```

### 👟 Reproduction steps

It seems to happen when the techdocs collator runs.

### 🖥️ Your Environment

```OS:   Darwin 22.3.0 - darwin/arm64
node: v16.19.0
yarn: 1.22.19
cli:  0.22.4 (installed)
backstage:  1.11.1

Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1
  @backstage/backend-common                        0.13.5, 0.18.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.0
  @backstage/backend-tasks                         0.5.0
  @backstage/catalog-client                        1.4.0
  @backstage/catalog-model                         1.2.1
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.4
  @backstage/config-loader                         1.1.9
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.6.0
  @backstage/core-components                       0.12.5, 0.9.5
  @backstage/core-plugin-api                       1.5.0
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.2
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3
  @backstage/plugin-api-docs                       0.9.1
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.17.4, 0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend-module-gitlab  0.1.14
  @backstage/plugin-catalog-backend-module-ldap    0.5.10
  @backstage/plugin-catalog-backend                1.8.0
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-entity-feedback-backend        0.1.1
  @backstage/plugin-entity-feedback-common         0.1.0
  @backstage/plugin-entity-feedback                0.1.1
  @backstage/plugin-entity-validation              0.1.1
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-graphiql                       0.2.48
  @backstage/plugin-kafka-backend                  0.2.36
  @backstage/plugin-kafka                          0.3.16
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-permission-backend             0.5.18
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
✨  Done in 1.22s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by marct83** [comment]
I'm using PG as database and techdocs local in k8s. Only techdocs that I have opened are showing in the search. All other's don't show. These errors are in the logs. 

{"level":"info","message":"::ffff:127.0.0.1 - - [27/Mar/2023:14:04:29 +0000] \"GET /api/techdocs/static/docs/toolbox/component/toolbox-wifi-worker/search/search_index.json HTTP/1.1\" 404 - \"-\" \"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)\"","service":"backstage","type":"incomingRequest"}
