### ISSUE TITLE
🐛 Bug Report: plugin-catalog-backend-module-github backend fails

### ISSUE THREAD

**Issue by LyubomirGrancharov** [backstage/backstage#17240]
### 📜 Description

Backstage backend fails when I try to implement github discovery.

### 👍 Expected behavior

Github discovery should allow adding catalog entities within a GitHub organization automatically.

### 👎 Actual Behavior with Screenshots

The backstage backend fails with the following error:

`[1] Backend failed to start up Error: Expected a callback function but got a [object Undefined]
[1]     at wrapHandler (/home/lgrancharov/backstage-local/node_modules/express-promise-router/lib/express-promise-router.js:10:11)
[1]     at /home/lgrancharov/backstage-local/node_modules/express-promise-router/lib/express-promise-router.js:104:16
[1]     at Array.map (<anonymous>)
[1]     at instanceToWrap.<computed> [as use] (/home/lgrancharov/backstage-local/node_modules/express-promise-router/lib/express-promise-router.js:103:32)
[1]     at main (webpack-internal:///./src/index.ts:96:15)`

### 👟 Reproduction steps

I am following the official documentation about github discovery - https://backstage.io/docs/integrations/github/discovery

The steps I m doing are:

1. Creating backstage app  - `npx @backstage/create-app`
2. Installing plugin catalog backend-module - `yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-github`
3. Editing packages/backend/src/plugins/catalog.ts file
4. Adding catalog section in app-config.yaml

### 📃 Provide the context for the Bug.

Here are the files I m working with:

[app-config.txt](https://github.com/backstage/backstage/files/11148579/app-config.txt)
[catalog.txt](https://github.com/backstage/backstage/files/11148580/catalog.txt)

### 🖥️ Your Environment

`OS:   Linux 5.15.90.1-microsoft-standard-WSL2 - linux/x64
node: v18.15.0
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.12.0

Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1
  @backstage/backend-common                        0.18.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.0
  @backstage/backend-tasks                         0.5.0
  @backstage/catalog-client                        1.4.0
  @backstage/catalog-model                         1.2.1
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.5
  @backstage/config-loader                         1.1.9
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.6.0
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.2
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3
  @backstage/plugin-api-docs                       0.9.1
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend-module-github  0.2.6
  @backstage/plugin-catalog-backend                1.8.0
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-events-node                    0.2.4
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
Done in 0.98s.`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by LyubomirGrancharov** [comment]
This part was missing from the catalog.ts 

const { processingEngine, router } = await builder.build();
await processingEngine.start();
return router;

Now its working.
