### ISSUE TITLE
🐛 Bug Report: example backstage backend fails to startup with exception

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#17264]
### 📜 Description

The example backstage backend is failing to startup.

### 👍 Expected behavior

It should start up successfully.

### 👎 Actual Behavior with Screenshots

It shows the following exception:

```
Backend failed to start up TypeError: Cannot read properties of undefined (reading 'forEach')
    at eval (webpack-internal:///../../plugins/events-backend/src/service/DefaultEventBroker.ts:54:45)
    at Array.forEach (<anonymous>)
    at DefaultEventBroker.subscribe (webpack-internal:///../../plugins/events-backend/src/service/DefaultEventBroker.ts:53:28)
    at new DemoEventBasedEntityProvider (webpack-internal:///./src/plugins/DemoEventBasedEntityProvider.ts:49:21)
    at createPlugin (webpack-internal:///./src/plugins/catalog.ts:28:26)
    at async main (webpack-internal:///./src/index.ts:176:31)
```

### 👟 Reproduction steps

Pull master branch and run yarn start-backend

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Thanks for fixing! ❤️
