### ISSUE TITLE
🐛 Bug Report: Skipping admin access when using "publish:github" action

### ISSUE THREAD

**Issue by grvpandey11** [backstage/backstage#17385]
### 📜 Description

I am using "publish:github" action in Software Template.
While running I am getting below warning 

`
warn: Skipping admin access for group:default/abc, Not Found
`

The action is looking for GitHub team  'group:default/abc' instead of team 'abc'

The owner name is getting appended with **group:default/** by it's own

My template file have below code as 'publish:github'

```
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        defaultBranch: main
        protectDefaultBranch: false
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: internal
        collaborators:
          - access: admin
            team: ${{ parameters.owner }}
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: ${{ user.entity.spec.profile.email }}
```

### 👍 Expected behavior

'publish:github'  should be able to set permission for respective team in GitHub

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/36168816/232037120-7f37afb5-90c6-4098-a8c1-9f3c94e928f0.png)

### 👟 Reproduction steps

1. Use 'publish:github' in your template.yaml file
2. Add below code in the action
``` 
       collaborators:
          - access: admin
            team: ${{ parameters.owner }}
```
3. Run the action.

### 📃 Provide the context for the Bug.

Users are not getting permission to the repository which is getting created from Backstage Software Template.
We have to give them permissions manually which should not be the case.

### 🖥️ Your Environment

node: v16.15.0
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.12.1
```
Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1 
  @backstage/backend-common                        0.18.3
  @backstage/backend-dev-utils                     0.1.1 
  @backstage/backend-plugin-api                    0.5.0 
  @backstage/backend-tasks                         0.5.0 
  @backstage/catalog-client                        1.4.0 
  @backstage/catalog-model                         1.2.1 
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.5
  @backstage/config-loader                         1.1.9 
  @backstage/config                                1.0.7 
  @backstage/core-app-api                          1.6.0 
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0 
  @backstage/dev-utils                             1.0.13
  @backstage/errors                                1.1.5 
  @backstage/eslint-plugin                         0.1.2 
  @backstage/integration-aws-node                  0.1.2 
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3 
  @backstage/plugin-api-docs                       0.9.1 
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend-module-github  0.2.6 
  @backstage/plugin-catalog-backend                1.8.0 
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-events-node                    0.2.4
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-home                           0.4.32
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-sentry                         0.5.1
  @backstage/plugin-stack-overflow-backend         0.1.12
  @backstage/plugin-stack-overflow                 0.1.12
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
Hi @grvpandey11, sorry that you ran into this issue. There was a change to always return an `entityRef` (`kind:namespace/name`) in the last release. More details can be found in this issue: https://github.com/backstage/backstage/issues/16301 or the related PR: https://github.com/backstage/backstage/pull/16577

There is a feature to make it easier to work with `entityRefs` but it has not been released outside of the nightly and weekly releases - expected monthly release date is April 18th. More details on this can be found here: https://github.com/backstage/backstage/issues/17053 and the PR is here: https://github.com/backstage/backstage/pull/17091

**Comment by ArtemChekunov** [comment]
Hi @awanlin,

I met the same issue.

but when I bump the backstage to the next release the software templates stop working 
```
--- a/backstage.json
+++ b/backstage.json
@@ -1,3 +1,3 @@
 {
-  "version": "1.12.1"
+  "version": "1.13.0"
 }
```

```
[1](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-1)2023-04-19T11:46:22.938Z Beginning step Base Skeleton[2](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-2)2023-04-19T11:46:22.965Z info: Fetching template content from remote URL[3](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-3)2023-04-19T11:46:23.207Z NotFoundError: Request failed for [https://api.github.com/repos/COMPANY/software-templates/commits/add-fast-api-software-template/status?per_page=0, Opens in a new window](https://api.github.com/repos/COMPANY/software-templates/commits/add-fast-api-software-template/status?per_page=0), [4](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-4)04 Not Found4    at _GithubUrlReader.fetchResponse (/Users/artem/git/backstage/node_modules/@backstage/backend-common/dist/index.cjs.js:2379:15)[5](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-5)    at runMicrotasks (<anonymous>)[6](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-6)    at processTicksAndRejections (node:internal/process/task_queues:96:5)[7](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-7)    at async _GithubUrlReader.fetchJson (/Users/artem/git/backstage/node_modules/@backstage/backend-common/dist/index.cjs.js:2386:22)[8](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-8)    at async _GithubUrlReader.getRepoDetails (/Users/artem/git/backstage/node_modules/@backstage/backend-common/dist/index.cjs.js:2357:26)[9](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-9)    at async _GithubUrlReader.readTree (/Users/artem/git/backstage/node_modules/@backstage/backend-common/dist/index.cjs.js:2255:25)[10](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-10)    at async UrlReaderPredicateMux.readTree (/Users/artem/git/backstage/node_modules/@backstage/backend-common/dist/index.cjs.js:3130:16)[11](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-11)    at async fetchContents (/Users/artem/git/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-2f24bb9e.cjs.js:565:17)[12](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-12)    at async Object.handler (/Users/artem/git/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-2f24bb9e.cjs.js:1006:7)[13](http://localhost:7007/create/tasks/7ab68f7f-8b1b-4734-8990-41c90c9db842#line-13)    at async NunjucksWorkflowRunner.executeStep (/Users/artem/git/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-2f24bb9e.cjs.js:5187:7)
```

**Comment by ArtemChekunov** [comment]
@grvpandey11 

here is a workaround for "1.12"
```
        collaborators:
          - access: admin
            team: ${{ parameters.owner | replace("group:default/", "") }}
```

**Comment by grvpandey11** [comment]
@ArtemChekunov Yes, I am using the same as workaround for now.

**Comment by awanlin** [comment]
@ArtemChekunov I had the same error after upgrading to `1.13.0`. To be clear it doesn't break everything but if you just use GitHub it would seem that way; most of our software templates still worked.

So for us we use a GitHub App and the fix was to give it read access to Commit statuses:

![image](https://user-images.githubusercontent.com/67169551/233096715-96e8be2e-bb6a-4400-b836-c12c174898c0.png)

**Comment by ArtemChekunov** [comment]
@awanlin 

unfortunately, it didn't help

**Comment by awanlin** [comment]
OK, not sure what to say but that 100% fixes the issue if you are using a GitHub app, did you make sure it was also approved?

**Comment by ArtemChekunov** [comment]
ah, sorry, my bad
last time I forget to pick up a second config 
the solutions is working

**Comment by awanlin** [comment]
No worries @ArtemChekunov, glad it is working for you 🚀

**Comment by grvpandey11** [comment]
Closing the issue since solution is available in latest release
Thanks @awanlin for helping.
