### ISSUE TITLE
🐛 Bug Report: GitlabOrgDiscoveryEntityProvider

### ISSUE THREAD

**Issue by sbarrypoppulo** [backstage/backstage#17735]
### 📜 Description

I have configured the `GitlabOrgDiscoveryEntityProvider` entity provider with `orgEnabled: true` and seeing an error in the backend logs (see below), which prevents ingestion of `User` and `Group` entities from GitLab.

The GitLab Personal Access Token used in the config has the following scope:
- `api`, `read_repository`, `admin_mode`

### 👍 Expected behavior

The `GitlabOrgDiscoveryEntityProvider` should work without error and ingest `User` and `Group` entities

### 👎 Actual Behavior with Screenshots

The `GitlabOrgDiscoveryEntityProvider` throw the following error on refresh:

```bash
2023-05-10T09:36:04.985Z catalog error GitlabOrgDiscoveryEntityProvider:gitlabSelfHostedData refresh failedCannot read properties of null (reading 'id') type=plugin target=GitlabOrgDiscoveryEntityProvider:gitlabSelfHostedData class=GitlabOrgDiscoveryEntityProvider taskId=GitlabOrgDiscoveryEntityProvider:gitlabSelfHostedData:refresh taskInstanceId=7da67e5b-3663-40ca-9412-b3a677987b34 stack=TypeError: Cannot read properties of null (reading 'id')
    at /Users/stephenbarry/Development/backstage/backstage-app/node_modules/@backstage/plugin-catalog-backend-module-gitlab/dist/cjs/GitlabDiscoveryEntityProvider-1de558b0.cjs.js:103:38
    at Array.map (<anonymous>)
    at GitLabClient.getGroupMembers (/Users/stephenbarry/Development/backstage/backstage-app/node_modules/@backstage/plugin-catalog-backend-module-gitlab/dist/cjs/GitlabDiscoveryEntityProvider-1de558b0.cjs.js:102:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GitlabOrgDiscoveryEntityProvider.refresh (/Users/stephenbarry/Development/backstage/backstage-app/node_modules/@backstage/plugin-catalog-backend-module-gitlab/dist/index.cjs.js:271:24)
    at async TaskWorker.fn (/Users/stephenbarry/Development/backstage/backstage-app/node_modules/@backstage/plugin-catalog-backend-module-gitlab/dist/index.cjs.js:211:13)
    at async TaskWorker.runOnce (/Users/stephenbarry/Development/backstage/backstage-app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:360:7)
    at async /Users/stephenbarry/Development/backstage/backstage-app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:308:31
```

### 👟 Reproduction steps

1. Configure the `GitlabOrgDiscoveryEntityProvider` in `backend/src/plugins/catalog.ts`
```typescript
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import {
  GitlabDiscoveryEntityProvider,
  GitlabOrgDiscoveryEntityProvider,
} from '@backstage/plugin-catalog-backend-module-gitlab';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addEntityProvider(
    ...GitlabDiscoveryEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      scheduler: env.scheduler,
    }),
  );
  builder.addEntityProvider(
    ...GitlabOrgDiscoveryEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      scheduler: env.scheduler,
    }),
  );
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
```
2. Configure the GitLab provider in `app-config.yaml`
```yaml
...
catalog:
  providers:
    gitlab:
      gitlabSelfHostedData:
        host: gitlab.mydomain.com
        orgEnabled: true
        schedule:
          frequency: { minutes: 5 }
          timeout: { minutes: 20 }
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location, Domain, Template]
```
3. Start the Backstage backend `yarn --cwd packages/backend start`

### 📃 Provide the context for the Bug.

Testing the functionality to ingest Org data from GitLab via EntityProvider

### 🖥️ Your Environment

```bash
OS:   Darwin 20.6.0 - darwin/x64
node: v16.14.2
yarn: 1.22.17
cli:  0.22.6 (installed)
backstage:  1.13.1

Dependencies:
  @backstage/app-defaults                               1.3.0
  @backstage/backend-app-api                            0.4.2
  @backstage/backend-common                             0.18.4
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.1
  @backstage/backend-tasks                              0.5.1
  @backstage/catalog-client                             1.4.1
  @backstage/catalog-model                              1.2.0, 1.3.0
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.0
  @backstage/cli                                        0.22.6
  @backstage/config-loader                              1.2.0
  @backstage/config                                     1.0.7
  @backstage/core-app-api                               1.7.0
  @backstage/core-components                            0.12.4, 0.12.5, 0.13.0
  @backstage/core-plugin-api                            1.0.6, 1.5.1
  @backstage/dev-utils                                  1.0.14
  @backstage/errors                                     1.1.5
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.2
  @backstage/integration-react                          1.1.12
  @backstage/integration                                1.4.4
  @backstage/plugin-api-docs                            0.9.2
  @backstage/plugin-app-backend                         0.3.44
  @backstage/plugin-auth-backend                        0.18.2
  @backstage/plugin-auth-node                           0.2.13
  @backstage/plugin-bazaar-backend                      0.2.7
  @backstage/plugin-bazaar                              0.2.7
  @backstage/plugin-catalog-backend-module-gitlab       0.2.0
  @backstage/plugin-catalog-backend                     1.9.0
  @backstage/plugin-catalog-common                      1.0.13
  @backstage/plugin-catalog-graph                       0.2.29
  @backstage/plugin-catalog-import                      0.9.7
  @backstage/plugin-catalog-node                        1.3.5
  @backstage/plugin-catalog-react                       1.2.1, 1.5.0
  @backstage/plugin-catalog                             1.10.0
  @backstage/plugin-entity-validation                   0.1.2
  @backstage/plugin-explore-backend                     0.0.6
  @backstage/plugin-explore-common                      0.0.1
  @backstage/plugin-explore-react                       0.0.28
  @backstage/plugin-explore                             0.4.2
  @backstage/plugin-github-actions                      0.5.17
  @backstage/plugin-home                                0.5.0
  @backstage/plugin-kubernetes-backend                  0.10.0
  @backstage/plugin-kubernetes-common                   0.6.2
  @backstage/plugin-kubernetes                          0.8.0
  @backstage/plugin-org                                 0.6.7
  @backstage/plugin-permission-common                   0.7.5
  @backstage/plugin-permission-node                     0.7.7
  @backstage/plugin-permission-react                    0.4.12
  @backstage/plugin-proxy-backend                       0.2.38
  @backstage/plugin-scaffolder-backend-module-yeoman    0.2.17
  @backstage/plugin-scaffolder-backend                  1.13.1
  @backstage/plugin-scaffolder-common                   1.2.7
  @backstage/plugin-scaffolder-node                     0.1.2
  @backstage/plugin-scaffolder-react                    1.3.0
  @backstage/plugin-scaffolder                          1.13.0
  @backstage/plugin-search-backend-module-catalog       0.1.0
  @backstage/plugin-search-backend-module-explore       0.1.0
  @backstage/plugin-search-backend-module-techdocs      0.1.0
  @backstage/plugin-search-backend-node                 1.2.0
  @backstage/plugin-search-backend                      1.3.0
  @backstage/plugin-search-common                       1.2.3
  @backstage/plugin-search-react                        1.5.2
  @backstage/plugin-search                              1.2.0
  @backstage/plugin-sentry                              0.5.2
  @backstage/plugin-shortcuts                           0.3.9
  @backstage/plugin-sonarqube-backend                   0.1.9
  @backstage/plugin-sonarqube-react                     0.1.5
  @backstage/plugin-sonarqube                           0.6.6
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.28
  @backstage/plugin-tech-insights-backend               0.5.10
  @backstage/plugin-tech-insights-common                0.2.10
  @backstage/plugin-tech-insights-node                  0.4.2
  @backstage/plugin-tech-insights                       0.3.9
  @backstage/plugin-tech-radar                          0.6.3
  @backstage/plugin-techdocs-backend                    1.6.1
  @backstage/plugin-techdocs-module-addons-contrib      1.0.12
  @backstage/plugin-techdocs-node                       1.7.0
  @backstage/plugin-techdocs-react                      1.1.5
  @backstage/plugin-techdocs                            1.6.1
  @backstage/plugin-user-settings                       0.7.2
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.3.0
  @backstage/theme                                      0.2.19
  @backstage/types                                      1.0.2
  @backstage/version-bridge                             1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by rolandsgs** [comment]
Hy @sbarrypoppulo, i'm with the same problem. Intersting is the fact the same code runs locally, but i cant run on production. Which version of gitlab are you running? In the latest version of community dont have problem (running locally)
In production we are using 15.9.0-ee. I'm justing guessing, dont know if its related

**Comment by sbarrypoppulo** [comment]
Interesting, I haven't personally tried this with a local GitLab instance. Our GitLab EE production instance that I am connecting to is on `15.11.0-ee`.

**Comment by jamieklassen** [comment]
Reading the stack trace, it looks like `node.user` is `null` in this map:

https://github.com/backstage/backstage/blob/667c490cc10fdb6dea06ccfe7ef2ab92364d7d45/plugins/catalog-backend-module-gitlab/src/lib/client.ts#L131-L134

Not sure why that would be, given this is the GraphQL query being run:

https://github.com/backstage/backstage/blob/667c490cc10fdb6dea06ccfe7ef2ab92364d7d45/plugins/catalog-backend-module-gitlab/src/lib/client.ts#L109-L123

I changed these lines when I created #16856, and you can see the procedure I used to test my changes there. I'm guessing it was 15.9 that I tested against.

**Comment by sbarrypoppulo** [comment]
Yep, so I deleted the invite for the project bot user (i.e. project access token bot user) from the group, and the GraphQL query for the associated group no longer returns the `null` user node. And I can now see the groups and user entities ingested 🎉

**Comment by freben** [comment]
Thanks for tracking what the actual cause was - made https://github.com/backstage/backstage/pull/17774 to make it deal gracefully with these corner cases.
