### ISSUE TITLE
🔌 Plugin: Auth-backend: Create OIDC provider from scratch

### ISSUE THREAD

**Issue by vijaykrishnach1** [backstage/backstage#18220]
### 🔖 Summary

Creating new  OIDC provider from scratch for PingFederate and followed the steps in this link.
https://backstage.io/docs/auth/oidc/
Getting this error:
[3:35 PM] Krishna, Vijay-CW

{"error":{"name":"NotFoundError","message":"No auth provider registered for 'pingfederate-auth-provider'","stack":"NotFoundError: No auth provider registered for 'pingfederate-auth-provider'\n    at /node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:3539:15\n    at handleReturn (/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/node_modules/express/lib/router/index.js:328:13)\n    at /node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/node_modules/express/lib/router/index.js:346:12)\n    at next (/node_modules/express/lib/router/index.js:280:10)\n    at jsonParser (/node_modules/body-parser/lib/types/json.js:110:7)\n    at handleReturn (/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at jsonParser (/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/node_modules/express/lib/router/index.js:328:13)\n    at /node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/node_modules/express/lib/router/index.js:346:12)\n    at next (/node_modules/express/lib/router/index.js:280:10)"},"request":{"method":"GET","url":"/api/auth/pingfederate-auth-provider/start?scope=openid%20profile&origin=http%3A%2F%2Flocalhost%3A3000&env=local"},"response":{"statusCode":404}}

### ✌️ Context

I have added in auth.ts 
#Step 3 from Documentation: The Auth Provider
'pingfederate-auth-provider': providers.oidc.create({

        signIn: {

          resolver(info, ctx) {

            const userRef = stringifyEntityRef({

              kind: 'User',

              name: info.result.userinfo.sub,

              namespace: DEFAULT_NAMESPACE,

            });

            return ctx.issueToken({

              claims: {

                sub: userRef, // The user's own identity

                ent: [userRef], // A list of identities that the user claims ownership through

              },

            });

          },

        },

      }),

#Step 5 from Documentation: The configuration
Added with same ID in app-config.xml
pingfederate-auth-provider:

      local:

        callbackUrl: ${APP_BASE_URL}/api/auth/pingfederate-auth-provider/handler/frame

        clientId:

        clientSecret:

      test:

        callbackUrl: ${APP_BASE_URL}/api/auth/pingfederate-auth-provider/handler/frame

        clientId:

        clientSecret:

      production:

        callbackUrl: ${APP_BASE_URL}/api/auth/pingfederate-auth-provider/handler/frame

        clientId:

        clientSecret:

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jamieklassen** [comment]
This strikes me more as a support discussions (or possibly a bug report) than a plugin request? The error message you pasted looks like this one:

https://github.com/backstage/backstage/blob/5f5727189aff6217cf4f4da996fd68692d5b4377/plugins/auth-backend/src/service/router.ts#L185

which suggests that you've defined a provider factory for that ID, but that it's missing from your app config. It doesn't look like you shared a complete app config; at the top level it should look something like

```yaml
auth:
  environment: local
  providers:
    pingfederate-auth-provider:
      local:
        callbackUrl:
        clientId:
        clientSecret:
```

**Comment by vijaykrishnach1** [comment]
Agree, it support required on existing plugin - Auth-backend. I have already added this in my app-config.yaml.. Is there anything else i need to be doing for the  NEW auth provider to be registered?


 app-config.yaml

auth:

  environment: ${ENVIRONMENT}




  providers:

    github:

      local:

        clientId: ${GITHUB_CLIENT_ID}

        clientSecret: ${GITHUB_CLIENT_SECRET}

        callbackUrl: ${APP_BASE_URL}/api/auth/github/handler/frame

      test:

        clientId: ${GITHUB_CLIENT_ID}

        clientSecret: ${GITHUB_CLIENT_SECRET}

        callbackUrl: ${APP_BASE_URL}/api/auth/github/handler/frame

      production:

        clientId: ${GITHUB_CLIENT_ID}

        clientSecret: ${GITHUB_CLIENT_SECRET}

        callbackUrl: ${APP_BASE_URL}/api/auth/github/handler/frame

    pingfederate-auth-provider:

      local:

        callbackUrl: ${APP_BASE_URL}/api/auth/pingfederate-auth-provider/handler/frame

        authorizationUrl: ${AUTH_URL}

        clientId: ${PING_CLIENT_ID}

        clientSecret: ${PING_CLIENT_SECRET}

      test:

        callbackUrl: ${APP_BASE_URL}/api/auth/pingfederate-auth-provider/handler/frame

        authorizationUrl: ${AUTH_URL}

        clientId: ${PING_CLIENT_ID}

        clientSecret: ${PING_CLIENT_SECRET}

      production:

        callbackUrl: ${APP_BASE_URL}/api/auth/pingfederate-auth-provider/handler/frame

        authorizationUrl: ${AUTH_URL}

        clientId: ${PING_CLIENT_ID}

        clientSecret: ${PING_CLIENT_SECRET}

**Comment by jamieklassen** [comment]
A couple things:
* Can you be very careful to copy the exact contents of your app-config into a single fenced code block (ideally with [YAML syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting))? You have the keys `auth`, `environment` and `providers` kinda hanging loose above the rest of the config, which makes it impossible to tell if you might have a YAML indentation error or something silly like that.
* Can you share a more complete code sample? Like put your auth provider in a public repo somewhere where other people can clone and test it themselves?

**Comment by vijaykrishnach1** [comment]
i can confirm Yaml indentation is fine, let me see if i can get this code into public repo
