### ISSUE TITLE
🐛 Bug Report: Authentication Error with GitHub OAuth caused by missing session cookies

### ISSUE THREAD

**Issue by ChiaraKr** [backstage/backstage#18335]
### 📜 Description

I am running backstage in WSL and trying to use authentication with GitHub OAuth app. 
After accepting the application during the log in process in the pop up window an error occurs after being redirected to the backstage URL. 

Error message: "Authentication failed. Failed to obtain access token."

Having a closer look into the log messages it says that session cookies are missing. 

```json
{
    "error": {
        "name": "AuthenticationError",
        "message": "Refresh failed; caused by InputError: Missing session cookie",
        "cause": {
            "name": "InputError",
            "message": "Missing session cookie",
            "stack": "InputError: Missing session cookie\n    at OAuthAdapter.refresh (<PATH TO BACKSTAGE>/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:460:15)\n    at OAuthEnvironmentHandler.refresh (<PATH TO BACKSTAGE>/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:209:58)\n    at handleReturn (<PATH TO BACKSTAGE>/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (<PATH TO BACKSTAGE>/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at handleReturn (<PATH TO BACKSTAGE>/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (<PATH TO BACKSTAGE>/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at Layer.handle [as handle_request] (<PATH TO BACKSTAGE>/node_modules/express/lib/router/layer.js:95:5)\n    at next (<PATH TO BACKSTAGE>/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (<PATH TO BACKSTAGE>/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (<PATH TO BACKSTAGE>/node_modules/express/lib/router/layer.js:95:5)\n    at <PATH TO BACKSTAGE>/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (<PATH TO BACKSTAGE>/node_modules/express/lib/router/index.js:346:12)\n    at next (<PATH TO BACKSTAGE>/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (<PATH TO BACKSTAGE>/node_modules/express/lib/router/index.js:175:3)\n    at router (<PATH TO BACKSTAGE>/node_modules/express/lib/router/index.js:47:12)\n    at handleReturn (<PATH TO BACKSTAGE>/node_modules/express-promise-router/lib/express-promise-router.js:24:23)"
        },
        "stack": "AuthenticationError: Refresh failed; caused by InputError: Missing session cookie\n    at OAuthAdapter.refresh (<PATH TO BACKSTAGE>/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:478:13)\n    at OAuthEnvironmentHandler.refresh (<PATH TO BACKSTAGE>/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:209:58)\n    at handleReturn (<PATH TO BACKSTAGE>/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (<PATH TO BACKSTAGE>/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at handleReturn (<PATH TO BACKSTAGE>/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (<PATH TO BACKSTAGE>/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at Layer.handle [as handle_request] (<PATH TO BACKSTAGE>/node_modules/express/lib/router/layer.js:95:5)\n    at next (<PATH TO BACKSTAGE>/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (<PATH TO BACKSTAGE>/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (<PATH TO BACKSTAGE>/node_modules/express/lib/router/layer.js:95:5)\n    at <PATH TO BACKSTAGE>/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (<PATH TO BACKSTAGE>/node_modules/express/lib/router/index.js:346:12)\n    at next (<PATH TO BACKSTAGE>/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (<PATH TO BACKSTAGE>/node_modules/express/lib/router/index.js:175:3)\n    at router (<PATH TO BACKSTAGE>/node_modules/express/lib/router/index.js:47:12)\n    at handleReturn (<PATH TO BACKSTAGE>/node_modules/express-promise-router/lib/express-promise-router.js:24:23)"
    },
    "request": {
        "method": "GET",
        "url": "/api/auth/github/refresh?optional&scope=&env=development"
    },
    "response": {
        "statusCode": 401
    }
}
``` 

### 👍 Expected behavior

After granting access in the GitHub login pop up window the authentication should be completed. 

### 👎 Actual Behavior with Screenshots

The OAuth app in GitHub has no usage tracked. The token is therefore never used. 

![image](https://github.com/backstage/backstage/assets/60965659/fca90f04-9d2f-43ad-90f6-f3dcea603321)
![image](https://github.com/backstage/backstage/assets/60965659/900e3314-c3e9-43a6-84e9-37942b3aa818)

### 👟 Reproduction steps

The steps were made following the Backstage [Stand Up tutorial](https://backstage.spotify.com/learn/standing-up-backstage/configuring-backstage/7-authentication/).

conig in ``app-config.local.yaml``
```yaml
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    github:
      development:
        clientId: MY CLIENT ID
        clientSecret: MY CLIENT SECRET
``` 

### 🖥️ Your Environment

Windows Subsystem for Linux with Ubuntu 20.04 LTS.

```
yarn run v1.22.19
$ /home/chiara/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v16.20.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.0

Dependencies:
  @backstage/app-defaults                          1.3.1
  @backstage/backend-app-api                       0.4.3
  @backstage/backend-common                        0.18.5
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.2
  @backstage/backend-tasks                         0.5.2
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.7
  @backstage/config-loader                         1.3.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.8.0
  @backstage/core-components                       0.13.1
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.3
  @backstage/integration-react                     1.1.13
  @backstage/integration                           1.4.5
  @backstage/plugin-api-docs                       0.9.4
  @backstage/plugin-app-backend                    0.3.45
  @backstage/plugin-auth-backend                   0.18.3
  @backstage/plugin-auth-node                      0.2.14
  @backstage/plugin-catalog-backend-module-gitlab  0.2.1
  @backstage/plugin-catalog-backend                1.9.1
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.30
  @backstage/plugin-catalog-import                 0.9.8
  @backstage/plugin-catalog-node                   1.3.6
  @backstage/plugin-catalog-react                  1.6.0
  @backstage/plugin-catalog                        1.11.1
  @backstage/plugin-github-actions                 0.5.18
  @backstage/plugin-org                            0.6.8
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.8
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.39
  @backstage/plugin-scaffolder-backend             1.14.0
  @backstage/plugin-scaffolder-common              1.3.0
  @backstage/plugin-scaffolder-node                0.1.3
  @backstage/plugin-scaffolder-react               1.4.0
  @backstage/plugin-scaffolder                     1.13.1
  @backstage/plugin-search-backend-module-catalog  0.1.1
  @backstage/plugin-search-backend-module-pg       0.5.6
  @backstage/plugin-search-backend-module-techdocs 0.1.1
  @backstage/plugin-search-backend-node            1.2.1
  @backstage/plugin-search-backend                 1.3.1
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.6.1
  @backstage/plugin-search                         1.3.1
  @backstage/plugin-tech-radar                     0.6.4
  @backstage/plugin-techdocs-backend               1.6.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.13
  @backstage/plugin-techdocs-node                  1.7.1
  @backstage/plugin-techdocs-react                 1.1.6
  @backstage/plugin-techdocs                       1.6.3
  @backstage/plugin-user-settings                  0.7.3
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.1
  @backstage/theme                                 0.3.0
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4
``` 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by AmbrishRamachandiran** [comment]
Simply use Google DNS to fix the problem because it usually results from a DNS restriction on the wsl side

**Steps :**
1.Go to wsl and edit following file using below command
sudo nano /etc/resolv.conf

2.Add the dns server ips 
nameserver 8.8.8.8
nameserver 4.4.4.4
save it and try to access the backstage github login now

**Comment by AmbrishRamachandiran** [comment]
@ChiaraKr did you tried the solution if its helps can you confirm it for closing this one.

**Comment by sabinasiddiqi** [comment]
Same issue here - what was the solution or workaround?

**Comment by ashutoshdcx** [comment]
Hey @sabinasiddiqi @ChiaraKr 

I am facing the same issue. Did you find any solution for this ?

**Comment by LeBaronDeCharlus** [comment]
By any chances, did you update your clientSecret on both your-github-private-key.yaml and app-config.yaml files ?

**Comment by dosht** [comment]
I followed the documentation and get the same error with Microsoft provider. 
My `app-config.yaml` looks like this:

```yaml
auth:
  environment: development
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    guest: {}
    microsoft:
      development:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        callbackUrl: https://my-domain/auth/microsoft/handler/frame
        signIn:
          resolvers:
            # See https://backstage.io/docs/auth/microsoft/provider#resolvers for more resolvers
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName
            - resolver: usernameMatchingUserEntityName
```
Is there anything missing here? I don't see any cookie created for Microsoft provider.
