### ISSUE TITLE
Customizable home page breaks on larger screens

### ISSUE THREAD

**Issue by jmezach** [backstage/backstage#18468]
### 📜 Description

We've introduced the customizable homepage last week in our Backstage instance, and all seemed to be working fine. But this morning when I got back to the office and I plugged in my external monitor I started seeing this error:

```
Error
ResponsiveReactGridLayout: `cols` entry for breakpoint xl is missing!
Error: ResponsiveReactGridLayout: `cols` entry for breakpoint xl is missing!
    at L (https://backstage.cloud.rr-wfm.com/static/module-react-grid-layout.ebe04bf3.js:3:27930)
    at c.value (https://backstage.cloud.rr-wfm.com/static/module-react-grid-layout.ebe04bf3.js:3:18732)
    at c.value (https://backstage.cloud.rr-wfm.com/static/module-react-grid-layout.ebe04bf3.js:3:18456)
    at Ya (https://backstage.cloud.rr-wfm.com/static/module-react-dom.1e98f356.js:14:1764)
    at qa (https://backstage.cloud.rr-wfm.com/static/module-react-dom.1e98f356.js:16:5030)
    at w.unstable_runWithPriority (https://backstage.cloud.rr-wfm.com/static/vendor.9b9db2e0.js:172:3906)
    at Ze (https://backstage.cloud.rr-wfm.com/static/module-react-dom.1e98f356.js:12:38480)
    at nn (https://backstage.cloud.rr-wfm.com/static/module-react-dom.1e98f356.js:16:1807)
    at Si (https://backstage.cloud.rr-wfm.com/static/module-react-dom.1e98f356.js:14:11069)
    at https://backstage.cloud.rr-wfm.com/static/module-react-dom.1e98f356.js:12:38702
```

### 👍 Expected behavior

The home page should render as intended.

### 👎 Actual Behavior with Screenshots

Instead I see this:

![Web capture_28-6-2023_84015_backstage cloud rr-wfm com](https://github.com/backstage/backstage/assets/1225489/c2cf92a3-2bf9-40e4-a1cd-9aeabb4a1d74)

### 👟 Reproduction steps

1. Create Backstage instance
2. Add the [customizable homepage](https://github.com/backstage/backstage/blob/master/plugins/home/README.md#customizable-home-page)
3. Open the Backstage instance on a screen larger than 2192 pixels (2192 pixels or smaller works fine)
4. See the error shown above

### 🖥️ Your Environment

OS: Linux 5.15.0-1038-azure - linux/x64
node: v16.20.1
backstage: 1.15.0
Dependencies:
    @backstage/app-defaults: 1.4.0
    @backstage/backend-app-api: 0.4.4
    @backstage/backend-common: 0.18.5, 0.19.0
    @backstage/backend-dev-utils: 0.1.1
    @backstage/backend-plugin-api: 0.5.3
    @backstage/backend-tasks: 0.5.3
    @backstage/catalog-client: 1.4.2
    @backstage/catalog-model: 1.4.0
    @backstage/cli-common: 0.1.12
    @backstage/cli-node: 0.1.1
    @backstage/cli: 0.22.8
    @backstage/config-loader: 1.3.1
    @backstage/config: 1.0.8
    @backstage/core-app-api: 1.8.1
    @backstage/core-components: 0.12.5, 0.13.2
    @backstage/core-plugin-api: 1.5.2
    @backstage/errors: 1.2.0
    @backstage/eslint-plugin: 0.1.3
    @backstage/integration-aws-node: 0.1.4
    @backstage/integration-react: 1.1.14
    @backstage/integration: 1.5.0
    @backstage/plugin-adr-backend: 0.3.4
    @backstage/plugin-adr-common: 0.2.10
    @backstage/plugin-adr: 0.6.2
    @backstage/plugin-api-docs: 0.9.5
    @backstage/plugin-app-backend: 0.3.46
    @backstage/plugin-auth-backend: 0.18.4
    @backstage/plugin-auth-node: 0.2.15
    @backstage/plugin-azure-devops-backend: 0.3.25
    @backstage/plugin-azure-devops-common: 0.3.0
    @backstage/plugin-azure-devops: 0.3.1
    @backstage/plugin-catalog-backend-module-azure: 0.1.17
    @backstage/plugin-catalog-backend-module-msgraph: 0.5.5
    @backstage/plugin-catalog-backend: 1.10.0
    @backstage/plugin-catalog-common: 1.0.14
    @backstage/plugin-catalog-graph: 0.2.31
    @backstage/plugin-catalog-import: 0.9.9
    @backstage/plugin-catalog-node: 1.3.7
    @backstage/plugin-catalog-react: 1.7.0
    @backstage/plugin-catalog: 1.11.2
    @backstage/plugin-devtools-backend: 0.1.1
    @backstage/plugin-devtools-common: 0.1.1
    @backstage/plugin-devtools: 0.1.1
    @backstage/plugin-entity-validation: 0.1.4
    @backstage/plugin-events-node: 0.2.7
    @backstage/plugin-explore-backend: 0.0.8
    @backstage/plugin-explore-common: 0.0.1
    @backstage/plugin-explore-react: 0.0.29
    @backstage/plugin-explore: 0.4.5
    @backstage/plugin-github-actions: 0.6.0
    @backstage/plugin-home-react: 0.1.0
    @backstage/plugin-home: 0.5.3
    @backstage/plugin-octopus-deploy: 0.2.1
    @backstage/plugin-org: 0.6.9
    @backstage/plugin-permission-common: 0.7.6
    @backstage/plugin-permission-node: 0.7.9
    @backstage/plugin-permission-react: 0.4.13
    @backstage/plugin-proxy-backend: 0.2.40
    @backstage/plugin-scaffolder-backend: 1.15.0
    @backstage/plugin-scaffolder-common: 1.3.1
    @backstage/plugin-scaffolder-node: 0.1.4
    @backstage/plugin-scaffolder-react: 1.5.0
    @backstage/plugin-scaffolder: 1.14.0
    @backstage/plugin-search-backend-module-catalog: 0.1.2
    @backstage/plugin-search-backend-module-explore: 0.1.2
    @backstage/plugin-search-backend-module-pg: 0.5.7
    @backstage/plugin-search-backend-module-techdocs: 0.1.2
    @backstage/plugin-search-backend-node: 1.2.2
    @backstage/plugin-search-backend: 1.3.2
    @backstage/plugin-search-common: 1.2.4
    @backstage/plugin-search-react: 1.6.2
    @backstage/plugin-search: 1.3.2
    @backstage/plugin-sonarqube-backend: 0.2.0
    @backstage/plugin-sonarqube-react: 0.1.6
    @backstage/plugin-sonarqube: 0.7.0
    @backstage/plugin-tech-radar: 0.6.5
    @backstage/plugin-techdocs-backend: 1.6.3
    @backstage/plugin-techdocs-module-addons-contrib: 1.0.14
    @backstage/plugin-techdocs-node: 1.7.2
    @backstage/plugin-techdocs-react: 1.1.7
    @backstage/plugin-techdocs: 1.6.4
    @backstage/plugin-user-settings: 0.7.4
    @backstage/release-manifests: 0.0.9
    @backstage/test-utils: 1.4.0
    @backstage/theme: 0.2.19, 0.4.0
    @backstage/types: 1.1.0
    @backstage/version-bridge: 1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by clanghout** [comment]
Running into the same thing. Are you working on a fix?

**Comment by awanlin** [comment]
Perhaps this is the fix? https://github.com/backstage/backstage/pull/18467

CC @drodil

**Comment by clanghout** [comment]
Yeah that MR is very much related!

@jmezach I have the same issue with the workaround indeed 😢
