### ISSUE TITLE
🐛 Bug Report: Could not find Python installation to use in Dockerfile build

### ISSUE THREAD

**Issue by fosterm-mw** [backstage/backstage#18717]
### 📜 Description

We are using postgresql and have no dependencies on sqlite3. When building the backstage image with the multistage dockerfile from https://backstage.io/docs/deployment/docker it fails to build. When adding back in the sqlite3 dependencies in the dockerfile, the error goes away and we are able to build the image.

### 👍 Expected behavior

When running a `docker image build -t backstage .`, I should successfully have an image I can run as a containerized application. I should not need the sqlite3 dependencies in the dockerfile since there are none in the package.json files. 

### 👎 Actual Behavior with Screenshots

Here is the error from building the docker image: 
```
#0 178.5 error /app/node_modules/isolated-vm: Command failed.
#0 178.5 Exit code: 1
#0 178.5 Command: node-gyp rebuild --release -j 4
#0 178.5 Arguments:
#0 178.5 Directory: /app/node_modules/isolated-vm
#0 178.5 Output:
#0 178.5 gyp info it worked if it ends with ok
#0 178.5 gyp info using node-gyp@9.3.0
#0 178.5 gyp info using node@16.18.0 | linux | arm64
#0 178.5 gyp ERR! find Python
#0 178.5 gyp ERR! find Python Python is not set from command line or npm configuration
#0 178.5 gyp ERR! find Python Python is not set from environment variable PYTHON
#0 178.5 gyp ERR! find Python checking if "python3" can be used
#0 178.5 gyp ERR! find Python - "python3" is not in PATH or produced an error
#0 178.5 gyp ERR! find Python checking if "python" can be used
#0 178.5 gyp ERR! find Python - "python" is not in PATH or produced an error
#0 178.5 gyp ERR! find Python
#0 178.5 gyp ERR! find Python **********************************************************
#0 178.5 gyp ERR! find Python You need to install the latest version of Python.
#0 178.5 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#0 178.5 gyp ERR! find Python you can try one of the following options:
#0 178.5 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#0 178.5 gyp ERR! find Python   (accepted by both node-gyp and npm)
#0 178.5 gyp ERR! find Python - Set the environment variable PYTHON
#0 178.5 gyp ERR! find Python - Set the npm configuration variable python:
#0 178.5 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#0 178.5 gyp ERR! find Python For more information consult the documentation at:
#0 178.5 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#0 178.5 gyp ERR! find Python **********************************************************
#0 178.5 gyp ERR! find Python
#0 178.5 gyp ERR! configure error
#0 178.5 gyp ERR! stack Error: Could not find any Python installation to use
#0 178.5 gyp ERR! stack     at PythonFinder.fail (/app/node_modules/node-gyp/lib/find-python.js:330:47)
#0 178.5 gyp ERR! stack     at PythonFinder.runChecks (/app/node_modules/node-gyp/lib/find-python.js:159:21)
#0 178.5 gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/find-python.js:202:16)
#0 178.5 gyp ERR! stack     at PythonFinder.execFileCallback (/app/node_modules/node-gyp/lib/find-python.js:294:16)
#0 178.5 gyp ERR! stack     at exithandler (node:child_process:410:5)
#0 178.5 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:422:5)
#0 178.5 gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#0 178.5 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#0 178.5 gyp ERR! stack     at onErrorNT (node:internal/child_process:485:16)
#0 178.5 gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#0 178.5 gyp ERR! System Linux 5.15.96-0-virt
#0 178.5 gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-gyp" "rebuild" "--release" "-j" "4"
#0 178.5 gyp ERR! cwd /app/node_modules/isolated-vm
#0 178.5 gyp ERR! node -v v16.18.0
#0 178.5 gyp ERR! node-gyp -v v9.3.0
#0 178.5 gyp ERR! not ok
#0 178.5 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#0 178.5 warning Error running install script for optional dependency: "/app/node_modules/cpu-features: Command failed.
#0 178.5 Exit code: 1
#0 178.5 Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
#0 178.5 Arguments:
#0 178.5 Directory: /app/node_modules/cpu-features
#0 178.5 Output:
#0 178.5 /app/node_modules/buildcheck/lib/index.js:115
#0 178.5   throw new Error('Unable to detect compiler type');
#0 178.5   ^
#0 178.5
#0 178.5 Error: Unable to detect compiler type
#0 178.5     at BuildEnvironment.getKind (/app/node_modules/buildcheck/lib/index.js:115:9)
#0 178.5     at BuildEnvironment.tryCompile (/app/node_modules/buildcheck/lib/index.js:537:15)
#0 178.5     at BuildEnvironment.checkHeader (/app/node_modules/buildcheck/lib/index.js:423:25)
#0 178.5     at Object.<anonymous> (/app/node_modules/cpu-features/buildcheck.js:16:4)
#0 178.5     at Module._compile (node:internal/modules/cjs/loader:1155:14)
#0 178.5     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
#0 178.5     at Module.load (node:internal/modules/cjs/loader:1033:32)
#0 178.5     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
#0 178.5     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
#0 178.5     at node:internal/main/run_main_module:22:47"
#0 178.5 info This module is OPTIONAL, you can safely ignore this error
------
ERROR: failed to solve: executor failed running [/bin/sh -c yarn install --frozen-lockfile --network-timeout 600000]: exit code: 1
```
Then a successful build when running with the sqlite3 dependencies.

### 👟 Reproduction steps

Here is the dockerfile I am using: 
```
# Stage 1 - Create yarn install skeleton layer
FROM node:16-bullseye-slim AS packages

WORKDIR /app
COPY package.json yarn.lock ./

COPY packages packages

# Comment this out if you don't have any internal plugins
COPY plugins plugins

RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -exec rm -rf {} \+

# Stage 2 - Install dependencies and build packages
FROM node:16-bullseye-slim AS build


# RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
#     --mount=type=cache,target=/var/lib/apt,sharing=locked \
#     apt-get update && \
#     apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential && \
#     yarn config set python /usr/bin/python3

USER node
WORKDIR /app

COPY --from=packages --chown=node:node /app .

# Stop cypress from downloading it's massive binary.
ENV CYPRESS_INSTALL_BINARY=0
RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --network-timeout 600000

COPY --chown=node:node . .

RUN yarn tsc
RUN yarn --cwd packages/backend build

RUN mkdir packages/backend/dist/skeleton packages/backend/dist/bundle \
    && tar xzf packages/backend/dist/skeleton.tar.gz -C packages/backend/dist/skeleton \
    && tar xzf packages/backend/dist/bundle.tar.gz -C packages/backend/dist/bundle

# Stage 3 - Build the actual backend image and install production dependencies
FROM node:16-bullseye-slim

# Install sqlite3 dependencies. You can skip this if you don't use sqlite3 in the image,
# in which case you should also move better-sqlite3 to "devDependencies" in package.json.
# RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
#     --mount=type=cache,target=/var/lib/apt,sharing=locked \
#     apt-get update && \
#     apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential && \
#     yarn config set python /usr/bin/python3

# From here on we use the least-privileged `node` user to run the backend.
USER node

# This should create the app dir as `node`.
# If it is instead created as `root` then the `tar` command below will fail: `can't create directory 'packages/': Permission denied`.
# If this occurs, then ensure BuildKit is enabled (`DOCKER_BUILDKIT=1`) so the app dir is correctly created as `node`.
WORKDIR /app

# Copy the install dependencies from the build stage and context
COPY --from=build --chown=node:node /app/yarn.lock /app/package.json /app/packages/backend/dist/skeleton/ ./

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --production --network-timeout 600000

# Copy the built packages from the build stage
COPY --from=build --chown=node:node /app/packages/backend/dist/bundle/ ./

# Copy any other files that we need at runtime
COPY --chown=node:node app-config.yaml ./

# This switches many Node.js dependencies to production mode.
ENV NODE_ENV production

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```
With this in the root directory run a `docker image build -t backstage .` And see the python type is missing.

### 📃 Provide the context for the Bug.

I am wondering if I need the sqlite3 dependencies in the Dockerfile or if I should install python3 seperately so I can avoid all of the sqlite3 dependencies that get installed in the container.

### 🖥️ Your Environment

```
OS:   Darwin 21.5.0 - darwin/arm64
node: v16.20.0
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.16.0

Dependencies:
  @backstage/app-defaults                          1.4.1
  @backstage/backend-app-api                       0.4.5
  @backstage/backend-common                        0.15.2, 0.18.5, 0.19.1
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.4
  @backstage/backend-tasks                         0.5.4
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.2
  @backstage/cli                                   0.22.9
  @backstage/config-loader                         1.3.2
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.9.0
  @backstage/core-components                       0.12.5, 0.13.3
  @backstage/core-plugin-api                       1.5.3
  @backstage/dev-utils                             1.0.17
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.15
  @backstage/integration                           1.5.1
  @backstage/plugin-api-docs                       0.9.6
  @backstage/plugin-app-backend                    0.3.47
  @backstage/plugin-auth-backend                   0.18.5
  @backstage/plugin-auth-node                      0.2.16
  @backstage/plugin-azure-devops-backend           0.3.26
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.3.2
  @backstage/plugin-catalog-backend-module-azure   0.1.18
  @backstage/plugin-catalog-backend-module-msgraph 0.5.6
  @backstage/plugin-catalog-backend                1.11.0
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.32
  @backstage/plugin-catalog-import                 0.9.10
  @backstage/plugin-catalog-node                   1.4.0
  @backstage/plugin-catalog-react                  1.8.0
  @backstage/plugin-catalog                        1.12.0
  @backstage/plugin-cost-insights-common           0.1.1
  @backstage/plugin-cost-insights                  0.12.9
  @backstage/plugin-events-node                    0.2.8
  @backstage/plugin-explore-backend                0.0.9
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.30
  @backstage/plugin-explore                        0.4.6
  @backstage/plugin-gcalendar                      0.3.16
  @backstage/plugin-github-actions                 0.6.1
  @backstage/plugin-graphiql                       0.2.52
  @backstage/plugin-home-react                     0.1.1
  @backstage/plugin-home                           0.5.4
  @backstage/plugin-kubernetes-backend             0.11.2
  @backstage/plugin-kubernetes-common              0.6.5
  @backstage/plugin-kubernetes                     0.9.3
  @backstage/plugin-microsoft-calendar             0.1.5
  @backstage/plugin-org                            0.6.10
  @backstage/plugin-permission-backend             0.5.22
  @backstage/plugin-permission-common              0.7.7
  @backstage/plugin-permission-node                0.7.10
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.2.41
  @backstage/plugin-scaffolder-backend             1.15.1
  @backstage/plugin-scaffolder-common              1.3.2
  @backstage/plugin-scaffolder-node                0.1.5
  @backstage/plugin-scaffolder-react               1.5.1
  @backstage/plugin-scaffolder                     1.14.1
  @backstage/plugin-search-backend-module-catalog  0.1.3
  @backstage/plugin-search-backend-module-explore  0.1.3
  @backstage/plugin-search-backend-module-pg       0.5.8
  @backstage/plugin-search-backend-module-techdocs 0.1.3
  @backstage/plugin-search-backend-node            1.2.3
  @backstage/plugin-search-backend                 1.3.3
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.3
  @backstage/plugin-search                         1.3.3
  @backstage/plugin-tech-radar                     0.6.6
  @backstage/plugin-techdocs-backend               1.6.4
  @backstage/plugin-techdocs-module-addons-contrib 1.0.15
  @backstage/plugin-techdocs-node                  1.7.3
  @backstage/plugin-techdocs-react                 1.1.8
  @backstage/plugin-techdocs                       1.6.5
  @backstage/plugin-user-settings                  0.7.5
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.1
  @backstage/theme                                 0.2.19, 0.4.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
  ```
  

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by gsasanelli** [comment]
Hi i think that the problem is that you are not removing only sqlite:
so instead removing the entire section:
`
# RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
#     --mount=type=cache,target=/var/lib/apt,sharing=locked \
#     apt-get update && \
#     apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential && \
#     yarn config set python /usr/bin/python3
`
just remove libsqlite3-dev:
`
 RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
     --mount=type=cache,target=/var/lib/apt,sharing=locked \
     apt-get update && \
     apt-get install -y --no-install-recommends python3 build-essential && \
     yarn config set python /usr/bin/python3
`
This because python (and build-essential libs) are required from other node library (for example isolated-vm)
