### ISSUE TITLE
🐛 Bug Report: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full | Happens during app startup

### ISSUE THREAD

**Issue by s-sathish** [backstage/backstage#19863]
### 📜 Description

During app startup, we occasionally run into this issue -
```
Failed to connect to the database to make sure that '${DATABASE}' exists, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? 
```
It is not specific to one database, it happens with all plugin databases. And this happens only at app startup. Haven't got this post startup.
We even tried overriding the knex default pool config (handled by tarn internally). Ex. - (default max is 10, increased it to 15)
```
    knexConfig:
      pool:
        min: 2
        max: 15
        acquireTimeoutMillis: 30000
        createTimeoutMillis: 30000
        destroyTimeoutMillis: 5000
        idleTimeoutMillis: 30000
        reapIntervalMillis: 1000
        createRetryIntervalMillis: 200
        propagateCreateError: false
```
But still ended up with the same error.
Possibly a connection leak somewhere / some flow has taken connection from the pool and not returned it back ?

### 👍 Expected behavior

App should start normally without KnexTimeoutError

### 👎 Actual Behavior with Screenshots

It actually fails with following error -
```
Failed to connect to the database to make sure that '${DATABASE}' exists, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? 
```

### 👟 Reproduction steps

It's not reproducible consistently as it happens only during app startup for us. And it doesn't happen during every startup.

### 📃 Provide the context for the Bug.

Complete DB config -
```
database:
  client: pg
  connection:
    host: ${POSTGRES_HOST}
    port: 5432
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  prefix: ${DB_PREFIX}
  knexConfig:
    pool:
      min: 2
      max: 15
      acquireTimeoutMillis: 30000
      createTimeoutMillis: 30000
      destroyTimeoutMillis: 5000
      idleTimeoutMillis: 30000
      reapIntervalMillis: 1000
      createRetryIntervalMillis: 200
      propagateCreateError: false
```

catalog has close to 100 entities. And for most of the time, catalog & search plugin usually hovers around the max of 15 connections. Does multiple backend tasks / some pooling tasks keep it all busy ?

### 🖥️ Your Environment
```
OS: Debian GNU/Linux 11 (bullseye)
node: v16.20.2
yarn: 3.2.3
cli:  0.22.7 (installed)
backstage:  1.16.0

Dependencies:
  @backstage/app-defaults                          1.4.1
  @backstage/backend-app-api                       0.4.5
  @backstage/backend-common                        0.19.1
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.4
  @backstage/backend-tasks                         0.5.4
  @backstage/catalog-client                        1.4.1, 1.4.0, 1.4.2, 1.4.3
  @backstage/catalog-model                         1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/config-loader                         1.3.1, 1.3.0, 1.3.2
  @backstage/config                                1.0.7, 1.0.6, 1.0.8
  @backstage/core-app-api                          1.9.0
  @backstage/core-components                       0.12.4, 0.11.2, 0.12.5, 0.13.2, 0.13.3
  @backstage/core-plugin-api                       1.0.6, 1.5.0, 1.5.1, 1.4.0, 1.5.2, 1.5.3
  @backstage/dev-utils                             1.0.17
  @backstage/errors                                1.1.5, 1.1.4, 1.2.0, 1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.11, 1.1.15
  @backstage/integration                           1.4.4, 1.4.3, 1.5.0, 1.5.1
  @backstage/plugin-api-docs                       0.9.6
  @backstage/plugin-app-backend                    0.3.47
  @backstage/plugin-auth-backend                   0.18.5
  @backstage/plugin-auth-node                      0.2.16
  @backstage/plugin-catalog-backend-module-github  0.3.2
  @backstage/plugin-catalog-backend                1.11.0
  @backstage/plugin-catalog-common                 1.0.12, 1.0.14, 1.0.15, 1.0.13
  @backstage/plugin-catalog-graph                  0.2.32
  @backstage/plugin-catalog-import                 0.9.10
  @backstage/plugin-catalog-node                   1.4.0
  @backstage/plugin-catalog-react                  1.2.1, 1.4.0, 1.7.0, 1.8.0
  @backstage/plugin-catalog                        1.12.0
  @backstage/plugin-circleci                       0.3.20
  @backstage/plugin-events-node                    0.2.8
  @backstage/plugin-firehydrant                    0.2.4
  @backstage/plugin-github-actions                 0.6.1
  @backstage/plugin-github-pull-requests-board     0.1.14
  @backstage/plugin-home-react                     0.1.1
  @backstage/plugin-home                           0.4.32, 0.5.4
  @backstage/plugin-jenkins-backend                0.2.2
  @backstage/plugin-jenkins-common                 0.1.17
  @backstage/plugin-jenkins                        0.8.2
  @backstage/plugin-kubernetes-backend             0.11.2
  @backstage/plugin-kubernetes-common              0.6.5
  @backstage/plugin-kubernetes                     0.9.3
  @backstage/plugin-org                            0.6.10
  @backstage/plugin-pagerduty                      0.6.1
  @backstage/plugin-permission-backend             0.5.22
  @backstage/plugin-permission-common              0.7.5, 0.7.4, 0.7.6, 0.7.7
  @backstage/plugin-permission-node                0.7.10
  @backstage/plugin-permission-react               0.4.11, 0.4.13, 0.4.14, 0.4.12
  @backstage/plugin-proxy-backend                  0.2.41
  @backstage/plugin-scaffolder-backend             1.15.1
  @backstage/plugin-scaffolder-common              1.3.2
  @backstage/plugin-scaffolder-node                0.1.5
  @backstage/plugin-scaffolder-react               1.5.1
  @backstage/plugin-scaffolder                     1.14.1
  @backstage/plugin-search-backend-module-catalog  0.1.3
  @backstage/plugin-search-backend-module-pg       0.5.8
  @backstage/plugin-search-backend-module-techdocs 0.1.3
  @backstage/plugin-search-backend-node            1.2.3
  @backstage/plugin-search-backend                 1.3.3
  @backstage/plugin-search-common                  1.2.5, 1.2.2, 1.2.3, 1.2.4
  @backstage/plugin-search-react                   1.6.3
  @backstage/plugin-search                         1.3.3
  @backstage/plugin-techdocs-backend               1.6.4
  @backstage/plugin-techdocs-module-addons-contrib 1.0.15
  @backstage/plugin-techdocs-node                  1.7.3
  @backstage/plugin-techdocs-react                 1.1.8
  @backstage/plugin-techdocs                       1.6.5
  @backstage/plugin-todo-backend                   0.1.44
  @backstage/plugin-todo                           0.2.22
  @backstage/plugin-user-settings                  0.7.5
  @backstage/release-manifests                     0.0.8, 0.0.9
  @backstage/test-utils                            1.4.1
  @backstage/theme                                 0.2.18, 0.2.17, 0.4.0, 0.4.1
  @backstage/types                                 1.0.2, 1.1.0
  @backstage/version-bridge                        1.0.3, 1.0.4
```
### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
Sorry to hear that you're having issues.
I'm does this error appear after 30 seconds given the `createTimeoutMillis: 30000`? Is there possibly a full stacktrace of this error as well?

**Comment by s-sathish** [comment]
@jhaals Yes. It happens after 30 seconds as per createTimeoutMillis. But the thing is this happens only at app startup. Post that things work fine till the next restart.

Sample stack traces -
```
Error: Failed to connect to the database to make sure that '{DB_PREFIX}_catalog' exists, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /app/node_modules/@backstage/backend-common/dist/index.cjs.js:973:17
    at async CatalogBuilder.build (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-21da853f.cjs.js:4940:22)
    at async createPlugin$a (/app/packages/backend/dist/index.cjs.js:258:40)
    at async main (/app/packages/backend/dist/index.cjs.js:1015:5)"

Unhandled Rejection: Error: Failed to connect to the database to make sure that '{DB_PREFIX}_search' exists, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /app/node_modules/@backstage/backend-common/dist/index.cjs.js:973:17
    at async PluginTaskSchedulerImpl.<anonymous> (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:659:20)"

KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/app/node_modules/@backstage/backend-common/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/app/node_modules/@backstage/backend-common/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/@backstage/backend-common/node_modules/knex/lib/execution/runner.js:30:19)
    at async listCompleted (/app/node_modules/@backstage/backend-common/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:12:3)
    at async Promise.all (index 1)
    at async Migrator.latest (/app/node_modules/@backstage/backend-common/node_modules/knex/lib/migrations/migrate/Migrator.js:63:29)
    at async Function.runMigrations (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:3847:5)
    at async /app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:3856:9
    at async Function.fromConfig (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:3606:35)
    at async Object.createRouter (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:3882:20)
    at async createPlugin$b (/app/packages/backend/dist/index.cjs.js:158:10)
    at async main (/app/packages/backend/dist/index.cjs.js:1008:26) {
```
P.S - Have replace the actual db prefix with placeholder

**Comment by freben** [comment]
What is your database instance like? Could it be that it's under-powered such that DDL operations take excessive amounts of resources so that things stack up? We recommend not slimming down the database host too much, especially not where the catalog is connected.

I'll look into that unhandled rejection error, that does look potentially unexpected.

**Comment by s-sathish** [comment]
@freben We use GCP Cloud SQL instance for Postgres. Instance size is good enough, we don't see anything abnormal in the instance stats / metrics when this error happens.

**Comment by taras** [comment]
We're seeing similar problems on Google Cloud SQL. I'm unsure if it's the same, but we've had to experiment with config because we got failed deployments due to a full connection pool - we get 50 connections. The catalog keeps 26 connections with many of them being idle.

## catalog makes 26 connections
![image](https://github.com/backstage/backstage/assets/74687/d34a8dfe-a204-4a7b-8cd0-51130641bd8f)

## 36 idle connections
![36 idle connections](https://github.com/backstage/backstage/assets/74687/52aa7d37-5b86-489f-95b0-2e1667baacd3)

**Comment by jlucktay** [comment]
We use Postgres on Google Cloud SQL as well, and are seeing a similar crash not long after the app starts:

```
ForwardedError: Module 'postgres-engine' for plugin 'search' startup failed; caused by Error: Failed to connect to the database to make sure that 'backstage_plugin_search' exists, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1781:21
    at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1780:13
    ... 8 lines matching cause stack trace ...
    at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1881:5) {
  cause: Error: Failed to connect to the database to make sure that 'backstage_plugin_search' exists, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
      at /app/node_modules/@backstage/backend-common/dist/index.cjs.js:1504:17
      at async DatabaseDocumentStore.create (/app/node_modules/@backstage/plugin-search-backend-module-pg/dist/cjs/PgSearchEngine-7d93bdd7.cjs.js:28:18)
      at async PgSearchEngine.fromConfig (/app/node_modules/@backstage/plugin-search-backend-module-pg/dist/cjs/PgSearchEngine-7d93bdd7.cjs.js:260:7)
      at async Object.init [as func] (/app/node_modules/@backstage/plugin-search-backend-module-pg/dist/alpha.cjs.js:24:11)
      at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1780:13
      at async processNode (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1302:22)
      at async Promise.all (index 0)
      at async processMoreNodes (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1297:7)
      at async _DependencyGraph.parallelTopologicalTraversal (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1308:5)
      at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1777:9
      at async Promise.all (index 14)
      at async BackendInitializer.doStart_fn (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1757:3)
      at async BackendInitializer.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1611:5)
      at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1881:5)
}
```

It's running inside a Debian 12 (bookworm) container on GKE.

<details>
<summary>yarn backstage-cli info</summary>

```
node: v20.9.0
yarn: 4.1.0
cli:  0.25.2 (installed)
backstage:  1.23.3

Dependencies:
  @backstage/app-defaults                                          1.5.0
  @backstage/backend-app-api                                       0.5.14, 0.6.2
  @backstage/backend-common                                        0.19.10, 0.20.2, 0.21.6
  @backstage/backend-defaults                                      0.2.13
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.6
  @backstage/backend-plugin-api                                    0.5.4, 0.6.16
  @backstage/backend-tasks                                         0.5.21
  @backstage/backend-test-utils                                    0.3.3
  @backstage/catalog-client                                        1.6.3
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.0
  @backstage/core-compat-api                                       0.2.0
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.0
  @backstage/core-plugin-api                                       1.9.0
  @backstage/dev-utils                                             1.0.27
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.5
  @backstage/frontend-plugin-api                                   0.6.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.24
  @backstage/integration                                           1.9.1
  @backstage/plugin-api-docs                                       0.11.0
  @backstage/plugin-app-backend                                    0.3.61
  @backstage/plugin-app-node                                       0.1.13
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.8
  @backstage/plugin-auth-backend-module-github-provider            0.1.10
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.10
  @backstage/plugin-auth-backend-module-google-provider            0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.8
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.10
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.6
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.6
  @backstage/plugin-auth-backend                                   0.21.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.11
  @backstage/plugin-bazaar-backend                                 0.3.11
  @backstage/plugin-bazaar                                         0.2.22
  @backstage/plugin-catalog-backend-module-github                  0.5.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.10
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.10
  @backstage/plugin-catalog-backend                                1.17.3
  @backstage/plugin-catalog-common                                 1.0.21
  @backstage/plugin-catalog-graph                                  0.4.0
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.7.3
  @backstage/plugin-catalog-react                                  1.10.0
  @backstage/plugin-catalog-unprocessed-entities                   0.1.8
  @backstage/plugin-catalog                                        1.17.0
  @backstage/plugin-circleci                                       0.3.30
  @backstage/plugin-devtools-backend                               0.2.10
  @backstage/plugin-devtools-common                                0.1.8
  @backstage/plugin-devtools                                       0.1.9
  @backstage/plugin-entity-feedback-backend                        0.2.10
  @backstage/plugin-entity-feedback-common                         0.1.3
  @backstage/plugin-entity-feedback                                0.2.13
  @backstage/plugin-events-node                                    0.2.22
  @backstage/plugin-explore-backend                                0.0.22
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.36
  @backstage/plugin-explore                                        0.4.16
  @backstage/plugin-github-actions                                 0.6.11
  @backstage/plugin-github-issues                                  0.2.19
  @backstage/plugin-github-pull-requests-board                     0.1.24
  @backstage/plugin-home-react                                     0.1.8
  @backstage/plugin-home                                           0.6.2
  @backstage/plugin-kubernetes-common                              0.7.4
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.11
  @backstage/plugin-permission-backend                             0.5.36
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.27
  @backstage/plugin-permission-react                               0.4.20
  @backstage/plugin-proxy-backend                                  0.4.11
  @backstage/plugin-scaffolder-backend-module-azure                0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.3
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.3
  @backstage/plugin-scaffolder-backend-module-github               0.2.4
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.16
  @backstage/plugin-scaffolder-backend                             1.21.3
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.1.5, 0.2.10, 0.3.3, 0.4.0
  @backstage/plugin-scaffolder-react                               1.8.0
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.17
  @backstage/plugin-search-backend-module-explore                  0.1.17
  @backstage/plugin-search-backend-module-pg                       0.5.22
  @backstage/plugin-search-backend-module-techdocs                 0.1.17
  @backstage/plugin-search-backend-node                            1.2.17
  @backstage/plugin-search-backend                                 1.5.3
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-tech-radar                                     0.6.13
  @backstage/plugin-techdocs-backend                               1.9.6
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.5
  @backstage/plugin-techdocs-node                                  1.11.5
  @backstage/plugin-techdocs-react                                 1.1.16
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.3
  @backstage/test-utils                                            1.5.0
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.1
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

</details>

**Comment by jlucktay** [comment]
Similar to [the charts posted above by taras](https://github.com/backstage/backstage/issues/19863#issuecomment-1904534859), we have even fewer connections, and most of them sitting idle:

![image](https://github.com/backstage/backstage/assets/460028/5b853982-3fed-41ee-8726-b0137f1be5a0)

I have tried enlarging the pool with these two environment variables on the GKE container:

```yaml
            - name: APP_CONFIG_backend_database_knexConfig_pool_min
              value: '0'
            - name: APP_CONFIG_backend_database_knexConfig_pool_max
              value: '200'
```

This helped for a few restarts, but then a few hours later it fell back to the old behaviour.
Back to throwing the `ForwardedError: Module 'postgres-engine' for plugin 'search' startup failed ...` error above not long after the app starts.

**Comment by freben** [comment]
The code that ensures the creation of the databases is special. It doesn't use the regular connection config fully, since it needs to connect to the `postgres` database in the pg case etc. The pg code specifically [creates an entirely new connection pool for this purpose](https://github.com/backstage/backstage/blob/3b4eae38ad72837dffbce2a00bd703d3e93ac7aa/packages/backend-common/src/database/connectors/postgres.ts#L125).

**Comment by ingestevezaquino** [comment]
I'm receiving same exception when trying to connect backstage to a fresh PostgreDB installation.

**Comment by taras** [comment]
One of our clients asked us to figure this out. I gathered some notes from @freben, so I'll copy them here for posterity and others to access.

1. The refactor in #24545 was done to isolate each provider more cleanly. It's expected to make it more straightforward how to interact with each provider in isolation. For example, if we wanted to create an "admin" connection pool differently for a specific provider, that should be possible.
2. It's been observed that sometimes it starts happening for every provider at once, which suggests that it's a lower-level, systematic problem deeper down. 
3. In previous GitHub, Issues in the Knex project suggest that it could be a combination of Node/pg drivers that causes this problem. #24590 also suggests that these problems come from lower down in the stack.
4. While refactoring #24545, @freben noticed that [`this retry loop`](https://github.com/backstage/backstage/blob/66fb7275c9835a176b7fedf20da6d69bbd138d59/packages/backend-common/src/database/connectors/postgres.ts#L164) does NOT try to do the pool creation itself over and over, but it probably should. 
5. It might be worth trying to move [admin client creation](https://github.com/backstage/backstage/blob/66fb7275c9835a176b7fedf20da6d69bbd138d59/packages/backend-common/src/database/connectors/postgres.ts#L134) into the loop as well.

**Comment by freben** [comment]
@taras Did you find some time to poke at this?

**Comment by Koshiz** [comment]
Any solution for this issue? tried this [](https://stackoverflow.com/questions/40435315/knex-timeout-acquiring-a-connection-the-pool-is-probably-full-are-you-missing ) but got no luck

**Comment by benjidotsh** [comment]
@Koshiz our temporary solution that worked is scaling up the database to allow for more connections

**Comment by Koshiz** [comment]
![2024-07-22 18_59_32-Window](https://github.com/user-attachments/assets/4d6677a8-1ad6-4d5d-9bc5-626cdbbc380e)
@benjidotsh I have scaled the postgresql like this but the error is sitll there. I've connected successfully with my local postgresql instance but not with this.

**Comment by benjidotsh** [comment]
@Koshiz I'm not too familiar with Azure I think that is? But in AWS that did the trick for us. Maybe in Azure there is another way to increase the amount of database connections?

**Comment by adminy** [comment]
I'm experiencing this locally on a pretty big machine. There is more to this than meets the eye.

**Comment by acierto** [comment]
We configured Postgres itself (not via Knex configuration) to have 2000 connections. No problems after that.

**Comment by MTJ-GH** [comment]
Also facing this issue in Google Cloud, with Backstage hosted on Cloud Run connecting to PostgreSQL.

**Comment by camilaibs** [comment]
Hi @MTJ-GH, we are open to suggestions on what metrics to collect. If you have any insights, please let us know 🙏🏻 .

**Comment by benjdlambert** [comment]
I wonder we should ship tighter constraints here.

`min: 0, max: 1` for all plugins by default, and then maybe `max: 4` for the catalog or something out of the box and see if that helps us?

**Comment by mjramer** [comment]
Currently running into this issue on a new azure postgres instance with very little traffic on our Backstage deployment and max_connections = 859

**Comment by Silthus** [comment]
We just ran into the exact same issue where the `catalog` plugin exhausts almost all of our 50 available knex pool connections and then causes a full failure and timeouts of the backend.
We also use Google Cloud Run Services together with CloudSQL and PostgresSQL on GCP.

The `max_connections` of our database is set to `4096` and the knex pool configured with `min: 0` and `max: 50`.

<img width="1802" height="1242" alt="Image" src="https://github.com/user-attachments/assets/ad479912-c52d-4f69-ab44-e85c36c5180b" />

First I wanted to increase the default knex pool max limit to `1` for all plugins and then overriding it for the catalog to `20`, but I found myself in a time machine and came across [this related issue](https://github.com/backstage/backstage/issues/30412#issuecomment-3034342354), which explicitly states that if in `pluginDivisionMode: schema` you cannot fine tune the per plugin connection pool limits.

Edit: ~~So I am going with `max: 5` and hope that fixes it for now.~~
That made it worse. Now increased to `max: 100` and it is working.

---

One thing to note, which I am not sure if it is related, is that we have setup Github and the Catalog Events plugin module to do event driven catalog processing. As we have quite a few repositories the backend is under constant fire of Github Push events running in a constant processing loop of entities. Even though none of them really change that often. Could it be that there is a bug in the detection of what entities need processing deeper in the catalog, when using the events setup?

**Comment by Silthus** [comment]
I want to give another update here what we found out to be the actual root cause of the pool exhaustion in the catalog plugin.

After digging deep I found that we had one custom Entity Processor that was taking a very long time (>20s) and was running on every component kind entity. Together with the event driven entity updates this somehow caused the catalog plugin that calls the processors to open up transaction handles and leave them open until the actual processor returned. Combined with a long pool reconciliation timeout it caused the pool to exhaust and connections to fail.

To debug this if you are facing the same issue you can take the following steps:
1. Filter and group traces using the `backstage.catalog.processor.name` attribute, sorting them by time.
2. Make sure you have debug logging enabled and set `backend.database.knexConfig.pool.propagateCreateError: true` (without this the actual pool exhaustion messages will not appear as errors)

---

To the maintainers of the catalog: could it be that there are open handles to the database when delegating to the potentially unsafe processing steps, thus causing this issue?

**Comment by freben** [comment]
In general, catalog nodes have a lot of stuff going on. At absolute peak, up to 10 concurrent processing runs, and 5 concurrent stitcher runs are ongoing at any one instant.

Everything that's doing work is receiving the same central connection pool. What they do with it varies. The processing and stitching workers are in and of themselves very fast per-entity (shouldn't be holding on to connections for long). But like you say, if the processor also uses the connection pool, it adds up. We do not hold anything explicitly _during_ the process of calling into provided processors though. For example, it is not the case that there's a transaction surrounding the read-process-write steps of a processing run.

A catalog that stays at that peak all the time is unhealthy though. Ideally, as our instance does, it processes an entity here and there at just background noise levels (a few per second at most or so), and there's no queue whatsoever except right when a big ingestion with lots of changes happened for example. Your slow processor most likely made your processing queue be perpetually full and it fighting for its life to work it down slower than the arrival rate was of new work.

An ideal processor completes its work in microseconds, or doesn't exist at all and is folded into upfront provider work instead where possible :)
