### ISSUE TITLE
🚀 Feature: Pin workspace dependencies

### ISSUE THREAD

**Issue by schultzp2020** [backstage/backstage#19908]
### 🔖 Feature description

Pin workspace dependencies using `workspace:*`.

### 🎤 Context

There are four different ways to [cross-reference](https://yarnpkg.com/features/workspaces#cross-references) packages in a yarn workspace monorepo. 

e.g. `version` field is set to `3.2.1`

| Initial range | Range after publish |
| -------- | ------- |
| `workspace:^3.0.0`  | `^3.0.0` |
| `workspace:^`  | `^3.2.1` |
| `workspace:~`  | `~3.2.1` |
| `workspace:*`  | `=3.2.1` |

Currently, transitive dependencies are very likely to overwrite a dependencies specified version which causes backstage to complain. By switching to `workspace:*` this would make it easier for platform engineers to maintain an older version of backstage without requiring them to update it to the latest version or resolve dependencies manually. Both of which are not very feasible in the long term.

### ✌️ Possible Implementation

Find and replace [all](https://github.com/search?q=repo%3Abackstage%2Fbackstage%20workspace%3A%5E&type=code) `workspace:^` with `workspace:*`.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
> Currently, transitive dependencies are very likely to overwrite a dependencies specified version which causes backstage to complain.

What does this complaint look like? Should we perhaps fix that instead?

Regarding switching to fixed version ranges, I summarized my thoughts on that over [here](https://github.com/backstage/backstage/issues/18881#issuecomment-1704958820)

**Comment by schultzp2020** [comment]
@Rugvip 

> What does this complaint look like? Should we perhaps fix that instead?

Steps to reproduce.

1. Checkout this [branch](https://github.com/janus-idp/backstage-showcase/tree/demo-dep-issue) using backstage 1.16.0.
2. Run `yarn install`
3. Run `yarn run start`

```console
backend:start: C:\Programming\Work\backstage-showcase\packages\backend\dist\main.js:554
backend:start: /******/                         throw e;
backend:start:                                  ^
backend:start: 
backend:start: TypeError: Cannot read properties of undefined (reading 'redacter')
backend:start:     at Object.<anonymous> (C:\Programming\Work\backstage-showcase\node_modules\@roadiehq\scaffolder-backend-module-utils\node_modules\@backstage\backend-app-api\node_modules\@backstage\backend-common\dist\index.cjs.js:110:46)
backend:start:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
backend:start:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
backend:start:     at Module.load (node:internal/modules/cjs/loader:1119:32)
backend:start:     at Module._load (node:internal/modules/cjs/loader:960:12)
backend:start:     at Module.require (node:internal/modules/cjs/loader:1143:19)
backend:start:     at require (node:internal/modules/cjs/helpers:110:18)
backend:start:     at Object.<anonymous> (C:\Programming\Work\backstage-showcase\node_modules\@roadiehq\scaffolder-backend-module-utils\node_modules\@backstage\backend-app-api\dist\index.cjs.js:25:21)
backend:start:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
backend:start:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
backend:start:     at Module.load (node:internal/modules/cjs/loader:1119:32)
backend:start:     at Module._load (node:internal/modules/cjs/loader:960:12)
backend:start:     at Module.require (node:internal/modules/cjs/loader:1143:19)
backend:start:     at require (node:internal/modules/cjs/helpers:110:18)
backend:start:     at Object.<anonymous> (C:\Programming\Work\backstage-showcase\node_modules\@roadiehq\scaffolder-backend-module-utils\node_modules\@backstage\plugin-scaffolder-backend\node_modules\@backstage\backend-common\dist\index.cjs.js:10:21)
backend:start:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
backend:start: 
backend:start: Node.js v18.16.1
```

This error is caused by having a newer transitive dependency `@backstage/backend-common@1.19.4` than the version specified under dependencies `@backstage/backend-common@1.19.1`. 

```console
$ yarn list --pattern @backstage/backend-common
yarn list v1.22.19
├─ @backstage/backend-common@0.19.1
├─ @immobiliarelabs/backstage-plugin-gitlab-backend@5.0.2
│  └─ @backstage/backend-common@0.18.5
├─ @janus-idp/backstage-plugin-keycloak-backend@1.3.10
│  └─ @backstage/backend-common@0.18.5
├─ @janus-idp/backstage-plugin-ocm-backend@3.0.3
│  └─ @backstage/backend-common@0.18.5
└─ @roadiehq/scaffolder-backend-module-utils@1.10.1
   ├─ @backstage/backend-app-api@0.5.2
   │  └─ @backstage/backend-common@0.19.4
   ├─ @backstage/backend-tasks@0.5.7
   │  └─ @backstage/backend-common@0.19.4
   ├─ @backstage/plugin-auth-node@0.2.19
   │  └─ @backstage/backend-common@0.19.4
   ├─ @backstage/plugin-catalog-backend@1.12.4
   │  └─ @backstage/backend-common@0.19.4
   ├─ @backstage/plugin-permission-node@0.7.13
   │  └─ @backstage/backend-common@0.19.4
   ├─ @backstage/plugin-scaffolder-backend@1.16.5
   │  └─ @backstage/backend-common@0.19.4
   ├─ @backstage/plugin-search-backend-module-catalog@0.1.6
   │  └─ @backstage/backend-common@0.19.4
   └─ @backstage/plugin-search-backend-node@1.2.6
      └─ @backstage/backend-common@0.19.4
Done in 1.34s.
```

> Regarding switching to fixed version ranges, I summarized my thoughts on that over https://github.com/backstage/backstage/issues/18881#issuecomment-1704958820

The error message is irrelevant because I should be able to install any 1.16.0 plugin without it breaking. 

`@roadiehq/scaffolder-backend-module-utils` [release date](https://github.com/RoadieHQ/roadie-backstage-plugins/releases/tag/release-2023-07-24.1): 2023/07/24
Backstage 1.17.0 [release date](https://github.com/backstage/backstage/releases/tag/v1.17.0): 2023/08/15

If the dependency was pinned instead of using a caret, this issue would not have occurred since the plugin would pull the correct version. However, the plugin pulled the latest "non-breaking" patch (`@backstage/backend-common@1.19.4` instead of `@backstage/backend-common@1.19.1`) because it was specified using a caret. I say "non-breaking" because the newer patch version breaks backstage. Even though I used `@roadiehq/scaffolder-backend-module-utils` as an example, ANY plugin that uses a caret could be affected by this issue. The easiest way to remedy this issue would be by pinning the dependencies.

**Comment by Rugvip** [comment]
@schultzp2020 ah alright, that's an unrelated issue that shows up due to a particular `node_modules` layout, fix is over in #19989

**Comment by Rugvip** [comment]
@schultzp2020 alright, reopened, but please provide another example of where this is an issue.

The `config-loader` change was something that we deliberately decided to ship as a non-breaking change. It would have impact for use, but it's only catches existing broken behavior where the schema did not behave as expected. Basically this is what we have in mind for these kind of choices: https://xkcd.com/1172/, of course this one was a bit more tricky.

**Comment by schultzp2020** [comment]
@Rugvip, the errors I have brought up are just examples from the most recent minor version update for backstage. The reason behind raising this concern is that dependencies from version 1.17.x are impacting plugins that worked on 1.16.x before 1.17.x was released. This situation should not occur. Users running a 1.16.x instance with 1.16.x plugins shouldn't experience issues related to 1.17.x changes. It can be confusing for users to have their backstage instance encounter unexpected failures without any corresponding changes in their source code.

**Comment by Rugvip** [comment]
@schultzp2020 that is how the vast majority of the NPM ecosystem works. With the information we currently have it is not something that we are considering changing.

**Comment by schultzp2020** [comment]
Let's discuss this in the next SIG session. The issue is more nuanced than it may appear on the surface.

**Comment by schultzp2020** [comment]
not stale

**Comment by Rugvip** [comment]
Gonna close this as a followup to the discussion in the adoption SIG. tl;dr is that the underlying issue was that lockfiles weren't used properly, as well as non-breaking package version bumps for changes that could be argued to be breaking. Neither of those two things affect the decision here though, we still don't want to pin workspace dependencies. Consumers of our packages should use lockfiles to pin versions, and we should not release breaking changes without an appropriate package version bump.
