### ISSUE TITLE
🐛 Bug Report: Unable to read techdocs_metadata.json when using techdocs-entity annotation

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#20046]
### 📜 Description

I am trying to use the new `backstage.io/techdocs-entity` annotation functionality introduced in #19279 which allows you to write one single techdocs entry for multiple entities.

My setup includes:
- A system entity with `backstage.io/techdocs-ref` annotation
- A component entity which links to the system using `backstage.io/techdocs-entity` annotation

The techdocs on the sytem entity still works, and I can see that the component entity now has the techdocs link enabled on the component entity page.

However, navigating to the system techdocs from the component entity is not properly able to show the techdocs and runs into an error.

### 👍 Expected behavior

When clicking on the techdocs link on the component view, it should properly show the techdocs for the linked entity

### 👎 Actual Behavior with Screenshots

An error occurs, causing techdocs to not render for the `backstage-ui` component.

### 👟 Reproduction steps

I first tried this out by modeling our own Backstage system (not listing all for brevity). This is a local `catalog-info.yaml` file statically linked into backstage `app-config.yaml` in the same repo for testing.

Techdocs is set to use the local builder / generator / publisher mode.

```
---
apiVersion: backstage.io/v1alpha1\
kind: System
metadata:
  name: backstage
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: user:bforbis
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1\
kind: Component
metadata:
  name: backstage-ui
  annotations:
    backstage.io/techdocs-entity: system/default:backstage
spec:
  type: website
  system: backstage
  owner: user:bforbis
  lifecycle: experimental
---
```

### 📃 Provide the context for the Bug.

```
1] 2023-09-20T13:43:24.367Z techdocs info Unable to get metadata for 'component:default/backstage-ui' with error Error: Unable to read techdocs_metadata.json at /Users/bforbis/athena/git/bforbis/athena-backstage/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/backstage-ui/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory, open '/Users/bforbis/athena/git/bforbis/athena-backstage/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/backstage-ui/techdocs_metadata.json'; caused by Error: ENOENT: no such file or directory, open '/Users/bforbis/athena/git/bforbis/athena-backstage/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/backstage-ui/techdocs_metadata.json' type=plugin
[1] 2023-09-20T13:43:24.368Z backstage info ::1 - - [20/Sep/2023:13:43:24 +0000] "GET /api/techdocs/static/docs/default/component/backstage-ui/index.html HTTP/1.1" 404 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" type=incomingRequest
[1] 2023-09-20T13:43:24.369Z techdocs info Unable to get metadata for 'component:default/backstage-ui' with error InputError: No location annotation provided in entity: backstage-ui type=plugin
[1] 2023-09-20T13:43:24.369Z backstage info ::1 - - [20/Sep/2023:13:43:24 +0000] "GET /api/techdocs/metadata/techdocs/default/component/backstage-ui HTTP/1.1" 404 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" type=incomingRequest
[1] 2023-09-20T13:43:24.370Z techdocs error Failed to build the docs page: No location annotation provided in entity: backstage-ui No location annotation provided in entity: backstage-ui type=plugin cause=undefined name=InputError stack=InputError: No location annotation provided in entity: backstage-ui
[1]     at parseReferenceAnnotation (/Users/bforbis/athena/git/bforbis/athena-backstage/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:641:11)
[1]     at Preparers.get (/Users/bforbis/athena/git/bforbis/athena-backstage/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:853:22)
[1]     at new DocsBuilder (/Users/bforbis/athena/git/bforbis/athena-backstage/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:109:31)
[1]     at DocsSynchronizer.doSync (/Users/bforbis/athena/git/bforbis/athena-backstage/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:300:27)
[1]     at /Users/bforbis/athena/git/bforbis/athena-backstage/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:683:30
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1] 2023-09-20T13:43:24.370Z backstage info ::1 - - [20/Sep/2023:13:43:24 +0000] "GET /api/techdocs/metadata/entity/default/component/backstage-ui HTTP/1.1" 404 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" type=incomingRequest
[1] 2023-09-20T13:43:24.371Z backstage info ::1 - - [20/Sep/2023:13:43:24 +0000] "GET /api/techdocs/sync/default/component/backstage-ui HTTP/1.1" 200 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" type=incomingRequest
```

### 🖥️ Your Environment

```
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.14.0
yarn: 1.22.19
cli:  0.22.13 (installed)
backstage:  1.18.0

Dependencies:
  @backstage/app-defaults                                          1.4.3
  @backstage/backend-app-api                                       0.4.3, 0.5.3
  @backstage/backend-common                                        0.18.5, 0.19.5
  @backstage/backend-dev-utils                                     0.1.1
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.5.2, 0.6.3
  @backstage/backend-tasks                                         0.5.8
  @backstage/catalog-client                                        1.4.4
  @backstage/catalog-model                                         1.4.2
  @backstage/cli-common                                            0.1.12
  @backstage/cli-node                                              0.1.4
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.0
  @backstage/config                                                1.1.0
  @backstage/core-app-api                                          1.10.0
  @backstage/core-components                                       0.12.5, 0.13.5
  @backstage/core-plugin-api                                       1.6.0
  @backstage/errors                                                1.2.2
  @backstage/eslint-plugin                                         0.1.3
  @backstage/integration-aws-node                                  0.1.6
  @backstage/integration-react                                     1.1.19
  @backstage/integration                                           1.7.0
  @backstage/plugin-analytics-module-ga4                           0.1.4
  @backstage/plugin-api-docs                                       0.9.11
  @backstage/plugin-app-backend                                    0.3.51
  @backstage/plugin-app-node                                       0.1.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.0
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.0
  @backstage/plugin-auth-backend-module-google-provider            0.1.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.0
  @backstage/plugin-auth-backend                                   0.19.0
  @backstage/plugin-auth-node                                      0.2.19, 0.3.0
  @backstage/plugin-bazaar-backend                                 0.3.0
  @backstage/plugin-bazaar                                         0.2.16
  @backstage/plugin-catalog-backend-module-aws                     0.2.6
  @backstage/plugin-catalog-backend-module-bitbucket-server        0.1.16
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.0
  @backstage/plugin-catalog-backend                                1.13.0
  @backstage/plugin-catalog-common                                 1.0.16
  @backstage/plugin-catalog-graph                                  0.2.36
  @backstage/plugin-catalog-import                                 0.10.0
  @backstage/plugin-catalog-node                                   1.4.4
  @backstage/plugin-catalog-react                                  1.8.4
  @backstage/plugin-catalog                                        1.13.0
  @backstage/plugin-entity-validation                              0.1.9
  @backstage/plugin-events-backend                                 0.2.12
  @backstage/plugin-events-node                                    0.2.12
  @backstage/plugin-github-actions                                 0.6.5
  @backstage/plugin-kubernetes-common                              0.6.6
  @backstage/plugin-linguist-backend                               0.5.0
  @backstage/plugin-linguist-common                                0.1.2
  @backstage/plugin-linguist                                       0.1.9
  @backstage/plugin-org                                            0.6.14
  @backstage/plugin-permission-backend                             0.5.26
  @backstage/plugin-permission-common                              0.7.8
  @backstage/plugin-permission-node                                0.7.14
  @backstage/plugin-permission-react                               0.4.15
  @backstage/plugin-proxy-backend                                  0.4.0
  @backstage/plugin-scaffolder-backend                             1.17.0
  @backstage/plugin-scaffolder-common                              1.4.1
  @backstage/plugin-scaffolder-node                                0.2.3
  @backstage/plugin-scaffolder-react                               1.5.5
  @backstage/plugin-scaffolder                                     1.15.0
  @backstage/plugin-search-backend-module-catalog                  0.1.7
  @backstage/plugin-search-backend-module-pg                       0.5.12
  @backstage/plugin-search-backend-module-techdocs                 0.1.7
  @backstage/plugin-search-backend-node                            1.2.7
  @backstage/plugin-search-backend                                 1.4.3
  @backstage/plugin-search-common                                  1.2.6
  @backstage/plugin-search-react                                   1.7.0
  @backstage/plugin-search                                         1.4.0
  @backstage/plugin-tech-radar                                     0.6.8
  @backstage/plugin-techdocs-backend                               1.7.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.0
  @backstage/plugin-techdocs-node                                  1.8.0
  @backstage/plugin-techdocs-react                                 1.1.11
  @backstage/plugin-techdocs                                       1.7.0
  @backstage/plugin-user-settings                                  0.7.10
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.3
  @backstage/theme                                                 0.2.19, 0.4.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
Hi @jrwpatterson 👋
Could you have a look into this?

**Comment by Jeymisson** [comment]
I'm with the same issue. @bforbis did you find any workaround for it?

**Comment by bforbis** [comment]
> I'm with the same issue. @bforbis did you find any workaround for it?

No, I did not find a workaround. Still hoping someone can help out here.

**Comment by lsabalo** [comment]
@bforbis you have a type in you `techdocs-entity` line, it should be 
`backstage.io/techdocs-entity: system:default/backstage`
not
`backstage.io/techdocs-entity: system/default:backstage`

(Notice the forward slash and the semicolon)

**Comment by bforbis** [comment]
Oh, well that will do it 😞 . Can't believe I didn't see that. Looks like things are working once I swap the colon and /.
