### ISSUE TITLE
🐛 Bug Report: new Backstage site fails with runtime TechDocs error "react-dom/client"

### ISSUE THREAD

**Issue by ourchitectureio** [backstage/backstage#20648]
### 📜 Description

Creating a new backstage skeleton application and then running `yarn install` followed by `yarn dev` results in the runtime TechDocs error.

The backend starts up correctly and the frontend "app" starts to launch a browser, briefly displays the catalog home page, but then "crashes" with a client-side runtime error in the browser as well as in the "app" logs.

### 👍 Expected behavior

Works out of the box.

### 👎 Actual Behavior with Screenshots

```
Failed to compile.

Module not found: Can't resolve 'react-dom/client' in 'node_modules\@backstage\plugin-techdocs\dist\esm'
node_modules/@backstage/plugin-techdocs/dist/esm/TechDocsReaderPage-ac1d5884.esm.js
```

### 👟 Reproduction steps

1. Create new backstage app
2. Run `yarn install`
3. Run `yarn dev`

### 📃 Provide the context for the Bug.

> $ yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace @ourchitecture/ourstage-app start
$ yarn workspace @ourchitecture/ourstage-backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[1] Build succeeded
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '\packages\app\public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[0] ERROR in ../../node_modules/@backstage/plugin-techdocs/dist/esm/TechDocsReaderPage-ac1d5884.esm.js 1143:13-40
[0] Module not found: Error: Can't resolve 'react-dom/client' in '\node_modules\@backstage\plugin-techdocs\dist\esm'
[0]
[0] webpack compiled with 1 error
[1] Loaded config from app-config.yaml
[1] 2023-10-17T21:34:13.274Z backstage info Found 2 new secrets in config that will be redacted 
[1] 2023-10-17T21:34:13.285Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{}
[1] 2023-10-17T21:34:13.518Z catalog info Performing database migration type=plugin
[1] 2023-10-17T21:34:14.211Z auth info Configuring "database" as KeyStore provider type=plugin
[1] 2023-10-17T21:34:14.280Z techdocs info Creating Local publisher for TechDocs type=plugin
[1] 2023-10-17T21:34:14.294Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog type=plugin
[1] 2023-10-17T21:34:14.295Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs type=plugin
[1] 2023-10-17T21:34:14.296Z search info Starting all scheduled search tasks. type=plugin
[1] 2023-10-17T21:34:14.390Z backstage info Listening on :7007 
[1] 2023-10-17T21:34:14.409Z backstage info Task worker starting: search_index_software_catalog, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} type=taskManager task=search_index_software_catalog
[1] 2023-10-17T21:34:14.409Z backstage info Task worker starting: search_index_techdocs, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} type=taskManager task=search_index_techdocs
[1] 2023-10-17T21:34:14.799Z backstage info ::ffff:127.0.0.1 - - [17/Oct/2023:21:34:14 +0000] "GET /api/catalog/entities?filter=kind=component HTTP/1.1" 200 2 "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0" type=incomingRequest
[1] 2023-10-17T21:34:14.870Z backstage info ::ffff:127.0.0.1 - - [17/Oct/2023:21:34:14 +0000] "GET /api/catalog/entity-facets?filter=kind=component&facet=spec.type HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0" type=incomingRequest
[1] 2023-10-17T21:34:14.876Z backstage info ::ffff:127.0.0.1 - - [17/Oct/2023:21:34:14 +0000] "GET /api/catalog/entity-facets?filter=kind=component&facet=spec.lifecycle HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0" type=incomingRequest
[1] 2023-10-17T21:34:14.878Z backstage info ::ffff:127.0.0.1 - - [17/Oct/2023:21:34:14 +0000] "GET /api/catalog/entity-facets?filter=kind=component&facet=metadata.tags HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0" type=incomingRequest
[1] 2023-10-17T21:34:14.880Z backstage info ::ffff:127.0.0.1 - - [17/Oct/2023:21:34:14 +0000] "GET /api/catalog/entity-facets?filter=kind=component&facet=metadata.namespace HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0" type=incomingRequest
[1] 2023-10-17T21:34:17.425Z search info Collating documents for software-catalog via DefaultCatalogCollatorFactory type=plugin documentType=software-catalog
[1] 2023-10-17T21:34:17.432Z search info Collating documents for techdocs via DefaultTechDocsCollatorFactory type=plugin documentType=techdocs
[1] 2023-10-17T21:34:17.442Z backstage info ::1 - - [17/Oct/2023:21:34:17 +0000] "GET /api/catalog/entities?filter=metadata.annotations.backstage.io%2Ftechdocs-ref&fields=kind,namespace,metadata.annotations,metadata.name,metadata.title,metadata.namespace,spec.type,spec.lifecycle,relations&offset=0&limit=500 HTTP/1.1" 200 2 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2023-10-17T21:34:17.446Z search warn Index for techdocs was not created: indexer received 0 documents type=plugin documentType=techdocs
[1] 2023-10-17T21:34:17.447Z search info Collating documents for techdocs succeeded type=plugin documentType=techdocs
[1] 2023-10-17T21:34:17.449Z backstage info ::1 - - [17/Oct/2023:21:34:17 +0000] "GET /api/catalog/entities?offset=0&limit=500 HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2023-10-17T21:34:17.459Z search info Collating documents for software-catalog succeeded type=plugin documentType=software-catalog

### 🖥️ Your Environment

> $ yarn backstage-cli info
yarn run v1.22.19
$ node_modules\.bin\backstage-cli info
OS:   Windows_NT 10.0.22621 - win32/x64
node: v18.18.1
yarn: 1.22.19
cli:  0.22.13 (installed)
backstage:  1.18.0

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.6
  @backstage/backend-common                                        0.19.8
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6
  @backstage/backend-tasks                                         0.5.11
  @backstage/catalog-client                                        1.4.5
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.13.6
  @backstage/core-plugin-api                                       1.7.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.3
  @backstage/plugin-auth-node                                      0.3.2, 0.4.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-github-actions                                 0.6.6
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-permission-common                              0.7.9
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.3
  @backstage/plugin-scaffolder-backend                             1.18.0
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.6
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6
Done in 0.89s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by javaface** [comment]
Same issue.  I think this to be related...  **error Received malformed response from registry for "@types%2freact-dom". The registry may be down** shows with yarn config set "strict-ssl" false

**Comment by asotog** [comment]
at least for us this is kind of fix, culprit seems on that tech docs package, something getting update on minor version breaking it:
<img width="478" alt="image" src="https://github.com/backstage/backstage/assets/813023/f2ec2675-f773-4ec9-a6fd-8080f7d97e93">

**Comment by javaface** [comment]
@asotog, thanks for the post.  Changing this line worked for me to work around this error.
"@backstage/plugin-techdocs": "1.7.0",

**Comment by awanlin** [comment]
Hi everyone, a new version of Backstage was release yesterday - `1.19.0` - and after running `npx @backstage/create-app@latest` then following the reproduction steps I don't have this error. Any chance you can try that?

Alternatively you could run `yarn backstage-cli versions:bump` that would upgrade you to the latest monthly release

**Comment by Rugvip** [comment]
Thank you for reporting! I've backported the support for `HAS_REACT_DOM_CLIENT` to older versions of the CLI in #20674. That'll significantly widen the techdocs/CLI support window so that older apps are very unlikely to run into this issue.

**Comment by Rugvip** [comment]
For anyone hitting this issue right now that want's a solution: make sure you upgrade to the latest version of `@backstage/cli`

**Comment by javaface** [comment]
> Hi everyone, a new version of Backstage was release yesterday - `1.19.0` - and after running `npx @backstage/create-app@latest` then following the reproduction steps I don't have this error. Any chance you can try that?
> 
> Alternatively you could run `yarn backstage-cli versions:bump` that would upgrade you to the latest monthly release

@awanlin, created a new app and got this error.

~/src/test/test-app$ yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[1] (node:31184) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
[1] (Use `node --trace-warnings ...` to show where the warning was created)
[0] Loaded config from app-config.yaml
[0] fatal: not a git repository (or any of the parent directories): .git
[0] WARNING: Failed to read git commit, ExitCodeError: Command 'git rev-parse HEAD' exited with code 128
[0] fatal: not a git repository (or any of the parent directories): .git
[0] WARNING: Failed to describe git version, ExitCodeError: Command 'git describe --always' exited with code 128
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/home/admin/src/test/test-app/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] node:fs:603
[1]   handleErrorFromBinding(ctx);
[1]   ^
[1]
[1] Error: EMFILE: too many open files, open '/home/admin/src/test/test-app/node_modules/qs/lib/parse.js'
[1]     at Object.openSync (node:fs:603:3)
[1]     at Object.readFileSync (node:fs:471:35)
[1]     at Object.N (/home/admin/src/test/test-app/node_modules/@esbuild-kit/cjs-loader/dist/index.cjs:1:897)
[1]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[1]     at Module._load (node:internal/modules/cjs/loader:960:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18)
[1]     at <anonymous> (/home/admin/src/test/test-app/node_modules/qs/lib/index.js:4:13)
[1]     at Object.<anonymous> (/home/admin/src/test/test-app/node_modules/qs/lib/index.js:11:1)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[1]     at Object.N (/home/admin/src/test/test-app/node_modules/@esbuild-kit/cjs-loader/dist/index.cjs:1:1077)
[1]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[1]     at Module._load (node:internal/modules/cjs/loader:960:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18)
[1]     at <anonymous> (/home/admin/src/test/test-app/node_modules/typed-rest-client/Util.js:13:12) {
[1]   errno: -24,
[1]   syscall: 'open',
[1]   code: 'EMFILE',
[1]   path: '/home/admin/src/test/test-app/node_modules/qs/lib/parse.js'
[1] }
[1]
[1] Node.js v18.18.0
[0] webpack compiled successfully

**Comment by ourchitectureio** [comment]
> > Hi everyone, a new version of Backstage was release yesterday - `1.19.0` - and after running `npx @backstage/create-app@latest` then following the reproduction steps I don't have this error. Any chance you can try that?
> > Alternatively you could run `yarn backstage-cli versions:bump` that would upgrade you to the latest monthly release
> 
> @awanlin, created a new app and got this error.
> 
> ~/src/test/test-app$ yarn dev yarn run v1.22.19 $ concurrently "yarn start" "yarn start-backend" $ yarn workspace app start $ yarn workspace backend start $ backstage-cli package start $ backstage-cli package start [1] (node:31184) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time [1] (Use `node --trace-warnings ...` to show where the warning was created) [0] Loaded config from app-config.yaml [0] fatal: not a git repository (or any of the parent directories): .git [0] WARNING: Failed to read git commit, ExitCodeError: Command 'git rev-parse HEAD' exited with code 128 [0] fatal: not a git repository (or any of the parent directories): .git [0] WARNING: Failed to describe git version, ExitCodeError: Command 'git describe --always' exited with code 128 [0] [webpack-dev-server] Project is running at: [0] [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/ [0] [webpack-dev-server] Content not from webpack is served from '/home/admin/src/test/test-app/packages/app/public' directory [0] [webpack-dev-server] 404s will fallback to '/index.html' [0] [webpack-dev-middleware] wait until bundle finished: / [1] node:fs:603 [1] handleErrorFromBinding(ctx); [1] ^ [1] [1] **Error: EMFILE: too many open files, open '/home/admin/src/test/test-app/node_modules/qs/lib/parse.js'** [1] at Object.openSync (node:fs:603:3) [1] at Object.readFileSync (node:fs:471:35) [1] at Object.N (/home/admin/src/test/test-app/node_modules/@esbuild-kit/cjs-loader/dist/index.cjs:1:897) [1] at Module.load (node:internal/modules/cjs/loader:1119:32) [1] at Module._load (node:internal/modules/cjs/loader:960:12) [1] at Module.require (node:internal/modules/cjs/loader:1143:19) [1] at require (node:internal/modules/cjs/helpers:119:18) [1] at (/home/admin/src/test/test-app/node_modules/qs/lib/index.js:4:13) [1] at Object. (/home/admin/src/test/test-app/node_modules/qs/lib/index.js:11:1) [1] at Module._compile (node:internal/modules/cjs/loader:1256:14) [1] at Object.N (/home/admin/src/test/test-app/node_modules/@esbuild-kit/cjs-loader/dist/index.cjs:1:1077) [1] at Module.load (node:internal/modules/cjs/loader:1119:32) [1] at Module._load (node:internal/modules/cjs/loader:960:12) [1] at Module.require (node:internal/modules/cjs/loader:1143:19) [1] at require (node:internal/modules/cjs/helpers:119:18) [1] at (/home/admin/src/test/test-app/node_modules/typed-rest-client/Util.js:13:12) { [1] errno: -24, [1] syscall: 'open', [1] code: 'EMFILE', [1] path: '/home/admin/src/test/test-app/node_modules/qs/lib/parse.js' [1] } [1] [1] Node.js v18.18.0 [0] webpack compiled successfully
> 
> yarn **backstage-cli info** $ /home/admin/src/test/test-app/node_modules/.bin/backstage-cli info OS: Linux 5.10.102.1-microsoft-standard-WSL2 - linux/x64 node: v18.18.0 yarn: 1.22.19 cli: 0.23.0 (installed) backstage: 1.19.0
> 
> Dependencies: @backstage/app-defaults 1.4.4 @backstage/backend-app-api 0.5.6 @backstage/backend-common 0.19.8 @backstage/backend-dev-utils 0.1.2 @backstage/backend-openapi-utils 0.0.5 @backstage/backend-plugin-api 0.6.6 @backstage/backend-tasks 0.5.11 @backstage/catalog-client 1.4.5 @backstage/catalog-model 1.4.3 @backstage/cli-common 0.1.13 @backstage/cli-node 0.1.5 @backstage/cli 0.23.0 @backstage/config-loader 1.5.1 @backstage/config 1.1.1 @backstage/core-app-api 1.11.0 @backstage/core-components 0.13.6 @backstage/core-plugin-api 1.7.0 @backstage/e2e-test-utils 0.1.0 @backstage/errors 1.2.3 @backstage/eslint-plugin 0.1.3 @backstage/frontend-app-api 0.2.0 @backstage/frontend-plugin-api 0.2.0 @backstage/integration-aws-node 0.1.7 @backstage/integration-react 1.1.20 @backstage/integration 1.7.1 @backstage/plugin-api-docs 0.9.12 @backstage/plugin-app-backend 0.3.54 @backstage/plugin-app-node 0.1.6 @backstage/plugin-auth-backend-module-gcp-iap-provider 0.2.0 @backstage/plugin-auth-backend-module-github-provider 0.1.3 @backstage/plugin-auth-backend-module-gitlab-provider 0.1.3 @backstage/plugin-auth-backend-module-google-provider 0.1.3 @backstage/plugin-auth-backend-module-microsoft-provider 0.1.1 @backstage/plugin-auth-backend-module-oauth2-provider 0.1.3 @backstage/plugin-auth-backend 0.19.3 @backstage/plugin-auth-node 0.4.0 @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3 @backstage/plugin-catalog-backend 1.14.0 @backstage/plugin-catalog-common 1.0.17 @backstage/plugin-catalog-graph 0.2.37 @backstage/plugin-catalog-import 0.10.1 @backstage/plugin-catalog-node 1.4.7 @backstage/plugin-catalog-react 1.8.5 @backstage/plugin-catalog 1.14.0 @backstage/plugin-events-node 0.2.15 @backstage/plugin-github-actions 0.6.6 @backstage/plugin-graphiql 0.2.55 @backstage/plugin-org 0.6.15 @backstage/plugin-permission-common 0.7.9 @backstage/plugin-permission-node 0.7.17 @backstage/plugin-permission-react 0.4.16 @backstage/plugin-proxy-backend 0.4.3 @backstage/plugin-scaffolder-backend 1.18.0 @backstage/plugin-scaffolder-common 1.4.2 @backstage/plugin-scaffolder-node 0.2.6 @backstage/plugin-scaffolder-react 1.5.6 @backstage/plugin-scaffolder 1.15.1 @backstage/plugin-search-backend-module-catalog 0.1.10 @backstage/plugin-search-backend-module-pg 0.5.15 @backstage/plugin-search-backend-module-techdocs 0.1.10 @backstage/plugin-search-backend-node 1.2.10 @backstage/plugin-search-backend 1.4.6 @backstage/plugin-search-common 1.2.7 @backstage/plugin-search-react 1.7.1 @backstage/plugin-search 1.4.1 @backstage/plugin-tech-radar 0.6.9 @backstage/plugin-techdocs-backend 1.8.0 @backstage/plugin-techdocs-module-addons-contrib 1.1.1 @backstage/plugin-techdocs-node 1.9.0 @backstage/plugin-techdocs-react 1.1.12 @backstage/plugin-techdocs 1.8.0 @backstage/plugin-user-settings 0.7.11 @backstage/release-manifests 0.0.10 @backstage/test-utils 1.4.4 @backstage/theme 0.4.3 @backstage/types 1.1.1 @backstage/version-bridge 1.0.6 Done in 0.56s.

@javaface What you describe is a different error caused by running backstage in the absence of a `git` project. Simply run `git init` in the same directory and then re-run `yarn dev`.

**Comment by ourchitectureio** [comment]
> Hi everyone, a new version of Backstage was release yesterday - `1.19.0` - and after running `npx @backstage/create-app@latest` then following the reproduction steps I don't have this error. Any chance you can try that?
> 
> Alternatively you could run `yarn backstage-cli versions:bump` that would upgrade you to the latest monthly release

Thank you. I have run both `yarn backstage-cli versions:bump` and `yarn upgrade`.

For some reason, `yarn dev` (with the "concurrently" task) completely fails to start the backend, but `yarn start-backend` in one terminal and `yarn start` in another terminal successfully runs backstage. I don't really want to submit another issue and investigate "why", so I'll just work this way for now.
