### ISSUE TITLE
🐛 Bug Report: Cannot mock `@backstage/core-components` dependency

### ISSUE THREAD

**Issue by schultzp2020** [backstage/backstage#20713]
### 📜 Description

It bugs out when users try to mock the `@backstage/core-components` dependency. Specifically the `...jest.requireActual('@backstage/core-components'),` line causes the error. 

```tsx
jest.mock('@backstage/core-components', () => ({
  ...jest.requireActual('@backstage/core-components'),
  useSidebarOpenState: jest.fn(),
}));
```

### 👍 Expected behavior

I should be able to mock the `@backstage/core-components` dependency`.

### 👎 Actual Behavior with Screenshots

```log
$ yarn --cwd ./packages/app/ test
yarn run v1.22.19
$ backstage-cli package test --coverage      
 FAIL  src/components/Root/SidebarLogo.test.tsx
  ● Test suite failed to run

    ReferenceError: Cannot access 'AutoLogout' before initialization

       7 |
       8 | jest.mock('@backstage/core-components', () => ({
    >  9 |   ...jest.requireActual('@backstage/core-components'),
         |           ^
      10 |   useSidebarOpenState: jest.fn(),
      11 | }));
      12 |

      at Object.AutoLogout (../../../node_modules/@backstage/core-components/dist/index.esm.js:16:9)
      at requireActual (components/Root/SidebarLogo.test.tsx:9:11)
      at Object.<anonymous> (../../../node_modules/@backstage/plugin-catalog-react/dist/index.esm.js:172:25)
      at Object.<anonymous> (../../../node_modules/@backstage/core-components/dist/index.esm.js:367:29)
      at requireActual (components/Root/SidebarLogo.test.tsx:9:11)
      at Object.<anonymous> (components/Root/SidebarLogo.test.tsx:20:25)
```

A quick Google search says the `AutoLogout` export most likely has a circular dependency. I have not verified if this is correct.

### 👟 Reproduction steps

1. Mock the `@backstage/core-components` dependency.

    ```tsx
    jest.mock('@backstage/core-components', () => ({
      ...jest.requireActual('@backstage/core-components'),
      useSidebarOpenState: jest.fn(),
    }));
    ```
2. Run the test script

### 📃 Provide the context for the Bug.

I am trying to mock the `@backstage/core-components` dependency so I can mock the `useSidebarOpenState()` hook. 

### 🖥️ Your Environment

```log
$ yarn backstage-cli info
yarn run v1.22.19
$ C:\Programming\Work\backstage-showcase\node_modules\.bin\backstage-cli info
OS:   Windows_NT 10.0.19045 - win32/x64
node: v18.18.0
yarn: 1.22.19
cli:  0.23.0 (installed)
backstage:  1.19.1

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.6
  @backstage/backend-common                                        0.19.8
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6
  @backstage/backend-plugin-manager                                0.0.5-janus.0
  @backstage/backend-tasks                                         0.5.11
  @backstage/catalog-client                                        1.4.5
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.23.0
  @backstage/config-loader                                         1.5.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.13.6
  @backstage/core-plugin-api                                       1.7.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.3
  @backstage/plugin-auth-node                                      0.4.0, 0.3.2
  @backstage/plugin-azure-devops-backend                           0.4.3
  @backstage/plugin-azure-devops-common                            0.3.1
  @backstage/plugin-azure-devops                                   0.3.7
  @backstage/plugin-catalog-backend-module-github                  0.4.4
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.3
  @backstage/plugin-catalog-backend-module-openapi                 0.1.23
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-dynatrace                                      7.0.5
  @backstage/plugin-events-backend                                 0.2.15
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-github-actions                                 0.6.6
  @backstage/plugin-github-issues                                  0.2.14
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-home-react                                     0.1.4
  @backstage/plugin-home                                           0.5.9
  @backstage/plugin-jenkins-backend                                0.3.0
  @backstage/plugin-jenkins-common                                 0.1.20
  @backstage/plugin-jenkins                                        0.9.0
  @backstage/plugin-kubernetes-backend                             0.13.0
  @backstage/plugin-kubernetes-common                              0.7.0
  @backstage/plugin-kubernetes-node                                0.1.0
  @backstage/plugin-kubernetes-react                               0.1.0
  @backstage/plugin-kubernetes                                     0.11.0
  @backstage/plugin-lighthouse-common                              0.1.4
  @backstage/plugin-lighthouse                                     0.4.10
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-pagerduty                                      0.6.6
  @backstage/plugin-permission-backend                             0.5.29
  @backstage/plugin-permission-common                              0.7.9
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.3
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.9
  @backstage/plugin-scaffolder-backend                             1.18.0
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.6
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-sonarqube-backend                              0.2.8
  @backstage/plugin-sonarqube-react                                0.1.9
  @backstage/plugin-sonarqube                                      0.7.6
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6
Done in 2.62s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
This is likely caused by #18318, looking back at it I'm realizing that `MissingAnnotationEmptyState` should not actually live in `core-components` and the dependencies on the catalog packages should be removed.

Best way forward here I think is:

- Copy and export `MissingAnnotationEmptyState` from `@backstage/plugin-catalog-react`
- Update all usages of `MissingAnnotationEmptyState` in the main repo to import it from `@backstage/plugin-catalog-react`
- Deprecate `MissingAnnotationEmptyState` in `@backstage/core-components` and point to the new one
- Remove `useEntity` from `MissingAnnotationEmptyState` in `@backstage/core-components` and remove the dependencies on `@backstage/plugins-catalog-react` and `@backstage/catalog-model`

Would love some help to get this update through 🙏

**Comment by stephenmuss** [comment]
I'm seeing this after upgrading Backstage to 1.26.0.

**Comment by schultzp2020** [comment]
@Rugvip can you please reopen? Or should I create another issue?

```log
    ReferenceError: Cannot access 'AutoLogout' before initialization

       7 |
       8 | jest.mock('@backstage/core-components', () => ({
    >  9 |   ...jest.requireActual('@backstage/core-components'),
         |           ^
      10 |   useSidebarOpenState: jest.fn(),
      11 | }));
      12 |

      at Object.AutoLogout (../../../node_modules/@backstage/core-components/dist/index.esm.js:19:9)
      at requireActual (components/Root/SidebarLogo.test.tsx:9:11)
      at Object.<anonymous> (../../../node_modules/@backstage/core-components/dist/index.esm.js:420:25)
      at requireActual (components/Root/SidebarLogo.test.tsx:9:11)
      at Object.<anonymous> (components/Root/SidebarLogo.test.tsx:20:25)
```
