### ISSUE TITLE
🐛 Bug Report: Cannot find module '@backstage/plugin-scaffolder-backend-module-gitlab'

### ISSUE THREAD

**Issue by Andrei101Ru** [backstage/backstage#20785]
### 📜 Description

Unable to load backend-module-github even adding the module.

The same problem (only GitHUB) was described in the issue https://github.com/backstage/backstage/issues/15096, but no solution was indicated there.

### 👍 Expected behavior

We should be able to load the module after adding via yarn add

### 👎 Actual Behavior with Screenshots

```
yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[1] Build succeeded
[0] Loaded config from app-config.yaml, app-config.local.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] On Your Network (IPv4): http://10.128.1.6:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/opt/test/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[1] /opt/test/packages/backend/dist/main.js:323
[1] /******/                    throw e;
[1]                             ^
[1]
[1] Error: Cannot find module '@backstage/plugin-catalog-backend-module-gitlab'
[1]     at webpackMissingModule (webpack-internal:///./src/plugins/catalog.ts:9:50)
[1]     at eval (webpack-internal:///./src/plugins/catalog.ts:9:172)
[1]     at ./src/plugins/catalog.ts (/opt/test/packages/backend/dist/main.js:52:1)
[1]     at __webpack_require__ (/opt/test/packages/backend/dist/main.js:320:33)
[1]     at fn (/opt/test/packages/backend/dist/main.js:480:21)
[1]     at eval (webpack-internal:///./src/index.ts:10:74)
[1]     at ./src/index.ts (/opt/test/packages/backend/dist/main.js:19:1)
[1]     at __webpack_require__ (/opt/test/packages/backend/dist/main.js:320:33)
[1]     at /opt/test/packages/backend/dist/main.js:1299:37
[1]     at Object.<anonymous> (/opt/test/packages/backend/dist/main.js:1301:12)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[1]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[1]     at Module._load (node:internal/modules/cjs/loader:960:12)
[1]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
[1]     at node:internal/main/run_main_module:23:47 {
[1]   code: 'MODULE_NOT_FOUND'
[1] }
```

### 👟 Reproduction steps

Add github discovery  https://backstage.io/docs/integrations/gitlab/discovery

### 🖥️ Your Environment

```
yarn backstage-cli info
yarn run v1.22.19
$ /opt/test/node_modules/.bin/backstage-cli info
OS:   Linux 5.10.0-19-amd64 - linux/x64
node: v18.18.1
yarn: 1.22.19
cli:  0.22.13 (installed)
backstage:  1.18.0

Dependencies:
  @backstage/app-defaults                                          1.4.3
  @backstage/backend-app-api                                       0.5.5, 0.5.6
  @backstage/backend-common                                        0.19.7, 0.19.8
  @backstage/backend-dev-utils                                     0.1.1, 0.1.2
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.6.5, 0.6.6
  @backstage/backend-tasks                                         0.5.10, 0.5.11
  @backstage/catalog-client                                        1.4.4, 1.4.5
  @backstage/catalog-model                                         1.4.2, 1.4.3
  @backstage/cli-common                                            0.1.12, 0.1.13
  @backstage/cli-node                                              0.1.4, 0.1.5
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.0, 1.5.1
  @backstage/config                                                1.1.0, 1.1.1
  @backstage/core-app-api                                          1.10.0
  @backstage/core-components                                       0.13.5
  @backstage/core-plugin-api                                       1.6.0
  @backstage/errors                                                1.2.2, 1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/integration-aws-node                                  0.1.6, 0.1.7
  @backstage/integration-react                                     1.1.19
  @backstage/integration                                           1.7.0, 1.7.1
  @backstage/plugin-api-docs                                       0.9.11
  @backstage/plugin-app-backend                                    0.3.53
  @backstage/plugin-app-node                                       0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.2
  @backstage/plugin-auth-backend-module-github-provider            0.1.2
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.2
  @backstage/plugin-auth-backend-module-google-provider            0.1.2
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.2
  @backstage/plugin-auth-backend                                   0.19.2
  @backstage/plugin-auth-node                                      0.3.2, 0.4.0
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.2
  @backstage/plugin-catalog-backend                                1.13.3
  @backstage/plugin-catalog-common                                 1.0.16, 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.36
  @backstage/plugin-catalog-import                                 0.10.0
  @backstage/plugin-catalog-node                                   1.4.6, 1.4.7
  @backstage/plugin-catalog-react                                  1.8.4
  @backstage/plugin-catalog                                        1.13.0
  @backstage/plugin-events-node                                    0.2.14
  @backstage/plugin-github-actions                                 0.6.5
  @backstage/plugin-org                                            0.6.14
  @backstage/plugin-permission-common                              0.7.8, 0.7.9
  @backstage/plugin-permission-node                                0.7.16, 0.7.17
  @backstage/plugin-permission-react                               0.4.15
  @backstage/plugin-proxy-backend                                  0.4.2
  @backstage/plugin-scaffolder-backend                             1.17.3
  @backstage/plugin-scaffolder-common                              1.4.1
  @backstage/plugin-scaffolder-node                                0.2.5
  @backstage/plugin-scaffolder-react                               1.5.5
  @backstage/plugin-scaffolder                                     1.15.0
  @backstage/plugin-search-backend-module-catalog                  0.1.9
  @backstage/plugin-search-backend-module-pg                       0.5.14
  @backstage/plugin-search-backend-module-techdocs                 0.1.9
  @backstage/plugin-search-backend-node                            1.2.9
  @backstage/plugin-search-backend                                 1.4.5
  @backstage/plugin-search-common                                  1.2.6, 1.2.7
  @backstage/plugin-search-react                                   1.7.0
  @backstage/plugin-search                                         1.4.0
  @backstage/plugin-tech-radar                                     0.6.8
  @backstage/plugin-techdocs-backend                               1.7.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.0
  @backstage/plugin-techdocs-node                                  1.8.2
  @backstage/plugin-techdocs-react                                 1.1.11
  @backstage/plugin-techdocs                                       1.7.0
  @backstage/plugin-user-settings                                  0.7.10
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.3
  @backstage/theme                                                 0.4.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5

```

cat ./packages/backend/src/plugins/catalog.ts
```
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { GitLabDiscoveryProcessor } from '@backstage/plugin-catalog-backend-module-gitlab';
import { Router } from 'express';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  builder.addProcessor(
    GitLabDiscoveryProcessor.fromConfig(env.config, { logger: env.logger }),
  );
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
You seem to be confusing github with gitlab. Did you try to follow the gitHUB installation instructions and then can't find the giLAB provider?

**Comment by Andrei101Ru** [comment]
Sorry, not a link to the instructions, here is the correct one: https://backstage.io/docs/integrations/gitlab/discovery
I configured gitLAB specifically, as you might notice from the listing of my config.
@freben

**Comment by freben** [comment]
Seems to work for me.

```
yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-gitlab
```

and then adding the exact same import and addProcessor as in your quoted code.

Can you chack that your `packages/backend/package.json` really has a line for `@backstage/plugin-catalog-backend-module-gitlab`?

Did you run this in some odd environment, such as developing from within a docker image or whatnot, which could mean that the actual node_modules used differs from the env where you did the `yarn add`?

In the place where you try to execute things, can you look into the node_modules structure and seeing that the desired module actually exists in there?

Feel free to make a reproduction repository somewhere that exhibits the problem, where we can look into it.

**Comment by Andrei101Ru** [comment]
@freben hi!
You are right - the problem is in the environment.
Fixed it by reinstalling node, yarn, backstage

**Comment by vinzscam** [comment]
glad the problem was fixed! Marking the issue as completed.
