### ISSUE TITLE
Error: Cannot find module '@backstage/plugin-catalog-backend-module-gerrit'

### ISSUE THREAD

**Issue by anishaanil1** [backstage/backstage#21438]
### 📜 Description

Steps to setup Gerrit Integration

https://backstage.io/docs/integrations/gerrit/discovery

Run the command

# From your Backstage root directory
yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-gerrit

Cd to the app-config.yaml file
Run yarn Dev it fails with the below errors

yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] On Your Network (IPv4): http://10.9.1.2:3001/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/data/test_backstage/backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[1] node:internal/modules/cjs/loader:1077
[1]   const err = new Error(message);
[1]               ^
[1]
[1] Error: Cannot find module '@backstage/plugin-catalog-backend-module-gerrit'
[1] Require stack:
[1] - /data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts
[1] - /data/test_backstage/backstage/packages/backend/src/index.ts
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[1]     at l.default._resolveFilename (/data/test_backstage/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1671)
[1]     at Module._load (node:internal/modules/cjs/loader:922:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18)
[1]     at <anonymous> (/data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts:5:38)
[1]     at Object.<anonymous> (/data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts:8:31)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[1]     at Object.j (/data/test_backstage/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1197)
[1]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[1]     at Module._load (node:internal/modules/cjs/loader:960:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18)
[1]     at app (/data/test_backstage/backstage/packages/backend/src/index.ts:26:21)
[1]     at Object.<anonymous> (/data/test_backstage/backstage/packages/backend/src/index.ts:115:2)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   requireStack: [
[1]     '/data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts',
[1]     '/data/test_backstage/backstage/packages/backend/src/index.ts'
[1]   ]
[1] }
[1]
[1] Node.js v18.18.2
[0] webpack compiled successfully

### 👍 Expected behavior

It should not throw the error but simply install teh plugin

### 👎 Actual Behavior with Screenshots

Steps to setup Gerrit Integration

https://backstage.io/docs/integrations/gerrit/discovery

Run the command

# From your Backstage root directory
yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-gerrit

Cd to the app-config.yaml file
Run yarn Dev it fails with the below errors

yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] On Your Network (IPv4): http://10.9.1.2:3001/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/data/test_backstage/backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[1] node:internal/modules/cjs/loader:1077
[1]   const err = new Error(message);
[1]               ^
[1]
[1] Error: Cannot find module '@backstage/plugin-catalog-backend-module-gerrit'
[1] Require stack:
[1] - /data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts
[1] - /data/test_backstage/backstage/packages/backend/src/index.ts
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[1]     at l.default._resolveFilename (/data/test_backstage/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1671)
[1]     at Module._load (node:internal/modules/cjs/loader:922:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18)
[1]     at <anonymous> (/data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts:5:38)
[1]     at Object.<anonymous> (/data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts:8:31)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[1]     at Object.j (/data/test_backstage/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1197)
[1]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[1]     at Module._load (node:internal/modules/cjs/loader:960:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18)
[1]     at app (/data/test_backstage/backstage/packages/backend/src/index.ts:26:21)
[1]     at Object.<anonymous> (/data/test_backstage/backstage/packages/backend/src/index.ts:115:2)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   requireStack: [
[1]     '/data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts',
[1]     '/data/test_backstage/backstage/packages/backend/src/index.ts'
[1]   ]
[1] }
[1]
[1] Node.js v18.18.2
[0] webpack compiled successfully

### 👟 Reproduction steps

Steps to setup Gerrit Integration

https://backstage.io/docs/integrations/gerrit/discovery

Run the command

# From your Backstage root directory
yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-gerrit

Cd to the app-config.yaml file
Run yarn Dev it fails with the below errors

yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] On Your Network (IPv4): http://10.9.1.2:3001/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/data/test_backstage/backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[1] node:internal/modules/cjs/loader:1077
[1]   const err = new Error(message);
[1]               ^
[1]
[1] Error: Cannot find module '@backstage/plugin-catalog-backend-module-gerrit'
[1] Require stack:
[1] - /data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts
[1] - /data/test_backstage/backstage/packages/backend/src/index.ts
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[1]     at l.default._resolveFilename (/data/test_backstage/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1671)
[1]     at Module._load (node:internal/modules/cjs/loader:922:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18)
[1]     at <anonymous> (/data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts:5:38)
[1]     at Object.<anonymous> (/data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts:8:31)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[1]     at Object.j (/data/test_backstage/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1197)
[1]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[1]     at Module._load (node:internal/modules/cjs/loader:960:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18)
[1]     at app (/data/test_backstage/backstage/packages/backend/src/index.ts:26:21)
[1]     at Object.<anonymous> (/data/test_backstage/backstage/packages/backend/src/index.ts:115:2)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   requireStack: [
[1]     '/data/test_backstage/backstage/packages/backend/src/plugins/catalog.ts',
[1]     '/data/test_backstage/backstage/packages/backend/src/index.ts'
[1]   ]
[1] }
[1]
[1] Node.js v18.18.2
[0] webpack compiled successfully

### 🖥️ Your Environment

yarn backstage-cli info
yarn run v1.22.19
$ /data/test_backstage/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.0-88-generic - linux/x64
node: v18.18.2
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.0

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-api-docs                                       0.10.0
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.4.1
  @backstage/plugin-catalog-backend-module-gerrit                  0.1.23
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.0
  @backstage/plugin-catalog-import                                 0.10.2
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.0
  @backstage/plugin-catalog                                        1.15.0
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.7
  @backstage/plugin-org                                            0.6.16
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.0
  @backstage/plugin-scaffolder                                     1.16.0
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.2
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.0
  @backstage/plugin-user-settings                                  0.7.12
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
Done in 0.81s.
root@:/data/test_backstage/backstage#

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @anishaanil1 👋🏻 ,
Could you check if the package has been added to the dependencies in the `packages/backend/package.json` file and is listed in the `node_module` folder?
