### ISSUE TITLE
🐛 Bug Report: app-config.yaml schema file includes wrong property

### ISSUE THREAD

**Issue by schematis** [backstage/backstage#21430]
### 📜 Description

When leveraging the schema file for app-config.yaml, it instructs you to put a `clientOptions` property under `elasticsearch` (see below).

```
elasticsearch:
    clientOptions:
      provider: aws
      node: https://vpc-backstage-aaabbbccc.us-east-1.es.amazonaws.com
```

[link to app-config.json](https://json.schemastore.org/app-config.json)

### 👍 Expected behavior

The app should come up and connect to the aws elasticsearch endpoint

### 👎 Actual Behavior with Screenshots
This is the error that is returned when specifying `clientOptions` as dictated by the schema file:

```
backstage-app-1: Backend failed to start up Error: Missing required config value at 'search.elasticsearch.node'
backstage-app-1:     at ConfigReader.getString (/app/node_modules/@backstage/config/dist/index.cjs.js:305:13)
backstage-app-1:     at ObservableConfigProxy.getString (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:169:30)
backstage-app-1:     at ElasticSearchSearchEngine.createElasticSearchClientOptions (/app/node_modules/@backstage/plugin-search-backend-module-elasticsearch/dist/index.cjs.js:636:20)
backstage-app-1:     at ElasticSearchSearchEngine.fromConfig (/app/node_modules/@backstage/plugin-search-backend-module-elasticsearch/dist/index.cjs.js:352:38)
backstage-app-1:     at async createPlugin (/app/packages/backend/dist/index.cjs.js:189:24)
backstage-app-1:     at async main (/app/packages/backend/dist/index.cjs.js:288:28)
```

### 👟 Reproduction steps

1. Configure app with the [aws elasticsearch search options](https://backstage.io/docs/features/search/search-engines#aws).
2. Add `clientOptions` between `elasticsearch` and `provider`.
3. Start App

### 🖥️ Your Environment

```
➜ yarn backstage-cli info
yarn run v1.22.19
$ /Users/brendan.vinson/Projects/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.1.0 - darwin/arm64
node: v20.9.0
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.0

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-api-docs                                       0.10.0
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.4.1
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.0
  @backstage/plugin-catalog-import                                 0.10.2
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.0
  @backstage/plugin-catalog                                        1.15.0
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.7
  @backstage/plugin-kafka-backend                                  0.3.5
  @backstage/plugin-kafka                                          0.3.26
  @backstage/plugin-nomad-backend                                  0.1.9
  @backstage/plugin-nomad                                          0.1.7
  @backstage/plugin-org                                            0.6.16
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.0
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.0
  @backstage/plugin-scaffolder                                     1.16.0
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-elasticsearch            1.3.10
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.2
  @backstage/plugin-sonarqube-backend                              0.2.9
  @backstage/plugin-sonarqube-react                                0.1.10
  @backstage/plugin-sonarqube                                      0.7.8
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.0
  @backstage/plugin-user-settings                                  0.7.12
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 0.79s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by sennyeya** [comment]
@backstage/discoverability-maintainers This seems like an issue with the current config schema. The [tests](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-elasticsearch/src/engines/ElasticSearchSearchEngine.test.ts#L905) are checking for a root level `node` value, but the schema requires it defined in `clientOptions`.

**Comment by emmaindal** [comment]
Hello, thanks for opening this issue. If I read the config schema correctly it says `clientOptions` is optional for any client [AND the rest of the client specific config](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-elasticsearch/config.d.ts#L83), so in your case, if you want to use it you can do something like: 

```
elasticsearch:
    provider: aws
    node: https://vpc-backstage-aaabbbccc.us-east-1.es.amazonaws.com
    clientOptions:
       .....
```

**Comment by schematis** [comment]
Yes, the definition file is correct, however per the link in the op, the app-config.json file stored on the json schema store file is not, which when using a schema aware editor (for instance, intellij) it shows as below:

![screenshot](https://github.com/backstage/backstage/assets/43475734/ae0971e1-41ff-45f9-85f6-bfbcf7f8f1e1)

Here is the appropriate section of the json schema:

```json
"clientOptions": {
              "description": "Miscellaneous options for the client",
              "anyOf": [
                {
                  "type": "object",
                  "properties": {
                    "ssl": {
                      "type": "object",
                      "properties": {
                        "rejectUnauthorized": {
                          "description": "If true the server will reject any connection which is not\nauthorized with the list of supplied CAs.",
                          "default": true,
                          "type": "boolean"
                        }
                      }
                    },
                    "provider": {
                      "type": "string",
                      "enum": ["elastic"]
                    },
                    "cloudId": {
                      "description": "Elastic.co CloudID\nSee: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-connecting.html#authentication",
                      "type": "string"
                    },
                    "auth": {
                      "type": "object",
                      "properties": {
                        "username": {
                          "type": "string"
                        },
                        "password": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                {
                  "type": "object",
                  "properties": {
                    "ssl": {
                      "type": "object",
                      "properties": {
                        "rejectUnauthorized": {
                          "description": "If true the server will reject any connection which is not\nauthorized with the list of supplied CAs.",
                          "default": true,
                          "type": "boolean"
                        }
                      }
                    },
                    "provider": {
                      "type": "string",
                      "enum": ["aws"]
                    },
                    "node": {
                      "description": "Node configuration.\nURL AWS ES endpoint to connect to.\nEg. https://my-es-cluster.eu-west-1.es.amazonaws.com",
                      "type": "string"
                    }
                  }
                },
                {
                  "type": "object",
                  "properties": {
                    "ssl": {
                      "type": "object",
                      "properties": {
                        "rejectUnauthorized": {
                          "description": "If true the server will reject any connection which is not\nauthorized with the list of supplied CAs.",
                          "default": true,
                          "type": "boolean"
                        }
                      }
                    },
                    "node": {
                      "description": "Node configuration.\nURL/URLS to ElasticSearch node to connect to.\nEither direct URL like 'https://localhost:9200' or with credentials like 'https://username:password@localhost:9200'",
                      "anyOf": [
                        {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        {
                          "type": "string"
                        }
                      ]
                    },
                    "auth": {
                      "description": "Authentication credentials for ElasticSearch\nIf both ApiKey/Bearer token and username+password is provided, tokens take precedence",
                      "anyOf": [
                        {
                          "type": "object",
                          "properties": {
                            "username": {
                              "type": "string"
                            },
                            "password": {
                              "type": "string"
                            }
                          }
                        },
                        {
                          "type": "object",
                          "properties": {
                            "apiKey": {
                              "description": "Base64 Encoded API key to be used to connect to the cluster.\nSee: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html",
                              "type": "string"
                            }
                          }
                        }
                      ]
                    }
                  }
                },
                {
                  "type": "object",
                  "properties": {
                    "ssl": {
                      "type": "object",
                      "properties": {
                        "rejectUnauthorized": {
                          "description": "If true the server will reject any connection which is not\nauthorized with the list of supplied CAs.",
                          "default": true,
                          "type": "boolean"
                        }
                      }
                    },
                    "provider": {
                      "type": "string",
                      "enum": ["opensearch"]
                    },
                    "node": {
                      "description": "Node configuration.\nURL/URLS to OpenSearch node to connect to.\nEither direct URL like 'https://localhost:9200' or with credentials like 'https://username:password@localhost:9200'",
                      "anyOf": [
                        {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        {
                          "type": "string"
                        }
                      ]
                    },
                    "auth": {
                      "description": "Authentication credentials for OpenSearch\nIf both ApiKey/Bearer token and username+password is provided, tokens take precedence",
                      "anyOf": [
                        {
                          "type": "object",
                          "properties": {
                            "username": {
                              "type": "string"
                            },
                            "password": {
                              "type": "string"
                            }
                          }
                        },
                        {
                          "type": "object",
                          "properties": {
                            "apiKey": {
                              "type": "string"
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              ]
            }
```

**Comment by freben** [comment]
@schematis Oh it's in schemastore ... well that explains it. We were not involved in putting anything in schemastore, and have no idea how it even ended up there or how it'd be updated or whatnot. It's a third party and you would be well adviced to completely forget about its existence, or conversely, if you find out what happened and whether there's something that can be done about it, we'd like to hear about it. I'd honestly prefer if it were removed because it's a constant source of confusion. The thing about the config is, everybody has different sets of config and setups, so there's little sense in having a centrally stored one in the first place.

**Comment by schematis** [comment]
@freben It looks like what's needed is a pr to https://github.com/SchemaStore/schemastore with the config change.

**Comment by emmaindal** [comment]
Thank you @freben I wasn't aware of this 😬 makes sense!

**Comment by sennyeya** [comment]
@emmaindal I don't think this is the case, the schema for the search plugin is incorrect. `clientOptions` must be the parent of `node`, but we expect `node` as a root key on `elasticsearch` in the code itself. If I create a fake `plugins/search-backend-module-elasticsearch/index.ts` with the following content,
```
import { Config } from "./config";

export const test: Config = {
    search: {
        elasticsearch: {
            clientOptions: {
                node: 'test'
            }
        }
    }
}
```
I don't get type errors, but 
```
import { Config } from "./config";

export const test: Config = {
    search: {
        elasticsearch: {
            node: 'test'
        }
    }
}
```
does.
