### ISSUE TITLE
🐛 Bug Report: Typescript 5.3 causes config-schema-generator to fail to find @backstage/cli's tsconfig.json

### ISSUE THREAD

**Issue by mitchhentgesspotify** [backstage/backstage#21448]
### 📜 Description

I run `yarn build:all` (the underlying failing command is `config-schema-generator`).
The underlying issue [is here in `ts-node`](https://github.com/TypeStrong/ts-node/issues/2076), but I wanted to save the time of people who are checking Backstage's issue tracker first.

### 👍 Expected behavior

Not fail

### 👎 Actual Behavior with Screenshots

```
yarn config-schema-generator
/Users/mhentges/dev/my-backstage/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '@backstage/cli/config/tsconfig.json' not found.

    at createTSError (/Users/mhentges/dev/my-backstage/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/mhentges/dev/my-backstage/node_modules/ts-node/src/index.ts:863:19)
    at createFromPreloadedConfig (/Users/mhentges/dev/my-backstage/node_modules/ts-node/src/index.ts:874:36)
    at create (/Users/mhentges/dev/my-backstage/node_modules/ts-node/src/index.ts:624:10)
    at Object.register (/Users/mhentges/dev/my-backstage/node_modules/ts-node/src/index.ts:591:15)
    at Object.<anonymous> (/Users/mhentges/dev/my-backstage/packages/config-schema-generator/bin/config-schema-generator:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12) {
  diagnosticCodes: [ 6053 ]
}

```

### 👟 Reproduction steps

1. Upgrade your Backstage project's `package.json` to have `"typescript": "~5.3.0"`

### 📃 Provide the context for the Bug.

The workaround is likely going to be to update `ts-node` in your project once they release a fix.

### 🖥️ Your Environment

```
OS:   Darwin 23.1.0 - darwin/arm64
node: v18.16.0
yarn: 3.7.0
cli:  0.24.0 (installed)
backstage:  1.20.1
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Looks like this should now be fixed upstream: https://github.com/microsoft/TypeScript/issues/53314
