### ISSUE TITLE
🐛 Bug Report: Code coverage plugin returns InputError: Unable to parse body as jacoco

### ISSUE THREAD

**Issue by polarp** [backstage/backstage#21620]
### 📜 Description

Hello everyone, I'm running a local instance of backstage version `1.3.0` and I installed and enabled the `@backstage/plugin-code-coverage:0.2.20` and `@backstage/plugin-code-coverage-backend:0.2.21`.

When I try to post a jacoco report I get the following response:

`curl -X POST -H "Content-Type:text/xml" -d @jacoco.xml http://localhost:7000/api/code-coverage/report?entity=component:default/test-component&coverageType=jacoco`

```json
{
    "error": {
        "name": "InputError",
        "message": "Unable to parse body as jacoco",
        "stack": "../node_modules/@backstage/plugin-code-coverage-backend/dist/index.cjs.js:567\n      throw new errors.InputError(`Unable to parse body as ${coverageType}`);\n            ^\n\nInputError: Unable to parse body as jacoco\n    at null.<anonymous> (../developer-portal/node_modules/@backstage/plugin-code-coverage-backend/dist/index.cjs.js:567:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
    },
    "request": {
        "method": "POST",
        "url": "/report?entity=component:default/test-component&coverageType=jacoco"
    },
    "response": {
        "statusCode": 400
    }
}
```
The entity that I am trying to publish the report for has the following annotations:
```
    backstage.io/code-coverage: enabled
    backstage.io/techdocs-ref: url:https://github.com/<org>/<repo>
 ```
  
I tried different jacoco reports (even the ones from the tests in the plugin), tried with postman too but I always get the same error so I am not really sure what am I doing wrong or is this some kind of bug in the plugin itself.

### 👍 Expected behavior

I guess the expected behavior would be to successfully be able to post a jacoco report for a given entity.

### 👎 Actual Behavior with Screenshots

```json
{
    "error": {
        "name": "InputError",
        "message": "Unable to parse body as jacoco",
        "stack": "../node_modules/@backstage/plugin-code-coverage-backend/dist/index.cjs.js:567\n      throw new errors.InputError(`Unable to parse body as ${coverageType}`);\n            ^\n\nInputError: Unable to parse body as jacoco\n    at null.<anonymous> (../developer-portal/node_modules/@backstage/plugin-code-coverage-backend/dist/index.cjs.js:567:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
    },
    "request": {
        "method": "POST",
        "url": "/report?entity=component:default/test-component&coverageType=jacoco"
    },
    "response": {
        "statusCode": 400
    }
}
```

### 👟 Reproduction steps

1. Install and enable `@backstage/plugin-code-coverage:0.2.20` and `@backstage/plugin-code-coverage-backend:0.2.21`.
2. Register a test entity and set the correct annotations
```
    backstage.io/code-coverage: enabled
    backstage.io/techdocs-ref: url:https://github.com/<org>/<repo>
 ```
 3. Try to publish a jacoco report 
 `curl -X POST -H "Content-Type:text/xml" -d @<path/to/jacoco/report.xml> http://localhost:7000/api/code-coverage/report?entity=component:default/<component>&coverageType=jacoco`

### 📃 Provide the context for the Bug.

I want to try and publish a jacoco report for a given entity.

### 🖥️ Your Environment

```
$ yarn backstage-cli info


OS:   Linux 6.2.16-1-MANJARO - linux/x64
node: v16.14.2
yarn: 3.2.3
cli:  0.24.0 (installed)
backstage:  1.20.2

Dependencies:
@backstage/app-defaults                                1.4.5
@backstage/backend-app-api                             0.5.8
@backstage/backend-common                              0.19.9
@backstage/backend-dev-utils                           0.1.2
@backstage/backend-openapi-utils                       0.1.0
@backstage/backend-plugin-api                          0.6.7
@backstage/backend-tasks                               0.5.12
@backstage/backend-test-utils                          0.2.8
@backstage/catalog-client                              1.4.6
@backstage/catalog-model                               1.4.3
@backstage/cli-common                                  0.1.13
@backstage/cli-node                                    0.2.0
@backstage/cli                                         0.24.0
@backstage/codemods                                    0.1.46
@backstage/config-loader                               1.5.3
@backstage/config                                      1.1.1
@backstage/core-app-api                                1.11.1
@backstage/core-components                             0.13.8
@backstage/core-plugin-api                             1.8.0
@backstage/create-app                                  0.5.7
@backstage/dev-utils                                   1.0.23
@backstage/errors                                      1.2.3
@backstage/eslint-plugin                               0.1.3
@backstage/frontend-plugin-api                         0.3.0
@backstage/integration-aws-node                        0.1.8
@backstage/integration-react                           1.1.21
@backstage/integration                                 1.7.2
@backstage/plugin-analytics-module-ga4                 0.1.6
@backstage/plugin-analytics-module-ga                  0.1.35
@backstage/plugin-api-docs                             0.10.0
@backstage/plugin-app-backend                          0.3.55
@backstage/plugin-app-node                             0.1.7
@backstage/plugin-auth-backend-module-gcp-iap-provider 0.2.1
@backstage/plugin-auth-backend-module-github-provider  0.1.4
@backstage/plugin-auth-backend-module-gitlab-provider  0.1.4
@backstage/plugin-auth-backend-module-google-provider  0.1.4
@backstage/plugin-auth-backend-module-oauth2-provider  0.1.4
@backstage/plugin-auth-backend                         0.20.0
@backstage/plugin-auth-node                            0.4.1
@backstage/plugin-badges-backend                       0.3.4
@backstage/plugin-badges                               0.2.50
@backstage/plugin-catalog-backend-module-github        0.4.5
@backstage/plugin-catalog-backend-module-unprocessed   0.3.4
@backstage/plugin-catalog-backend                      1.15.0
@backstage/plugin-catalog-common                       1.0.18
@backstage/plugin-catalog-graph                        0.3.0
@backstage/plugin-catalog-graphql                      0.4.1
@backstage/plugin-catalog-import                       0.10.2
@backstage/plugin-catalog-node                         1.5.0
@backstage/plugin-catalog-react                        1.9.0, 1.9.1
@backstage/plugin-catalog-unprocessed-entities         0.1.5
@backstage/plugin-catalog                              1.15.0
@backstage/plugin-cloudbuild                           0.3.26
@backstage/plugin-code-coverage-backend                0.2.21
@backstage/plugin-code-coverage                        0.2.20
@backstage/plugin-events-node                          0.2.16
@backstage/plugin-gcp-projects                         0.3.43
@backstage/plugin-github-actions                       0.6.7
@backstage/plugin-github-deployments                   0.1.57
@backstage/plugin-github-pull-requests-board           0.1.20
@backstage/plugin-graphiql                             0.3.0
@backstage/plugin-graphql-backend                      0.2.1
@backstage/plugin-graphql-voyager                      0.1.9
@backstage/plugin-home-react                           0.1.5
@backstage/plugin-ilert                                0.2.15
@backstage/plugin-kubernetes-backend                   0.13.1
@backstage/plugin-kubernetes-common                    0.7.1
@backstage/plugin-kubernetes-node                      0.1.1
@backstage/plugin-kubernetes-react                     0.1.1
@backstage/plugin-kubernetes                           0.11.1
@backstage/plugin-org                                  0.6.16
@backstage/plugin-permission-backend                   0.5.30
@backstage/plugin-permission-common                    0.7.10
@backstage/plugin-permission-node                      0.7.18
@backstage/plugin-permission-react                     0.4.17
@backstage/plugin-proxy-backend                        0.4.5
@backstage/plugin-scaffolder-common                    1.4.3
@backstage/plugin-search-backend-module-catalog        0.1.11
@backstage/plugin-search-backend-module-elasticsearch  1.3.10
@backstage/plugin-search-backend-module-pg             0.5.16
@backstage/plugin-search-backend-module-techdocs       0.1.11
@backstage/plugin-search-backend-node                  1.2.11
@backstage/plugin-search-backend                       1.4.7
@backstage/plugin-search-common                        1.2.8
@backstage/plugin-search-react                         1.7.3
@backstage/plugin-search                               1.4.2
@backstage/plugin-sentry                               0.5.11
@backstage/plugin-shortcuts                            0.3.16
@backstage/plugin-sonarqube-react                      0.1.10
@backstage/plugin-sonarqube                            0.7.8
@backstage/plugin-tech-insights-backend-module-jsonfc  0.1.39
@backstage/plugin-tech-insights-backend                0.5.21
@backstage/plugin-tech-insights-common                 0.2.12
@backstage/plugin-tech-insights-node                   0.4.13
@backstage/plugin-tech-insights                        0.3.18
@backstage/plugin-tech-radar                           0.6.10
@backstage/plugin-techdocs-backend                     1.9.0
@backstage/plugin-techdocs-module-addons-contrib       1.1.2
@backstage/plugin-techdocs-node                        1.10.0
@backstage/plugin-techdocs-react                       1.1.13
@backstage/plugin-techdocs                             1.9.0
@backstage/plugin-todo-backend                         0.3.5
@backstage/plugin-todo                                 0.2.30
@backstage/plugin-user-settings-backend                0.2.6
@backstage/plugin-user-settings                        0.7.12
@backstage/release-manifests                           0.0.11
@backstage/repo-tools                                  0.4.0
@backstage/test-utils                                  1.4.5
@backstage/theme                                       0.4.4
@backstage/types                                       1.1.1
@backstage/version-bridge                              1.0.7
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tudi2d** [comment]
Hej @alde - are you up for guiding @polarp here to create a PR? :)

**Comment by alde** [comment]
sorry for the delay!

I'd suggest trying to make as small of a failing jacoco file as possible, and add it as a test fixture and see what's actually failing

**Comment by polarp** [comment]
Hi guys, it's been a while but I finally found some time to take a look at the issue again. 

@alde Just to make sure that I understand correctly what I need to do is to try and add a failing test? I've managed to to that with the sample files already provided in the plugin fixtures. The test is simple and it looks like:

```
    it('returns error when posting jacoco', async () => {
        const buff = fs.readFileSync(
          path.resolve(__dirname, '__fixtures__/jacoco-testdata-1.xml'),
        );

        const response = await request(app)
        .post('/report?entity=component:default/mycomponent&coverageType=jacoco')
        .set('Content-Type', 'text/xml')
        .send(
          buff.toString(),
        );
        expect(response.status).toBe(201);      
    });
```

From what I was able to  understand is that the error is coming from the following code in the router:

```
    const { sourceLocation, vcs, scmFiles, body } =
      await utils.processCoveragePayload(entity, req);

    const files = converter.convert(body, scmFiles);
    if (!files || files.length === 0) {
      throw new InputError(`Unable to parse body as ${coverageType}`);
    }
```
So I think the issue is in the `processCoveragePayload` function since the converter already has tests with the same test data and it looks like they are passing. 

Thoughts and next steps?

**Comment by alde** [comment]
ok so I think the issue is in the jacoco converter, it seems to only work if you have the configuration set to scm-only.

Fix PR incoming.

**Comment by polarp** [comment]
Awesome, thanks everyone for the support!
