### ISSUE TITLE
🐛 Bug Report: GitHub Actions CI and AWS S3 with OIDC?

### ISSUE THREAD

**Issue by sramekmichal** [backstage/backstage#21630]
### 📜 Description

I want to implement this: https://backstage.io/docs/features/techdocs/configuring-ci-cd/#example-github-actions-ci-and-aws-s3

Since using AWS Credentials is prohibited and not best secure practice to share it with everybody in the GitHub Organisation, I wanted to use OIDC.

So my env in github workflow looks like this:
```
jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    env:
      TECHDOCS_S3_BUCKET_NAME: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
      role-to-assume: ${{ secrets.AWS_ARN_ROLE }}
      role-session-name: ${{ secrets.AWS_SESSION }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ENTITY_NAMESPACE: 'default'
      ENTITY_KIND: 'Component'
      ENTITY_NAME: 'my-doc-entity'
```

### 👍 Expected behavior

I was thinking, that would assume role and it would be enough to publish the TechDocs site.

Unfortunately, It works only with AWS Credentials:
```
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

### 👎 Actual Behavior with Screenshots

Using OIDC it throws the following error:
```
Run techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
info: Creating AWS S3 Bucket publisher for TechDocs
error: Could not retrieve metadata about the AWS S3 bucket <my-bucket-name>. Make sure the bucket exists. Also make sure that authentication is setup either by explicitly defining credentials and region in techdocs.publisher.awsS3 in app config or by using environment variables. Refer to https://backstage.io/docs/features/techdocs/using-cloud-storage
error: from AWS client library Could not load credentials from any providers {"$metadata":{"attempts":1,"totalRetryDelay":0},"name":"CredentialsProviderError","stack":"CredentialsProviderError: Could not load credentials from any providers\n    at /usr/local/lib/node_modules/@techdocs/cli/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11\n    at /usr/local/lib/node_modules/@techdocs/cli/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async coalesceProvider (/usr/local/lib/node_modules/@techdocs/cli/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)\n    at async SignatureV4S3Express.credentialProvider (/usr/local/lib/node_modules/@techdocs/cli/node_modules/@smithy/property-provider/dist-cjs/memoize.js:33:24)\n    at async SignatureV4S3Express.signRequest (/usr/local/lib/node_modules/@techdocs/cli/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:106:29)\n    at async /usr/local/lib/node_modules/@techdocs/cli/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:28:25\n    at async /usr/local/lib/node_modules/@techdocs/cli/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46\n    at async /usr/local/lib/node_modules/@techdocs/cli/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24\n    at async /usr/local/lib/node_modules/@techdocs/cli/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:[20](https://github.com/almacareer/test-entity-ci/actions/runs/7032382126/job/19136001038#step:8:21)","tryNextLink":false}
```

### 👟 Reproduction steps

See Description 🔝 

### 📃 Provide the context for the Bug.

I want to use OIDC with this workflow and not use sharable AWS credentials (not safe and prohibited in our organization).

### 🖥️ Your Environment

GitHub workflow.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sramekmichal** [comment]
It seems I solved by adding `aws-actions/configure-aws-credentials@v3` step and token permission to the workflow with OIDC.

The full workflow looks like this:
```
name: Publish TechDocs Site

on:
  push:
    branches: [master]
    # You can even set it to run only when TechDocs related files are updated.
    paths:
     - "docs/**"
     - "mkdocs.yml"

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    env:
      TECHDOCS_S3_BUCKET_NAME: 'devhub-backstage-development-stable--documentation-00a'
      AWS_REGION: eu-west-1
      ENTITY_NAMESPACE: 'default'
      ENTITY_KIND: 'Component'
      ENTITY_NAME: 'my-doc-entity'

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ARN_ROLE }}
          role-session-name: ${{ secrets.AWS_SESSION }}
          aws-region: eu-west-1
          
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
```

And it works like a charm!
