### ISSUE TITLE
🐛 Bug Report: scaffolder-backend-module-confluence-to-markdown action fails if confluence page title contains special characters

### ISSUE THREAD

**Issue by luca-ballerini** [backstage/backstage#21736]
### 📜 Description

When running the action, if the page title contains any of the following `) ( , / [ ] ' :` the execution will fail at the stage where the action tries to fetch the page here -> https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend-module-confluence-to-markdown/src/actions/confluence/confluenceToMarkdown.ts#L110

### 👍 Expected behavior

Submitting a valid confluence URL should convert the page and generate a PR

### 👎 Actual Behavior with Screenshots

When the page title contains special characters, the page conversion fails:

Sample URL:
`https://squarespace.atlassian.net/wiki/spaces/REL/pages/38386107403/FAQ+In+30+Mins+Or+Less+Or+The+Deploy+s+Free`
Actual page title:
`FAQ: In 30 Mins Or Less, Or The Deploy's Free`

Output:
```
2023-12-01T11:05:26.537Z InputError: Could not find document https://squarespace.atlassian.net/wiki/spaces/REL/pages/38386107403/FAQ+In+30+Mins+Or+Less+Or+The+Deploy+s+Free. Please check your input.
    5 at Object.handler (/usr/src/app/node_modules/@backstage/plugin-scaffolder-backend-module-confluence-to-markdown/dist/index.cjs.js:227:17)6    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)7       at async NunjucksWorkflowRunner.executeStep (/usr/src/app/packages/backend/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-68c854a3.cjs.js:7233:9)8    at async NunjucksWorkflowRunner.execute (/usr/src/app/packages/backend/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-68c854a3.cjs.js:7306:9)9    at async TaskWorker.runOneTask (/usr/src/app/packages/backend/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-68c854a3.cjs.js:7528:26)10    at async run (/usr/src/app/node_modules/p-queue/dist/index.js:163:29)
```

### 👟 Reproduction steps

1. Create a page in confluence where the title contains one of the following chars ) ( , / [ ] ' :
2. Use the URL of the newly created page with the action

### 📃 Provide the context for the Bug.

A simple alternative that would help mitigate the error would be to get as input instead of the url with the page title, only the page ID. For example:
This URL -> https://squarespace.atlassian.net/wiki/rest/api/content?id={id}&expand=body.export_view
Will return the same as https://squarespace.atlassian.net/wiki/rest/api/content?title=${title}&spaceKey=${spacekey}&expand=body.export_view

### 🖥️ Your Environment

```
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.17.1
yarn: 1.22.19
cli:  0.23.1 (installed)
backstage:  1.19.5

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.7
  @backstage/backend-common                                        0.19.8
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6
  @backstage/backend-tasks                                         0.5.11
  @backstage/catalog-client                                        1.4.5
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.22.14, 0.23.1
  @backstage/config-loader                                         1.5.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.11.2, 0.12.5, 0.13.6
  @backstage/core-plugin-api                                       1.7.0
  @backstage/dev-utils                                             1.0.22
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.4
  @backstage/plugin-auth-node                                      0.4.0
  @backstage/plugin-catalog-backend-module-github                  0.4.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-events-backend-module-github                   0.1.16
  @backstage/plugin-events-backend                                 0.2.15
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.32
  @backstage/plugin-explore                                        0.4.11
  @backstage/plugin-gcalendar                                      0.3.19
  @backstage/plugin-github-actions                                 0.6.6
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-home-react                                     0.1.4
  @backstage/plugin-home                                           0.5.9
  @backstage/plugin-kubernetes-backend                             0.13.0
  @backstage/plugin-kubernetes-common                              0.7.0
  @backstage/plugin-kubernetes-node                                0.1.0
  @backstage/plugin-kubernetes-react                               0.1.0
  @backstage/plugin-kubernetes                                     0.11.0
  @backstage/plugin-lighthouse-common                              0.1.4
  @backstage/plugin-lighthouse                                     0.4.10
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-pagerduty                                      0.6.6
  @backstage/plugin-permission-common                              0.7.9
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.4
  @backstage/plugin-scaffolder-backend                             1.18.1
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.7
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-sonarqube-backend                              0.2.8
  @backstage/plugin-sonarqube-react                                0.1.9
  @backstage/plugin-sonarqube                                      0.7.7
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/plugin-xcmetrics                                      0.2.44
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.2.19, 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Thanks for raising this! Is this something that you would like to contribute a fix for? :pray:

**Comment by Thutm** [comment]
I created a page with special characters in my confluence. When linking to it within confluence it does direct you to use to the page id instead of a friendly URI as you pointed out: 

![image](https://github.com/backstage/backstage/assets/26581580/fcfe15d3-e92f-4723-9955-cd2a41145f2e)

If I URL encode the friendly url though (%5BTest%20Page%5D) confluence is able to route the page:
![image](https://github.com/backstage/backstage/assets/26581580/087ef610-738a-481f-8e66-ba1488fd4e0b)

API responds similarly.. would URL encoding previous to the fetch request be a reasonable/friction-less modification here? Or maybe I don't understand the failure setup you have. I would have expected the URL to either be in the confluence pageid format or attempt to url encode it. The sample URL seems to be missing the : altogether based on the title. Perhaps there is a setting in confluence for that I am missing.

**Comment by luca-ballerini** [comment]
@Thutm I did some testing and it seems the issue is caused indeed by a confluence behaviour. By the look of things, not something we have implemented as custom extension but the URL of our pages displayed in the browser is different from the URL in the webui field.

for example:
Page TItle: `FAQ: In 30 Mins Or Less, Or The Deploy's Free`
URL in Browser: `/FAQ+In+30+Mins+Or+Less+Or+The+Deploy+s+Free`
URL from `webui` field in json version of the page: `/FAQ%3A+In+30+Mins+Or+Less%2C+Or+The+Deploy%27s+Free`

The one in webui has the correct encoding, but there must be some feature in Confluence that generates a more human readable URL for the browser.

I think at this point this issue should no longer be considered a bug, since the action does the conversion correctly when the right input is provided.

I'd still like to send some sort of feature request where we can pass as input the pageID that seems a more consistent parameter.

**Comment by Thutm** [comment]
Its interesting that confluence would interpret and display the pretty URI to user but API doesn't understand how to make the same connection. I agree though if that is the behavior likely easiest to give backstage users the option to submit a pageid instead, at leas they could self resolve when they run into this case. Confluence seems to force the pageid URI anyway if the page title is complex enough (i.e. includes other special characters I guess?).
