### ISSUE TITLE
🐛 Bug Report: Node 18.19.0: stopping and restarting server causes "fetch failed"

### ISSUE THREAD

**Issue by mitchhentgesspotify** [backstage/backstage#21888]
### 📜 Description

This worked in Node 18.18.2 but is now failing in 18.19.0.
[I've reported the issue upstream here](https://github.com/nodejs/node/issues/51165).

### 👍 Expected behavior

If I've `await`-d `backend.start()`, then the server should be ready for `fetch` requests.

See the behaviour with 18.18.2:

```
Listening on :7007 undefined
Running 0 startup tasks... undefined
::1 - - [15/Dec/2023:13:41:44 +0000] "GET / HTTP/1.1" 404 - "-" "node" undefined
Running 1 shutdown tasks... undefined
Shutdown hook succeeded undefined
Listening on :7007 undefined
Running 0 startup tasks... undefined
::1 - - [15/Dec/2023:13:41:44 +0000] "GET / HTTP/1.1" 404 - "-" "node" undefined
Running 1 shutdown tasks... undefined
Shutdown hook succeeded undefined
done

```

### 👎 Actual Behavior with Screenshots

```
Listening on :7007 undefined
Running 0 startup tasks... undefined
::1 - - [15/Dec/2023:13:41:29 +0000] "GET / HTTP/1.1" 404 - "-" "node" undefined
Running 1 shutdown tasks... undefined
Shutdown hook succeeded undefined
Listening on :7007 undefined
Running 0 startup tasks... undefined
Unhandled rejection TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at async runServerAndFetch (/Users/mhentges/dev/backstage-quickstart/node.js:48:3)
    at async main (/Users/mhentges/dev/backstage-quickstart/node.js:54:3) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -54,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
Unhandled rejection TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at async runServerAndFetch (/Users/mhentges/dev/backstage-quickstart/node.js:48:3)
    at async main (/Users/mhentges/dev/backstage-quickstart/node.js:54:3) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -54,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}

```

### 👟 Reproduction steps

Use the following script:
```
const { createBackend } = require('@backstage/backend-defaults');
const {
  coreServices,
  createServiceFactory,
} = require('@backstage/backend-plugin-api');
const { mockServices } = require('@backstage/backend-test-utils');

class MockRootLoggerService {
  error(message, meta) {
    console.log(message, meta);
  }

  warn(message, meta) {
    console.log(message, meta);
  }

  info(message, meta) {
    console.log(message, meta);
  }

  debug(message, meta) {
    console.log(message, meta);
  }

  child(meta) {
    return new MockRootLoggerService();
  }
}

const runServerAndFetch = async () => {
  const backend = createBackend();
  backend.add(
    createServiceFactory(() => ({
      service: coreServices.rootLogger,
      deps: { config: coreServices.rootConfig },
      async factory() {
        // await new Promise(resolve => setTimeout(() => resolve(1)));
        return new MockRootLoggerService();
      },
    })),
  );
  backend.add(
    mockServices.rootConfig.factory({
      data: {},
    }),
  );
  await backend.start();
  await fetch(`http://localhost:7007`);
  await backend.stop();
};

const main = async () => {
  await runServerAndFetch();
  await runServerAndFetch();
  console.log('done');
};

main();

```

### 📃 Provide the context for the Bug.

I encountered this in the tests for our Backstage app. We restart the backend between every test, and it's causing the second test's `fetch` to fail because, despite the server _appearing_ online, initial requests are failing.

Note that part of this issue is due to [`stoppable`](https://github.com/hunterloftis/stoppable), [which is doing some weird stuff with timeouts and callbacks](https://github.com/hunterloftis/stoppable/blob/master/lib/stoppable.js#L40)

### 🖥️ Your Environment

```
OS:   Darwin 23.2.0 - darwin/arm64
node: v18.19.0
yarn: 3.7.0
cli:  0.25.0-next.3 (installed)
backstage:  1.21.0-next.4

Dependencies:
  @backstage/app-defaults                                     1.4.6-next.3
  @backstage/backend-app-api                                  0.5.8
  @backstage/backend-common                                   0.19.5-next.3
  @backstage/backend-defaults                                 0.2.8-next.3
  @backstage/backend-dev-utils                                0.1.2
  @backstage/backend-openapi-utils                            0.1.1-next.3
  @backstage/backend-plugin-api                               0.6.7, 0.6.8-next.3
  @backstage/backend-tasks                                    0.5.12, 0.5.13-next.3
  @backstage/backend-test-utils                               0.2.9-next.3
  @backstage/catalog-client                                   1.4.6, 1.5.0-next.1
  @backstage/catalog-model                                    1.4.3
  @backstage/cli-common                                       0.1.13
  @backstage/cli-node                                         0.2.0
  @backstage/cli                                              0.25.0-next.3
  @backstage/config-loader                                    1.5.3, 1.6.0-next.0
  @backstage/config                                           1.1.1
  @backstage/core-app-api                                     1.11.2-next.1
  @backstage/core-compat-api                                  0.1.0-next.3
  @backstage/core-components                                  0.13.9-next.3
  @backstage/core-plugin-api                                  1.8.1-next.1
  @backstage/dev-utils                                        1.0.25-next.3
  @backstage/errors                                           1.2.3
  @backstage/eslint-plugin                                    0.1.4-next.0
  @backstage/frontend-app-api                                 0.4.0-next.3
  @backstage/frontend-plugin-api                              0.4.0-next.3
  @backstage/integration-aws-node                             0.1.8
  @backstage/integration-react                                1.1.22-next.1
  @backstage/integration                                      1.7.2, 1.8.0-next.1
  @backstage/plugin-api-docs                                  0.10.2-next.4
  @backstage/plugin-app-backend                               0.3.56-next.3
  @backstage/plugin-app-node                                  0.1.8-next.3
  @backstage/plugin-auth-backend-module-atlassian-provider    0.1.0-next.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider      0.2.2-next.3
  @backstage/plugin-auth-backend-module-github-provider       0.1.5-next.3
  @backstage/plugin-auth-backend-module-gitlab-provider       0.1.5-next.3
  @backstage/plugin-auth-backend-module-google-provider       0.1.5-next.3
  @backstage/plugin-auth-backend-module-oauth2-provider       0.1.5-next.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider 0.1.0-next.2
  @backstage/plugin-auth-backend-module-okta-provider         0.0.1-next.3
  @backstage/plugin-auth-backend                              0.20.1-next.3
  @backstage/plugin-auth-node                                 0.4.1, 0.4.2-next.3
  @backstage/plugin-catalog-backend-module-github-org         0.1.2-next.3
  @backstage/plugin-catalog-backend-module-github             0.4.6-next.3
  @backstage/plugin-catalog-backend                           1.16.0-next.3
  @backstage/plugin-catalog-common                            1.0.18
  @backstage/plugin-catalog-graph                             0.3.2-next.3
  @backstage/plugin-catalog-import                            0.10.4-next.4
  @backstage/plugin-catalog-node                              1.6.0-next.3
  @backstage/plugin-catalog-react                             1.9.2-next.3
  @backstage/plugin-catalog                                   1.16.0-next.4
  @backstage/plugin-events-node                               0.2.17-next.3
  @backstage/plugin-org                                       0.6.18-next.3
  @backstage/plugin-permission-backend                        0.5.31-next.3
  @backstage/plugin-permission-common                         0.7.10
  @backstage/plugin-permission-node                           0.7.18, 0.7.19-next.3
  @backstage/plugin-permission-react                          0.4.18-next.1
  @backstage/plugin-scaffolder-common                         1.4.3
  @backstage/plugin-search-backend-module-catalog             0.1.12-next.3
  @backstage/plugin-search-backend-node                       1.2.12-next.3
  @backstage/plugin-search-common                             1.2.8
  @backstage/plugin-search-react                              1.7.4-next.3
  @backstage/plugin-user-settings                             0.7.14-next.4
  @backstage/release-manifests                                0.0.11
  @backstage/repo-tools                                       0.5.0-next.2
  @backstage/test-utils                                       1.4.6-next.2
  @backstage/theme                                            0.5.0-next.1
  @backstage/types                                            1.1.1
  @backstage/version-bridge                                   1.0.7
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by mitchhentgesspotify** [comment]
This can be worked around by delaying the execution of `fetch` by one event loop:
```
await backend.start();
await new Promise(res => setTimeout(res, 0));
```

**Comment by freben** [comment]
For some context, even though it may not quite be an excuse: I think it's fair to say that we intended `stop` to happen at system shutdown - not sure we originally intended for stop-and-then-start at all. If we can perform changes to make it work, then awesome. But in a way it's feature work :) Looking forward to seeing if a root cause for this can be found and fixed.
