### ISSUE TITLE
🐛Add 'demo.backstage.io' to allowed hosts in default configuration 'app-config.local.yaml'

### ISSUE THREAD

**Issue by jhuboo** [backstage/backstage#21932]
### 📜 Description

When following the tutorial at https://backstage.io/docs/getting-started/configuration#register-an-existing-component, I couldn't use the [URL listed](https://github.com/backstage/demo/blob/master/catalog-info.yaml) (which used by the demo site) by adding it and clicking on Analyze. 

It seems like the site is trying to read from https://demo.backstage.io/api/graphql/schema, and I encountered an error indicating that reading from this host is not allowed. The error message suggested adding the host to the allowed hosts in the 'backend.reading.allow' configuration.

### 👍 Expected behavior

I expected the backend to be able to read from demo.backstage.io by default.

## Proposed Solution

I suggest adding 'demo.backstage.io' to the allowed hosts in the default configuration. This can be done by adding the following lines to the `app-config.local.yaml` file:

```yaml
backend:
  reading:
    allow:
      - host: 'demo.backstage.io'
```

This configuration would allow the Backstage backend to read from 'demo.backstage.io'. If there are other hosts that users commonly use, the docs can also hint for them be added to the allowed hosts.

### 👎 Actual Behavior with Screenshots

Here's the error message for reference:

```
{"error":{"name":"InputError","message":"InputError: Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location [https://demo.backstage.io/api/graphql/schema](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html "https://demo.backstage.io/api/graphql/schema"), NotAllowedError: Reading from '[https://demo.backstage.io/api/graphql/schema'](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html "https://demo.backstage.io/api/graphql/schema&#39;") is not allowed. You may need to configure an integration for the target host, or add it to the configured list of allowed hosts at 'backend.reading.allow'","stack":"InputError: InputError: Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location [https://demo.backstage.io/api/graphql/schema](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html "https://demo.backstage.io/api/graphql/schema"), NotAllowedError: Reading from '[https://demo.backstage.io/api/graphql/schema'](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html "https://demo.backstage.io/api/graphql/schema&#39;") is not allowed. You may need to configure an integration for the target host, or add it to the configured list of allowed hosts at 'backend.reading.allow'\n at DefaultLocationService.processEntities (/Users/agj/Workspace/backstage/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-2ff47757.cjs.js:2157:15)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at DefaultLocationService.dryRunCreateLocation (/Users/agj/Workspace/backstage/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-2ff47757.cjs.js:2188:22)\n at (/Users/agj/Workspace/backstage/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-2ff47757.cjs.js:5612:22)"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}
```

### 👟 Reproduction steps

Follow the steps outlined in https://backstage.io/docs/getting-started/configuration#register-an-existing-component,

1. Register a new component, by going to create and choose Register existing component
2. As URL use https://github.com/backstage/demo/blob/master/catalog-info.yaml. This is used by our [demo site](https://demo.backstage.io/).
3. Hit Analyze and review the changes. Apply them if correct.

Step 3 fails because reading from the URL in Step 2 is not allowed in the default `app-config.local.yaml`.

### 🖥️ Your Environment

Browser: Chrome Version 120.0.6099.109 (Official Build) (arm64)
Laptop: Macbook Pro M1 (2021)

```bash
$ yarn backstage-cli info
yarn run v1.22.21
$ /Users/agj/Workspace/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.2.0 - darwin/arm64
node: v20.10.0
yarn: 1.22.21
cli:  0.24.0 (installed)
backstage:  1.20.0

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.4.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.1
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.8
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 0.70s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Parsifal-M** [comment]
Hey! 👋 

Possibly, another proposed solution could be to update the docs saying something like add the following to your `app-config.yaml`?

```yaml
backend:
  reading:
    allow:
      - host: 'demo.backstage.io'
```

That way once you have tested it and are happy you can also remember to remove it 😅

**Comment by awanlin** [comment]
Hi, I have a PR to change this to use the `catalog-info.yaml` from this repo and not the Demo site: https://github.com/backstage/backstage/pull/21724. I don't think getting people to make these changes this early in their Backstage journey makes sense to me.

**Comment by jhuboo** [comment]
@awanlin, your PR looks good, and should resolve this issue. Cheers!

**Comment by netgio** [comment]
Resolved for backstage.io docs.... the Spotify team need to update https://backstage.spotify.com/learn/standing-up-backstage/putting-backstage-into-action/9-software-catalog/ to resolve the same issue for new users.
