### ISSUE TITLE
🐛 Bug Report: Scaffolder/Template: PullRequests for files at the root of the repo, and a blank "targetPath" result in "GithubResponseError: Pull request creation failed; caused by HttpError: Not Found"

### ISSUE THREAD

**Issue by bcotton** [backstage/backstage#21976]
### 📜 Description

With a template that creates a github pull-request at the end of the workflow, and `targetPath` is not specified, I get the following error:

```
2023-12-21T18:13:01.697Z GithubResponseError: Pull request creation failed; caused by HttpError: Not Found
  at Object.handler (/workspace/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-68c854a3.cjs.js:5525:15)
  at async NunjucksWorkflowRunner.executeStep (/workspace/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-68c854a3.cjs.js:7233:9)
  at async NunjucksWorkflowRunner.execute (/workspace/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-68c854a3.cjs.js:7306:9)
  at async TaskWorker.runOneTask (/workspace/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-68c854a3.cjs.js:7528:26)
  at async run (/workspace/node_modules/p-queue/dist/index.js:163:29)
```
For the same template, if `targetPath` is specified, the PR is created without error, but the files in the PR are rooted under the given `targetPath`.

However I don't want a `targetPath` as the files created in the PR are rooted at the root of the repo.

If there are instructions on how to import the scaffolder plugin into my backstage instance, I could debug further.

### 👍 Expected behavior

A PR was created without error, with the the files at the root of the repo.

### 👎 Actual Behavior with Screenshots

![CleanShot 2023-12-21 at 12 15 23@2x](https://github.com/backstage/backstage/assets/1392/27b263fe-8eb3-4ea4-bec7-671663b7a92f)

### 👟 Reproduction steps

Create a template that prompts the user for all the necessary github info (group/repo etc)
Create the skeleton with data that will be installed into the root of the repo.

### 📃 Provide the context for the Bug.

Trying to create a template that will issue PRs to add an existing project to the catalog, with techdocs etc.

### 🖥️ Your Environment

```
$ yarn backstage-cli info
yarn run v1.22.19
$ /workspace/node_modules/.bin/backstage-cli info
OS:   Linux 6.5.10-orbstack-00110-gbcfe04c86d2f - linux/arm64
node: v18.19.0
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.21.0

Dependencies:
  @backstage/app-defaults                                          1.4.6
  @backstage/backend-app-api                                       0.5.9
  @backstage/backend-common                                        0.20.0
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.1
  @backstage/backend-plugin-api                                    0.6.8
  @backstage/backend-tasks                                         0.5.13
  @backstage/catalog-client                                        1.5.0
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.1
  @backstage/cli                                                   0.25.0
  @backstage/config-loader                                         1.6.0
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.2
  @backstage/core-compat-api                                       0.1.0
  @backstage/core-components                                       0.13.9
  @backstage/core-plugin-api                                       1.8.1
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.4.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.22
  @backstage/integration                                           1.8.0
  @backstage/plugin-adr-backend                                    0.4.5
  @backstage/plugin-adr-common                                     0.2.18
  @backstage/plugin-adr                                            0.6.11
  @backstage/plugin-api-docs                                       0.10.2
  @backstage/plugin-app-backend                                    0.3.56
  @backstage/plugin-app-node                                       0.1.8
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.2
  @backstage/plugin-auth-backend-module-github-provider            0.1.5
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.5
  @backstage/plugin-auth-backend-module-google-provider            0.1.5
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.0
  @backstage/plugin-auth-backend-module-okta-provider              0.0.1
  @backstage/plugin-auth-backend                                   0.20.1
  @backstage/plugin-auth-node                                      0.4.2
  @backstage/plugin-catalog-backend-module-github                  0.4.6
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.5
  @backstage/plugin-catalog-backend                                1.16.0
  @backstage/plugin-catalog-common                                 1.0.19
  @backstage/plugin-catalog-graph                                  0.3.2
  @backstage/plugin-catalog-import                                 0.10.4
  @backstage/plugin-catalog-node                                   1.6.0
  @backstage/plugin-catalog-react                                  1.9.2
  @backstage/plugin-catalog                                        1.16.0
  @backstage/plugin-events-node                                    0.2.17
  @backstage/plugin-explore-backend                                0.0.18
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.34
  @backstage/plugin-explore                                        0.4.14
  @backstage/plugin-github-actions                                 0.6.9
  @backstage/plugin-github-pull-requests-board                     0.1.22
  @backstage/plugin-org                                            0.6.18
  @backstage/plugin-permission-common                              0.7.11
  @backstage/plugin-permission-node                                0.7.19
  @backstage/plugin-permission-react                               0.4.18
  @backstage/plugin-proxy-backend                                  0.4.6
  @backstage/plugin-scaffolder-backend-module-azure                0.1.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.0
  @backstage/plugin-scaffolder-backend-module-github               0.1.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.11
  @backstage/plugin-scaffolder-backend                             1.19.2
  @backstage/plugin-scaffolder-common                              1.4.4
  @backstage/plugin-scaffolder-node                                0.2.9
  @backstage/plugin-scaffolder-react                               1.7.0
  @backstage/plugin-scaffolder                                     1.17.0
  @backstage/plugin-search-backend-module-catalog                  0.1.12
  @backstage/plugin-search-backend-module-explore                  0.1.12
  @backstage/plugin-search-backend-module-pg                       0.5.17
  @backstage/plugin-search-backend-module-techdocs                 0.1.12
  @backstage/plugin-search-backend-node                            1.2.12
  @backstage/plugin-search-backend                                 1.4.8
  @backstage/plugin-search-common                                  1.2.9
  @backstage/plugin-search-react                                   1.7.4
  @backstage/plugin-search                                         1.4.4
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.40
  @backstage/plugin-tech-insights-backend                          0.5.22
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.14
  @backstage/plugin-tech-insights                                  0.3.20
  @backstage/plugin-techdocs-backend                               1.9.1
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.3
  @backstage/plugin-techdocs-node                                  1.11.0
  @backstage/plugin-techdocs-react                                 1.1.14
  @backstage/plugin-techdocs                                       1.9.2
  @backstage/plugin-user-settings                                  0.7.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.6
  @backstage/theme                                                 0.4.4, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
Done in 0.48s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by bcotton** [comment]
Reopening as we have some more findings (to follow)
