### ISSUE TITLE
🐛 Bug Report: Getting "Error: could not fetch catalog entities." error on browser

### ISSUE THREAD

**Issue by nileshgadgi** [backstage/backstage#22202]
### 📜 Description

I've setup backstage on my linux server environement. I've installed all prerequisites like node, yarn and postgresql before setting up backstage. Was following this 'getting started' official doc from backstage. Here is my `app-config.yaml` file looks like:
```
app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: Clouddrove

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: pg
    connection:
      host: localhost
      port: 5432
      user: postgres
      password: postgres
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}

proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  # endpoints:
  #   '/test':
  #     target: 'https://example.com'
  #     changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers: {}

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    ## Uncomment these lines to add more example data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]
```

Here is my complete log while running `yarn dev` command in root of backstage app dir:
```
yarn run v1.22.21
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] fatal: not a git repository (or any of the parent directories): .git
[0] fatal: not a git repository (or any of the parent directories): .git
[0] NOTE: Did not compute git version or commit hash, could not execute the git command line utility
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/root/backstage/backstage-demo/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] Loaded config from app-config.yaml
[1] 2024-01-11T16:58:06.591Z backstage info Found 2 new secrets in config that will be redacted 
[1] 2024-01-11T16:58:06.630Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{} 
[1] 2024-01-11T16:58:06.821Z catalog info Performing database migration type=plugin
[1] 2024-01-11T16:58:09.174Z auth info Configuring "database" as KeyStore provider type=plugin
[1] 2024-01-11T16:58:09.307Z techdocs info Creating Local publisher for TechDocs type=plugin
[1] 2024-01-11T16:58:09.360Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog type=plugin
[1] 2024-01-11T16:58:09.361Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs type=plugin
[1] 2024-01-11T16:58:09.374Z search info Starting all scheduled search tasks. type=plugin
[1] 2024-01-11T16:58:10.118Z backstage info Listening on :7007 
[1] 2024-01-11T16:58:10.415Z backstage info Task worker starting: search_index_software_catalog, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} type=taskManager task=search_index_software_catalog
[1] 2024-01-11T16:58:10.418Z backstage info Task worker starting: search_index_techdocs, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} type=taskManager task=search_index_techdocs
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[0] <i> [webpack-dev-middleware] wait until bundle finished: /ws
[0] ERROR in ../../node_modules/swagger-ui-react/node_modules/react-redux/dist/react-redux.mjs 1097:18-45
[0] export 'useSyncExternalStore' (imported as 'React2') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
[0] 
[0] webpack compiled with 1 error
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] 2024-01-11T17:00:08.539Z search info Collating documents for techdocs via DefaultTechDocsCollatorFactory type=plugin documentType=techdocs
[1] 2024-01-11T17:00:08.558Z search info Collating documents for software-catalog via DefaultCatalogCollatorFactory type=plugin documentType=software-catalog
[1] 2024-01-11T17:00:08.629Z backstage info ::1 - - [11/Jan/2024:17:00:08 +0000] "GET /api/catalog/entities?limit=500&filter=metadata.annotations.backstage.io%2Ftechdocs-ref&offset=0 HTTP/1.1" 200 2 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-01-11T17:00:08.641Z search warn Index for techdocs was not created: indexer received 0 documents type=plugin documentType=techdocs
[1] 2024-01-11T17:00:08.643Z search info Collating documents for techdocs succeeded type=plugin documentType=techdocs
[1] 2024-01-11T17:00:08.650Z backstage info ::1 - - [11/Jan/2024:17:00:08 +0000] "GET /api/catalog/entities?limit=500&offset=0 HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-01-11T17:00:08.667Z search info Collating documents for software-catalog succeeded type=plugin documentType=software-catalog
[0] Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
[0] Exit code: 137
[0] Command: /usr/bin/node
[0] Arguments: /usr/local/lib/node_modules/yarn/lib/cli.js start
[0] Directory: /root/backstage/backstage-demo/packages/app
[0] Output:
[0] 
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[0] yarn start exited with code 137
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] 2024-01-11T17:01:48.827Z backstage info ::1 - - [11/Jan/2024:17:01:48 +0000] "GET / HTTP/1.1" 404 - "-" "curl/8.2.1" type=incomingRequest
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] 2024-01-11T17:04:48.849Z backstage warn Task worker failed unexpectedly, attempt number 2, error: the database system is in recovery mode type=taskManager task=search_index_techdocs
[1] 2024-01-11T17:04:48.850Z backstage warn Task worker failed unexpectedly, attempt number 2, error: the database system is in recovery mode type=taskManager task=search_index_software_catalog
[1] 2024-01-11T17:04:48.875Z catalog warn Failed to load processing items the database system is in recovery mode type=plugin length=109 name=error severity=FATAL code=57P03 detail=undefined hint=undefined position=undefined internalPosition=undefined internalQuery=undefined where=undefined schema=undefined table=undefined column=undefined dataType=undefined constraint=undefined file=postmaster.c line=2361 routine=ProcessStartupPacket stack=error: the database system is in recovery mode
[1]     at Parser.parseErrorMessage (/root/backstage/backstage-demo/node_modules/pg-protocol/src/parser.ts:369:69)
[1]     at Parser.handlePacket (/root/backstage/backstage-demo/node_modules/pg-protocol/src/parser.ts:188:21)
[1]     at Parser.parse (/root/backstage/backstage-demo/node_modules/pg-protocol/src/parser.ts:103:30)
[1]     at Socket.<anonymous> (/root/backstage/backstage-demo/node_modules/pg-protocol/src/index.ts:7:48)
[1]     at Socket.emit (node:events:513:28)
[1]     at Socket.emit (node:domain:489:12)
[1]     at addChunk (node:internal/streams/readable:324:12)
[1]     at readableAddChunk (node:internal/streams/readable:297:9)
[1]     at Readable.push (node:internal/streams/readable:234:10)
[1]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] Connection Error: Connection ended unexpectedly
[1] 2024-01-11T17:10:08.081Z search info Collating documents for techdocs via DefaultTechDocsCollatorFactory type=plugin documentType=techdocs
[1] 2024-01-11T17:10:08.087Z search info Collating documents for software-catalog via DefaultCatalogCollatorFactory type=plugin documentType=software-catalog
[1] 2024-01-11T17:10:08.107Z backstage info ::1 - - [11/Jan/2024:17:10:08 +0000] "GET /api/catalog/entities?limit=500&filter=metadata.annotations.backstage.io%2Ftechdocs-ref&offset=0 HTTP/1.1" 200 2 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-01-11T17:10:08.109Z backstage info ::1 - - [11/Jan/2024:17:10:08 +0000] "GET /api/catalog/entities?limit=500&offset=0 HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-01-11T17:10:08.111Z search warn Index for techdocs was not created: indexer received 0 documents type=plugin documentType=techdocs
[1] 2024-01-11T17:10:08.112Z search info Collating documents for techdocs succeeded type=plugin documentType=techdocs
[1] 2024-01-11T17:10:08.123Z search info Collating documents for software-catalog succeeded type=plugin documentType=software-catalog
```

### 👍 Expected behavior

I should get a browser responce like this

![image](https://github.com/backstage/backstage/assets/115100281/4c86e2c6-d7a0-44e2-96e4-23d1e7129401)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/115100281/ea886904-5c0e-45e2-a397-d3ef1289a4b5)

### 👟 Reproduction steps

By running backstage app in dev env using this command: `yarn dev`

### 📃 Provide the context for the Bug.

I'm trying to setup backstage tool in my linux server.

### 🖥️ Your Environment

```
yarn run v1.22.21
$ /root/backstage/backstage-demo/node_modules/.bin/backstage-cli info
OS:   Linux 6.5.0-14-generic - linux/x64
node: v18.13.0
yarn: 1.22.21
cli:  0.25.0 (installed)
backstage:  1.21.0

Dependencies:
  @backstage/app-defaults                                          1.4.6
  @backstage/backend-app-api                                       0.5.9
  @backstage/backend-common                                        0.20.0
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.1
  @backstage/backend-plugin-api                                    0.6.8
  @backstage/backend-tasks                                         0.5.13
  @backstage/catalog-client                                        1.5.1
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.1
  @backstage/cli                                                   0.25.0
  @backstage/config-loader                                         1.6.0
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.2
  @backstage/core-compat-api                                       0.1.0
  @backstage/core-components                                       0.13.9
  @backstage/core-plugin-api                                       1.8.1
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.4.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.22
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.2
  @backstage/plugin-app-backend                                    0.3.56
  @backstage/plugin-app-node                                       0.1.8
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.2
  @backstage/plugin-auth-backend-module-github-provider            0.1.5
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.5
  @backstage/plugin-auth-backend-module-google-provider            0.1.5
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.0
  @backstage/plugin-auth-backend-module-okta-provider              0.0.1
  @backstage/plugin-auth-backend                                   0.20.2
  @backstage/plugin-auth-node                                      0.4.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.5
  @backstage/plugin-catalog-backend                                1.16.0
  @backstage/plugin-catalog-common                                 1.0.19
  @backstage/plugin-catalog-graph                                  0.3.2
  @backstage/plugin-catalog-import                                 0.10.4
  @backstage/plugin-catalog-node                                   1.6.0
  @backstage/plugin-catalog-react                                  1.9.2
  @backstage/plugin-catalog                                        1.16.0
  @backstage/plugin-events-node                                    0.2.17
  @backstage/plugin-github-actions                                 0.6.9
  @backstage/plugin-org                                            0.6.18
  @backstage/plugin-permission-common                              0.7.11
  @backstage/plugin-permission-node                                0.7.19
  @backstage/plugin-permission-react                               0.4.18
  @backstage/plugin-proxy-backend                                  0.4.6
  @backstage/plugin-scaffolder-backend-module-azure                0.1.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.0
  @backstage/plugin-scaffolder-backend-module-github               0.1.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.11
  @backstage/plugin-scaffolder-backend                             1.19.2
  @backstage/plugin-scaffolder-common                              1.4.4
  @backstage/plugin-scaffolder-node                                0.2.9
  @backstage/plugin-scaffolder-react                               1.7.0
  @backstage/plugin-scaffolder                                     1.17.0
  @backstage/plugin-search-backend-module-catalog                  0.1.12
  @backstage/plugin-search-backend-module-pg                       0.5.17
  @backstage/plugin-search-backend-module-techdocs                 0.1.12
  @backstage/plugin-search-backend-node                            1.2.12
  @backstage/plugin-search-backend                                 1.4.8
  @backstage/plugin-search-common                                  1.2.9
  @backstage/plugin-search-react                                   1.7.4
  @backstage/plugin-search                                         1.4.4
  @backstage/plugin-tech-radar                                     0.6.11
  @backstage/plugin-techdocs-backend                               1.9.1
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.3
  @backstage/plugin-techdocs-node                                  1.11.0
  @backstage/plugin-techdocs-react                                 1.1.14
  @backstage/plugin-techdocs                                       1.9.2
  @backstage/plugin-user-settings                                  0.7.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.6
  @backstage/theme                                                 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
Done in 1.40s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
`backend.baseUrl` should be the address that _the browser_ needs to make requests to, to reach the backend. It's often the address of a reverse proxy, an ingress web gateway, etc - depending on your deployment topology

**Comment by nileshgadgi** [comment]
@freben I'm only using my server where backstage is deployed. I've just created one server where I want to setup backstage. I've gone through getting started instruction, but not worked for me.

**Comment by freben** [comment]
Do you get the page loading? What does the location bar of your browser say then?

**Comment by nileshgadgi** [comment]
Hi @freben ,
Yes, I get initial page loading that throwing error like this
![Screenshot from 2024-01-11 22-35-38](https://github.com/backstage/backstage/assets/115100281/889915de-9150-49f8-81c8-68eb08ef4485)
While checking log it says listening to 7007 and resolving request fine:
```
yarn run v1.22.21
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] fatal: not a git repository (or any of the parent directories): .git
[0] fatal: not a git repository (or any of the parent directories): .git
[0] NOTE: Did not compute git version or commit hash, could not execute the git command line utility
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/root/backstage/backstage-demo1/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[1] Loaded config from app-config.yaml
[1] 2024-01-16T18:21:10.868Z backstage info Found 2 new secrets in config that will be redacted 
[1] 2024-01-16T18:21:10.891Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{} 
[1] 2024-01-16T18:21:10.927Z catalog info Performing database migration type=plugin
[1] 2024-01-16T18:21:12.282Z auth info Configuring "database" as KeyStore provider type=plugin
[1] 2024-01-16T18:21:12.387Z techdocs info Creating Local publisher for TechDocs type=plugin
[1] 2024-01-16T18:21:12.395Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog type=plugin
[1] 2024-01-16T18:21:12.403Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs type=plugin
[1] 2024-01-16T18:21:12.405Z search info Starting all scheduled search tasks. type=plugin
[1] 2024-01-16T18:21:12.890Z backstage info Listening on :7007 
[1] 2024-01-16T18:21:12.953Z backstage info Task worker starting: search_index_software_catalog, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} type=taskManager task=search_index_software_catalog
[1] 2024-01-16T18:21:12.955Z backstage info Task worker starting: search_index_techdocs, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} type=taskManager task=search_index_techdocs
[1] 2024-01-16T18:21:15.961Z search info Collating documents for software-catalog via DefaultCatalogCollatorFactory type=plugin documentType=software-catalog
[1] 2024-01-16T18:21:16.016Z search info Collating documents for techdocs via DefaultTechDocsCollatorFactory type=plugin documentType=techdocs
[1] 2024-01-16T18:21:16.199Z backstage info ::1 - - [16/Jan/2024:18:21:16 +0000] "GET /api/catalog/entities?limit=500&filter=metadata.annotations.backstage.io%2Ftechdocs-ref&offset=0 HTTP/1.1" 200 2 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-01-16T18:21:16.218Z search warn Index for techdocs was not created: indexer received 0 documents type=plugin documentType=techdocs
[1] 2024-01-16T18:21:16.220Z search info Collating documents for techdocs succeeded type=plugin documentType=techdocs
[1] 2024-01-16T18:21:16.227Z backstage info ::1 - - [16/Jan/2024:18:21:16 +0000] "GET /api/catalog/entities?limit=500&offset=0 HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-01-16T18:21:16.248Z search info Collating documents for software-catalog succeeded type=plugin documentType=software-catalog
[0] webpack compiled successfully
[1] 2024-01-16T18:24:08.270Z backstage info ::1 - - [16/Jan/2024:18:24:08 +0000] "GET / HTTP/1.1" 404 - "-" "curl/8.2.1" type=incomingRequest
[1] 2024-01-16T18:31:16.403Z search info Collating documents for techdocs via DefaultTechDocsCollatorFactory type=plugin documentType=techdocs
[1] 2024-01-16T18:31:16.426Z search info Collating documents for software-catalog via DefaultCatalogCollatorFactory type=plugin documentType=software-catalog
[1] 2024-01-16T18:31:16.453Z backstage info ::1 - - [16/Jan/2024:18:31:16 +0000] "GET /api/catalog/entities?limit=500&filter=metadata.annotations.backstage.io%2Ftechdocs-ref&offset=0 HTTP/1.1" 200 2 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-01-16T18:31:16.463Z search warn Index for techdocs was not created: indexer received 0 documents type=plugin documentType=techdocs
[1] 2024-01-16T18:31:16.465Z search info Collating documents for techdocs succeeded type=plugin documentType=techdocs
[1] 2024-01-16T18:31:16.474Z backstage info ::1 - - [16/Jan/2024:18:31:16 +0000] "GET /api/catalog/entities?limit=500&offset=0 HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-01-16T18:31:16.488Z search info Collating documents for software-catalog succeeded type=plugin documentType=software-catalog
[1] 2024-01-16T18:41:16.649Z search info Collating documents for techdocs via DefaultTechDocsCollatorFactory type=plugin documentType=techdocs
[1] 2024-01-16T18:41:16.657Z search info Collating documents for software-catalog via DefaultCatalogCollatorFactory type=plugin documentType=software-catalog
[1] 2024-01-16T18:41:16.668Z backstage info ::1 - - [16/Jan/2024:18:41:16 +0000] "GET /api/catalog/entities?limit=500&filter=metadata.annotations.backstage.io%2Ftechdocs-ref&offset=0 HTTP/1.1" 200 2 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-01-16T18:41:16.673Z search warn Index for techdocs was not created: indexer received 0 documents type=plugin documentType=techdocs
[1] 2024-01-16T18:41:16.674Z search info Collating documents for techdocs succeeded type=plugin documentType=techdocs
[1] 2024-01-16T18:41:16.677Z backstage info ::1 - - [16/Jan/2024:18:41:16 +0000] "GET /api/catalog/entities?limit=500&offset=0 HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-01-16T18:41:16.689Z search info Collating documents for software-catalog succeeded type=plugin documentType=software-catalog
```

**Comment by connor11528** [comment]
I am getting a similar error following the getting started docs:

```
export 'useSyncExternalStore' (imported as 'React2') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
node_modules/swagger-ui-react/node_modules/react-redux/dist/react-redux.mjs
``` 

Looks like this is a duplicate of https://github.com/backstage/backstage/issues/22142 and https://github.com/swagger-api/swagger-ui/issues/9495

**Comment by nileshgadgi** [comment]
To fix this issue you can do [this](https://github.com/backstage/backstage/issues/22142#issuecomment-1881770676) and run `yarn install` command. now the error should be gone.

**Comment by nileshgadgi** [comment]
The backstage getting started doc contains many bugs that still should be fixed. 😞

**Comment by freben** [comment]
@nileshgadgi What I'm saying is that your **browser** will be trying to connect to `http://localhost:7007`. Is that really correct? Is that where Backstage is deployed, or is it on a different machine?

**Comment by freben** [comment]
`Failed to load processing items the database system is in recovery mode`

What could that be? Could your local postgres be having problems somehow?
