### ISSUE TITLE
🐛 Bug Report: app-config.production.yaml created by `npx @backstage/create-app@latest` is broken.

### ISSUE THREAD

**Issue by mugioka** [backstage/backstage#22240]
### 📜 Description

app-config.production.yaml created by `npx @backstage/create-app@latest` is broken.

error log is bellow:
```
{"level":"info","message":"Found 2 new secrets in config that will be redacted","service":"backstage"}
Backend failed to start up TypeError: Invalid type in config for key 'backend.listen' in 'app-config.production.yaml', got string, wanted object
```

### 👍 Expected behavior

https://github.com/backstage/backstage/blob/56d3373c8262e947747b7dfe399d9a5870ff775a/packages/create-app/templates/default-app/app-config.production.yaml#L14 would be bellow
```:yaml
backend:
  listen:
    port: 7007
```

### 👎 Actual Behavior with Screenshots

we cannot start application using app-config.production.yaml.

### 👟 Reproduction steps

1. Build docker image（ENTRYPOINT or COMMAND should use app-config.production.yaml）
2. Run docker image

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Hm that's unexpected, I can't reproduce at least locally on latest master. The code around it hasn't changed as far as I know. Here's the config schema for that key:

https://github.com/backstage/backstage/blob/63afa63eb8593009956e06fd51f1111ccb654bd0/packages/backend-common/config.d.ts#L41

```
    listen:
      | string
      | {
          host?: string;
          port?: string | number;
        };
```

What were the exact reproduction steps? Running that create-app command then then what yarn commands + file modifications were made?

**Comment by CaioAugustoo** [comment]
any progress on this? i'm facing the same issue...

**Comment by veronluc-ansys** [comment]
Same issue here

**Comment by ValeryAsah** [comment]
same issue as well

**Comment by SuperCoolAlan** [comment]
I faced this issue and found that changing the templated app-config.yaml format fixed my issue...

from this:
```yaml
# errored configuration
backend:
  listen: ':7007'
```

to this:
```yaml
# working configuration
backend:
  listen:
    port: 7007
```

Cheers, y'all! :zap:

**Comment by mikejoh** [comment]
@freben i'm having the same issue as the user reported here. And the fix is the same, basically change the `backend.listen` config in the `app-config.production.yaml` as mentioned [above](https://github.com/backstage/backstage/issues/22240#issuecomment-2435762433).

When trying out Backstage using the getting started guide, and deploying it to a local `kind` k8s cluster, i got the following error:

```bash
Loading config from MergedConfigSource{FileConfigSource{path="/app/app-config.yaml"}, FileConfigSource{path="/app/app-config.production.yaml"}, EnvConfigSource{count=1}}
{"level":"info","message":"Found 3 new secrets in config that will be redacted","service":"backstage"}
/app/node_modules/@backstage/config/dist/reader.cjs.js:363
        throw new TypeError(
              ^

TypeError: Invalid type in config for key 'backend.listen' in 'app-config.production.yaml', got string, wanted object
    at ConfigReader.readValue (/app/node_modules/@backstage/config/dist/reader.cjs.js:363:15)
    at ConfigReader.getOptional (/app/node_modules/@backstage/config/dist/reader.cjs.js:132:34)
    at ConfigReader.getOptional (/app/node_modules/@backstage/config/dist/reader.cjs.js:133:42)
    at ObservableConfigProxy.getOptional (/app/node_modules/@backstage/config-loader/dist/sources/ObservableConfigProxy.cjs.js:79:32)
    at readHttpListenOptions (/app/node_modules/@backstage/backend-defaults/dist/entrypoints/rootHttpRouter/http/config.cjs.js:28:24)
    at Object.readHttpServerOptions (/app/node_modules/@backstage/backend-defaults/dist/entrypoints/rootHttpRouter/http/config.cjs.js:7:13)
    at Object.factory (/app/node_modules/@backstage/backend-defaults/dist/entrypoints/rootHttpRouter/rootHttpRouterServiceFactory.cjs.js:42:14)
    at Function.factory (/app/node_modules/@backstage/backend-plugin-api/dist/services/system/types.cjs.js:37:35)
    at /app/node_modules/@backstage/backend-app-api/dist/wiring/ServiceRegistry.cjs.js:190:38
    at async Promise.all (index 0)
    at async ServiceRegistry.initializeEagerServicesWithScope (/app/node_modules/@backstage/backend-app-api/dist/wiring/ServiceRegistry.cjs.js:159:11)
    at async #doStart (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:174:5)
    at async BackendInitializer.start (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:163:5)
    at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackstageBackend.cjs.js:19:5)
```

`kind` cluster deployed using the following cluster configuration:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: backstage
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
```

Then i deployed `backstage` onto my local `kind` cluster using the following commands:
```bash
helm upgrade --install \
  backstage backstage/backstage \
  --create-namespace \
  --namespace backstage \
  -f backstage-values.yaml \
  --version 2.6.1
```

with the following Helm values:

```yaml
backstage:
  image:
    registry: docker.io
    repository: mikejoh/my-backstage
    tag: latest
    pullPolicy: Always
  extraEnvVarsSecrets:
    - github-secret
  extraEnvVars:
    - name: BACKSTAGE_ENV
      value: production
  
postgresql:
  enabled: true
  auth:
    username: demo
    password: secret
```

My home built Docker image are using the following config: [`app-config.production.yaml`](https://github.com/backstage/backstage/blob/v1.43.0/packages/create-app/templates/default-app/app-config.production.yaml).

To build the Docker image i'm testing i did the following:

```bash
npx @backstage/create-app@latest
docker image build . -f packages/backend/Dockerfile --tag mikejoh/my-backstage:latest
docker push
``` 

`yarn backstage-cli info`
```bash
OS:   Linux 6.16.4-zen1-1-zen - linux/x64
node: v22.19.0
yarn: 4.4.1
cli:  0.34.3 (installed)
backstage:  1.43.0

Dependencies:
  @backstage/app-defaults                                          1.7.0
  @backstage/backend-app-api                                       1.2.7
  @backstage/backend-defaults                                      0.12.1
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.6.1
  @backstage/backend-plugin-api                                    1.4.3
  @backstage/catalog-client                                        1.12.0
  @backstage/catalog-model                                         1.7.5
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.14
  @backstage/cli                                                   0.34.3
  @backstage/config-loader                                         1.10.3
  @backstage/config                                                1.3.3
  @backstage/core-app-api                                          1.19.0
  @backstage/core-compat-api                                       0.5.2
  @backstage/core-components                                       0.17.5, 0.18.1
  @backstage/core-plugin-api                                       1.11.0
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.7
  @backstage/eslint-plugin                                         0.1.11
  @backstage/frontend-app-api                                      0.13.0
  @backstage/frontend-defaults                                     0.3.1
  @backstage/frontend-plugin-api                                   0.11.0, 0.12.0
  @backstage/frontend-test-utils                                   0.3.6
  @backstage/integration-aws-node                                  0.1.17
  @backstage/integration-react                                     1.2.10
  @backstage/integration                                           1.18.0
  @backstage/plugin-api-docs                                       0.12.11
  @backstage/plugin-app-backend                                    0.5.6
  @backstage/plugin-app-node                                       0.1.37
  @backstage/plugin-app                                            0.3.0
  @backstage/plugin-auth-backend-module-github-provider            0.3.7
  @backstage/plugin-auth-backend-module-guest-provider             0.2.12
  @backstage/plugin-auth-backend                                   0.25.4
  @backstage/plugin-auth-node                                      0.6.7
  @backstage/plugin-auth-react                                     0.1.19
  @backstage/plugin-bitbucket-cloud-common                         0.3.2
  @backstage/plugin-catalog-backend-module-logs                    0.1.14
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.12
  @backstage/plugin-catalog-backend                                3.1.0
  @backstage/plugin-catalog-common                                 1.1.5
  @backstage/plugin-catalog-graph                                  0.5.1
  @backstage/plugin-catalog-import                                 0.13.5
  @backstage/plugin-catalog-node                                   1.19.0
  @backstage/plugin-catalog-react                                  1.21.1
  @backstage/plugin-catalog                                        1.31.3
  @backstage/plugin-events-node                                    0.4.15
  @backstage/plugin-home-react                                     0.1.30
  @backstage/plugin-home                                           0.8.12
  @backstage/plugin-kubernetes-backend                             0.20.2
  @backstage/plugin-kubernetes-common                              0.9.6
  @backstage/plugin-kubernetes-node                                0.3.4
  @backstage/plugin-kubernetes-react                               0.5.11
  @backstage/plugin-kubernetes                                     0.12.11
  @backstage/plugin-notifications-backend                          0.5.10
  @backstage/plugin-notifications-common                           0.1.0
  @backstage/plugin-notifications-node                             0.2.19
  @backstage/plugin-notifications                                  0.5.9
  @backstage/plugin-org                                            0.6.44
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.12
  @backstage/plugin-permission-backend                             0.7.4
  @backstage/plugin-permission-common                              0.9.1
  @backstage/plugin-permission-node                                0.10.4
  @backstage/plugin-permission-react                               0.4.36
  @backstage/plugin-proxy-backend                                  0.6.6
  @backstage/plugin-proxy-node                                     0.1.8
  @backstage/plugin-scaffolder-backend-module-azure                0.2.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.13
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.14
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.13
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.13
  @backstage/plugin-scaffolder-backend-module-github               0.9.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.9.5
  @backstage/plugin-scaffolder-backend-module-notifications        0.1.14
  @backstage/plugin-scaffolder-backend                             2.2.1
  @backstage/plugin-scaffolder-common                              1.7.1
  @backstage/plugin-scaffolder-node                                0.11.1
  @backstage/plugin-scaffolder-react                               1.19.1
  @backstage/plugin-scaffolder                                     1.34.1
  @backstage/plugin-search-backend-module-catalog                  0.3.8
  @backstage/plugin-search-backend-module-pg                       0.5.48
  @backstage/plugin-search-backend-module-techdocs                 0.4.6
  @backstage/plugin-search-backend-node                            1.3.15
  @backstage/plugin-search-backend                                 2.0.6
  @backstage/plugin-search-common                                  1.2.19
  @backstage/plugin-search-react                                   1.9.4
  @backstage/plugin-search                                         1.4.30
  @backstage/plugin-signals-backend                                0.3.8
  @backstage/plugin-signals-node                                   0.1.24
  @backstage/plugin-signals-react                                  0.0.15
  @backstage/plugin-signals                                        0.0.23
  @backstage/plugin-techdocs-backend                               2.1.0
  @backstage/plugin-techdocs-common                                0.1.1
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.28
  @backstage/plugin-techdocs-node                                  1.13.7
  @backstage/plugin-techdocs-react                                 1.3.3
  @backstage/plugin-techdocs                                       1.15.0
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.26
  @backstage/release-manifests                                     0.0.13
  @backstage/test-utils                                            1.7.11
  @backstage/theme                                                 0.6.8
  @backstage/types                                                 1.2.2
  @backstage/ui                                                    0.7.1
  @backstage/version-bridge                                        1.0.11
```
