### ISSUE TITLE
🐛 Bug Report: Azure Devops Pull Request dashboard produces misleading error if `project-repo` doesn't exist

### ISSUE THREAD

**Issue by alexanderc-tray** [backstage/backstage#22255]
### 📜 Description

If you 

### 👍 Expected behavior

Some kind of error that more clearly indicates that the project can't be found (e.g. a 404)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/129862982/4a2dfc87-7e7b-4802-ac18-bea51812a691)

### 👟 Reproduction steps

Have the Azure Devops plugins installed & configured and an entity with the following annotations
```
  annotations:
    dev.azure.com/project-repo: Does/Not.Exist
```

Go to the pull request dashboard

### 📃 Provide the context for the Bug.

Stack error from the backend is

```
TypeError: Cannot read properties of null (reading 'id')
    at AzureDevOpsApi.getPullRequests (/app/node_modules/@backstage/plugin-azure-devops-backend/dist/index.cjs.js:484:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/@backstage/plugin-azure-devops-backend/dist/index.cjs.js:840:28
```

I believe we need a check at https://github.com/backstage/backstage/blob/b053ab1782f43300d65473a81aaf65aaee94ae03/plugins/azure-devops-backend/src/api/AzureDevOpsApi.ts#L286-L297 to fail fast with a 404 if `gitRepository` comes back undefined.

I'm happy to make a Pr for this bug, but logging this here as a reminder

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @alexanderc-tray, thanks for the detailed issue and possible solution. Sounds good to me, feel free to submit a PR!

**Comment by awanlin** [comment]
This is still a bug that should be fixed. Going to toss a help wanted label so someone else can pick it up 👍
