### ISSUE TITLE
🐛 Bug Report: Bitbucket auth provider does not remember login state

### ISSUE THREAD

**Issue by martinohmann** [backstage/backstage#22383]
### 📜 Description

When logging in via Bitbucket at https://backstage.domain.tld/settings/auth-providers, the login state does not seem to be persisted in the browser session, leading to frequent re-login requests whenever an action against Bitbucket on the behalf of the user is performed.

Other auth providers like Microsoft and GitHub do not have this issue.

One use case that becomes painful due to that is filling in the repository name when using the [`RepoUrlPicker`](https://backstage.io/docs/features/software-templates/ui-options-examples/#repourlpicker) in a software template to create a new software repository in Bitbucket. Whenever the user stops typing in the repository name field, the Bitbucket login popup opens up. This is rather annoying :wink:.

Since the `bitbucket-refresh-token` cookie is set afterwards and actions against Bitbucket on the behalf of the user are working, I suspect that this might just be a UI bug since the authentication seems to work overall.

### 👍 Expected behavior

When the user is logged in to Bitbucket, backstage should remember the login state until the user logs out explicitly, in the same way as it already works for other auth providers.

### 👎 Actual Behavior with Screenshots

Sign In to Bitbucket:
![Screenshot 2024-01-19 at 15 30 44](https://github.com/backstage/backstage/assets/1335045/9991cb23-7663-4907-bc91-a96beb13def3)

The login state is reflected in backstage directly after:
![Screenshot 2024-01-19 at 15 31 00](https://github.com/backstage/backstage/assets/1335045/304983c1-55ae-4e5c-9dc2-f9be2a61dfe3)

After a page reload, the user does not show as signed in anymore:
![Screenshot 2024-01-19 at 15 48 26](https://github.com/backstage/backstage/assets/1335045/c9686f85-4ce1-4723-95d3-696b34944550)

### 👟 Reproduction steps

1. Navigate to https://backstage.domain.tld/settings/auth-providers
2. Sign In with Bitbucket
3. The Bitbucket auth provider shows the user as signed in afterwards
4. Reload the page
5. The Bitbucket auth provider shows the user as logged out

### 🖥️ Your Environment

```
❯ yarn backstage-cli info
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.19.0
yarn: 3.7.0
cli:  0.25.1 (installed)
backstage:  1.22.0

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.5.10
  @backstage/backend-common                                        0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/catalog-client                                        1.5.1, 1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.13.10, 0.13.9
  @backstage/core-plugin-api                                       1.8.1, 1.8.2
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.4.0, 0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.22, 1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-adr-backend                                    0.4.6
  @backstage/plugin-adr-common                                     0.2.19
  @backstage/plugin-adr                                            0.6.12
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.4.3
  @backstage/plugin-badges-backend                                 0.3.6
  @backstage/plugin-badges                                         0.2.53
  @backstage/plugin-bitbucket-cloud-common                         0.2.15
  @backstage/plugin-catalog-backend-module-aws                     0.3.3
  @backstage/plugin-catalog-backend-module-bitbucket-cloud         0.1.24
  @backstage/plugin-catalog-backend-module-gerrit                  0.1.25
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.16
  @backstage/plugin-catalog-backend-module-openapi                 0.1.26
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.6
  @backstage/plugin-catalog-backend                                1.16.1
  @backstage/plugin-catalog-common                                 1.0.19, 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.2, 1.9.3
  @backstage/plugin-catalog-unprocessed-entities                   0.1.7
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-entity-feedback-backend                        0.2.6
  @backstage/plugin-entity-feedback-common                         0.1.3
  @backstage/plugin-entity-feedback                                0.2.12
  @backstage/plugin-entity-validation                              0.1.14
  @backstage/plugin-events-backend-module-aws-sqs                  0.2.12
  @backstage/plugin-events-backend-module-bitbucket-cloud          0.1.19
  @backstage/plugin-events-backend-module-github                   0.1.19
  @backstage/plugin-events-backend                                 0.2.18
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-explore-backend                                0.0.19
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.35
  @backstage/plugin-explore                                        0.4.15
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-kubernetes-backend                             0.14.1
  @backstage/plugin-kubernetes-common                              0.7.3
  @backstage/plugin-kubernetes-node                                0.1.3
  @backstage/plugin-kubernetes-react                               0.2.1
  @backstage/plugin-kubernetes                                     0.11.4
  @backstage/plugin-linguist-backend                               0.5.6
  @backstage/plugin-linguist-common                                0.1.2
  @backstage/plugin-linguist                                       0.1.14
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-common                              0.7.11, 0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.18, 0.4.19
  @backstage/plugin-playlist-backend                               0.3.13
  @backstage/plugin-playlist-common                                0.1.14
  @backstage/plugin-playlist                                       0.2.3
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-explore                  0.1.13
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10, 1.2.9
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-sentry                                         0.5.14
  @backstage/plugin-shortcuts                                      0.3.18
  @backstage/plugin-sonarqube-backend                              0.2.11
  @backstage/plugin-sonarqube-react                                0.1.12
  @backstage/plugin-sonarqube                                      0.7.11
  @backstage/plugin-splunk-on-call                                 0.4.18
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.41
  @backstage/plugin-tech-insights-backend                          0.5.23
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.15
  @backstage/plugin-tech-insights                                  0.3.21
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Hi! Could you give a quick look at https://backstage.io/docs/auth/troubleshooting/ to see if that helps you advance?

**Comment by martinohmann** [comment]
@freben Thanks for the pointer!

If found a 401 error to `/api/auth/bitbucket/refresh?optional&scope=team&env=production` in the network console:

```json
{
    "error": {
        "name": "AuthenticationError",
        "message": "Refresh failed; caused by InternalOAuthError: Failed to fetch user profile (status: 403 data: {\"type\": \"error\", \"error\": {\"message\": \"Your credentials lack one or more required privilege scopes.\", \"detail\": {\"required\": [\"account\"], \"granted\": [\"team\"]}}})",
        "cause": {
            "name": "InternalOAuthError",
            "message": "Failed to fetch user profile",
            "oauthError": {
                "statusCode": 403,
                "data": "{\"type\": \"error\", \"error\": {\"message\": \"Your credentials lack one or more required privilege scopes.\", \"detail\": {\"required\": [\"account\"], \"granted\": [\"team\"]}}}"
            },
            "stack": "InternalOAuthError: Failed to fetch user profile\n    at /app/node_modules/passport-bitbucket-oauth2/lib/passport-bitbucket/strategy.js:90:19\n    at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)\n    at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)\n    at IncomingMessage.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
        }
    },
    "request": {
        "method": "GET",
        "url": "/api/auth/bitbucket/refresh?optional&scope=team&env=production"
    },
    "response": {
        "statusCode": 401
    }
}
```

One thing that stands out is that it's trying to refresh with `scope=team`. There is no `team` scope according to the Bitbucket API docs: https://developer.atlassian.com/cloud/bitbucket/rest/intro/#bitbucket-oauth-2-0-scopes

If I replay the request with `scope=account` it works as expected, returning an access token and user information:

```json
{"providerInfo":{"accessToken":"[redacted]","expiresInSeconds":7200},"profile":{"picture":"[redacted]","displayName":"Martin Ohmann"}}
```

I've looked a bit around in the config and code of the auth plugins but couldn't figure out where the `team` scope is defined.

If somebody could give me a pointer I'd be glad to take a stab at fixing this.

**Comment by martinohmann** [comment]
I think I found where this is coming from: https://github.com/backstage/backstage/blob/master/packages/app-defaults/src/defaults/apis.ts#L227

Will test what effect changes to the default scopes have on the Bitbucket auth flow.
