### ISSUE TITLE
Scaffolding failing on @gitbeaker dependency

### ISSUE THREAD

**Issue by 5-k** [backstage/backstage#22586]
### 📜 Description

When i start a newly built plugin, it breaks at the very start

```
Now using node v18.18.2 (npm v9.8.1)
pmishra7@HCFGQJ690V hackathon-24 % npx @backstage/create-app@latest


? Enter a name for the app [required] backstage

Creating the app...

 Checking if the directory is available:
  checking      backstage ✔ 

 Creating a temporary app directory:

 Preparing files:
  copying       .dockerignore ✔ 
  templating    .eslintrc.js.hbs ✔ 
  templating    .gitignore.hbs ✔ 
  copying       .prettierignore ✔ 
  copying       README.md ✔ 
  copying       app-config.local.yaml ✔ 
  copying       .eslintignore ✔ 
  copying       app-config.production.yaml ✔ 
  templating    app-config.yaml.hbs ✔ 
  templating    backstage.json.hbs ✔ 
  templating    catalog-info.yaml.hbs ✔ 
  copying       playwright.config.ts ✔ 
  copying       tsconfig.json ✔ 
  copying       yarn.lock ✔ 
  templating    package.json.hbs ✔ 
  copying       lerna.json ✔ 
  copying       README.md ✔ 
  copying       entities.yaml ✔ 
  copying       org.yaml ✔ 
  copying       template.yaml ✔ 
  copying       catalog-info.yaml ✔ 
  copying       index.js ✔ 
  copying       package.json ✔ 
  copying       README.md ✔ 
  templating    .eslintrc.js.hbs ✔ 
  copying       Dockerfile ✔ 
  copying       README.md ✔ 
  templating    package.json.hbs ✔ 
  copying       index.ts ✔ 
  copying       types.ts ✔ 
  copying       index.test.ts ✔ 
  copying       auth.ts ✔ 
  copying       app.ts ✔ 
  copying       catalog.ts ✔ 
  copying       proxy.ts ✔ 
  copying       scaffolder.ts ✔ 
  templating    search.ts.hbs ✔ 
  copying       techdocs.ts ✔ 
  copying       .eslintignore ✔ 
  templating    .eslintrc.js.hbs ✔ 
  templating    package.json.hbs ✔ 
  copying       app.test.ts ✔ 
  copying       android-chrome-192x192.png ✔ 
  copying       apple-touch-icon.png ✔ 
  copying       favicon-16x16.png ✔ 
  copying       favicon-32x32.png ✔ 
  copying       favicon.ico ✔ 
  copying       manifest.json ✔ 
  copying       index.html ✔ 
  copying       robots.txt ✔ 
  copying       safari-pinned-tab.svg ✔ 
  copying       App.test.tsx ✔ 
  copying       App.tsx ✔ 
  copying       apis.ts ✔ 
  copying       setupTests.ts ✔ 
  copying       index.tsx ✔ 
  copying       LogoFull.tsx ✔ 
  copying       LogoIcon.tsx ✔ 
  copying       index.ts ✔ 
  copying       Root.tsx ✔ 
  copying       EntityPage.tsx ✔ 
  copying       SearchPage.tsx ✔ 

 Moving to final location:
  moving        backstage ✔ 
  init          git repository ◜ 
 Installing dependencies:
  init          git repository ✔ 
  determining   yarn version ✔ 
  executing     yarn install ✔ 
  executing     yarn tsc ✔ 

🥇  Successfully created backstage


 All set! Now you might want to:
  Run the app: cd backstage && yarn dev
  Set up the software catalog: https://backstage.io/docs/features/software-catalog/configuration
  Add authentication: https://backstage.io/docs/auth/

pmishra7@HCFGQJ690V hackathon-24 % cd backstage 
pmishra7@HCFGQJ690V backstage % ls
README.md			app-config.yaml			dist-types			node_modules			playwright.config.ts		yarn.lock
app-config.local.yaml		backstage.json			examples			package.json			plugins
app-config.production.yaml	catalog-info.yaml		lerna.json			packages			tsconfig.json
pmishra7@HCFGQJ690V backstage % yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/pmishra7/Documents/repos/hackathon-24/backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] node:internal/modules/cjs/loader:1098
[1]   const err = new Error(`Cannot find module '${request}'`);
[1]               ^
[1] 
[1] Error: Cannot find module '/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/@gitbeaker/rest/dist/index.js'
[1]     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1098:15)
[1]     at finalizeEsmResolution (node:internal/modules/cjs/loader:1091:15)
[1]     at resolveExports (node:internal/modules/cjs/loader:567:14)
[1]     at Module._findPath (node:internal/modules/cjs/loader:636:31)
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
[1]     at a._resolveFilename (/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1729)
[1]     at Module._load (node:internal/modules/cjs/loader:922:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18)
[1]     at Object.<anonymous> (/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/@backstage/plugin-scaffolder-backend-module-gitlab/dist/index.cjs.js:9:12)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[1]     at Object.S (/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1292)
[1]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[1]     at Module._load (node:internal/modules/cjs/loader:960:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   path: '/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/@gitbeaker/rest/package.json'
[1] }
[1] 
[1] Node.js v18.18.2
[0] webpack compiled successfully
^C[0] <i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...

pmishra7@HCFGQJ690V backstage % [1] yarn start-backend exited with code SIGINT
[0] yarn start exited with code SIGINT
nvm ^C
pmishra7@HCFGQJ690V backstage % npm --version
9.8.1
pmishra7@HCFGQJ690V backstage % node --version
v18.18.2
```

Similar issue: https://github.com/backstage/backstage/issues/5980 

### 👍 Expected behavior

Should start the application

### 👎 Actual Behavior with Screenshots

<img width="1179" alt="image" src="https://github.com/backstage/backstage/assets/7741962/808f65d0-cab4-42c1-a454-b93547a2eec3">

### 👟 Reproduction steps

```
npx @backstage/create-app@latest
cd backstage
yarn dev
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
I would try adding a resolution for `@gitbeaker/rest` to version `39.33.0` in your root `package.json` file in the mean time, I have not had time to test.

**Comment by mptasinski** [comment]
adding resolutions partially fix the problem

i need to add all 3 libs to fix missing file problem
```json
 "resolutions": {
   ...
    "@gitbeaker/core": "39.33.0",
    "@gitbeaker/rest": "39.33.0",
    "@gitbeaker/requester-utils": "39.33.0"
  }
```

but now there is another one
```
/node_modules/@gitbeaker/requester-utils/dist/index.js:99
[1]   Object.entries(resources).filter(([, s]) => typeof s === "function").forEach(([k, r]) => {
[1]          ^
[1] 
[1] TypeError: Cannot convert undefined or null to object
[1]     at Function.entries (<anonymous>)
[1]     at Object.presetResourceArguments (/node_modules/@gitbeaker/requester-utils/dist/index.js:99:10)
[1]     at Object.<anonymous> (/node_modules/@gitbeaker/node/src/index.ts:5:13)
```

**Comment by awanlin** [comment]
Looks like maybe also `@gitbeaker/node` needs a resolution as well?

**Comment by axiac** [comment]
The PR validation tasks started failing earlier today for the same reason. ([#22570](https://github.com/backstage/backstage/actions/runs/7693097204/job/20964276318?pr=22570), [#22576](https://github.com/backstage/backstage/actions/runs/7693976768/job/20963783530?pr=22576), [#22579](https://github.com/backstage/backstage/actions/runs/7695843056/job/20969584068?pr=22579) etc.)

**Comment by codequester** [comment]
I am getting the original error even after adding the resolution section. 
```
  "resolutions": {
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@gitbeaker/core": "39.33.0",
    "@gitbeaker/rest": "39.33.0",
    "@gitbeaker/requester-utils": "39.33.0",
    "@gitbeaker/node": "39.33.0"    
  },
```
Below is the error snippet
```
yarn run v1.22.21
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/home/user123/tech/workspace/backstage/my-backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] node:internal/modules/cjs/loader:1181
[1]   const err = new Error(`Cannot find module '${request}'`);
[1]               ^
[1] 
[1] Error: Cannot find module '/home/user123/tech/workspace/backstage/my-backstage/node_modules/@gitbeaker/rest/dist/index.js'
[1]     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1181:15)
[1]     at finalizeEsmResolution (node:internal/modules/cjs/loader:1169:15)
[1]     at resolveExports (node:internal/modules/cjs/loader:591:14)
[1]     at Module._findPath (node:internal/modules/cjs/loader:668:31)
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
[1]     at a._resolveFilename (/home/user123/tech/workspace/backstage/my-backstage/node_modules/tsx/dist/cjs/index.cjs:1:1729)
[1]     at Module._load (node:internal/modules/cjs/loader:985:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[1]     at require (node:internal/modules/helpers:176:18)
[1]     at Object.<anonymous> (/home/user123/tech/workspace/backstage/my-backstage/node_modules/@backstage/plugin-scaffolder-backend-module-gitlab/dist/index.cjs.js:9:12)
[1]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[1]     at Object.S (/home/user123/tech/workspace/backstage/my-backstage/node_modules/tsx/dist/cjs/index.cjs:1:1292)
[1]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[1]     at Module._load (node:internal/modules/cjs/loader:1023:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[1]     at require (node:internal/modules/helpers:176:18) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   path: '/home/user123/tech/workspace/backstage/my-backstage/node_modules/@gitbeaker/rest/package.json'
[1] }
[1] 
[1] Node.js v20.10.0
[0] webpack compiled successfully

```

**Comment by awanlin** [comment]
Thanks @codequester, I wasn't totally sure it would work. I don't know these packages very well and how they are all connected. Can you go back further? We might be stuck waiting on an upstream fix 🤔

**Comment by codequester** [comment]
Apologies @awanlin after adding those to the resolution and doing a `yarn install` I am now getting the same error as @mptasinski . Thanks for getting back!! By going back further, you mean go back to a previous version of backstage? If so I am new to node / npm / yard etc :) could you pls let me know the steps to go back to a previous version? (We could probably add these to the docs as well for folks who are new to those tech stacks) TIA!!!

**Comment by awanlin** [comment]
No worries, sorry going back to older versions of the various `@gitbeaker` packages. But I really don't know if that's going to help :(

**Comment by 5-k** [comment]
The gitbeaker node was moved to rest https://www.npmjs.com/package/@gitbeaker/node however it seems the last 2 version of this library (https://www.npmjs.com/package/@gitbeaker/rest) were not published or had some issues.

If you see they deployed hotfix just now, so its better that we use a stable version like [39.33.0](https://www.npmjs.com/package/@gitbeaker/rest/v/39.33.0 and not the latest one for backstage plugins

**Comment by codequester** [comment]
@5-k Thank you!! And did that solve the issue? For me its not. And just to double check, whenever i make changes to the package.json. I delete the node_modules dir and issue the `yarn install`. Is that correct? Coz when i do that i see few warning messgages like these
```
warning Resolution field "@gitbeaker/requester-utils@37.0.0" is incompatible with requested version "@gitbeaker/requester-utils@^35.8.1"
warning workspace-aggregator-9e10c729-383f-44d6-92c0-6a57c55b782e > backend > @backstage/plugin-scaffolder-backend > @backstage/plugin-scaffolder-backend-module-gitlab > @gitbeaker/node@35.8.1: Please use its successor @gitbeaker/rest
warning Resolution field "@gitbeaker/requester-utils@37.0.0" is incompatible with requested version "@gitbeaker/requester-utils@^35.8.1"
warning Resolution field "@gitbeaker/requester-utils@37.0.0" is incompatible with requested version "@gitbeaker/requester-utils@^39.33.2"
warning Resolution field "@gitbeaker/requester-utils@37.0.0" is incompatible with requested version "@gitbeaker/requester-utils@^39.33.2"

``` 
and then error messages like this
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user123/tech/workspace/backstage/my-backstage/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.6.11-200.fc39.x86_64
gyp ERR! command \"/usr/bin/node-20\" \"/home/user123/tech/workspace/backstage/my-backstage/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/user123/tech/workspace/backstage/my-backstage/node_modules/cpu-features
```
and then 
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user123/tech/workspace/backstage/my-backstage/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.6.11-200.fc39.x86_64
gyp ERR! command \"/usr/bin/node-20\" \"/home/user123/tech/workspace/backstage/my-backstage/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/user123/tech/workspace/backstage/my-backstage/node_modules/tree-sitter

```

**Comment by awanlin** [comment]
Can you all try the new version? https://github.com/jdalrymple/gitbeaker/releases/tag/39.34.0

**Comment by codequester** [comment]
Thanks @awanlin , @jdalrymple . This is working now!!! Will post here if i find any further issues.

**Comment by kimsagro1** [comment]
@codequester Just to confirm, what was the actual fix in the end, I'm having the same issues

**Comment by giocolas** [comment]
I don't know if it can help, during yarn install:

```
warning Resolution field "@gitbeaker/core@39.34.0" is incompatible with requested version "@gitbeaker/core@^35.8.0"
warning Resolution field "@gitbeaker/core@39.34.0" is incompatible with requested version "@gitbeaker/core@^35.8.1"
warning Resolution field "@gitbeaker/requester-utils@39.34.0" is incompatible with requested version "@gitbeaker/requester-utils@^35.8.1"
```

Error is generated from 'plugin-scaffolder-backend-module-gitlab', this is complete stack trace:

```
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml, app-config.local.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/giocolas/Projects/Test/my-backstage-app/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] /Users/giocolas/Projects/Test/my-backstage-app/node_modules/@gitbeaker/requester-utils/dist/index.js:99
[1]   Object.entries(resources).filter(([, s]) => typeof s === "function").forEach(([k, r]) => {
[1]          ^
[1] 
[1] TypeError: Cannot convert undefined or null to object
[1]     at Function.entries (<anonymous>)
[1]     at Object.presetResourceArguments (/Users/giocolas/Projects/Test/my-backstage-app/node_modules/@gitbeaker/requester-utils/dist/index.js:99:10)
[1]     at Object.<anonymous> (/Users/giocolas/Projects/Test/my-backstage-app/node_modules/@gitbeaker/node/src/index.ts:5:13)
[1]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[1]     at Object.S (/Users/giocolas/Projects/Test/my-backstage-app/node_modules/tsx/dist/cjs/index.cjs:1:1292)
[1]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[1]     at Module._load (node:internal/modules/cjs/loader:958:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[1]     at require (node:internal/modules/cjs/helpers:110:18)
[1]     at Object.<anonymous> (/Users/giocolas/Projects/Test/my-backstage-app/node_modules/@backstage/plugin-scaffolder-backend-module-gitlab/dist/index.cjs.js:6:12)
[1]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[1]     at Object.S (/Users/giocolas/Projects/Test/my-backstage-app/node_modules/tsx/dist/cjs/index.cjs:1:1292)
[1]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[1]     at Module._load (node:internal/modules/cjs/loader:958:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[1]     at require (node:internal/modules/cjs/helpers:110:18)
[1] 
[1] Node.js v18.15.0
```

**Comment by anerathil** [comment]
> @codequester Just to confirm, what was the actual fix in the end, I'm having the same issues
> 
> I've set my resolutions to
> 
> ```json
> "resolutions": {
>     "@types/react": "^18",
>     "@types/react-dom": "^18",
>     "@gitbeaker/core": "39.34.0",
>     "@gitbeaker/rest": "39.34.0",
>     "@gitbeaker/requester-utils": "39.34.0"
> },
> ```
> 
> But am getting the following
> 
> ```
> /node_modules/@gitbeaker/requester-utils/dist/index.js:99
> [1]   Object.entries(resources).filter(([, s]) => typeof s === "function").forEach(([k, r]) => {
> [1]          ^
> [1] 
> [1] TypeError: Cannot convert undefined or null to object
> [1]     at Function.entries (<anonymous>)
> [1]     at Object.presetResourceArguments (/node_modules/@gitbeaker/requester-utils/dist/index.js:99:10)
> [1]     at Object.<anonymous> (/node_modules/@gitbeaker/node/src/index.ts:5:13)
> ```

Same issue after reinstalling all dependencies here :(

**Comment by 5-k** [comment]
@codequester  it didnt work for me as well yet. It seemed it worked with this config
```
"resolutions": {
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@gitbeaker/core": "39.34.0",
    "@gitbeaker/rest": "39.34.0",
    "@gitbeaker/requester-utils": "39.34.0"
},
```

but appartenly it did not. I am still trying to fix by using different version for resolution as of now.

**Comment by giocolas** [comment]
I'm continuing some experiments and have restored the original contents of the package.json file by removing lines added in the resolutions section.
To my surprise everything is working fine now!
These are the details of the backstage-cli information result:
```
yarn run v1.22.19
$ /Users/giocolas/Projects/Test/my-backstage-app/node_modules/.bin/backstage-cli info
OS:   Darwin 23.2.0 - darwin/x64
node: v18.15.0
yarn: 1.22.19
cli:  0.25.1 (installed)
backstage:  1.22.1

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.5.10
  @backstage/backend-common                                        0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.4.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend                                1.16.2
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

**Comment by gsavalia** [comment]
If it can help someone, I was able to fix the problem using these resolutions:
`"resolutions": {
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@gitbeaker/rest": "39.34.0",
    "@gitbeaker/requester-utils": "35.8.1",
    "@gitbeaker/core": "35.8.1"
  },`

**Comment by 6d68** [comment]
If anyone still has problems. Doing a `rm -rf node_modules && rm yarn.lock` followed by a `yarn install` solved the problem for me without adjusting the resolutions.

**Comment by freben** [comment]
Deleting the _entire_ yarn.lock is risky, best to avoid doing that. Better instead to just open the lock file and search for e.g. `@gitbeaker/rest@` and delete that exact resolved block. Or run `yarn up @gitbeaker/rest` and let yarn do it for you.

**Comment by 6d68** [comment]
Yes, that's right. Thanks for the explanation.

**Comment by anerathil** [comment]
> @giocolas That's because the team behind that library released a fixed version.

Working fine for me now :)

**Comment by freben** [comment]
Closing this for now, thanks for reporting!

**Comment by 5-k** [comment]
Yes now this is not longer an issue after the fix. Thanks everyone for the quick response and helping fix this. Cheers

**Comment by codequester** [comment]
> @codequester it didnt work for me as well yet. It seemed it worked with this config
> 
> ```
> "resolutions": {
>     "@types/react": "^18",
>     "@types/react-dom": "^18",
>     "@gitbeaker/core": "39.34.0",
>     "@gitbeaker/rest": "39.34.0",
>     "@gitbeaker/requester-utils": "39.34.0"
> },
> ```
> 
> but appartenly it did not. I am still trying to fix by using different version for resolution as of now.

@5-k and @anerathil , My bad for the delayed response. Right after @jdalrymple mentioned that its a pipeline problem. I just did a fresh install i.e I didn't have to tweak the resolutions section in the package.json and it worked!! HTH.
