### ISSUE TITLE
🐛 Bug Report: node-gyp build failure

### ISSUE THREAD

**Issue by rr-jino-jose** [backstage/backstage#22865]
### 📜 Description

Hello I am new to backstage and was trying to create an app following this [doc](https://backstage.io/docs/getting-started/create-an-app/) but I am facing issues like below:

```
warning Error running install script for optional dependency: "/Users/jino.jose/backstage/done/node_modules/tree-sitter-yaml: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/jino.jose/backstage/done/node_modules/tree-sitter-yaml
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@20.11.0 | darwin | arm64
gyp info find Python using Python version 3.11.7 found at \"/opt/homebrew/opt/python@3.11/bin/python3.11\"
gyp http GET https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz failed, reason: self-signed certificate in certificate chain
gyp ERR! stack     at ClientRequest.<anonymous> (/Users/jino.jose/backstage/done/node_modules/node-gyp/node_modules/minipass-fetch/lib/index.js:130:14)
gyp ERR! stack     at ClientRequest.emit (node:events:518:28)
gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:495:9)
gyp ERR! stack     at TLSSocket.emit (node:events:530:35)
gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:169:8)
gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gyp ERR! System Darwin 22.6.0
gyp ERR! command \"/Users/jino.jose/.nvm/versions/node/v20.11.0/bin/node\" \"/Users/jino.jose/backstage/done/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/jino.jose/backstage/done/node_modules/tree-sitter-yaml
gyp ERR! node -v v20.11.0
gyp ERR! node-gyp -v v9.4.1
gyp ERR! not ok"
warning Error running install script for optional dependency: "/Users/jino.jose/backstage/done/node_modules/tree-sitter-json: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/jino.jose/backstage/done/node_modules/tree-sitter-json
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@20.11.0 | darwin | arm64
gyp info find Python using Python version 3.11.7 found at \"/opt/homebrew/opt/python@3.11/bin/python3.11\"
gyp http GET https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz failed, reason: self-signed certificate in certificate chain
gyp ERR! stack     at ClientRequest.<anonymous> (/Users/jino.jose/backstage/done/node_modules/node-gyp/node_modules/minipass-fetch/lib/index.js:130:14)
gyp ERR! stack     at ClientRequest.emit (node:events:518:28)
gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:495:9)
gyp ERR! stack     at TLSSocket.emit (node:events:530:35)
gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:169:8)
gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gyp ERR! System Darwin 22.6.0
gyp ERR! command \"/Users/jino.jose/.nvm/versions/node/v20.11.0/bin/node\" \"/Users/jino.jose/backstage/done/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/jino.jose/backstage/done/node_modules/tree-sitter-json
gyp ERR! node -v v20.11.0
gyp ERR! node-gyp -v v9.4.1
gyp ERR! not ok"
warning Error running install script for optional dependency: "/Users/jino.jose/backstage/done/node_modules/tree-sitter: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /Users/jino.jose/backstage/done/node_modules/tree-sitter
Output:
prebuild-install warn install No prebuilt binaries found (target=20.11.0 runtime=node arch=arm64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@20.11.0 | darwin | arm64
gyp info find Python using Python version 3.11.7 found at \"/opt/homebrew/opt/python@3.11/bin/python3.11\"
gyp http GET https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz failed, reason: self-signed certificate in certificate chain
gyp ERR! stack     at ClientRequest.<anonymous> (/Users/jino.jose/backstage/done/node_modules/node-gyp/node_modules/minipass-fetch/lib/index.js:130:14)
gyp ERR! stack     at ClientRequest.emit (node:events:518:28)
gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:495:9)
gyp ERR! stack     at TLSSocket.emit (node:events:530:35)
gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:169:8)
gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gyp ERR! System Darwin 22.6.0
gyp ERR! command \"/Users/jino.jose/.nvm/versions/node/v20.11.0/bin/node\" \"/Users/jino.jose/backstage/done/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/jino.jose/backstage/done/node_modules/tree-sitter
gyp ERR! node -v v20.11.0
gyp ERR! node-gyp -v v9.4.1
gyp ERR! not ok"
warning Error running install script for optional dependency: "/Users/jino.jose/backstage/done/node_modules/cpu-features: Command failed.
Exit code: 1
Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
Arguments:
Directory: /Users/jino.jose/backstage/done/node_modules/cpu-features
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@20.11.0 | darwin | arm64
gyp info find Python using Python version 3.11.7 found at \"/opt/homebrew/opt/python@3.11/bin/python3.11\"
gyp http GET https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz failed, reason: self-signed certificate in certificate chain
gyp ERR! stack     at ClientRequest.<anonymous> (/Users/jino.jose/backstage/done/node_modules/node-gyp/node_modules/minipass-fetch/lib/index.js:130:14)
gyp ERR! stack     at ClientRequest.emit (node:events:518:28)
gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:495:9)
gyp ERR! stack     at TLSSocket.emit (node:events:530:35)
gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:169:8)
gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gyp ERR! System Darwin 22.6.0
gyp ERR! command \"/Users/jino.jose/.nvm/versions/node/v20.11.0/bin/node\" \"/Users/jino.jose/backstage/done/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/jino.jose/backstage/done/node_modules/cpu-features
gyp ERR! node -v v20.11.0
gyp ERR! node-gyp -v v9.4.1
gyp ERR! not ok"
error /Users/jino.jose/backstage/done/node_modules/isolated-vm: Command failed.
Exit code: 1
Command: prebuild-install || (node-gyp rebuild --release -j max && node-gyp clean)
Arguments:
Directory: /Users/jino.jose/backstage/done/node_modules/isolated-vm
Output:
prebuild-install warn install No prebuilt binaries found (target=20.11.0 runtime=node arch=arm64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@20.11.0 | darwin | arm64
gyp info find Python using Python version 3.11.7 found at "/opt/homebrew/opt/python@3.11/bin/python3.11"
gyp http GET https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz failed, reason: self-signed certificate in certificate chain
gyp ERR! stack     at ClientRequest.<anonymous> (/Users/jino.jose/backstage/done/node_modules/node-gyp/node_modules/minipass-fetch/lib/index.js:130:14)
gyp ERR! stack     at ClientRequest.emit (node:events:518:28)
gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:495:9)
gyp ERR! stack     at TLSSocket.emit (node:events:530:35)
gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:169:8)
gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gyp ERR! System Darwin 22.6.0
gyp ERR! command "/Users/jino.jose/.nvm/versions/node/v20.11.0/bin/node" "/Users/jino.jose/backstage/done/node_modules/.bin/node-gyp" "rebuild" "--release" "-j" "max"
gyp ERR! cwd /Users/jino.jose/backstage/done/node_modules/isolated-vm
gyp ERR! node -v v20.11.0
gyp ERR! node-gyp -v v9.4.1
gyp ERR! not ok
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info This module is OPTIONAL, you can safely ignore this error
info This module is OPTIONAL, you can safely ignore this error
info This module is OPTIONAL, you can safely ignore this error
info This module is OPTIONAL, you can safely ignore this error
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  executing     yarn install ✖

Error: Could not execute command yarn install

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!
```

I tried disabling the cert lookup from env variables like NODE_TLS_REJECT_UNAUTHORIZED. Going through some past issues reported I see node-gyp doesn't respect npm registries. I don't want to disable SSL, so i even tried creating a self signed cert and adding it env variables of node js NODE_EXTRA_CA_CERTS and setting up via npm config set. But no luck. Any help is appreciated. If possible please also add the step to solve such kinda issue in the create-app doc. Thanks 

versions:
```
~/backstage ❯ node -v                                                                                                                                                                           
v20.11.0

~/backstage ❯ npm -v                                                                                                                                                                            
10.4.0

~/backstage ❯ npx -v                                                                                                                                                                            
10.4.0
```

### 👍 Expected behavior

Installing packages without error as its a creator module.

### 👎 Actual Behavior with Screenshots

--

### 👟 Reproduction steps

npx @backstage/create-app@latest

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Hmm this looks like an issue with downloading the node headers.

`request to https://nodejs.org/download/release/v20.11.0/node-v20.11.0-headers.tar.gz failed, reason: self-signed certificate in certificate chain` is interesting. Do you have any extra CA certs installed, or a corporate proxy or something?

**Comment by benjdlambert** [comment]
I think that these probably an issue with the `https_proxy`, and you'll need to add the proxys public cert to the keychain. Node doesn't use the built in keychain.

I think that it's `NODE_EXTRA_CA_CERTS` that you will need to set too with the proxy certs, if you've already configured npm http proxy settings. https://medium.com/@jonatascastro12/understanding-self-signed-certificate-in-chain-issues-on-node-js-npm-git-and-other-applications-ad88547e7028 might help you get started.

I don't think this is a backstage related issue though, seems to be an NPM issue which hopefully the above will fix 🤞

**Comment by rr-jino-jose** [comment]
Thanks. It works now. 

resolution: added a new cert pem ( NODE_EXTRA_CA_CERTS)

**Comment by hspens** [comment]
I had a slightly different error 

```bash
Traceback (most recent call last):
  File \"[...]/node-gyp/gyp/gyp_main.py\", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File \"[...]/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 9, in <module>
    import gyp.input
  File \"[...]/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
```

That was solved with updating `setuptools` for python:

```bash
brew install python-setuptools
```

**Comment by zhixiangyao** [comment]
> I had a slightly different error
> 
> ```shell
> Traceback (most recent call last):
>   File \"[...]/node-gyp/gyp/gyp_main.py\", line 42, in <module>
>     import gyp  # noqa: E402
>     ^^^^^^^^^^
>   File \"[...]/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 9, in <module>
>     import gyp.input
>   File \"[...]/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 19, in <module>
>     from distutils.version import StrictVersion
> ModuleNotFoundError: No module named 'distutils'
> ```
> 
> That was solved with updating `setuptools` for python:
> 
> ```shell
> brew install python-setuptools
> ```

thx!!!!!
