### ISSUE TITLE
🐛 Bug Report: ‼️ techdocs not showing up 

### ISSUE THREAD

**Issue by rr-jino-jose** [backstage/backstage#23081]
### 📜 Description

Hello

recently I caught up with an error like below and is stuck on the same.

```
2024-02-19T18:08:55.970Z backstage info ::ffff:100.126.90.189 - - [19/Feb/2024:18:08:55 +0000] "POST /api/backend/analytics HTTP/1.1" 200 15 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" type=incomingRequest
2024-02-19T18:08:55.972Z backstage info ::ffff:100.126.91.121 - - [19/Feb/2024:18:08:55 +0000] "POST /api/backend/analytics HTTP/1.1" 200 15 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" type=incomingRequest
2024-02-19T18:08:55.972Z backstage info ::ffff:100.126.90.189 - - [19/Feb/2024:18:08:55 +0000] "GET /api/techdocs/static/docs/default/component/rewards-developer-portal/contribute/index.html HTTP/1.1" 404 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" type=incomingRequest
2024-02-19T18:08:55.979Z backstage info ::1 - - [19/Feb/2024:18:08:55 +0000] "GET /api/catalog/entities/by-name/component/default/rewards-developer-portal HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
2024-02-19T18:08:56.039Z backstage info ::ffff:100.126.91.121 - - [19/Feb/2024:18:08:56 +0000] "POST /api/catalog/entities/by-refs HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" type=incomingRequest
2024-02-19T18:08:56.220Z techdocs info Unable to get metadata for 'component:default/rewards-developer-portal' with error Error: Unable to read techdocs_metadata.json at /app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/rewards-developer-portal/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/rewards-developer-portal/techdocs_metadata.json'; caused by Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/rewards-developer-portal/techdocs_metadata.json' type=plugin
2024-02-19T18:08:56.221Z backstage info ::ffff:100.126.90.189 - - [19/Feb/2024:18:08:56 +0000] "GET /api/techdocs/metadata/techdocs/default/component/rewards-developer-portal HTTP/1.1" 404 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" type=incomingRequest
2024-02-19T18:08:56.223Z backstage info ::ffff:100.126.10.79 - - [19/Feb/2024:18:08:56 +0000] "GET /api/techdocs/metadata/entity/default/component/rewards-developer-portal HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" type=incomingRequest
2024-02-19T18:08:56.228Z techdocs error Failed to build the docs page for entity component:default/rewards-developer-portal: Request failed for https://api.github.com/repos/rewards-devops/rewards-developer-portal/commits/main/status?per_page=0, 403 Forbidden Request failed for https://api.github.com/repos/rewards-devops/rewards-developer-portal/commits/main/status?per_page=0, 403 Forbidden type=plugin stack=Error: Request failed for https://api.github.com/repos/rewards-devops/rewards-developer-portal/commits/main/status?per_page=0, 403 Forbidden
    at _GithubUrlReader.fetchResponse (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:2495:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _GithubUrlReader.fetchJson (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:2500:22)
    at async _GithubUrlReader.getRepoDetails (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:2465:26)
    at async _GithubUrlReader.readTree (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:2363:25)
    at async UrlReaderPredicateMux.readTree (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:3311:16)
    at async DirectoryPreparer.prepare (/app/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:763:26)
    at async DocsBuilder.build (/app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:152:32)
2024-02-19T18:08:56.229Z backstage info ::ffff:100.126.10.79 - - [19/Feb/2024:18:08:56 +0000] "GET /api/techdocs/sync/default/component/rewards-developer-portal HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" type=incomingRequest
2024-02-19T18:08:56.314Z backstage info ::ffff:100.126.91.121 - - [19/Feb/2024:18:08:56 +0000] "POST /api/backend/analytics HTTP/1.1" 200 15 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" type=incomingRequest
```
I did tried `npx @techdocs/cli serve -v` and it serves correctly with all file contents. (while developing)

my conf are as follows:
```
#mkdocs.yaml
site_name: 'rr-developer-portal'

nav:
  - Home: index.md
  - Developer Guide:
      - Adding Software Components: contribute.md
      - Adding API Components: add-api.md

plugins:
  - techdocs-core

```

app-config.yaml

```
techdocs:
  storageUrl: http://localhost:7007/api/techdocs/static/docs
  requestUrl: http://localhost:7007/api/techdocs
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local'
```

any help/hint is appreciated to resolve this issue. Thanks

### 👍 Expected behavior

to show the basic details from docs folder present in root directory
<img width="275" alt="Screenshot 2024-02-19 at 1 17 07 PM" src="https://github.com/backstage/backstage/assets/103286934/066efcee-75e5-40c4-9f5a-8db68b123d0c">

### 👎 Actual Behavior with Screenshots

<img width="1505" alt="Screenshot 2024-02-19 at 1 17 41 PM" src="https://github.com/backstage/backstage/assets/103286934/c29fd1bd-1319-4096-960e-2dc3faf5aedc">

### 👟 Reproduction steps

from docker file `CMD ["node", "packages/backend", "--config", "app-config.yaml"]`

but from local `yarn dev` also its now populating

### 🖥️ Your Environment

 yarn backstage-cli info                                                                                                           ✘ INT ▼ 01:18:31 pm
yarn run v1.22.19
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.19.0
yarn: 1.22.19
cli:  0.25.1 (installed)
backstage:  1.22.2

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.5.10
  @backstage/backend-common                                        0.15.2, 0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.11.2, 0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/dev-utils                                             1.0.26
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.4.3
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend                                1.16.2
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-home-react                                     0.1.7
  @backstage/plugin-home                                           0.6.1
  @backstage/plugin-kubernetes-backend                             0.14.1
  @backstage/plugin-kubernetes-common                              0.7.3
  @backstage/plugin-kubernetes-node                                0.1.3
  @backstage/plugin-kubernetes-react                               0.2.1
  @backstage/plugin-kubernetes                                     0.11.4
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.2.19, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 0.80s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by rr-jino-jose** [comment]
thanks a lot @awanlin.
