### ISSUE TITLE
🙏 Help Wanted: How to know the details for error coming from github when using a template

### ISSUE THREAD

**Issue by bernaxa** [backstage/backstage#23140]
### 📜 Description

Hello,

Sorry we don't have access to Discord. Our company is blocking it.

We're trying to use a template, when creating the repo we can see in the screen logs for the task run

`[10](https://backstage-url/create/tasks/e110ee9a-3732-4428-b9e8-3f84529b80f5#line-10)2024-02-21T13:58:23.704Z warn: The GitHub app or token provided may not have the required permissions to create the User repository company-user/Website13.`

`[11](https://backstage-url/create/tasks/e110ee9a-3732-4428-b9e8-3f84529b80f5#line-11)2024-02-21T13:58:23.704Z Error: Failed to create the User repository company-user/Website13, Resource not accessible by integration`
`    at createGithubRepoWithCollaboratorsAndTopics (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend-module-github/dist/index.cjs.js:195:11)`
`    at async Object.handler (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend-module-github/dist/index.cjs.js:2361:23)`
`    at async NunjucksWorkflowRunner.executeStep (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-e667d04e.cjs.js:2277:9)`
`    at async NunjucksWorkflowRunner.execute (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-e667d04e.cjs.js:2350:9)`
`    at async TaskWorker.runOneTask (/opt/app-root/src/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-e667d04e.cjs.js:2572:26)`
`    at async run (/opt/app-root/src/node_modules/p-queue/dist/index.js:163:29)`

We can create a repo at organization level, but not when trying to create the repo in a organization user account.

There is a Github App installed in  "company-user" account (user belongs to organization), with

-  Read access to commit statuses and metadata
-  Read and write access to , actions, administration, code, issues, pull requests, and workflows

How can we know the missing permissions that are causing that error? We have LOG_LEVEL=debug but there is no additional info in the stdout 

How can we "activate" additonal logging for the "plugin-scaffolder-backend-module-github" so may be we can see the details of the answer from github?

Thanks

### 👍 Expected behavior

N/A

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

Use a template

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by bernaxa** [comment]
According to this

https://github.com/orgs/community/discussions/24502#discussioncomment-3244302

`The endpoint for [creating a repository for the authenticated user](https://docs.github.com/en/rest/reference/repos#create-a-repository-for-the-authenticated-user) is not enabled for GitHub Apps.`

https://github.com/orgs/community/discussions/24502#discussioncomment-3244304

```
One approach is [creating an OAuth app] that requests either the public_repo scope (ability to create only public repositories) or the repo scope (ability to create either public or private repositories).
Once that person [authorizes your OAuth app through the web application flow] with either scope, then you can [use the access token to access the API] on their behalf  on their account
```

I've created an Oauth App and forced to authenticate "faking" the auth url adding the **repo** scope to **scope=read%3Auser%20repo**

I can confirm that the Oauth App has "**Full control of private repositories**" under my account but I still receive the same error

**Comment by bernaxa** [comment]
Fixed. See https://github.com/backstage/backstage/issues/22501
