### ISSUE TITLE
🚀 Feature: swagger-editor in backstage

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#23156]
### 🔖 Feature description

Provide the ability to use https://editor.swagger.io/ as a tool plugin within backstage.

### 🎤 Context

 There are certain advantages of using it here rather than the public site:

1. It allows for orgs that already host backstage to additionally self-host swagger editor and not worry about OpenAPI specs with confidential business data in it being pasted into third party sites
2. Possible to integrate into the catalog to pre-populate the swagger editor with an existing registered API entity's spec content

### ✌️ Possible Implementation

I've already tried to integrate this myself but started running into a few errors / blockers

<details>
<summary>Possible Implementation - Local React Page Linked To Sidebar App.tsx</summary>

```tsx
import { Content, Page, Header } from '@backstage/core-components';
import React, { useEffect } from 'react';
import SwaggerEditorBundle from 'swagger-editor-dist/swagger-editor-bundle';
import 'swagger-editor-dist/swagger-editor.css';

interface SwaggerEditorProps {}

export const SwaggerEditorPage = (props: SwaggerEditorProps) => {
  useEffect(() => {
    const editor = SwaggerEditorBundle({
      dom_id: '#swagger-editor',
      layout: 'EditorLayout',
      queryConfigEnabled: false,
    });
    // @ts-ignore
    window.editor = editor;
  }, []);

  return (
    <Page themeId="home">
      <Header title="Swagger Editor" />
      <Content>
        <div id="swagger-editor" />
      </Content>
    </Page>
  );
};
```
</details>

<details>
<summary>Error</summary>
```
Uncaught (in promise) Error: schema with key or id "openapi-2.0" already exists
    at r._callbacks.<computed> (swagger-editor-bundle.js:4:860399)
    at n (swagger-editor-bundle.js:4:860143)
    at Worker.eval (swagger-editor-bundle.js:4:860247)
```
</details>

Additionally, the CSS would need to modified so that the swagger editor does not overflow underneath the sidebar.

Seems like others have already tried doing this but also ran into issues, see ticket here https://github.com/swagger-api/swagger-editor/issues/3971

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Hey @bforbis ! I've made this plugin which includes a collection of different developer tools: https://github.com/drodil/backstage-plugin-toolbox

Maybe this could be included in that plugin?

**Comment by bforbis** [comment]
@drodil what's the best approach for this? After reviewing your plugin (which is awesome by the way), I am not sure if your intention is to grow that plugin unbounded or not.

**Option 1:** 
As you suggest, open an issue on your repo and begin work making it a supported plugin there

**Option 2**
Swagger editor remains its own standalone plugin with exports that allow backstage integrators to either make it a dedicated page themselves or to flexibly embed it into the ToolBox plugin by passing it as `extraTools` to the ToolBox props.

**Comment by drodil** [comment]
Personally I think having own plugin just for the editor is a bit too much and it would fit quite well in the toolbox. But totally up to you, if you want to create new plugin, go ahead 👌

I actually gave it a try to include it to the toolbox but it failed with the same error you encountered. I was able to get it to somewhat work with this https://github.com/swagger-api/swagger-editor/issues/2339#issuecomment-1286716712 but it's still not perfect as the version 4 of the editor doesn't support openapi 3 schemas. Maybe version 5 could be tried but it may have some issues as well. 

I don't think the editor is made to be included in this kind of external projects from the start and it requires quite a lot of UI tuning/CSS overrides to be even close to MUI used by backstage. I see quite a big effort to get this integrated to backstage. Another option could be to just use SwaggerUI (which is already used in backstage) to show the output and fallback to some default text field for input.
