### ISSUE TITLE
🐛 Bug Report: Failure to copywithoutrender in fetch:template + cookiecutter template

### ISSUE THREAD

**Issue by mathbeal** [backstage/backstage#23212]
### 📜 Description

I migrated a django cookiecutter template to backstage template.

All files are copied except **css.map**, displaying the following error message: "**Error: expected end of comment, got end of file**"

I tried to add copyWithoutRender: [''*.css.map"], without success.

### 👍 Expected behavior

the css.map file must be copied without trying to be rendered.

Without css.map in template, all files are copied as expected.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/23397421/e1e6dc0f-7633-45a4-83fa-8edf2ba8d32c)

```
[78](http://localhost:3000/create/tasks/0728eb53-d56d-4ab7-aff8-bc015017b75f#line-78)2024-02-23T14:13:01.051Z info: Writing file ${{values.repo_name}}/static/dist/[main.css.map, Opens in a new window](http://main.css.map/) to template output path with mode 33188.
[79](http://localhost:3000/create/tasks/0728eb53-d56d-4ab7-aff8-bc015017b75f#line-79)2024-02-23T14:13:01.120Z Error: (unknown path)
[80](http://localhost:3000/create/tasks/0728eb53-d56d-4ab7-aff8-bc015017b75f#line-80)  Error: expected end of comment, got end of file
[81](http://localhost:3000/create/tasks/0728eb53-d56d-4ab7-aff8-bc015017b75f#line-81)    at render (/workspaces/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-ca1e7c8a.cjs.js:863:24)
[82](http://localhost:3000/create/tasks/0728eb53-d56d-4ab7-aff8-bc015017b75f#line-82)    at handler (/workspaces/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-ca1e7c8a.cjs.js:1108:32)
[83](http://localhost:3000/create/tasks/0728eb53-d56d-4ab7-aff8-bc015017b75f#line-83)    at (<isolated-vm boundary>)
[84](http://localhost:3000/create/tasks/0728eb53-d56d-4ab7-aff8-bc015017b75f#line-84)    at render (/workspaces/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-ca1e7c8a.cjs.js:863:24)
[85](http://localhost:3000/create/tasks/0728eb53-d56d-4ab7-aff8-bc015017b75f#line-85)    at handler (/workspaces/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-ca1e7c8a.cjs.js:1108:32)
```

### 👟 Reproduction steps

```
  steps:
    - id: template
      name: Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: ['*.css', '*.css.map']
        values:
          # Provide information about the application
          # -----------------------------------------
          project_name: ${{(parameters.repoUrl | parseRepoUrl).repo}}
          namespace: ${{(parameters.repoUrl | parseRepoUrl).owner}}
```

./skeleton contains the cookiecutter template, with the replaced variables ${{values.project_name}}. 

### 🖥️ Your Environment

```
yarn run v1.22.19
$ /workspaces/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.133.1-microsoft-standard-WSL2 - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.25.0 (installed)
backstage:  1.21.1

Dependencies:
  @backstage/app-defaults                                          1.4.6
  @backstage/backend-app-api                                       0.4.4, 0.5.9
  @backstage/backend-common                                        0.18.5, 0.19.9, 0.20.0
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.1
  @backstage/backend-plugin-api                                    0.5.3, 0.6.8
  @backstage/backend-tasks                                         0.5.13
  @backstage/catalog-client                                        1.5.1
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.1
  @backstage/cli                                                   0.25.0
  @backstage/config-loader                                         1.6.0
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.2
  @backstage/core-compat-api                                       0.1.0
  @backstage/core-components                                       0.13.9
  @backstage/core-plugin-api                                       1.6.0, 1.8.0, 1.8.1
  @backstage/dev-utils                                             1.0.25
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.4.0
  @backstage/integration-aws-node                                  0.1.6, 0.1.8
  @backstage/integration-react                                     1.1.22
  @backstage/integration                                           1.7.0, 1.8.0
  @backstage/plugin-adr-backend                                    0.4.5
  @backstage/plugin-adr-common                                     0.2.18
  @backstage/plugin-adr                                            0.6.11
  @backstage/plugin-api-docs                                       0.10.2
  @backstage/plugin-app-backend                                    0.3.56
  @backstage/plugin-app-node                                       0.1.8
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.2
  @backstage/plugin-auth-backend-module-github-provider            0.1.5
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.5
  @backstage/plugin-auth-backend-module-google-provider            0.1.5
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.0
  @backstage/plugin-auth-backend-module-okta-provider              0.0.1
  @backstage/plugin-auth-backend                                   0.20.2
  @backstage/plugin-auth-node                                      0.2.15, 0.4.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.5
  @backstage/plugin-catalog-backend                                1.16.0
  @backstage/plugin-catalog-common                                 1.0.19
  @backstage/plugin-catalog-graph                                  0.3.2
  @backstage/plugin-catalog-import                                 0.10.4
  @backstage/plugin-catalog-node                                   1.6.0
  @backstage/plugin-catalog-react                                  1.9.2
  @backstage/plugin-catalog                                        1.16.0
  @backstage/plugin-events-node                                    0.2.17
  @backstage/plugin-github-actions                                 0.6.9
  @backstage/plugin-home-react                                     0.1.6
  @backstage/plugin-home                                           0.6.0
  @backstage/plugin-org                                            0.6.18
  @backstage/plugin-permission-backend                             0.5.31
  @backstage/plugin-permission-common                              0.7.11, 0.7.8
  @backstage/plugin-permission-node                                0.7.19
  @backstage/plugin-permission-react                               0.4.18
  @backstage/plugin-playlist-backend                               0.3.12
  @backstage/plugin-playlist-common                                0.1.13
  @backstage/plugin-proxy-backend                                  0.4.6
  @backstage/plugin-scaffolder-backend-module-azure                0.1.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.0
  @backstage/plugin-scaffolder-backend-module-github               0.1.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.11
  @backstage/plugin-scaffolder-backend                             1.19.2
  @backstage/plugin-scaffolder-common                              1.4.4
  @backstage/plugin-scaffolder-node                                0.2.9
  @backstage/plugin-scaffolder-react                               1.7.0
  @backstage/plugin-scaffolder                                     1.17.0
  @backstage/plugin-search-backend-module-catalog                  0.1.12
  @backstage/plugin-search-backend-module-pg                       0.5.17
  @backstage/plugin-search-backend-node                            1.2.12
  @backstage/plugin-search-backend                                 1.4.8
  @backstage/plugin-search-common                                  1.2.9
  @backstage/plugin-search-react                                   1.7.4
  @backstage/plugin-search                                         1.4.4
  @backstage/plugin-sonarqube-backend                              0.2.10
  @backstage/plugin-sonarqube-react                                0.1.11
  @backstage/plugin-sonarqube                                      0.7.10
  @backstage/plugin-user-settings                                  0.7.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.6
  @backstage/theme                                                 0.2.19, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
Done in 0.65s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave: Thanks for raising this! Are you able to provide a reproduction template and skeleton that we can dig into a little further? :pray:

**Comment by mathbeal** [comment]
Hi @benjdlambert 
I'm trying to extract the main error from a complex css.map. I'll update code during this week.

**Comment by gbovegra** [comment]
Same issue here, any update? Thanks :)

**Comment by mathbeal** [comment]
@gbovegra, 

I found out that `copywithoutRender `is deprecated, and `copywithoutTemplating `must be used.

I solve the issue using  `copyWithoutRender: ['**/*.css', '**/*.css.map']` as css and css.map are not in main folder.

Could you please try it ?

**Comment by gbovegra** [comment]
@mathbeal 
It works, thank you for the guidance!
