### ISSUE TITLE
🐛 Bug Report: plugin-scaffolder-node-test-utils cannot be imported as a dev dependency

### ISSUE THREAD

**Issue by StephanHCB** [backstage/backstage#23416]
### 📜 Description

When importing `@backstage/plugin-scaffolder-node-test-utils` (only published version seems to be 0.1.0-next.0)  in a test, yarn install works fine and downloads the dependency to `node_modules`, but running the test then fails with

```
Cannot find module '@backstage/plugin-scaffolder-node-test-utils' from 'actions/Xyz.test.ts'
```

The issue seems to be that `@backstage/plugin-scaffolder-node-test-utils` has an invalid `package.json` file. It defines the file index.esm.js as the entrypoint but the package output does not include such a file.

![image](https://github.com/backstage/backstage/assets/23000514/9ed7b51b-b57b-43d0-8e3a-1c7a4c6a6824)

### 👍 Expected behavior

using `createMockActionContext()` from `plugin-scaffolder-node-test-utils` in a test should work rather than fail.

### 👎 Actual Behavior with Screenshots

```
Test suite failed to run

    Cannot find module '@backstage/plugin-scaffolder-node-test-utils' from 'actions/GetOwner.test.ts'

       9 | import { createMockActionContext } from '@backstage/plugin-scaffolder-node-test-utils';
      10 |
    > 11 | describe('xyz', () => {
         |                                        ^

      at Resolver._throwModNotFoundError (../../../node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (actions/GetOwner.test.ts:11:40)
```

### 👟 Reproduction steps

In a plugin directory, do `yarn add --dev @backstage/plugin-scaffolder-node-test-utils`, then `yarn install`.

Now write a test trying to use 

```
import { createMockActionContext } from '@backstage/plugin-scaffolder-node-test-utils';

[...]

   const ctx = createMockActionContext({
      input: { [...] },
    });
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by StephanHCB** [comment]
Ah, duplicate, sorry.

https://github.com/backstage/backstage/issues/23380
