### ISSUE TITLE
devApp of the plugin scaffolder don't work

### ISSUE THREAD

**Issue by cmoulliard** [backstage/backstage#23684]
### 📜 Description

I did a test top of the backstage master branch (commit `2c2f705fe169 2024-03-18 Patrik Oldsberg (HEAD -> master, upstream/master) Merge pull request #23663 from backstage/rugvip/watch-fix
`), build the project and launch using `yarn start` the DevApp of the plugin scaffolder to test it without success.

The browser's console reports the following issue:
```
react-dom.development.js:86 Warning: Cannot update a component (`AlertDisplay`) while rendering a different component (`TemplateGroups`). To locate the bad setState() call inside `TemplateGroups`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at TemplateGroups (webpack-internal:///../scaffolder-react/src/next/components/TemplateGroups/TemplateGroups.tsx:47:120)
    at div
    at Grid (webpack-internal:///../../node_modules/@material-ui/core/esm/Grid/Grid.js:237:35)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:65:31)
    at Content (webpack-internal:///../catalog-react/src/components/CatalogFilterLayout/CatalogFilterLayout.tsx:128:25)
    at div
    at Grid (webpack-internal:///../../node_modules/@material-ui/core/esm/Grid/Grid.js:237:35)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:65:31)
    at CatalogFilterLayout (webpack-internal:///../catalog-react/src/components/CatalogFilterLayout/CatalogFilterLayout.tsx:142:25)
    at article
    at Content (webpack-internal:///../../packages/core-components/src/layout/Content/Content.tsx:65:13)
    at main
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:45:24)
    at Page (webpack-internal:///../../packages/core-components/src/layout/Page/Page.tsx:54:13)
    at EntityListProvider (webpack-internal:///../catalog-react/src/hooks/useEntityListProvider.tsx:60:96)
    at TemplateListPage (webpack-internal:///./src/next/TemplateListPage/TemplateListPage.tsx:76:106)
    at RenderedRoute (webpack-internal:///../../node_modules/react-router/dist/index.js:577:5)
    at Routes (webpack-internal:///../../node_modules/react-router/dist/index.js:1267:5)
    at Router (webpack-internal:///./src/components/Router/Router.tsx:58:25)
    at RoutableExtensionWrapper (webpack-internal:///../../packages/core-plugin-api/src/extensions/extensions.tsx:63:99)
    at AnalyticsContext (webpack-internal:///../../packages/core-plugin-api/src/analytics/AnalyticsContext.tsx:71:13)
    at PluginErrorBoundary (webpack-internal:///../../packages/core-plugin-api/src/extensions/PluginErrorBoundary.tsx:54:9)
    at Suspense
    at Result (webpack-internal:///../../packages/core-plugin-api/src/extensions/extensions.tsx:182:73)
    at RenderedRoute (webpack-internal:///../../node_modules/react-router/dist/index.js:577:5)
    at FlatRoutes (webpack-internal:///../../packages/core-app-api/src/routing/FlatRoutes.tsx:50:83)
    at div
    at StyledComponent (webpack-internal:///../../node_modules/@material-ui/styles/esm/styled/styled.js:96:28)
    at SidebarPinStateProvider (webpack-internal:///../../packages/core-components/src/layout/Sidebar/SidebarPinStateContext.tsx:51:13)
    at SidebarPage (webpack-internal:///../../packages/core-components/src/layout/Sidebar/Page.tsx:74:84)
    at Router (webpack-internal:///../../node_modules/react-router/dist/index.js:1201:15)
    at BrowserRouter (webpack-internal:///../../node_modules/react-router-dom/dist/index.js:694:5)
    at AppRouter (webpack-internal:///../../packages/core-app-api/src/app/AppRouter.tsx:105:140)
    at Suspense
    at RoutingProvider (webpack-internal:///../../packages/core-app-api/src/routing/RoutingProvider.tsx:34:28)
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:45:24)
    at StylesProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/StylesProvider/StylesProvider.js:50:24)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:45:5)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:57:5)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/material/styles/ThemeProvider.js:26:14)
    at StyledEngineProvider (webpack-internal:///../../node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:31:5)
    at UnifiedThemeProvider (webpack-internal:///../../packages/theme/src/unified/UnifiedThemeProvider.tsx:50:13)
    at Provider (webpack-internal:///../../packages/app-defaults/src/defaults/themes.tsx:45:22)
    at AppThemeProvider (webpack-internal:///../../packages/core-app-api/src/app/AppThemeProvider.tsx:73:29)
    at AppContextProvider (webpack-internal:///../../packages/core-app-api/src/app/AppContext.tsx:32:31)
    at ApiProvider (webpack-internal:///../../packages/core-app-api/src/apis/system/ApiProvider.tsx:46:13)
    at Provider (webpack-internal:///../../packages/core-app-api/src/app/AppManager.tsx:198:29)
    at AppRoot
```﻿



### 👍 Expected behavior

We should be able to see some templates to scaffold under link `/create`

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-03-18 at 15 11 07](https://github.com/backstage/backstage/assets/463790/d06b6546-d6f1-49f4-9503-54057d4bd129)
![Screenshot 2024-03-18 at 15 20 35](https://github.com/backstage/backstage/assets/463790/009f5a9f-51f3-4ac2-899c-eb100079133c)


### 👟 Reproduction steps

```
git clone https://github.com/backstage/backstage
cd backstage
yarn install
yarn tsc
yarn build:all
cd plugins/scaffolder
yarn start
```

### 📃 Provide the context for the Bug.

n/a

### 🖥️ Your Environment

See : https://gist.github.com/cmoulliard/28723488a2ce13835936c22d0ca7b5a0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
I think that you'll also need to start the backend in general for this frontend to work. It's going to need the catalog + scaffolder in order to run. Maybe we can make this a little clearer and easier to setup somehow?

**Comment by cmoulliard** [comment]
> Maybe we can make this a little clearer and easier to setup somehow?

Yes, please as this not evident/logic for a new developer to figure out that the backend should be started in another terminal. 

**Important**: That fails too if you launch separately the backend

```
// Terminal 1
cd backstage/plugins/scaffolder
yarn start

// Terminal 2
cd backstage/packages/backend-next
yarn start
```
![Screenshot 2024-04-08 at 18 05 20](https://github.com/backstage/backstage/assets/463790/73af7b06-85a3-47f5-91f0-3f96369db90c)

**Comment by benjdlambert** [comment]
@cmoulliard what's the actual failure for the network requests? Maybe it's something with `backend-next` and the new `auth` work that's ongoing, does it work with `packages/backend` instead?

**Comment by cmoulliard** [comment]
> Maybe it's something with `backend-next` and the new `auth` work that's ongoing, does it work with `packages/backend` instead?

No luck too using `packages/backend` instead of `packages/backend-next`

**Comment by cmoulliard** [comment]
> what's the actual failure for the network requests?

Nothing is logged as errors within the terminal of front `packages/plugins/scaffolder => yarn start` or backend `packages/backend => yarn start`

**Comment by benjdlambert** [comment]
@cmoulliard sorry I mean in the chrome dev tools, what's the network request failures say when it's trying to communicate with the backend?

**Comment by cmoulliard** [comment]
> what's the network request failures

I dont see network's errors 
![Screenshot 2024-04-10 at 14 27 15](https://github.com/backstage/backstage/assets/463790/36649f2b-db35-4157-8682-b12f09d7a71c)

**Comment by cmoulliard** [comment]
I dont find errors if I filter using `-status-code:200 ` within DevTools - network tab

![Screenshot 2024-04-10 at 15 59 09](https://github.com/backstage/backstage/assets/463790/b6e4c6d1-1737-49b1-a14c-4714754287b1)

![Screenshot 2024-04-10 at 16 07 32](https://github.com/backstage/backstage/assets/463790/c9cd3804-1fca-492c-b470-9e0e917a8e73)



Here is the HTTP Archive json output: https://gist.github.com/cmoulliard/beb7042dc2be376b5e6584c44d63ef2b

**Comment by cmoulliard** [comment]
Any idea ?

**Comment by cmoulliard** [comment]
The existing code needs some refactoring :-) I was able to use this `index.tsx` file (of our quarkus plugin) with the backstage `packages/backend-next`
```
import { catalogPlugin } from '@backstage/plugin-catalog';
import { createDevApp } from '@backstage/dev-utils';
import { scmIntegrationsApiRef } from '@backstage/integration-react';
import React from 'react';
import { ScaffolderClient, ScaffolderPage } from '@backstage/plugin-scaffolder';
import { scaffolderApiRef, ScaffolderFieldExtensions } from '@backstage/plugin-scaffolder-react';
import {
  discoveryApiRef,
  fetchApiRef,
  identityApiRef,
} from '@backstage/core-plugin-api';
import { CatalogEntityPage } from '@backstage/plugin-catalog';
import {QuarkusExtensionListField, QuarkusVersionListField} from "../src";

createDevApp()
  .registerPlugin(catalogPlugin)
  .registerApi({
    api: scaffolderApiRef,
    deps: {
      discoveryApi: discoveryApiRef,
      fetchApi: fetchApiRef,
      scmIntegrationsApi: scmIntegrationsApiRef,
      identityApi: identityApiRef,
    },

    factory: ({ discoveryApi, fetchApi, scmIntegrationsApi, identityApi }) =>
      new ScaffolderClient({
        discoveryApi,
        fetchApi,
        // @ts-ignore
        scmIntegrationsApi,
        identityApi,
      }),
  })
  .addPage({
    path: '/create',
    title: 'Create',
    element: <ScaffolderPage />,
    children: (
        <ScaffolderFieldExtensions>
            <QuarkusExtensionListField />
            <QuarkusVersionListField />
        </ScaffolderFieldExtensions>
    )
  })
  .addPage({
    element: <CatalogEntityPage />,
  })
  .render();
```

**Comment by cmoulliard** [comment]
Ticket can be closed as PR fixed the issue
