### ISSUE TITLE
🐛 Bug Report: NotFoundError: Template action with ID 'publish:github' is not registered.

### ISSUE THREAD

**Issue by SeanoNET** [backstage/backstage#23820]
### 📜 Description

Trying to create a new component using the default Example Node.js Template service

### 👍 Expected behavior

It publishes a new repo in to my GitHub account

### 👎 Actual Behavior with Screenshots

An error is thrown on the publish step.

```
2024-03-23T13:48:05.131Z NotFoundError: Template action with ID 'publish:github' is not registered.[12](http://localhost:3000/create/tasks/6b1564a8-39b4-49d4-a1c0-5dde5f30dc75#line-12)    at TemplateActionRegistry.get (P:\seanonet-dev-portal\node_modules\@backstage\plugin-scaffolder-backend\src\scaffolder\actions\TemplateActionRegistry.ts:39:13)[13](http://localhost:3000/create/tasks/6b1564a8-39b4-49d4-a1c0-5dde5f30dc75#line-13)    at NunjucksWorkflowRunner.executeStep (P:\seanonet-dev-portal\node_modules\@backstage\plugin-scaffolder-backend\src\scaffolder\tasks\NunjucksWorkflowRunner.ts:264:37)[14](http://localhost:3000/create/tasks/6b1564a8-39b4-49d4-a1c0-5dde5f30dc75#line-14)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[15](http://localhost:3000/create/tasks/6b1564a8-39b4-49d4-a1c0-5dde5f30dc75#line-15)    at NunjucksWorkflowRunner.execute (P:\seanonet-dev-portal\node_modules\@backstage\plugin-scaffolder-backend\src\scaffolder\tasks\NunjucksWorkflowRunner.ts:501:9)[16](http://localhost:3000/create/tasks/6b1564a8-39b4-49d4-a1c0-5dde5f30dc75#line-16)    at TaskWorker.runOneTask (P:\seanonet-dev-portal\node_modules\@backstage\plugin-scaffolder-backend\src\scaffolder\tasks\TaskWorker.ts:176:26)[17](http://localhost:3000/create/tasks/6b1564a8-39b4-49d4-a1c0-5dde5f30dc75#line-17)    at async run (P:\seanonet-dev-portal\node_modules\p-queue\dist\index.js:163:29)
```

### 👟 Reproduction steps

Follow the Getting Started guide, configured GitHub integration and auth, configure Postgres DB.

### 🖥️ Your Environment

```
OS:   Windows_NT 10.0.22631 - win32/x64
node: v20.11.1
yarn: 1.22.22
cli:  0.26.0 (installed)
backstage:  1.24.0

Dependencies:
  @backstage/app-defaults                                          1.5.1
  @backstage/backend-app-api                                       0.6.0
  @backstage/backend-common                                        0.21.4
  @backstage/backend-defaults                                      0.2.14
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.7
  @backstage/backend-plugin-api                                    0.6.14
  @backstage/backend-tasks                                         0.5.19
  @backstage/catalog-client                                        1.6.1
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.26.0
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.1
  @backstage/core-compat-api                                       0.2.1
  @backstage/core-components                                       0.14.1
  @backstage/core-plugin-api                                       1.9.1
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.1
  @backstage/integration-aws-node                                  0.1.10
  @backstage/integration-react                                     1.1.25
  @backstage/integration                                           1.9.1
  @backstage/plugin-api-docs                                       0.11.1
  @backstage/plugin-app-backend                                    0.3.62
  @backstage/plugin-app-node                                       0.1.14
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.6
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.9
  @backstage/plugin-auth-backend-module-github-provider            0.1.11
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.11
  @backstage/plugin-auth-backend-module-google-provider            0.1.11
  @backstage/plugin-auth-backend-module-guest-provider             0.1.0
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.9
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.11
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.7
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.4
  @backstage/plugin-auth-backend-module-okta-provider              0.0.7
  @backstage/plugin-auth-backend                                   0.22.0
  @backstage/plugin-auth-node                                      0.4.9
  @backstage/plugin-auth-react                                     0.0.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.11
  @backstage/plugin-catalog-backend                                1.18.0
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.1
  @backstage/plugin-catalog-import                                 0.10.7
  @backstage/plugin-catalog-node                                   1.8.0
  @backstage/plugin-catalog-react                                  1.11.0
  @backstage/plugin-catalog                                        1.18.0
  @backstage/plugin-events-node                                    0.3.0
  @backstage/plugin-github-actions                                 0.6.12
  @backstage/plugin-org                                            0.6.21
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.11
  @backstage/plugin-permission-backend                             0.5.37
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.25
  @backstage/plugin-permission-react                               0.4.21
  @backstage/plugin-proxy-backend                                  0.4.12
  @backstage/plugin-scaffolder-backend-module-azure                0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.4
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.4
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.4
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.6
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.4
  @backstage/plugin-scaffolder-backend-module-github               0.2.4
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.0
  @backstage/plugin-scaffolder-backend                             1.22.0
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.0
  @backstage/plugin-scaffolder-react                               1.8.1
  @backstage/plugin-scaffolder                                     1.19.0
  @backstage/plugin-search-backend-module-catalog                  0.1.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.18
  @backstage/plugin-search-backend-node                            1.2.18
  @backstage/plugin-search-backend                                 1.5.4
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.7
  @backstage/plugin-search                                         1.4.7
  @backstage/plugin-tech-radar                                     0.7.0
  @backstage/plugin-techdocs-backend                               1.10.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.6
  @backstage/plugin-techdocs-node                                  1.12.0
  @backstage/plugin-techdocs-react                                 1.2.0
  @backstage/plugin-techdocs                                       1.10.1
  @backstage/plugin-user-settings                                  0.8.2
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.1
  @backstage/theme                                                 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
The new backstage experience is more modular than before. If you use github features, you add the github modules. In your case, `@backstage/plugin-scaffolder-backend-module-github`.

**Comment by SeanoNET** [comment]
Thanks, now getting #23824

**Comment by camilaibs** [comment]
> Thanks, now getting https://github.com/backstage/backstage/issues/23824

@SeanoNET, thanks for responding so quickly.
Could we close this and ask to reopen the issue you have linked to?

**Comment by pedrovieiramiguez** [comment]
Sorry, but can someone provide some additional details about how to fix this problem? I tried looking into the [scaffolder-backend plugin](https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend) README file, but when it explains how to configure the scaffolder it points to a [non-existent page](https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/packages/backend/src/plugins/scaffolder.ts), so I assume it's outdated and the structures have changed.

If so, it would be great if someone could point me to a doc that explains how I can setup the latest Backstage version locally in a way that allows me to publish to GitHub! Thank you

**Comment by twanbeeren** [comment]
I have the same thing but with azure.

`Template action with ID 'publish:azure' is not registered.`

The publish azure is a built-in function and I have no Idea why it doesn't work anymore.

**Comment by awanlin** [comment]
@twanbeeren have you looked at this? https://backstage.io/docs/backend-system/building-backends/migrating#the-scaffolder-plugin:~:text=such%20as%20adding%20custom%20actions%2C%20read%20on

**Comment by twanbeeren** [comment]
It seems like my plugins/scaffolder.ts needs to become a legacyplugin (since my custom actions are referenced there).

```
const actions = [...builtInActions, createAzurePipelineAction({integrations}), getAzureRepoAction({integrations}), runAzurePipelineAction({integrations})];
  
  return await createRouter({
    actions,
    logger: env.logger,
    config: env.config,
    database: env.database,
    reader: env.reader,
    catalogClient,
    identity: env.identity,
  });
```

My backend/src/index.ts

`backend.add(legacyPlugin('customScaffolderActions', import('./plugins/scaffolder')));`

 I can't find a proper example on how to restructure my plugin to become a legacyplugin.

I might not yet fully understand the concept yet and how plugins should be used.

**Comment by awanlin** [comment]
You'll need to use `createBackendModule` and there is an example just below that link I shared on what that would look like.

Using `legacyPlugin` means that you would keep everything as is. It's just a stop gap and you aren't really migrated to the new backend fully, it's just a partial step forward.

**Comment by twanbeeren** [comment]
I guess that's not prefered then.

Further stuff I'll probably not ask here since this conversation it's not really part of this bug anymore

**Comment by awanlin** [comment]
Hi @AngelicaR-25, the documentation here should help: https://backstage.io/docs/features/software-templates/builtin-actions#installing-action-modules
