### ISSUE TITLE
🐛 Bug Report: TypeError: req.header is not a function in kubernetes backend plugin

### ISSUE THREAD

**Issue by stevez** [backstage/backstage#23999]
### 📜 Description

I found the exception happened in here: https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesProxy.ts#L175

The detailed error message is like this:

Error:
```
[/backstage-demo/node_modules/@backstage/plugin-kubernetes-backend/src/service/KubernetesProxy.ts:175]
[1]           const authHeader = req.header(HEADER_KUBERNETES_AUTH);

[1]                                  ^

[1] 

[1] 

[1] TypeError: req.header is not a function

[1]     at router ([/backstage-demo/node_modules/@backstage/plugin-kubernetes-backend/src/service/KubernetesProxy.ts:175:34]

[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

[1]     at async Object.getTarget (/development/backstage-demo/node_modules/http-proxy-middleware/dist/router.js:14:21)

[1]     at async HttpProxyMiddleware.applyRouter (/backstage-demo/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:110:29)

[1]     at async HttpProxyMiddleware.prepareProxyRequest (/backstage-demo/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:97:13)

[1]     at async HttpProxyMiddleware.handleUpgrade (/backstage-demo/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:62:44)
```

### 👍 Expected behavior

The server app should run as normal

### 👎 Actual Behavior with Screenshots

The server stop running after the exception thrown

### 👟 Reproduction steps

1. start the backstage app with kubernetes plugin installed
2. connect to kubernetes
3. do some operation, maybe for the error pods
4. the page will show error, 
5. when refresh, the app still show errors.

### 🖥️ Your Environment

Mac 13.6.3 (22G436)
local docker env: colima / docker
Backstage app was created by @backstage/create-app@0.5.10
kubernetes plugin: @backstage/plugin-kubernetes-backend : 0.16.3
node: 18.17.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Closing this as fixed :tada:
