### ISSUE TITLE
🐛 Bug Report: Issue with image in explore-plugin

### ISSUE THREAD

**Issue by ruieloi** [backstage/backstage#24079]
### 📜 Description

Trying to use the explore-plugin but can't make the image to work.
Got a "Warning: Failed prop type: Material-UI: Either `children`, `image`, `src` or `component` prop must be specified." error in console.

I followed the README.md of the plugin.
The image link it's a azure storage with read access and I added in app-config.yaml

```
reading:
 allow:
  - host: "[mystorage].blob.core.windows.net"
csp: 
  img-src: 
    - "https://[mystorage].blob.core.windows.net"
```

Am I missing something?

Thank you!

### 👍 Expected behavior

It should present the image of the tool and no console error.

### 👎 Actual Behavior with Screenshots

Plugin loads the information but not the image.
Got a "Warning: Failed prop type: Material-UI: Either `children`, `image`, `src` or `component` prop must be specified." error in console.

![image](https://github.com/backstage/backstage/assets/2378539/94547314-72f2-45a1-b670-34a31486f168)

```
react.development.js:220 Warning: Failed prop type: Material-UI: Either `children`, `image`, `src` or `component` prop must be specified.
    at CardMedia (webpack-internal:///../../node_modules/@material-ui/core/esm/CardMedia/CardMedia.js:43:24)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:31)
    at div
    at Paper (webpack-internal:///../../node_modules/@material-ui/core/esm/Paper/Paper.js:48:23)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:31)
    at Card (webpack-internal:///../../node_modules/@material-ui/core/esm/Card/Card.js:28:23)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:31)
    at ToolCard (webpack-internal:///../../node_modules/@backstage/plugin-explore/dist/esm/ToolExplorerContent-B8M06fmW.esm.js:62:21)
    at div
    at StyledComponent (webpack-internal:///../../node_modules/@material-ui/styles/esm/styled/styled.js:95:28)
    at ItemCardGrid (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:6527:11)
    at Body (webpack-internal:///../../node_modules/@backstage/plugin-explore/dist/esm/ToolExplorerContent-B8M06fmW.esm.js:88:84)
    at article
    at Content (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4032:11)
    at ToolExplorerContent (webpack-internal:///../../node_modules/@backstage/plugin-explore/dist/esm/ToolExplorerContent-B8M06fmW.esm.js:117:320)
    at AnalyticsContext (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:75:11)
    at PluginErrorBoundary (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:416:5)
    at Suspense
    at Result (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:513:21)
    at article
    at Content (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4032:11)
    at RoutedTabs (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4147:11)
    at main
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:44:24)
    at Page (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:6554:11)
    at ExploreLayout (webpack-internal:///../../node_modules/@backstage/plugin-explore/dist/esm/index-CFTA3J1_.esm.js:180:11)
    at ExplorePage
    at RenderedRoute (webpack-internal:///../../node_modules/react-router/dist/index.js:554:5)
    at ExplorePage (webpack-internal:///../../node_modules/@backstage/plugin-explore/dist/esm/index-C31wDFdC.esm.js:58:77)
    at RoutableExtensionWrapper (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:450:31)
    at AnalyticsContext (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:75:11)
    at PluginErrorBoundary (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:416:5)
    at Suspense
    at Result (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:513:21)
    at RenderedRoute (webpack-internal:///../../node_modules/react-router/dist/index.js:554:5)
    at FlatRoutes (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:4067:82)
    at div
    at StyledComponent (webpack-internal:///../../node_modules/@material-ui/styles/esm/styled/styled.js:95:28)
    at SidebarPinStateProvider (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4974:11)
    at SidebarPage (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:5231:82)
    at Root (webpack-internal:///./src/components/Root/Root.tsx:125:17)
    at SignInPageWrapper (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2376:14)
    at Router (webpack-internal:///../../node_modules/react-router/dist/index.js:1112:15)
    at BrowserRouter (webpack-internal:///../../node_modules/react-router-dom/dist/index.js:666:5)
    at AppRouter (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2392:139)
    at Suspense
    at RoutingProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2948:3)
    at CssBaseline (webpack-internal:///../../node_modules/@material-ui/core/esm/CssBaseline/CssBaseline.js:67:31)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:31)
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:44:24)
    at Provider (webpack-internal:///./src/App.tsx:137:26)
    at AppThemeProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:3147:29)
    at AppContextProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:3019:3)
    at ApiProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:97:11)
    at Provider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:3849:25)
    at App
```

### 👟 Reproduction steps

1. Go to "Explore" page  (/explore)

### 📃 Provide the context for the Bug.

Got a API that is retrieving the json tool data

```json
[
{
"title": "Datadog",
"description": "Monitoring tool",
"url": "https://www.datadoghq.com/",
"image": "https://[mystorage].blob.core.windows.net/tools/img/datadog_icon.jpg",
"tags": [
"monitoring",
"security",
"devops"
]
}
]
```

### 🖥️ Your Environment

```
OS:   Windows_NT 10.0.22631 - win32/x64
node: v18.12.1
yarn: 1.22.22
cli:  0.26.2 (installed)
backstage:  1.25.1

Dependencies:
  @backstage/app-defaults                                          1.5.3
  @backstage/backend-app-api                                       0.4.5, 0.5.9, 0.6.2
  @backstage/backend-common                                        0.15.2, 0.18.5, 0.19.9, 0.20.0, 0.21.6
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.9
  @backstage/backend-plugin-api                                    0.5.4, 0.6.16
  @backstage/backend-tasks                                         0.5.21
  @backstage/backend-test-utils                                    0.3.6
  @backstage/catalog-client                                        1.6.3
  @backstage/catalog-model                                         1.2.0, 1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.26.2
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.3
  @backstage/core-compat-api                                       0.2.3
  @backstage/core-components                                       0.12.4, 0.11.2, 0.12.5, 0.13.10, 0.13.9, 0.14.3
  @backstage/core-plugin-api                                       1.0.6, 1.9.1
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.3
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.25
  @backstage/integration                                           1.9.1
  @backstage/plugin-adr-common                                     0.2.21
  @backstage/plugin-adr                                            0.6.16
  @backstage/plugin-api-docs                                       0.11.3
  @backstage/plugin-app-backend                                    0.3.64
  @backstage/plugin-app-node                                       0.1.16
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.8
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.8
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.11
  @backstage/plugin-auth-backend-module-github-provider            0.1.13
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.13
  @backstage/plugin-auth-backend-module-google-provider            0.1.13
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.11
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.13
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.9
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.7
  @backstage/plugin-auth-backend-module-okta-provider              0.0.9
  @backstage/plugin-auth-backend                                   0.22.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.11
  @backstage/plugin-auth-react                                     0.0.3
  @backstage/plugin-azure-devops-backend                           0.6.3
  @backstage/plugin-azure-devops-common                            0.4.0
  @backstage/plugin-azure-devops                                   0.4.2
  @backstage/plugin-azure-sites-backend                            0.3.3
  @backstage/plugin-azure-sites-common                             0.1.3
  @backstage/plugin-azure-sites                                    0.1.22
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.24
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.14
  @backstage/plugin-catalog-backend                                1.21.0
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.3
  @backstage/plugin-catalog-import                                 0.10.9
  @backstage/plugin-catalog-node                                   1.11.0
  @backstage/plugin-catalog-react                                  1.2.1, 1.11.2
  @backstage/plugin-catalog                                        1.18.2
  @backstage/plugin-events-node                                    0.3.2
  @backstage/plugin-explore-backend                                0.0.26
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.37
  @backstage/plugin-explore                                        0.4.19
  @backstage/plugin-github-actions                                 0.6.14
  @backstage/plugin-home-react                                     0.1.11
  @backstage/plugin-home                                           0.7.2
  @backstage/plugin-org                                            0.6.23
  @backstage/plugin-permission-backend                             0.5.40
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.27
  @backstage/plugin-permission-react                               0.4.21
  @backstage/plugin-playlist-backend                               0.3.20
  @backstage/plugin-playlist-common                                0.1.15
  @backstage/plugin-playlist                                       0.2.7
  @backstage/plugin-proxy-backend                                  0.4.14
  @backstage/plugin-scaffolder-backend-module-azure                0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.8
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.6
  @backstage/plugin-scaffolder-backend-module-github               0.2.6
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.2
  @backstage/plugin-scaffolder-backend-module-yeoman               0.2.37
  @backstage/plugin-scaffolder-backend                             1.22.3
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node-test-utils                     0.1.2
  @backstage/plugin-scaffolder-node                                0.4.2
  @backstage/plugin-scaffolder-react                               1.8.3
  @backstage/plugin-scaffolder                                     1.19.2
  @backstage/plugin-search-backend-module-catalog                  0.1.21
  @backstage/plugin-search-backend-module-explore                  0.1.20
  @backstage/plugin-search-backend-module-pg                       0.5.25
  @backstage/plugin-search-backend-module-techdocs                 0.1.21
  @backstage/plugin-search-backend-node                            1.2.20
  @backstage/plugin-search-backend                                 1.5.6
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.9
  @backstage/plugin-search                                         1.4.9
  @backstage/plugin-shortcuts                                      0.3.22
  @backstage/plugin-sonarqube-backend                              0.2.18
  @backstage/plugin-sonarqube-react                                0.1.14
  @backstage/plugin-sonarqube                                      0.7.15
  @backstage/plugin-tech-radar                                     0.7.2
  @backstage/plugin-techdocs-backend                               1.10.3
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.8
  @backstage/plugin-techdocs-node                                  1.12.2
  @backstage/plugin-techdocs-react                                 1.2.2
  @backstage/plugin-techdocs                                       1.10.3
  @backstage/plugin-todo-backend                                   0.3.15
  @backstage/plugin-todo                                           0.2.37
  @backstage/plugin-user-settings                                  0.8.4
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.3
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Yeah it seems to me that the only way that could happen, was if it actually didn't have an image specified at all in the source data. I'd set a breakpoint inside `ToolExplorerContent` and looking at what comes into it.

**Comment by ruieloi** [comment]
Your right, it was a typo issue in the mapping code. After fixing it all is working.
Thank you
