### ISSUE TITLE
Could not find a service to retrieve profileInfo inside the module , if tried to use useAPI, getting the error `Cannot use import statement outside a module`(New backend system)

### ISSUE THREAD

**Issue by Vikram-arc** [backstage/backstage#24279]
### 📜 Description

I need to use the  identityApiRef **(import { useApi, identityApiRef } from '@backstage/core-plugin-api';)** in my module, the purpose is to make external api calls based on the user profile information. 
The `**New backend System**` of backstage does not have an examples for the use of identityAPI within the backend-plugin module. 
I clearly understand the **useAPI** function cannot be used in the **backend-plugin-module** , but I need a solution/example to call the backstage-identity service from the module.

/Users/X/DE/backstage-plugins/node_modules/@backstage/core-plugin-api/dist/index.esm.js:1
[1] import { createVersionedContext, createVersionedValueMap, getOrCreateGlobalSingleton, useVersionedContext } from '@backstage/version-bridge';
[1] ^^^^^^
[1]
[1] SyntaxError: Cannot use import statement outside a module
[1]     at internalCompileFunction (node:internal/vm:73:18)
[1]     at wrapSafe (node:internal/modules/cjs/loader:1176:20)
[1]     at Module._compile (node:internal/modules/cjs/loader:1218:27)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[1]     at Object.newLoader [as .js] (/Users/X/DE/backstage-plugins/node_modules/pirates/lib/index.js:121:7)
[1]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[1]     at Module._load (node:internal/modules/cjs/loader:958:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[1]     at require (node:internal/modules/cjs/helpers:110:18)
[1]     at Object.<anonymous> (/Users/X/DE/backstage-plugins/plugins/custom-catalog-backend-module-backend/src/hooks/ComponentProvider.ts:16:14)
[1]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[1]     at Module._compile (/Users/X/DE/backstage-plugins/node_modules/pirates/lib/index.js:117:24)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[1]     at Object.newLoader [as .ts] (/Users/X/DE/backstage-plugins/node_modules/pirates/lib/index.js:121:7)
[1]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[1]     at Module._load (node:internal/modules/cjs/loader:958:12)
[1]
[1] Node.js v18.14.1

### 👍 Expected behavior

I need a solution/example to call the backstage-identity service from the module.

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

...
import { useApi, identityApiRef } from '@backstage/core-plugin-api';
import { IdentityService, LoggerService,} from '@backstage/backend-plugin-api';
... 

async run(): Promise<void> {

    if (!this.connection) {
      throw new Error('Not initialized');
    }
    const profileAPI = useApi(identityApiRef);
    console.log('Profile', profileAPI.getProfileInfo);
...

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
`core-plugin-api` is a frontend package, and cannot at all be used from the backend. Same with all hooks in general, those are React concepts.

In the backend you use the `coreServices.auth` and `coreServices.httpAuth` services to extract user information. For example: https://github.com/backstage/backstage/blob/8ae3b45236463835c0c0044b715769a09f6173bd/plugins/search-backend/src/service/router.ts#L196

**Comment by Vikram-arc** [comment]
Thank you @freben , I think the example shows the auth implementation within the router. My requirement is to call the profileinfo/auth service from the Entityprovider class (https://backstage.io/docs/features/software-catalog/external-integrations/)

**Comment by Vikram-arc** [comment]
Trying to access the authService inside the run function in the above reference   **async run(): Promise<void> {**

Example <img width="1717" alt="image" src="https://github.com/backstage/backstage/assets/52925592/2a2d74fc-3296-47d2-843f-1b027e04317c">

**Comment by Rugvip** [comment]
User profile information is not available in the backend in the same way as it is in the frontend. The most common way to access that data is to make sure it's present in `User` entities in the catalog, and then fetch those via the catalog api.

One example of consuming that information is the search backend, it accesses the information from an entity here: https://github.com/backstage/backstage/blob/98d3f2fa31680b782caddc7d328e71e178ccddab/plugins/search-backend-module-catalog/src/collators/defaultCatalogCollatorEntityTransformer.ts#L20-L37

And does the actual fetching from the catalog here: https://github.com/backstage/backstage/blob/bb368a598beb1b667181f80f9d44ae201cae6c6d/plugins/search-backend-module-catalog/src/collators/DefaultCatalogCollatorFactory.ts#L150-L157
