### ISSUE TITLE
🐛 Bug Report: Gitlab discovery with SAML users and groups

### ISSUE THREAD

**Issue by netvolart** [backstage/backstage#24361]
### 📜 Description

I've configured my dev backstage app with GitLab authentication, and added my user
```
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: my_gitlab_username
spec:
  memberOf: [guests]
```
Authentication was successful. 

After that, I wanted to discover Users, Groups and Components from GitLab
```
catalog:
  providers:
    gitlab:
      gitlab:
        host: gitlab.com
        group: mygroup
        orgEnabled: true
        branch: main 
        schedule: 
          frequency: { minutes: 15 }
          timeout: { minutes: 3 }
        rules:
          - allow: [ Component, System, API, Group, User, Resource, Location, Domain, Template ]


integrations:
  gitlab:
    - host: gitlab.com
      token: token
```
I've also added 
```
backend.add(import('@backstage/plugin-search-backend/alpha'));
```
to index.ts

### 👍 Expected behavior

See a list of users and groups discovered imported from GitLab in a Software Catalog.

### 👎 Actual Behavior with Screenshots

 I see discovered components, but not Users and Groups. But for my user, the specified as a Kind: User I see even photo.

In logs:
```
[1] 2024-04-18T18:36:10.040Z catalog-gitlab warn Source GitlabOrgDiscoveryEntityProvider:gitlab detected conflicting entityRef user:default/my_gitlab_username already referenced by file:/IDP/backstage-app/examples/org.yaml and now also GitlabOrgDiscoveryEntityProvider:gitlab
[1] 2024-04-18T18:39:01.036Z catalog-gitlab warn Task timed out and was lost: GitlabDiscoveryEntityProvider:gitlab:refresh
```
### 👟 Reproduction steps

```
npx @backstage/create-app@latest
cd backstage
add    "@backstage/plugin-auth-backend-module-gitlab-provider": "^0.1.14",
add     "@backstage/plugin-catalog-backend-module-gitlab": "^0.3.15",
add.    config from description
start    yarn dev
```

### 📃 Provide the context for the Bug.

Trying to start using backstage

### 🖥️ Your Environment

```yarn backstage-cli info
yarn run v1.22.19
$ /Users/artem/dev/IDP/backstage-app/node_modules/.bin/backstage-cli info
OS:   Darwin 23.0.0 - darwin/arm64
node: v20.9.0
yarn: 1.22.19
cli:  0.26.3 (installed)
backstage:  1.26.0

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.7.0
  @backstage/backend-common                                        0.21.7
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.17
  @backstage/backend-tasks                                         0.5.22
  @backstage/catalog-client                                        1.6.4
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.3
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.14.4
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           1.10.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-guest-provider             0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12
  @backstage/plugin-auth-react                                     0.1.0
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.15
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-github-actions                                 0.6.15
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.14
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.4
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.22
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-tech-radar                                     0.7.3
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by BillKlineVT** [comment]
I believe the org discovery feature with the new backend is being moved to a separate plugin/module called GitLabOrgDiscoveryEntityProvider (@backstage/plugin-catalog-backend-module-gitlab-org) 

See https://github.com/backstage/backstage/pull/23373

Eagerly awaiting that PR to be merged since I am seeing the same issue as you are.

**Comment by camilaibs** [comment]
Hi @BillKlineVT 👋🏻 , could you please confirm if this issue can be closed?

**Comment by BillKlineVT** [comment]
> Hi @BillKlineVT 👋🏻 , could you please confirm if this issue can be closed?

I see issue #23373 got merged and will be in 1.27.0 coming out in May, so can check it when that is released.

**Comment by camilaibs** [comment]
Hi @BillKlineVT ,
We are closing this issue for now, please let us know if you have any troubles after the release 1.27.0 🙌🏻 .

**Comment by netvolart** [comment]
Hi @BillKlineVT . Could you help here?
I am trying to set up a new org plugin, but my dev server is not starting.
What am I missing?


```
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/artem/dev/IDP/backstage-app/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] Loading config from MergedConfigSource{FileConfigSource{path="/Users/artem/dev/IDP/backstage-app/app-config.yaml"}, FileConfigSource{path="/Users/artem/dev/IDP/backstage-app/app-config.local.yaml"}, EnvConfigSource{count=0}}
[1] 2024-05-09T10:37:11.043Z backstage info Found 4 new secrets in config that will be redacted
[1] 2024-05-09T10:37:11.049Z rootHttpRouter info Listening on :7007
[1] 2024-05-09T10:37:11.051Z backstage warn Generated a secret for service-to-service authentication: DEVELOPMENT USE ONLY.
[1] 2024-05-09T10:37:11.127Z permission warn Permission backend started with permissions disabled. Enable permissions by setting permission.enabled=true.
[1] 2024-05-09T10:37:11.130Z auth info Configuring "database" as KeyStore provider
[1] 2024-05-09T10:37:11.130Z techdocs info Creating Local publisher for TechDocs
[1] 2024-05-09T10:37:11.134Z scaffolder info Starting scaffolder with the following actions enabled fetch:plain, fetch:plain:file, fetch:template, debug:log, debug:wait, catalog:register, catalog:fetch, catalog:write, fs:delete, fs:rename
[1] 2024-05-09T10:37:11.137Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog
[1] 2024-05-09T10:37:11.137Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs
[1] 2024-05-09T10:37:11.137Z search info Starting all scheduled search tasks.
[1] /Users/artem/dev/IDP/backstage-app/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:87
[1]       throw new Error(
[1]             ^
[1]
[1]
[1] Error: No extension point or service available for the following ref(s): serviceRef{events.service}
[1]     at BackendInitializer.getInitDeps_fn (/Users/artem/dev/IDP/backstage-app/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:87:13)
[1]     at <anonymous> (/Users/artem/dev/IDP/backstage-app/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:261:34)
[1]     at processNode (/Users/artem/dev/IDP/backstage-app/node_modules/@backstage/backend-app-api/src/lib/DependencyGraph.ts:234:22)
[1]     at async Promise.all (index 1)
[1]     at processMoreNodes (/Users/artem/dev/IDP/backstage-app/node_modules/@backstage/backend-app-api/src/lib/DependencyGraph.ts:226:7)
[1]     at _DependencyGraph.parallelTopologicalTraversal (/Users/artem/dev/IDP/backstage-app/node_modules/@backstage/backend-app-api/src/lib/DependencyGraph.ts:242:5)
[1]     at <anonymous> (/Users/artem/dev/IDP/backstage-app/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:259:11)
[1]     at async Promise.all (index 5)
[1]     at BackendInitializer.doStart_fn (/Users/artem/dev/IDP/backstage-app/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:230:5)
[1]     at BackendInitializer.start (/Users/artem/dev/IDP/backstage-app/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:149:5)
[1]     at BackstageBackend.start (/Users/artem/dev/IDP/backstage-app/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:42:11)
[1]
[1] Node.js v20.9.0
```

**Comment by mickfeech** [comment]
As soon as I add
`backend.add(import('@backstage/plugin-catalog-backend-module-gitlab-org'));` per the new documentation I'm also getting the same errors.

**Comment by mickfeech** [comment]
It's included in the [1.27.next-2 release](https://github.com/backstage/backstage/releases/tag/v1.27.0-next.2)

**Comment by netvolart** [comment]
> Is this out yet? The last comment in the PR that this was merged in said it'd be part of 1.27.0 coming out May 14, 2024
It's in the documentation. Just curious how to set GitLab user's discovery for authentication if this new plugin doesn't work and the old one does as well. Probably just wait for May 14 for a stable version.

**Comment by BillKlineVT** [comment]
Ah, I wasn't tracking the early releases.  I'm certainly new to working with this project but one thing I'm uncertain on is when to use the /alpha at the end of the backend.add commands with referencing the plugin.  Maybe give that a shot?

**Comment by awanlin** [comment]
In this case it doesn't have an `alpha` export so you won't need that, you would have seen a type error if it was needed though.

I think the root problem is that this new provided supports the events framework but it might not handle the case where you don't have that setup. I'm making this assumptions based on the mention of `serviceRef{events.service}` in the error that @netvolart shared.

To validate this can one of you try this:

1. Run `yarn --cwd packages/backend add @backstage/plugin-events-backend`
2. Then add this to your backend `index.ts` file: `backend.add(import('@backstage/plugin-events-backend/alpha'));`

@elaine-mattos any chance you can help out here?

**Comment by netvolart** [comment]
@awanlin 
I've tied this. The same error.


> To validate this can one of you try this:
> 
> 1. Run `yarn --cwd packages/backend add @backstage/plugin-events-backend`
> 2. Then add this to your backend `index.ts` file: `backend.add(import('@backstage/plugin-events-backend/alpha'));`

I've tied, but the error is the same.

I've also tried to install @backstage/plugin-events-backend-module-gitlab and add backend.add(eventsModuleGitlabEventRouter()); (even if I am not sure if I need this events for the scheduled discovery). The error is the same again

**Comment by awanlin** [comment]
OK, thanks for trying @netvolart, still feel like it's related to events. You did a full version bump to the `1.27.0-next.2` release, right? I would try that too but keep the package I mentioned in place

**Comment by netvolart** [comment]
I am also new to the project. Not sure. I've run a bump like

```
yarn backstage-cli versions:bump
```
Looks good except:

```

Version bump complete!


Error: Version bump failed for @backstage/plugin-catalog-backend-module-gitlab

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
yarn backstage-cli info
yarn run v1.22.19
$ /Users/artem/dev/IDP/backstage-app/node_modules/.bin/backstage-cli info
OS:   Darwin 23.0.0 - darwin/arm64
node: v20.9.0
yarn: 1.22.19
cli:  0.26.4 (installed)
backstage:  1.26.5

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.0.0-nightly-20240509021548, 0.7.2
  @backstage/backend-common                                        0.0.0-nightly-20240509021548, 0.21.7
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.0.0-nightly-20240509021548, 0.6.17
  @backstage/backend-tasks                                         0.0.0-nightly-20240509021548, 0.5.22
  @backstage/catalog-client                                        0.0.0-nightly-20240509021548, 1.6.4
  @backstage/catalog-model                                         0.0.0-nightly-20240509021548, 1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.4
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.14.6
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           0.0.0-nightly-20240509021548, 1.10.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-guest-provider             0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.0.0-nightly-20240509021548, 0.4.12
  @backstage/plugin-auth-react                                     0.1.1
  @backstage/plugin-catalog-backend-module-gitlab-org              0.0.0-nightly-20240423021331
  @backstage/plugin-catalog-backend-module-gitlab                  0.0.0-nightly-20240509021548, 0.3.15
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 0.0.0-nightly-20240509021548, 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   0.0.0-nightly-20240509021548, 1.11.1
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-backend-module-gitlab                   0.2.3
  @backstage/plugin-events-backend                                 0.3.4
  @backstage/plugin-events-node                                    0.0.0-nightly-20240509021548, 0.3.3
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.14
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.0.0-nightly-20240509021548, 0.7.28
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.5
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.23
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 0.59s.
```

**Comment by awanlin** [comment]
Might be safer to wait for the release next week, really need to hear @elaine-mattos thoughts on this. I don't use GitLab at all so can't really test this.

You could run `yarn backstage-cli versions:bump --release next` to use the weekly next release though, you might need to run it twice as that version failed error has been fixed

**Comment by netvolart** [comment]
@awanlin It works !!! Discovering users from GitLab. 
Fantastic.
Thank you for your help and for the education.

**Comment by elaine-mattos** [comment]
> In this case it doesn't have an `alpha` export so you won't need that, you would have seen a type error if it was needed though.
> 
> I think the root problem is that this new provided supports the events framework but it might not handle the case where you don't have that setup. I'm making this assumptions based on the mention of `serviceRef{events.service}` in the error that @netvolart shared.
> 
> To validate this can one of you try this:
> 
> 1. Run `yarn --cwd packages/backend add @backstage/plugin-events-backend`
> 2. Then add this to your backend `index.ts` file: `backend.add(import('@backstage/plugin-events-backend/alpha'));`
> 
> @elaine-mattos any chance you can help out here?

Hi guys, 

I'll try and take a look at it, however I'm on vacation until Monday and don't have a computer that I can use right now...

**Comment by awanlin** [comment]
@elaine-mattos, this looks to be resolved, enjoy your vacation!!! 🌴 

@netvolart glad to hear it's working 👍 

@mickfeech can you make sure you are fully on the next release? That looks to be the solution here.
