### ISSUE TITLE
🐛 Bug Report: `legacyPlugins` unreachable when migrating to 1.25

### ISSUE THREAD

**Issue by mspiegel31** [backstage/backstage#24517]
### 📜 Description

I am attempting to follow the migration guide for the new backend system (https://backstage.io/docs/backend-system/building-backends/migrating).  I am moving from `1.23` -> `1.25`.  I have elected to start with just migrating the `packages/backend/src/index.ts` file to use the new style backend features, i.e.:

```
const backend = createBackend();

// backstage core utils
backend.add(legacyPlugin('app', import('./plugins/app')));
backend.add(legacyPlugin('auth', import('./plugins/auth')));
backend.add(legacyPlugin('catalog',import('./plugins/catalog')));
...
```

however, when running locally with `yarn dev` all attempts to make requests to these plugins are returning `404` errors.  Is there a nuance to this migration guide I am missing?

### 👍 Expected behavior

the backstage application should start up as normal with plugins defined in the `packages/backend/src/plugins`

### 👎 Actual Behavior with Screenshots

the application starts, however core routes are unreachable

![Screenshot 2024-04-25 at 4 56 57 PM](https://github.com/backstage/backstage/assets/5898525/e7209a72-5db7-4191-bdf6-8ff85438141c)
![Screenshot 2024-04-25 at 4 00 20 PM](https://github.com/backstage/backstage/assets/5898525/0bea4015-de15-4a54-b272-959ad3a8557b)

### 👟 Reproduction steps

1. on a backstage instance running version `1.23.4`, run `yarn backstage-cli versions:bump --release 1.25.2`
1. modify `packages/backend/src/index.ts` to contain the following contents:

```ts
const legacyPlugin = makeLegacyPlugin({
  cache: coreServices.cache,
  config: coreServices.rootConfig,
  database: coreServices.database,
  discovery: coreServices.discovery,
  logger: coreServices.logger,
  permissions: coreServices.permissions,
  scheduler: coreServices.scheduler,
  tokenManager: coreServices.tokenManager,
  reader: coreServices.urlReader,
  identity: coreServices.identity,
},
  {
    logger: log => {
      const winstonLogger = loggerToWinstonLogger(log);
      winstonLogger.defaultMeta = {
        ...winstonLogger.defaultMeta,
        // "service" is a reserved word for datadog logging.
        // we need to override the logging for our datadog setup
        // see https://docs.datadoghq.com/logs/log_configuration/attributes_naming_convention/#reserved-attributes
        service: process.env.AppName ?? 'backstage',
      }
      return winstonLogger;

    },
    cache: cache => cacheToPluginCacheManager(cache),
  }
);

const backend = createBackend();

// backstage core utils
backend.add(legacyPlugin('app', import('./plugins/app')));
backend.add(legacyPlugin('auth', import('./plugins/auth')));
backend.add(legacyPlugin('catalog',import('./plugins/catalog')));
backend.add(legacyPlugin('proxy', import('./plugins/proxy')));
backend.add(legacyPlugin('scaffolder', import('./plugins/scaffolder')));
backend.add(legacyPlugin('search', import('./plugins/search')));
backend.add(legacyPlugin('techdocs', import('./plugins/techdocs')));
backend.add(legacyPlugin('techradar', import('./plugins/techradar')));
```

3. observe error

### 🖥️ Your Environment

```sh
yarn run v1.22.19
OS:   Darwin 23.0.0 - darwin/arm64
node: v18.14.0
yarn: 1.22.19
cli:  0.26.4 (installed)
backstage:  1.25.2

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.5.14, 0.7.1
  @backstage/backend-common                                        0.19.9, 0.21.7
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.17
  @backstage/backend-tasks                                         0.5.22
  @backstage/backend-test-utils                                    0.3.7
  @backstage/catalog-client                                        1.6.4
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.4
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.5
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.31
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           1.10.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12
  @backstage/plugin-auth-react                                     0.1.1
  @backstage/plugin-bitbucket-cloud-common                         0.2.18
  @backstage/plugin-catalog-backend-module-bitbucket-cloud         0.2.4
  @backstage/plugin-catalog-backend-module-github                  0.5.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.4
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.1
  @backstage/plugin-catalog-unprocessed-entities                   0.2.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-cost-insights-common                           0.1.2
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.4
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.23
  @backstage/plugin-search-backend-module-pg                       0.5.26
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7, 1.0.8
Done in 0.63s.

```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Do you have a `backend.start()` as well at the end? Could be what's missing although I wouldn't really expect it given the error. Looks alright otherwise though

**Comment by mspiegel31** [comment]
> Do you have a `backend.start()` as well at the end? Could be what's missing although I wouldn't really expect it given the error. Looks alright otherwise though

@Rugvip yup, there's a `backend.start()` call right after all the `backend.add(...)` statements.

does the new built-in authentication middleware return `404`s when the request isn't authenticated?  I get this response when trying to hit the backend API route through the terminal:

```
$ http --body http://localhost:7007/api/catalog/entities                                                                                                                                ue1.staging-ue1.staging
{
    "error": {
        "body": {
            "error": {
                "message": "Request failed with status 404 Not Found",
                "name": "Error"
            },
            "response": {
                "statusCode": 404
            }
        },
        "cause": {
            "message": "Request failed with status 404 Not Found",
            "name": "Error"
        },
        "message": "Request failed with 404 Not Found",
        "name": "ResponseError",
        "response": {
            "size": 0,
            "timeout": 0
        },
        "stack": "ResponseError: Request failed with 404 Not Found\n    at Function.fromResponse (/Users/michaelspiegel/development/production/back-of-house/node_modules/@backstage/errors/src/errors/ResponseError.ts:76:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at PermissionClient.makeRequest (/Users/michaelspiegel/development/production/back-of-house/node_modules/@backstage/plugin-permission-common/src/PermissionClient.ts:160:13)\n    at AuthorizedEntitiesCatalog.entities (/Users/michaelspiegel/development/production/back-of-house/node_modules/@backstage/plugin-catalog-backend/src/service/AuthorizedEntitiesCatalog.ts:55:7)\n    at <anonymous> (/Users/michaelspiegel/development/production/back-of-house/node_modules/@backstage/plugin-catalog-backend/src/service/createRouter.ts:135:40)",
        "statusCode": 404,
        "statusText": "Not Found"
    },
    "request": {
        "method": "GET",
        "url": "/entities"
    },
    "response": {
        "statusCode": 404
    }
}
```

I have the `dangerouslyDisableDefaultAuthPolicy: true` set in my `app-config.yaml`

```yaml
backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  auth:
    dangerouslyDisableDefaultAuthPolicy: true
```

**Comment by mspiegel31** [comment]
@Rugvip ahh, found the issue.  I had forgotten to migrate the permissions backend as well.  I needed to add the lines

```ts
// permissions + permission policy
backend.add(import('@backstage/plugin-permission-backend/alpha'));
backend.add(
  import('@internal/plugin-custom-permissions-backend'),
);

```
and now things are working as expected.  Sorry for the noise, closing!
