### ISSUE TITLE
🐛 Bug Report: Github Auth not working on backstage version 1.26.0

### ISSUE THREAD

**Issue by prasoon-pxc** [backstage/backstage#24559]
### 📜 Description

I have created new backstage instance using `npx @backstage/create-app@latest` and Now I want to add auth provider for Github , I am following this [doc](https://backstage.io/docs/auth/github/provider) and created Github App with 
**HomePage-URL:** **http://localhost:3000**
**CallBack-URL:** http://localhost:7007/api/auth/github/handler/frame

Also, configured Auth-setting in `app-config.yaml` like below:

```
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    github:
      development:
        clientId: "my-plain-test-id"
        clientSecret: "my-plain-text-secret"
```

Also, change sign-in page in frontend, like this:

```
import {
  SignInProviderConfig
  SignInPage,
} from '@backstage/core-components';
import { githubAuthApiRef } from '@backstage/core-plugin-api';

const app = createApp({
  apis,
  components: {
  SignInPage: props => (
    <SignInPage
      {...props}
      auto
      provider={{
        id: 'github-auth-provider',
        title: 'GitHub',
        message: 'Sign in using GitHub',
        apiRef: githubAuthApiRef,
      }}
    />
  ),
},
```

But, when I am trying to sign in frontend, it is giving below error:

```
{"error":{"name":"NotFoundError","message":"Unknown auth provider 'github'","stack":"NotFoundError: Unknown auth provider 'github'\n    at <anonymous> (/home/il58d0/new-backstagea-app/node_modules/@backstage/plugin-auth-backend/src/service/router.ts:162:11)\n    at handleReturn (/home/il58d0/new-backstagea-app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /home/il58d0/new-backstagea-app/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle [as handle_request] (/home/il58d0/new-backstagea-app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/il58d0/new-backstagea-app/node_modules/express/lib/router/index.js:328:13)\n    at /home/il58d0/new-backstagea-app/node_modules/express/lib/router/index.js:286:9\n    at param (/home/il58d0/new-backstagea-app/node_modules/express/lib/router/index.js:365:14)\n    at param (/home/il58d0/new-backstagea-app/node_modules/express/lib/router/index.js:376:14)\n    at Function.process_params (/home/il58d0/new-backstagea-app/node_modules/express/lib/router/index.js:421:3)\n    at next (/home/il58d0/new-backstagea-app/node_modules/express/lib/router/index.js:280:10)\n    at /home/il58d0/new-backstagea-app/node_modules/express/lib/router/index.js:646:15\n    at next (/home/il58d0/new-backstagea-app/node_modules/express/lib/router/index.js:265:14)\n    at Function.handle (/home/il58d0/new-backstagea-app/node_modules/express/lib/router/index.js:175:3)\n    at router (/home/il58d0/new-backstagea-app/node_modules/express/lib/router/index.js:47:12)\n    at handleReturn (/home/il58d0/new-backstagea-app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at router (/home/il58d0/new-backstagea-app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)"},"request":{"method":"GET","url":"/api/auth/github/start?scope=read%3Auser&origin=http%3A%2F%2Flocalhost%3A3000&flow=popup&env=development"},"response":{"statusCode":404}}
```

### 👍 Expected behavior

It should allow to sign-in using Github

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/106815018/d2255a45-61e1-4b07-b389-8cc92c3c4585)

### 👟 Reproduction steps

Create backstage with : `npx @backstage/create-app@latest`
And configure Github Authentication provider as described in [doc](https://backstage.io/docs/auth/github/provider)

### 🖥️ Your Environment

```
yarn run v1.22.21
$ /home/il58d0/new-backstagea-app/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.0-105-generic - linux/x64
node: v18.18.2
yarn: 1.22.21
cli:  0.26.4 (installed)
backstage:  1.26.0

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.7.1
  @backstage/backend-common                                        0.21.7
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.17
  @backstage/backend-tasks                                         0.5.22
  @backstage/catalog-client                                        1.6.4
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.4
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.14.5
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           1.10.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-guest-provider             0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12
  @backstage/plugin-auth-react                                     0.1.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-github-actions                                 0.6.16
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.14
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.4
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.23
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-tech-radar                                     0.7.4
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 0.71s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by prasoon-pxc** [comment]
After adding `backend.add(import('@backstage/plugin-auth-backend-module-github-provider'));`  in `packages/backend/src/index.ts` , it's not giving above error but now getting below:

![image](https://github.com/backstage/backstage/assets/106815018/e6f97622-a561-4d66-9ffb-69c89c14cf58)

**Comment by awanlin** [comment]
Hi @prasoon-pxc, sorry you've had issues and the docs haven't been to helpful. We are actively working on that: https://github.com/backstage/backstage/issues/24195

Any new instances of Backstage will use the new backend system by default as of the `1.24.0` release from a few months ago. This means that you do need to add `backend.add(import('@backstage/plugin-auth-backend-module-github-provider'));` to your backend `index.ts` file and also add the `signIn.resolvers` details in your config.

**Comment by prasoon-pxc** [comment]
No problem, But I am wondering if it is the case with Github-org data [doc](https://backstage.io/docs/integrations/github/org) as well because I am also getting problem on automating ingesting github users to backstage, I am looking more into it and will check if there is some document issue there as well :-)

**Comment by awanlin** [comment]
Yes, that page needs to be updated as well. The migration guide here might help you in the mean time: https://backstage.io/docs/backend-system/building-backends/migrating#the-catalog-plugin:~:text=GithubMultiOrgEntityProvider%20and%20GithubOrgEntityProvider

**Comment by prasoon-pxc** [comment]
@awanlin , I tried to add changes what is mentioned in above doc, but it's still not working.

Added github-org package:

`yarn --cwd packages/backend add @backstage/plugin-catalog-backend-module-github-org`

---
`packages/backend/src/index.ts`

```
backend.add(import('@backstage/plugin-catalog-backend-module-github/alpha'));
backend.add(import('@backstage/plugin-catalog-backend-module-github-org'));
```

Apart from the above steps, I have used this [doc](https://backstage.io/docs/integrations/github/org/) to install required things.

My `catalog.ts` file looks like this:

`packages/backend/src/plugins/catalog.ts`

```
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-catalog-backend-module-scaffolder-entity-model';
import { Router } from 'express';
import { PluginEnvironment } from '../types';

import { GitHubOrgEntityProvider } from '@backstage/plugin-catalog-backend-module-github';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);

   //Added GITHUB ORG

   builder.addEntityProvider(
    GitHubOrgEntityProvider.fromConfig(env.config, {
      id: 'production',
      orgUrl: 'https://github.com/my-org',
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 60 },
        timeout: { minutes: 15 },
      }),
    }),
  );

  builder.addProcessor(new ScaffolderEntitiesProcessor());
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
```

Also, added github integration using Github-App
`app-config.yaml`

```
integrations:
  github:
    - host: github.com
      apps:
        - $include: my-githubapp.yaml

```

**Comment by prasoon-pxc** [comment]
==Tried updated doc to configure it, did below steps:

I have setup Github-integration with github app using this [doc](https://github.com/awanlin/backstage/blob/topic/nbs-integration-github/docs/integrations/github/github-apps.md) also provide required permissions for Github-app to ingest users and teams

After that added below package:

```yarn --cwd packages/backend add @backstage/plugin-catalog-backend-module-github-org```

added below line in `packages/backend/src/index-tx`

```
backend.add(import('@backstage/plugin-catalog-backend-module-github-org'));
```

`app-config.yaml`

```
integrations:
  github:
    - host: github.com
      apps:
        - $include: my-big-org.yaml
```

**Comment by awanlin** [comment]
One of the items missing in my PR to updated the docs which you might be missing too is that you need to make sure to schedule it:

```yaml
catalog:
  providers: 
    githubOrg:
      id: production
      githubUrl: https://github.com
      orgs: ['Org1', 'Org2']
      schedule:
        frequency: PT1H
        timeout: PT50M
 ```

**Comment by prasoon-pxc** [comment]
@awanlin , thanks for update, indeed that was missing. Now, working as expected.

**Comment by awanlin** [comment]
Awesome! Glad everything is working for you now. Really appreciate your patience as we worked to sort this out.

**Comment by SreeHarshithaGaddam** [comment]
@awanlin @prasoon-pxc I am facing the below issue even after following all the above steps 
![Screenshot 2024-06-01 7 46 41 PM](https://github.com/backstage/backstage/assets/127414715/2c15871a-29ab-4afc-a234-22bf4a9e9da8)

**Comment by SreeHarshithaGaddam** [comment]
@awanlin can you please look into this new issue [#25043](https://github.com/backstage/backstage/issues/25043)

**Comment by stone-monkeys** [comment]
Hey @prasoon-pxc - thanks for putting this together, helped me resolve an issue I was debugging for a couple. Highly recommend to the backstage team to incorporate this body of work into the initial clone or at least document the error somewhere!

**Comment by awanlin** [comment]
Hi @stone-monkeys, I've updated the docs to cover all the issues highlighted by @prasoon-pxc back in May. Can you share where there were gaps still?

**Comment by Prateek-Wayne** [comment]
Hi there,

I faced a similar issue and found that the problem was related to where the Client ID and Client Secret were created. Initially, I created them from my user account,`https://github.com/settings/applications/new` which led to issues.

To resolve this, make sure to create the Client ID and Client Secret from your organization account. You can do this by navigating to:

`https://github.com/organizations/<org name>/settings/applications/new`

Hope this helps!

**Comment by jrtaylorJH** [comment]
@Prateek-Wayne Hey there - was there a specific error you were getting that led to this resolution?
