### ISSUE TITLE
🐛 Bug Report: BitbucketCloudClient returning status 400 Bad Request

### ISSUE THREAD

**Issue by ssliman** [backstage/backstage#24639]
### 📜 Description

BitbucketCloudClient errors when searching for catalog files. This is because `search_query` parameter is not present.

### 👍 Expected behavior

BitbucketCloudClient should not error when searching for catalog files. It should use `search_query` parameter because it's required

See: https://developer.atlassian.com/cloud/bitbucket/rest/api-group-other-operations/#api-workspaces-workspace-search-code-get

### 👎 Actual Behavior with Screenshots

```
[1] 2024-05-06T07:15:58.737Z catalog error bitbucketCloud-provider:default refresh failed, Error: Unexpected response for GET https://api.bitbucket.org/2.0/workspaces/%7Bba6c5774-0480-45be-a92f-732566a1273a%7D/search/code?fields=-values.content_matches%2C%2Bvalues.file.commit.repository.mainbranch.name%2C%2Bvalues.file.commit.repository.project.key%2C%2Bvalues.file.commit.repository.slug%2C-values.%2A.links%2C-values.%2A.%2A.links%2C-values.%2A.%2A.%2A.links%2C%2Bvalues.file.commit.repository.links.html.href?search_query=%22catalog-info.yaml%22+path%3A%2Fcatalog-info.yaml&pagelen=100&page=2. Expected 200 but got 400 - Bad Request Unexpected response for GET https://api.bitbucket.org/2.0/workspaces/%7Bba6c5774-0480-45be-a92f-732566a1273a%7D/search/code?fields=-values.content_matches%2C%2Bvalues.file.commit.repository.mainbranch.name%2C%2Bvalues.file.commit.repository.project.key%2C%2Bvalues.file.commit.repository.slug%2C-values.%2A.links%2C-values.%2A.%2A.links%2C-values.%2A.%2A.%2A.links%2C%2Bvalues.file.commit.repository.links.html.href?search_query=%22catalog-info.yaml%22+path%3A%2Fcatalog-info.yaml&pagelen=100&page=2. Expected 200 but got 400 - Bad Request target=bitbucketCloud-provider:default class=BitbucketCloudEntityProvider taskId=bitbucketCloud-provider:default:refresh taskInstanceId=170ad9cc-94fa-4263-a1bd-78e16ca2f757 stack=Error: Unexpected response for GET https://api.bitbucket.org/2.0/workspaces/%7Bba6c5774-0480-45be-a92f-732566a1273a%7D/search/code?fields=-values.content_matches%2C%2Bvalues.file.commit.repository.mainbranch.name%2C%2Bvalues.file.commit.repository.project.key%2C%2Bvalues.file.commit.repository.slug%2C-values.%2A.links%2C-values.%2A.%2A.links%2C-values.%2A.%2A.%2A.links%2C%2Bvalues.file.commit.repository.links.html.href?search_query=%22catalog-info.yaml%22+path%3A%2Fcatalog-info.yaml&pagelen=100&page=2. Expected 200 but got 400 - Bad Request
[1]     at <anonymous> (/Users/ssaid/projects/backstage/node_modules/@backstage/plugin-bitbucket-cloud-common/src/BitbucketCloudClient.ts:100:9)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at WithPagination.iterateResults (/Users/ssaid/projects/backstage/node_modules/@backstage/plugin-bitbucket-cloud-common/src/pagination.ts:86:13)
[1]     at BitbucketCloudEntityProvider.findCatalogFiles (/Users/ssaid/projects/backstage/node_modules/@backstage/plugin-catalog-backend-module-bitbucket-cloud/src/providers/BitbucketCloudEntityProvider.ts:364:22)
[1]     at BitbucketCloudEntityProvider.refresh (/Users/ssaid/projects/backstage/node_modules/@backstage/plugin-catalog-backend-module-bitbucket-cloud/src/providers/BitbucketCloudEntityProvider.ts:205:21)
[1]     at fn (/Users/ssaid/projects/backstage/node_modules/@backstage/plugin-catalog-backend-module-bitbucket-cloud/src/providers/BitbucketCloudEntityProvider.ts:156:19)
[1]     at TaskWorker.fn (/Users/ssaid/projects/backstage/node_modules/@backstage/backend-tasks/src/tasks/PluginTaskSchedulerImpl.ts:134:9)
[1]     at TaskWorker.runOnce (/Users/ssaid/projects/backstage/node_modules/@backstage/backend-tasks/src/tasks/TaskWorker.ts:155:13)
[1]     at <anonymous> (/Users/ssaid/projects/backstage/node_modules/@backstage/backend-tasks/src/tasks/TaskWorker.ts:75:31)
```

While debugging I got

```json
{"type":"about:blank","title":"Bad Request","status":400,"detail":"Required parameter 'search_query' is not present.","instance":"/api/2.0/workspaces/%7Bba6c5774-0480-45be-a92f-732566a1273a%7D/search/code"}
```

### 👟 Reproduction steps

```yaml
catalog:
  providers:
    bitbucketCloud:
      schedule:
        frequency: PT30M
        timeout: PT3M
      catalogPath: /catalog-info.yaml
      workspace: xxxxxxx
```

### 🖥️ Your Environment

```bash
OS:   Darwin 23.4.0 - darwin/arm64
node: v18.18.2
yarn: 4.1.1
cli:  0.26.4 (installed)
backstage:  1.26.5

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.5.14, 0.6.2, 0.7.1
  @backstage/backend-common                                        0.17.0, 0.19.10, 0.20.2, 0.21.7
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.17
  @backstage/backend-tasks                                         0.5.22
  @backstage/backend-test-utils                                    0.3.7
  @backstage/catalog-client                                        1.6.4
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.4
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.5, 0.14.6
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.31
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           1.10.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-guest-provider             0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12
  @backstage/plugin-auth-react                                     0.1.1
  @backstage/plugin-bitbucket-cloud-common                         0.2.16
  @backstage/plugin-catalog-backend-module-aws                     0.3.12
  @backstage/plugin-catalog-backend-module-bitbucket-cloud         0.2.4
  @backstage/plugin-catalog-backend-module-github                  0.6.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-explore-common                                 0.0.3
  @backstage/plugin-explore                                        0.0.0-use.local
  @backstage/plugin-home-react                                     0.1.12
  @backstage/plugin-home                                           0.7.3
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-cookiecutter         0.2.41
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.4, 1.22.5
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.23
  @backstage/plugin-search-backend-module-elasticsearch            1.4.0
  @backstage/plugin-search-backend-module-explore                  0.1.23
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@pjungermann can you take a peek here and see if anything stands out? :pray:

**Comment by ssliman** [comment]
@benjdlambert Closing this issue we found the bug in our patched package. Sorry for the fuss
