### ISSUE TITLE
🐛 Bug Report: cannot use GitLab Org Data and Discovery together anymore

### ISSUE THREAD

**Issue by ZF-fredericvanlinthoudt** [backstage/backstage#24857]
### 📜 Description

We are using both the GitLab Org Data and the GitLab Discovery together.
Therefore we use the following config:
```yaml
catalog:
  providers:
    gitlab:
      gitlab-users:
        host: REDACTED
        orgEnabled: true
        group: pe-teams
        schedule:
          frequency: PT1H
          timeout: PT50M
        rules:
          - allow: [Group, User]
      gitlab-projects:
        host: REDACTED
        schedule:
          frequency: PT1H
          timeout: PT50M
```

On Backstage v1.26 this was working well because the OrgData entity provider was just ignoring gitlab providers with `orgEnabled` not set.
Since 1.27 ([see commit](https://github.com/backstage/backstage/commit/a70377d3e1902480cbae14b2c7a861514f0a61ff#diff-dd88319827a66d2f2f49890fcfe42f108a431bd463f63c822d85e5b49b30142cL99-R135)), the behavior has been changed to throw an error if  `orgEnabled` is not set, so this is a breaking, probably unintentional, change which makes it impossible to use Org Data & Discovery together.

### 👍 Expected behavior

Backstage to start normally and scan for org data (groups and users) from our Gitlab instance + scan / perform discovery from projects from our Gitlab instance

### 👎 Actual Behavior with Screenshots

Backstage fails to start with an error:
```
❯ yarn dev
yarn run v1.22.22
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/REDACTED/backstage/backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] Loading config from MergedConfigSource{FileConfigSource{path="/Users/REDACTED/backstage/backstage/app-config.yaml"}, FileConfigSource{path="/Users/REDACTED/backstage/backstage/app-config.local.yaml"}, EnvConfigSource{count=0}}
[1] 2024-05-21T17:49:15.867Z backstage info Found 4 new secrets in config that will be redacted 
[1] 2024-05-21T17:49:15.883Z rootHttpRouter info Listening on :7007 
[1] 2024-05-21T17:49:15.887Z backstage info Plugin initialization started: 'app', 'proxy', 'scaffolder', 'techdocs', 'auth', 'catalog', 'permission', 'search', 'announcements', 'kubernetes', 'gitlab' type=initialization
[1] (node:30131) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [process]. Use emitter.setMaxListeners() to increase limit
[1] (Use `node --trace-warnings ...` to show where the warning was created)
[1] 2024-05-21T17:49:16.275Z gitlab info [HPM] Proxy created: (_pathname, req) => {
[1]     var _a;
[1]     headersManipulation(req.headers);
[1]     return req.method === "POST" && !((_a = req.body.query) == null ? void 0 : _a.includes("mutation"));
[1]   }  -> https://REDACTED 
[1] 2024-05-21T17:49:16.275Z gitlab info [HPM] Proxy rewrite rule created: "^/api/gitlab/graphql/REDACTED" ~> "/api/graphql" 
[1] 2024-05-21T17:49:16.276Z gitlab info [HPM] Proxy created: (_pathname, req) => {
[1]     headersManipulation(req.headers);
[1]     return req.method === "GET";
[1]   }  -> https://REDACTED 
[1] 2024-05-21T17:49:16.276Z gitlab info [HPM] Proxy rewrite rule created: "^/api/gitlab/rest/REDACTED" ~> "/api/v4" 
[1] 2024-05-21T17:49:16.277Z gitlab info [HPM] Proxy created: (_pathname, req) => {
[1]     var _a;
[1]     headersManipulation(req.headers);
[1]     return req.method === "POST" && !((_a = req.body.query) == null ? void 0 : _a.includes("mutation"));
[1]   }  -> https://gitlab.com 
[1] 2024-05-21T17:49:16.277Z gitlab info [HPM] Proxy rewrite rule created: "^/api/gitlab/graphql/gitlab.com" ~> "/api/graphql" 
[1] 2024-05-21T17:49:16.278Z gitlab info [HPM] Proxy created: (_pathname, req) => {
[1]     headersManipulation(req.headers);
[1]     return req.method === "GET";
[1]   }  -> https://gitlab.com 
[1] 2024-05-21T17:49:16.278Z gitlab info [HPM] Proxy rewrite rule created: "^/api/gitlab/rest/gitlab.com" ~> "/api/v4" 
[1] 2024-05-21T17:49:16.312Z kubernetes info Initializing Kubernetes backend 
[1] 2024-05-21T17:49:16.312Z kubernetes warn Failed to initialize kubernetes backend: kubernetes config is missing 
[1] 2024-05-21T17:49:16.316Z auth info Configuring "database" as KeyStore provider 
[1] 2024-05-21T17:49:16.317Z techdocs info Creating Local publisher for TechDocs 
[1] 2024-05-21T17:49:16.328Z scaffolder info Starting scaffolder with the following actions enabled infinity:api:call, gitlab:cookiecutter:repo:push, fetch:cookiecutter, fetch:plain, fetch:plain:file, fetch:template, debug:log, debug:wait, catalog:register, catalog:fetch, catalog:write, fs:delete, fs:rename 
[1] 2024-05-21T17:49:16.332Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog 
[1] 2024-05-21T17:49:16.332Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs 
[1] /Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:273
[1]                 throw new ForwardedError(
[1]                       ^
[1] 
[1] 
[1] ForwardedError: Module 'gitlabOrgDiscoveryEntityProvider' for plugin 'catalog' startup failed; caused by Error: Org not enabled for gitlab-projects.
[1]     at <anonymous> (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:273:23)
[1]     at <anonymous> (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:272:15)
[1]     at processNode (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/lib/DependencyGraph.ts:234:22)
[1]     ... 7 lines matching cause stack trace ...
[1]     at BackstageBackend.start (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:42:11) {
[1]   cause: Error: Org not enabled for gitlab-projects.
[1]       at <anonymous> (/Users/REDACTED/backstage/backstage/node_modules/@backstage/plugin-catalog-backend-module-gitlab/src/providers/GitlabOrgDiscoveryEntityProvider.ts:136:15)
[1]       at Array.forEach (<anonymous>)
[1]       at Function.fromConfig (/Users/REDACTED/backstage/backstage/node_modules/@backstage/plugin-catalog-backend-module-gitlab/src/providers/GitlabOrgDiscoveryEntityProvider.ts:132:21)
[1]       at Object.init (/Users/REDACTED/backstage/backstage/node_modules/@backstage/plugin-catalog-backend-module-gitlab-org/src/catalogModuleGitlabOrgDiscoveryEntityProvider.ts:46:46)
[1]       at <anonymous> (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:272:37)
[1]       at processNode (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/lib/DependencyGraph.ts:234:22)
[1]       at async Promise.all (index 2)
[1]       at processMoreNodes (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/lib/DependencyGraph.ts:226:7)
[1]       at _DependencyGraph.parallelTopologicalTraversal (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/lib/DependencyGraph.ts:242:5)
[1]       at <anonymous> (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:265:11)
[1]       at async Promise.all (index 5)
[1]       at BackendInitializer.doStart_fn (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:236:5)
[1]       at BackendInitializer.start (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:150:5)
[1]       at BackstageBackend.start (/Users/REDACTED/backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:42:11)
[1] }
[1] 
[1] Node.js v18.20.2
```

### 👟 Reproduction steps

Configure both GitLab org data + discovery to the same GitLab instance:
```yaml
catalog:
  providers:
    gitlab:
      gitlab-users:
        host: REDACTED
        orgEnabled: true
        group: pe-teams
        schedule:
          frequency: PT1H
          timeout: PT50M
        rules:
          - allow: [Group, User]
      gitlab-projects:
        host: REDACTED
        schedule:
          frequency: PT1H
          timeout: PT50M
```

### 🖥️ Your Environment

```
OS:   Darwin 23.0.0 - darwin/x64
node: v18.20.2
yarn: 1.22.22
cli:  0.26.5 (installed)
backstage:  1.27.2

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.5
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.32
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-aws                     0.3.13
  @backstage/plugin-catalog-backend-module-gitlab-org              0.0.1
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.16
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-kubernetes-backend                             0.17.1
  @backstage/plugin-kubernetes-common                              0.7.6
  @backstage/plugin-kubernetes-node                                0.1.12
  @backstage/plugin-kubernetes-react                               0.3.5
  @backstage/plugin-kubernetes                                     0.11.10
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-cookiecutter         0.2.42
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.5
  @backstage/plugin-scaffolder                                     1.20.0
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-pg                       0.5.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ZF-fredericvanlinthoudt** [comment]
Pinging @elaine-mattos who committed the change causing this behavior.

**Comment by elaine-mattos** [comment]
Oh shoot! I'm sorry to hear it broke your setup @ZF-fredericvanlinthoudt !
@freben , I can take a look at it as soon as https://github.com/backstage/backstage/pull/24838 gets merged. 🥲

**Comment by elaine-mattos** [comment]
Hi @freben ,

I just went ahead and submitted a PR for this. Could you please take a look at it? https://github.com/backstage/backstage/pull/24862
I will go through the list of the other points you mentioned [here](https://github.com/backstage/backstage/pull/23373) later, ok?
