### ISSUE TITLE
🐛 Bug Report: Error on gitlab:publish to create new repo

### ISSUE THREAD

**Issue by adickinson72** [backstage/backstage#24876]
### 📜 Description

When using default example scaffolder [springboot template](https://github.com/backstage/software-templates/blob/main/scaffolder-templates/springboot-grpc-template/template.yaml)  and use gitlab:publish instead of github:publish - it creates project but fails to populate repo with data as it gives the error: AlreadyExistsError: Failed to create remote at origin because it already exists.
But the project was just created via gitlab:publish action in previous step

### 👍 Expected behavior

Create new project repository with files

### 👎 Actual Behavior with Screenshots

`[455](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-455)2024-05-22T14:46:10.900Z Beginning step Publish[456](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-456)2024-05-22T14:46:13.319Z info: Init git repository {dir=/var/folders/92/72w6cd4x6nn9_g7zmljltfd80000gp/T/7a18b64d-e588-4281-8f5e-608fb006111a}[457](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-457)2024-05-22T14:46:13.320Z info: Adding file {dir=/var/folders/92/72w6cd4x6nn9_g7zmljltfd80000gp/T/7a18b64d-e588-4281-8f5e-608fb006111a,filepath=.}[458](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-458)2024-05-22T14:46:13.440Z info: Committing file to repo {dir=/var/folders/92/72w6cd4x6nn9_g7zmljltfd80000gp/T/7a18b64d-e588-4281-8f5e-608fb006111a,message=initial commit}[459](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-459)2024-05-22T14:46:13.790Z info: Creating new remote {dir=/var/folders/92/72w6cd4x6nn9_g7zmljltfd80000gp/T/7a18b64d-e588-4281-8f5e-608fb006111a,remote=origin,url=https://gitlab.com/organizationname/infrastructure/test-adamd-test.git}[460](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-460)2024-05-22T14:46:13.816Z AlreadyExistsError: Failed to create remote at origin because it already exists. (Hint: use 'force: true' parameter to overwrite existing remote.)[461](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-461)    at _addRemote (/Users/adickinson/repos/backstage/node_modules/isomorphic-git/index.cjs:5668:15)[462](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-462)    at async Object.addRemote (/Users/adickinson/repos/backstage/node_modules/isomorphic-git/index.cjs:5718:12)[463](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-463)    at Object.initRepoAndPush (/Users/adickinson/repos/backstage/node_modules/@backstage/plugin-scaffolder-node/src/actions/gitHelpers.ts:68:3)[464](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-464)    at Object.handler (/Users/adickinson/repos/backstage/node_modules/@backstage/plugin-scaffolder-backend/node_modules/@backstage/plugin-scaffolder-backend-module-gitlab/src/actions/gitlab.ts:392:28)[465](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-465)    at NunjucksWorkflowRunner.executeStep (/Users/adickinson/repos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:374:9)[466](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-466)    at NunjucksWorkflowRunner.execute (/Users/adickinson/repos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:501:9)[467](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-467)    at TaskWorker.runOneTask (/Users/adickinson/repos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:176:26)[468](http://localhost:3000/create/tasks/7a18b64d-e588-4281-8f5e-608fb006111a#line-468)    at async run (/Users/adickinson/repos/backstage/node_modules/p-queue/dist/index.js:163:29)`

### 👟 Reproduction steps

Create a template and use with public Gitlab:
`
     - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com
   steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main`

### 🖥️ Your Environment

`yarn backstage-cli info
yarn run v1.22.21
$ /Users/adickinson/repos/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.5.0 - darwin/x64
node: v20.11.1
yarn: 1.22.21
cli:  0.26.2 (installed)
backstage:  1.25.0

Dependencies:
  @backstage/app-defaults                                          1.5.3
  @backstage/backend-app-api                                       0.5.14, 0.6.2, 0.7.2
  @backstage/backend-common                                        0.19.10, 0.20.2, 0.21.6, 0.21.7
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.9
  @backstage/backend-plugin-api                                    0.6.16, 0.6.17
  @backstage/backend-tasks                                         0.5.21, 0.5.22
  @backstage/catalog-client                                        1.6.3, 1.6.4
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4, 0.2.5
  @backstage/cli                                                   0.26.2
  @backstage/config-loader                                         1.7.0, 1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.3
  @backstage/core-compat-api                                       0.2.3
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.3
  @backstage/core-plugin-api                                       1.9.1
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.3
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.25
  @backstage/integration                                           1.10.0, 1.9.1
  @backstage/plugin-api-docs                                       0.11.3
  @backstage/plugin-app-backend                                    0.3.64
  @backstage/plugin-app-node                                       0.1.16
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.8
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.8
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.11
  @backstage/plugin-auth-backend-module-github-provider            0.1.13
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.13
  @backstage/plugin-auth-backend-module-google-provider            0.1.13
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.11
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.13
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.9
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.7
  @backstage/plugin-auth-backend-module-okta-provider              0.0.9
  @backstage/plugin-auth-backend                                   0.22.3
  @backstage/plugin-auth-node                                      0.4.11, 0.4.12
  @backstage/plugin-auth-react                                     0.0.3
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.14
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.14
  @backstage/plugin-catalog-backend                                1.21.0
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.3
  @backstage/plugin-catalog-import                                 0.10.9
  @backstage/plugin-catalog-node                                   1.11.0
  @backstage/plugin-catalog-react                                  1.11.2
  @backstage/plugin-catalog                                        1.18.2
  @backstage/plugin-events-node                                    0.3.2
  @backstage/plugin-github-actions                                 0.6.14
  @backstage/plugin-home-react                                     0.1.11
  @backstage/plugin-home                                           0.7.2
  @backstage/plugin-kubernetes-backend                             0.16.4
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-kubernetes-node                                0.1.10
  @backstage/plugin-kubernetes-react                               0.3.3
  @backstage/plugin-kubernetes                                     0.11.8
  @backstage/plugin-org                                            0.6.23
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.27, 0.7.28
  @backstage/plugin-permission-react                               0.4.21
  @backstage/plugin-proxy-backend                                  0.4.14
  @backstage/plugin-scaffolder-backend-module-azure                0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.8
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.6
  @backstage/plugin-scaffolder-backend-module-github               0.2.6
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.2, 0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.3
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.2.10, 0.4.2, 0.4.3
  @backstage/plugin-scaffolder-react                               1.8.3
  @backstage/plugin-scaffolder                                     1.19.2
  @backstage/plugin-search-backend-module-catalog                  0.1.21
  @backstage/plugin-search-backend-module-pg                       0.5.25
  @backstage/plugin-search-backend-module-techdocs                 0.1.21
  @backstage/plugin-search-backend-node                            1.2.20
  @backstage/plugin-search-backend                                 1.5.6
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.9
  @backstage/plugin-search                                         1.4.9
  @backstage/plugin-tech-radar                                     0.7.2
  @backstage/plugin-techdocs-backend                               1.10.3
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.8
  @backstage/plugin-techdocs-node                                  1.12.2
  @backstage/plugin-techdocs-react                                 1.2.2
  @backstage/plugin-techdocs                                       1.10.3
  @backstage/plugin-user-settings                                  0.8.4
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.3
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 1.71s.`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by adickinson72** [comment]
Re-built and issue went away - unsure on cause but its no longer reproducible
