### ISSUE TITLE
🐛 Bug Report: Calling the API throws 401 Invalid server token

### ISSUE THREAD

**Issue by CARLOSMECK** [backstage/backstage#24890]
### 📜 Description

We have quite recently deployed Backstage. We are using the Microsoft Azure Authentication Provider for auth. 
We would now like to integrate some applications, one use case is to query components from backstage. 

### 👍 Expected behavior

When calling the API: `GET https://backstage.cotonso.com/api/catalog/entities/by-query?filter=kind=Component,metadata.name=cloudflare`

```
With token from Azure AD:
client_id = 'client_id_value'
client_secret = '"client_secret_value'

# OAuth2 token endpoint for Azure AD
tenant_id = '3216c6ae-2291-10a0-b038-3884d1948974' 
token_url = f'https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token'

# Scope for the API
scope = ['mcb3879b-987f-445f-1338-7339d1969367/.default']

# Create a client for the OAuth2 session
client = BackendApplicationClient(client_id=client_id)
oauth = OAuth2Session(client=client)

token = oauth.fetch_token(token_url=token_url, client_id=client_id, client_secret=client_secret, scope=scope)
print(token)
```

We should get info about the component. 

### 👎 Actual Behavior with Screenshots

Throws an error:
![image](https://github.com/backstage/backstage/assets/6379811/d0787f73-02b1-4399-bae0-1f45fd7f3727)

Full error response:
```
Status code: 401
Response text: {"error":{"name":"AuthenticationError","message":"Invalid server token; caused by TypeError: Key for the RS256 algorithm must be one of type KeyObject or CryptoKey. Received an instance of Uint8Array","cause":{"name":"TypeError","message":"Key for the RS256 algorithm must be one of type KeyObject or CryptoKey. Received an instance of Uint8Array","stack":"TypeError: Key for the RS256 algorithm must be one of type KeyObject or CryptoKey. Received an instance of Uint8Array\n    at asymmetricTypeCheck (/app/node_modules/jose/dist/node/cjs/lib/check_key_type.js:17:15)\n    at checkKeyType (/app/node_modules/jose/dist/node/cjs/lib/check_key_type.js:44:9)\n    at flattenedVerify (/app/node_modules/jose/dist/node/cjs/jws/flattened/verify.js:78:37)\n    at compactVerify (/app/node_modules/jose/dist/node/cjs/jws/compact/verify.js:18:60)\n    at Object.jwtVerify (/app/node_modules/jose/dist/node/cjs/jwt/verify.js:8:58)\n    at ServerTokenManager.authenticate (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:5486:24)\n    at AuthCompat.authenticate (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:586:59)\n    at HttpAuthCompat.extractCredentialsFromRequest_fn (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:698:36)\n    at HttpAuthCompat.getCredentials_fn (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:703:168)\n    at HttpAuthCompat.credentials (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:658:89)\n    at /app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-g0TDave-.cjs.js:5582:37\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /app/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /app/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)"}},"request":{"method":"GET","url":"/entities/by-query?filter=kind%3DComponent%2Cmetadata.name%3Dfastly"},"response":{"statusCode":401}}
```

### 👟 Reproduction steps

Trying to call the API with valid token from Azure AD.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drewfish** [comment]
I've run into this too, when using custom authMiddleware for Auth0. It worked before upgrading

**Comment by benjdlambert** [comment]
For this error in particular, I wonder if anything here helps you: https://github.com/backstage/backstage/issues/24553

**Comment by drewfish** [comment]
Ah thanks, yeah that https://github.com/backstage/backstage/issues/24553 looks more like my issue.
