### ISSUE TITLE
🐛 Bug Report: Failed to get started

### ISSUE THREAD

**Issue by modatwork** [backstage/backstage#25049]
### 📜 Description

Follow the get-started instruction and it failed to run. Same as the issue https://github.com/backstage/backstage/issues/24941.

After bump to a newer version, it report another error message showed below.

### 👍 Expected behavior

The initial app should run without issue.

### 👎 Actual Behavior with Screenshots

```
[0] ERROR in node:url
[0] Module build failed: UnhandledSchemeError: Reading from "node:url" is not handled by plugins (Unhandled scheme).
[0] Webpack supports "data:" and "file:" URIs by default.
[0] You may need an additional plugin to handle "node:" URIs.
[0]     at /home/ops/backstage/node_modules/webpack/lib/NormalModule.js:918:25
[0]     at Hook.eval [as callAsync] (eval at create (/home/ops/backstage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
[0]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/ops/backstage/node_modules/tapable/lib/Hook.js:18:14)
[0]     at Object.processResource (/home/ops/backstage/node_modules/webpack/lib/NormalModule.js:915:8)
[0]     at processResource (/home/ops/backstage/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
[0]     at iteratePitchingLoaders (/home/ops/backstage/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
[0]     at runLoaders (/home/ops/backstage/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
[0]     at NormalModule._doBuild (/home/ops/backstage/node_modules/webpack/lib/NormalModule.js:905:3)
[0]     at NormalModule.build (/home/ops/backstage/node_modules/webpack/lib/NormalModule.js:1081:15)
[0]     at /home/ops/backstage/node_modules/webpack/lib/Compilation.js:1400:12
[0]
[0] webpack compiled with 1 error
```

### 👟 Reproduction steps

```shell
npx @backstage/create-app@latest
cd backstage && yarn dev
yarn backstage-cli versions:bump
yarn dev
```

### 🖥️ Your Environment

```
$ yarn backstage-cli info
yarn run v1.22.22
$ /home/ops/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.4.17-2136.331.7.el8uek.x86_64 - linux/x64
node: v20.14.0
yarn: 1.22.22
cli:  0.26.6 (installed)
backstage:  1.27.6

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.6
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.6
  @backstage/plugin-scaffolder                                     1.20.1
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 0.65s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by MingYunChen** [comment]
I have the same problem. Here is my Backstage environment.

OS:   Linux 5.15.0-107-generic - linux/x64
node: v18.18.2
yarn: 1.22.21
cli:  0.26.6 (installed)
backstage:  1.27.6

**Comment by modatwork** [comment]
close this in favor of https://github.com/backstage/backstage/issues/24941#issuecomment-2146870246 .

**Comment by seng-siong** [comment]
The error is still present but both this and #24941 got closed. Is this being actively looked at?

**Comment by sam-cogan** [comment]
@modatwork  please re-open this issue, as #24941 has also bee closed

**Comment by awanlin** [comment]
I'm reopening this issue, would like those with this error to share any details they have here or things that they have tried to resolve it, this would be terribly helpful 👍

**Comment by freben** [comment]
Noting that end-to-end tests have started failing with `UnhandledSchemeError` too, eg https://github.com/backstage/backstage/actions/runs/9365383685/job/25780482929?pr=24353

**Comment by Rugvip** [comment]
This is due to https://github.com/ajv-validator/ajv/issues/2446, I'll pin to an older version

**Comment by twanbeeren** [comment]
I've ran a new yarn install today and I face the same issue when my pipeline runs a yarn--cwd packages/backend build. Is there any action needed from our side to resolve this issue.

Or can I just run a new yarn install after the PR above is merged?

**Comment by Rugvip** [comment]
@twanbeeren we'll need to either edit `yarn.lock` or use `resolutions` to make sure you're getting an older version of `ajv`. The above fix only applies to new projects created with `@backstage/create-app`
