### ISSUE TITLE
Software catalogs integration with gitlab - facing error

### ISSUE THREAD

**Issue by vinaykv23** [backstage/backstage#25120]
### 📜 Description

Hi Team
I am very new to backstage and first I am trying to integrate Software catalog from gitlab, but resulting in below error
referred https://backstage.io/docs/integrations/gitlab/discovery
still facing below error

 error GitlabDiscoveryEntityProvider:organization refresh failed, FetchError: request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com target=GitlabDiscoveryEntityProvider:organization class=GitlabDiscoveryEntityProvider taskId=GitlabDiscoveryEntityProvider:organization:refresh taskInstanceId=d733b910-de77-4003-9d9c-19a0959c0a98 type=system errno=ENOTFOUND code=ENOTFOUND stack=FetchError: request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com
[1]     at ClientRequest.<anonymous> (/home/vinaykv/backstage/node_modules/node-fetch/lib/index.js:1501:11)
[1]     at ClientRequest.emit (node:events:517:28)
[1]     at TLSSocket.socketErrorListener (node:_http_client:501:9)
[1]     at TLSSocket.emit (node:events:517:28)
[1]     at emitErrorNT (node:internal/streams/destroy:151:8)
[1]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[1] 2024-06-10T17:48:28.955Z catalog error GitlabDiscoveryEntityProvider:yourProviderId refresh failed, FetchError: request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com target=GitlabDiscoveryEntityProvider:yourProviderId class=GitlabDiscoveryEntityProvider taskId=GitlabDiscoveryEntityProvider:yourProviderId:refresh taskInstanceId=e5e9d813-6972-4d4d-8cc7-80cc5579275f type=system errno=ENOTFOUND code=ENOTFOUND stack=FetchError: request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com
[1]     at ClientRequest.<anonymous> (/home/vinaykv/backstage/node_modules/node-fetch/lib/index.js:1501:11)
[1]     at ClientRequest.emit (node:events:517:28)
[1]     at TLSSocket.socketErrorListener (node:_http_client:501:9)
[1]     at TLSSocket.emit (node:events:517:28)
[1]     at emitErrorNT (node:internal/streams/destroy:151:8)
[1]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

### 👍 Expected behavior

it should load the software catalogs from gitlab, where catalog-info.yaml is present
example
https://gitlab.corp.organization.com/project-one/project-one-sub/-/blob/develop/catalog-info.yaml
https://gitlab.corp.organization.com/project-one/project-two-sub/-/blob/develop/catalog-info.yaml
https://gitlab.corp.organization.com/project-two/project-one/-/blob/develop/catalog-info.yaml
etc

### 👎 Actual Behavior with Screenshots

I am trying to integrate Software catalog from gitlab, but resulting in below error
referred https://backstage.io/docs/integrations/gitlab/discovery
still facing below error

 error GitlabDiscoveryEntityProvider:organization refresh failed, FetchError: request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com target=GitlabDiscoveryEntityProvider:organization class=GitlabDiscoveryEntityProvider taskId=GitlabDiscoveryEntityProvider:organization:refresh taskInstanceId=d733b910-de77-4003-9d9c-19a0959c0a98 type=system errno=ENOTFOUND code=ENOTFOUND stack=FetchError: request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com
[1]     at ClientRequest.<anonymous> (/home/vinaykv/backstage/node_modules/node-fetch/lib/index.js:1501:11)
[1]     at ClientRequest.emit (node:events:517:28)
[1]     at TLSSocket.socketErrorListener (node:_http_client:501:9)
[1]     at TLSSocket.emit (node:events:517:28)
[1]     at emitErrorNT (node:internal/streams/destroy:151:8)
[1]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[1] 2024-06-10T17:48:28.955Z catalog error GitlabDiscoveryEntityProvider:yourProviderId refresh failed, FetchError: request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com target=GitlabDiscoveryEntityProvider:yourProviderId class=GitlabDiscoveryEntityProvider taskId=GitlabDiscoveryEntityProvider:yourProviderId:refresh taskInstanceId=e5e9d813-6972-4d4d-8cc7-80cc5579275f type=system errno=ENOTFOUND code=ENOTFOUND stack=FetchError: request to https://gitlab.corp.organization.com/api/v4/projects?archived=false&page=1&per_page=50 failed, reason: getaddrinfo ENOTFOUND gitlab.corp.organization.com
[1]     at ClientRequest.<anonymous> (/home/vinaykv/backstage/node_modules/node-fetch/lib/index.js:1501:11)
[1]     at ClientRequest.emit (node:events:517:28)
[1]     at TLSSocket.socketErrorListener (node:_http_client:501:9)
[1]     at TLSSocket.emit (node:events:517:28)
[1]     at emitErrorNT (node:internal/streams/destroy:151:8)
[1]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

### 👟 Reproduction steps

1. npx @backstage/create-app@latest create project
2. cd my-backstage-app # your app name
3. yarn dev
4. app-config.yaml
    integrations:
        gitlab:
          - host: gitlab.corp.organization.com
            token: token 
            apiBaseUrl: https://gitlab.corp.organization.com/api/v4
            baseUrl: https://gitlab.corp.organization.com

      catalog:
        providers:
          gitlab:
            yourProviderId:
              host: gitlab.corp.organization.com  
              branch: master
              fallbackBranch: master
              skipForkedRepos: false  
              entityFilename: catalog-info.yaml  
              projectPattern: '[\s\S]*'  
              schedule:  
                frequency: { minutes: 30 }                 
                timeout: { minutes: 10 }
5. execute below commands
    **From your Backstage root directory**
     yarn --cwd packages/backend add @backstage/plugin-catalog-backend-module-gitlab
    
    **backend/src/index.ts**
    backend.add(import('@backstage/plugin-catalog-backend-module-gitlab/alpha'));

    **backend/src/plugins/catalog.ts**
       import { GitlabDiscoveryEntityProvider } from '@backstage/plugin-catalog-backend-module-gitlab';
      import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
      import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
      import { Router } from 'express';
      import { PluginEnvironment } from '../types';
      
      export default async function createPlugin(
      env: PluginEnvironment,
      ): Promise<Router> {
      const builder = await CatalogBuilder.create(env);
      
      builder.addEntityProvider(
        ...GitlabDiscoveryEntityProvider.fromConfig(env.config, {
          logger: env.logger,
          // optional: alternatively, use scheduler with schedule defined in app-config.yaml
          schedule: env.scheduler.createScheduledTaskRunner({
            frequency: { minutes: 30 },
            timeout: { minutes: 3 },
          }),
          // optional: alternatively, use schedule
          scheduler: env.scheduler,
        }),
      );
      
      builder.addProcessor(new ScaffolderEntitiesProcessor());
      const {processingEngine, router } = await builder.build();
      await processingEngine.start();
      return router;
      }

 

### 📃 Provide the context for the Bug.

backstage with gitlab

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @vinaykv23, could you please let us know if you are running behind a corporate proxy? This documentation might be helpful if so: https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md
