### ISSUE TITLE
🐛 Bug Report: plugin-catalog-backend-module-puppetdb default transformer does not work on puppetdb 7 or higher

### ISSUE THREAD

**Issue by jagexjake** [backstage/backstage#25224]
### 📜 Description

It fails to read and import nodes from puppetdb when using puppetdb 7 or higher, not tested 6 as 6 now deprecated.

What is happening:
1: request /pdb/query/v4/facts: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-puppetdb/src/puppet/read.ts#L50
2: default transformer for ecah object: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-puppetdb/src/puppet/read.ts#L66
3: latest_report_status is not in factsets for the node: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-puppetdb/src/puppet/transformers.ts#L40 

API docs:
- factsets: https://www.puppet.com/docs/puppetdb/7/api/query/v4/factsets.html
- nodes: https://www.puppet.com/docs/puppetdb/7/api/query/v4/nodes

nodes api endpoint has the latest_report_status
but the ENDPOINT_NODES is only being used in `withLocations` https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-puppetdb/src/providers/PuppetDbEntityProvider.ts#L198

Error:
```
[1] 2024-06-13T14:18:39.929Z catalog debug Reading nodes from PuppetDB target=puppetdb-provider:default class=PuppetDbEntityProvider taskId=puppetdb-provider:default:refresh taskInstanceId=d8ae230b-67ea-4055-9d47-0b5a9830443c url=http://puppet-db.example.com:8080/pdb/query/v4/factsets?query=%5B%22%3D%22%2C%22certname%22%2C%22puppet-host.domain%22%5D
[1] 2024-06-13T14:18:40.341Z catalog error puppetdb-provider:default refresh failed, TypeError: Cannot read properties of undefined (reading 'toString') Cannot read properties of undefined (reading 'toString') target=puppetdb-provider:default class=PuppetDbEntityProvider taskId=puppetdb-provider:default:refresh taskInstanceId=d8ae230b-67ea-4055-9d47-0b5a9830443c stack=TypeError: Cannot read properties of undefined (reading 'toString')
[1]     at defaultResourceTransformer (/Users/jake/git/backstage/node_modules/@backstage/plugin-catalog-backend-module-puppetdb/src/puppet/transformers.ts:57:34)
[1]     at readPuppetNodes (/Users/jake/git/backstage/node_modules/@backstage/plugin-catalog-backend-module-puppetdb/src/puppet/read.ts:66:26)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at PuppetDbEntityProvider.refresh (/Users/jake/git/backstage/node_modules/@backstage/plugin-catalog-backend-module-puppetdb/src/providers/PuppetDbEntityProvider.ts:172:22)
[1]     at fn (/Users/jake/git/backstage/node_modules/@backstage/plugin-catalog-backend-module-puppetdb/src/providers/PuppetDbEntityProvider.ts:149:19)
[1]     at TaskWorker.fn (/Users/jake/git/backstage/node_modules/@backstage/backend-tasks/src/tasks/PluginTaskSchedulerImpl.ts:134:9)
[1]     at TaskWorker.runOnce (/Users/jake/git/backstage/node_modules/@backstage/backend-tasks/src/tasks/TaskWorker.ts:155:13)
[1]     at <anonymous> (/Users/jake/git/backstage/node_modules/@backstage/backend-tasks/src/tasks/TaskWorker.ts:75:31)
[1] 2024-06-13T14:18:40.343Z catalog debug task: puppetdb-provider:default:refresh will next occur around 2024-06-13T09:19:40.343-05:00 task=puppetdb-provider:default:refresh
```

I have created a custom transformer, but I am not sure how to override the default transformer with my custom one with the new backend system

### 👍 Expected behavior

- transformer does not have latest_report_status hardcoded in as it is not supported by the puppetdb api

### 👎 Actual Behavior with Screenshots

See logs

### 👟 Reproduction steps

packages/backend/src/index.ts: `backend.add(import('@backstage/plugin-catalog-backend-module-puppetdb/alpha'))`

app-config.yaml:
```
catalog
  providers:
    puppetdb:
      default:
        baseUrl: http://puppet-db.example.com:8080
        query: '["=","certname","puppet-host.domain"]'
        schedule:
          frequency: { minutes: 1 }
          timeout: { minutes: 1 }
```

### 🖥️ Your Environment

```
yarn run v1.22.22
$ /Users/jake/git/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.5.0 - darwin/arm64
node: v18.20.2
yarn: 1.22.22
cli:  0.26.6 (installed)
backstage:  1.27.6

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.21.7, 0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/backend-test-utils                                    0.3.8
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.6
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.12.5, 0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.32
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-bitbucket-server        0.1.32
  @backstage/plugin-catalog-backend-module-github                  0.6.1
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.26
  @backstage/plugin-catalog-backend-module-puppetdb                0.1.24
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.5
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.1
  @backstage/plugin-catalog-unprocessed-entities                   0.2.4
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-home-react                                     0.1.13
  @backstage/plugin-home                                           0.7.4
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.6
  @backstage/plugin-scaffolder                                     1.20.1
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.2.19, 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 1.73s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jagexjake** [comment]
Appears related to: https://github.com/backstage/backstage/commit/bc644fb451db508ff888c5e9557322d66a6723c4 
introduced in 1.23.0-next.2 https://github.com/backstage/backstage/blob/master/docs/releases/v1.23.0-next.2-changelog.md#backstageplugin-catalog-backend-module-puppetdb0115-next2

**Comment by freben** [comment]
Alright, sounds like it may be worth making `latest_report_status` optional in a typescript sense and then figure out how the code changes need to look to support that. Would love a contribution for that; for our own part we don't have a good way of testing that so if you make it work in your env it's a good input to the review 🙏

**Comment by jagexjake** [comment]
> Alright, sounds like it may be worth making `latest_report_status` optional in a typescript sense and then figure out how the code changes need to look to support that. Would love a contribution for that; for our own part we don't have a good way of testing that so if you make it work in your env it's a good input to the review 🙏

I can look at getting a PR in for that
In my opinion, re revert that commit as it is incompatible with the default puppetdb setup
Alternatively, optional as you say and look at using the nodes api: https://www.puppet.com/docs/puppetdb/7/api/query/v4/nodes 
as https://www.puppet.com/docs/puppetdb/7/api/query/v4/nodes#pdbqueryv4nodesnodefacts can get facts aswell but require multiple queries ... will look at contributing this option

**Comment by jagexjake** [comment]
@freben I have submitted a PR: https://github.com/backstage/backstage/pull/25228 
I have tested this against standard puppetdb 7 implementation.
It discovers against the `NODES_ENDPOINT`
and then for each node it will retrieve against the `FACTSET_ENDPOINT` and merge into the object before being sent to the transformer.

If you are able to help me with any missing stuff in the PR that would be appreciated.

Also are you able to assist me in how to provide a custom transformer for this plugin in the new backend setup? Alot of documentation is in the old backend setup

**Comment by jagexjake** [comment]
PR is still linked and waiting to be reviewed and merged

**Comment by camilaibs** [comment]
Hi @freben , the mentioned pull request was automatically closed, so I just want to double check if we would like to reopen it 🙂
