### ISSUE TITLE
🐛 Bug Report: Legacy custom auth provider with New Backend giving 403

### ISSUE THREAD

**Issue by jenil-harness** [backstage/backstage#25432]
### 📜 Description

We are migrating to New Backend System. We are facing an issue with API calls. All the API calls (catalog, scaffolder) are failing with 403 when permission are enabled.
Error message is
```{
    "error": {
        "name": "ResponseError",
        "message": "Request failed with 403 Forbidden",
        "response": {
            "size": 0,
            "timeout": 0
        },
        "body": {
            "error": {
                "name": "NotAllowedError",
                "message": "This endpoint does not allow 'service' credentials",
                "stack": "NotAllowedError: This endpoint does not allow 'service' credentials\n    at HttpAuthCompat.credentials (/Users/jeniljain/Projects/Harness/harness-idp/node_modules/@backstage/backend-common/src/auth/createLegacyAuthAdapters.ts:249:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/Users/jeniljain/Projects/Harness/harness-idp/node_modules/@backstage/plugin-permission-backend/src/service/router.ts:225:27)"
            },
            "request": {
                "method": "POST",
                "url": "/authorize"
            },
            "response": {
                "statusCode": 403
            }
        },
        "cause": {
            "name": "NotAllowedError",
            "message": "This endpoint does not allow 'service' credentials",
            "stack": "NotAllowedError: This endpoint does not allow 'service' credentials\n    at HttpAuthCompat.credentials (/Users/jeniljain/Projects/Harness/harness-idp/node_modules/@backstage/backend-common/src/auth/createLegacyAuthAdapters.ts:249:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/Users/jeniljain/Projects/Harness/harness-idp/node_modules/@backstage/plugin-permission-backend/src/service/router.ts:225:27)"
        },
        "statusCode": 403,
        "statusText": "Forbidden",
        "stack": "ResponseError: Request failed with 403 Forbidden\n    at Function.fromResponse (/Users/jeniljain/Projects/Harness/harness-idp/node_modules/@backstage/errors/src/errors/ResponseError.ts:76:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at PermissionClient.makeRequest (/Users/jeniljain/Projects/Harness/harness-idp/node_modules/@backstage/plugin-permission-common/src/PermissionClient.ts:160:13)\n    at AuthorizedEntitiesCatalog.facets (/Users/jeniljain/Projects/Harness/harness-idp/node_modules/@backstage/plugin-catalog-backend/src/service/AuthorizedEntitiesCatalog.ts:276:7)\n    at <anonymous> (/Users/jeniljain/Projects/Harness/harness-idp/node_modules/@backstage/plugin-catalog-backend/src/service/createRouter.ts:232:26)"
    },
    "request": {
        "method": "GET",
        "url": "/entity-facets?facet=kind"
    },
    "response": {
        "statusCode": 403
    }
} 
```

**Could someone please help me with resources / info for migrating auth integration to the new backend system. I went through docs but seems like I couldn't figure out how to do it.**

### 👍 Expected behavior

API should not give 403 as I have disabled default auth policy.

### 👎 Actual Behavior with Screenshots

<img width="566" alt="Screenshot 2024-06-27 at 12 43 18 PM" src="https://github.com/backstage/backstage/assets/62697923/cb6d635b-92d7-4a7c-bdfc-c3a27303d0fd">
<img width="616" alt="Screenshot 2024-06-27 at 12 43 28 PM" src="https://github.com/backstage/backstage/assets/62697923/9eaed829-7d0b-467a-8870-0f7e4e53aeab">

### 👟 Reproduction steps

1. set `dangerouslyDisableDefaultAuthPolicy` as true and enable the permission.
2. Go to any catalog page.

### 📃 Provide the context for the Bug.

We are using our own legacy Auth Integration.

**backend/src/plugins/providers/harness.ts**
```
export class HarnessAuthProvider implements AuthProviderRouteHandlers {
  private readonly signInResolver: SignInResolver<HarnessAuthResult>;
  private readonly resolverContext: AuthResolverContext;

  constructor(options: HarnessOptions) {
    this.signInResolver = options.signInResolver;
    this.resolverContext = options.resolverContext;
  }

  async start() {
    console.log('start to be implemented');
  }
  async frameHandler() {
    console.log('frame to be implemented');
  }
  async logout() {
    console.log('logout to be implemented');
  }

  async refresh(request: Request, response: any) {
  // Making a call to our service to validate credentials.
  }
}

export const harness: Readonly<{
  create: (
    options?:
      | {
          authHandler?: AuthHandler<HarnessAuthResult> | undefined;
          signIn: { resolver: SignInResolver<HarnessAuthResult> };
        }
      | undefined,
  ) => AuthProviderFactory;
  resolvers: never;
}> = createAuthProviderIntegration({
  create(options?: {
    authHandler?: AuthHandler<HarnessAuthResult>;
    signIn: {
      resolver: SignInResolver<HarnessAuthResult>;
    };
  }) {
    return ({ resolverContext }) => {
      if (!options?.signIn.resolver)
        throw new Error('SignIn resolver is required');

      return new HarnessAuthProvider({
        signInResolver: options?.signIn?.resolver,
        resolverContext,
      });
    };
  },
});
```

**backend/src/plugins/auth.ts**
```
import { harness } from './providers/harness';

const harnessServiceAuthHelper = new HarnessServiceAuthHelper();
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      harness: harness.create({
        signIn: {
          resolver: async (returnValueFromRefresh, ctx) => {
            const harnessEntityName = harnessUserEntity(
              returnValueFromRefresh.result,
            );

            try {
              const { entity } = await ctx.findCatalogUser({
                entityRef: {
                  name: harnessEntityName,
                },
                annotations: {
                  [HARNESS_UUID_ANNOTATION]: returnValueFromRefresh.result.uuid,
                },
              });


              const ownershipRefs = getDefaultOwnershipEntityRefs(entity);
              return ctx.issueToken({
                claims: {
                  sub: stringifyEntityRef(entity),
                  ent: ownershipRefs,
                },
              });
            } catch (error) {
      // Error handling
            }
          },
        },
      }),
    },
  });
}
```

**backend/index.ts**

```
...
  backend.add(legacyPlugin('auth', import('./plugins/auth')));
...
```

Also I have set `backend.auth.dangerouslyDisableDefaultAuthPolicy` as true.,

### 🖥️ Your Environment

```
OS:   Darwin 23.5.0 - darwin/arm64
node: v18.19.1
yarn: 3.2.3
cli:  0.25.0 (installed)
backstage:  1.26.5

Dependencies:
  @backstage/app-defaults                                          1.5.7
  @backstage/backend-app-api                                       0.4.5, 0.5.14, 0.7.9
  @backstage/backend-common                                        0.23.2, 0.18.5, 0.19.10, 0.20.2, 0.21.7, 0.22.0
  @backstage/backend-defaults                                      0.3.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.14
  @backstage/backend-plugin-api                                    0.5.4, 0.6.21
  @backstage/backend-tasks                                         0.5.26
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.2.0, 1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6
  @backstage/cli                                                   0.26.10
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.13.0
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.12.4, 0.11.2, 0.12.5, 0.13.10, 0.14.8
  @backstage/core-plugin-api                                       1.0.6, 1.9.3
  @backstage/dev-utils                                             1.0.34
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28
  @backstage/integration                                           1.12.0
  @backstage/plugin-adr-backend                                    0.4.14
  @backstage/plugin-adr-common                                     0.2.22, 0.2.23
  @backstage/plugin-adr                                            0.6.18
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.70
  @backstage/plugin-app-node                                       0.1.21
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.16
  @backstage/plugin-auth-backend-module-github-provider            0.1.18
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.18
  @backstage/plugin-auth-backend-module-google-provider            0.1.18
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.14
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.16
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-azure-devops-backend                           0.5.5
  @backstage/plugin-azure-devops-common                            0.3.2, 0.4.2
  @backstage/plugin-azure-devops                                   0.4.4
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.19
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.10
  @backstage/plugin-catalog-backend                                1.23.2
  @backstage/plugin-catalog-common                                 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.12.3
  @backstage/plugin-catalog-react                                  1.12.1
  @backstage/plugin-catalog-unprocessed-entities                   0.2.5
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-circleci                                       0.3.35
  @backstage/plugin-devtools-common                                0.1.10
  @backstage/plugin-devtools                                       0.1.15
  @backstage/plugin-dynatrace                                      10.0.4
  @backstage/plugin-events-node                                    0.2.22, 0.3.7
  @backstage/plugin-firehydrant                                    0.2.19
  @backstage/plugin-github-actions                                 0.6.16
  @backstage/plugin-github-pull-requests-board                     0.2.1
  @backstage/plugin-home-react                                     0.1.14
  @backstage/plugin-home                                           0.7.6
  @backstage/plugin-jenkins-backend                                0.3.7
  @backstage/plugin-jenkins-common                                 0.1.25, 0.1.26
  @backstage/plugin-jenkins                                        0.9.10
  @backstage/plugin-kubernetes-backend                             0.14.1
  @backstage/plugin-kubernetes-common                              0.7.6, 0.8.0
  @backstage/plugin-kubernetes-node                                0.1.15
  @backstage/plugin-kubernetes-react                               0.4.0
  @backstage/plugin-kubernetes                                     0.11.11
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-pagerduty                                      0.7.7
  @backstage/plugin-permission-backend                             0.5.45
  @backstage/plugin-permission-common                              0.7.14
  @backstage/plugin-permission-node                                0.7.32
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.11
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.13
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.11
  @backstage/plugin-scaffolder-backend-module-github               0.3.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.3
  @backstage/plugin-scaffolder-backend                             1.22.11
  @backstage/plugin-scaffolder-common                              1.5.3
  @backstage/plugin-scaffolder-node                                0.1.5, 0.4.7
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.22.0
  @backstage/plugin-search-backend-module-catalog                  0.1.27
  @backstage/plugin-search-backend-module-pg                       0.5.31
  @backstage/plugin-search-backend-module-techdocs                 0.1.26
  @backstage/plugin-search-backend-node                            1.2.26
  @backstage/plugin-search-backend                                 1.5.13
  @backstage/plugin-search-common                                  1.2.12
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.12
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-sonarqube-backend                              0.2.19
  @backstage/plugin-sonarqube-react                                0.1.16
  @backstage/plugin-sonarqube                                      0.7.17
  @backstage/plugin-splunk-on-call                                 0.4.24
  @backstage/plugin-techdocs-backend                               1.10.8
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.11
  @backstage/plugin-techdocs-node                                  1.12.7
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.8
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.7
  @backstage/theme                                                 0.2.19, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by mfb1909** [comment]
Has anything been found with this? I'm getting the same error at the moment, also using my own legacy auth.

**Comment by jhl0214** [comment]
Is there no solution other than upgrading to 1.28? I'm slowly updating to latest version but currently on 1.18 so it's gonna take some time to upgrade as I'm updating 1 version at a time.

**Comment by benjdlambert** [comment]
>  I'm slowly updating to latest version but currently on 1.18 

I'm not sure how you're getting these error messages on 1.18 as the error message you're getting came about 7 months after that release, it's most likely that you have inconsistent versions, maybe doing a `yarn add` or something and that's pulling in incompatible versions for everything or duplicates of dependencies as it would install the latest version of that package, and then you've got the core framework outdated for the plugin version which could lead to these error messages.

I'd check to see what's bringing in different versions of `backend-app-api` as a start, and also what's bringing in different versions of `backend-plugin-api` to see if you can get rid of some of those duplicated dependencies.

**Comment by freben** [comment]
Indeed the `/authorize` endpoint should never be called with service credentials. The server permission client should be checking the incoming credential type, and take the decision without making this call if it's a service credential. Only if it's a user credential, should it reach out to the permissions backend to take a decision. Not sure how this sequence of events came to be.

**Comment by Rugvip** [comment]
We're deprecating the `legacyPlugin` helper in the next release, but I'd already now encourage completely migrate away from using it since it doesn't have great compatibility with the new core services. Especially avoid using it for any core plugins that have already has been migrated to the new backend system.

**Comment by Rugvip** [comment]
@jhl0214 could you provide a bit more information about the error you're setting and your setup?

**Comment by jhl0214** [comment]
> @jhl0214 could you provide a bit more information about the error you're setting and your setup?

Sorry, issue resolved!

**Comment by jhl0214** [comment]
> @jhl0214 could you provide a bit more information about the error you're setting and your setup?

Actually, I don't have this problem anymore, but looks like proxy is giving 401? I am passing the backstage token as the Authorization header and even tried setting 'dangerously-allow-unauthenticated', but no luck on that. Any idea on this? I'm using version 1.29.2.

**Comment by pedronastasi** [comment]
I'm facing this issue currently with the `1.24.2` version . Could you provide me some more insights on how you fixed it ? @jhl0214
