### ISSUE TITLE
🐛 Bug Report: Upgrading PostgreSql RDS minor version is causing timeout issues

### ISSUE THREAD

**Issue by shivasantosh** [backstage/backstage#25557]
### 📜 Description

Hi there,

I am using node 16 and backstage 1.9.1 facing below error after my RDS Postgresql is upgraded minor version

```
Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
at /opt/app-root/src/node_modules/@backstage/backend-common/dist/index.cjs.js:1024:17
at async CatalogBuilder.build (/opt/app-root/src/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:4344:22)
at async createPlugin$h (/opt/app-root/src/packages/backend/dist/index.cjs.js:1050:40)
at async main (/opt/app-root/src/packages/backend/dist/index.cjs.js:4626:29)
```

Even though I revert RDS to old version it is not working still.

### 👍 Expected behavior

It should start the Backstage normally and successfully connect to postgres

### 👎 Actual Behavior with Screenshots

Backstage fails to start with the stacktrace mentioned in the Description section

### 👟 Reproduction steps

#this is pulling image from internal cloud
FROM node16:2022-07-25-BUILD-16

WORKDIR /opt/app-root/src
RUN chmod -R 777 /opt/app-root/src

COPY yarn.lock package.json .npmrc packages/backend/dist/skeleton.tar.gz ./

RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production --network-timeout 600000 && rm -rf "$(yarn cache dir)"

COPY packages/backend/dist/bundle.tar.gz app-config.yaml ./

RUN tar xzf bundle.tar.gz && rm bundle.tar.gz
RUN chmod -R 775 /opt/app-root/src

EXPOSE 7000

CMD ["node", "packages/backend", "--config", "app-config.yaml"]

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Hi! Release 1.9.1 is very old, please update to a more recent version as there have been many changes in this area. I'll close this issue for now, but please report again if the issue persists in the latest version.
