### ISSUE TITLE
🐛 Bug Report: Catalog Error awsS3 provider - AccessDenied Exception

### ISSUE THREAD

**Issue by visalishalini** [backstage/backstage#25661]
### 📜 Description

When installing backstage helm chart, kubernetes pod seems to be running but pod logs show the below accessdenied error
Please can you help me in resolving this issue?

2024-07-17T01:20:17.424Z catalog error awsS3-provider:default refresh failed, AccessDenied: Access Denied Access Denied type=plugin target=awsS3-provider:default class=AwsS3EntityProvider taskId=awsS3-provider:default:refresh taskInstanceId=5ada4cec-491c-40d3-a7f1-4b225cfebb51 name=AccessDenied $fault=client $metadata=[object Object] Code=AccessDenied RequestId=FPF26WG8ZGPMQRE2 HostId=JHxEC8ej3m8E9fXwH5/xyRQvJOIAqOm5H3XGAEeZoMYb9HjnutPmTBZ4kigOIshRIKvPKO8RdZg= stack=AccessDenied: Access Denied
    at throwDefaultError (/app/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /app/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_CommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /app/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:225:18
    at async /app/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20
    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14
    at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async AwsS3EntityProvider.listAllObjectKeys (/app/node_modules/@backstage/plugin-catalog-backend-module-aws/dist/cjs/AwsS3EntityProvider-Dh7NVD-U.cjs.js:190:16)
    at async AwsS3EntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-aws/dist/cjs/AwsS3EntityProvider-Dh7NVD-U.cjs.js:168:18)
    at async fn (/app/node_modules/@backstage/plugin-catalog-backend-module-aws/dist/cjs/AwsS3EntityProvider-Dh7NVD-U.cjs.js:123:13)
    at async TaskWorker.fn (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:605:9)
    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:356:7)
    at async /app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:304:31

Please can you help with resolving the issue?

### 👍 Expected behavior

Objects will be discovered without this error

### 👎 Actual Behavior with Screenshots

Error:

2024-07-17T01:20:17.424Z catalog error awsS3-provider:default refresh failed, AccessDenied: Access Denied Access Denied type=plugin target=awsS3-provider:default class=AwsS3EntityProvider taskId=awsS3-provider:default:refresh taskInstanceId=5ada4cec-491c-40d3-a7f1-4b225cfebb51 name=AccessDenied $fault=client $metadata=[object Object] Code=AccessDenied RequestId=FPF26WG8ZGPMQRE2 HostId=JHxEC8ej3m8E9fXwH5/xyRQvJOIAqOm5H3XGAEeZoMYb9HjnutPmTBZ4kigOIshRIKvPKO8RdZg= stack=AccessDenied: Access Denied
    at throwDefaultError (/app/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /app/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_CommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /app/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:225:18
    at async /app/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20
    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14
    at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async AwsS3EntityProvider.listAllObjectKeys (/app/node_modules/@backstage/plugin-catalog-backend-module-aws/dist/cjs/AwsS3EntityProvider-Dh7NVD-U.cjs.js:190:16)
    at async AwsS3EntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-aws/dist/cjs/AwsS3EntityProvider-Dh7NVD-U.cjs.js:168:18)
    at async fn (/app/node_modules/@backstage/plugin-catalog-backend-module-aws/dist/cjs/AwsS3EntityProvider-Dh7NVD-U.cjs.js:123:13)
    at async TaskWorker.fn (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:605:9)
    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:356:7)
    at async /app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:304:31

### 👟 Reproduction steps

install helm chart with awss3 integration as per the doc : https://backstage.io/docs/integrations/aws-s3/locations

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
This looks like an Authorization issue from AWS side, have you configured the AWS credentials properly in your `app-config.yaml`? Something like this: https://backstage.io/docs/integrations/aws-s3/locations

There's a possibility that this could  something to do with the helm chart if not, so you might want to move this issue to that upstream repository instead :pray:
