### ISSUE TITLE
🐛 Bug Report: "Resource not accessible by Integration" with Github App; Backstage release 1.29

### ISSUE THREAD

**Issue by mspiegel31** [backstage/backstage#25689]
### 📜 Description

After upgrading to `1.29`, github catalog discovery (from `@backstage/plugin-catalog-backend-module-github/alpha`) is failing when using a github app.  Graphql queries are failing with `Resource not accessible by integration` errors, which almost always means the configured Github App has insufficient permissions to execute the graphql query.

### 👍 Expected behavior

Discover github entities without throwing graphql errrors.

## Request
```graphql

    query repositories($org: String!, $catalogPathRef: String!, $cursor: String) {
      repositoryOwner(login: $org) {
        login
        repositories(first: 50, after: $cursor) {
          nodes {
            name
            catalogInfoFile: object(expression: $catalogPathRef) {
              __typename
              ... on Blob {
                id
                text
              }
            }
            url
            isArchived
            isFork
            visibility
            repositoryTopics(first: 100) {
              nodes {
                ... on RepositoryTopic {
                  topic {
                    name
                  }
                }
              }
            }
            defaultBranchRef {
              name
            }
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
    }
```

## Response (truncated)
<img width="568" alt="Screenshot 2024-07-18 at 10 22 01 AM" src="https://github.com/user-attachments/assets/172c24ce-a155-486b-b4b2-4ab789b30613">

## Stack (truncated)

```
GraphqlResponseError: Request failed due to following response errors:
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
    at /app/node_modules/@octokit/graphql/dist-node/index.js:105:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async queryWithPaging (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-CJpx_erw.cjs.js:606:22)
    at async getOrganizationRepositories (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-CJpx_erw.cjs.js:523:24)
    at async GithubEntityProvider.findCatalogFiles (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-CJpx_erw.cjs.js:841:54)
    at async GithubEntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-CJpx_erw.cjs.js:813:21)
    at async fn (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-CJpx_erw.cjs.js:798:13)
    at async TaskWorker.fn (/app/node_modules/@backstage/backend-defaults/dist/scheduler.cjs.js:552:9)
    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-defaults/dist/scheduler.cjs.js:310:7)
    at async /app/node_modules/@backstage/backend-defaults/dist/scheduler.cjs.js:258:31
```

### 👟 Reproduction steps

1. upgrade to backstage `1.29` from `1.28`
2. proactively migrate deprecated interfaces from `backend-common`
3. uninstall `backend-common` in plugins/packages that no longer use them

### 📃 Provide the context for the Bug.

- we are _not_ using the events-based configuration for our github discovery

### 🖥️ Your Environment

```
$ yarn backstage-cli info                                                            arn:aws:eks:us-east-1:656168747096:cluster/spoton-ue1-corp-eks-cluster
yarn run v1.22.19
$ /Users/michaelspiegel/development/production/spoton-backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.0.0 - darwin/arm64
node: v20.15.1
yarn: 1.22.19
cli:  0.26.11 (installed)
backstage:  1.29.0

Dependencies:
  @backstage/app-defaults                                          1.5.8
  @backstage/backend-app-api                                       0.7.9, 0.8.0
  @backstage/backend-common                                        0.21.7, 0.23.3
  @backstage/backend-defaults                                      0.4.0
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.15
  @backstage/backend-plugin-api                                    0.6.21, 0.7.0
  @backstage/backend-tasks                                         0.5.27
  @backstage/backend-test-utils                                    0.4.4
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.26.11
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.0
  @backstage/core-compat-api                                       0.2.7
  @backstage/core-components                                       0.12.5, 0.14.9
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.35
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.29
  @backstage/integration                                           1.13.0
  @backstage/plugin-api-docs                                       0.11.7
  @backstage/plugin-app-backend                                    0.3.71
  @backstage/plugin-app-node                                       0.1.22
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.14
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.5
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.5
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.17
  @backstage/plugin-auth-backend-module-github-provider            0.1.19
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.19
  @backstage/plugin-auth-backend-module-google-provider            0.1.19
  @backstage/plugin-auth-backend-module-guest-provider             0.1.8
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.17
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.15
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.15
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.3
  @backstage/plugin-auth-backend                                   0.22.9
  @backstage/plugin-auth-node                                      0.4.17
  @backstage/plugin-auth-react                                     0.1.4
  @backstage/plugin-bitbucket-cloud-common                         0.2.21
  @backstage/plugin-catalog-backend-module-bitbucket-cloud         0.2.9
  @backstage/plugin-catalog-backend-module-github                  0.6.5
  @backstage/plugin-catalog-backend-module-logs                    0.0.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.20
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.9
  @backstage/plugin-catalog-backend                                1.24.0
  @backstage/plugin-catalog-common                                 1.0.25
  @backstage/plugin-catalog-graph                                  0.4.7
  @backstage/plugin-catalog-import                                 0.12.1
  @backstage/plugin-catalog-node                                   1.12.4
  @backstage/plugin-catalog-react                                  1.12.2
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.3
  @backstage/plugin-catalog-unprocessed-entities                   0.2.6
  @backstage/plugin-catalog                                        1.21.1
  @backstage/plugin-events-node                                    0.3.8
  @backstage/plugin-org                                            0.6.27
  @backstage/plugin-permission-backend                             0.5.46
  @backstage/plugin-permission-common                              0.7.14, 0.8.0
  @backstage/plugin-permission-node                                0.7.32, 0.8.0
  @backstage/plugin-permission-react                               0.4.24
  @backstage/plugin-proxy-backend                                  0.5.3
  @backstage/plugin-scaffolder-backend-module-azure                0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.12
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.14
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.12
  @backstage/plugin-scaffolder-backend-module-github               0.4.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.4
  @backstage/plugin-scaffolder-backend                             1.23.0
  @backstage/plugin-scaffolder-common                              1.5.4
  @backstage/plugin-scaffolder-node                                0.4.8
  @backstage/plugin-scaffolder-react                               1.10.0
  @backstage/plugin-scaffolder                                     1.23.0
  @backstage/plugin-search-backend-module-catalog                  0.1.28
  @backstage/plugin-search-backend-module-pg                       0.5.32
  @backstage/plugin-search-backend-module-techdocs                 0.1.27
  @backstage/plugin-search-backend-node                            1.2.27
  @backstage/plugin-search-backend                                 1.5.14
  @backstage/plugin-search-common                                  1.2.13
  @backstage/plugin-search-react                                   1.7.13
  @backstage/plugin-search                                         1.4.14
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.9
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.12
  @backstage/plugin-techdocs-node                                  1.12.8
  @backstage/plugin-techdocs-react                                 1.2.6
  @backstage/plugin-techdocs                                       1.10.7
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.9
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.8
  @backstage/theme                                                 0.2.19, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 0.91s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by csuich2** [comment]
What version did you upgrade from? I'm on 1.27.7 and am attempting to add the GitHub Org Data plugin and am seeing a similar error despite having the app permissions listed here: https://backstage.io/docs/integrations/github/github-apps/#app-permissions

```json
{
  ...,
  "response": {
    "data": {
      "organization": null
    },
    "errors": [
      {
        "extensions": {
          "saml_failure": false
        },
        "locations": [
          {
            "column": 9,
            "line": 4
          }
        ],
        "message": "Resource not accessible by integration",
        "path": [
          "organization",
          "membersWithRole"
        ],
        "type": "FORBIDDEN"
      }
    ]
  },
  ...
}
```

**Comment by mspiegel31** [comment]
this is migrating from `1.28` -> `1.29`

**Comment by benjdlambert** [comment]
@mspiegel31 my guess is that this query is net new for the repository events support which droppped here: https://github.com/backstage/backstage/commit/ba7d58643a84ecaa56968b4bd649d7a701bc2c2f

@pjungermann what permissions would be needed in the GitHub app after these changes, I wonder if there's a documentation update needed here to add some more permissions to the app.

**Comment by benjdlambert** [comment]
@csuich2 it looks like either the GitHub app is not installed in the right place, so you're maybe reading from an Organization that the GitHub app isn't installed in, or the GitHub app doesn't have the correct Org read permissions for members.

This change in the app also will need to be approved in each of the installations, so it's possible that there could be outstanding requests that have not been approved yet.

https://backstage.io/docs/integrations/github/github-apps/#updating-permissions
