### ISSUE TITLE
🐛 Bug Report: Cannot find module 'app/package.json. Locally works, on K8S/container it fails. Ver 1.29.1

### ISSUE THREAD

**Issue by eilonash92** [backstage/backstage#25724]
### 📜 Description

Locally the app is working, on a container it fails. Backstage Ver 1.29.1

During deployment of backstage on K8S getting this error when the app is starting -

```
{"level":"info","message":"Plugin initialization started: 'app', 'proxy', 'scaffolder', 'techdocs', 'auth', 'catalog', 'permission', 'search', 'oneclickPlugin'","service":"backstage","type":"initialization"}
{"level":"warn","message":"DEPRECATION WARNING: The backend.auth.keys config has been replaced by backend.auth.externalAccess, see https://backstage.io/docs/auth/service-to-service-auth","service":"backstage"}
/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1680
            throw new errors.ForwardedError(
                  ^

ForwardedError: Plugin 'app' startup failed; caused by Error: Cannot find module 'app/package.json'
Require stack:
- /app/node_modules/@backstage/backend-plugin-api/dist/cjs/paths-D7KGMZeP.cjs.js
- /app/node_modules/@backstage/backend-plugin-api/dist/index.cjs.js
- /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js
- /app/node_modules/@backstage/backend-defaults/dist/index.cjs.js
- /app/packages/backend/dist/index.cjs.js
    at /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1680:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1679:11
    at async Promise.all (index 0)
    ... 2 lines matching cause stack trace ...
    at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1762:5) {
```

### 👍 Expected behavior

Start the service

### 👎 Actual Behavior with Screenshots

App not starting

### 👟 Reproduction steps

Deploying backstage on K8S

### 🖥️ Your Environment

This is what runs locally.

I can't get the info from the container, but I guess its the same.

```
OS:   Darwin 23.5.0 - darwin/x64
node: v18.12.1
yarn: 1.22.1
cli:  0.26.11 (installed)
backstage:  1.29.1

Dependencies:
  @backstage/app-defaults                                          1.5.8
  @backstage/backend-app-api                                       0.8.0
  @backstage/backend-common                                        0.23.3
  @backstage/backend-defaults                                      0.4.1
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.15
  @backstage/backend-plugin-api                                    0.7.0
  @backstage/backend-tasks                                         0.5.27
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.26.11
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.0
  @backstage/core-compat-api                                       0.2.7
  @backstage/core-components                                       0.14.9
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.35
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.29
  @backstage/integration                                           1.13.0
  @backstage/plugin-api-docs                                       0.11.7
  @backstage/plugin-app-backend                                    0.3.71
  @backstage/plugin-app-node                                       0.1.22
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.14
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.5
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.5
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.17
  @backstage/plugin-auth-backend-module-github-provider            0.1.19
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.19
  @backstage/plugin-auth-backend-module-google-provider            0.1.19
  @backstage/plugin-auth-backend-module-guest-provider             0.1.8
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.17
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.15
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.15
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.3
  @backstage/plugin-auth-backend                                   0.22.9
  @backstage/plugin-auth-node                                      0.4.17
  @backstage/plugin-auth-react                                     0.1.4
  @backstage/plugin-bitbucket-cloud-common                         0.2.21
  @backstage/plugin-catalog-backend-module-github-org              0.1.17
  @backstage/plugin-catalog-backend-module-github                  0.6.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.20
  @backstage/plugin-catalog-backend                                1.24.0
  @backstage/plugin-catalog-common                                 1.0.25
  @backstage/plugin-catalog-graph                                  0.4.7
  @backstage/plugin-catalog-import                                 0.12.1
  @backstage/plugin-catalog-node                                   1.12.4
  @backstage/plugin-catalog-react                                  1.12.2
  @backstage/plugin-catalog                                        1.21.1
  @backstage/plugin-events-node                                    0.3.8
  @backstage/plugin-home-react                                     0.1.15
  @backstage/plugin-home                                           0.7.7
  @backstage/plugin-org                                            0.6.27
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.19
  @backstage/plugin-permission-backend                             0.5.46
  @backstage/plugin-permission-common                              0.8.0
  @backstage/plugin-permission-node                                0.8.0
  @backstage/plugin-permission-react                               0.4.24
  @backstage/plugin-proxy-backend                                  0.5.3
  @backstage/plugin-scaffolder-backend-module-azure                0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.12
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.14
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.12
  @backstage/plugin-scaffolder-backend-module-github               0.4.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.4
  @backstage/plugin-scaffolder-backend                             1.23.0
  @backstage/plugin-scaffolder-common                              1.5.4
  @backstage/plugin-scaffolder-node                                0.4.8
  @backstage/plugin-scaffolder-react                               1.10.0
  @backstage/plugin-scaffolder                                     1.23.0
  @backstage/plugin-search-backend-module-catalog                  0.1.28
  @backstage/plugin-search-backend-module-techdocs                 0.1.27
  @backstage/plugin-search-backend-node                            1.2.27
  @backstage/plugin-search-backend                                 1.5.14
  @backstage/plugin-search-common                                  1.2.13
  @backstage/plugin-search-react                                   1.7.13
  @backstage/plugin-search                                         1.4.14
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.9
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.12
  @backstage/plugin-techdocs-node                                  1.12.8
  @backstage/plugin-techdocs-react                                 1.2.6
  @backstage/plugin-techdocs                                       1.10.7
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.9
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.8
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 1.66s.

```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by zwilias** [comment]
I think there are a couple of things that go into this successfully working when using `backend-app-api`:
- `packages/backend/package.json` having a dependency on `"app": "link:../app"`. Note that this isn't required locally as the backend doesn't serve the frontend there, and also note that `knip` thinks it's unused - it is needed however!
- _something_ running `yarn build:backend`
- a `Dockerfile` that puts the skeleton and backend bundles in place

Having some insight into how those steps are setup in your case is probably helpful :)

**Comment by benjdlambert** [comment]
This is the `app-backend` plugin failing to startup. As mentioned above you'll want to make sure that the `app` is a dependency of the `backend` if you want to use this plugin. It looks like it could be missing.

**Comment by eilonash92** [comment]
@zwilias @benjdlambert 

my backend/package.json -
```
{
  "name": "backend",
  "version": "0.0.0",
  "main": "dist/index.cjs.js",
  "types": "src/index.ts",
  "private": true,
  "backstage": {
    "role": "backend"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "lint": "backstage-cli package lint",
    "test": "backstage-cli package test",
    "clean": "backstage-cli package clean",
    "build-image": "docker build ../.. -f Dockerfile --tag backstage"
  },
  "dependencies": {
    "@backstage/backend-common": "^0.23.3",
    "@backstage/backend-defaults": "^0.4.1",
    "@backstage/backend-tasks": "^0.5.27",
    "@backstage/config": "^1.2.0",
    "@backstage/plugin-app-backend": "^0.3.71",
    "@backstage/plugin-auth-backend": "^0.22.9",
    "@backstage/plugin-auth-backend-module-github-provider": "^0.1.19",
    "@backstage/plugin-auth-backend-module-guest-provider": "^0.1.8",
    "@backstage/plugin-auth-node": "^0.4.17",
    "@backstage/plugin-catalog-backend": "^1.24.0",
    "@backstage/plugin-catalog-backend-module-github-org": "^0.1.17",
    "@backstage/plugin-catalog-backend-module-scaffolder-entity-model": "^0.1.20",
    "@backstage/plugin-permission-backend": "^0.5.46",
    "@backstage/plugin-permission-backend-module-allow-all-policy": "^0.1.19",
    "@backstage/plugin-permission-common": "^0.8.0",
    "@backstage/plugin-permission-node": "^0.8.0",
    "@backstage/plugin-proxy-backend": "^0.5.3",
    "@backstage/plugin-scaffolder-backend": "^1.23.0",
    "@backstage/plugin-search-backend": "^1.5.14",
    "@backstage/plugin-search-backend-module-catalog": "^0.1.28",
    "@backstage/plugin-search-backend-module-techdocs": "^0.1.27",
    "@backstage/plugin-search-backend-node": "^1.2.27",
    "@backstage/plugin-techdocs-backend": "^1.10.9",
    "@internal/backstage-plugin-oneclick-backend": "^0.1.0",
    "better-sqlite3": "^9.0.0",
    "dockerode": "^3.3.1",
    "node-gyp": "^9.0.0",
    "pg": "^8.12.0",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "@backstage/cli": "^0.26.11",
    "@types/dockerode": "^3.3.0",
    "@types/express": "^4.17.6",
    "@types/express-serve-static-core": "^4.17.5",
    "@types/luxon": "^2.0.4"
  },
  "files": [
    "dist"
  ]
}
```

The command I run is -
```
docker buildx build --build-arg NPM_TOKEN="blabla" --cache-from type=gha --cache-to type=gha,mode=max --file Dockerfile --iidfile /home/runner/work/_temp/docker-actions-toolkit-h84ggh/build-iidfile-66e1243b3a.txt --attest type=provenance,disabled=true --tag xxxx/xxxx-backstage:xxxx-backstage_release-1.0.7 --metadata-file /home/runner/work/_temp/docker-actions-toolkit-h84ggh/build-metadata-63aa4d3e58.json
```

My dockerfile (taken from the doc) in the root file -
```
# This dockerfile builds an image for the backend package.
# It should be executed with the root of the repo as docker context.
#
# Before building this image, be sure to have run the following commands in the repo root:
#
# yarn install
# yarn tsc
# yarn build:backend
#
# Once the commands have been run, you can build the image using `yarn build-image`

FROM node:18-bookworm-slim

# Install isolate-vm dependencies, these are needed by the @backstage/plugin-scaffolder-backend.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends python3 g++ build-essential && \
    yarn config set python /usr/bin/python3

# Install sqlite3 dependencies. You can skip this if you don't use sqlite3 in the image,
# in which case you should also move better-sqlite3 to "devDependencies" in package.json.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev

# From here on we use the least-privileged `node` user to run the backend.
USER node

# This should create the app dir as `node`.
# If it is instead created as `root` then the `tar` command below will fail: `can't create directory 'packages/': Permission denied`.
# If this occurs, then ensure BuildKit is enabled (`DOCKER_BUILDKIT=1`) so the app dir is correctly created as `node`.
WORKDIR /app

# This switches many Node.js dependencies to production mode.
ENV NODE_ENV production

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY --chown=node:node yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --production --network-timeout 300000

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY --chown=node:node packages/backend/dist/bundle.tar.gz app-config*.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml"]
```

**Comment by zwilias** [comment]
Try adding `"app": "link:../app"` to the `dependencies` in that `packages/backend/package.json` file - that definitely seems to have gone missing 😅

**Comment by crazy-canux** [comment]
I got the same issue. 
"app": "link:../app" not working.

**Comment by crazy-canux** [comment]
After use "example-app": "link:../app" the error has gone, but UI not working.

`An error occurred: Expected Backstage token in sign-in response`

**Comment by Rugvip** [comment]
Hmm, hard to say exactly what might be wrong from that information. It could help to try to step through the auth flow manually to see where and how it fails, see https://backstage.io/docs/auth/troubleshooting#stepping-through-authentication-manually

**Comment by crazy-canux** [comment]
Maybe some chaos with my browser or environment. It works now.

**Comment by benjdlambert** [comment]
@eilonash92 did you manage to get this working?

**Comment by kunchalavikram1427** [comment]
I'm getting the same error
```
code:internal/modules/cjs/loader:1143
 throw err;
 ^

Error: Cannot find module '/app/start'
  at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
  at Module._load (node:internal/modules/cjs/loader:981:27)
  at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
  at node:internal/main/run_main_module:28:49 {
 code: 'MODULE_NOT_FOUND',
 requireStack: []
}
```

My`packages/backend/package.json` does include `"app": "link:../app"`
```
{
  "name": "backend",
  "version": "0.0.0",
  "main": "dist/index.cjs.js",
  "types": "src/index.ts",
  "private": true,
  "backstage": {
    "role": "backend"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "lint": "backstage-cli package lint",
    "test": "backstage-cli package test",
    "clean": "backstage-cli package clean",
    "build-image": "docker build ../.. -f Dockerfile --tag backstage"
  },
  "dependencies": {
    "@backstage/backend-common": "^0.21.5",
    "@backstage/backend-tasks": "^0.5.20",
    "@backstage/catalog-client": "^1.6.2",
    "@backstage/catalog-model": "^1.4.5",
    "@backstage/config": "^1.2.0",
    "@backstage/plugin-app-backend": "^0.3.63",
    "@backstage/plugin-auth-backend": "^0.22.2",
    "@backstage/plugin-auth-node": "^0.4.10",
    "@backstage/plugin-catalog-backend": "^1.20.0",
    "@backstage/plugin-jenkins-backend": "^0.4.2",
    "@backstage/plugin-kubernetes-backend": "^0.16.2",
    "@backstage/plugin-permission-backend": "^0.5.39",
    "@backstage/plugin-permission-common": "^0.7.13",
    "@backstage/plugin-permission-node": "^0.7.26",
    "@backstage/plugin-proxy-backend": "^0.4.13",
    "@backstage/plugin-scaffolder-backend": "^1.22.2",
    "@backstage/plugin-search-backend": "^1.5.5",
    "@backstage/plugin-search-backend-module-pg": "^0.5.24",
    "@backstage/plugin-search-backend-node": "^1.2.19",
    "@backstage/plugin-techdocs-backend": "^1.10.2",
    "@internal/backstage-plugin-auth-fork-backend-module-auth-okta-fork": "^0.1.0",
    "@internal/backstage-plugin-kubernetes-sie-backend": "^0.1.0",
    "@internal/backstage-plugin-search-backend-module-custom": "^0.1.0",
    "@opentelemetry/auto-instrumentations-node": "^0.46.1",
    "@opentelemetry/exporter-prometheus": "^0.51.1",
    "@opentelemetry/sdk-node": "^0.51.1",
    "@procore-oss/backstage-plugin-announcements": "^0.6.5",
    "@procore-oss/backstage-plugin-announcements-backend": "^0.6.4",
    "@types/cookie-parser": "^1.4.7",
    "app": "link:../app",
    "better-sqlite3": "^8.0.0",
    "cookie-parser": "^1.4.6",
    "dockerode": "^3.3.1",
    "express": "^4.17.1",
    "express-prom-bundle": "^7.0.0",
    "express-promise-router": "^4.1.0",
    "lz-string": "^1.5.0",
    "pg": "^8.11.3",
    "prom-client": "^15.0.0",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "@backstage/cli": "^0.26.1",
    "@types/cookie-parser": "^1.4.7",
    "@types/dockerode": "^3.3.0",
    "@types/express": "^4.17.6",
    "@types/express-serve-static-core": "^4.17.5",
    "@types/luxon": "^2.0.4"
  },
  "files": [
    "dist"
  ]
}
```

**Comment by camilaibs** [comment]
Hi @kunchalavikram1427, the latest error you posted seems unrelated, could you please create a separate issue so we can look at it separately 🙂 ?

**Comment by jcreek** [comment]
I've just had this exact issue on a completely fresh install. Here's my package.json:

```json
{
  "name": "root",
  "version": "1.0.0",
  "private": true,
  "engines": {
    "node": "18 || 20"
  },
  "scripts": {
    "dev": "yarn workspaces foreach -A --include backend --include app --parallel -v -i run start",
    "start": "yarn workspace app start",
    "start-backend": "yarn workspace backend start",
    "build:backend": "yarn workspace backend build",
    "build:all": "backstage-cli repo build --all",
    "build-image": "yarn workspace backend build-image",
    "tsc": "tsc",
    "tsc:full": "tsc --skipLibCheck false --incremental false",
    "clean": "backstage-cli repo clean",
    "test": "backstage-cli repo test",
    "test:all": "backstage-cli repo test --coverage",
    "test:e2e": "playwright test",
    "fix": "backstage-cli repo fix",
    "lint": "backstage-cli repo lint --since origin/master",
    "lint:all": "backstage-cli repo lint",
    "prettier:check": "prettier --check .",
    "new": "backstage-cli new --scope internal"
  },
  "workspaces": {
    "packages": [
      "packages/*",
      "plugins/*"
    ]
  },
  "devDependencies": {
    "@backstage/cli": "^0.27.1",
    "@backstage/e2e-test-utils": "^0.1.1",
    "@playwright/test": "^1.32.3",
    "@spotify/prettier-config": "^12.0.0",
    "node-gyp": "^10.0.0",
    "prettier": "^2.3.2",
    "typescript": "~5.4.0"
  },
  "resolutions": {
    "@types/react": "^18",
    "@types/react-dom": "^18"
  },
  "prettier": "@spotify/prettier-config",
  "lint-staged": {
    "*.{js,jsx,ts,tsx,mjs,cjs}": [
      "eslint --fix",
      "prettier --write"
    ],
    "*.{json,md}": [
      "prettier --write"
    ]
  },
  "packageManager": "yarn@4.4.1"
}
```

Here's the error message: 

```
node_modules\@backstage\backend-app-api\src\wiring\BackendInitializer.ts:333
[backend]:             throw new ForwardedError(
[backend]:                   ^
[backend]: 
[backend]: 
[backend]: ForwardedError: Plugin 'app' startup failed; caused by Error: Cannot find module 'app/package.json'
[backend]: Require stack:
```

**Comment by tkf144** [comment]
Still a problem having followed the Getting Started guide. Used @jcreek's workaround above.
