### ISSUE TITLE
🐛 Bug Report: Event based processing of github teams creation not working as expected 

### ISSUE THREAD

**Issue by vanessap-aa** [backstage/backstage#26109]
### 📜 Description

We have set up events triggers for the creation of github teams. This adds the github team created to the catalog as a groups entity. We do this via webhook method using the github events backend module. 

We noticed that when github calls our webhook, the entity correctly begins to process the newly added group. 
```
debug Processing group:default/vanessa5
```

As the process continued, and after deep levels of debugging, we found that processing the group entity fails with the following error:

```
InputError: Processor BuiltinKindsEntityProcessor threw an error while validating the entity group:default/vanessa6; caused by TypeError: /spec/parent must NOT have fewer than 1 characters - limit: 1\n    at <anonymous> (/Users/aa217928/Documents/Projects/runway/node_modules/@backstage/plugin-catalog-backend/src/processing/DefaultCatalogProcessingOrchestrator.ts:321:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

We noticed that the "unprocessedEntity" has the following spec. There are several issues with this spec. Aside from the parent key, which is causing an error, there are no members tied to this github team. The information at this glance is incorrect. Could be the default values.

```
{
    type: "team",
    profile: {
      displayName: "vanessa6",
    },
    children: [
    ],
    parent: "",
    members: [
    ],
  }
```

We noticed that the error eventually clears, the spec corrects itself, but it takes about an hour, which I am unsure if this is due to our `GithubOrgEntityProcessor` scheduler (which runs hourly).

### 👍 Expected behavior

The expected behavior, would be that once the event for creating a github team is triggered, the github team is "immediately" added to the catalog as a group entity, without failing.

### 👎 Actual Behavior with Screenshots

Notice the time gap. The group was finally added at 16:34.

```
Aug 20 15:47:43 debug Processing group:default/vanessa6
Aug 20 15:47:43 debug Event received: topic=experimental.catalog.errors, metadata=undefined, payload={"entity":"group:default/vanessa6","location":"url:https://github.com/orgs/AAInternal/teams/vanessa6","errors":[{"cause":{},"name":"InputError"}]}
Aug 20 15:47:43 debug Stitching group:default/vanessa6
Aug 20 15:47:43 debug Unable to stitch group:default/vanessa6, the entity has not yet been processed
Aug 20 15:49:57 debug Processing group:default/vanessa6
.
.
.

Aug 20 16:34:33 debug Event received: topic=experimental.catalog.errors, metadata=undefined, payload={"entity":"group:default/vanessa6","location":"url:https://github.com/orgs/AAInternal/teams/vanessa6","errors":[{"cause":{},"name":"InputError"}]}
Aug 20 16:34:53 debug Stitching group:default/vanessa6
Aug 20 16:34:53 debug Unable to stitch group:default/vanessa6, the entity has not yet been processed
Aug 20 16:34:54 debug Processing group:default/vanessa6
Aug 20 16:34:54 debug Stitching group:default/vanessa6
```

The error here is not being shown. My team will attempt to submit a contribution to make these errors visible. 

The Error:

```
{
    cause: {},
    name: "InputError",
}
  
"InputError: Processor BuiltinKindsEntityProcessor threw an error while validating the entity group:default/vanessa6; caused by TypeError: /spec/parent must NOT have fewer than 1 characters - limit: 1\n    at <anonymous> (/Users/aa217928/Documents/Projects/runway/node_modules/@backstage/plugin-catalog-backend/src/processing/DefaultCatalogProcessingOrchestrator.ts:321:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
```

### 👟 Reproduction steps

Create a webhook using the github events module in tandem with the GithubOrgEntityProcessor. Create a github team that would then call the webhook. You should notice this behaviour, however, you will need to enable a lower level of logging (debug).

### 🖥️ Your Environment

```
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.18.0
yarn: 4.3.1
cli:  0.26.11 (installed)
backstage:  1.28.4

Dependencies:
  @backstage/app-defaults                                          1.5.8
  @backstage/backend-app-api                                       0.5.14, 0.7.9, 0.8.0
  @backstage/backend-common                                        0.19.10, 0.20.2, 0.21.7, 0.22.0, 0.23.3
  @backstage/backend-defaults                                      0.3.3, 0.4.0
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.15
  @backstage/backend-plugin-api                                    0.6.21, 0.7.0
  @backstage/backend-tasks                                         0.5.27
  @backstage/backend-test-utils                                    0.3.8, 0.4.4
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.26.11
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.0
  @backstage/core-compat-api                                       0.2.7
  @backstage/core-components                                       0.13.10, 0.14.9
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.35
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.29
  @backstage/integration                                           1.13.0
  @backstage/plugin-api-docs                                       0.11.7
  @backstage/plugin-app-backend                                    0.3.71
  @backstage/plugin-app-node                                       0.1.22
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.14
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.5
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.5
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.17
  @backstage/plugin-auth-backend-module-github-provider            0.1.19
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.19
  @backstage/plugin-auth-backend-module-google-provider            0.1.19
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.17
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.15
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.15
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.3
  @backstage/plugin-auth-backend                                   0.22.9
  @backstage/plugin-auth-node                                      0.4.17
  @backstage/plugin-auth-react                                     0.1.4
  @backstage/plugin-bitbucket-cloud-common                         0.2.21
  @backstage/plugin-catalog-backend-module-github                  0.6.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.20
  @backstage/plugin-catalog-backend                                1.24.0
  @backstage/plugin-catalog-common                                 1.0.25
  @backstage/plugin-catalog-graph                                  0.4.7
  @backstage/plugin-catalog-import                                 0.12.1
  @backstage/plugin-catalog-node                                   1.12.4
  @backstage/plugin-catalog-react                                  1.12.2
  @backstage/plugin-catalog                                        1.21.1
  @backstage/plugin-events-backend-module-github                   0.2.8
  @backstage/plugin-events-backend                                 0.3.9
  @backstage/plugin-events-node                                    0.3.8
  @backstage/plugin-home-react                                     0.1.15
  @backstage/plugin-home                                           0.7.7
  @backstage/plugin-kubernetes-backend                             0.18.3
  @backstage/plugin-kubernetes-common                              0.8.1
  @backstage/plugin-kubernetes-node                                0.1.16
  @backstage/plugin-kubernetes-react                               0.4.1
  @backstage/plugin-kubernetes                                     0.11.12
  @backstage/plugin-org                                            0.6.27
  @backstage/plugin-permission-backend                             0.5.46
  @backstage/plugin-permission-common                              0.7.14, 0.8.0
  @backstage/plugin-permission-node                                0.7.32, 0.8.0
  @backstage/plugin-permission-react                               0.4.24
  @backstage/plugin-proxy-backend                                  0.5.3
  @backstage/plugin-scaffolder-backend-module-azure                0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.12
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.14
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.12
  @backstage/plugin-scaffolder-backend-module-github               0.4.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.4
  @backstage/plugin-scaffolder-backend                             1.23.0
  @backstage/plugin-scaffolder-common                              1.5.4
  @backstage/plugin-scaffolder-node-test-utils                     0.1.9
  @backstage/plugin-scaffolder-node                                0.4.8
  @backstage/plugin-scaffolder-react                               1.10.0
  @backstage/plugin-scaffolder                                     1.23.0
  @backstage/plugin-search-backend-module-catalog                  0.1.28
  @backstage/plugin-search-backend-module-elasticsearch            1.5.3
  @backstage/plugin-search-backend-module-pg                       0.5.32
  @backstage/plugin-search-backend-module-techdocs                 0.1.27
  @backstage/plugin-search-backend-node                            1.2.27
  @backstage/plugin-search-backend                                 1.5.14
  @backstage/plugin-search-common                                  1.2.13
  @backstage/plugin-search-react                                   1.7.13
  @backstage/plugin-search                                         1.4.14
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.9
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.12
  @backstage/plugin-techdocs-node                                  1.12.8
  @backstage/plugin-techdocs-react                                 1.2.6
  @backstage/plugin-techdocs                                       1.10.7
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.9
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.8
  @backstage/theme                                                 0.4.4, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Hi! I believe this might be related to https://github.com/backstage/backstage/pull/26016 which was released recently.

**Comment by vanessap-aa** [comment]
> #26016

Not sure if this is the fix. Looking at the PR it looks like it is related to repository events. Not github org team events.

**Comment by freben** [comment]
@pjungermann could it be something related?

**Comment by pjungermann** [comment]
There is no event support for the creation of teams, yet.

I'm not aware of any event-based capabilities at the github org entity provider. 🤔

**Comment by vanessap-aa** [comment]
@pjungermann  https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/providers/GithubOrgEntityProvider.ts#L302

**Comment by vanessap-aa** [comment]
@pjungermann and @freben May you please help?

**Comment by Rugvip** [comment]
Gonna ping @angeliski as the original contributor through https://github.com/backstage/backstage/pull/14870

We'll leave this one open to community contributions though, happy for any help we can get 🙏

**Comment by vanessap-aa** [comment]
Thank you

**Comment by angeliski** [comment]
Hey @vanessap-aa,

I was digging a little, and the parent could be the problem (we send an empty parent [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/providers/GithubOrgEntityProvider.ts#L514), so this key should not be defined [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/lib/defaultTransformers.ts#L125)). The members are not an issue because GitHub sends separate events for that (as you can see below). Could you try creating a team with a parent to see if we get the same error? I will try to write a unit test to catch this behavior.


![image](https://github.com/user-attachments/assets/2ce010be-85d4-41fd-8b20-aa2abc1e62cb)

**Comment by angeliski** [comment]
@vanessap-aa Parent is really the problem, the #27192 should fix the problem :)

**Comment by vanessap-aa** [comment]
Thank you @angeliski <3
