### ISSUE TITLE
🐛 Bug Report: ForwardedError: Plugin 'auth' startup failed; caused by Error: Failed to initialize github auth provider, Sign-in resolver 'usernameMatchingUserEntityName' is not available

### ISSUE THREAD

**Issue by ryan-WORK** [backstage/backstage#26226]
### 📜 Description

After upgrading to 1.30.3  from 1.29.1 I ran locally and it worked then creating a docker image the backend won't start up and you will receive the following error (`yarn dev` seems to work perfectly ):

```
backstage  | /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:677
backstage  |             throw new errors.ForwardedError(
backstage  |                   ^
backstage  |
backstage  | ForwardedError: Plugin 'auth' startup failed; caused by Error: Failed to initialize github auth provider, Sign-in resolver 'usernameMatchingUserEntityName' is not available
backstage  |     at /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:677:19
backstage  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
backstage  |     at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:676:11
backstage  |     ... 3 lines matching cause stack trace ...
backstage  |     at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:832:5) {
backstage  |   cause: Error: Failed to initialize github auth provider, Sign-in resolver 'usernameMatchingUserEntityName' is not available
backstage  |       at bindProviderRouters (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:1544:17)
backstage  |       at createRouter (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:2267:3)
backstage  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
backstage  |       at async Object.init [as func] (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:2335:24)
backstage  |       at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:676:11
backstage  |       at async Promise.all (index 3)
backstage  |       at async #doStart (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:630:5)
backstage  |       at async BackendInitializer.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:556:5)
backstage  |       at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:832:5)
backstage  | }
backstage  |
backstage  | Node.js v20.17.0
```

### 👍 Expected behavior

No change were needed when ran in container.

### 👎 Actual Behavior with Screenshots

The backend fails to start with this error:

ForwardedError: Plugin 'auth' startup failed; caused by Error: Failed to initialize github auth provider, Sign-in resolver 'usernameMatchingUserEntityName' is not available

### 👟 Reproduction steps

```
# app-config.yaml
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${IDP_GITHUB_APP_CLIENT_ID}
        clientSecret: ${IDP_GITHUB_APP_CLIENT_SECRET}
        enterpriseInstanceUrl: ${GITHUB_ENTERPRISE_URL}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
    okta:
      development:
...
```

```
// packages/backend/src/index.ts
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(import('@backstage/plugin-auth-backend-module-github-provider'));
```

### 📃 Provide the context for the Bug.

1. Create a new instance: `npx @backstage/create-app@latest ` or in our case upgrade from 1.29.1 to 1.30.3
2. add the configuration above
3. Run yarn dev (this works)
4. Build and image and `docker run -it -p 7007:7007 backstage` (fails)

### 🖥️ Your Environment

```
OS:   Darwin 23.6.0 - darwin/x64
node: v20.11.1
yarn: 4.1.0
cli:  0.27.0 (installed)
backstage:  1.30.3

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.9.2
  @backstage/backend-common                                        0.23.3, 0.24.0
  @backstage/backend-defaults                                      0.4.3
  @backstage/backend-dev-utils                                     0.1.4, 0.1.5
  @backstage/backend-openapi-utils                                 0.1.16
  @backstage/backend-plugin-api                                    0.7.0, 0.8.0
  @backstage/backend-tasks                                         0.6.0
  @backstage/catalog-client                                        1.6.5, 1.6.6
  @backstage/catalog-model                                         1.4.5, 1.5.0, 1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.8.1, 1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.4, 0.2.7, 0.2.8
  @backstage/core-components                                       0.14.10, 0.14.4, 0.14.9
  @backstage/core-plugin-api                                       1.9.2, 1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.4, 0.6.7, 0.7.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26, 1.1.29, 1.1.30
  @backstage/integration                                           1.10.0, 1.13.0, 1.14.0
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.72
  @backstage/plugin-app-node                                       0.1.23
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.16
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.6
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.6
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.18
  @backstage/plugin-auth-backend-module-github-provider            0.1.20
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.20
  @backstage/plugin-auth-backend-module-google-provider            0.1.20
  @backstage/plugin-auth-backend-module-guest-provider             0.1.9
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.18
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.4
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.16
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.5
  @backstage/plugin-auth-backend-module-okta-provider              0.0.16
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.4
  @backstage/plugin-auth-backend                                   0.22.11
  @backstage/plugin-auth-node                                      0.4.17, 0.5.0
  @backstage/plugin-auth-react                                     0.1.5
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-github-org              0.2.1
  @backstage/plugin-catalog-backend-module-github                  0.7.1
  @backstage/plugin-catalog-backend-module-ldap                    0.8.0
  @backstage/plugin-catalog-backend-module-logs                    0.0.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.21
  @backstage/plugin-catalog-backend                                1.25.1
  @backstage/plugin-catalog-common                                 1.0.22, 1.0.25, 1.0.26
  @backstage/plugin-catalog-graph                                  0.4.8
  @backstage/plugin-catalog-import                                 0.12.2
  @backstage/plugin-catalog-node                                   1.12.5
  @backstage/plugin-catalog-react                                  1.11.3, 1.12.2, 1.12.3
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-events-node                                    0.3.9
  @backstage/plugin-kubernetes-backend                             0.18.4
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-kubernetes-node                                0.1.17
  @backstage/plugin-kubernetes-react                               0.4.2
  @backstage/plugin-kubernetes                                     0.11.13
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.20
  @backstage/plugin-permission-backend                             0.5.47
  @backstage/plugin-permission-common                              0.7.13, 0.8.0, 0.8.1
  @backstage/plugin-permission-node                                0.8.0, 0.8.1
  @backstage/plugin-permission-react                               0.4.22, 0.4.24, 0.4.25
  @backstage/plugin-proxy-backend                                  0.5.4
  @backstage/plugin-scaffolder-backend-module-azure                0.1.15
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.13
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.15
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.13
  @backstage/plugin-scaffolder-backend-module-github               0.4.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.5
  @backstage/plugin-scaffolder-backend                             1.24.0
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node                                0.4.9
  @backstage/plugin-scaffolder-react                               1.11.0
  @backstage/plugin-scaffolder                                     1.24.0
  @backstage/plugin-search-backend-module-catalog                  0.2.0
  @backstage/plugin-search-backend-module-pg                       0.5.33
  @backstage/plugin-search-backend-module-techdocs                 0.2.0
  @backstage/plugin-search-backend-node                            1.3.0
  @backstage/plugin-search-backend                                 1.5.15
  @backstage/plugin-search-common                                  1.2.11, 1.2.13, 1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.11
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.13
  @backstage/plugin-techdocs-node                                  1.12.9
  @backstage/plugin-techdocs-react                                 1.2.7
  @backstage/plugin-techdocs                                       1.10.8
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.5.3, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by freben** [comment]
Hm I don't think I'm able to reproduce this at least with the latest version of the code. Seems to work both locally and after being docker built.
