### ISSUE TITLE
🐛 Bug Report: Error: Failed to instantiate service 'core.urlReader' for 'techdocs' because the following dependent services are missing: 'core.urlReader.factories'

### ISSUE THREAD

**Issue by darrenyung** [backstage/backstage#26229]
### 📜 Description

Error during startup after upgrading to 1.29.2 and the same after going to 1.30.3 when running `yarn dev`

### 👍 Expected behavior

Application starts up fine

### 👎 Actual Behavior with Screenshots

```
[1] /Users/yungc/Documents/Projects/backstage/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:151
[1]       throw new Error(
[1]             ^
[1]
[1]
[1] Error: Failed to instantiate service 'core.urlReader' for 'techdocs' because the following dependent services are missing: 'core.urlReader.factories'
[1]     at ServiceRegistry.#checkForMissingDeps (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:151:13)
[1]     at <anonymous> (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:248:14)
[1]     at async BackendInitializer.#getInitDeps (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:74:22)
[1]     at async <anonymous> (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:286:30)
[1]     at async Promise.all (index 4)
[1]     at async BackendInitializer.#doStart (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:236:5)
[1]     at async BackendInitializer.start (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:150:5)
[1]     at async BackstageBackend.start (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:42:11)
```

### 👟 Reproduction steps

1. After upgrading, delete yarn lock file.
2. Re-install dependency packages
3. Run `yarn dev`
4. Observe error output log

### 📃 Provide the context for the Bug.

Trying to run upgrade and perform regressions test successfully so the application is running with the latest version.

### 🖥️ Your Environment

```
OS:   Darwin 23.6.0 - darwin/arm64
node: v20.17.0
yarn: 1.22.22
cli:  0.27.0 (installed)
backstage:  1.30.3

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.8.0
  @backstage/backend-common                                        0.23.3, 0.24.0
  @backstage/backend-defaults                                      0.4.3
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.16
  @backstage/backend-plugin-api                                    0.7.0, 0.8.0
  @backstage/backend-tasks                                         0.5.27, 0.6.0
  @backstage/backend-test-utils                                    0.5.0
  @backstage/catalog-client                                        1.6.6
  @backstage/catalog-model                                         1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.8
  @backstage/core-components                                       0.11.2, 0.14.10
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.37
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-app-api                                      0.8.0
  @backstage/frontend-plugin-api                                   0.6.7, 0.7.0
  @backstage/frontend-test-utils                                   0.1.12
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.72
  @backstage/plugin-app-node                                       0.1.23
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.16
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.6
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.6
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.18
  @backstage/plugin-auth-backend-module-github-provider            0.1.20
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.20
  @backstage/plugin-auth-backend-module-google-provider            0.1.20
  @backstage/plugin-auth-backend-module-guest-provider             0.1.9
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.18
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.4
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.16
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.5
  @backstage/plugin-auth-backend-module-okta-provider              0.0.16
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.4
  @backstage/plugin-auth-backend                                   0.22.11
  @backstage/plugin-auth-node                                      0.4.17, 0.5.0
  @backstage/plugin-auth-react                                     0.1.5
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-github-org              0.2.1
  @backstage/plugin-catalog-backend-module-github                  0.7.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.21
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.10
  @backstage/plugin-catalog-backend                                1.25.1
  @backstage/plugin-catalog-common                                 1.0.26
  @backstage/plugin-catalog-graph                                  0.4.8
  @backstage/plugin-catalog-import                                 0.12.2
  @backstage/plugin-catalog-node                                   1.12.5
  @backstage/plugin-catalog-react                                  1.12.3
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.4
  @backstage/plugin-catalog-unprocessed-entities                   0.2.7
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-devtools-backend                               0.3.9
  @backstage/plugin-devtools-common                                0.1.12
  @backstage/plugin-devtools                                       0.1.17
  @backstage/plugin-events-node                                    0.3.9
  @backstage/plugin-home-react                                     0.1.16
  @backstage/plugin-home                                           0.7.9
  @backstage/plugin-kubernetes-backend                             0.18.4
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-kubernetes-node                                0.1.17
  @backstage/plugin-kubernetes-react                               0.4.2
  @backstage/plugin-kubernetes                                     0.11.13
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend                             0.5.47
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.1
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.4
  @backstage/plugin-scaffolder-backend-module-azure                0.1.15
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.13
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.15
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.13
  @backstage/plugin-scaffolder-backend-module-github               0.4.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.5
  @backstage/plugin-scaffolder-backend                             1.24.0
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node                                0.4.9
  @backstage/plugin-scaffolder-react                               1.11.0
  @backstage/plugin-scaffolder                                     1.24.0
  @backstage/plugin-search-backend-module-catalog                  0.2.0
  @backstage/plugin-search-backend-module-elasticsearch            1.5.4
  @backstage/plugin-search-backend-module-pg                       0.5.33
  @backstage/plugin-search-backend-module-techdocs                 0.2.0
  @backstage/plugin-search-backend-node                            1.3.0
  @backstage/plugin-search-backend                                 1.5.15
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-addons-test-utils                     1.0.37
  @backstage/plugin-techdocs-backend                               1.10.11
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.13
  @backstage/plugin-techdocs-node                                  1.12.9
  @backstage/plugin-techdocs-react                                 1.2.7
  @backstage/plugin-techdocs                                       1.10.8
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.2.19, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 1.18s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
So if you do NOT delete the lockfile, this does not happen?

In general we strongly discourage outright deleting the lockfile because it can have unexpected side effects. Were you trying to address something in particular?

**Comment by freben** [comment]
I'll say also, that `@backstage/backend-app-api` is on 0.9.2 in the latest release, not 0.8.0.

**Comment by darrenyung** [comment]
> So if you do NOT delete the lockfile, this does not happen?
> 
> In general we strongly discourage outright deleting the lockfile because it can have unexpected side effects. Were you trying to address something in particular?

Thanks. It has happened before in the past when we kept the lock file and upgraded as normal, we didn't receive any upgrades from some packages most noticeably, the UI enhancements of the 2nd version of Scaffolder until we regenerated the lock file. Since then, it has become a habit for every time either myself or other devs that does an upgrade, we ensure that the lock files are regenerated.

> I'll say also, that `@backstage/backend-app-api` is on 0.9.2 in the latest release, not 0.8.0.

Will take a look, strange that the upgrade didn't pick these up
