### ISSUE TITLE
🐛 Bug Report: 401 Unauthorized after switching from sqlite to postgres

### ISSUE THREAD

**Issue by KiqoCode** [backstage/backstage#26526]
### 📜 Description

We have just started setting up a test environment for backstage, currently only running on localhost.
Managed to setup authentication with Azure and also Catalog sync with Microsoft Graph, and authentication was working fine while using in-memory sqlite, but then we switched to a postgres, also running locally.
I can see all the schemas, catalogs etc are populated in postgres, I can login to backstage, but instantly get 401 on start page ( Did not happend when using sqlite). 

### 👍 Expected behavior

Getting a correct authorize response and possible to see entities. 

### 👎 Actual Behavior with Screenshots

Looking at "Network Tracing" in the browser, I see a response from http://localhost:7007/api/permission/authorize:

```
{
    "error": {
        "name": "AuthenticationError",
        "message": "Invalid token; caused by JWKSNoMatchingKey: no applicable key found in the JSON Web Key Set",
        "cause": {
            "code": "ERR_JWKS_NO_MATCHING_KEY",
            "name": "JWKSNoMatchingKey",
            "message": "no applicable key found in the JSON Web Key Set",
            "stack": "JWKSNoMatchingKey: no applicable key found in the JSON Web Key Set\n    at LocalJWKSet.getKey (/Users/local-user/Stash/3idp/node_modules/jose/dist/node/cjs/jwks/local.js:84:19)\n    at RemoteJWKSet.localJWKSet [as _local] (/Users/local-user/Stash/3idp/node_modules/jose/dist/node/cjs/jwks/local.js:115:63)\n    at RemoteJWKSet.getKey (/Users/local-user/Stash/3idp/node_modules/jose/dist/node/cjs/jwks/remote.js:79:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async flattenedVerify (/Users/local-user/Stash/3idp/node_modules/jose/dist/node/cjs/jws/flattened/verify.js:75:15)\n    at async compactVerify (/Users/local-user/Stash/3idp/node_modules/jose/dist/node/cjs/jws/compact/verify.js:18:22)\n    at async Object.jwtVerify (/Users/local-user/Stash/3idp/node_modules/jose/dist/node/cjs/jwt/verify.js:8:22)\n    at async UserTokenHandler.verifyToken (/Users/local-user/Stash/3idp/node_modules/@backstage/backend-defaults/src/entrypoints/auth/user/UserTokenHandler.ts:55:25)\n    at async DefaultAuthService.authenticate (/Users/local-user/Stash/3idp/node_modules/@backstage/backend-defaults/src/entrypoints/auth/DefaultAuthService.ts:80:24)\n    at async DefaultHttpAuthService.#extractCredentialsFromRequest (/Users/local-user/Stash/3idp/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:95:12)\n    at async DefaultHttpAuthService.credentials (/Users/local-user/Stash/3idp/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:138:9)"
        },
        "stack": "AuthenticationError: Invalid token; caused by JWKSNoMatchingKey: no applicable key found in the JSON Web Key Set\n    at <anonymous> (/Users/local-user/Stash/3idp/node_modules/@backstage/backend-defaults/src/entrypoints/auth/user/UserTokenHandler.ts:60:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserTokenHandler.verifyToken (/Users/local-user/Stash/3idp/node_modules/@backstage/backend-defaults/src/entrypoints/auth/user/UserTokenHandler.ts:55:25)\n    at async DefaultAuthService.authenticate (/Users/local-user/Stash/3idp/node_modules/@backstage/backend-defaults/src/entrypoints/auth/DefaultAuthService.ts:80:24)\n    at async DefaultHttpAuthService.#extractCredentialsFromRequest (/Users/local-user/Stash/3idp/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:95:12)\n    at async DefaultHttpAuthService.credentials (/Users/local-user/Stash/3idp/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:138:9)"
    },
    "request": {
        "method": "POST",
        "url": "/api/permission/authorize"
    },
    "response": {
        "statusCode": 401
    }
}
```

### 👟 Reproduction steps

- Setup a backstage project
- Setup azure authentication
- Setup a local postgres database
- 401 Errors

### 📃 Provide the context for the Bug.

Trying to setup a basic backstage environment as a demo / starting point for our org. 

### 🖥️ Your Environment

```
yarn run v1.22.22
$ /Users/local-user/Stash/3idp/node_modules/.bin/backstage-cli info
OS:   Darwin 23.6.0 - darwin/arm64
node: v20.17.0
yarn: 1.22.22
cli:  0.27.0 (installed)
backstage:  1.30.4

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.9.3
  @backstage/backend-common                                        0.24.1
  @backstage/backend-defaults                                      0.4.4
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.17
  @backstage/backend-plugin-api                                    0.8.1
  @backstage/backend-tasks                                         0.6.1
  @backstage/catalog-client                                        1.6.6
  @backstage/catalog-model                                         1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.8
  @backstage/core-components                                       0.14.10
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.7.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.73
  @backstage/plugin-app-node                                       0.1.24
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.17
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.7
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.7
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.19
  @backstage/plugin-auth-backend-module-github-provider            0.1.21
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.21
  @backstage/plugin-auth-backend-module-google-provider            0.1.21
  @backstage/plugin-auth-backend-module-guest-provider             0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.19
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.17
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.6
  @backstage/plugin-auth-backend-module-okta-provider              0.0.17
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.5
  @backstage/plugin-auth-backend                                   0.22.12
  @backstage/plugin-auth-node                                      0.5.1
  @backstage/plugin-auth-react                                     0.1.5
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-logs                    0.0.4
  @backstage/plugin-catalog-backend-module-msgraph                 0.6.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.22
  @backstage/plugin-catalog-backend                                1.25.2
  @backstage/plugin-catalog-common                                 1.0.26
  @backstage/plugin-catalog-graph                                  0.4.8
  @backstage/plugin-catalog-import                                 0.12.2
  @backstage/plugin-catalog-node                                   1.12.6
  @backstage/plugin-catalog-react                                  1.12.3
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-events-node                                    0.3.10
  @backstage/plugin-kubernetes-backend                             0.18.5
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-kubernetes-node                                0.1.18
  @backstage/plugin-kubernetes-react                               0.4.2
  @backstage/plugin-kubernetes                                     0.11.13
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.21
  @backstage/plugin-permission-backend                             0.5.48
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.2
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.5
  @backstage/plugin-scaffolder-backend-module-azure                0.1.16
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.14
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.16
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.14
  @backstage/plugin-scaffolder-backend-module-github               0.4.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.6
  @backstage/plugin-scaffolder-backend                             1.24.1
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node                                0.4.10
  @backstage/plugin-scaffolder-react                               1.11.0
  @backstage/plugin-scaffolder                                     1.24.0
  @backstage/plugin-search-backend-module-catalog                  0.2.1
  @backstage/plugin-search-backend-module-pg                       0.5.34
  @backstage/plugin-search-backend-module-techdocs                 0.2.1
  @backstage/plugin-search-backend-node                            1.3.1
  @backstage/plugin-search-backend                                 1.5.16
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.12
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.13
  @backstage/plugin-techdocs-node                                  1.12.10
  @backstage/plugin-techdocs-react                                 1.2.7
  @backstage/plugin-techdocs                                       1.10.8
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 0.84s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by KiqoCode** [comment]
Seems that there are no signing keys in the database, could maybe be a reason for the error.
But isn't signing keys supposed to be generated automatically?

**Comment by KiqoCode** [comment]
Setting database for auth plugin to memory but using postgres for the rest also works without issues. But auth plugin does not seem to handle postgres with signing keys currently..
```
  database:
    client: pg
    connection:
      host: localhost
      port: 5432
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    prefix: 'idp_'
    plugin:
      auth:
        client: better-sqlite3
        connection: ':memory:'
```

Any ideas?

**Comment by jhaals** [comment]
Hi! Sorry to hear that you're having issues. And just to verify, you are you experiencing the same with fresh browser state? Changing the the database without a full reload is going to result in errors. Please let us know if that works or not as it's not obvious to spot something that could cause this. Would be great with a repository so that we can reproduce this for troubleshooting.

**Comment by KiqoCode** [comment]
I have no idea why.. But I added guest provider, then it started working, removed guest provider and changed back to microsoft, and it's still working now.. I can see new signing keys being created.. I have no idea why it suddenly is working.. But happy anyway 😃  Thanks for your time!

**Comment by Rugvip** [comment]
@KiqoCode alright thank you for the update! 👍 

Gonna close this, but let us know if you run into any other issues! 🙏
