### ISSUE TITLE
🐛 Bug Report: HttpError fetch failed with Github Enterprise integration and discovery after multistage docker build guide

### ISSUE THREAD

**Issue by pF-luis** [backstage/backstage#26686]
### 📜 Description

So i've setup a completely new backstage app using the npx command. After that I've configurated the github integration for our github enterprise instance. The last step was setting the catalog github provider config to the github enterprise integration.If I run this in dev mode(referring to "yarn dev" in my local terminal) on my machine, every thing works completely fine.

As soon as I do the multi-staged build locally from the webpage(https://backstage.io/docs/deployment/docker/#multi-stage-build) and then run the resulting container locally, I get the following error

```
2024-09-15T15:48:06.549Z catalog error github-provider:test refresh failed, HttpError: fetch failed fetch failed target=github-provider:test class=GithubEntityProvider taskId=github-provider:test:refresh taskInstanceId=00414045-eb69-415a-bf39-61c8ac3bb2a8 name=HttpError status=500 request=[object Object] stack=HttpError: fetch failed                                     
    at /app/node_modules/@octokit/request/dist-node/index.js:146:11                                                                                                                       
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                         
    at async queryWithPaging (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-BoslYJTt.cjs.js:606:22)                                     
    at async getOrganizationRepositories (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-BoslYJTt.cjs.js:523:24)                         
    at async GithubEntityProvider.findCatalogFiles (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-BoslYJTt.cjs.js:843:54)               
    at async GithubEntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-BoslYJTt.cjs.js:815:21)                        
    at async fn (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-BoslYJTt.cjs.js:800:13)                                                  
    at async TaskWorker.fn (/app/node_modules/@backstage/backend-defaults/dist/scheduler.cjs.js:568:9)                                                                                    
    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-defaults/dist/scheduler.cjs.js:317:7)                                                                               
    at async /app/node_modules/@backstage/backend-defaults/dist/scheduler.cjs.js:265:31
```
  
Sadly, at least to me, this error does not really tell me what to look for or what to test, as it's missing a "why" did the fetch fail.

Using a github.com integration locally alongside the enterprise integration will make the catalog discovery work for github.com just as expected while the enterprise integration won't function just as before(all within the built container).

### 👍 Expected behavior

The enterprise integration should work as the github.com integration,especially after the docker build

### 👎 Actual Behavior with Screenshots

Well, there are only logs, I'll add them below

### 👟 Reproduction steps

* setup new backstage app
* add settings for github enterprise integration and use said integration for the catalog provider 
* run yarn dev and check that the enterprise integration works locally
* build the docker image locally using the multi-staged build method mentioned here: [#multi-stage-build](https://backstage.io/docs/deployment/docker/#multi-stage-build)
* run the resulting container locally using the same app-config.yaml as for the local "yarn dev"
* GHE will no longer work

### 📃 Provide the context for the Bug.

- [This is how the image was build locally](#this-is-how-the-image-was-build-locally)
- [This is how the image was run as a container locally](#this-is-how-the-image-was-run-as-a-container-locally)
- [contents of the app-config.yaml](#contents-of-the-app-configyaml)
- [Dockerfile used:](#dockerfile-used)
- [logs of "yarn dev" (working just fine):](#logs-of-yarn-dev-working-just-fine)
- [logs from the docker container(not working):](#logs-from-the-docker-containernot-working)

### This is how the image was build locally 
`docker image build --no-cache -t atlas:dev -f Dockerfile.deployment .`
### This is how the image was run as a container locally 
`docker run -it --rm -v $(pwd)/app-config.yaml:/app/app-config.yaml -e NODE_ENV=development -e LOG_LEVEL=debug atlas:dev`
### contents of the app-config.yaml
```yaml
app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: better-sqlite3
    connection: ':memory:'
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      token: ***
    - host: myhost.acme.intern
      apiBaseUrl: https://myhost.acme.intern/api/v3
      token: ***

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    guest: {}

catalog:
  processingInterval: { seconds: 5 }
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Group, Team]
  providers:
    github:
      test:
        host: myhost.acme.intern
        organization: test
        catalogPath: 'organisation/teams/teams.yaml' # string
        filters:
          repository: 'atlas-data' # Regex
        schedule:
          frequency: PT30M
          timeout: PT3M

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

```
### Dockerfile used:
```dockerfile
# Stage 1 - Create yarn install skeleton layer
FROM node:18-bookworm-slim AS packages

WORKDIR /app
COPY package.json yarn.lock ./

COPY packages packages

# Comment this out if you don't have any internal plugins
#COPY plugins plugins

RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -exec rm -rf {} \+

# Stage 2 - Install dependencies and build packages
FROM node:18-bookworm-slim AS build

# Install isolate-vm dependencies, these are needed by the @backstage/plugin-scaffolder-backend.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends python3 g++ build-essential && \
    yarn config set python /usr/bin/python3

# Install sqlite3 dependencies. You can skip this if you don't use sqlite3 in the image,
# in which case you should also move better-sqlite3 to "devDependencies" in package.json.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev

USER node
WORKDIR /app

COPY --from=packages --chown=node:node /app .

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --network-timeout 600000

COPY --chown=node:node . .

RUN ls -lah && ls -lah packages/ && yarn tsc
RUN yarn --cwd packages/backend build
# If you have not yet migrated to package roles, use the following command instead:
# RUN yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies

RUN mkdir packages/backend/dist/skeleton packages/backend/dist/bundle \
    && tar xzf packages/backend/dist/skeleton.tar.gz -C packages/backend/dist/skeleton \
    && tar xzf packages/backend/dist/bundle.tar.gz -C packages/backend/dist/bundle

# Stage 3 - Build the actual backend image and install production dependencies
FROM node:18-bookworm-slim

# Install isolate-vm dependencies, these are needed by the @backstage/plugin-scaffolder-backend.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends python3 g++ build-essential && \
    yarn config set python /usr/bin/python3

# Install sqlite3 dependencies. You can skip this if you don't use sqlite3 in the image,
# in which case you should also move better-sqlite3 to "devDependencies" in package.json.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev

# From here on we use the least-privileged `node` user to run the backend.
USER node

# This should create the app dir as `node`.
# If it is instead created as `root` then the `tar` command below will
# fail: `can't create directory 'packages/': Permission denied`.
# If this occurs, then ensure BuildKit is enabled (`DOCKER_BUILDKIT=1`)
# so the app dir is correctly created as `node`.
WORKDIR /app

# Copy the install dependencies from the build stage and context
COPY --from=build --chown=node:node /app/yarn.lock /app/package.json /app/packages/backend/dist/skeleton/ ./
# Note: The skeleton bundle only includes package.json files -- if your app has
# plugins that define a `bin` export, the bin files need to be copied as well to
# be linked in node_modules/.bin during yarn install.

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --production --network-timeout 600000

# Copy the built packages from the build stage
COPY --from=build --chown=node:node /app/packages/backend/dist/bundle/ ./

# Copy any other files that we need at runtime
COPY --chown=node:node app-config*.yaml ./

# This switches many Node.js dependencies to production mode.
ENV NODE_ENV production

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

### logs of "yarn dev" (working just fine):
```log
/workspaces/atlas/backstage # yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/workspaces/atlas/backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] Loading config from MergedConfigSource{FileConfigSource{path="/workspaces/atlas/backstage/app-config.yaml"}, FileConfigSource{path="/workspaces/atlas/backstage/app-config.local.yaml"}, EnvConfigSource{count=0}}
[1] 2024-09-15T16:04:04.463Z backstage info Found 3 new secrets in config that will be redacted 
[1] 2024-09-15T16:04:04.481Z rootHttpRouter info Listening on :7007 
[1] 2024-09-15T16:04:04.483Z backstage info Plugin initialization started: 'app', 'proxy', 'scaffolder', 'auth', 'catalog', 'permission', 'search' type=initialization
[1] 2024-09-15T16:04:04.600Z search warn Postgres search engine is not supported, skipping registration of search-backend-module-pg 
[1] 2024-09-15T16:04:04.642Z auth info Configuring "database" as KeyStore provider 
[1] 2024-09-15T16:04:04.668Z scaffolder info Starting scaffolder with the following actions enabled fetch:plain, fetch:plain:file, fetch:template, debug:log, debug:wait, catalog:register, catalog:fetch, catalog:write, fs:delete, fs:rename 
[1] 2024-09-15T16:04:04.682Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog 
[1] 2024-09-15T16:04:04.698Z catalog info Performing database migration 
[1] 2024-09-15T16:04:04.870Z app info Serving static app content from /workspaces/atlas/backstage/packages/app/dist 
[1] 2024-09-15T16:04:04.883Z auth info Configuring auth provider: guest 
[1] 2024-09-15T16:04:05.525Z backstage info Plugin initialization in progress, newly initialized: 'proxy', 'permission', 'search', 'auth', still initializing: 'app', 'scaffolder', 'catalog' type=initialization
[1] 2024-09-15T16:04:05.559Z catalog info Task worker starting: github-provider:test:refresh, {"version":2,"cadence":"PT30M","timeoutAfterDuration":"PT3M"} task=github-provider:test:refresh
[1] 2024-09-15T16:04:05.706Z app info Replacing injected env config in module-backstage.b714f3d8.js entry=main
[1] 2024-09-15T16:04:05.721Z app info Storing 0 updated assets and 293 new assets 
[1] 2024-09-15T16:04:05.949Z search info Starting all scheduled search tasks. 
[1] 2024-09-15T16:04:05.951Z backstage info Plugin initialization complete, newly initialized: 'scaffolder', 'catalog', 'app' type=initialization
[1] 2024-09-15T16:04:05.962Z search info Task worker starting: search_index_software_catalog, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} task=search_index_software_catalog
[1] 2024-09-15T16:04:06.671Z catalog info Read 11 GitHub repositories (1 matching the pattern) target=github-provider:test class=GithubEntityProvider taskId=github-provider:test:refresh taskInstanceId=d3aa169b-2b13-44b6-b0e7-ef5f954e167c
[1] 2024-09-15T16:04:08.967Z search info Collating documents for software-catalog via DefaultCatalogCollatorFactory documentType=software-catalog
[1] 2024-09-15T16:04:08.990Z rootHttpRouter info [15/Sep/2024:16:04:08 +0000] "GET /api/catalog/.backstage/auth/v1/jwks.json HTTP/1.1" 200 11 "-" "node" type=incomingRequest
[1] 2024-09-15T16:04:08.999Z backstage info Created new signing key 87ff665a-c81f-45b2-b43d-902a57fe55ae 
[1] 2024-09-15T16:04:09.028Z rootHttpRouter info [15/Sep/2024:16:04:09 +0000] "GET /api/search/.backstage/auth/v1/jwks.json HTTP/1.1" 200 196 "-" "node" type=incomingRequest
[1] 2024-09-15T16:04:09.044Z rootHttpRouter info [15/Sep/2024:16:04:09 +0000] "GET /api/search/.backstage/auth/v1/jwks.json HTTP/1.1" 200 196 "-" "jose/v5.9.2" type=incomingRequest
[1] 2024-09-15T16:04:09.093Z rootHttpRouter info [15/Sep/2024:16:04:09 +0000] "GET /api/catalog/entities?limit=500&offset=0 HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-09-15T16:04:09.108Z search info Collating documents for software-catalog succeeded documentType=software-catalog
```
### logs from the docker container(not working):
```log
Loading config from MergedConfigSource{FileConfigSource{path="/app/app-config.yaml"}, EnvConfigSource{count=0}}
[2024-09-15T16:07:15.478Z] backstage info Found 3 new secrets in config that will be redacted 
[2024-09-15T16:07:15.489Z] rootHttpRouter info Listening on :7007 
[2024-09-15T16:07:15.490Z] backstage info Plugin initialization started: 'app', 'proxy', 'scaffolder', 'auth', 'catalog', 'permission', 'search' [36mtype[39m=initialization
[2024-09-15T16:07:15.575Z] search warn Postgres search engine is not supported, skipping registration of search-backend-module-pg 
[2024-09-15T16:07:15.584Z] proxy debug Running 1 plugin startup tasks... 
[2024-09-15T16:07:15.585Z] proxy debug Plugin startup hook succeeded 
[2024-09-15T16:07:15.590Z] permission debug Running 1 plugin startup tasks... 
[2024-09-15T16:07:15.590Z] permission debug Plugin startup hook succeeded 
[2024-09-15T16:07:15.591Z] auth info Configuring "database" as KeyStore provider 
[2024-09-15T16:07:15.598Z] scaffolder info Starting scaffolder with the following actions enabled fetch:plain, fetch:plain:file, fetch:template, debug:log, debug:wait, catalog:register, catalog:fetch, catalog:write, fs:delete, fs:rename 
[2024-09-15T16:07:15.603Z] search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog 
[2024-09-15T16:07:15.609Z] catalog info Performing database migration 
[2024-09-15T16:07:15.612Z] search debug Running 1 plugin startup tasks... 
[2024-09-15T16:07:15.722Z] search debug Plugin startup hook succeeded 
[2024-09-15T16:07:15.735Z] app info Serving static app content from /app/packages/app/dist 
[2024-09-15T16:07:16.265Z] auth info Configuring auth provider: guest 
[2024-09-15T16:07:16.267Z] auth debug Running 1 plugin startup tasks... 
[2024-09-15T16:07:16.267Z] auth debug Plugin startup hook succeeded 
[2024-09-15T16:07:16.275Z] scaffolder debug Running 1 plugin startup tasks... 
[2024-09-15T16:07:16.275Z] scaffolder debug Plugin startup hook succeeded 
[2024-09-15T16:07:16.284Z] catalog debug task: github-provider:test:refresh configured to run at: CURRENT_TIMESTAMP [36mtask[39m=github-provider:test:refresh
[2024-09-15T16:07:16.286Z] catalog info Task worker starting: github-provider:test:refresh, {"version":2,"cadence":"PT30M","timeoutAfterDuration":"PT3M"} [36mtask[39m=github-provider:test:refresh
[2024-09-15T16:07:16.287Z] catalog debug Running 1 plugin startup tasks... 
[2024-09-15T16:07:16.287Z] catalog debug Plugin startup hook succeeded 
[2024-09-15T16:07:16.387Z] app info Injecting env config into module-backstage.db6ff687.js [36mentry[39m=main
[2024-09-15T16:07:16.407Z] app info Storing 0 updated assets and 293 new assets 
[2024-09-15T16:07:16.491Z] backstage info Plugin initialization in progress, newly initialized: 'proxy', 'permission', 'search', 'auth', 'scaffolder', 'catalog', still initializing: 'app' [36mtype[39m=initialization
[2024-09-15T16:07:16.520Z] catalog error github-provider:test refresh failed, HttpError: fetch failed fetch failed [36mtarget[39m=github-provider:test [36mclass[39m=GithubEntityProvider [36mtaskId[39m=github-provider:test:refresh [36mtaskInstanceId[39m=2590ad0e-a4a7-4324-8937-22cca8defdff [36mname[39m=HttpError [36mstatus[39m=500 [36mrequest[39m=[object Object] [36mstack[39m=HttpError: fetch failed
    at /app/node_modules/@octokit/request/dist-node/index.js:146:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async queryWithPaging (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-BoslYJTt.cjs.js:606:22)
    at async getOrganizationRepositories (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-BoslYJTt.cjs.js:523:24)
    at async GithubEntityProvider.findCatalogFiles (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-BoslYJTt.cjs.js:843:54)
    at async GithubEntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-BoslYJTt.cjs.js:815:21)
    at async fn (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-BoslYJTt.cjs.js:800:13)
    at async TaskWorker.fn (/app/node_modules/@backstage/backend-defaults/dist/scheduler.cjs.js:568:9)
    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-defaults/dist/scheduler.cjs.js:317:7)
    at async /app/node_modules/@backstage/backend-defaults/dist/scheduler.cjs.js:265:31
[2024-09-15T16:07:16.523Z] catalog debug task: github-provider:test:refresh will next occur around 2024-09-15T16:37:16.522+00:00 [36mtask[39m=github-provider:test:refresh
[2024-09-15T16:07:16.572Z] app debug Running 1 plugin startup tasks... 
[2024-09-15T16:07:16.573Z] app debug Plugin startup hook succeeded 
[2024-09-15T16:07:16.573Z] backstage debug Running 4 startup tasks... 
[2024-09-15T16:07:16.575Z] backstage debug Startup hook succeeded 
[2024-09-15T16:07:16.575Z] search info Starting all scheduled search tasks. 
[2024-09-15T16:07:16.576Z] backstage debug Startup hook succeeded 
[2024-09-15T16:07:16.576Z] backstage debug Startup hook succeeded 
[2024-09-15T16:07:16.577Z] backstage debug Startup hook succeeded 
[2024-09-15T16:07:16.577Z] backstage info Plugin initialization complete, newly initialized: 'app' [36mtype[39m=initialization
[2024-09-15T16:07:16.586Z] search debug task: search_index_software_catalog configured to run at: datetime('now', '3 seconds') [36mtask[39m=search_index_software_catalog
[2024-09-15T16:07:16.586Z] search info Task worker starting: search_index_software_catalog, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} [36mtask[39m=search_index_software_catalog
[2024-09-15T16:07:19.592Z] search info Collating documents for software-catalog via DefaultCatalogCollatorFactory [36mdocumentType[39m=software-catalog
[2024-09-15T16:07:19.630Z] rootHttpRouter info [15/Sep/2024:16:07:19 +0000] "GET /api/catalog/.backstage/auth/v1/jwks.json HTTP/1.1" 200 11 "-" "node" [36mtype[39m=incomingRequest
[2024-09-15T16:07:19.653Z] backstage info Created new signing key 18f89884-8ab2-4700-b028-675c06609250 
[2024-09-15T16:07:19.674Z] rootHttpRouter info [15/Sep/2024:16:07:19 +0000] "GET /api/search/.backstage/auth/v1/jwks.json HTTP/1.1" 200 196 "-" "node" [36mtype[39m=incomingRequest
[2024-09-15T16:07:19.694Z] rootHttpRouter info [15/Sep/2024:16:07:19 +0000] "GET /api/search/.backstage/auth/v1/jwks.json HTTP/1.1" 200 196 "-" "jose/v5.9.2" [36mtype[39m=incomingRequest
[2024-09-15T16:07:19.733Z] rootHttpRouter info [15/Sep/2024:16:07:19 +0000] "GET /api/catalog/entities?limit=500&offset=0 HTTP/1.1" 200 2 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" [36mtype[39m=incomingRequest
[2024-09-15T16:07:19.738Z] search warn Index for software-catalog was not created: indexer received 0 documents [36mdocumentType[39m=software-catalog
[2024-09-15T16:07:19.739Z] search info Collating documents for software-catalog succeeded [36mdocumentType[39m=software-catalog
[2024-09-15T16:07:19.739Z] search debug task: search_index_software_catalog will next occur around 2024-09-15T16:17:19.739+00:00 [36mtask[39m=search_index_software_catalog

```

### 🖥️ Your Environment

yarn run v1.22.19
$ /workspaces/atlas/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.153.1-microsoft-standard-WSL2 - linux/x64
node: v18.18.2
yarn: 1.22.19
cli:  0.27.0 (installed)
backstage:  1.30.4

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.9.3
  @backstage/backend-common                                        0.24.1
  @backstage/backend-defaults                                      0.4.4
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.17
  @backstage/backend-plugin-api                                    0.8.1
  @backstage/backend-tasks                                         0.6.1
  @backstage/catalog-client                                        1.6.6
  @backstage/catalog-model                                         1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.8
  @backstage/core-components                                       0.14.10
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.7.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.73
  @backstage/plugin-app-node                                       0.1.24
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.17
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.7
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.7
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.19
  @backstage/plugin-auth-backend-module-github-provider            0.1.21
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.21
  @backstage/plugin-auth-backend-module-google-provider            0.1.21
  @backstage/plugin-auth-backend-module-guest-provider             0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.19
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.17
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.6
  @backstage/plugin-auth-backend-module-okta-provider              0.0.17
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.5
  @backstage/plugin-auth-backend                                   0.22.12
  @backstage/plugin-auth-node                                      0.5.1
  @backstage/plugin-auth-react                                     0.1.5
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-github                  0.7.2
  @backstage/plugin-catalog-backend-module-logs                    0.0.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.22
  @backstage/plugin-catalog-backend                                1.25.2
  @backstage/plugin-catalog-common                                 1.0.26
  @backstage/plugin-catalog-graph                                  0.4.8
  @backstage/plugin-catalog-import                                 0.12.2
  @backstage/plugin-catalog-node                                   1.12.6
  @backstage/plugin-catalog-react                                  1.12.3
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-events-node                                    0.3.10
  @backstage/plugin-kubernetes-backend                             0.18.5
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-kubernetes-node                                0.1.18
  @backstage/plugin-kubernetes-react                               0.4.2
  @backstage/plugin-kubernetes                                     0.11.13
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.21
  @backstage/plugin-permission-backend                             0.5.48
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.2
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.5
  @backstage/plugin-scaffolder-backend-module-azure                0.1.16
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.14
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.16
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.14
  @backstage/plugin-scaffolder-backend-module-github               0.4.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.6
  @backstage/plugin-scaffolder-backend                             1.24.1
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node                                0.4.10
  @backstage/plugin-scaffolder-react                               1.11.0
  @backstage/plugin-scaffolder                                     1.24.0
  @backstage/plugin-search-backend-module-catalog                  0.2.1
  @backstage/plugin-search-backend-module-pg                       0.5.34
  @backstage/plugin-search-backend-module-techdocs                 0.2.1
  @backstage/plugin-search-backend-node                            1.3.1
  @backstage/plugin-search-backend                                 1.5.16
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.12
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.13
  @backstage/plugin-techdocs-node                                  1.12.10
  @backstage/plugin-techdocs-react                                 1.2.7
  @backstage/plugin-techdocs                                       1.10.8
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 1.23s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Indeed, would be best to have the cause of the error included in the log message too, that'll tell us what's actually going wrong with the fetch. Leaving this open for contributions for now in case anyone want to help out 🙏 

For the actual issue, have you verified that `myhost.acme.intern` is reachable from within your container?
