### ISSUE TITLE
🐛 Bug Report: eventsModuleGithubEventRouter is not a function

### ISSUE THREAD

**Issue by adminy** [backstage/backstage#26750]
### 📜 Description

https://github.com/backstage/backstage/blob/761dd1b6d6498893e31a8d2eb9daf0e40101e296/plugins/events-backend-module-github/README.md?plain=1#L36

### 👍 Expected behavior

allow for events coming at `/api/events/http/github` to refresh the catalog.

### 👎 Actual Behavior with Screenshots

eventsModuleGithubEventRouter is not a function

also if I just pass it as is, not calling it,
it returns {"status":"accepted"}
but no catalog is refreshed.

### 👟 Reproduction steps

```javascript
import { createBackend } from '@backstage/backend-defaults'
import { eventsModuleGithubEventRouter } from '@backstage/plugin-events-backend-module-github/alpha'
const backend = createBackend()
backend.add(eventsModuleGithubEventRouter()) // its not a function!
backend.start()
```

Also I'm trying to pretend to be github:
```bash
curl -H "x-github-event: push" \
  -H "X-Hub-Signature-256: sha256=$(echo -en refresh | sha256sum)" \
  -X POST http://localhost:7007/api/events/http/github \
  -d '{ "catalogFile": { "action": "modified", "path": "catalog-info.yaml" }, "org": "example", "ref: "refs/heads/main" }'
```
app-config.yaml
```yaml
events:
  modules:
    github:
      webhookSecret: refresh
  http:
    topics: # exposes: POST /api/events/http/{topic}
      - github
      - aws
```
But it doesn't do anything.

### 🖥️ Your Environment

```
OS:   Linux 6.10.10 - linux/x64
node: v20.16.0
yarn: 1.22.22
cli:  0.27.0 (installed)
backstage:  1.31.0-next.2

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.9.2, 0.9.3
  @backstage/backend-common                                        0.23.3, 0.24.0, 0.24.1
  @backstage/backend-defaults                                      0.4.3, 0.4.4
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.16, 0.1.17
  @backstage/backend-plugin-api                                    0.7.0, 0.8.0, 0.8.1
  @backstage/backend-tasks                                         0.6.0
  @backstage/catalog-client                                        1.6.6
  @backstage/catalog-model                                         1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.8
  @backstage/core-components                                       0.14.10
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7, 0.7.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.72
  @backstage/plugin-app-node                                       0.1.23
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.15
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.6
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.6
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.18
  @backstage/plugin-auth-backend-module-github-provider            0.1.20
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.20
  @backstage/plugin-auth-backend-module-google-provider            0.1.20
  @backstage/plugin-auth-backend-module-guest-provider             0.1.9
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.18
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.4
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.16
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.4
  @backstage/plugin-auth-backend-module-okta-provider              0.0.16
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.4
  @backstage/plugin-auth-backend                                   0.22.10
  @backstage/plugin-auth-node                                      0.4.17, 0.5.0, 0.5.1
  @backstage/plugin-auth-react                                     0.1.5
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-aws                     0.4.0
  @backstage/plugin-catalog-backend-module-github-org              0.2.0
  @backstage/plugin-catalog-backend-module-github                  0.7.0
  @backstage/plugin-catalog-backend-module-logs                    0.0.2
  @backstage/plugin-catalog-backend-module-openapi                 0.1.43
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.21
  @backstage/plugin-catalog-backend                                1.25.0, 1.25.2
  @backstage/plugin-catalog-common                                 1.0.26
  @backstage/plugin-catalog-graph                                  0.4.8
  @backstage/plugin-catalog-import                                 0.12.2
  @backstage/plugin-catalog-node                                   1.12.5, 1.12.6
  @backstage/plugin-catalog-react                                  1.12.3
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-events-backend-module-github                   0.2.9
  @backstage/plugin-events-backend                                 0.3.10
  @backstage/plugin-events-node                                    0.3.10, 0.3.9
  @backstage/plugin-gcalendar                                      0.3.28
  @backstage/plugin-home-react                                     0.1.16
  @backstage/plugin-home                                           0.7.9
  @backstage/plugin-kubernetes-backend                             0.18.4
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-kubernetes-node                                0.1.17
  @backstage/plugin-kubernetes-react                               0.4.2
  @backstage/plugin-kubernetes                                     0.11.13
  @backstage/plugin-notifications-common                           0.0.5
  @backstage/plugin-notifications                                  0.3.0
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.20
  @backstage/plugin-permission-backend                             0.5.47
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.1, 0.8.2
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.4
  @backstage/plugin-scaffolder-backend-module-azure                0.1.15
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.13
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.15
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.13
  @backstage/plugin-scaffolder-backend-module-github               0.4.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.5
  @backstage/plugin-scaffolder-backend                             1.24.0
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node                                0.4.9
  @backstage/plugin-scaffolder-react                               1.11.0
  @backstage/plugin-scaffolder                                     1.24.0
  @backstage/plugin-search-backend-module-catalog                  0.2.0, 0.2.1
  @backstage/plugin-search-backend-module-pg                       0.5.33
  @backstage/plugin-search-backend-module-techdocs                 0.2.0
  @backstage/plugin-search-backend-node                            1.3.0, 1.3.1
  @backstage/plugin-search-backend                                 1.5.15
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.11
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.13
  @backstage/plugin-techdocs-node                                  1.12.9
  @backstage/plugin-techdocs-react                                 1.2.7
  @backstage/plugin-techdocs                                       1.10.8
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
You'll want to drop the function call from `eventsModuleGithubEventRouter`, so just `backend.add(eventsModuleGithubEventRouter)`

Fixing the docs for this in https://github.com/backstage/backstage/pull/26775

**Comment by adminy** [comment]
still this does not refresh the catalog. Any ideas?

I tried a couple of variations of this:
```bash
curl -H "x-github-event: push" \
  -H "X-Hub-Signature-256: sha256=$(echo -en refresh | sha256sum)" \
  -X POST http://localhost:7007/api/events/http/github \
  -d '{ "catalogFile": { "action": "modified", "path": "catalog-info.yaml" }, "org": "example", "ref: "refs/heads/main" }'
```

always comes back with `{"status":"accepted"}`  but no refresh of the catalog occurs.

**Comment by camilaibs** [comment]
Could you double checking the payload format with the linked documentation? It doesn't look right.

**Comment by alexef** [comment]
@Rugvip after changing it to not be a function call, it still fails with: ```[1] /Users/alex/work/stack/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:121
[1]       const ep = this.#extensionPoints.get(ref.id);
[1]                                                ^
[1] 
[1] 
[1] TypeError: Cannot read properties of undefined (reading 'id')
[1]     at BackendInitializer.#getInitDeps (/Users/alex/work/stack/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:121:48)
[1]     at <anonymous> (/Users/alex/work/stack/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:328:30)
[1]     at async Promise.all (index 10)
[1]     at BackendInitializer.#doStart (/Users/alex/work/stack/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:278:5)
[1]     at BackendInitializer.start (/Users/alex/work/stack/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
[1]     at BackstageBackend.start (/Users/alex/work/stack/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)
[1] 
[1] Node.js v20.12.2
```
this is on 1.31

**Comment by Rugvip** [comment]
@alexef hmm, could you double check that you only have a single version of the backend app api packages, and that you don't have any type errors in your project?

```sh
yarn why @backstage/backend-app-api

yarn tsc:full
```

**Comment by alexef** [comment]
I think the issue was not with eventsModuleGithubEventRouter, but with other plugins that had a custom legacyPlugin mount, due to custom pluginEnvironment and complications. I'm passed, please ignore the previous comment.

**Comment by Rugvip** [comment]
Alright!

I'm gonna close this as I think the discussion is past the original issue. Please open separate issues if anything else pops up
