### ISSUE TITLE
🐛 Bug Report: Cannot start the newly created backstage app

### ISSUE THREAD

**Issue by psychiatrichwj** [backstage/backstage#26766]
### 📜 Description

I created a new backstage app with `npx @backstage/create-app@latest` and when trying to run with `yarn dev`, I got following error:

```
Error: The SQLite driver does not support plugin division mode 'schema'
    at Sqlite3Connector.getClient (/Users/psychiatrichwj/dev-portal/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/database/connectors/sqlite3.ts:192:13)
    at DatabaseManagerImpl.getDatabase (/Users/psychiatrichwj/dev-portal/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/database/DatabaseManager.ts:138:37)
    at Object.getClient (/Users/psychiatrichwj/dev-portal/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/database/DatabaseManager.ts:79:34)
    at Function.create (/Users/psychiatrichwj/dev-portal/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/plugin/keys/DatabaseKeyStore.ts:58:35)
    at Function.create (/Users/psychiatrichwj/dev-portal/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/plugin/keys/DatabasePluginKeySource.ts:50:45)
    at createPluginKeySource (/Users/psychiatrichwj/dev-portal/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/plugin/keys/createPluginKeySource.ts:40:36)
    at Object.factory (/Users/psychiatrichwj/dev-portal/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/authServiceFactory.ts:53:29)
    at Object.factory (/Users/psychiatrichwj/dev-portal/backstage/node_modules/@backstage/backend-plugin-api/src/services/system/types.ts:321:9)
    at <anonymous> (/Users/psychiatrichwj/dev-portal/backstage/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:334:29)
```

### 👍 Expected behavior

Newly created app should start without a problem

### 👎 Actual Behavior with Screenshots

Newly created app failed to start

### 👟 Reproduction steps

Create a new application, and run `yarn dev`

### 🖥️ Your Environment

Sqlite version:
```
SQLite version 3.43.2 2023-10-10 13:08:14
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Did you make any changes to the app or config? I'm not able to reproduce this in a new app

**Comment by psychiatrichwj** [comment]
No, no changes, I suspected something up with sqllite?

**Comment by freben** [comment]
No. A `pluginDivisionMode` setting must be somewhere in your config; this is thrown by our code and as far as I can tell it's all defaulted to the value `'database'` unless explicitly configured to something else. Could you for example have an `app-config.local.yaml` that has a partial database config in it? Your config files are merged together in layers, so the setting may not be in the file you expect it to be.
