### ISSUE TITLE
🐛 Bug Report:Scaffolder Actions failing with JWTClaimValidationFailed

### ISSUE THREAD

**Issue by padupe** [backstage/backstage#26825]
### 📜 Description

I have a Scaffolder Action that consumes an external API through the Backstage proxy mechanic.

When migrating to the new backend system, I started receiving the error message:

```
{"error":{"name":"AuthenticationError","message":"Invalid plugin token; caused by JWTClaimValidationFailed: unexpected \"aud\" claim value","cause":{"code":"ERR_JWT_CLAIM_VALIDATION_FAILED","name":"JWTClaimValidationFailed","claim":"aud","reason":"check_failed","message":"unexpected \"aud\" claim value","stack":"JWTClaimValidationFailed: unexpected \"aud\" claim value\n    at exports.default (/Users/padupe/Projects/backstage/node_modules/jose/dist/node/cjs/lib/jwt_claims_set.js:57:15)\n    at Object.jwtVerify (/Users/padupe/Projects/backstage/node_modules/jose/dist/node/cjs/jwt/verify.js:12:53)\n    at PluginTokenHandler.verifyToken (/Users/padupe/Projects/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/plugin/PluginTokenHandler.ts:99:25)\n    at DefaultAuthService.authenticate (/Users/padupe/Projects/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/DefaultAuthService.ts:60:26)\n    at DefaultHttpAuthService.#extractCredentialsFromRequest (/Users/padupe/Projects/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:95:12)\n    at DefaultHttpAuthService.credentials (/Users/padupe/Projects/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:138:9)"},"stack":"AuthenticationError: Invalid plugin token; caused by JWTClaimValidationFailed: unexpected \"aud\" claim value\n    at <anonymous> (/Users/padupe/Projects/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/plugin/PluginTokenHandler.ts:108:13)\n    at PluginTokenHandler.verifyToken (/Users/padupe/Projects/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/plugin/PluginTokenHandler.ts:99:25)\n    at DefaultAuthService.authenticate (/Users/padupe/Projects/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/DefaultAuthService.ts:60:26)\n    at DefaultHttpAuthService.#extractCredentialsFromRequest (/Users/padupe/Projects/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:95:12)\n    at DefaultHttpAuthService.credentials (/Users/padupe/Projects/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:138:9)"},"request":{"method":"GET","url":"/api/proxy/tech-hub-winrm/health"},"response":{"statusCode":401}}
```

### 👍 Expected behavior

API being "invoked" successfully.

### 👎 Actual Behavior with Screenshots

Message error.

### 👟 Reproduction steps

1. Migrate Scaffolder Actions to "new" Backend system;

```ts
export class ExampleService implements IExampleService {
  private readonly auth: AuthService
  private readonly logger: Logger
  private readonly discoveryApi: DiscoveryApi

  constructor(
    auth: AuthService,
    discoveryApi: DiscoveryApi,
    logger: Logger
  ){
    this.auth = auth
    this.discoveryApi = discoveryApi
    this.logger = logger
  }

   private async getUrlFromProxy(): Promise<string> {
    const proxyUrl = await this.discoveryApi.getBaseUrl('proxy')
    return `${proxyUrl}/example`
  }

  async healthCheckApi(): Promise<boolean> {
    const url = await this.getUrlFromProxy()
    const token = await this.generateBackendToken()
    const health = await fetch(`${url}/health`, { 
      method: 'GET', 
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`
      }
    })

    const data = await health.json()

    if (data.status !== 'success') { 
      this.logger.error(`API is "unhealth"`)
      throw Error(`API is "unhealth"`)
    }

    return true
  }

  private async generateBackendToken() {
    const { token } = await this.auth.getPluginRequestToken({
      onBehalfOf: await this.auth.getOwnServiceCredentials(),
      targetPluginId: 'scaffolder'
    }))
    return token
  }
```

2. Call action;
3. Error

### 📃 Provide the context for the Bug.

After migration to the new backend.

In the "old" backend we made calls to this API through the Scaffolder Action in a similar way to:

1. Class
```ts
export class ExampleService implements IExampleService {
  private readonly logger: Logger
  private readonly discoveryApi: DiscoveryApi

  constructor(
    discoveryApi: DiscoveryApi,
    logger: Logger
  ){
    this.discoveryApi = discoveryApi
    this.logger = logger
  }

   private async getUrlFromProxy(): Promise<string> {
    const proxyUrl = await this.discoveryApi.getBaseUrl('proxy')
    return `${proxyUrl}/example`
  }

  async healthCheckApi(): Promise<boolean> {
    const url = await this.getUrlFromProxy()
    const health = await fetch(`${url}/health`, { 
      method: 'GET', 
      headers: {
        'Content-Type': 'application/json',
      }
    })

    const data = await health.json()

    if (data.status !== 'success') { 
      this.logger.error(`API is "unhealth"`)
      throw Error(`API is "unhealth"`)
    }

    return true
  }
```

2. Config at `app-config.yaml`:
```yaml
app:
  title: Backstage

[...]

proxy:
  endpoints:
    '/example':
      target: 'https://example-api.acme.com'
      headers:
        Authorization: Bearer ${EXAMPLE_API_TOKEN}
```

### 🖥️ Your Environment

```
OS:   Darwin 24.0.0 - darwin/arm64
node: v18.20.4
yarn: 1.22.22
cli:  0.27.0 (installed)
backstage:  1.30.4

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.6.2, 0.7.9, 0.9.3, 1.0.0
  @backstage/backend-common                                        0.21.6, 0.21.7, 0.23.3, 0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.4.4, 0.5.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.17, 0.1.18
  @backstage/backend-plugin-api                                    0.6.16, 0.6.21, 0.7.0, 0.8.1, 1.0.0
  @backstage/backend-tasks                                         0.5.21, 0.5.27, 0.6.1
  @backstage/catalog-client                                        1.6.6, 1.7.0
  @backstage/catalog-model                                         1.6.0, 1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7, 0.2.8
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0, 1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.8
  @backstage/core-components                                       0.12.5, 0.14.10
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.37
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7, 0.7.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0, 1.15.0
  @backstage/plugin-analytics-module-ga4                           0.2.5
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.73
  @backstage/plugin-app-node                                       0.1.24
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.17
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.7
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.7
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.19
  @backstage/plugin-auth-backend-module-github-provider            0.1.21
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.21
  @backstage/plugin-auth-backend-module-google-provider            0.1.21
  @backstage/plugin-auth-backend-module-guest-provider             0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.19, 0.2.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.17
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.6
  @backstage/plugin-auth-backend-module-okta-provider              0.0.17
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.5
  @backstage/plugin-auth-backend                                   0.22.12
  @backstage/plugin-auth-node                                      0.4.11, 0.4.17, 0.5.1, 0.5.2
  @backstage/plugin-auth-react                                     0.1.5
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-github-org              0.3.0
  @backstage/plugin-catalog-backend-module-github                  0.7.2, 0.7.3
  @backstage/plugin-catalog-backend-module-msgraph                 0.6.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.22
  @backstage/plugin-catalog-backend                                1.25.2, 1.26.0
  @backstage/plugin-catalog-common                                 1.0.26, 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.8
  @backstage/plugin-catalog-import                                 0.12.2
  @backstage/plugin-catalog-node                                   1.12.6, 1.13.0
  @backstage/plugin-catalog-react                                  1.12.3
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-dynatrace                                      10.0.4
  @backstage/plugin-events-node                                    0.3.10, 0.4.0
  @backstage/plugin-home-react                                     0.1.16
  @backstage/plugin-home                                           0.7.9
  @backstage/plugin-kubernetes-backend                             0.18.5
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-kubernetes-node                                0.1.18
  @backstage/plugin-kubernetes-react                               0.4.2
  @backstage/plugin-kubernetes                                     0.11.13
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.21
  @backstage/plugin-permission-backend                             0.5.48
  @backstage/plugin-permission-common                              0.7.13, 0.7.14, 0.8.1
  @backstage/plugin-permission-node                                0.7.27, 0.7.32, 0.8.2, 0.8.3
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.5, 0.5.6
  @backstage/plugin-scaffolder-backend-module-azure                0.1.16
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.14
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.16
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.14
  @backstage/plugin-scaffolder-backend-module-github               0.4.2, 0.5.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.6
  @backstage/plugin-scaffolder-backend                             1.24.1
  @backstage/plugin-scaffolder-common                              1.5.5, 1.5.6
  @backstage/plugin-scaffolder-node                                0.4.10, 0.4.11
  @backstage/plugin-scaffolder-react                               1.11.0
  @backstage/plugin-scaffolder                                     1.24.0
  @backstage/plugin-search-backend-module-catalog                  0.2.1, 0.2.2
  @backstage/plugin-search-backend-module-explore                  0.2.1
  @backstage/plugin-search-backend-module-pg                       0.5.34
  @backstage/plugin-search-backend-module-techdocs                 0.2.1
  @backstage/plugin-search-backend-node                            1.3.1, 1.3.2
  @backstage/plugin-search-backend                                 1.5.16
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-node                                   0.1.10
  @backstage/plugin-signals-react                                  0.0.2, 0.0.4
  @backstage/plugin-sonarqube-backend                              0.2.20
  @backstage/plugin-sonarqube-react                                0.1.16
  @backstage/plugin-sonarqube                                      0.7.17
  @backstage/plugin-tech-radar                                     0.7.4
  @backstage/plugin-techdocs-backend                               1.10.12
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.13
  @backstage/plugin-techdocs-node                                  1.12.10
  @backstage/plugin-techdocs-react                                 1.2.7
  @backstage/plugin-techdocs                                       1.10.8
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.2.19, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Hi! The caller generates a token explicitly for the scaffolder as a recipient (that's what the `targetPluginId` means), then actually calls the proxy instead of the scaffolder, and then the proxy inserts some other foreign token to speak with the upstream. But what you may have wanted to do in this case instead, is to either set `targetPluginId` to `proxy`, or [follow the docs](https://backstage.io/docs/plugins/proxying/#configuration) to set your route as `credentials: dangerously-allow-unauthenticated` so that the proxy doesn't gatekeep for a service token in the first place.
