### ISSUE TITLE
🐛 Bug Report: [ERR_PACKAGE_NOT_EXPORTED]: Package subpath './dist/alpha' is not defined by "exports" in @backstage/plugin-scaffolder-node/package.json

### ISSUE THREAD

**Issue by padupe** [backstage/backstage#26956]
### 📜 Description

I am developing a module with custom actions that will be consumed by Scaffolder and when performing a test in the local environment I received the error:

```bash
[backend]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/alpha' is not defined by "exports" in /Users/padupe/backstage/node_modules/@backstage/plugin-scaffolder-node/package.json
[backend]:     at exportsNotFound (node:internal/modules/esm/resolve:304:10)
[backend]:     at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
[backend]:     at resolveExports (node:internal/modules/cjs/loader:592:36)
[backend]:     at Module._findPath (node:internal/modules/cjs/loader:669:31)
[backend]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
[backend]:     at Module._load (node:internal/modules/cjs/loader:986:27)
[backend]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
[backend]:     at require (node:internal/modules/helpers:179:18)
[backend]:     at Object.<anonymous> (/Users/padupe/backstage/plugins/scaffolder-backend-module-raizen-scaffolder-actions/src/module.ts:4:8)
[backend]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
[backend]:     at Module._compile (/Users/padupe/backstage/node_modules/pirates/lib/index.js:117:24)
[backend]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
[backend]:     at Object.newLoader [as .ts] (/Users/padupe/backstage/pirates/lib/index.js:121:7)
[backend]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
[backend]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
[backend]:     at Module.require (node:internal/modules/cjs/loader:1233:19) {
[backend]:   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
[backend]: }
[backend]: 
[backend]: Node.js v20.16.0
```

### 👍 Expected behavior

Backend running.

### 👎 Actual Behavior with Screenshots

Backend fails to start.

### 👟 Reproduction steps

1. Develop a module based on [documentation](https://backstage.io/docs/features/software-templates/writing-custom-actions).

2. Import into "packages/src/index.ts".

3. Run "yarn dev"

4. Get the error.

### 📃 Provide the context for the Bug.

Writing Custom Actions

### 🖥️ Your Environment

```
OS:   Darwin 24.0.0 - darwin/arm64
node: v20.16.0
yarn: 4.4.1
cli:  0.27.1 (installed)
backstage:  1.31.1

Dependencies:
  @backstage/app-defaults                                          1.5.11
  @backstage/backend-app-api                                       1.0.0
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.5.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.18
  @backstage/backend-plugin-api                                    1.0.0
  @backstage/catalog-client                                        1.7.0
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.8
  @backstage/cli                                                   0.27.1
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.0
  @backstage/core-compat-api                                       0.2.8, 0.3.0
  @backstage/core-components                                       0.14.10, 0.15.0
  @backstage/core-plugin-api                                       1.9.4
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.9
  @backstage/frontend-app-api                                      0.8.0
  @backstage/frontend-plugin-api                                   0.7.0, 0.8.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.32
  @backstage/integration                                           1.15.0
  @backstage/plugin-api-docs                                       0.11.10
  @backstage/plugin-app-backend                                    0.3.74
  @backstage/plugin-app-node                                       0.1.25
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.0
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.0
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.0
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.0
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.0
  @backstage/plugin-auth-backend-module-github-provider            0.2.0
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.0
  @backstage/plugin-auth-backend-module-google-provider            0.2.0
  @backstage/plugin-auth-backend-module-guest-provider             0.2.0
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.0
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.0
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.0
  @backstage/plugin-auth-backend-module-okta-provider              0.1.0
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.0
  @backstage/plugin-auth-backend                                   0.23.0
  @backstage/plugin-auth-node                                      0.5.2
  @backstage/plugin-auth-react                                     0.1.6
  @backstage/plugin-bitbucket-cloud-common                         0.2.23
  @backstage/plugin-catalog-backend-module-github-org              0.3.1
  @backstage/plugin-catalog-backend-module-github                  0.7.4
  @backstage/plugin-catalog-backend-module-logs                    0.1.1
  @backstage/plugin-catalog-backend-module-msgraph                 0.6.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.0
  @backstage/plugin-catalog-backend                                1.26.1
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.10
  @backstage/plugin-catalog-import                                 0.12.4
  @backstage/plugin-catalog-node                                   1.13.0
  @backstage/plugin-catalog-react                                  1.13.1
  @backstage/plugin-catalog                                        1.23.1
  @backstage/plugin-devtools-backend                               0.4.0
  @backstage/plugin-devtools-common                                0.1.12
  @backstage/plugin-devtools                                       0.1.18
  @backstage/plugin-events-node                                    0.4.0
  @backstage/plugin-home-react                                     0.1.17
  @backstage/plugin-home                                           0.7.11
  @backstage/plugin-kubernetes-backend                             0.18.6
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-node                                0.1.19
  @backstage/plugin-kubernetes-react                               0.4.3
  @backstage/plugin-kubernetes                                     0.11.15
  @backstage/plugin-org                                            0.6.30
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.0
  @backstage/plugin-permission-backend                             0.5.49
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.3
  @backstage/plugin-permission-react                               0.4.26
  @backstage/plugin-proxy-backend                                  0.5.6
  @backstage/plugin-scaffolder-backend-module-azure                0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.0
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.0
  @backstage/plugin-scaffolder-backend-module-github               0.5.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.5.0
  @backstage/plugin-scaffolder-backend                             1.25.0
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node                                0.4.11
  @backstage/plugin-scaffolder-react                               1.12.1
  @backstage/plugin-scaffolder                                     1.25.1
  @backstage/plugin-search-backend-module-catalog                  0.2.2
  @backstage/plugin-search-backend-module-pg                       0.5.35
  @backstage/plugin-search-backend-module-techdocs                 0.2.2
  @backstage/plugin-search-backend-node                            1.3.2
  @backstage/plugin-search-backend                                 1.5.17
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.0
  @backstage/plugin-search                                         1.4.17
  @backstage/plugin-signals-react                                  0.0.5
  @backstage/plugin-techdocs-backend                               1.10.13
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.15
  @backstage/plugin-techdocs-node                                  1.12.11
  @backstage/plugin-techdocs-react                                 1.2.8
  @backstage/plugin-techdocs                                       1.10.10
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.6.0
  @backstage/theme                                                 0.5.7
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.9
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by padupe** [comment]
My IDE dynamically performed 
```ts
import { scaffolderActionsExtensionPoint } from '@backstage/plugin-scaffolder-node/dist/alpha';
```

While the correct one should be:
```ts
import { scaffolderActionsExtensionPoint } from '@backstage/plugin-scaffolder-node/alpha';
```

Closing the issue.
