### ISSUE TITLE
🐛 Bug Report: Software template fetch:template action fails at j2 macro

### ISSUE THREAD

**Issue by Vinzz** [backstage/backstage#27000]
### 📜 Description

When I fetch a template (action: fetch:template) that contains a j2 macro like:

`j2_block_start_string: '{{{%'`

The templating process fails at parsing it, even though it's not in the ${{ values.xx }} format

### 👍 Expected behavior

It should ignore this macro and not fail

### 👎 Actual Behavior with Screenshots

it actually fails:

```
2024-10-07T14:09:24.000Z Error: (unknown path) [Line 3, Column 29]
[11](https://backstage.0cs-oab-dt-services-staging.caas-cnp-apps-np.com.intraorange/create/tasks/1da10366-30ea-488c-8ede-82fb6aef3cda#line-11)  tag name expected
[12](https://backstage.0cs-oab-dt-services-staging.caas-cnp-apps-np.com.intraorange/create/tasks/1da10366-30ea-488c-8ede-82fb6aef3cda#line-12)    at render (<isolated-vm>:10434:[13](https://backstage.0cs-oab-dt-services-staging.caas-cnp-apps-np.com.intraorange/create/tasks/1da10366-30ea-488c-8ede-82fb6aef3cda#line-13))
13    at <isolated-vm>:1:1
[14](https://backstage.0cs-oab-dt-services-staging.caas-cnp-apps-np.com.intraorange/create/tasks/1da10366-30ea-488c-8ede-82fb6aef3cda#line-14)    at (<isolated-vm boundary>)
[15](https://backstage.0cs-oab-dt-services-staging.caas-cnp-apps-np.com.intraorange/create/tasks/1da10366-30ea-488c-8ede-82fb6aef3cda#line-15)    at render (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-L9rspgmo.cjs.js:933:22)
[16](https://backstage.0cs-oab-dt-services-staging.caas-cnp-apps-np.com.intraorange/create/tasks/1da10366-30ea-488c-8ede-82fb6aef3cda#line-16)    at handler (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-L9rspgmo.cjs.js:1185:32)
```

### 👟 Reproduction steps

Make a fetch tamplate with an index.js file containing:

```
console.log('Hello from ${{ values.name }}!');

j2_block_start_string: '{{{%'
```

### 🖥️ Your Environment

Backstage

OS: backstage-69f4bb945b-2wtcl: Linux 5.15.0-58-generic - linux/x64
Resources: Memory: 43027/64312MB - Load: 10.27/10.12/12.27
node: v18.20.4
backstage: 1.31.1
Dependencies:
    @backstage-community/plugin-adr-backend: 0.4.24
    @backstage-community/plugin-adr-common: 0.2.28
    @backstage-community/plugin-adr: 0.6.25
    @backstage-community/plugin-explore-backend: 0.1.5
    @backstage-community/plugin-explore-common: 0.0.5
    @backstage-community/plugin-explore-node: 0.1.3
    @backstage-community/plugin-explore-react: 0.0.41
    @backstage-community/plugin-explore: 0.5.4
    @backstage-community/plugin-shortcuts: 0.3.26
    @backstage-community/plugin-tech-radar: 0.7.9
    @backstage-community/search-backend-module-adr: 0.1.4
    @backstage/app-defaults: 1.5.11
    @backstage/backend-app-api: 0.9.3, 1.0.0
    @backstage/backend-common: 0.23.3, 0.24.1, 0.25.0
    @backstage/backend-defaults: 0.4.4, 0.5.0
    @backstage/backend-dev-utils: 0.1.5
    @backstage/backend-openapi-utils: 0.1.18
    @backstage/backend-plugin-api: 0.7.0, 0.8.1, 1.0.0
    @backstage/backend-tasks: 0.6.1
    @backstage/catalog-client: 1.6.6, 1.7.0
    @backstage/catalog-model: 1.6.0, 1.7.0
    @backstage/cli-common: 0.1.14
    @backstage/cli-node: 0.2.7, 0.2.8
    @backstage/cli: 0.27.1
    @backstage/config-loader: 1.9.0, 1.9.1
    @backstage/config: 1.2.0
    @backstage/core-app-api: 1.15.0
    @backstage/core-compat-api: 0.2.8, 0.3.0
    @backstage/core-components: 0.13.10, 0.14.10, 0.15.0
    @backstage/core-plugin-api: 1.9.3, 1.9.4
    @backstage/e2e-test-utils: 0.1.1
    @backstage/errors: 1.2.4
    @backstage/eslint-plugin: 0.1.9
    @backstage/frontend-plugin-api: 0.7.0, 0.8.0
    @backstage/integration-aws-node: 0.1.12
    @backstage/integration-react: 1.1.30, 1.1.31
    @backstage/integration: 1.14.0, 1.15.0
    @backstage/plugin-api-docs: 0.11.9
    @backstage/plugin-app-backend: 0.3.74
    @backstage/plugin-app-node: 0.1.25
    @backstage/plugin-auth-backend-module-atlassian-provider: 0.3.0
    @backstage/plugin-auth-backend-module-auth0-provider: 0.1.0
    @backstage/plugin-auth-backend-module-aws-alb-provider: 0.2.0
    @backstage/plugin-auth-backend-module-azure-easyauth-provider: 0.2.0
    @backstage/plugin-auth-backend-module-bitbucket-provider: 0.2.0
    @backstage/plugin-auth-backend-module-bitbucket-server-provider: 0.1.0
    @backstage/plugin-auth-backend-module-cloudflare-access-provider: 0.3.0
    @backstage/plugin-auth-backend-module-gcp-iap-provider: 0.3.0
    @backstage/plugin-auth-backend-module-github-provider: 0.2.0
    @backstage/plugin-auth-backend-module-gitlab-provider: 0.2.0
    @backstage/plugin-auth-backend-module-google-provider: 0.2.0
    @backstage/plugin-auth-backend-module-guest-provider: 0.2.0
    @backstage/plugin-auth-backend-module-microsoft-provider: 0.2.0
    @backstage/plugin-auth-backend-module-oauth2-provider: 0.3.0
    @backstage/plugin-auth-backend-module-oauth2-proxy-provider: 0.2.0
    @backstage/plugin-auth-backend-module-oidc-provider: 0.3.0
    @backstage/plugin-auth-backend-module-okta-provider: 0.1.0
    @backstage/plugin-auth-backend-module-onelogin-provider: 0.2.0
    @backstage/plugin-auth-backend: 0.23.0
    @backstage/plugin-auth-node: 0.4.17, 0.5.1, 0.5.2
    @backstage/plugin-auth-react: 0.1.5, 0.1.6
    @backstage/plugin-bitbucket-cloud-common: 0.2.23
    @backstage/plugin-catalog-backend-module-gitlab: 0.4.2
    @backstage/plugin-catalog-backend-module-scaffolder-entity-model: 0.2.0
    @backstage/plugin-catalog-backend: 1.26.0
    @backstage/plugin-catalog-common: 1.0.26, 1.1.0
    @backstage/plugin-catalog-graph: 0.4.9
    @backstage/plugin-catalog-import: 0.12.3
    @backstage/plugin-catalog-node: 1.12.6, 1.13.0
    @backstage/plugin-catalog-react: 1.12.3, 1.13.0
    @backstage/plugin-catalog: 1.23.0
    @backstage/plugin-devtools-backend: 0.4.0
    @backstage/plugin-devtools-common: 0.1.12
    @backstage/plugin-devtools: 0.1.18
    @backstage/plugin-events-node: 0.3.10, 0.4.0
    @backstage/plugin-home-react: 0.1.17
    @backstage/plugin-home: 0.7.10
    @backstage/plugin-kubernetes-backend: 0.18.6
    @backstage/plugin-kubernetes-common: 0.7.6, 0.8.2, 0.8.3
    @backstage/plugin-kubernetes-node: 0.1.19
    @backstage/plugin-kubernetes-react: 0.4.2, 0.4.3
    @backstage/plugin-kubernetes: 0.11.14, 0.11.13
    @backstage/plugin-org: 0.6.29
    @backstage/plugin-permission-backend-module-allow-all-policy: 0.2.0
    @backstage/plugin-permission-backend: 0.5.49
    @backstage/plugin-permission-common: 0.7.14, 0.8.1
    @backstage/plugin-permission-node: 0.8.2, 0.8.3
    @backstage/plugin-permission-react: 0.4.25, 0.4.26
    @backstage/plugin-proxy-backend: 0.5.6
    @backstage/plugin-scaffolder-backend-module-azure: 0.2.0
    @backstage/plugin-scaffolder-backend-module-bitbucket-cloud: 0.2.0
    @backstage/plugin-scaffolder-backend-module-bitbucket-server: 0.2.0
    @backstage/plugin-scaffolder-backend-module-bitbucket: 0.3.0
    @backstage/plugin-scaffolder-backend-module-gerrit: 0.2.0
    @backstage/plugin-scaffolder-backend-module-gitea: 0.2.0
    @backstage/plugin-scaffolder-backend-module-github: 0.5.0
    @backstage/plugin-scaffolder-backend-module-gitlab: 0.5.0
    @backstage/plugin-scaffolder-backend: 1.25.0
    @backstage/plugin-scaffolder-common: 1.5.6
    @backstage/plugin-scaffolder-node: 0.4.11
    @backstage/plugin-scaffolder-react: 1.12.0
    @backstage/plugin-scaffolder: 1.25.0
    @backstage/plugin-search-backend-module-catalog: 0.2.2
    @backstage/plugin-search-backend-module-techdocs: 0.2.2
    @backstage/plugin-search-backend-node: 1.3.1, 1.3.2
    @backstage/plugin-search-backend: 1.5.17
    @backstage/plugin-search-common: 1.2.14
    @backstage/plugin-search-react: 1.7.14, 1.8.0
    @backstage/plugin-search: 1.4.16
    @backstage/plugin-signals-react: 0.0.5
    @backstage/plugin-techdocs-backend: 1.10.13
    @backstage/plugin-techdocs-common: 0.1.0
    @backstage/plugin-techdocs-module-addons-contrib: 1.1.14
    @backstage/plugin-techdocs-node: 1.12.11
    @backstage/plugin-techdocs-react: 1.2.8
    @backstage/plugin-techdocs: 1.10.9
    @backstage/plugin-user-settings-common: 0.0.1
    @backstage/plugin-user-settings: 0.8.12
    @backstage/release-manifests: 0.0.11
    @backstage/test-utils: 1.6.0
    @backstage/theme: 0.4.4, 0.5.6, 0.5.7
    @backstage/types: 1.1.1
    @backstage/version-bridge: 1.0.8, 1.0.9
    @immobiliarelabs/backstage-plugin-gitlab-backend: 6.6.0
    @immobiliarelabs/backstage-plugin-gitlab: 6.6.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by stephenglass** [comment]
Does your template work if you modify it like this?

```yaml
console.log('Hello from ${{ values.name }}!');

{% raw %}
j2_block_start_string: '{{{%'
{% endraw %}
```

**Comment by Rugvip** [comment]
@Vinzz  You can use the `copyWithoutTemplating` option for the templating action to exclude files from templating. If you do want other parts to be templated then you'll need to escape the other warts as @stephenglass suggests. `{% ... %}` is part of the templating syntax so this is expected.

**Comment by Vinzz** [comment]
@Rugvip I beg to differ, with such a regex my sample seems to be parsed fine:

`\$\{\{.*\}\}`

That's being said, I agree that this bug can be worked around

**Comment by Rugvip** [comment]
Yep, gonna close this as it is working as intended
