### ISSUE TITLE
🐛 Bug Report: `getLocationByEntity `does not work with camel or upper case entity references

### ISSUE THREAD

**Issue by emre** [backstage/backstage#27235]
### 📜 Description

We have some entity references and entity locations like this:

Location:
```
{
"target": "https://<my-rest-api>/api/v1/<entity-type>/entityName",
"type": "my_custom_type"
}
```
Entity:

`<entity-type>/entityName`

However, when we try to get location by entity, we try to use

```
{{backstage_catalog_api_url}}/location/by-entity/<entity-type>/default/entityName
```

We get a `NotFoundError` because, `entityName` is lowered down with [stringifyEntityRef](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/entity/ref.ts#L159).

In our system we support locations like this:

-  https://example.com/api/v1/<entity-type>/entityName
-  https://example.com/api/v1/<entity-type>/entityname

They're not the same. Both entityname and entityName can co-exist.

### 👍 Expected behavior

`<catalog_api>/locations/by-entity/...` call shall work with references that includes upper case chars.

### 👎 Actual Behavior with Screenshots

<img width="1080" alt="redacted-ss" src="https://github.com/user-attachments/assets/46cf6706-2a0c-4754-9d4e-1cf0005ef8d1">

### 👟 Reproduction steps

1) create a location and entity that includes camelcase
2) try to use `<catalog_api>/locations/by-entity/...` call from catalog api to fetch the location by entity.

### 🖥️ Your Environment

```yarn run v1.22.21
$ backstage-cli info
OS:   Darwin 24.0.0 - darwin/arm64
node: v20.12.2
yarn: 1.22.21
cli:  0.26.10 (installed)
backstage:  1.28.4

Dependencies:
  @backstage/app-defaults                                          1.5.7
  @backstage/backend-app-api                                       0.7.9
  @backstage/backend-common                                        0.21.7, 0.22.0, 0.23.3
  @backstage/backend-defaults                                      0.3.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.15
  @backstage/backend-plugin-api                                    0.6.21, 0.7.0
  @backstage/backend-tasks                                         0.5.27
  @backstage/backend-test-utils                                    0.4.3
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.26.10
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.1
  @backstage/core-compat-api                                       0.2.7
  @backstage/core-components                                       0.14.9
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.34
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.29
  @backstage/integration                                           1.13.0
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.70
  @backstage/plugin-app-node                                       0.1.22
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.14
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.5
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.5
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.17
  @backstage/plugin-auth-backend-module-github-provider            0.1.19
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.19
  @backstage/plugin-auth-backend-module-google-provider            0.1.19
  @backstage/plugin-auth-backend-module-guest-provider             0.1.8
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.17
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.15
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.15
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.3
  @backstage/plugin-auth-backend                                   0.22.9
  @backstage/plugin-auth-node                                      0.4.17
  @backstage/plugin-bitbucket-cloud-common                         0.2.21
  @backstage/plugin-catalog-backend-module-ldap                    0.6.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.20
  @backstage/plugin-catalog-backend                                1.23.2
  @backstage/plugin-catalog-common                                 1.0.25
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   1.12.4
  @backstage/plugin-catalog-react                                  1.12.2
  @backstage/plugin-catalog                                        1.21.1
  @backstage/plugin-events-node                                    0.3.8
  @backstage/plugin-home-react                                     0.1.15
  @backstage/plugin-home                                           0.7.6
  @backstage/plugin-kubernetes-backend                             0.18.2
  @backstage/plugin-kubernetes-common                              0.8.1
  @backstage/plugin-kubernetes-node                                0.1.16
  @backstage/plugin-kubernetes-react                               0.4.0
  @backstage/plugin-kubernetes                                     0.11.11
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-backend                             0.5.45
  @backstage/plugin-permission-common                              0.7.14, 0.8.0
  @backstage/plugin-permission-node                                0.7.32, 0.8.0
  @backstage/plugin-permission-react                               0.4.24
  @backstage/plugin-proxy-backend                                  0.5.2
  @backstage/plugin-scaffolder-backend-module-azure                0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.12
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.14
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.12
  @backstage/plugin-scaffolder-backend-module-github               0.4.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.4
  @backstage/plugin-scaffolder-backend                             1.23.0
  @backstage/plugin-scaffolder-common                              1.5.4
  @backstage/plugin-scaffolder-node                                0.4.8
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.22.0
  @backstage/plugin-search-backend-module-catalog                  0.1.27
  @backstage/plugin-search-backend-module-pg                       0.5.31
  @backstage/plugin-search-backend-node                            1.2.26
  @backstage/plugin-search-backend                                 1.5.13
  @backstage/plugin-search-common                                  1.2.13
  @backstage/plugin-search-react                                   1.7.13
  @backstage/plugin-search                                         1.4.13
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.8
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.7
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No

**Comment by freben** [comment]
If I correctly understand what you describe, this could never work, because entity refs are by their very nature case insensitive. You can't have two entities in the catalog that differ only by casing, when it comes to their `kind:namespace/name` ref triplet. This string is used as a primary key in the database with a hard uniqueness constraint on it, and is always lowercase. There's no way around that. Yes a lot of APIs let you _input_ queries etc in mixed case, and that works because it's ultimately case insensitive internally, but the ref is always lowercase either way.

**Comment by freben** [comment]
To clarify some more, what I wrote applies to entity refs and the filters used when you search for entities (e.g. you can search for `kind=component` and it'll happily return `kind: Component` entities).

You CAN, however, probably register the URLs `https://example.com/api/v1/entityName` and ``https://example.com/api/v1/entityname` side by side - nothing should stop that as far as I know. But they have to return entities that won't result in a violation of the case insensitive naming rules :)

**Comment by freben** [comment]
`by-entity` effectively accepts an entity ref though - even if it's spread over several URL parts - so that one will inevitably be case insensitive too. The input there has nothing to do with what the URL was originally; the URL pattern is `/locations/by-entity/:kind/:namespace/:name`.

**Comment by Joz73** [comment]
Hi, I'm also seeing this issue whereby an entity registered with "Register Existing Component" button on the "Create" page registers a location with the casing of the URL provided. Also if you use the `catalog:register` template action.

So for instance if your repository name mixes case, the locations DB will store it like that and the `/api/catalog/locations/` api will return it with mixed case.

```json
[
    {
        "data": {
            "id": "ac27491c-45fc-4a29-aaf2-20b357ea1038",
            "target": "https://github.com/my-github-org/test.lowercase.api/tree/main/catalog-info.yaml",
            "type": "url"
        }
    },
    {
        "data": {
            "id": "8e7f1f39-775b-4311-852c-33d48c8962ea",
            "target": "https://github.com/my-github-org/Test.MixedCase.Api/blob/main/catalog-info.yaml",
            "type": "url"
        }
    }
]
```

When running a GET on the `/api/catalog/locations/by-entity/component/default/<name>` api for the entity that was registered with lowercase, the endpoint returns the location, regardless of casing used for <name>:

GET: http://localhost:7007/api/catalog/locations/by-entity/component/default/Test.LowerCase.Api
```json
{
    "id": "ac27491c-45fc-4a29-aaf2-20b357ea1038",
    "type": "url",
    "target": "https://github.com/my-github-org/test.lowercase.api/tree/main/catalog-info.yaml"
}
```

But the location that was registered with lowercase is unable to be retrieved by this endpoint:

GET: http://localhost:7007/api/catalog/locations/by-entity/component/default/Test.MixedCase.Api

```json
{
    "error": {
        "name": "NotFoundError",
        "message": "Found no location with type url and target https://github.com/ch-robinson-internal/test.mixedcase.api/blob/main/catalog-info.yaml",
        "stack": "NotFoundError: Found no location with type url and target https://github.com/my-github-org/test.mixedcase.api/blob/main/catalog-info.yaml\n    at DefaultLocationStore.getLocationByEntity (/home/myuser/git_clones/Local.Backstage/node_modules/@backstage/plugin-catalog-backend/src/providers/DefaultLocationStore.ts:156:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/home/myuser/git_clones/Local.Backstage/node_modules/@backstage/plugin-catalog-backend/src/service/createRouter.ts:672:26)"
    },
    "request": {
        "method": "GET",
        "url": "/locations/by-entity/component/default/Test.MixedCase.Api"
    },
    "response": {
        "statusCode": 404
    }
}
```

I suspect the issue being as mentioned, the `stringifyEntityRef` is lowercasing the `entityRef` so when the [locations db query](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/providers/DefaultLocationStore.ts#L149) is done, it is case sensitive so since there is no lowercased location entity for that target url it returns 404.

I was able to adjust locally the locations query to look like this, so it uses a DB query to filter the data and it resolves the issue of having mixed casing entities like we do in our instance of backstage.

```diff
  async getLocationByEntity(entityRef) {
    const entityRefString = catalogModel.stringifyEntityRef(entityRef);
    const [entityRow] = await this.db("refresh_state").where({ entity_ref: entityRefString }).select("entity_id").limit(1);
    if (!entityRow) {
      throw new errors.NotFoundError(`found no entity for ref ${entityRefString}`);
    }
    const [searchRow] = await this.db("search").where({
      entity_id: entityRow.entity_id,
      key: `metadata.annotations.${catalogModel.ANNOTATION_ORIGIN_LOCATION}`
    }).select("value").limit(1);
    if (!searchRow?.value) {
      throw new errors.NotFoundError(
        `found no origin annotation for ref ${entityRefString}`
      );
    }
    const { type, target } = catalogModel.parseLocationRef(searchRow.value);
-     const [locationRow] = await this.db("locations").where({ type, target }).select().limit(1);
+     const [locationRow] = await this.db("locations").whereRaw('LOWER(type) = LOWER(?) AND LOWER(target) = LOWER(?)', [type, target]).select().limit(1);
    if (!locationRow) {
      throw new errors.NotFoundError(
        `Found no location with type ${type} and target ${target}`
      );
    }
    return locationRow;
  }
```

@emre & @freben 


```
├─ @backstage/cli@npm:0.33.0
│  ├─ Instances: 1
│  ├─ Version: 0.33.0
│  │ 
│  ├─ Exported Binaries
│  │  └─ backstage-cli
│  │ 
│  └─ Dependencies
│     ├─ @backstage/catalog-model@npm:^1.7.4 → npm:1.7.4
│     ├─ @backstage/cli-common@npm:^0.1.15 → npm:0.1.15
│     ├─ @backstage/cli-node@npm:^0.2.13 → npm:0.2.13
│     ├─ @backstage/config-loader@npm:^1.10.1 → npm:1.10.1
│     ├─ @backstage/config@npm:^1.3.2 → npm:1.3.2
│     ├─ @backstage/errors@npm:^1.2.7 → npm:1.2.7
│     ├─ @backstage/eslint-plugin@npm:^0.1.11 → npm:0.1.11
│     ├─ @backstage/integration@npm:^1.17.0 → npm:1.17.0
│     ├─ @backstage/release-manifests@npm:^0.0.13 → npm:0.0.13
│     ├─ @backstage/types@npm:^1.2.1 → npm:1.2.1
│     ├─ @manypkg/get-packages@npm:^1.1.3 → npm:1.1.3
│     ├─ @module-federation/enhanced@npm:^0.9.0 → npm:0.9.1
│     ├─ @octokit/graphql-schema@npm:^13.7.0 → npm:13.10.0
│     ├─ @octokit/graphql@npm:^5.0.0 → npm:5.0.6
│     ├─ @octokit/oauth-app@npm:^4.2.0 → npm:4.2.4
│     ├─ @octokit/request@npm:^8.0.0 → npm:8.4.0
│     ├─ @pmmmwh/react-refresh-webpack-plugin@npm:^0.5.7 → npm:0.5.11
│     ├─ @rollup/plugin-commonjs@npm:^26.0.0 → npm:26.0.3
│     ├─ @rollup/plugin-json@npm:^6.0.0 → npm:6.1.0
│     ├─ @rollup/plugin-node-resolve@npm:^15.0.0 → npm:15.2.3
│     ├─ @rollup/plugin-yaml@npm:^4.0.0 → npm:4.1.1
│     ├─ @spotify/eslint-config-base@npm:^15.0.0 → npm:15.0.0
│     ├─ @spotify/eslint-config-react@npm:^15.0.0 → npm:15.0.0
│     ├─ @spotify/eslint-config-typescript@npm:^15.0.0 → npm:15.0.0
│     ├─ @sucrase/webpack-loader@npm:^2.0.0 → npm:2.0.0
│     ├─ @svgr/core@npm:6.5.x → npm:6.5.1
│     ├─ @svgr/plugin-jsx@npm:6.5.x → npm:6.5.1
│     ├─ @svgr/plugin-svgo@npm:6.5.x → npm:6.5.1
│     ├─ @svgr/rollup@npm:6.5.x → npm:6.5.1
│     ├─ @svgr/webpack@npm:6.5.x → npm:6.5.1
│     ├─ @swc/core@npm:^1.3.46 → npm:1.3.86
│     ├─ @swc/helpers@npm:^0.5.0 → npm:0.5.2
│     ├─ @swc/jest@npm:^0.2.22 → npm:0.2.29
│     ├─ @types/jest@npm:^29.5.11 → npm:29.5.11
│     ├─ @types/webpack-env@npm:^1.15.2 → npm:1.18.1
│     ├─ @typescript-eslint/eslint-plugin@npm:^8.17.0 → npm:8.23.0
│     ├─ @typescript-eslint/parser@npm:^8.16.0 → npm:8.23.0
│     ├─ @yarnpkg/lockfile@npm:^1.1.0 → npm:1.1.0
│     ├─ @yarnpkg/parsers@npm:^3.0.0 → npm:3.0.2
│     ├─ bfj@npm:^8.0.0 → npm:8.0.0
│     ├─ buffer@npm:^6.0.3 → npm:6.0.3
│     ├─ chalk@npm:^4.0.0 → npm:4.1.2
│     ├─ chokidar@npm:^3.3.1 → npm:3.6.0
│     ├─ commander@npm:^12.0.0 → npm:12.0.0
│     ├─ cross-fetch@npm:^4.0.0 → npm:4.0.0
│     ├─ cross-spawn@npm:^7.0.3 → npm:7.0.6
│     ├─ css-loader@npm:^6.5.1 → npm:6.11.0
│     ├─ ctrlc-windows@npm:^2.1.0 → npm:2.1.0
│     ├─ esbuild-loader@npm:^4.0.0 → npm:4.0.3
│     ├─ esbuild@npm:^0.25.0 → npm:0.25.2
│     ├─ eslint-config-prettier@npm:^9.0.0 → npm:9.1.0
│     ├─ eslint-formatter-friendly@npm:^7.0.0 → npm:7.0.0
│     ├─ eslint-plugin-deprecation@npm:^3.0.0 → npm:3.0.0
│     ├─ eslint-plugin-import@npm:^2.31.0 → npm:2.31.0
│     ├─ eslint-plugin-jest@npm:^28.9.0 → npm:28.11.0
│     ├─ eslint-plugin-jsx-a11y@npm:^6.10.2 → npm:6.10.2
│     ├─ eslint-plugin-react-hooks@npm:^5.0.0 → npm:5.1.0
│     ├─ eslint-plugin-react@npm:^7.37.2 → npm:7.37.4
│     ├─ eslint-plugin-unused-imports@npm:^4.1.4 → npm:4.1.4
│     ├─ eslint-webpack-plugin@npm:^4.2.0 → npm:4.2.0
│     ├─ eslint@npm:^8.6.0 → npm:8.49.0
│     ├─ express@npm:^4.17.1 → npm:4.21.2
│     ├─ fork-ts-checker-webpack-plugin@npm:^9.0.0 → npm:9.0.2
│     ├─ fs-extra@npm:^11.2.0 → npm:11.2.0
│     ├─ git-url-parse@npm:^15.0.0 → npm:15.0.0
│     ├─ glob@npm:^7.1.7 → npm:7.2.3
│     ├─ global-agent@npm:^3.0.0 → npm:3.0.0
│     ├─ globby@npm:^11.1.0 → npm:11.1.0
│     ├─ handlebars@npm:^4.7.3 → npm:4.7.8
│     ├─ html-webpack-plugin@npm:^5.6.3 → npm:5.6.3
│     ├─ inquirer@npm:^8.2.0 → npm:8.2.6
│     ├─ jest-cli@npm:^29.7.0 → npm:29.7.0
│     ├─ jest-css-modules@npm:^2.1.0 → npm:2.1.0
│     ├─ jest-environment-jsdom@npm:^29.0.2 → npm:29.7.0
│     ├─ jest-runtime@npm:^29.0.2 → npm:29.7.0
│     ├─ jest@npm:^29.7.0 → npm:29.7.0
│     ├─ json-schema@npm:^0.4.0 → npm:0.4.0
│     ├─ lodash@npm:^4.17.21 → npm:4.17.21
│     ├─ mini-css-extract-plugin@npm:^2.4.2 → npm:2.7.6
│     ├─ minimatch@npm:^9.0.0 → npm:9.0.5
│     ├─ node-stdlib-browser@npm:^1.3.1 → npm:1.3.1
│     ├─ npm-packlist@npm:^5.0.0 → npm:5.1.3
│     ├─ ora@npm:^5.3.0 → npm:5.4.1
│     ├─ p-queue@npm:^6.6.2 → npm:6.6.2
│     ├─ pirates@npm:^4.0.6 → npm:4.0.6
│     ├─ postcss@npm:^8.1.0 → npm:8.4.49
│     ├─ process@npm:^0.11.10 → npm:0.11.10
│     ├─ raw-loader@npm:^4.0.2 → npm:4.0.2
│     ├─ react-dev-utils@npm:^12.0.0-next.60 → npm:12.0.1
│     ├─ react-refresh@npm:^0.17.0 → npm:0.17.0
│     ├─ recursive-readdir@npm:^2.2.2 → npm:2.2.3
│     ├─ replace-in-file@npm:^7.1.0 → npm:7.1.0
│     ├─ rollup-plugin-dts@npm:^6.1.0 → npm:6.1.0
│     ├─ rollup-plugin-esbuild@npm:^6.1.1 → npm:6.1.1
│     ├─ rollup-plugin-postcss@npm:^4.0.0 → npm:4.0.2
│     ├─ rollup-pluginutils@npm:^2.8.2 → npm:2.8.2
│     ├─ rollup@npm:^4.27.3 → npm:4.27.3
│     ├─ semver@npm:^7.5.3 → npm:7.6.3
│     ├─ style-loader@npm:^3.3.1 → npm:3.3.3
│     ├─ sucrase@npm:^3.20.2 → npm:3.34.0
│     ├─ swc-loader@npm:^0.2.3 → npm:0.2.3
│     ├─ tar@npm:^6.1.12 → npm:6.2.1
│     ├─ terser-webpack-plugin@npm:^5.1.3 → npm:5.3.10
│     ├─ ts-morph@npm:^24.0.0 → npm:24.0.0
│     ├─ undici@npm:^7.2.3 → npm:7.3.0
│     ├─ util@npm:^0.12.3 → npm:0.12.5
│     ├─ webpack-dev-server@npm:^5.0.0 → npm:5.2.2
│     ├─ webpack@npm:^5.94.0 → npm:5.96.1
│     ├─ yaml@npm:^2.0.0 → npm:2.3.2
│     ├─ yargs@npm:^16.2.0 → npm:16.2.0
│     ├─ yml-loader@npm:^2.1.0 → npm:2.1.0
│     ├─ yn@npm:^4.0.0 → npm:4.0.0
│     ├─ zod-validation-error@npm:^3.4.0 → npm:3.4.0
│     └─ zod@npm:^3.22.4 → npm:3.23.8
│
├─ dd-trace@npm:5.4.0
│  ├─ Version: 5.4.0
│  │ 
│  └─ Dependencies
│     ├─ @datadog/native-appsec@npm:7.0.0 → npm:7.0.0
│     ├─ @datadog/native-iast-rewriter@npm:2.2.3 → npm:2.2.3
│     ├─ @datadog/native-iast-taint-tracking@npm:1.7.0 → npm:1.7.0
│     ├─ @datadog/native-metrics@npm:^2.0.0 → npm:2.0.0
│     ├─ @datadog/pprof@npm:5.0.0 → npm:5.0.0
│     ├─ @datadog/sketches-js@npm:^2.1.0 → npm:2.1.0
│     ├─ @opentelemetry/api@npm:^1.0.0 → npm:1.9.0
│     ├─ crypto-randomuuid@npm:^1.0.0 → npm:1.0.0
│     ├─ dc-polyfill@npm:^0.1.4 → npm:0.1.4
│     ├─ ignore@npm:^5.2.4 → npm:5.3.2
│     ├─ import-in-the-middle@npm:^1.7.3 → npm:1.7.3
│     ├─ int64-buffer@npm:^0.1.9 → npm:0.1.10
│     ├─ ipaddr.js@npm:^2.1.0 → npm:2.1.0
│     ├─ istanbul-lib-coverage@npm:3.2.0 → npm:3.2.0
│     ├─ jest-docblock@npm:^29.7.0 → npm:29.7.0
│     ├─ koalas@npm:^1.0.2 → npm:1.0.2
│     ├─ limiter@npm:1.1.5 → npm:1.1.5
│     ├─ lodash.sortby@npm:^4.7.0 → npm:4.7.0
│     ├─ lru-cache@npm:^7.14.0 → npm:7.18.3
│     ├─ methods@npm:^1.1.2 → npm:1.1.2
│     ├─ module-details-from-path@npm:^1.0.3 → npm:1.0.3
│     ├─ msgpack-lite@npm:^0.1.26 → npm:0.1.26
│     ├─ node-abort-controller@npm:^3.1.1 → npm:3.1.1
│     ├─ opentracing@npm:>=0.12.1 → npm:0.14.7
│     ├─ path-to-regexp@npm:^0.1.2 → npm:0.1.12
│     ├─ pprof-format@npm:^2.0.7 → npm:2.0.7
│     ├─ protobufjs@npm:^7.2.5 → npm:7.2.6
│     ├─ retry@npm:^0.13.1 → npm:0.13.1
│     ├─ semver@npm:^7.5.4 → npm:7.6.3
│     ├─ shell-quote@npm:^1.8.1 → npm:1.8.1
│     ├─ tlhunter-sorted-set@npm:^0.1.0 → npm:0.1.0
│     └─ @opentelemetry/core@npm:^1.14.0 → npm:1.17.0 [d1bea]
│
├─ prettier@npm:3.3.3
│  ├─ Version: 3.3.3
│  │ 
│  └─ Exported Binaries
│     └─ prettier
│
├─ root@workspace:.
│  ├─ Version: 1.0.0
│  │ 
│  └─ Dependencies
│     ├─ dd-trace@npm:^5.4.0 → npm:5.4.0
│     ├─ prettier@npm:^3.0.0 → npm:3.3.3
│     ├─ touch@npm:^3.1.0 → npm:3.1.0
│     ├─ typescript@patch:typescript@npm%3A~5.5.0#optional!builtin<compat/typescript> → patch:typescript@npm%3A5.5.4#optional!builtin<compat/typescript>::version=5.5.4&hash=379a07
│     ├─ undici@npm:^5.29.0 → npm:5.29.0
│     └─ @backstage/cli@backstage:^::backstage=1.40.2&npm=0.33.0 → npm:0.33.0 [36a01]
│
├─ touch@npm:3.1.0
│  ├─ Version: 3.1.0
│  │ 
│  ├─ Exported Binaries
│  │  └─ nodetouch
│  │ 
│  └─ Dependencies
│     └─ nopt@npm:~1.0.10 → npm:1.0.10
│
├─ typescript@patch:typescript@npm%3A5.5.4#optional!builtin<compat/typescript>::version=5.5.4&hash=379a07
│  ├─ Version: 5.5.4
│  │ 
│  └─ Exported Binaries
│     ├─ tsc
│     └─ tsserver
│
└─ undici@npm:5.29.0
   ├─ Version: 5.29.0
   │ 
   └─ Dependencies
      └─ @fastify/busboy@npm:^2.0.0 → npm:2.0.0
```
