### ISSUE TITLE
🐛 Bug Report: Upgrading catalog plugin throws error on backend startup: TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by jgrumboe** [backstage/backstage#27242]
### 📜 Description

Following the upgrade guide and upgrade helper, I want to upgrade from 1.30.4 to 1.32.2.

I can upgrade all modules and plugins, except the plugin-catalog-backend.
After upgrading from 1.25.2 to 1.27.1 the following error is thrown when I run `yarn workspace backend start`.

```
❯ yarn workspace backend start
Loading config from MergedConfigSource{FileConfigSource{path="/Users/jgrumboeck/app-cloud-backstage/app-config.yaml"}, FileConfigSource{path="/Users/jgrumboeck/app-cloud-backstage/app-config.local.yaml"}, EnvConfigSource{count=0}}
2024-10-18T08:16:11.970Z backstage info Found 8 new secrets in config that will be redacted 
2024-10-18T08:16:11.976Z rootHttpRouter info Listening on 0.0.0.0:7007 
2024-10-18T08:16:11.977Z backstage info Plugin initialization started: 'app', 'events', 'proxy', 'techdocs', 'scaffolder', 'auth', 'search', 'catalog', 'permission', 'devtools' type=initialization
2024-10-18T08:16:12.024Z backstage error Plugin 'catalog' thew an error during startup, waiting for 9 other plugins to finish before shutting down the process type=initialization
2024-10-18T08:16:12.030Z search warn Postgres search engine is not supported, skipping registration of search-backend-module-pg 
2024-10-18T08:16:12.050Z auth info Configuring "database" as KeyStore provider 
2024-10-18T08:16:12.051Z events info Database is not PostgreSQL, using memory store 
2024-10-18T08:16:12.129Z techdocs info Creating Local publisher for TechDocs 
2024-10-18T08:16:12.132Z scaffolder info Starting scaffolder with the following actions enabled github:actions:dispatch, github:autolinks:create, github:deployKey:create, github:environment:create, github:issues:label, github:repo:create, github:repo:push, github:webhook, publish:github, publish:github:pull-request, github:pages:enable, github:branch-protection:create, http:backstage:request, fetch:plain, fetch:plain:file, fetch:template, fetch:template:file, debug:log, debug:wait, catalog:register, catalog:fetch, catalog:write, fs:delete, fs:rename 
2024-10-18T08:16:12.133Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog 
2024-10-18T08:16:12.133Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs 
2024-10-18T08:16:12.192Z app info Serving static app content from /Users/jgrumboeck/app-cloud-backstage/packages/app/dist 
2024-10-18T08:16:12.200Z auth info Configuring auth provider: github 
2024-10-18T08:16:12.201Z auth info Configuring auth provider: microsoft 
2024-10-18T08:16:12.322Z app info Replacing injected env config in module-backstage.c83a3df5.js entry=main
2024-10-18T08:16:12.327Z app info Storing 0 updated assets and 318 new assets 
/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297
                provides: Array.from(moduleInit.consumes).map(c => c.id),
                                                                     ^


TypeError: Cannot read properties of undefined (reading 'id')
    at <anonymous> (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297:70)
    at Array.map (<anonymous>)
    at <anonymous> (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297:59)
    at Array.map (<anonymous>)
    at <anonymous> (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:291:35)
    at async Promise.allSettled (index 7)
    at BackendInitializer.#doStart (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:278:21)
    at BackendInitializer.start (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
    at BackstageBackend.start (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)

Node.js v18.18.2
^C%                                                                                                     
```

### 👍 Expected behavior

The backend should start without error.

### 👎 Actual Behavior with Screenshots

```
❯ yarn workspace backend start
Loading config from MergedConfigSource{FileConfigSource{path="/Users/jgrumboeck/app-cloud-backstage/app-config.yaml"}, FileConfigSource{path="/Users/jgrumboeck/app-cloud-backstage/app-config.local.yaml"}, EnvConfigSource{count=0}}
2024-10-18T08:16:11.970Z backstage info Found 8 new secrets in config that will be redacted 
2024-10-18T08:16:11.976Z rootHttpRouter info Listening on 0.0.0.0:7007 
2024-10-18T08:16:11.977Z backstage info Plugin initialization started: 'app', 'events', 'proxy', 'techdocs', 'scaffolder', 'auth', 'search', 'catalog', 'permission', 'devtools' type=initialization
2024-10-18T08:16:12.024Z backstage error Plugin 'catalog' thew an error during startup, waiting for 9 other plugins to finish before shutting down the process type=initialization
2024-10-18T08:16:12.030Z search warn Postgres search engine is not supported, skipping registration of search-backend-module-pg 
2024-10-18T08:16:12.050Z auth info Configuring "database" as KeyStore provider 
2024-10-18T08:16:12.051Z events info Database is not PostgreSQL, using memory store 
2024-10-18T08:16:12.129Z techdocs info Creating Local publisher for TechDocs 
2024-10-18T08:16:12.132Z scaffolder info Starting scaffolder with the following actions enabled github:actions:dispatch, github:autolinks:create, github:deployKey:create, github:environment:create, github:issues:label, github:repo:create, github:repo:push, github:webhook, publish:github, publish:github:pull-request, github:pages:enable, github:branch-protection:create, http:backstage:request, fetch:plain, fetch:plain:file, fetch:template, fetch:template:file, debug:log, debug:wait, catalog:register, catalog:fetch, catalog:write, fs:delete, fs:rename 
2024-10-18T08:16:12.133Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog 
2024-10-18T08:16:12.133Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs 
2024-10-18T08:16:12.192Z app info Serving static app content from /Users/jgrumboeck/app-cloud-backstage/packages/app/dist 
2024-10-18T08:16:12.200Z auth info Configuring auth provider: github 
2024-10-18T08:16:12.201Z auth info Configuring auth provider: microsoft 
2024-10-18T08:16:12.322Z app info Replacing injected env config in module-backstage.c83a3df5.js entry=main
2024-10-18T08:16:12.327Z app info Storing 0 updated assets and 318 new assets 
/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297
                provides: Array.from(moduleInit.consumes).map(c => c.id),
                                                                     ^


TypeError: Cannot read properties of undefined (reading 'id')
    at <anonymous> (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297:70)
    at Array.map (<anonymous>)
    at <anonymous> (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297:59)
    at Array.map (<anonymous>)
    at <anonymous> (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:291:35)
    at async Promise.allSettled (index 7)
    at BackendInitializer.#doStart (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:278:21)
    at BackendInitializer.start (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
    at BackstageBackend.start (/Users/jgrumboeck/app-cloud-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)

Node.js v18.18.2
^C%                                                                                                     
```

### 👟 Reproduction steps

1. upgrade all packages except plugin-catalog-* with `yarn backstage-cli versions:bump ....``
2. verify `yarn workspace backend start` is still working fine
3. run `yarn backstage-cli versions:bump --pattern '@backstage/plugin-catalog*'
4. `yarn workspace backend start`is failing

### 🖥️ Your Environment

❯ yarn backstage-cli info                                                
OS:   Darwin 23.6.0 - darwin/arm64
node: v18.18.2
yarn: 4.4.1
cli:  0.27.0 (installed)
backstage:  1.30.4

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.9.3, 1.0.1
  @backstage/backend-common                                        0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.4.4, 0.5.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.2.0
  @backstage/backend-plugin-api                                    0.8.1, 1.0.1
  @backstage/catalog-client                                        1.6.6, 1.7.1
  @backstage/catalog-model                                         1.6.0, 1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7, 0.2.9
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0, 1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2, 1.15.1
  @backstage/core-compat-api                                       0.2.8, 0.3.1
  @backstage/core-components                                       0.14.10, 0.15.1
  @backstage/core-plugin-api                                       1.10.0, 1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-app-api                                      0.10.0
  @backstage/frontend-defaults                                     0.1.1
  @backstage/frontend-plugin-api                                   0.7.0, 0.8.0, 0.9.0
  @backstage/frontend-test-utils                                   0.2.1
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30, 1.2.0
  @backstage/integration                                           1.14.0, 1.15.1
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.76
  @backstage/plugin-app-node                                       0.1.26
  @backstage/plugin-app                                            0.1.1
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.1
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.1
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.1
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.1
  @backstage/plugin-auth-backend-module-github-provider            0.2.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.1
  @backstage/plugin-auth-backend-module-google-provider            0.2.1
  @backstage/plugin-auth-backend-module-guest-provider             0.2.1
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.1
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.1
  @backstage/plugin-auth-backend-module-okta-provider              0.1.1
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.1
  @backstage/plugin-auth-backend                                   0.23.1
  @backstage/plugin-auth-node                                      0.5.1, 0.5.3
  @backstage/plugin-auth-react                                     0.1.7
  @backstage/plugin-bitbucket-cloud-common                         0.2.22, 0.2.24
  @backstage/plugin-catalog-backend-module-github                  0.7.6
  @backstage/plugin-catalog-backend-module-logs                    0.1.3
  @backstage/plugin-catalog-backend-module-msgraph                 0.6.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.22, 0.2.1
  @backstage/plugin-catalog-backend                                1.27.1
  @backstage/plugin-catalog-common                                 1.0.26, 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.11
  @backstage/plugin-catalog-import                                 0.12.5
  @backstage/plugin-catalog-node                                   1.12.6, 1.13.1
  @backstage/plugin-catalog-react                                  1.12.3, 1.14.0
  @backstage/plugin-catalog                                        1.22.0, 1.24.0
  @backstage/plugin-devtools-backend                               0.4.1
  @backstage/plugin-devtools-common                                0.1.12
  @backstage/plugin-devtools                                       0.1.19
  @backstage/plugin-events-backend                                 0.3.14
  @backstage/plugin-events-node                                    0.3.10, 0.4.2
  @backstage/plugin-github-actions                                 0.6.16
  @backstage/plugin-home-react                                     0.1.16
  @backstage/plugin-home                                           0.7.9
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.1
  @backstage/plugin-permission-backend                             0.5.50
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.2, 0.8.4
  @backstage/plugin-permission-react                               0.4.25, 0.4.27
  @backstage/plugin-proxy-backend                                  0.5.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.16, 0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.14, 0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.14, 0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.14, 0.3.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.16, 0.2.1
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.14, 0.2.1
  @backstage/plugin-scaffolder-backend-module-github               0.4.2, 0.5.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.6, 0.6.0
  @backstage/plugin-scaffolder-backend                             1.24.1, 1.26.2
  @backstage/plugin-scaffolder-common                              1.5.5, 1.5.6
  @backstage/plugin-scaffolder-node                                0.4.10, 0.5.0
  @backstage/plugin-scaffolder-react                               1.13.1
  @backstage/plugin-scaffolder                                     1.26.1
  @backstage/plugin-search-backend-module-catalog                  0.2.4
  @backstage/plugin-search-backend-module-pg                       0.5.37
  @backstage/plugin-search-backend-module-techdocs                 0.3.1
  @backstage/plugin-search-backend-node                            1.3.4
  @backstage/plugin-search-backend                                 1.6.1
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14, 1.8.1
  @backstage/plugin-search                                         1.4.18
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.11.1
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.16
  @backstage/plugin-techdocs-node                                  1.12.12
  @backstage/plugin-techdocs-react                                 1.2.9
  @backstage/plugin-techdocs                                       1.11.0
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10, 1.7.0
  @backstage/theme                                                 0.5.6, 0.6.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.10, 1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by mepperla** [comment]
`[1] Backend failed to start up TypeError: Cannot read properties of undefined (reading 'id')
[1]     at <anonymous> (/Users/vsm291/Documents/TDP/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297:70)
[1]     at Array.map (<anonymous>)
[1]     at <anonymous> (/Users/vsm291/Documents/TDP/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297:59)
[1]     at Array.map (<anonymous>)
[1]     at <anonymous> (/Users/vsm291/Documents/TDP/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:291:35)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async Promise.allSettled (index 2)
[1]     at BackendInitializer.#doStart (/Users/vsm291/Documents/TDP/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:278:21)
[1]     at BackendInitializer.start (/Users/vsm291/Documents/TDP/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
[1]     at BackstageBackend.start (/Users/vsm291/Documents/TDP/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)
[0] webpack compiled successfully`

**Comment by mepperla** [comment]
`[1] Backend failed to start up TypeError: Cannot read properties of undefined (reading 'id')
[1]     at <anonymous> (**redacted**/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297:70)
[1]     at Array.map (<anonymous>)
[1]     at <anonymous> (**redacted**/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297:59)
[1]     at Array.map (<anonymous>)
[1]     at <anonymous> (**redacted**/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:291:35)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async Promise.allSettled (index 2)
[1]     at BackendInitializer.#doStart (**redacted**/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:278:21)
[1]     at BackendInitializer.start (**redacted**/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
[1]     at BackstageBackend.start (**redacted**/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)
[0] webpack compiled successfully`

I am also seeing a similar error.

**Comment by jwnmulder** [comment]
Had the same issue. On our side the root cause was wrong imports. Running `yarn tsc` showed the error

**Comment by jgrumboe** [comment]
@jwnmulder Thank you very much for the hint!
Yes, `yarn tsc` showed errors with a custom sign-in resolver. After resolving them, the backend started successfully.

I'm closing the issue.

**Comment by faiz-kpit** [comment]
Encountering an initialization error: Plugin 'scaffolder' threw an error during startup, waiting for 4 other plugins to finish before shutting down the process when upgrading Backstage from version 1.33.0 to 1.34.2 using **yarn backstage-cli versions:bump --release 1.34.2** with Node v22.13.1 and Yarn 4.4.1."


[backend]: 2025-05-06T07:00:52.805Z techdocs info Creating Local publisher for TechDocs 
[backend]: 2025-05-06T07:00:52.808Z backstage error Plugin 'scaffolder' thew an error during startup, waiting for 4 other plugins to finish before shutting down the process type=initialization
[backend]: 2025-05-06T07:00:52.809Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog 
[backend]: 2025-05-06T07:00:52.809Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs 
[backend]: 2025-05-06T07:00:52.814Z catalog info Performing database migration 
[backend]: 2025-05-06T07:00:52.967Z catalog info Created new signing key 6af3f20a-7157-46e5-b7ad-d5e8d1e61dc7 
[backend]: 2025-05-06T07:00:52.995Z auth info Configuring auth provider: guest 
[backend]: /home/faizk/ros-mil-BS-1_34_2/backstage-gen2-elite-cl-ros-mils/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:205
[backend]:       throw new Error(
[backend]:             ^
[backend]: 
[backend]: 
[backend]: Error: Service or extension point dependencies of plugin 'scaffolder' are missing for the following ref(s): serviceRef{core.auditor}
[backend]:     at BackendInitializer.#getInitDeps (/home/faizk/ros-mil-BS-1_34_2/backstage-gen2-elite-cl-ros-mils/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:205:13)
[backend]:     at async <anonymous> (/home/faizk/ros-mil-BS-1_34_2/backstage-gen2-elite-cl-ros-mils/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:391:32)
[backend]:     at async Promise.allSettled (index 2)
[backend]:     at async BackendInitializer.#doStart (/home/faizk/ros-mil-BS-1_34_2/backstage-gen2-elite-cl-ros-mils/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:340:21)
[backend]:     at async BackendInitializer.start (/home/faizk/ros-mil-BS-1_34_2/backstage-gen2-elite-cl-ros-mils/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:245:5)
[backend]:     at async BackstageBackend.start (/home/faizk/ros-mil-BS-1_34_2/backstage-gen2-elite-cl-ros-mils/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)
