### ISSUE TITLE
🐛 Bug Report: GitHub org fetching fails intermittently for large orgs 

### ISSUE THREAD

**Issue by stephenglass** [backstage/backstage#27284]
### 📜 Description

Here at AT&T we are working towards getting Backstage ready for production, which means configuring it to use some of our main (and larger) GitHub orgs i.e > 10K GitHub users, > 5K teams. We have been using smaller test organizations in our development and local environments with no issues. However, we quickly noticed when using the larger GitHub orgs the data loading process fails very often at some random time during the process (maybe like 75% of the time?) with a `HttpError: fetch failed` error. We are using GitHub enterprise cloud hosted by GitHub (not self-hosted enterprise server).

Additionally, when this error occurs none of the org data that was fetched up to the point of failure are committed to the catalog (i.e. no exception handling). This is quite unfortunate because for large GitHub orgs the loading process can take close to 30 minutes in our testing.

We are configured behind a corporate proxy but I don't believe the issue lays with our configuration because as mentioned this is an intermittent issue (it doesn't always happen and does not occur when using smaller orgs).

We also do not think it is rate limiting because after encountering this error, we use the same token to make a request to GitHub, inspect the headers and confirmed have not reached the rate limit.

I'll be debugging this further by trying to add more verbose logging in the `node_modules` for `@backstage/plugin-catalog-backend-module-github/src/lib/github.ts` and perhaps in the Octokit request library to try and see what is actually causing the error.

### 👍 Expected behavior

Fetch org data from large orgs with no errors.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/a78aac56-c285-45fd-8e06-5db2c34a20dd)

### 👟 Reproduction steps

Configure a `githubOrg` in `app-config.yaml` to pull from a large GitHub organization

### 🖥️ Your Environment

- Backstage v1.32.2
- NodeJS v20
- Configured for corporate proxy using `global-agent` and `undici`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @stephenglass, just popping this on your radar, it's not exactly the same but there was some work to fix it and perhaps you've found something that got missed: https://github.com/backstage/backstage/issues/22222

**Comment by awanlin** [comment]
The part of this I would be looking at is here:

https://github.com/backstage/backstage/blob/16a6771821ba8a11c16e8b64a66fadb29ea5edf7/plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts#L320-L329

It waits for all the data to be available and then does a full mutation. Perhaps using the events features could help but you still need to get that initial load in for that to work well. Maybe along with an incremental entity provider? https://backstage.io/docs/features/software-catalog/external-integrations#writing-an-incremental-entity-provider

**Comment by stephenglass** [comment]
Still debugging this. I've modified the `queryWithPaging` method in `node_modules/@backstage/plugin-catalog-backend-module-github/dist/lib/github.cjs.js` to add a try/catch around the graphql query and log the exception. Eventually got the exception caught as shown here:

```
[backend]: Error:
[backend]: RequestError [HttpError]: fetch failed
[backend]:     at /workspaces/backstage/node_modules/@octokit/request/dist-node/index.js:146:11
[backend]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[backend]:     at queryWithPaging (/workspaces/backstage/node_modules/@backstage/plugin-catalog-backend-module-github/src/lib/github.ts:670:23)
[backend]:     at getTeamMembers (/workspaces/backstage/node_modules/@backstage/plugin-catalog-backend-module-github/src/lib/github.ts:651:16)
[backend]:     at materialisedTeams (/workspaces/backstage/node_modules/@backstage/plugin-catalog-backend-module-github/src/lib/github.ts:249:3)
[backend]:     at queryWithPaging (/workspaces/backstage/node_modules/@backstage/plugin-catalog-backend-module-github/src/lib/github.ts:687:20)
[backend]:     at Object.getOrganizationTeams (/workspaces/backstage/node_modules/@backstage/plugin-catalog-backend-module-github/src/lib/github.ts:271:17)
[backend]:     at GithubMultiOrgEntityProvider.read (/workspaces/backstage/node_modules/@backstage/plugin-catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts:289:25)
[backend]:     at Object.fn (/workspaces/backstage/node_modules/@backstage/plugin-catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts:839:13)
[backend]:     at <anonymous> (/workspaces/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/PluginTaskSchedulerImpl.ts:154:19)
[backend]:     at TaskWorker.fn (/workspaces/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/PluginTaskSchedulerImpl.ts:151:9)
[backend]:     at TaskWorker.runOnce (/workspaces/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/TaskWorker.ts:156:13)
[backend]:     at <anonymous> (/workspaces/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/TaskWorker.ts:76:31) {
[backend]:   status: 500,
[backend]:   request: {
[backend]:     method: 'POST',
[backend]:     url: 'https://api.github.com/graphql',
[backend]:     headers: {
[backend]:       accept: 'application/vnd.github.v3+json',
[backend]:       'user-agent': 'octokit-graphql.js/5.0.6 Node.js/20.16.0 (linux; x64)',
[backend]:       authorization: 'Bearer [REDACTED]',
[backend]:       'content-type': 'application/json; charset=utf-8'
[backend]:     },
[backend]:     body: '{"query":"\\n    query members($org: String!, $teamSlug: String!, $cursor: String) {\\n      organization(login: $org) {\\n        team(slug: $teamSlug) {\\n          members(first: 100, after: $cursor, membership: IMMEDIATE) {\\n            pageInfo { hasNextPage, endCursor }\\n            nodes { login }\\n          }\\n        }\\n      }\\n    }","variables":{"org":"myorg","teamSlug":"myteamslug"}}'
[backend]:   }
[backend]: }
```

As soon as I got the error I checked GitHub rate limits and was not exceeding any limit. Then I went an manually made the failed Graphql call to GitHub and it returned back a success just fine.

I'll attempt to insert some more verbose logs in the Octokit requests library to see if I can determine what the cause is because even catching the exception doesn't explain what the error is.

**Comment by stephenglass** [comment]
After some more debugging and discussing with other teams we're fairly confident the error stems from an internal network/proxy issue. However, I think it makes sense to add some exception handling in Backstage because as mentioned if there is any error thrown the entire data loading process terminates.

I'll be able to make a PR but I would appreciate some feedback on what approach to take. Some potential options:
- (exponential) retry for failed requests before terminating. 
- on exception return the data that we've gathered up to the point of error. If we do this then will anything that we didn't fetch be scheduled for deletion from the catalog?

**Comment by camilaibs** [comment]
Hi @stephenglass,
We discussed your suggestions and here are the team initial thoughts 🙂 :

> (exponential) retry for failed requests before terminating.

It may be possible to consider retries, but in a rate limit situation it might make things worse unless retries occur in batches that are time spaced widely apart.

>If we do this then will anything that we didn't fetch be scheduled for deletion from the catalog?

It would delete things.

**Comment by stephenglass** [comment]
Makes sense. I would propose [exponential backoff ](https://en.m.wikipedia.org/wiki/Exponential_backoff) retries which would prevent additional rate limit errors from occurring. And then three additional config values:

- `retry.exponential.baseDelay`: Amount of time(Duration) to wait between retry attempts.
- `retry.exponential.maxDelay`: Maximum permissible amount of time(duration) between retry attempts.
- `retry.exponential.maxRetries`: The maximum number of attempts.
