### ISSUE TITLE
🐛 Bug Report: While deploying into docker container, getting an  Error: ExtensionPoint with ID 'catalog.processing' is already registered

### ISSUE THREAD

**Issue by satyareddym** [backstage/backstage#27357]
### 📜 Description

When I try to deploy using docker run
#docker run -it -p 7007:7007 backstage
run into issue saying

--------------------------------------------
Loading config from MergedConfigSource{FileConfigSource{path="/app/app-config.yaml"}, FileConfigSource{path="/app/app-config.production.yaml"}, EnvConfigSource{count=0}}
{"level":"info","message":"Found 0 new secrets in config that will be redacted","service":"backstage"}
{"level":"info","message":"Listening on :7007","service":"rootHttpRouter"}
/app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:149
              throw new Error(
                    ^

Error: ExtensionPoint with ID 'catalog.processing' is already registered
    at #doStart (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:149:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BackendInitializer.start (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:120:5)
    at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackstageBackend.cjs.js:19:5)

Node.js v20.18.0
--------------------------------------------------

### 👍 Expected behavior

It should have created a container

### 👎 Actual Behavior with Screenshots

Loading config from MergedConfigSource{FileConfigSource{path="/app/app-config.yaml"}, FileConfigSource{path="/app/app-config.production.yaml"}, EnvConfigSource{count=0}}
{"level":"info","message":"Found 0 new secrets in config that will be redacted","service":"backstage"}
{"level":"info","message":"Listening on :7007","service":"rootHttpRouter"}
/app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:149
              throw new Error(
                    ^

Error: ExtensionPoint with ID 'catalog.processing' is already registered
    at #doStart (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:149:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BackendInitializer.start (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:120:5)
    at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackstageBackend.cjs.js:19:5)

Node.js v20.18.0

### 👟 Reproduction steps

I was able to setup the 'dev' and that worked fine, using cmd "yarn dev"

next, as part of CI deployment, trying to create docker image by following steps given at backstage guide https://backstage.io/docs/deployment/docker

I was able to run 
yarn install --immutable
yarn tsc
yarn build:backend --config ../../app-config.yaml --config ../../app-config.production.yaml
docker image build . -f packages/backend/Dockerfile --tag backstage

then, when I try to run
docker run -it -p 7007:7007 backstage

I get above error.

### 📃 Provide the context for the Bug.

Trying to setup first time.

### 🖥️ Your Environment

Ubuntu latest

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @satyareddym, would you be able to provide us with a repro repository link so that we can clone and run the docker image that throws the error 🙂 ?

**Comment by satyareddym** [comment]
Hi @camilaibs , I'm trying to set this up on my local system, not yet on repo/cloud, hence I cannot share any link. Is there any other way you can help? Thanks for response.

**Comment by freben** [comment]
Can we see your `packages/backend/src/index.ts` file? I'm not entirely sure, but it seems to me that this should only happen if you have an actual duplicate registration happening.

**Comment by satyareddym** [comment]
Thanks for the response. I was trying different options and noticed it could be due to firewall connectivity reason. Could you pls confirm and do u have any suggestion on how to update it with the local docker registry that we have?  Not sure if there is any trick for such local docker registry cases, as we are not allowed to connect to external registry directly. 


$ sudo docker image build . -f packages/backend/Dockerfile --tag backstage
[+] Building 0.1s (3/3) FINISHED                                                        docker:default
 => [internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 2.98kB                                                            0.0s
 => [internal] load .dockerignore                                                                 0.0s
 => => transferring context: 153B                                                                 0.0s
 => ERROR [internal] load metadata for docker.io/library/node:20-bookworm-slim                    0.1s
------
 > [internal] load metadata for docker.io/library/node:20-bookworm-slim:
------
Dockerfile:12
--------------------
  10 |     # Once the commands have been run, you can build the image using `yarn build-image`
  11 |
  12 | >>> FROM node:20-bookworm-slim
  13 |
  14 |     # Set Python interpreter for `node-gyp` to use
--------------------
ERROR: failed to solve: node:20-bookworm-slim: failed to do request: Head "https://registry-1.docker.io/v2/library/node/manifests/20-bookworm-slim": http: server gave HTTP response to HTTPS client

**Comment by satyareddym** [comment]
* Hi!
 *
 * Note that this is an EXAMPLE Backstage backend. Please check the README.
 *


import { createBackend } from '@backstage/backend-defaults';

const backend = createBackend();

backend.add(import('@backstage/plugin-app-backend/alpha'));
backend.add(import('@backstage/plugin-proxy-backend/alpha'));
backend.add(import('@backstage/plugin-scaffolder-backend/alpha'));
backend.add(import('@backstage/plugin-techdocs-backend/alpha'));

// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
// See https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin
backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));
// See https://backstage.io/docs/auth/guest/provider

// catalog plugin
backend.add(import('@backstage/plugin-catalog-backend/alpha'));
backend.add(
  import('@backstage/plugin-catalog-backend-module-scaffolder-entity-model'),
);

// See https://backstage.io/docs/features/software-catalog/configuration#subscribing-to-catalog-errors
backend.add(import('@backstage/plugin-catalog-backend-module-logs'));

// permission plugin
backend.add(import('@backstage/plugin-permission-backend/alpha'));
// See https://backstage.io/docs/permissions/getting-started for how to create your own permission policy
backend.add(
  import('@backstage/plugin-permission-backend-module-allow-all-policy'),
);

// search plugin
backend.add(import('@backstage/plugin-search-backend/alpha'));

// search engine
// See https://backstage.io/docs/features/search/search-engines
backend.add(import('@backstage/plugin-search-backend-module-pg/alpha'));

// search collators
backend.add(import('@backstage/plugin-search-backend-module-catalog/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-techdocs/alpha'));

// kubernetes
backend.add(import('@backstage/plugin-kubernetes-backend/alpha'));

//GitHub
backend.add(import('@backstage/plugin-catalog-backend'));
backend.add(import('@backstage/plugin-catalog-backend-module-github'));


backend.start();

**Comment by satyareddym** [comment]
Thanks for response @freben . Above is the content you had asked for.

**Comment by freben** [comment]
Look closely. You'll see that you add `@backstage/plugin-catalog-backend` twice. Once with `/alpha` at the end, and once without

**Comment by satyareddym** [comment]
Thanks for pointing that out @freben . I have removed the duplicate entry and re-generated image, and I still get the same error unfortunately. I did check if there are any other duplicates, but atleast I couldn't find any.  Same error message. any other hints?

**Comment by jhaals** [comment]
You should be able to reproduce this locally using `yarn dev` and not have to go trough the hassle of building a final container to test. Double check again that you don't have any duplicates and if you don't spot any start with just the catalog backend and gradually add modules. Yarn dev will restart automatically when you save the file so spotting the error should be quick

**Comment by satyareddym** [comment]
Hi @jhaals , "yarn dev" works fine (even now). do not see any error. Also tried with limiting modules and get the same error that I listed. thanks for pitching in...

**Comment by jhaals** [comment]
And you're sure that this is not the old container? I don't see how this could happen unless there are duplicates in the file 🤯 
It would be very helpful if you can reproduce this in a public repository so that we can further debug this issue.
