### ISSUE TITLE
🐛 Bug Report: BackendInitializer Error after backstage-cli versions:bump

### ISSUE THREAD

**Issue by FourShore** [backstage/backstage#27370]
### 📜 Description

After running

```
yarn backstage-cli versions:bump
yarn backstage-cli versions:bump --pattern "@spotify/backstage*"
yarn backstage-cli versions:bump --pattern "@roadiehq/*"
yarn backstage-cli versions:bump --pattern "@pagerduty/*"
```

The build breaks when trying to `yarn dev` with this error

```
[1] 2024-10-24T15:22:58.992Z soundcheck info Soundcheck backend started. 
[1] 2024-10-24T15:22:58.995Z soundcheck info Task worker starting: refresh-applicable-entities, {"version":2,"cadence":"PT30M","initialDelayDuration":"PT5M","timeoutAfterDuration":"PT30M"} task=refresh-applicable-entities
[1] 2024-10-24T15:22:58.998Z rbac info Starting RBACPolicy... 
[1] /Users/.../Documents/repos/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:121
[1]       const ep = this.#extensionPoints.get(ref.id);
[1]                                                ^
[1] 
[1] 
[1] TypeError: Cannot read properties of undefined (reading 'id')
[1]     at BackendInitializer.#getInitDeps (/Users/.../Documents/repos/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:121:48)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at <anonymous> (/Users/.../Documents/repos/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:329:32)
[1]     at async Promise.allSettled (index 13)
[1]     at BackendInitializer.#doStart (/Users/.../Documents/repos/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:278:21)
[1]     at BackendInitializer.start (/Users/.../Documents/repos/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
[1]     at BackstageBackend.start (/Users/.../Documents/repos/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)
[1] 
[1] Node.js v18.19.1

```

### 👍 Expected behavior

build and run successfully

### 👎 Actual Behavior with Screenshots

Build fails with the above error

### 👟 Reproduction steps

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @FourShore, could you provide us with a repro repo so we can try to run it locally? That would be helpful for us to debug the error.

**Comment by famibo** [comment]
Almost the same problem here (BackendInitializer error: Cannot read properties of undefined (reading 'id')) 
after 1.31.3 -> 1.32.3 upgrade (deleting node_modules and yarn install didn't help):

2024-10-28T12:29:00.015Z backstage error Plugin 'catalog' thew an error during startup, waiting for 13 other plugins to finish before shutting down the process type=initialization
2024-10-28T12:29:00.056Z kubernetes info Initializing Kubernetes backend 
2024-10-28T12:29:00.057Z kubernetes info action=LoadingCustomResources numOfCustomResources=0 
2024-10-28T12:29:00.059Z auth info Configuring "database" as KeyStore provider 
2024-10-28T12:29:00.063Z techdocs info Creating Azure Blob Storage Container publisher for TechDocs 
2024-10-28T12:29:00.083Z scaffolder info Starting scaffolder with the following actions enabled publish:azure, github:actions:dispatch, github:autolinks:create, github:deployKey:create, github:environment:create, github:issues:label, github:repo:create, github:repo:push, github:webhook, publish:github, publish:github:pull-request, github:pages:enable, github:branch-protection:create, azure:keyvault:get, azure:pipeline:create, azure:pipeline:permit, azure:pipeline:run, azure:repo:clone, azure:repo:pr, azure:repo:push, azure:workitem:create, azure:workitem:update, fetch:plain:file:try, roadiehq:utils:fs:parse, roadiehq:utils:fs:write, roadiehq:utils:json:merge, roadiehq:utils:jsonata:yaml:transform, roadiehq:utils:merge, roadiehq:utils:serialize:json, roadiehq:utils:serialize:yaml, fetch:plain, fetch:plain:file, fetch:template, fetch:template:file, debug:log, debug:wait, catalog:register, catalog:fetch, catalog:write, fs:delete, fs:rename 
2024-10-28T12:29:00.085Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog 
2024-10-28T12:29:00.085Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs 
2024-10-28T12:29:00.182Z scaffolder info using working directory: /tmp 
2024-10-28T12:29:00.233Z auth info Configuring auth provider: github 
2024-10-28T12:29:00.235Z auth info Configuring auth provider: microsoft 
/Users/.../devhub-app-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297
                provides: Array.from(moduleInit.consumes).map(c => c.id),
                                                                     ^
TypeError: Cannot read properties of undefined (reading 'id')
    at <anonymous> (/Users/.../devhub-app-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297:70)
    at Array.map (<anonymous>)
    at <anonymous> (/Users/.../devhub-app-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:297:59)
    at Array.map (<anonymous>)
    at <anonymous> (/Users/.../devhub-app-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:291:35)
    at async Promise.allSettled (index 3)
    at BackendInitializer.#doStart (/Users/.../devhub-app-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:278:21)
    at BackendInitializer.start (/Users/.../devhub-app-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
    at BackstageBackend.start (/Users/.../devhub-app-backstage/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)

Node.js v20.11.0

**Comment by Rugvip** [comment]
@famibo are you seeing any errors if you run `yarn tsc`?

**Comment by famibo** [comment]
@Rugvip you re right ! This is the same issue as described hier: https://github.com/backstage/backstage/issues/27242

In our case the problem was this wrong (in 1.32.3) import:
import { microsoftGraphOrgEntityProviderTransformExtensionPoint } from '@backstage/plugin-catalog-backend-module-msgraph/alpha';
Should be instead:
import { microsoftGraphOrgEntityProviderTransformExtensionPoint } from '@backstage/plugin-catalog-backend-module-msgraph';

Our backstage app starts now again :-) Many thanks !!!

**Comment by FourShore** [comment]
@camilaibs unfortunately I can not provide a repo but I think we may have resolved it after @Rugvip comment led us to fixing some typescript errors.
