### ISSUE TITLE
🐛 Bug Report: /@backstage/plugin-catalog-backend-module-msgraph -> Unhandled rejection Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by KL2808** [backstage/backstage#27394]
### 📜 Description

After Upgrading to 1.32.3 i get a lot of errors from the msgraph backend plugin. I'm not able to resolve the error...
The errors appear on `yarn dev` but no errors on `yarn tsc`.

I checked for similar issues and tried to follow the solution from them but no luck :I

Thank you for helping guys <3

### 👍 Expected behavior

should work

### 👎 Actual Behavior with Screenshots

```logs
[1] 2024-10-29T15:38:00.451Z backstage error Unhandled rejection Cannot read properties of undefined (reading 'trim') type=unhandledRejection stack=TypeError: Cannot read properties of undefined (reading 'trim')
[1]     at Object.normalizeEntityName (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/helper.ts:24:6)
[1]     at defaultUserTransformer (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/defaultTransformers.ts:131:7)
[1]     at <anonymous> (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/read.ts:497:30)
[1]     at /Users/kevin/Source/fp-sre-backstage/node_modules/p-limit/index.js:23:31
[1]     at run (/Users/kevin/Source/fp-sre-backstage/node_modules/p-limit/index.js:23:43)
[1]     at /Users/kevin/Source/fp-sre-backstage/node_modules/p-limit/index.js:45:20
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1] 2024-10-29T15:38:00.452Z backstage error Unhandled rejection Cannot read properties of undefined (reading 'trim') type=unhandledRejection stack=TypeError: Cannot read properties of undefined (reading 'trim')
[1]     at Object.normalizeEntityName (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/helper.ts:24:6)
[1]     at defaultUserTransformer (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/defaultTransformers.ts:131:7)
[1]     at <anonymous> (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/read.ts:497:30)
[1]     at /Users/kevin/Source/fp-sre-backstage/node_modules/p-limit/index.js:23:31
[1]     at run (/Users/kevin/Source/fp-sre-backstage/node_modules/p-limit/index.js:23:43)
[1]     at /Users/kevin/Source/fp-sre-backstage/node_modules/p-limit/index.js:45:20
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1] 2024-10-29T15:38:00.452Z backstage error Unhandled rejection Cannot read properties of undefined (reading 'trim') type=unhandledRejection stack=TypeError: Cannot read properties of undefined (reading 'trim')
[1]     at Object.normalizeEntityName (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/helper.ts:24:6)
[1]     at defaultUserTransformer (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/defaultTransformers.ts:131:7)
[1]     at <anonymous> (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/read.ts:497:30)
[1]     at /Users/kevin/Source/fp-sre-backstage/node_modules/p-limit/index.js:23:31
[1]     at run (/Users/kevin/Source/fp-sre-backstage/node_modules/p-limit/index.js:23:43)
[1]     at /Users/kevin/Source/fp-sre-backstage/node_modules/p-limit/index.js:45:20
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1] 2024-10-29T15:38:00.452Z backstage error Unhandled rejection Cannot read properties of undefined (reading 'trim') type=unhandledRejection stack=TypeError: Cannot read properties of undefined (reading 'trim')
[1]     at Object.normalizeEntityName (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/helper.ts:24:6)
[1]     at defaultUserTransformer (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/defaultTransformers.ts:131:7)
[1]     at <anonymous> (/Users/kevin/Source/fp-sre-backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/read.ts:497:30)
... and on and on
```

### 👟 Reproduction steps

see environment

### 🖥️ Your Environment

# yarn backstage-cli info
```bash
yarn run v1.22.22
$ /Users/kevin/Source/fp-sre-backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 24.0.0 - darwin/arm64
node: v18.18.2
yarn: 1.22.22
cli:  0.28.1 (installed)
backstage:  1.32.3

Dependencies:
  @backstage/app-defaults                                          1.5.12
  @backstage/backend-app-api                                       0.9.3, 1.0.1
  @backstage/backend-common                                        0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.4.4, 0.5.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.2.0
  @backstage/backend-plugin-api                                    0.8.1, 1.0.1
  @backstage/backend-tasks                                         0.6.1
  @backstage/backend-test-utils                                    1.0.2
  @backstage/catalog-client                                        1.7.1
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.9
  @backstage/cli                                                   0.28.1
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.1
  @backstage/core-compat-api                                       0.2.8, 0.3.1
  @backstage/core-components                                       0.14.10, 0.15.1
  @backstage/core-plugin-api                                       1.10.0
  @backstage/dev-utils                                             1.1.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.0
  @backstage/frontend-defaults                                     0.1.1
  @backstage/frontend-plugin-api                                   0.7.0, 0.9.0
  @backstage/frontend-test-utils                                   0.2.1
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.2.0
  @backstage/integration                                           1.15.1
  @backstage/plugin-api-docs                                       0.11.11
  @backstage/plugin-app-backend                                    0.3.76
  @backstage/plugin-app-node                                       0.1.26
  @backstage/plugin-app                                            0.1.1
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.1
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.1
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.1
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.1
  @backstage/plugin-auth-backend-module-github-provider            0.2.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.1
  @backstage/plugin-auth-backend-module-google-provider            0.2.1
  @backstage/plugin-auth-backend-module-guest-provider             0.2.1
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.1
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.1
  @backstage/plugin-auth-backend-module-okta-provider              0.1.1
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.1
  @backstage/plugin-auth-backend                                   0.23.1
  @backstage/plugin-auth-node                                      0.5.3
  @backstage/plugin-auth-react                                     0.1.7
  @backstage/plugin-bitbucket-cloud-common                         0.2.24
  @backstage/plugin-catalog-backend-module-azure                   0.2.3
  @backstage/plugin-catalog-backend-module-logs                    0.1.3
  @backstage/plugin-catalog-backend-module-msgraph                 0.6.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.1
  @backstage/plugin-catalog-backend                                1.27.1
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.11
  @backstage/plugin-catalog-import                                 0.12.5
  @backstage/plugin-catalog-node                                   1.13.1
  @backstage/plugin-catalog-react                                  1.14.0
  @backstage/plugin-catalog                                        1.24.0
  @backstage/plugin-events-node                                    0.3.10, 0.4.3
  @backstage/plugin-home-react                                     0.1.18
  @backstage/plugin-home                                           0.8.0
  @backstage/plugin-kubernetes-backend                             0.18.7
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-node                                0.1.20
  @backstage/plugin-kubernetes-react                               0.4.4
  @backstage/plugin-kubernetes                                     0.11.16
  @backstage/plugin-org                                            0.6.31
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.1
  @backstage/plugin-permission-backend                             0.5.50
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.4
  @backstage/plugin-permission-react                               0.4.27
  @backstage/plugin-proxy-backend                                  0.5.7
  @backstage/plugin-scaffolder-backend-module-azure                0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.1
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.1
  @backstage/plugin-scaffolder-backend-module-github               0.5.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.6.0
  @backstage/plugin-scaffolder-backend                             1.26.2
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node                                0.5.0
  @backstage/plugin-scaffolder-react                               1.13.2
  @backstage/plugin-scaffolder                                     1.26.2
  @backstage/plugin-search-backend-module-catalog                  0.2.4
  @backstage/plugin-search-backend-module-pg                       0.5.37
  @backstage/plugin-search-backend-module-techdocs                 0.3.1
  @backstage/plugin-search-backend-node                            1.3.4
  @backstage/plugin-search-backend                                 1.6.1
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.1
  @backstage/plugin-search                                         1.4.18
  @backstage/plugin-signals-react                                  0.0.6
  @backstage/plugin-techdocs-backend                               1.11.1
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.16
  @backstage/plugin-techdocs-node                                  1.12.12
  @backstage/plugin-techdocs-react                                 1.2.9
  @backstage/plugin-techdocs                                       1.11.0
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.7.0
  @backstage/theme                                                 0.5.7, 0.6.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.10
✨  Done in 0.91s.
```

# backend index.ts

```ts
import { createBackend } from '@backstage/backend-defaults';
import { rootHttpRouterServiceFactory } from '@backstage/backend-defaults/rootHttpRouter';

const backend = createBackend();

backend.add(import('@backstage/plugin-app-backend'));

// proxy plugin
backend.add(import('@backstage/plugin-proxy-backend'));

// scaffolder plugin
backend.add(import('@backstage/plugin-scaffolder-backend'));

// techdocs plugin
backend.add(import('@backstage/plugin-techdocs-backend/alpha'));
// easy workaround for fixing techdocs auth coockie requirement/Bug
// !TODO: add auth token for proxy and techdocs
backend.add(
  rootHttpRouterServiceFactory({
    configure: ({ app, applyDefaults }) => {
      app.use((req, _, next) => {
        // Remove Authorization header for techdocs stylesheet
        if (
          req.url.includes(
            '/api/techdocs/static/docs/default/component/backstage/assets/stylesheets/main.',
          )
        ) {
          req.headers.authorization = undefined;
        }
        next();
      });
      applyDefaults();
    },
  }),
);

// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));
backend.add(import('@backstage/plugin-auth-backend-module-microsoft-provider'));

// catalog plugin
backend.add(import('@backstage/plugin-catalog-backend'));
backend.add(
  import('@backstage/plugin-catalog-backend-module-scaffolder-entity-model'),
);
backend.add(import('@backstage/plugin-catalog-backend-module-msgraph'));
backend.add(import('@backstage/plugin-catalog-backend-module-azure'));
backend.add(import('@backstage/plugin-catalog-backend-module-logs'));
backend.add(import('@backstage-community/plugin-azure-devops-backend'));
backend.add(import('@internal/backstage-plugin-custom-entities-common'));

// permission plugin
backend.add(import('@backstage/plugin-permission-backend'));
// See https://backstage.io/docs/permissions/getting-started for how to create your own permission policy
backend.add(
  import('@backstage/plugin-permission-backend-module-allow-all-policy'),
);

// search plugin
backend.add(import('@backstage/plugin-search-backend'));

// search engine
// See https://backstage.io/docs/features/search/search-engines
backend.add(import('@backstage/plugin-search-backend-module-pg'));

// search collators
backend.add(import('@backstage/plugin-search-backend-module-catalog'));
backend.add(import('@backstage/plugin-search-backend-module-techdocs'));

// kubernetes
backend.add(import('@backstage/plugin-kubernetes-backend'));

backend.start();
```

# App config
```yaml
catalog:
  rules:
    - allow:
        [
          Component,
          API,
          System,
          Domain,
          Resource,
          Location,
          User,
          Group,
          Template,
          Project,
        ]
  providers:
    microsoftGraphOrg:
      default:
        tenantId: ${AZURE_TENANT_ID}
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        user:
          filter: >
            accountEnabled eq true 
            and userType eq 'member'
          loadPhotos: true
          select: ['id', 'displayName', 'mail']
        group:
          filter: >
            securityEnabled eq true
            and mailEnabled eq false
          search: '"displayName:grp-"'
        schedule:
          frequency: PT1H
          timeout: PT50M
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
It seems like the [code](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/src/microsoftGraph/defaultTransformers.ts#L131) tries to use the `userPrincipalName` when the `mail` isn't in the user data, and based on the error message you shared, it appears that `usePrincipalName` is also undefined. According to your app config, only `id`, `displayName`, and `mail` are selected to fill in user info. Would it make sense to also pick the `userPrincipalName`?

**Comment by KL2808** [comment]
Jackpot! It seems like it has worked. Thank you very much! <3
