### ISSUE TITLE
🐛 Bug Report: number of polling subscriptions from event backend grows exponentially until polls fail and system resources are exhausted

### ISSUE THREAD

**Issue by jgrumboe** [backstage/backstage#27400]
### 📜 Description

I've upgraded our Backstage instance to 1.32.3 and activated the events-backend because I saw it in the upgrade-helper diff.
Since the upgrade, our ECS tasks of Backstage restart around every 10-15 minutes because the CPU has reached 100%, the Knex DB connection pool is exhausted, and health checks are not responding anymore.
The log is full of "Poll failed for subscription" messages, our ECS tasks of Backstage restart around every 10-15 minutes because the CPU has reached 100%, the Knex DB connection pool is exhausted, and 

### 👍 Expected behavior

Polling event subscriptions shouldn't fail, and the task shouldn't die/restart.

### 👎 Actual Behavior with Screenshots

To reproduce the case locally, I followed the getting started guide to create a fresh Backstage app.
I didn't configure anything, all settings default.
I just added the events-backend and the events-backend-module-github according to their READMEs.
Then I just started everything with `LOG_LEVEL=debug yarn dev` and let it run without any browser interaction, just idling around.

Each minute you'll see log lines of the `catalog.catalog` and `events.GithubEventRouter` subscription polling.
Every minute the number of these grows exponentially.
After around 9-10 minutes the warning messages starts like:
```
[backend]: 2024-10-30T08:21:24.810Z catalog warn Poll failed for subscription "catalog.catalog", retrying in 1000ms fetch failed cause=AggregateError stack=TypeError: fetch failed
[backend]:     at node:internal/deps/undici/undici:12618:11
[backend]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[backend]:     at DefaultApiClient.getSubscriptionEvents (/Users/jgrumboeck/tmp/backstage-events-test/backstage/node_modules/@backstage/plugin-events-node/src/generated/apis/DefaultApi.client.ts:84:12)
[backend]:     at poll (/Users/jgrumboeck/tmp/backstage-events-test/backstage/node_modules/@backstage/plugin-events-node/src/api/DefaultEventsService.ts:203:23)
```
Just leave it open and running and it will get worse and worse until the process "dies" with out-of-memory exceptions.

I'll attach the debug.log from my test.
[debug.log.gz](https://github.com/user-attachments/files/17573608/debug.log.gz)

### 👟 Reproduction steps

- follow https://backstage.io/docs/getting-started/ and run `npx @backstage/create-app@latest`
- `yarn --cwd packages/backend add @backstage/plugin-events-backend`
- `yarn --cwd packages/backend add @backstage/plugin-events-backend-module-github`
- add to `backend/src/index.ts`:
```
backend.add(import('@backstage/plugin-events-backend'));
import { eventsModuleGithubEventRouter } from '@backstage/plugin-events-backend-module-github/alpha';
backend.add(eventsModuleGithubEventRouter); 
```
- run `LOG_LEVEL=debug yarn dev`
- see the growing number of polling subscription event loglines every minute
- after around 9-10 minutes watch the first polling errors

### 🖥️ Your Environment

```
OS:   Darwin 23.6.0 - darwin/arm64
node: v20.12.2
yarn: 4.4.1
cli:  0.28.2 (installed)
backstage:  1.32.0

Dependencies:
  @backstage/app-defaults                                          1.5.12
  @backstage/backend-app-api                                       1.0.1
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.5.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.2.0
  @backstage/backend-plugin-api                                    1.0.1
  @backstage/catalog-client                                        1.7.1
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.9
  @backstage/cli                                                   0.28.2
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.1
  @backstage/core-compat-api                                       0.3.1
  @backstage/core-components                                       0.15.1
  @backstage/core-plugin-api                                       1.10.0
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.0
  @backstage/frontend-defaults                                     0.1.1
  @backstage/frontend-plugin-api                                   0.9.0
  @backstage/frontend-test-utils                                   0.2.1
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.2.0
  @backstage/integration                                           1.15.1
  @backstage/plugin-api-docs                                       0.11.11
  @backstage/plugin-app-backend                                    0.3.76
  @backstage/plugin-app-node                                       0.1.26
  @backstage/plugin-app                                            0.1.1
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.1
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.1
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.1
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.1
  @backstage/plugin-auth-backend-module-github-provider            0.2.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.1
  @backstage/plugin-auth-backend-module-google-provider            0.2.1
  @backstage/plugin-auth-backend-module-guest-provider             0.2.1
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.1
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.1
  @backstage/plugin-auth-backend-module-okta-provider              0.1.1
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.1
  @backstage/plugin-auth-backend                                   0.23.1
  @backstage/plugin-auth-node                                      0.5.3
  @backstage/plugin-auth-react                                     0.1.7
  @backstage/plugin-bitbucket-cloud-common                         0.2.24
  @backstage/plugin-catalog-backend-module-logs                    0.1.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.1
  @backstage/plugin-catalog-backend                                1.27.1
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.11
  @backstage/plugin-catalog-import                                 0.12.5
  @backstage/plugin-catalog-node                                   1.13.1
  @backstage/plugin-catalog-react                                  1.14.0
  @backstage/plugin-catalog                                        1.24.0
  @backstage/plugin-events-backend-module-github                   0.2.13
  @backstage/plugin-events-backend                                 0.3.15
  @backstage/plugin-events-node                                    0.4.3
  @backstage/plugin-kubernetes-backend                             0.18.7
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-node                                0.1.20
  @backstage/plugin-kubernetes-react                               0.4.4
  @backstage/plugin-kubernetes                                     0.11.16
  @backstage/plugin-org                                            0.6.31
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.1
  @backstage/plugin-permission-backend                             0.5.50
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.4
  @backstage/plugin-permission-react                               0.4.27
  @backstage/plugin-proxy-backend                                  0.5.7
  @backstage/plugin-scaffolder-backend-module-azure                0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.1
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.1
  @backstage/plugin-scaffolder-backend-module-github               0.5.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.6.0
  @backstage/plugin-scaffolder-backend                             1.26.2
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node                                0.5.0
  @backstage/plugin-scaffolder-react                               1.13.2
  @backstage/plugin-scaffolder                                     1.26.2
  @backstage/plugin-search-backend-module-catalog                  0.2.4
  @backstage/plugin-search-backend-module-pg                       0.5.37
  @backstage/plugin-search-backend-module-techdocs                 0.3.1
  @backstage/plugin-search-backend-node                            1.3.4
  @backstage/plugin-search-backend                                 1.6.1
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.1
  @backstage/plugin-search                                         1.4.18
  @backstage/plugin-signals-react                                  0.0.6
  @backstage/plugin-techdocs-backend                               1.11.1
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.16
  @backstage/plugin-techdocs-node                                  1.12.12
  @backstage/plugin-techdocs-react                                 1.2.9
  @backstage/plugin-techdocs                                       1.11.0
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.7.0
  @backstage/theme                                                 0.6.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.10
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by andythehood** [comment]
Seeing same behaviour here with a brand new 1.32 install, with just the plugin-events-backend added and without the github module.

[backend]: 2024-10-31T00:27:29.512Z rootHttpRouter info [31/Oct/2024:00:27:29 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T00:28:24.528Z rootHttpRouter info [31/Oct/2024:00:28:24 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T00:28:24.530Z rootHttpRouter info [31/Oct/2024:00:28:24 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T00:29:19.545Z rootHttpRouter info [31/Oct/2024:00:29:19 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T00:29:19.550Z rootHttpRouter info [31/Oct/2024:00:29:19 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T00:29:19.554Z rootHttpRouter info [31/Oct/2024:00:29:19 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T00:29:19.558Z rootHttpRouter info [31/Oct/2024:00:29:19 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T00:30:14.561Z rootHttpRouter info [31/Oct/2024:00:30:14 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T00:30:14.568Z rootHttpRouter info [31/Oct/2024:00:30:14 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T00:30:14.571Z rootHttpRouter info [31/Oct/2024:00:30:14 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
...

..and then the fetch failed cause=AggregateError exception after a few minutes

**Comment by jgrumboe** [comment]
@andythehood Yes, these calls come from `@backstage/plugin-catalog-backend-module-logs` as it also listens on events to get catalog logs.

**Comment by Rugvip** [comment]
Thank you for the detailed report! Fix is on the way in #27407

I've verified the fix using the signal backend subscription that's installed in `packages/backend` in this repo, along with lowering the the polling timeout. Before the fix I quickly see a large amount of polling requests, after the requests it's only a single loop.

**Comment by Rugvip** [comment]
Fix is now out as part of [1.32.5](https://github.com/backstage/backstage/releases/tag/v1.32.5)

**Comment by mrackoa** [comment]
Hi @Rugvip I just upgraded Backstage to the v1.32.5 to fix this issue but I can still see tons of there warns running it locally - which never happened to me before the upgrade to: v1.32.4
`catalog warn Poll failed for subscription`
`signals warn Poll failed for subscription`
`events warn Poll failed for subscription`

```"dependencies": {
    "@backstage-community/plugin-sonarqube-backend": "^0.2.20",
    "@backstage/backend-app-api": "^1.0.1",
    "@backstage/backend-common": "^0.25.0",
    "@backstage/backend-defaults": "^0.5.2",
    "@backstage/backend-plugin-api": "^1.0.1",
    "@backstage/backend-tasks": "^0.6.1",
    "@backstage/catalog-client": "^1.7.1",
    "@backstage/catalog-model": "^1.7.0",
    "@backstage/config": "^1.2.0",
    "@backstage/errors": "^1.2.4",
    "@backstage/integration": "^1.15.1",
    "@backstage/plugin-app-backend": "^0.3.76",
    "@backstage/plugin-auth-backend": "^0.23.1",
    "@backstage/plugin-auth-backend-module-github-provider": "^0.2.1",
    "@backstage/plugin-auth-backend-module-okta-provider": "^0.1.1",
    "@backstage/plugin-auth-node": "^0.5.3",
    "@backstage/plugin-catalog-backend": "^1.27.1",
    "@backstage/plugin-catalog-backend-module-bitbucket-server": "^0.2.3",
    "@backstage/plugin-catalog-backend-module-github": "^0.7.6",
    "@backstage/plugin-catalog-backend-module-github-org": "^0.3.3",
    "@backstage/plugin-catalog-backend-module-scaffolder-entity-model": "^0.2.1",
    "@backstage/plugin-catalog-backend-module-unprocessed": "^0.5.1",
    "@backstage/plugin-catalog-common": "^1.1.0",
    "@backstage/plugin-catalog-node": "^1.13.1",
    "@backstage/plugin-devtools-backend": "^0.4.1",
    "@backstage/plugin-events-backend": "^0.3.15",
    "@backstage/plugin-events-backend-module-github": "^0.2.13",
    "@backstage/plugin-events-node": "^0.4.4",
    "@backstage/plugin-kubernetes-backend": "^0.18.7",
    "@backstage/plugin-kubernetes-common": "^0.8.3",
    "@backstage/plugin-kubernetes-node": "^0.1.20",
    "@backstage/plugin-notifications-backend": "^0.4.2",
    "@backstage/plugin-notifications-node": "^0.2.8",
    "@backstage/plugin-permission-backend": "^0.5.50",
    "@backstage/plugin-permission-common": "^0.8.1",
    "@backstage/plugin-permission-node": "^0.8.4",
    "@backstage/plugin-proxy-backend": "^0.5.7",
    "@backstage/plugin-scaffolder-backend": "^1.26.2",
    "@backstage/plugin-scaffolder-backend-module-confluence-to-markdown": "^0.3.1",
    "@backstage/plugin-scaffolder-backend-module-github": "^0.5.1",
    "@backstage/plugin-scaffolder-node": "^0.5.0",
    "@backstage/plugin-search-backend": "^1.6.1",
    "@backstage/plugin-search-backend-module-catalog": "^0.2.4",
    "@backstage/plugin-search-backend-module-pg": "^0.5.37",
    "@backstage/plugin-search-backend-module-techdocs": "^0.3.1",
    "@backstage/plugin-search-backend-node": "^1.3.4",
    "@backstage/plugin-signals-backend": "^0.2.2",
    "@backstage/plugin-signals-node": "^0.1.13",
    "@backstage/plugin-techdocs-backend": "^1.11.1",
    "@backstage/plugin-user-settings-backend": "^0.2.26",
    "@internal/plugin-catalog-backend-module-kubernetes-rancher": "^0.1.0",
    "@octokit/core": "^5.1.0",
    "@octokit/graphql": "^7.0.2",
    "@pagerduty/backstage-plugin-backend": "^0.9.1",
    "@roadiehq/backstage-plugin-argo-cd-backend": "^3.2.0",
    "@roadiehq/catalog-backend-module-okta": "^0.10.0",
    "@roadiehq/scaffolder-backend-module-utils": "^2.0.1",
    "app": "link:../app",
    "dockerode": "^3.3.1",
    "dotenv": "^16.3.1",
    "express": "^4.17.1",
    "express-prom-bundle": "^6.6.0",
    "express-promise-router": "^4.1.0",
    "fs-extra": "^11.2.0",
    "jose": "^4.14.6",
    "js-yaml": "^4.1.0",
    "node-fetch": "^2.6.12",
    "node-gyp": "^9.0.0",
    "pg": "^8.11.3",
    "prom-client": "^14.2.0",
    "winston": "^3.2.1",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@backstage/cli": "^0.28.2",
    "@octokit/types": "^12.0.0",
    "@octokit/webhooks-types": "^7.5.1",
    "@types/cookie-parser": "^1.4.7",
    "@types/dockerode": "^3.3.0",
    "@types/express": "^4.17.6",
    "@types/express-serve-static-core": "^4.17.5",
    "@types/fs-extra": "^11",
    "@types/js-yaml": "^4",
    "@types/luxon": "^3.3.1",
    "better-sqlite3": "^8.0.0"
  },```

**Comment by jgrumboe** [comment]
I could verify it with a clean getting started app.
Looks fixed.

I will also update our production instance the next days, and report back if something still breaks.

🎉  Thanks @Rugvip for this very quick fix!

Debug log output is now fine.
```
[backend]: 2024-10-31T13:27:38.178Z rootHttpRouter info [31/Oct/2024:13:27:38 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T13:27:38.179Z rootHttpRouter info [31/Oct/2024:13:27:38 +0000] "GET /api/events/bus/v1/subscriptions/events.GithubEventRouter/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T13:27:38.201Z events debug Reading subscription 'catalog.catalog' resulted in 0 events type=EventBus subject=plugin:catalog
[backend]: 2024-10-31T13:27:38.204Z events debug Reading subscription 'events.GithubEventRouter' resulted in 0 events type=EventBus subject=plugin:events
[backend]: 2024-10-31T13:28:33.211Z rootHttpRouter info [31/Oct/2024:13:28:33 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T13:28:33.216Z rootHttpRouter info [31/Oct/2024:13:28:33 +0000] "GET /api/events/bus/v1/subscriptions/events.GithubEventRouter/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T13:28:33.221Z events debug Reading subscription 'catalog.catalog' resulted in 0 events type=EventBus subject=plugin:catalog
[backend]: 2024-10-31T13:28:33.226Z events debug Reading subscription 'events.GithubEventRouter' resulted in 0 events type=EventBus subject=plugin:events
[backend]: 2024-10-31T13:29:28.228Z rootHttpRouter info [31/Oct/2024:13:29:28 +0000] "GET /api/events/bus/v1/subscriptions/catalog.catalog/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T13:29:28.232Z rootHttpRouter info [31/Oct/2024:13:29:28 +0000] "GET /api/events/bus/v1/subscriptions/events.GithubEventRouter/events HTTP/1.1" 202 - "-" "node" type=incomingRequest
[backend]: 2024-10-31T13:29:28.237Z events debug Reading subscription 'catalog.catalog' resulted in 0 events type=EventBus subject=plugin:catalog
[backend]: 2024-10-31T13:29:28.242Z events debug Reading subscription 'events.GithubEventRouter' resulted in 0 events type=EventBus subject=plugin:events
```

<details>

<summary>yarn backstage-cli info</summary>

```
OS:   Darwin 23.6.0 - darwin/arm64
node: v20.12.2
yarn: 4.4.1
cli:  0.28.2 (installed)
backstage:  1.32.0

Dependencies:
  @backstage/app-defaults                                          1.5.12
  @backstage/backend-app-api                                       1.0.1
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.5.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.2.0
  @backstage/backend-plugin-api                                    1.0.1
  @backstage/catalog-client                                        1.7.1
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.9
  @backstage/cli                                                   0.28.2
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.1
  @backstage/core-compat-api                                       0.3.1
  @backstage/core-components                                       0.15.1
  @backstage/core-plugin-api                                       1.10.0
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.0
  @backstage/frontend-defaults                                     0.1.1
  @backstage/frontend-plugin-api                                   0.9.0
  @backstage/frontend-test-utils                                   0.2.1
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.2.0
  @backstage/integration                                           1.15.1
  @backstage/plugin-api-docs                                       0.11.11
  @backstage/plugin-app-backend                                    0.3.76
  @backstage/plugin-app-node                                       0.1.26
  @backstage/plugin-app                                            0.1.1
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.1
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.1
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.1
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.1
  @backstage/plugin-auth-backend-module-github-provider            0.2.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.1
  @backstage/plugin-auth-backend-module-google-provider            0.2.1
  @backstage/plugin-auth-backend-module-guest-provider             0.2.1
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.1
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.1
  @backstage/plugin-auth-backend-module-okta-provider              0.1.1
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.1
  @backstage/plugin-auth-backend                                   0.23.1
  @backstage/plugin-auth-node                                      0.5.3
  @backstage/plugin-auth-react                                     0.1.7
  @backstage/plugin-bitbucket-cloud-common                         0.2.24
  @backstage/plugin-catalog-backend-module-logs                    0.1.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.1
  @backstage/plugin-catalog-backend                                1.27.1
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.11
  @backstage/plugin-catalog-import                                 0.12.5
  @backstage/plugin-catalog-node                                   1.13.1
  @backstage/plugin-catalog-react                                  1.14.0
  @backstage/plugin-catalog                                        1.24.0
  @backstage/plugin-events-backend-module-github                   0.2.13
  @backstage/plugin-events-backend                                 0.3.15
  @backstage/plugin-events-node                                    0.4.4
  @backstage/plugin-kubernetes-backend                             0.18.7
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-node                                0.1.20
  @backstage/plugin-kubernetes-react                               0.4.4
  @backstage/plugin-kubernetes                                     0.11.16
  @backstage/plugin-org                                            0.6.31
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.1
  @backstage/plugin-permission-backend                             0.5.50
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.4
  @backstage/plugin-permission-react                               0.4.27
  @backstage/plugin-proxy-backend                                  0.5.7
  @backstage/plugin-scaffolder-backend-module-azure                0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.1
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.1
  @backstage/plugin-scaffolder-backend-module-github               0.5.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.6.0
  @backstage/plugin-scaffolder-backend                             1.26.2
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node                                0.5.0
  @backstage/plugin-scaffolder-react                               1.13.2
  @backstage/plugin-scaffolder                                     1.26.2
  @backstage/plugin-search-backend-module-catalog                  0.2.4
  @backstage/plugin-search-backend-module-pg                       0.5.37
  @backstage/plugin-search-backend-module-techdocs                 0.3.1
  @backstage/plugin-search-backend-node                            1.3.4
  @backstage/plugin-search-backend                                 1.6.1
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.1
  @backstage/plugin-search                                         1.4.18
  @backstage/plugin-signals-react                                  0.0.6
  @backstage/plugin-techdocs-backend                               1.11.1
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.16
  @backstage/plugin-techdocs-node                                  1.12.12
  @backstage/plugin-techdocs-react                                 1.2.9
  @backstage/plugin-techdocs                                       1.11.0
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.7.0
  @backstage/theme                                                 0.6.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.10
```

</details>

**Comment by mrackoa** [comment]
Hi @Rugvip it was caused by some legacy third party dependency. With the bump it was resolved. All good now.
