### ISSUE TITLE
🐛 Bug Report: publish:bitbucketServer:pullrequest created source branch but again trying to create branch while cloning and failing as it already exist

### ISSUE THREAD

**Issue by rmanik54** [backstage/backstage#27542]
### 📜 Description

I am trying to use bitbucketServer:pull-request action to create pull request, it's created source branch and again trying to create branch while cloning and failing as it's already existing

### 👍 Expected behavior

It should create a pull request. While cloning, it should not create a new branch; instead, it should copy file content and add, commit, and push or checkout to the branch instead of creating it again.

### 👎 Actual Behavior with Screenshots

It actually created branch at first at remote repository and again trying to create again while cloning instead of checkout. Here are the logs
```
> 132024-11-06T06:57:33.219Z Beginning step Publish PR
> 142024-11-06T06:57:33.485Z info: source branch not found -> creating branch named: feature/adddevops_platform_backstage lastCommit: 5985bhr82ffhsufh749de374hrryr73b3b115
> 152024-11-06T06:57:33.729Z info: Cloning repo {dir=/tmp/9c648021-5979-4323-a65d-b86ab8251c12_step-publish-EzcrxQ,url=https://bitbucket.org/scm/team/some.git}
> 162024-11-06T06:57:34.281Z info: Counting objects
> 172024-11-06T06:57:34.282Z info: Compressing objects
> 182024-11-06T06:57:34.322Z info: Receiving objects
> 192024-11-06T06:57:34.356Z info: Resolving deltas
> 202024-11-06T06:57:34.432Z info: Analyzing workdir
> 212024-11-06T06:57:34.440Z info: Updating workdir
> 222024-11-06T06:57:34.487Z info: Creating branch {dir=/tmp/9c648021-5979-4323-a65d-b86ab8251c12_step-publish-EzcrxQ,ref=feature/adddevops_platform_backstage
> 232024-11-06T06:57:34.488Z AlreadyExistsError: Failed to create branch at feature/adddevops_platform_backstage because it already exists.24    at _branch (/app/node_modules/isomorphic-git/index.cjs:5960:13) at async Object.branch (/app/node_modules/isomorphic-git/index.cjs:6022:12)26    at async Object.createBranch (/app/node_modules/@backstage/plugin-scaffolder-node/dist/actions/gitHelpers.cjs.js:93:3)27    at async Object.handler (/app/node_modules/@backstage/plugin-scaffolder-backend-module-bitbucket-server/dist/actions/bitbucketServerPullRequest.cjs.js:323:9)28    at async NunjucksWorkflowRunner.executeStep (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/scaffolder/tasks/NunjucksWorkflowRunner.cjs.js:234:9)29    at async NunjucksWorkflowRunner.execute (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/scaffolder/tasks/NunjucksWorkflowRunner.cjs.js:339:9)30    at async TaskWorker.runOneTask (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/scaffolder/tasks/TaskWorker.cjs.js:96:26)31    at async run (/app/node_modules/p-queue/dist/index.js:163:29)
```

### 👟 Reproduction steps

Try to use template action bitbucketServer:pull-request action in scaffolder template

```
steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          some: ${{ parameters.some }}

    - id: fetch-plain
      name: Fetch Plain
      action: fetch:plain:file
      input:
        url: https://bitbucket.org/scm/team/art/some.txt
        targetPath: ./some.txt

    - id: append-content
      name: Append Content
      action: roadiehq:utils:fs:append
      input:
        path: ./some.txt
        content: ./content
  
    - id: publish
      name: Publish PR
      action: publish:bitbucketServer:pull-request
      input:
        repoUrl: 'bitbucket.org/?repo=art&project=team'
        title: Add ${{ parameters.name }} repo
        sourceBranch: feature/add${{ parameters.name }}
        targetBranch: main
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: ${{ user.entity.metadata.email }}
        gitCommitMessage: Added ${{ parameters.name }} repo
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by jhaals** [comment]
Hi @rmanik54!

This is fixed in https://github.com/backstage/backstage/pull/27343 and will be in our main release next week.
This is already fixed in our `next` release if you want to consume this fix sooner.

**Comment by rmanik54** [comment]
Thanks @jhaals
