### ISSUE TITLE
🐛 Bug Report: Internationalization - EntityPage

### ISSUE THREAD

**Issue by al-alison** [backstage/backstage#27714]
### 📜 Description

I'm trying to add another language to the EntityPage, but i can't make it work with the TechDocs reader in the EntityPage. The error happens because i needed to define the components using functions to be able to use the translation resources.

The error only happens in the Docs tab in EntityPage, the other tabs are translated with no errors.
This is my EntityPage:

```
import React from 'react';
import { Grid } from '@material-ui/core';
import {
  EntityApiDefinitionCard,
  EntityConsumedApisCard,
  EntityConsumingComponentsCard,
  EntityHasApisCard,
  EntityProvidedApisCard,
  EntityProvidingComponentsCard,
} from '@backstage/plugin-api-docs';
import {
  EntityAboutCard,
  EntityDependsOnComponentsCard,
  EntityDependsOnResourcesCard,
  EntityHasComponentsCard,
  EntityHasResourcesCard,
  EntityHasSubcomponentsCard,
  EntityHasSystemsCard,
  EntityLayout,
  EntityLinksCard,
  EntitySwitch,
  EntityOrphanWarning,
  EntityProcessingErrorsPanel,
  isComponentType,
  isKind,
  hasCatalogProcessingErrors,
  isOrphan,
  hasRelationWarnings,
  EntityRelationWarning,
} from '@backstage/plugin-catalog';

import {
  EntityUserProfileCard,
  EntityGroupProfileCard,
  EntityMembersListCard,
  EntityOwnershipCard,
} from '@backstage/plugin-org';
import { EntityTechdocsContent } from '@backstage/plugin-techdocs';
import {
  Direction,
  EntityCatalogGraphCard,
} from '@backstage/plugin-catalog-graph';
import {
  RELATION_API_CONSUMED_BY,
  RELATION_API_PROVIDED_BY,
  RELATION_CONSUMES_API,
  RELATION_DEPENDENCY_OF,
  RELATION_DEPENDS_ON,
  RELATION_HAS_PART,
  RELATION_PART_OF,
  RELATION_PROVIDES_API,
} from '@backstage/catalog-model';

import { TechDocsAddons } from '@backstage/plugin-techdocs-react';
import { ReportIssue } from '@backstage/plugin-techdocs-module-addons-contrib';
//import { EntityKubernetesContent } from '@backstage/plugin-kubernetes';
import { EntityEnvManagerContent } from './env-manager/EntityEnvManagerContent';
import { EntityDatabaseContent } from './database/EntityDatabaseContent';
import { EntityApplicationDeployContent } from './application-deploy/EntityApplicationDeployContent';
import { EntityWorkloadContent } from './workload/EntityWorkloadContent';
import { useTranslationRef } from '@backstage/core-plugin-api/alpha';
import { appTranslationRef } from '../../translations/app/app';

const techdocsContent = (
  <EntityTechdocsContent>
    <TechDocsAddons>
      <ReportIssue />
    </TechDocsAddons>
  </EntityTechdocsContent>
);


const entityWarningContent  = (
  <>
    <EntitySwitch>
      <EntitySwitch.Case if={isOrphan}>
        <Grid item xs={12}>
          <EntityOrphanWarning />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>

    <EntitySwitch>
      <EntitySwitch.Case if={hasRelationWarnings}>
        <Grid item xs={12}>
          <EntityRelationWarning />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>

    <EntitySwitch>
      <EntitySwitch.Case if={hasCatalogProcessingErrors}>
        <Grid item xs={12}>
          <EntityProcessingErrorsPanel />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
  </>
);

const overviewContent = (
  <Grid container spacing={3} alignItems="stretch">
    {entityWarningContent}
    <Grid item md={6}>
      <EntityAboutCard variant="gridItem" />
    </Grid>
    <Grid item md={6} xs={12}>
      <EntityCatalogGraphCard variant="gridItem" height={400} />
    </Grid>

    <Grid item md={4} xs={12}>
      <EntityLinksCard />
    </Grid>
    <Grid item md={8} xs={12}>
      <EntityHasSubcomponentsCard variant="gridItem" />
    </Grid>
  </Grid>
);

//<EntityLayout.Route path="/kubernetes" title="Kubernetes">
//<EntityKubernetesContent refreshIntervalMs={30000} />
//</EntityLayout.Route>

const serviceEntityPage = () => {
  const { t } = useTranslationRef(appTranslationRef);
  return (
    <EntityLayout>
      <EntityLayout.Route path="/" title={t('entityPage.overview.title')}>
        {overviewContent}
      </EntityLayout.Route>

      <EntityLayout.Route path="/environment-variables" title={t('entityPage.configuration.title')}>
        <EntityEnvManagerContent />
      </EntityLayout.Route>

      <EntityLayout.Route path="/application-deploy" title={t('entityPage.deployment.title')}>
        <EntityApplicationDeployContent />
      </EntityLayout.Route>

      <EntityLayout.Route path="/infrastructure" title={t('entityPage.infrastructure.title')}>
        <EntityWorkloadContent />
      </EntityLayout.Route>

      <EntityLayout.Route path="/databases" title={t('entityPage.database.title')}>
        <EntityDatabaseContent />
      </EntityLayout.Route>

      <EntityLayout.Route path="/api" title={t('entityPage.api.title')}>
        <Grid container spacing={3} alignItems="stretch">
          <Grid item md={6}>
            <EntityProvidedApisCard />
          </Grid>
          <Grid item md={6}>
            <EntityConsumedApisCard />
          </Grid>
        </Grid>
      </EntityLayout.Route>

      <EntityLayout.Route path="/dependencies" title={t('entityPage.dependencies.title')}>
        <Grid container spacing={3} alignItems="stretch">
          <Grid item md={6}>
            <EntityDependsOnComponentsCard variant="gridItem" />
          </Grid>
          <Grid item md={6}>
            <EntityDependsOnResourcesCard variant="gridItem" />
          </Grid>
        </Grid>
      </EntityLayout.Route>

      <EntityLayout.Route path="/docs" title="DOCS">
        {techdocsContent}
      </EntityLayout.Route>


    </EntityLayout>
  )
};

const websiteEntityPage = () => {
  const { t } = useTranslationRef(appTranslationRef);
  return (<EntityLayout>
    <EntityLayout.Route path="/" title={t('entityPage.overview.title')}>
      {overviewContent}
    </EntityLayout.Route>

    <EntityLayout.Route path="/environment-variables" title={t('entityPage.configuration.title')}>
      <EntityEnvManagerContent />
    </EntityLayout.Route>

    <EntityLayout.Route path="/application-deploy" title={t('entityPage.deployment.title')}>
      <EntityApplicationDeployContent />
    </EntityLayout.Route>

    <EntityLayout.Route path="/infrastructure" title={t('entityPage.infrastructure.title')}>
      <EntityWorkloadContent />
    </EntityLayout.Route>

    <EntityLayout.Route path="/dependencies" title={t('entityPage.dependencies.title')}>
      <Grid container spacing={3} alignItems="stretch">
        <Grid item md={6}>
          <EntityDependsOnComponentsCard variant="gridItem" />
        </Grid>
        <Grid item md={6}>
          <EntityDependsOnResourcesCard variant="gridItem" />
        </Grid>
      </Grid>
    </EntityLayout.Route>

    <EntityLayout.Route path="/docs" title="DOCS">
      {techdocsContent}
    </EntityLayout.Route>

  </EntityLayout>
  )
};

/**
 * NOTE: This page is designed to work on small screens such as mobile devices.
 * This is based on Material UI Grid. If breakpoints are used, each grid item must set the `xs` prop to a column size or to `true`,
 * since this does not default. If no breakpoints are used, the items will equitably share the available space.
 * https://material-ui.com/components/grid/#basic-grid.
 */

const defaultEntityPage = () => {
  const { t } = useTranslationRef(appTranslationRef);
  return (
    <EntityLayout>
      <EntityLayout.Route path="/" title={t('entityPage.overview.title')}>
        {overviewContent}
      </EntityLayout.Route>

      <EntityLayout.Route path="/docs" title="{t('entityPage.docs.title')}">
        {techdocsContent}
      </EntityLayout.Route>
    </EntityLayout>
  )
};

const componentPage = () => (
  <EntitySwitch>
    <EntitySwitch.Case if={isComponentType('service')}>
      {serviceEntityPage()}
    </EntitySwitch.Case>

    <EntitySwitch.Case if={isComponentType('website')}>
      {websiteEntityPage()}
    </EntitySwitch.Case>

    <EntitySwitch.Case>{defaultEntityPage()}</EntitySwitch.Case>
  </EntitySwitch>
);

const apiPage = () => {
  const { t } = useTranslationRef(appTranslationRef);
  return (
    <EntityLayout>
      <EntityLayout.Route path="/" title={t('entityPage.overview.title')}>
        <Grid container spacing={3}>
          {entityWarningContent}
          <Grid item md={6}>
            <EntityAboutCard />
          </Grid>
          <Grid item md={6} xs={12}>
            <EntityCatalogGraphCard variant="gridItem" height={400} />
          </Grid>
          <Grid item md={4} xs={12}>
            <EntityLinksCard />
          </Grid>
          <Grid container item md={12}>
            <Grid item md={6}>
              <EntityProvidingComponentsCard />
            </Grid>
            <Grid item md={6}>
              <EntityConsumingComponentsCard />
            </Grid>
          </Grid>
        </Grid>
      </EntityLayout.Route>

      <EntityLayout.Route path="/definition" title={t('entityPage.definition.title')}>
        <Grid container spacing={3}>
          <Grid item xs={12}>
            <EntityApiDefinitionCard />
          </Grid>
        </Grid>
      </EntityLayout.Route>
    </EntityLayout>
  )
};

const userPage = () => {
  const { t } = useTranslationRef(appTranslationRef);

  return (
    <EntityLayout>
      <EntityLayout.Route path="/" title={t('entityPage.overview.title')}>
        <Grid container spacing={3}>
          {entityWarningContent}
          <Grid item xs={12} md={6}>
            <EntityUserProfileCard variant="gridItem" />
          </Grid>
          <Grid item xs={12} md={6}>
            <EntityOwnershipCard variant="gridItem" />
          </Grid>
        </Grid>
      </EntityLayout.Route>
    </EntityLayout>
  )
};

const groupPage = () => {
  const { t } = useTranslationRef(appTranslationRef);
  return (
    <EntityLayout>
      <EntityLayout.Route path="/" title={t('entityPage.overview.title')}>
        <Grid container spacing={3}>
          {entityWarningContent}
          <Grid item xs={12} md={6}>
            <EntityGroupProfileCard variant="gridItem" />
          </Grid>
          <Grid item xs={12} md={6}>
            <EntityOwnershipCard variant="gridItem" />
          </Grid>
          <Grid item xs={12} md={6}>
            <EntityLinksCard />
          </Grid>
          <Grid item xs={12} md={6}>
            <EntityMembersListCard />
          </Grid>
        </Grid>
      </EntityLayout.Route>
    </EntityLayout>
  )
};

const systemPage = () => {
  const { t } = useTranslationRef(appTranslationRef);
  return (
    <EntityLayout>
      <EntityLayout.Route path="/" title={t('entityPage.overview.title')}>
        <Grid container spacing={3} alignItems="stretch">
          {entityWarningContent}
          <Grid item md={6}>
            <EntityAboutCard variant="gridItem" />
          </Grid>
          <Grid item md={6} xs={12}>
            <EntityCatalogGraphCard variant="gridItem" height={400} />
          </Grid>
          <Grid item md={4} xs={12}>
            <EntityLinksCard />
          </Grid>
          <Grid item md={8}>
            <EntityHasComponentsCard variant="gridItem" />
          </Grid>
          <Grid item md={6}>
            <EntityHasApisCard variant="gridItem" />
          </Grid>
          <Grid item md={6}>
            <EntityHasResourcesCard variant="gridItem" />
          </Grid>
        </Grid>
      </EntityLayout.Route>
      <EntityLayout.Route path="/diagram" title={t('entityPage.diagram.title')}>
        <EntityCatalogGraphCard
          variant="gridItem"
          direction={Direction.TOP_BOTTOM}
          title="System Diagram"
          height={700}
          relations={[
            RELATION_PART_OF,
            RELATION_HAS_PART,
            RELATION_API_CONSUMED_BY,
            RELATION_API_PROVIDED_BY,
            RELATION_CONSUMES_API,
            RELATION_PROVIDES_API,
            RELATION_DEPENDENCY_OF,
            RELATION_DEPENDS_ON,
          ]}
          unidirectional={false}
        />
      </EntityLayout.Route>
    </EntityLayout>
  )
};

const domainPage = () => {
  const { t } = useTranslationRef(appTranslationRef);
  return (
    <EntityLayout>
      <EntityLayout.Route path="/" title={t('entityPage.overview.title')}>
        <Grid container spacing={3} alignItems="stretch">
          {entityWarningContent}
          <Grid item md={6}>
            <EntityAboutCard variant="gridItem" />
          </Grid>
          <Grid item md={6} xs={12}>
            <EntityCatalogGraphCard variant="gridItem" height={400} />
          </Grid>
          <Grid item md={6}>
            <EntityHasSystemsCard variant="gridItem" />
          </Grid>
        </Grid>
      </EntityLayout.Route>
    </EntityLayout>
  )
};

const EntityPage = () => {
  return (
    <EntitySwitch>
      <EntitySwitch.Case if={isKind('component')} children={componentPage()} />
      <EntitySwitch.Case if={isKind('api')} children={apiPage()} />
      <EntitySwitch.Case if={isKind('group')} children={groupPage()} />
      <EntitySwitch.Case if={isKind('user')} children={userPage()} />
      <EntitySwitch.Case if={isKind('system')} children={systemPage()} />
      <EntitySwitch.Case if={isKind('domain')} children={domainPage()} />

      <EntitySwitch.Case>{defaultEntityPage()}</EntitySwitch.Case>
    </EntitySwitch>
  )
};

export const entityPage = <EntityPage />;
```
### 👍 Expected behavior

The page should be translated successfully.

### 👎 Actual Behavior with Screenshots

Error when accessing the "docs" tab in the EntityPage.

![techdocs_error](https://github.com/user-attachments/assets/6f7cc695-0e7b-4ad2-83d5-90c34bc27a1b)

### 👟 Reproduction steps

1. Setup Internationalization 
2. Define the components in EntityPage using functions instead of defining them directly.
3. Access the Docs tab in Entity Page.

### 📃 Provide the context for the Bug.

This is the stacktrace: 

```
Routable extension component with mount point routeRef{type=absolute,id=techdocs:catalog-reader-view} was not discovered in the app element tree. Routable extension components may not be rendered by other components and must be directly available as an element within the App provider component. 

Error: Routable extension component with mount point routeRef{type=absolute,id=techdocs:catalog-reader-view} was not discovered in the app element tree. Routable extension components may not be rendered by other components and must be directly available as an element within the App provider component. at U (https://portal.tecban.dev.br/static/module-backstage.a7c68593.js:33:8679) at ki (https://portal.tecban.dev.br/static/module-react-dom.52a81000.js:14:16950) at Mi (https://portal.tecban.dev.br/static/module-react-dom.52a81000.js:16:3133) at na (https://portal.tecban.dev.br/static/module-react-dom.52a81000.js:16:44191) at Js (https://portal.tecban.dev.br/static/module-react-dom.52a81000.js:16:39462) at Zc (https://portal.tecban.dev.br/static/module-react-dom.52a81000.js:16:39393) at Hr (https://portal.tecban.dev.br/static/module-react-dom.52a81000.js:16:39252) at Yi (https://portal.tecban.dev.br/static/module-react-dom.52a81000.js:16:35674) at Ys
```
### 🖥️ Your Environment

OS:   Windows_NT 10.0.22631 - win32/x64
node: v20.17.0
yarn: 1.22.22
cli:  0.28.2 (installed)
backstage:  1.32.5

Dependencies:
  @backstage/app-defaults                          1.5.12
  @backstage/catalog-client                        1.7.1
  @backstage/catalog-model                         1.7.0
  @backstage/cli-common                            0.1.14
  @backstage/cli-node                              0.2.9
  @backstage/cli                                   0.28.2
  @backstage/config-loader                         1.9.1
  @backstage/config                                1.2.0
  @backstage/core-app-api                          1.15.1
  @backstage/core-compat-api                       0.2.5, 0.3.1
  @backstage/core-components                       0.14.7, 0.15.1
  @backstage/core-plugin-api                       1.10.0
  @backstage/errors                                1.2.4
  @backstage/eslint-plugin                         0.1.10
  @backstage/frontend-app-api                      0.10.0
  @backstage/frontend-defaults                     0.1.1
  @backstage/frontend-plugin-api                   0.6.5, 0.9.0
  @backstage/frontend-test-utils                   0.2.1
  @backstage/integration-react                     1.2.0
  @backstage/integration                           1.15.1
  @backstage/plugin-api-docs                       0.11.11
  @backstage/plugin-app                            0.1.1
  @backstage/plugin-auth-react                     0.1.7
  @backstage/plugin-catalog-common                 1.1.0
  @backstage/plugin-catalog-graph                  0.4.11
  @backstage/plugin-catalog-import                 0.12.5
  @backstage/plugin-catalog-react                  1.14.0
  @backstage/plugin-catalog                        1.24.0
  @backstage/plugin-home-react                     0.1.18
  @backstage/plugin-home                           0.8.0
  @backstage/plugin-kubernetes-common              0.8.3
  @backstage/plugin-kubernetes-react               0.4.4
  @backstage/plugin-kubernetes                     0.11.16
  @backstage/plugin-org                            0.6.31
  @backstage/plugin-permission-common              0.8.1
  @backstage/plugin-permission-react               0.4.27
  @backstage/plugin-scaffolder-common              1.5.6
  @backstage/plugin-scaffolder-react               1.13.2
  @backstage/plugin-scaffolder                     1.26.2
  @backstage/plugin-search-common                  1.2.14
  @backstage/plugin-search-react                   1.8.1
  @backstage/plugin-search                         1.4.18
  @backstage/plugin-signals-react                  0.0.6
  @backstage/plugin-tech-radar                     0.7.4
  @backstage/plugin-techdocs-common                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib 1.1.16
  @backstage/plugin-techdocs-react                 1.2.9
  @backstage/plugin-techdocs                       1.11.0
  @backstage/plugin-user-settings-common           0.0.1
  @backstage/plugin-user-settings                  0.8.14
  @backstage/release-manifests                     0.0.11
  @backstage/test-utils                            1.7.0
  @backstage/theme                                 0.5.5, 0.6.0
  @backstage/types                                 1.1.1
  @backstage/version-bridge                        1.0.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
unfortunately, this is a limitation of the current frontend system, everything needs to be discoverable without rendering the components. 

By wrapping up some of the JSX behind a new component to allow for doing  `const { t } = useTranslationRef(appTranslationRef);`  you affectively hide the JSX until it's rendered.

I think that we would need to add the ability to pass in a translation key to the `EntityLayout.Route` so that it can use that key thats passed through in order to support your use case.

**Comment by noe-orga-NTT** [comment]
Hello, is this fixed? I'm having the same problem
