### ISSUE TITLE
🐛 Bug Report: Docker image creation fails

### ISSUE THREAD

**Issue by mkarthiatgithub** [backstage/backstage#27978]
### 📜 Description

https://backstage.io/docs/deployment/docker#host-build 

Docker image creation fails. 

### 👍 Expected behavior

Docker image gets created 

### 👎 Actual Behavior with Screenshots

```sh
#10 [stage-0  6/15] RUN python3 -m pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org --no-cache-dir -r requirements.txt
#10 CACHED

#11 [stage-0 10/15] COPY --chown=node:node yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
#11 CACHED

#12 [stage-0  9/15] COPY --chown=node:node .yarnrc.yml ./
#12 CACHED

#13 [stage-0  8/15] COPY --chown=node:node .yarn ./.yarn
#13 CACHED

#14 [stage-0  7/15] WORKDIR /app
#14 CACHED

#15 [stage-0  5/15] COPY requirements.txt .
#15 CACHED

#16 [stage-0 11/15] RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz
#16 CACHED

#17 [stage-0 12/15] RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000     yarn workspaces focus --all --production
#17 0.500 ➤ YN0000: · Yarn 4.5.1
#17 0.504 ➤ YN0000: ┌ Resolution step
#17 0.614 ➤ YN0085: │ - @adobe/css-tools@npm:4.4.0, @ampproject/remapping@npm:2.3.0, @antfu/install-pkg@npm:0.4.1, @antfu/utils@npm:0.7.10, @ardatan/sync-fetch@npm:0.0.1, and 2176 more.
#17 0.629 ➤ YN0000: └ Completed
#17 0.629 ➤ YN0000: ┌ Post-resolution validation
#17 0.629 ➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
#17 0.629 ➤ YN0000: └ Completed
#17 0.629 ➤ YN0000: ┌ Fetch step
#17 6.759 ➤ YN0013: │ 1312 packages were added to the project (+ 83.31 MiB).
#17 6.759 ➤ YN0000: └ Completed in 6s 130ms
#17 6.759 ➤ YN0000: ┌ Link step
#17 12.87 ➤ YN0007: │ better-sqlite3@npm:11.5.0 must be built because it never has been before or the last one failed
#17 12.87 ➤ YN0007: │ core-js@npm:3.39.0 must be built because it never has been before or the last one failed
#17 12.88 ➤ YN0007: │ better-sqlite3@npm:9.6.0 must be built because it never has been before or the last one failed
#17 12.88 ➤ YN0007: │ isolated-vm@npm:4.7.2 must be built because it never has been before or the last one failed
#17 12.88 ➤ YN0007: │ protobufjs@npm:7.4.0 must be built because it never has been before or the last one failed
#17 12.88 ➤ YN0007: │ msw@npm:1.3.5 [29f28] must be built because it never has been before or the last one failed
#17 12.88 ➤ YN0007: │ cpu-features@npm:0.0.10 must be built because it never has been before or the last one failed
#17 12.88 ➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
#17 13.39 ➤ YN0009: │ cpu-features@npm:0.0.10 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-8f56b075/build.log)
#17 13.53 ➤ YN0009: │ isolated-vm@npm:4.7.2 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-6f6243f9/build.log)
#17 13.72 ➤ YN0007: │ ssh2@npm:1.16.0 must be built because it never has been before or the last one failed
#17 14.04 ➤ YN0000: └ Completed in 7s 281ms
#17 14.10 ➤ YN0000: · Failed with errors in 13s 597ms
#17 ERROR: process "/bin/sh -c yarn workspaces focus --all --production" did not complete successfully: exit code: 1
------
 > [stage-0 12/15] RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000     yarn workspaces focus --all --production:
12.88 ➤ YN0007: │ isolated-vm@npm:4.7.2 must be built because it never has been before or the last one failed
12.88 ➤ YN0007: │ protobufjs@npm:7.4.0 must be built because it never has been before or the last one failed
12.88 ➤ YN0007: │ msw@npm:1.3.5 [29f28] must be built because it never has been before or the last one failed
12.88 ➤ YN0007: │ cpu-features@npm:0.0.10 must be built because it never has been before or the last one failed
12.88 ➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
13.39 ➤ YN0009: │ cpu-features@npm:0.0.10 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-8f56b075/build.log)
13.53 ➤ YN0009: │ isolated-vm@npm:4.7.2 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-6f6243f9/build.log)
13.72 ➤ YN0007: │ ssh2@npm:1.16.0 must be built because it never has been before or the last one failed
14.04 ➤ YN0000: └ Completed in 7s 281ms
14.10 ➤ YN0000: · Failed with errors in 13s 597ms
------
Dockerfile:66
--------------------
  65 |
  66 | >>> RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
  67 | >>>     yarn workspaces focus --all --production
  68 |
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn workspaces focus --all --production" did not complete successfully: exit code: 1
```

### 👟 Reproduction steps

https://backstage.io/docs/deployment/docker#host-build 
Follow the step as is:

```sh
yarn install --immutable
yarn tsc
yarn build:backend
```

### 📃 Provide the context for the Bug.

If I remove `--all` option and do only for `--production` it works fine: 

```sh
RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn workspaces focus --production
```    

### 🖥️ Your Environment

bash-3.2$ yarn backstage-cli -V
0.28.2
bash-3.2$ yarn --version
4.5.1
bash-3.2$ docker --version
Docker version 27.3.1, build ce1223035a
bash-3.2$
bash-3.2$ nvm --version
0.40.1
bash-3.2$ node -v
v20.18.1
bash-3.2$ nvm current
v20.18.1
bash-3.2$

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by paulohac** [comment]
same here. 

on M3 the docker build works as it is in the documentation 
but when I add the flag --platform="linux/amd64" to the docker build command I get:

```
Initiated Worker with invalid execArgv flags: --no-opt
```

removing --all  from the ` yarn workspaces focus` command indeed worked and the image is build without problems

**Comment by camilaibs** [comment]
Hi @mkarthiatgithub could you please share with us the `isolated-vm` log file content? The log file path is mentioned in this error message:

```
isolated-vm@npm:4.7.2 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-6f6243f9/build.log)
```

**Comment by sbrawner** [comment]
Getting the same error here. My error log:
```# This file contains the result of Yarn building a package (isolated-vm@npm:5.0.2)
# Script name: install

prebuild-install warn install No prebuilt binaries found (target=20.18.1 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@11.0.0
gyp info using node@20.18.1 | darwin | x64
gyp info find Python using Python version 3.7.9 found at "/usr/local/bin/python3"

gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args '/Users/xxx/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/tree-sitter/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/xxx/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/isolated-vm/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/xxx/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/tree-sitter/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/xxx/Library/Caches/node-gyp/20.18.1/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/Users/xxx/Library/Caches/node-gyp/20.18.1',
gyp info spawn args '-Dnode_gyp_dir=/Users/xxx/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/tree-sitter/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/Users/xxx/Library/Caches/node-gyp/20.18.1/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/Users/xxx/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/isolated-vm',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/Users/xxx/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/tree-sitter/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
  File "/Users/xxx/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/tree-sitter/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/Users/xxxr/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/tree-sitter/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 8, in <module>
    import gyp.common
  File "/Users/xxx/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/tree-sitter/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 435
    if CC := os.environ.get("CC_target") or os.environ.get("CC"):
           ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/Users/xxx/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/tree-sitter/node_modules/node-gyp/lib/configure.js:317:18)
gyp ERR! stack at ChildProcess.emit (node:events:518:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 24.1.0
gyp ERR! command "/Users/xxx/.nvm/versions/node/v20.18.1/bin/node" "/Users/xxxr/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/tree-sitter/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "max"
gyp ERR! cwd /Users/xxx/IdeaProjects/backstage/backstage/my-backstage-app-1/node_modules/isolated-vm
gyp ERR! node -v v20.18.1
gyp ERR! node-gyp -v v11.0.0
gyp ERR! not ok```

**Comment by sbrawner** [comment]
The similarity of the error messages with isolated-vm and cpu-features lead me to believe there is a bug in node-gyp 11

**Comment by deejay1** [comment]
FYI node 20.18.0 works, 20.18.1 fails

**Comment by drapalaa** [comment]
@sbrawner According to the [documentation](https://github.com/nodejs/node-gyp?tab=readme-ov-file#installation), node-gyp version 11 requires a supported version of Python - at least 3.9, and yours is 3.7.9. 
```
gyp info using node-gyp@11.0.0
gyp info using node@20.18.1 | darwin | x64
gyp info find Python using Python version 3.7.9 found at "/usr/local/bin/python3"
```
I had the same error and bumping the Python version helped.
