### ISSUE TITLE
🐛 Bug Report: Yarn backstage-cli versions:bump fails due to bad path to package.json

### ISSUE THREAD

**Issue by momiskill** [backstage/backstage#28077]
### 📜 Description

I've followed [this guide](https://backstage.io/docs/getting-started/keeping-backstage-updated#managing-package-versions-with-the-backstage-yarn-plugin) to add the yarn plugin for keeping our Backstage repo up to date. Adding the plugin went fine, but when I run `yarn backstage-cli versions:bump` I get this error on the `yarn install` step: 
**Error: No package.json found while searching for package root of /C:/Users/momiskill/source/repos/Backstage**

I suspect that the leading '/' in the path could be the issue.

Running only `backstage-cli versions:bump` without 'yarn' works fine. Not sure if the behaviour is the same though?

### 👍 Expected behavior

Following the steps in the guide, when running the command `yarn backstage-cli versions:bump`, it should bump and install the correct versions without errors.

### 👎 Actual Behavior with Screenshots

On the `yarn install` step, I get this error:

```
Running yarn install to install new versions ×
(node:34848) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
➤ YN0000: · Yarn 4.5.3
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: No package.json found while searching for package root of /C:/Users/momiskill/source/repos/Backstage
    at Su (C:\Users\momiskill\source\repos\Backstage\.yarn\plugins\@yarnpkg\plugin-backstage.cjs:35:441384)
    at U4 (C:\Users\momiskill\source\repos\Backstage\.yarn\plugins\@yarnpkg\plugin-backstage.cjs:35:441681)
    at ra (C:\Users\momiskill\source\repos\Backstage\.yarn\plugins\@yarnpkg\plugin-backstage.cjs:35:442441)
    at na.bindDescriptor (C:\Users\momiskill\source\repos\Backstage\.yarn\plugins\@yarnpkg\plugin-backstage.cjs:35:444427)
    at Pg.bindDescriptor (C:\Users\momiskill\source\repos\Backstage\.yarn\releases\yarn-4.5.3.cjs:141:1112)
    at Pg.bindDescriptor (C:\Users\momiskill\source\repos\Backstage\.yarn\releases\yarn-4.5.3.cjs:141:1112)
    at t.preparePackage (C:\Users\momiskill\source\repos\Backstage\.yarn\releases\yarn-4.5.3.cjs:210:6173)
    at async Z (C:\Users\momiskill\source\repos\Backstage\.yarn\releases\yarn-4.5.3.cjs:210:7587)
    at async Promise.allSettled (index 0)
    at async Wc (C:\Users\momiskill\source\repos\Backstage\.yarn\releases\yarn-4.5.3.cjs:140:53201)
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 0s 131ms

Command 'yarn' exited with code 1
```

### 👟 Reproduction steps

Following [this guide](https://backstage.io/docs/getting-started/keeping-backstage-updated#managing-package-versions-with-the-backstage-yarn-plugin).

### 🖥️ Your Environment

```
OS:   Windows_NT 10.0.22631 - win32/x64
node: v22.11.0
yarn: 4.5.3
cli:  0.29.2 (installed)
backstage:  1.33.5

Dependencies:
  @backstage/app-defaults                                          1.5.14
  @backstage/backend-app-api                                       1.0.2
  @backstage/backend-common                                        0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.5.3
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.2.0, 0.3.0
  @backstage/backend-plugin-api                                    0.8.1, 1.0.2
  @backstage/backend-tasks                                         0.6.1
  @backstage/catalog-client                                        1.8.0
  @backstage/catalog-model                                         1.7.1
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.10
  @backstage/cli                                                   0.29.2
  @backstage/config-loader                                         1.9.2
  @backstage/config                                                1.3.0
  @backstage/core-app-api                                          1.15.2
  @backstage/core-compat-api                                       0.3.3
  @backstage/core-components                                       0.15.1, 0.16.1
  @backstage/core-plugin-api                                       1.10.1
  @backstage/dev-utils                                             1.1.4
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.5
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.2
  @backstage/frontend-defaults                                     0.1.3
  @backstage/frontend-plugin-api                                   0.9.2
  @backstage/frontend-test-utils                                   0.2.3
  @backstage/integration-aws-node                                  0.1.13
  @backstage/integration-react                                     1.2.1
  @backstage/integration                                           1.15.2
  @backstage/plugin-api-docs                                       0.12.1
  @backstage/plugin-app-backend                                    0.4.2
  @backstage/plugin-app-node                                       0.1.27
  @backstage/plugin-app                                            0.1.3
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.2
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.2
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.3.0
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.2
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.2
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.2
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.2
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.2
  @backstage/plugin-auth-backend-module-github-provider            0.2.2
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.2
  @backstage/plugin-auth-backend-module-google-provider            0.2.2
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.2
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.2
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.2
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.2
  @backstage/plugin-auth-backend-module-okta-provider              0.1.2
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.2
  @backstage/plugin-auth-backend                                   0.24.0
  @backstage/plugin-auth-node                                      0.5.4
  @backstage/plugin-auth-react                                     0.1.9
  @backstage/plugin-bitbucket-cloud-common                         0.2.25
  @backstage/plugin-catalog-backend-module-azure                   0.2.4
  @backstage/plugin-catalog-backend-module-incremental-ingestion   0.6.0
  @backstage/plugin-catalog-backend-module-logs                    0.1.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.2
  @backstage/plugin-catalog-backend-module-unprocessed             0.5.2
  @backstage/plugin-catalog-backend                                1.28.0
  @backstage/plugin-catalog-common                                 1.1.1
  @backstage/plugin-catalog-graph                                  0.4.13
  @backstage/plugin-catalog-import                                 0.12.7
  @backstage/plugin-catalog-node                                   1.14.0
  @backstage/plugin-catalog-react                                  1.14.2
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.5
  @backstage/plugin-catalog-unprocessed-entities                   0.2.11
  @backstage/plugin-catalog                                        1.25.1
  @backstage/plugin-events-node                                    0.4.5
  @backstage/plugin-kubernetes-backend                             0.19.0
  @backstage/plugin-kubernetes-common                              0.9.0
  @backstage/plugin-kubernetes-node                                0.2.0
  @backstage/plugin-org                                            0.6.33
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.2
  @backstage/plugin-permission-backend                             0.5.51
  @backstage/plugin-permission-common                              0.8.2
  @backstage/plugin-permission-node                                0.8.5
  @backstage/plugin-permission-react                               0.4.28
  @backstage/plugin-proxy-backend                                  0.5.8
  @backstage/plugin-scaffolder-backend-module-azure                0.2.3
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.3
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.3
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.4
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.3
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.3
  @backstage/plugin-scaffolder-backend-module-github               0.5.3
  @backstage/plugin-scaffolder-backend-module-gitlab               0.6.2
  @backstage/plugin-scaffolder-backend                             1.27.2
  @backstage/plugin-scaffolder-common                              1.5.7
  @backstage/plugin-scaffolder-node                                0.6.1
  @backstage/plugin-scaffolder-react                               1.14.1
  @backstage/plugin-scaffolder                                     1.27.1
  @backstage/plugin-search-backend-module-catalog                  0.2.5
  @backstage/plugin-search-backend-module-explore                  0.2.5
  @backstage/plugin-search-backend-module-pg                       0.5.38
  @backstage/plugin-search-backend-module-techdocs                 0.3.3
  @backstage/plugin-search-backend-node                            1.3.5
  @backstage/plugin-search-backend                                 1.7.0
  @backstage/plugin-search-common                                  1.2.15
  @backstage/plugin-search-react                                   1.8.3
  @backstage/plugin-search                                         1.4.20
  @backstage/plugin-signals-react                                  0.0.7
  @backstage/plugin-techdocs-backend                               1.11.3
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.18
  @backstage/plugin-techdocs-node                                  1.12.14
  @backstage/plugin-techdocs-react                                 1.2.11
  @backstage/plugin-techdocs                                       1.11.2
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.16
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.7.2
  @backstage/theme                                                 0.6.2
  @backstage/types                                                 1.2.0
  @backstage/version-bridge                                        1.0.10
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
Interesting. @mtlewis is this something that rings a bell for you?

**Comment by davidgiga1993** [comment]
Got the same issue after installing the yarn backstage plugin, seems to be a bug in the path resolution. I can try and take a look at it
