### ISSUE TITLE
Global SSL rejectUnauthorized=false for all requests to software catalog

### ISSUE THREAD

**Issue by michaelsonnleitner** [backstage/backstage#3399]
## Expected Behavior

I have self signed certificates on my bitbuckt onpremis repo.

## Current Behavior

I get the following error message if I want to connect to a bitbucket instance with self signed certificates like: 
```
reason: unable to verify the first certificate at Module.generalError (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/processors/results.ts:59:56)
 at UrlReaderProcessor.readLocation (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/processors/UrlReaderProcessor.ts:75:67)
 at processTicksAndRejections (internal/process/task_queues.js:93:5) 
at async LocationReaders.handleLocation (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/LocationReaders.ts:142:13)
 at async LocationReaders.read (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/LocationReaders.ts:74:11) 
at async HigherOrderOperations.addLocation (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/HigherOrderOperations.ts:80:26) 
at async eval (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/service/router.ts:115:22)
```
## Possible Solution

I want to disable the checks for ssl communication.

**Comment by Rugvip** [comment]
Does adding `NODE_TLS_REJECT_UNAUTHORIZED=0` to the environment solve the issue?

**Comment by michaelsonnleitner** [comment]
thats right thank you!

**Comment by kaos** [comment]
Is there a way to add our own CA certificates to the trust store, so we can keep verifications on?

**Comment by jvilimek** [comment]
> Is there a way to add our own CA certificates to the trust store, so we can keep verifications on?

Will this <https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs> help?

**Comment by kaos** [comment]
> > Is there a way to add our own CA certificates to the trust store, so we can keep verifications on?
> 
> Will this https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs help?

Looks promising. I'll pass it on internally here, thank you.
