### ISSUE TITLE
npx @backstage/create-app not working / sqlite3 NOT found

### ISSUE THREAD

**Issue by michaelsonnleitner** [backstage/backstage#3428]
## Expected Behavior
I am new to npm / node but I think backstage is a thing we need in our company....
I am trying to create an app....
```
npx @backstage/create-app 
```

## Current Behavior

following error is printed:
```
error C:\ent\backstage\rsg\node_modules\sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\ent\backstage\rsg\node_modules\sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.15.1 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "C:\ent\backstage\rsg\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.15.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-win32-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.1 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.1 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\wrssmi\AppData\Local\Programs\Python\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\ent\\nodejs\\node.exe" "C:\\ent\\backstage\\rsg\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\ent\\backstage\\rsg\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\ent\\backstage\\rsg\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd C:\ent\backstage\rsg\node_modules\sqlite3
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\ent\nodejs\node.exe C:\ent\backstage\rsg\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\ent\backstage\rsg\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\ent\backstage\rsg\node_modules\sqlite3\lib\binding\node-v83-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\ent\backstage\rsg\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\ent\\nodejs\\node.exe" "C:\\ent\\backstage\\rsg\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\ent\backstage\rsg\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\ent\nodejs\node.exe C:\ent\backstage\rsg\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\ent\backstage\rsg\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\ent\backstage\rsg\node_modules\sqlite3\lib\binding\node-v83-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
yarn install v1.22.1
```

## Context

initial setup was ok
start of backend and frontend also works. I can browse localhost:3000 and it looks nice.

## Your Environment

C:\ent\backstage>node -v
v14.15.1
C:\ent\backstage>yarn -v
1.22.1
C:\ent\backstage>npm -v
6.14.9
OS
Windows 10

**Comment by benjdlambert** [comment]
Could you try with node version 12 instead?

**Comment by freben** [comment]
Hi! What I see in the logs is

```
gyp ERR! stack Error: Command failed: C:\Users\wrssmi\AppData\Local\Programs\Python\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
```

This looks like python 3 trying to run python 2 code - print is expected to have parentheses and work like a function in python 3. I am not an expert on gyp but it seems it wants python 2. Is there any way that you could use a py2 virtualenv or similar while working with backstage?

**Comment by regicsolutions** [comment]
@michaelsonnleitner were you able to get passed this error? I am running into the same error, using Node.JS 12.16.1 on Windows 10

**Comment by freben** [comment]
The exact same with `print "%s.%s.%s"`?

Would you be able to try with python 2 instead of 3, eg using virtualenv?

**Comment by michaelsonnleitner** [comment]
**i did following:**

see [https://spin.atomicobject.com/2019/03/27/node-gyp-windows/](https://spin.atomicobject.com/2019/03/27/node-gyp-windows/) (Punkt 2)

```
npm install --global --production windows-build-tools --vs2015
```

**Comment by oliverwehrens** [comment]
I also had this problem with Node14, was solved with Node16.
