### ISSUE TITLE
yarn install fails on Apple M1 requiring latest node

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#3444]
I've got a brand spanking new M1 MacBook Air that requires latest node to be installed. This means I can't run Backstage locally. Any suggestions for how to proceed? 🙌

```
stefan@Stefans-Air backstage % yarn install
yarn install v1.22.1
[1/5] 🔍  Validating package.json...
error root@1.0.0: The engine "node" is incompatible with this module. Expected version "12 || 14". Got "15.3.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by benjdlambert** [comment]
I think you can try `yarn install --ignore-engines`

**Comment by stefanalund** [comment]
@benjaminr thanks, that did the trick! But...now I have new errors:

```
@babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] 🔨  Building fresh packages...
[9/24] ⠐ canvas
[12/24] ⠐ bufferutil
[3/24] ⠐ fsevents
[10/24] ⠐ cypress
error /Users/stefan/code/backstage/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/stefan/code/backstage/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@15.3.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/Users/stefan/code/backstage/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-darwin-unknown-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-darwin-unknown-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-darwin-unknown-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@15.3.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-darwin-unknown-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@15.3.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@15.3.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/stefan/code/backstage/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stefan/code/backstage/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stefan/code/backstage/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/stefan/.node-gyp/15.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/stefan/.node-gyp/15.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/stefan/code/backstage/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/stefan/.node-gyp/15.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/stefan/code/backstage/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/stefan/code/backstage/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Darwin 20.1.0
gyp ERR! command "/Users/stefan/.nvm/versions/node/v15.3.0/bin/node" "/Users/stefan/code/backstage/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/stefan/code/backstage/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/stefan/code/backstage/node_modules/canvas/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88" "--python=/usr/bin/python"
gyp ERR! cwd /Users/stefan/code/backstage/node_modules/canvas
gyp ERR! node -v v15.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/stefan/.nvm/versions/node/v15.3.0/bin/node /Users/stefan/code/backstage/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/stefan/code/backstage/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/stefan/code/backstage/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88 --python=/usr/bin/python' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/stefan/code/backstage/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
node-pre-gyp ERR! System Darwin 20.1.0
node-pre-gyp ERR! command "/Users/stefan/.nvm/versions/node/v15.3.0/bin/node" "/Users/stefan/code/backstage/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/stefan/code/backstage/node_modules/canvas
node-pre-gyp ERR! node -v v15.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/stefan/.nvm/versions/node/v15.3.0/bin/node /Users/stefan/code/backstage/node_modules/node-gyp/bin/node-gyp.js configur
```

Some more discussions here https://github.com/nodejs/TSC/issues/886

**Comment by freben** [comment]
I think you need to do `brew install pkgconfig` first.

**Comment by stefanalund** [comment]
@freben nope, doesn't help 🤕

**Comment by Rugvip** [comment]
Bleeding edge 😅 

Got XCode commandline tools installed? Could be that you get the essentials needed with that.

If all else fails I think you can always fall back to running it all through rosetta 2, https://news.ycombinator.com/item?id=25132217

**Comment by stefanalund** [comment]
@Rugvip I gave up on trying to get latest version of node to work and eventually ran through [Rosetta instead](https://osxdaily.com/2020/11/18/how-run-homebrew-x86-terminal-apple-silicon-mac/). Now it works 😄 

Thanks all!

**Comment by volehuy1998** [comment]
I switched from VisualCode terminal to MacOS terminal, it worked very well.

**Comment by ngoclammevn** [comment]
> I think you can try `yarn install --ignore-engines`

It help me, thank you 🙏 😊
