### ISSUE TITLE
The catalog info file created by the catalog importer fails validation

### ISSUE THREAD

**Issue by iain-b** [backstage/backstage#3678]
When a repo is supplied to the catalog importer and the resulting PR merged nothing happens. This is because the component in the catalog info file is missing the owner field and it's now required.

```
[1] 2020-12-10T16:51:43.395Z catalog warn Failed item in location github:https://github.com/RoadieHQ/sample-service/blob/master/catalog-info.yaml, InputError: Processor BuiltinKindsEntityProcessor threw an error while validating the entity Component:default/sample-service at github https://github.com/RoadieHQ/sample-service/blob/master/catalog-info.yaml, ValidationError: spec.owner is a required field
[1]     at Module.inputError (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/processors/results.ts:51:12)
[1]     at LocationReaders.handleEntity (webpack-internal:///../../node_modules/@backstage/plugin-catalog-backend/src/ingestion/LocationReaders.ts:222:78)
[1]     at runMicrotasks (<anonymous>)
[1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Expected Behavior

The component the importer generates should have an owner field.

## Possible Solution

Could we use the userId of the logged in user? or their github username? Failing that some default value.

**Comment by adamdmharvey** [comment]
Hint: Following the breadcrumbs, Is it perhaps this, line 43 here?  The Analyze Location call doesn't define a `spec.owner`:

https://github.com/backstage/backstage/blob/257619c1ee9c49454fc32b6d7d2b07283ea8d738/plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts#L31-L44

Maybe it should just default to be the repo owner, a la the org or user who already owns the repo?  (although that doesn't guarantee there is a `group` or user in Backstage that mirrors it)

**Comment by dhenneke** [comment]
#4271 forces the user to define an owner during the import flow. That should fix this issue.

However, it might be nice to pre-fill the owner field based on e.g. codeowners. But that's another issue.

**Comment by freben** [comment]
The idea of codeowners is actually to not fill it in in the source yaml at all - it'll be dynamically populated on each refresh instead.
