### ISSUE TITLE
integrations url processor doesn't implement support for private gitlab repos

### ISSUE THREAD

**Issue by n2ygk** [backstage/backstage#4106]
Integrations for gitlab private repos do not work; only public repos can be pulled from, e.g. for catalog items.

## Expected Behavior

The gitlab API (or different auth headers) need to be used with the `token` in order to get files from a private repo.

## Current Behavior

Fails to load the referenced file.

## Possible Solution

Use gitlab API endpoint to retrieve file content?

## Steps to Reproduce

1. Make a private mirror of backstage/backstage.
2. Create an access token.
3. Modify example app-config.yaml (e.g. in app-config.local.yaml) to point a scaffolder entry at the private gitlab repo file. For example: the Documentation Template.
4. Run the demo server with `yarn dev`

```
[1] 2021-01-15T15:10:06.774Z catalog warn Failed item in location url:https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/blob/master/templates/docs-template/template.yaml, Error: YAML error, YAMLSemanticError: Implicit map keys need to be on a single line
[1]     at Module.generalError (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/results.ts:59:56)
[1]     at parseEntityYaml (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/util/parse.ts:45:66)
[1]     at parseEntityYaml.next (<anonymous>)
[1]     at UrlReaderProcessor.readLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/UrlReaderProcessor.ts:64:18)
[1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[1]     at async LocationReaders.handleLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:142:13)
[1]     at async LocationReaders.read (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:74:11)
[1]     at async HigherOrderOperations.refreshSingleLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:159:26)
[1]     at async HigherOrderOperations.refreshAllLocations (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:138:9)
[1]     at async startRefresh (webpack-internal:///../../plugins/catalog-backend/src/util/runPeriodically.ts:42:9) type=plugin
```

Tracing the code shows https://github.com/backstage/backstage/blob/9d7b50f2f36f599df4c9ceacb18676fc0fdf72bc/packages/backend-common/src/reading/GitlabUrlReader.ts#L56 generates a GET with a PRIVATE-TOKEN header.

Gitlab only supports the PRIVATE-TOKEN header for the API, not file URLs.

## Context

Trying to use backstage with private repos (on prem gitlab enterprise and/or github.com) and can't reference individual git-hosted files with the `url` processor.

The current workaround is to make the repos public.

## Your Environment

- NodeJS Version (v12): v12.20.0
- Operating System and Version (e.g. Ubuntu 14.04): MacOS Catalina 10.15.7 (19H114)
- Browser Information: N/A

**Comment by n2ygk** [comment]
@freben per our discord messages.

@Rugvip looks like you might want to look at this... Some notes I made:
```
Given this URL: https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/blob/customize/doc-template.yaml

":id" can be integer project ID or URL-encoded org/repo: cuit-ent-arch%2Fbackstage

https://gitlab.cc.columbia.edu/api/v4/projects/cuit-ent-arch%2Fbackstage/repository/files/doc-template.yaml?ref=customize

response:

{
    "file_name": "doc-template.yaml",
    "file_path": "doc-template.yaml",
    "size": 658,
    "encoding": "base64",
    "content_sha256": "a93c6061001f2cc87185932f9fd91614acbe67d545270f95b148bf05e22c175e",
    "ref": "customize",
    "blob_id": "36404f088ca56dde04ea71bdcb73fc730607740c",
    "commit_id": "f2c6e35ac4d981788ab2ddd352ffd2dc1f1911b8",
    "last_commit_id": "f2c6e35ac4d981788ab2ddd352ffd2dc1f1911b8",
    "content": "YXBpVmVyc2lvbjogYmFja3N0YWdlLmlvL3YxYWxwaGExCmtpbmQ6IFRlbXBsYXRlCm1ldGFkYXRhOgogIG5hbWU6IGRvY3MtdGVtcGxhdGUKICB0aXRsZTogRG9jdW1lbnRhdGlvbiBUZW1wbGF0ZQogIGRlc2NyaXB0aW9uOiBDcmVhdGUgYSBuZXcgc3RhbmRhbG9uZSBkb2N1bWVudGF0aW9uIHByb2plY3QKICB0YWdzOgogICAgLSByZWNvbW1lbmRlZAogICAgLSB0ZWNoZG9jcwogICAgLSBta2RvY3MKc3BlYzoKICBvd25lcjogYmFja3N0YWdlL3RlY2hkb2NzLWNvcmUKICB0ZW1wbGF0ZXI6IGNvb2tpZWN1dHRlcgogIHR5cGU6IGRvY3VtZW50YXRpb24KICBwYXRoOiAnLicKCiAgc2NoZW1hOgogICAgcmVxdWlyZWQ6CiAgICAgIC0gY29tcG9uZW50X2lkCiAgICAgIC0gZGVzY3JpcHRpb24KICAgIHByb3BlcnRpZXM6CiAgICAgIGNvbXBvbmVudF9pZDoKICAgICAgICB0aXRsZTogTmFtZQogICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgIGRlc2NyaXB0aW9uOiBVbmlxdWUgbmFtZSBvZiB0aGUgY29tcG9uZW50CiAgICAgIGRlc2NyaXB0aW9uOgogICAgICAgIHRpdGxlOiBEZXNjcmlwdGlvbgogICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgIGRlc2NyaXB0aW9uOiBIZWxwIG90aGVycyB1bmRlcnN0YW5kIHdoYXQgdGhlc2UgZG9jcyBhcmUgYWJvdXQuCg=="
}


```

**Comment by freben** [comment]
Thanks! Also post the relevant piece of your `integrations` section in config. Double check that it's the one that actually gets used - i.e., if it's overridden in `app-config.local.yaml`, then post that one, of course with the token censored.

**Comment by forrestwaters** [comment]
@n2ygk if you try `type: gitlab` I believe this will work. The code for figuring out project ID/talking to the gitlab API is [here](https://github.com/backstage/backstage/blob/9d7b50f2f36f599df4c9ceacb18676fc0fdf72bc/packages/integration/src/gitlab/core.ts#L101). The gitlab integration works for our private repos for catalog files as well as techdocs, etc.

**Comment by n2ygk** [comment]
> Thanks! Also post the relevant piece of your `integrations` section in config. Double check that it's the one that actually gets used - i.e., if it's overridden in `app-config.local.yaml`, then post that one, of course with the token censored.

```
integrations:
  github:
    - host: github.com
      token:
        $env: GITHUB_TOKEN
  gitlab:
    - host: gitlab.cc.columbia.edu
      token:
        $env: GITLAB_TOKEN
      apiBaseUrl: https://gitlab.cc.columbia.edu/api/v4
```

**Comment by n2ygk** [comment]
> @n2ygk if you try `type: gitlab` I believe this will work. The code for figuring out project ID/talking to the gitlab API is [here](https://github.com/backstage/backstage/blob/9d7b50f2f36f599df4c9ceacb18676fc0fdf72bc/packages/integration/src/gitlab/core.ts#L101). The gitlab integration works for our private repos for catalog files as well as techdocs, etc.

My understanding is these types are being deprecated and replaced by integrations `type: url`. I guess I will also have to add a gitlab `processor` to make this error go away:


```
[1] 2021-01-15T16:04:43.214Z catalog warn No processor was able to read location gitlab https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/blob/master/templates/docs-template/template.yaml type=plugin
[1] 2021-01-15T16:04:49.714Z catalog warn Failed item in location gitlab:https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/blob/master/templates/docs-template/template.yaml, InputError: No processor was able to read location gitlab https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/blob/master/templates/docs-template/template.yaml
[1]     at Module.inputError (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/results.ts:51:12)
[1]     at LocationReaders.handleLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:159:72)
[1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[1]     at async LocationReaders.read (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:74:11)
[1]     at async HigherOrderOperations.refreshSingleLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:159:26)
[1]     at async HigherOrderOperations.refreshAllLocations (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:138:9)
[1]     at async startRefresh (webpack-internal:///../../plugins/catalog-backend/src/util/runPeriodically.ts:42:9) type=plugin
```

**Comment by n2ygk** [comment]
> @n2ygk if you try `type: gitlab` I believe this will work. The code for figuring out project ID/talking to the gitlab API is [here]

BTW, there's no need to get the project ID as it can also be a [url-encoded org/repo](https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding)

**Comment by n2ygk** [comment]
> > @n2ygk if you try `type: gitlab` I believe this will work. The code for figuring out project ID/talking to the gitlab API is [here](https://github.com/backstage/backstage/blob/9d7b50f2f36f599df4c9ceacb18676fc0fdf72bc/packages/integration/src/gitlab/core.ts#L101). The gitlab integration works for our private repos for catalog files as well as techdocs, etc.
> 
> My understanding is these types are being deprecated and replaced by integrations `type: url`. I guess I will also have to add a gitlab `processor` to make this error go away:
> 
> ```
> [1] 2021-01-15T16:04:43.214Z catalog warn No processor was able to read location gitlab https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/blob/master/templates/docs-template/template.yaml type=plugin
> [1] 2021-01-15T16:04:49.714Z catalog warn Failed item in location gitlab:https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/blob/master/templates/docs-template/template.yaml, InputError: No processor was able to read location gitlab https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/blob/master/templates/docs-template/template.yaml
> [1]     at Module.inputError (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/results.ts:51:12)
> [1]     at LocationReaders.handleLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:159:72)
> [1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> [1]     at async LocationReaders.read (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:74:11)
> [1]     at async HigherOrderOperations.refreshSingleLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:159:26)
> [1]     at async HigherOrderOperations.refreshAllLocations (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:138:9)
> [1]     at async startRefresh (webpack-internal:///../../plugins/catalog-backend/src/util/runPeriodically.ts:42:9) type=plugin
> ```

I explicitly added the processor but still seeing the same error:
```
diff --git a/app-config.yaml b/app-config.yaml
index 5866354a8..8653eb9cf 100644
--- a/app-config.yaml
+++ b/app-config.yaml
@@ -139,6 +139,12 @@ catalog:
         - Location
 
   processors:
+    gitlab:
+      providers:
+        - target: https://gitlab.cc.columbia.edu
+          token:
+            $env: GITLAB_TOKEN
+          apiBaseUrl: https://gitlab.cc.columbia.edu/api/v4
```

**Comment by freben** [comment]
That last config diff does not show a host field. Just double checking

**Comment by n2ygk** [comment]
> That last config diff does not show a host field. Just double checking

Isn't the host inferred from the target? Anyway, I've added it and also did some experiments with gitlab vs url type.

Here's my config.app diffs from 9420aef1ae9409923e4dfa7bba9deb619e4bfe73:

```diff
backstage$ ls -l app-config.local.yaml
ls: app-config.local.yaml: No such file or directory
backstage$ git diff master app-config.yaml 
diff --git a/app-config.yaml b/app-config.yaml
index 5866354a8..2af04d06f 100644
--- a/app-config.yaml
+++ b/app-config.yaml
@@ -110,10 +110,15 @@ integrations:
     #   rawBaseUrl: https://ghe.example.net/raw
     #   token:
     #     $env: GHE_TOKEN
+  # gitlab:
+  #   - host: gitlab.com
+  #     token:
+  #       $env: GITLAB_TOKEN
   gitlab:
-    - host: gitlab.com
+    - host: gitlab.cc.columbia.edu
       token:
         $env: GITLAB_TOKEN
+      apiBaseUrl: https://gitlab.cc.columbia.edu/api/v4
   bitbucket:
     - host: bitbucket.org
       username:
@@ -149,6 +154,13 @@ catalog:
         #   apiBaseUrl: https://ghe.example.net/api
         #   token:
         #     $env: GHE_TOKEN
+    # gitlab:
+    #   providers:
+    #     - host: gitlab.cc.columbia.edu
+    #       target: https://gitlab.cc.columbia.edu
+    #       token:
+    #         $env: GITLAB_TOKEN
+    #       apiBaseUrl: https://gitlab.cc.columbia.edu/api/v4
     ldapOrg:
       ### Example for how to add your enterprise LDAP server
       # providers:
@@ -187,9 +199,6 @@ catalog:
     # Example component for github-actions
     - type: url
       target: https://github.com/backstage/backstage/blob/master/plugins/github-actions/examples/sample.yaml
-    # Example component for TechDocs
-    - type: url
-      target: https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/catalog-info.yaml
     # Backstage example APIs
     - type: url
       target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml
@@ -203,8 +212,16 @@ catalog:
     - type: url
       target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-domains.yaml
     # Backstage example templates
+    # - type: url
+    #   target: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/all-templates.yaml
+    ### try a few here:
     - type: url
-      target: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/all-templates.yaml
+      target: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/react-ssr-template/template.yaml
+    # Example component for TechDocs
+    - type: url
+      target: https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/blob/master/templates/docs-template/template.yaml
+    #   target: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/docs-template/template.yaml
+
     # Backstage example groups and users
     - type: url
       target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
```

(I commented out the `all-templates` to make things more clear and configured the `react-ssr-template` and the gitlab-hosted TechDocs template)

Here's the log, showing the error to load the gitlab template:
```
yarn run v1.22.1
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace example-app start
$ yarn workspace example-backend start
$ backstage-cli app:serve
$ backstage-cli backend:dev
[0] Loaded config from app-config.yaml
[0] ℹ ｢wds｣: Project is running at http://localhost:3000/
[0] ℹ ｢wds｣: webpack output is served from /
[0] ℹ ｢wds｣: Content not from webpack is served from /Users/alan/src/backstage/packages/app/public
[0] ℹ ｢wds｣: 404s will fallback to /index.html
[1] Build succeeded
[0] ℹ ｢wdm｣: wait until bundle finished: /create
[1] 2021-01-15T18:24:04.404Z backstage info Loaded config from app-config.yaml 
[1] 2021-01-15T18:24:04.409Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucket{host=bitbucket.org,authed=false},github{host=github.com,authed=true},gitlab{host=gitlab.cc.columbia.edu,authed=true},gitlab{host=gitlab.com,authed=false},fallback=fetch{}} 
[1] 2021-01-15T18:24:04.522Z catalog info Locations Refresh: Beginning locations refresh type=plugin component=catalog-all-locations-refresh
[1] 2021-01-15T18:24:04.539Z scaffolder warn Skipping azure scaffolding provider, Missing required config value at 'scaffolder.azure.api.token' type=plugin
[1] 2021-01-15T18:24:04.539Z scaffolder warn Skipping bitbucket scaffolding provider, Missing required config value at 'scaffolder.bitbucket.api.username' type=plugin
[1] 2021-01-15T18:24:04.544Z catalog info Locations Refresh: Visiting 1 locations type=plugin component=catalog-all-locations-refresh
[1] 2021-01-15T18:24:04.544Z catalog info Locations Refresh: Refreshing location bootstrap:bootstrap type=plugin component=catalog-all-locations-refresh
[1] 2021-01-15T18:24:04.582Z auth info Configuring provider, google type=plugin
[1] 2021-01-15T18:24:04.583Z auth warn Skipping google auth provider, Missing required config value at 'auth.providers.google.development.clientId' type=plugin
[1] 2021-01-15T18:24:04.583Z auth info Configuring provider, github type=plugin
[1] 2021-01-15T18:24:04.584Z auth info Configuring provider, gitlab type=plugin
[1] 2021-01-15T18:24:04.586Z auth info Configuring provider, saml type=plugin
[1] 2021-01-15T18:24:04.587Z auth info Configuring provider, okta type=plugin
[1] 2021-01-15T18:24:04.587Z auth warn Skipping okta auth provider, Missing required config value at 'auth.providers.okta.development.clientId' type=plugin
[1] 2021-01-15T18:24:04.587Z auth info Configuring provider, oauth2 type=plugin
[1] 2021-01-15T18:24:04.588Z auth warn Skipping oauth2 auth provider, Missing required config value at 'auth.providers.oauth2.development.clientId' type=plugin
[1] 2021-01-15T18:24:04.588Z auth info Configuring provider, oidc type=plugin
[1] 2021-01-15T18:24:04.588Z auth warn Skipping oidc auth provider, Missing required config value at 'auth.providers.oidc.development.clientId' type=plugin
[1] 2021-01-15T18:24:04.588Z auth info Configuring provider, auth0 type=plugin
[1] 2021-01-15T18:24:04.588Z auth warn Skipping auth0 auth provider, Missing required config value at 'auth.providers.auth0.development.clientId' type=plugin
[1] 2021-01-15T18:24:04.589Z auth info Configuring provider, microsoft type=plugin
[1] 2021-01-15T18:24:04.589Z auth warn Skipping microsoft auth provider, Missing required config value at 'auth.providers.microsoft.development.clientId' type=plugin
[1] 2021-01-15T18:24:04.589Z auth info Configuring provider, onelogin type=plugin
[1] 2021-01-15T18:24:04.589Z auth warn Skipping onelogin auth provider, Missing required config value at 'auth.providers.onelogin.development.clientId' type=plugin
[1] 2021-01-15T18:24:04.591Z techdocs info Creating Local publisher for TechDocs type=plugin
[1] 2021-01-15T18:24:04.593Z kubernetes info Initializing Kubernetes backend type=plugin
[1] 2021-01-15T18:24:04.597Z proxy info [HPM] Proxy created: [Function: filter]  ->  https://circleci.com/api/v1.1 type=plugin
[1] 2021-01-15T18:24:04.597Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/circleci/api/" ~> "/" type=plugin
[1] 2021-01-15T18:24:04.599Z proxy info [HPM] Proxy created: [Function: filter]  ->  http://localhost:8080 type=plugin
[1] 2021-01-15T18:24:04.599Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/jenkins/api/" ~> "/" type=plugin
[1] 2021-01-15T18:24:04.599Z proxy info [HPM] Proxy created: [Function: filter]  ->  https://api.travis-ci.com type=plugin
[1] 2021-01-15T18:24:04.606Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/travisci/api/" ~> "/" type=plugin
[1] 2021-01-15T18:24:04.606Z proxy info [HPM] Proxy created: [Function: filter]  ->  https://api.newrelic.com/v2 type=plugin
[1] 2021-01-15T18:24:04.606Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/newrelic/apm/api/" ~> "/" type=plugin
[1] 2021-01-15T18:24:04.607Z proxy info [HPM] Proxy created: [Function: filter]  ->  https://api.pagerduty.com type=plugin
[1] 2021-01-15T18:24:04.607Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/pagerduty/" ~> "/" type=plugin
[1] 2021-01-15T18:24:04.607Z proxy info [HPM] Proxy created: [Function: filter]  ->  https://api.buildkite.com/v2/ type=plugin
[1] 2021-01-15T18:24:04.607Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/buildkite/api/" ~> "/" type=plugin
[1] 2021-01-15T18:24:04.608Z proxy info [HPM] Proxy created: [Function: filter]  ->  https://sentry.io/api/ type=plugin
[1] 2021-01-15T18:24:04.608Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/sentry/api/" ~> "/" type=plugin
[1] 2021-01-15T18:24:04.670Z app info Serving static app content from /Users/alan/src/backstage/packages/app/dist type=plugin
[1] 2021-01-15T18:24:04.740Z app info Replacing injected env config in main.7d404d73.chunk.js type=plugin
[1] 2021-01-15T18:24:04.748Z backstage info Initializing http server 
[1] 2021-01-15T18:24:04.751Z backstage info Listening on :7000 
[1] 2021-01-15T18:24:06.910Z backstage info ::1 - - [15/Jan/2021:18:24:06 +0000] "GET /api/catalog/entities?filter=kind=Template HTTP/1.1" 200 2 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" type=incomingRequest
[1] 2021-01-15T18:24:11.697Z catalog warn Failed item in location url:https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/blob/master/templates/docs-template/template.yaml, Error: YAML error, YAMLSemanticError: Implicit map keys need to be on a single line
[1]     at Module.generalError (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/results.ts:59:56)
[1]     at parseEntityYaml (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/util/parse.ts:45:66)
[1]     at parseEntityYaml.next (<anonymous>)
[1]     at UrlReaderProcessor.readLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/UrlReaderProcessor.ts:64:18)
[1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[1]     at async LocationReaders.handleLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:142:13)
[1]     at async LocationReaders.read (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:74:11)
[1]     at async HigherOrderOperations.refreshSingleLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:159:26)
[1]     at async HigherOrderOperations.refreshAllLocations (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:138:9)
[1]     at async startRefresh (webpack-internal:///../../plugins/catalog-backend/src/util/runPeriodically.ts:42:9) type=plugin
[1] 2021-01-15T18:24:11.697Z catalog info Read 57 entities from location bootstrap:bootstrap in 7.2s type=plugin
[1] 2021-01-15T18:24:11.791Z catalog info Wrote 57 entities from location bootstrap:bootstrap in 94ms type=plugin
[1] 2021-01-15T18:24:11.792Z catalog info Locations Refresh: Completed locations refresh in 7.3s type=plugin component=catalog-all-locations-refresh
[0] ℹ ｢wdm｣: Compiled successfully.
[1] 2021-01-15T18:24:29.855Z backstage info ::1 - - [15/Jan/2021:18:24:29 +0000] "GET /api/catalog/entities?filter=kind=Template HTTP/1.1" 200 923 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" type=incomingRequest
```

And a screenshot of localhost:3000/create: 
![image](https://user-images.githubusercontent.com/4356471/104761380-d21b8e00-5730-11eb-8c98-bd090263737c.png)

All that above is with a private gitlab repo:
![image](https://user-images.githubusercontent.com/4356471/104763186-861e1880-5733-11eb-9cbc-7e69e1f896cf.png)


Now make the same repo public:
![image](https://user-images.githubusercontent.com/4356471/104763271-9c2bd900-5733-11eb-9ca1-c9c29dff4df2.png)

and voila, no errors logged and this:
![image](https://user-images.githubusercontent.com/4356471/104764632-ab138b00-5735-11eb-8547-0816573f6bf5.png)

I've traced this code, pulled out the URLs and headers and tested with Postman and it's pretty clear that the code is setting a `private-token` header on the URL as given whereas one I believe has to use the API endpoint to actually get the file content as a json document. When the repo is public, it "just works."

**Comment by digitole** [comment]
I have the same (?) or similar problem. Getting the catalog-info.yaml is possible in a public repo on our self-hosted gitlab, but not in a private repo (I've tested the token).

The error I get: "YAML error, YAMLSemanticError: Implicit map keys need to be on a single line"

I added this to the backstage config:
```
integrations:
  gitlab:
    - host: gitlab.wklive.net
      apiBaseUrl: https://gitlab.wklive.net/api/v4
      [token]

```

**Comment by freben** [comment]
That specific error almost always means that the response was HTML, not yaml. So, most likely a login page or similar.

**Comment by ruloweb** [comment]
@n2ygk all you have to do is to add a `-/` in the URL xD, like this:

`https://gitlab.cc.columbia.edu/cuit-ent-arch/backstage/-/blob/master/templates/docs-template/template.yaml` 

This is because of the logic in the `getGitLabFileFetchUrl` function, if the URL contains `-/` it will use the API, otherwise, it will do a simple fetch.

https://github.com/backstage/backstage/blob/master/packages/integration/src/gitlab/core.ts#L41

It could be rewritten following the same logic as the github integration, what do you think @freben?.

**Comment by n2ygk** [comment]
Huh. scoped URLs. Go figure... Didn't even know that was a thing. Aha! I see that our gitlab instance is on an old version (11.11.0) while [newer versions](https://gitlab.com/gitlab-org/gitlab/-/issues/28848) will remove the legacy (no-dash) URLs so that will be a non-issue going forward. 

Thanks @ruloweb!

**Comment by djh2020** [comment]
So how do you use private gitlab repos?   I have tired encoding the URL, providing the project id, changing ~/ to -/ and although I can curl the file no problem I am unable to register an existing component using the UI.
