### ISSUE TITLE
OKTA redirect_uri is broken due to configurable authentication environments

### ISSUE THREAD

**Issue by mmogylenko** [backstage/backstage#4464]
As per [auth-backend](https://github.com/backstage/backstage/tree/master/plugins/auth-backend) documentation for OKTA, we need to set `redirect_uri` in OKTA to `http://localhost:7000/api/auth/okta/handler/frame` (for example https://backstage.domain.com/api/auth/okta/handler/frame). But due to introduced configurable authentication env request to `redirect_uri` fails.

## Expected Behavior

Request to `http://localhost:7000/api/auth/okta/handler/frame` is returning HTTP 200 instead of 400.

## Current Behavior

When OKTA makes a call to `redirect_uri` we get this:
```bash
InputError: Must specify 'env' query to select environment
```

## Possible Solution

Work in progress, no recommendation at the moment

## Steps to Reproduce

Follow [Getting Started](https://backstage.io/docs/getting-started/running-backstage-locally) guide

1. Clone & Build
```bash
# Start from your local development folder
git clone --depth 1 git@github.com:backstage/backstage.git
cd backstage

# Fetch our dependencies and run an initial build
yarn install
yarn tsc
yarn build
```
2. Enable OKTA by exporting Environment variables and start Backend 
```bash
 AUTH_OKTA_CLIENT_ID=client-id-for-amazingcomp AUTH_OKTA_CLIENT_SECRET=super-secret-for-amazingcomp AUTH_OKTA_AUDIENCE=https://amazingcomp.okta.com yarn start
yarn run v1.22.1
$ backstage-cli backend:dev
Build succeeded
2021-02-09T18:45:36.272Z backstage info Loaded config from app-config.yaml
2021-02-09T18:45:36.278Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucket{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},fetch{}
2021-02-09T18:45:36.399Z catalog info Locations Refresh: Beginning locations refresh type=plugin component=catalog-all-locations-refresh
2021-02-09T18:45:36.405Z scaffolder warn 'Specifying credentials for Azure in the Scaffolder configuration is deprecated. This will cause errors in a future release. Please migrate to using integrations config and specifying tokens under hostnames' type=plugin
2021-02-09T18:45:36.406Z scaffolder warn 'Specifying credentials for GitHub in the Scaffolder configuration is deprecated. This will cause errors in a future release. Please migrate to using integrations config and specifying tokens under hostnames' type=plugin
2021-02-09T18:45:36.406Z scaffolder warn 'Specifying credentials for Gitlab in the Scaffolder configuration is deprecated. This will cause errors in a future release. Please migrate to using integrations config and specifying tokens under hostnames' type=plugin
2021-02-09T18:45:36.410Z catalog info Locations Refresh: Visiting 1 locations type=plugin component=catalog-all-locations-refresh
2021-02-09T18:45:36.411Z catalog info Locations Refresh: Refreshing location bootstrap:bootstrap type=plugin component=catalog-all-locations-refresh
2021-02-09T18:45:36.420Z auth info Configuring provider, google type=plugin
2021-02-09T18:45:36.420Z auth warn Skipping google auth provider, Missing required config value at 'auth.providers.google.development.clientId' type=plugin
2021-02-09T18:45:36.420Z auth info Configuring provider, github type=plugin
2021-02-09T18:45:36.421Z auth warn Skipping github auth provider, Missing required config value at 'auth.providers.github.development.clientId' type=plugin
2021-02-09T18:45:36.421Z auth info Configuring provider, gitlab type=plugin
2021-02-09T18:45:36.421Z auth warn Skipping gitlab auth provider, Missing required config value at 'auth.providers.gitlab.development.clientId' type=plugin
2021-02-09T18:45:36.421Z auth info Configuring provider, saml type=plugin
2021-02-09T18:45:36.422Z auth info Configuring provider, okta type=plugin.  <<<<<**SUCCESS**
2021-02-09T18:45:36.423Z auth info Configuring provider, oauth2 type=plugin
```
3. Make a request to OKTA `redirect_uri`:
```bash
curl http://localhost:7000/api/auth/okta/handler/frame
InputError: Must specify 'env' query to select environment
    at OAuthEnvironmentHandler.getProviderForEnv (webpack-internal:///../../plugins/auth-backend/src/lib/oauth/OAuthEnvironmentHandler.ts:91:13)
    at OAuthEnvironmentHandler.frameHandler (webpack-internal:///../../plugins/auth-backend/src/lib/oauth/OAuthEnvironmentHandler.ts:57:27)
    at handleReturn (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /Users/mogylenk/Work/sources/backstage-bare/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at handleReturn (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /Users/mogylenk/Work/sources/backstage-bare/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at Layer.handle [as handle_request] (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mogylenk/Work/sources/backstage-bare/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express/lib/router/index.js:47:12)
    at handleReturn (/Users/mogylenk/Work/sources/backstage-bare/node_modules/express-promise-router/lib/express-promise-router.js:24:27)%
```
Config file `app-config.yaml` has no changes (it does contain environment parameter)

In the same time, call to `redirect_uri` with `env` parameter works:
```bash
curl http://localhost:7000/api/auth/okta/handler/frame?env=development
<html><body><script>
    var authResponse = decodeURIComponent('%7B%22type%22%3A%22authorization_response%22%2C%22error%22%3A%7B%22name%22%3A%22Error%22%2C%22message%22%3A%22Invalid%20state%20passed%20via%20request%22%7D%7D');
    var origin = decodeURIComponent('http%3A%2F%2Flocalhost%3A3000');
    var originInfo = {'type': 'config_info', 'targetOrigin': origin};
    (window.opener || window.parent).postMessage(originInfo, '*');
    (window.opener || window.parent).postMessage(JSON.parse(authResponse), origin);
    setTimeout(() => {
      window.close();
    }, 100); // same as the interval of the core-api lib/loginPopup.ts (to address race conditions)
  </script></body></html>%
```

which is because of the [following change](https://github.com/backstage/backstage/commit/9e11dfca4021ef93c03ea95661624ccdd0077392)

But **OKTAs redirect_url** needs to be an **absolute URI**, without parameters, otherwise 400 error

## Your Environment

- NodeJS Version (v12): v14.15.4
- Operating System and Version (e.g. Ubuntu 14.04): OS-independent bug (Ubuntu 20.04)
- Browser Information: Version 88.0.4324.96 (Official Build) (x86_64)

**Comment by mmogylenko** [comment]
Closing for now, doing more troubleshooting.

**Comment by emilgelman** [comment]
@mmogylenko I'm experiencing the same, any luck with this?

**Comment by mmogylenko** [comment]
@emilgelman, in my case (if I remember right) it was due to ENV variables and config mismatch. Pay attention to:
- `NODE_ENV`, `APP_CONFIG_auth_environment` environment variables
- as well as application configuration
```yaml
....
  auth:
        environment: production
        providers:
        okta:
          production:
            clientId:
....
```

I had a feeling at that time, when you add default `app-config.yaml` into Docker Image and then tried to overwrite with ENV variables it didn't work.
