### ISSUE TITLE
Add app-config.yaml validations

### ISSUE THREAD

**Issue by nirga** [backstage/backstage#4727]
There should be more validations for the correctness of the different settings in `app-config.yaml` so that we can provide more meaningful errors.

## Feature Suggestion

I'll try to keep a list of configs that aren't currently validated at all:
- Proxy plugin

## Context

When we worked with the proxy plugin I encountered that if you don't write the config correctly (we accidentally wrote the URL as a direct child of a proxy entry, instead of under `target`) you get some cryptic error from Express:
```
TypeError: Cannot read property 'split' of null
    at required (/usr/src/app/node_modules/requires-port/index.js:13:23)
    at Object.common.setupOutgoing (/usr/src/app/node_modules/http-proxy/lib/http-proxy/common.js:101:7)
    at Array.stream (/usr/src/app/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:127:14)
    at ProxyServer.<anonymous> (/usr/src/app/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at middleware (/usr/src/app/node_modules/@backstage/plugin-proxy-backend/node_modules/http-proxy-middleware/lib/index.js:46:13)
    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)
    at handleReturn (/usr/src/app/packages/backend/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /usr/src/app/packages/backend/node_modules/express-promise-router/lib/express-promise-router.js:58:5
```

**Comment by Rugvip** [comment]
Huh, writing the URL directly as the value is explicitly allowed in the schema, perhaps that's not supposed to be the case? https://github.com/backstage/backstage/blob/f9ae3d5d5f5c3c9a6f7e9ab455bc8d546541b6a2/plugins/proxy-backend/config.d.ts#L25

If the object form is required, we should remove the `string` form from the schema

**Comment by freben** [comment]
That has to be a mistaken breakage - it was supposed to be a good short form that works for the most basic use cases

**Comment by nirga** [comment]
Ah @Rugvip so the `config.d.ts` should automatically validate the schema? Then this is a completely different bug 😅  I'll close and reopen a different one.

**Comment by nirga** [comment]
Opened #4728
