### ISSUE TITLE
Proxy Plugin fails with cryptic error when "http" is missing

### ISSUE THREAD

**Issue by nirga** [backstage/backstage#4728]
Missing `http` at the beginning of a proxy configuration causes a cryptic error to be thrown.
```yaml
proxy:
  '/facebook':
    facebook.com
```

## Expected Behavior

A better error message indicating the what happened.

## Current Behavior

When missing the `http` prefix, the following error is thrown:
```
TypeError: Cannot read property 'split' of null
    at required (/usr/src/app/node_modules/requires-port/index.js:13:23)
    at Object.common.setupOutgoing (/usr/src/app/node_modules/http-proxy/lib/http-proxy/common.js:101:7)
    at Array.stream (/usr/src/app/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:127:14)
    at ProxyServer.<anonymous> (/usr/src/app/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at middleware (/usr/src/app/node_modules/@backstage/plugin-proxy-backend/node_modules/http-proxy-middleware/lib/index.js:46:13)
    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)
    at handleReturn (/usr/src/app/packages/backend/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /usr/src/app/packages/backend/node_modules/express-promise-router/lib/express-promise-router.js:58:5
```

## Steps to Reproduce

Just add such entry and browse to the URL that the proxy plugin exposes.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): mac OS X
- Browser Information: Chrome 88

**Comment by nirga** [comment]
Further debugging this, the problem was with a missing `http://` at the beginning. I wonder if there should be a better handling of this or a better error message? Or should we disallow things that do not start with `http://` altogether?

**Comment by Rugvip** [comment]
I think we could validate that the target is an absolute URL, basically checking if `new URL(target)` throws and in that case re-throw some slightly more helpful error message
