### ISSUE TITLE
npx @backstage/create-app is not adding all files, issue in launching backend server

### ISSUE THREAD

**Issue by sanjeetCoder** [backstage/backstage#4773]
## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by OrkoHunter** [comment]
What's the issue in launching the backend? Share logs please.

**Comment by ravichadda** [comment]
2021-03-03T08:59:56.000Z Beginning step Publish
2021-03-03T08:59:56.000Z Error: Unable to find a publisher for URL: https://github.com/ravichadda/testingBackstage. Please make sure to register this host under an integration in app-config
    at Publishers.get (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts:43:13)
    at Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/legacy.ts:103:36)
    at TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:127:24)
    at async eval (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:53:9)

**Comment by OrkoHunter** [comment]
Hmm, make sure to register `github.com` in `integrations:` of your `app-config.yaml` like this

https://github.com/backstage/backstage/blob/faeba3472a1a67931b978d1f7f3bb17f11033fd6/app-config.yaml#L123-L127

**Comment by ravichadda** [comment]
We have already configured the settings in integrations as you mentioned as well.
[app-config.yaml.zip](https://github.com/backstage/backstage/files/6075677/app-config.yaml.zip)

**Comment by ravichadda** [comment]
Is there required any user github " https://github.com/ravichadda/testingBackstage" credentials w.r.t. the host?

**Comment by OrkoHunter** [comment]
Yeah, I think you'll need to set the `GITHUB_TOKEN` to create a new repository on GitHub.

**Comment by adamdmharvey** [comment]
Just following up on this and like OrkoHunder noted, the `app-config.yaml` you provided is roughly the out of the box one. This means you need to be providing your self-generated GITHUB_TOKEN to environment variables before you start the Backstage backend. (Your Backstage instance can't connect to public GitHub.com anonymously, even if you can access it over the web anonymously.)  I believe there's likely better documentation needed for this, but I've seen some work coming forth to improve the "integrations" section of https://backstage.io/docs/ so I think that is coming soon.

Does this help?  Do you think we can close this issue now, @sanjeetCoder ?

**Comment by OrkoHunter** [comment]
Thanks Adam for following up - closing this as inactive. :D
