### ISSUE TITLE
Error: Unable to find a publisher for URL "github.com", Please make sure to register this host under an integration in app-config

### ISSUE THREAD

**Issue by ravichadda** [backstage/backstage#4778]
Hi Team, 
I am getting an error while creating templet as following the steps mentioned in url https://backstage.io/blog/2020/08/05/announcing-backstage-software-templates
I have submitted all the required fields as:

1. Fill in template parameters
Name,
Description
Port 
2. Choose owner and repo
Owner
Store path
Access

Then in next step create the details as:

Http Port | 8080
-- | --
Component Id | testingreact
Description | testingreact
Owner | Ravi
Store Path | https://github.com/ravichadda/testingBackstage
Access | Backend

## Expected Behavior

*** Prepare Successfully in 31 seconds 
***Template Successfully in 10 seconds 
***Publish failed 

## Current Behavior

2021-03-03T08:59:56.000Z Beginning step Publish
2021-03-03T08:59:56.000Z Error: Unable to find a publisher for URL: https://github.com/ravichadda/testingBackstage. Please make sure to register this host under an integration in app-config
    at Publishers.get (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts:43:13)
    at Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/legacy.ts:103:36)
    at TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:127:24)
    at async eval (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:53:9)

## Possible Solution
No Idea
## Steps to Reproduce

1. Step 1: Create http://localhost:8080/create/tasks/a9ad7f25-2a68-4f70-bc28-f6b4b4f11731
2. Step 2: Fill in all the required information
3. in creating process getting error as explained above.
## Your Environment

- NodeJS Version (v12):v14.15.5
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS 11.1
- Browser Information: Chrome

**Comment by OrkoHunter** [comment]
Do you have a `GITHUB_TOKEN` set with permission to create a new repository?
Related https://github.com/backstage/backstage/issues/4773

**Comment by ravichadda** [comment]
Yes, I have set the GITHUB_TOKEN as well.
integrations:
  github:
    - host: github.com
      token:
        $env: 14453b0814e316f41877ec8c3333ac6c40dbc148

Getting the same error: 
2021-03-03T17:23:54.000Z Beginning step Publish
2021-03-03T17:23:54.000Z Error: Unable to find a publisher for URL: https://github.com/ravichadda/backstage_microservice.git. Please make sure to register this host under an integration in app-config
    at Publishers.get (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts:43:13)
    at Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/legacy.ts:103:36)
    at TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:127:24)
    at async eval (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:53:9)

___________________________________________________________


We are not able to debug exactly where is the problem, in Backstage documentation not clearly explained what type of configuration(app-config) required to create the template.

If possible could you please schedule a call to discuss the issue.

Thanks

**Comment by freben** [comment]
@ravichadda Oops, don't paste tokens publicly - you should probably expire/rotate that one ASAP.

**Comment by ravichadda** [comment]
Yes, I have revoked it, Please suggest how do I resolve the above-said issue.

**Comment by adamdmharvey** [comment]
When using env, that means you're pulling it FROM an environment variable - not putting it IN your actual YAML file.

So I would have expected you to have one of two things.  Either,

```yaml
integrations:
  github:
    - host: github.com
      token:
        $env: GITHUB_TOKEN
```

Which comes straight out of the box, and then you set a local environment variable. So for example, for a local environment you could say,

```bash
$ GITHUB_TOKEN=1010101010101010 yarn dev
```

And the ALTERNATIVE, is to statically hardcode it just for testing purposes, ideally in an `app-config.local.yaml` (which will be ignored with `.gitignore`) and it would look like this:

```yaml
integrations:
  github:
    - host: github.com
      token: 101010101010101
```

What you pasted looked like maybe you were putting the value as ENV in your YAML.  Does that help at all?

**Comment by ravichadda** [comment]
I have added the same as you suggested 
integrations:
  github:
    - host: github.com
      token: 101010101010101

found another error :
2021-03-04T04:48:30.000Z Beginning step Publish
2021-03-04T04:48:30.000Z info: Will now store the template {"timestamp":"2021-03-04T04:48:30.724Z"}
2021-03-04T04:48:31.000Z HttpError: Repository creation failed.: {"resource":"Repository","code":"custom","field":"name","message":"name already exists on this account"}
    at /Users/vandanasharma/Documents/BackStage_Code/backstage/node_modules/@octokit/request/dist-node/index.js:66:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GithubPublisher.createRemote (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts:139:22)
    at async GithubPublisher.publish (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts:86:23)
    at async Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/legacy.ts:105:45)
    at async TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:127:11)
    at async eval (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:53:9)

Please suggest accordingly.

**Comment by OrkoHunter** [comment]
The error from GitHub
```
2021-03-04T04:48:31.000Z HttpError: Repository creation failed.: {"resource":"Repository","code":"custom","field":"name","message":"name already exists on this account"}
```

suggests that you are trying to create an already existing repository. :) Try `testingBackstage1` or something new.

**Comment by ravichadda** [comment]
I have tried the same "testingBackstage1", found the same error as:

2021-03-04T09:27:52.000Z Beginning step Publish
2021-03-04T09:27:52.000Z info: Will now store the template {"timestamp":"2021-03-04T09:27:52.680Z"}
2021-03-04T09:27:53.000Z HttpError: Repository creation failed.: {"resource":"Repository","code":"custom","field":"name","message":"name already exists on this account"}
    at /Users/vandanasharma/Documents/BackStage_Code/backstage/node_modules/@octokit/request/dist-node/index.js:66:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GithubPublisher.createRemote (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts:139:22)
    at async GithubPublisher.publish (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts:86:23)
    at async Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/legacy.ts:105:45)
    at async TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:127:11)
    at async eval (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:53:9)

**Comment by ravichadda** [comment]
I have commented on the code where the error is shown as "backstage/node_modules/@octokit/request/dist-node/index.js:66:23"

The commented code is:
 if (status >= 400) {
      // return response.text().then(message => {
      //   const error = new requestError.RequestError(message, status, {
      //     headers,
      //     request: requestOptions
      //   });

      //   try {
      //     let responseBody = JSON.parse(error.message);
      //     Object.assign(error, responseBody);
      //     let errors = responseBody.errors; // Assumption `errors` would always be in Array format

      //     error.message = error.message + ": " + errors.map(JSON.stringify).join(", ");
      //   } catch (e) {// ignore, see octokit/rest.js#684
      //   }

      //   throw error;
      // });
    }

__________________________________________________________________________

Than after tried again and found another error as:

2021-03-04T09:35:33.000Z info: Creating new remote {dir=/var/folders/1q/rxlpdn1d0x9d4x5w7kwb1fqw0000gn/T/8330c5f3-e385-4b1a-99c5-f46dfb3d97a3/result,remote=origin,url=undefined} {"timestamp":"2021-03-04T09:35:33.052Z"}
2021-03-04T09:35:33.000Z MissingParameterError: The function requires a "url" parameter but none was provided.
    at assertParameter (/Users/vandanasharma/Documents/BackStage_Code/backstage/node_modules/isomorphic-git/index.cjs:4329:11)
    at Object.addRemote (/Users/vandanasharma/Documents/BackStage_Code/backstage/node_modules/isomorphic-git/index.cjs:4996:5)
    at Git.addRemote (webpack-internal:///../backend-common/src/scm/git.ts:71:66)
    at initRepoAndPush (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/publish/helpers.ts:64:13)
    at async GithubPublisher.publish (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts:94:5)
    at async Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/legacy.ts:105:45)
    at async TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:127:11)
    at async eval (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:53:9)

**Comment by OrkoHunter** [comment]
So, I can see that the https://github.com/ravichadda/testingBackstage1 repository already exists but it's empty. Hence the "name already exists on this account" once again. @ravichadda Hopefully you are not creating the repository yourself, since Scaffolder is supposed to create that repository for you. So, please provide a URL in the create workflow to a repository which does not exist.

If the error happens again, it could be that Scaffolder is trying to create the repository twice.

**Comment by ravichadda** [comment]
The issue has been resolved. Thanks for your quick reply and support.

**Comment by OrkoHunter** [comment]
@ravichadda Nice to know! Could you share what worked out finally? (In case some looks at the issue in future)

**Comment by ravichadda** [comment]
Yes, Sure I will.
