### ISSUE TITLE
HttpError: Not Found     at /Users/Documents/BackStage_Code/my-app/node_modules/@octokit/request/dist-node/index.js:66:23

### ISSUE THREAD

**Issue by ravichadda** [backstage/backstage#4887]
2021-03-09T11:26:54.000Z Beginning step Publish
2021-03-09T11:26:54.000Z info: Will now store the template {"timestamp":"2021-03-09T11:26:54.685Z"}
2021-03-09T11:26:56.000Z HttpError: Not Found
    at /Users/vandanasharma/Documents/BackStage_Code/my-app/node_modules/@octokit/request/dist-node/index.js:66:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GithubPublisher.createRemote (/Users/vandanasharma/Documents/BackStage_Code/my-app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:514:7)
    at async GithubPublisher.publish (/Users/vandanasharma/Documents/BackStage_Code/my-app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:468:23)
    at async Object.handler (/Users/vandanasharma/Documents/BackStage_Code/my-app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:1676:45)
    at async TaskWorker.runOneTask (/Users/vandanasharma/Documents/BackStage_Code/my-app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2205:11)
    at async /Users/vandanasharma/Documents/BackStage_Code/my-app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2146:9

**Comment by jhaals** [comment]
Hi,
It's very hard to troubleshoot this with just the stacktrace. It looks like store path format could be the problem here. Can you provide information on the format of your store path and if possible also the template used.

The store path should be in the format of `https://github.com/myorg/somerepo`

**Comment by ravichadda** [comment]
I have created the store path as:

Http Port | 8080
-- | --
Component Id | new-service-development
Description | new-service-development
Owner | Ravi
Store Path | https://github.com/ravichadda/new-service-development-1
Access | Backend Team

**Comment by jhaals** [comment]
Looks like you managed to get it working by your github so I'm closing this now. Please reopen if the problem persists.
