### ISSUE TITLE
docs: Method of converting from SqlLite to PostgreSQL

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4974]
## Feature Suggestion

The documentation doesn't currently cover the steps needed to move cleanly from a newly templated Backstage app that was set to use SqlLite, to then convert it to using PostgreSQL.  As a pattern, it may be likely that a user:

* Templates a new app using `npx @backstage/create-app`
* Gets started by only selecting SqlLite
* (time passes... one week later) Wants to get a bit more advanced and now move their app to PostgreSQL
* After modifying `app-config.yaml` appropriately, getting a working available PostgreSQL system, the backend startup fails with a Node error about the pg library among others being missed

When you actually template a new app with PostgreSQL, you seem to also get the `pg` and `pg-connection-string` libraries listed in your `packages/backend/package.json` file.

## Possible Implementation

Ideally, there should be a quick paragraph that high-levels the steps necessary to move an already Backstage templated setting from SqlLite to PostgreSQL, as this is likely to be a common path.  Obviously, the nuances of every database can't be outlined, but even if it was just 2-3 steps like "run yarn add pg" then change your settings in app-config.yaml, that sort of thing.

## Context

My colleague @tom-halpin used the path above, and found some documentation on one of the Roadie repos for how to perform the `app-config.yaml` changes, and he did all of the Docker work himself, but got stuck when the backend failed throwing npm errors.

In the cloned repo for example, I see these in `packages/backend/package.json`:

```diff
 "express": "^4.17.1",
     "express-promise-router": "^3.0.3",
     "knex": "^0.95.1",
+    "pg": "^8.3.0",
+    "pg-connection-string": "^2.3.0",
     "sqlite3": "^5.0.0",
     "winston": "^3.2.1"
```

So maybe even the instructions should say remove SqlLite and add PG, or something like that - a clean way of doing it sort of. (or even just a pattern that says you only need these libraries for this, or these libraries for that, something like that)

**Comment by tom-halpin** [comment]
@adamdmharvey the relevant section from the logs as discussed

[1] Knex: run
[1] $ npm install pg --save
[1] Cannot find module 'pg'
[1] Require stack:
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/dialects/postgres/index.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/knex-builder/internal/config-resolver.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/knex-builder/Knex.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/index.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/knex.js
[1] - /home/tomh/backstage-dxc/node_modules/@backstage/backend-common/dist/index.cjs.js
[1] - /home/tomh/backstage-dxc/packages/backend/dist/main.js
[1] Error: Cannot find module 'pg'
[1] Require stack:
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/dialects/postgres/index.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/knex-builder/internal/config-resolver.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/knex-builder/Knex.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/index.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/knex.js
[1] - /home/tomh/backstage-dxc/node_modules/@backstage/backend-common/dist/index.cjs.js
[1] - /home/tomh/backstage-dxc/packages/backend/dist/main.js
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
[1]     at Module.require (internal/modules/cjs/loader.js:952:19)
[1]     at require (internal/modules/cjs/helpers.js:88:18)
[1]     at Client_PG._driver (/home/tomh/backstage-dxc/node_modules/knex/lib/dialects/postgres/index.js:48:12)
[1]     at Client_PG.initializeDriver (/home/tomh/backstage-dxc/node_modules/knex/lib/client.js:178:26)
[1]     at new Client (/home/tomh/backstage-dxc/node_modules/knex/lib/client.js:71:12)
[1]     at new Client_PG (/home/tomh/backstage-dxc/node_modules/knex/lib/dialects/postgres/index.js:18:5)
[1]     at Object.knex [as default] (/home/tomh/backstage-dxc/node_modules/knex/lib/knex-builder/Knex.js:12:28)
[1]     at createPgDatabaseClient (/home/tomh/backstage-dxc/node_modules/@backstage/backend-common/dist/index.cjs.js:79:51)
[1]     at ensurePgDatabaseExists (/home/tomh/backstage-dxc/node_modules/@backstage/backend-common/dist/index.cjs.js:109:17)
[1]     at ensureDatabaseExists (/home/tomh/backstage-dxc/node_modules/@backstage/backend-common/dist/index.cjs.js:156:12)
[1]     at SingleConnectionDatabaseManager.ensureDatabase (/home/tomh/backstage-dxc/node_modules/@backstage/backend-common/dist/index.cjs.js:192:11)
[1]     at SingleConnectionDatabaseManager.getDatabase (/home/tomh/backstage-dxc/node_modules/@backstage/backend-common/dist/index.cjs.js:180:16)
[1]     at Object.getClient (/home/tomh/backstage-dxc/node_modules/@backstage/backend-common/dist/index.cjs.js:172:22)
[1]     at CatalogBuilder.build (/home/tomh/backstage-dxc/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3071:68)
[1] Backend failed to start up, Error: Knex: run
[1] $ npm install pg --save
[1] Cannot find module 'pg'
[1] Require stack:
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/dialects/postgres/index.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/knex-builder/internal/config-resolver.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/knex-builder/Knex.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/lib/index.js
[1] - /home/tomh/backstage-dxc/node_modules/knex/knex.js
[1] - /home/tomh/backstage-dxc/node_modules/@backstage/backend-common/dist/index.cjs.js
[1] - /home/tomh/backstage-dxc/packages/backend/dist/main.js
[0] ℹ ｢wdm｣: wait until bundle finished: /

**Comment by adamdmharvey** [comment]
I believe Tom found if he just did `yarn add pg` to the backend, both PG and it's dependency `pg-connection-string` package was automatically installed (without needing to be specified).

**Comment by tom-halpin** [comment]
The key being to execute the command from the packages/backend folder as per @adamdmharvey's suggestion.

**Comment by freben** [comment]
Related: #4975
