### ISSUE TITLE
Error while running backstage application in Kubernetes

### ISSUE THREAD

**Issue by ravargs** [backstage/backstage#5004]
I deployed the backstage application through the helm charts and the template creation was failing with with a docker not found error. This was fixed through docker in docker but now it fails with this error .
> 2021-03-18T13:05:10.764Z {"status":"Extracting","progressDetail":{"current":23264053,"total":23264053},"progress":"[==================================================\u003e] 23.26 MB/23.26 MB","id":"681cae0a8229"}
2021-03-18T13:05:10.798Z {"status":"Pull complete","progressDetail":{},"id":"681cae0a8229"}
2021-03-18T13:05:10.947Z {"status":"Digest: sha256:0e2891bebc903eeedf7293cf75e9faad7539874e9d4e5e37da91760e2c8fab60"}
2021-03-18T13:05:10.990Z {"status":"Status: Downloaded newer image for spotify/backstage-cookiecutter:latest"}
2021-03-18T13:05:12.975Z DEBUG cookiecutter.config: User config not found. Loading default config.
2021-03-18T13:05:12.976Z A valid repository for "/input" could not be found in the following locations:
/input
/input
2021-03-18T13:05:13.554Z Error: Docker container returned a non-zero exit code (1)
    at Object.runDockerContainer (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:1811:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CookieCutter.run (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:706:7)
    at async Object.handler (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:1626:9)
    at async TaskWorker.runOneTask (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2180:11)
    at async /app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2121:9

Can you please confirm if
Backstage application is fully supported in Kubernetes platform? If so Docker in Docker setup is necessary?

**Comment by Rugvip** [comment]
Hi! See #2842, I believe this is the issue you're facing. `/template` was renamed to `/input` not long ago

**Comment by ravargs** [comment]
@Rugvip - Its looks like similar issue but I don't see this occurring when run from local development box. 
Where should I change the /input directory?

**Comment by Rugvip** [comment]
@ravargs sorry for the confusion, was just highlighting that the `/template` directory referred to in the logs in #2842 has been renamed to `/input`, meaning the logs are comparable. You do not need to rename any directory.

You'll want to try out https://github.com/backstage/backstage/issues/2842#issuecomment-749605527 as see if that fixes the issue for you

**Comment by niallmccullagh** [comment]
Just wanted to tag onto this issue and note that comment in #2842 about sharing `/tmp` worked for me. I created a shared volume and mounted it to `/tmp` on both the backend and docker dind sidecar.

**Comment by ravargs** [comment]
@niallmccullagh - Thanks, the same steps worked for me  as well.

**Comment by ravargs** [comment]
Issue is fixed by creating /tmp shared volume.
