### ISSUE TITLE
Catalog rules only apply to base definition, not applied to urls in catalog

### ISSUE THREAD

**Issue by bbgobie** [backstage/backstage#5482]
When a rule is applied to a URL, than any catalog components defined in that url should be allowed.  Currently it seems the rule is only applying directly to the component.

```
catalog: 
  locations: 
    - type: url 
      target: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/all-templates.yaml 
      rules: 
        - allow: [Template] 
```

Currently, templates are not allowed to be applied when found via a url

```
2021-04-26T19:28:49.532Z catalog warn Failed item in location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/create-react-app/template.yaml, NotAllowedError: Entity of kind Template is not allowed from location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/create-react-app/template.yaml
    at LocationReaders.read (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1034:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async HigherOrderOperations.refreshSingleLocation (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:936:26)
    at async HigherOrderOperations.refreshAllLocations (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:924:9)
    at async startRefresh (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:865:9) type=plugin component=catalog-all-locations-refresh
2021-04-26T19:28:49.533Z catalog warn Failed item in location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/docs-template/template.yaml, NotAllowedError: Entity of kind Template is not allowed from location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/docs-template/template.yaml
    at LocationReaders.read (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1034:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async HigherOrderOperations.refreshSingleLocation (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:936:26)
    at async HigherOrderOperations.refreshAllLocations (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:924:9)
    at async startRefresh (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:865:9) type=plugin component=catalog-all-locations-refresh
2021-04-26T19:28:49.533Z catalog warn Failed item in location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/react-ssr-template/template.yaml, NotAllowedError: Entity of kind Template is not allowed from location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/react-ssr-template/template.yaml
    at LocationReaders.read (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1034:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async HigherOrderOperations.refreshSingleLocation (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:936:26)
    at async HigherOrderOperations.refreshAllLocations (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:924:9)
    at async startRefresh (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:865:9) type=plugin component=catalog-all-locations-refresh
2021-04-26T19:28:49.534Z catalog warn Failed item in location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/springboot-grpc-template/template.yaml, NotAllowedError: Entity of kind Template is not allowed from location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/springboot-grpc-template/template.yaml
    at LocationReaders.read (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1034:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async HigherOrderOperations.refreshSingleLocation (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:936:26)
    at async HigherOrderOperations.refreshAllLocations (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:924:9)
    at async startRefresh (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:865:9) type=plugin component=catalog-all-locations-refresh
2021-04-26T19:28:49.534Z catalog warn Failed item in location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/v1beta2-demo/template.yaml, NotAllowedError: Entity of kind Template is not allowed from location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/v1beta2-demo/template.yaml
    at LocationReaders.read (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1034:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async HigherOrderOperations.refreshSingleLocation (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:936:26)
    at async HigherOrderOperations.refreshAllLocations (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:924:9)
    at async startRefresh (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:865:9) type=plugin component=catalog-all-locations-refresh
2021-04-26T19:28:49.535Z catalog warn Failed item in location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/pull-request/template.yaml, NotAllowedError: Entity of kind Template is not allowed from location url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates/pull-request/template.yaml
    at LocationReaders.read (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1034:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async HigherOrderOperations.refreshSingleLocation (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:936:26)
    at async HigherOrderOperations.refreshAllLocations (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:924:9)
    at async startRefresh (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:865:9) type=plugin component=catalog-all-locations-refresh
2021-04-26T19:28:49.535Z catalog warn Failed item in location url:https://github.com/spotify/cookiecutter-golang/tree/master/template.yaml, NotAllowedError: Entity of kind Template is not allowed from location url:https://github.com/spotify/cookiecutter-golang/tree/master/template.yaml
    at LocationReaders.read (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1034:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async HigherOrderOperations.refreshSingleLocation (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:936:26)
    at async HigherOrderOperations.refreshAllLocations (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:924:9)
    at async startRefresh (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:865:9) type=plugin component=catalog-all-locations-refresh
```

As a temporary workaround, you'd have to define all templates at the base catalog definition.

```
catalog:
  locations:
    - type: url
      target: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/all-templates.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/create-react-app/template.yaml
      rules:
        - allow: [Template] 
```

## Context
Would like to keep each catalog component seperate from the main app-config.yaml

## Your Environment

- NodeJS Version (v12): v14.16.1
- Operating System and Version (e.g. Ubuntu 14.04): Debian Buster-slim
- Browser Information: Firefox

**Comment by Rugvip** [comment]
This is actually intentional, but I'm wonder if it's something that we could change. We could potentially make rules that target a location with `Location` entities work transitively. Since we're already trusting the target location to not contain any bad entities, we could allow that trust to be carried forward. Could also be made an option on the rule if we want to experiment a bit with it

**Comment by freben** [comment]
Another option could be to permit the global allow list to also have a target URL. That is,

```yaml
catalog:
  rules:
    - allow: Location
      target: https://github.com/backstage/backstage/templates
```

but yeah. It's probably more convenient to have it carried over from the config locations.

**Comment by OldBlackJoe** [comment]
Is there any best practice of yaml achitecture for this case?
I only want to manage Domains through`./domains/*` path.
If I write all path of yaml files in `./domains/` to `app-config.yaml`, 
there is a problem that the contents of `app-config.yaml` becomes too long.

**Comment by freben** [comment]
Not right now. We hadn't taken transitiveness into account when building this feature so we'll have to address that - which will not happen in the very short term unfortunately, but it's on our radar.

One possible workaround could be to define your domains in a single (or just a few) file. You can have multiple definitions after each other, separated by a `---` line, as seen for example [here](https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/team-a-group.yaml).

**Comment by manusant** [comment]
Hi guys any idea if this is going to be tackled and when? I can see that this issue was reported in April and i'm a bit concerned because in our scenario (big organization with several independent projects) it has some relevance in the way we are tracking permissions at entities level. 
I've provided more details on issue #7191

**Comment by freben** [comment]
Hey! No distinct plans - but I'll take a quick look now to try to gauge what the effort / complexity is

**Comment by freben** [comment]
Alright, made a pull request that hopefully addresses this. #7270
