### ISSUE TITLE
Override techdocs docker image

### ISSUE THREAD

**Issue by shukla2009** [backstage/backstage#5495]
## Expected Behavior
Provision to pull techdocs image from mirror repo, as I am trying to install backstage behind the corporate proxy where https://registry-1.docker.io/v2/ is blocked, only option  for me is https://mycorporate-docker-reg/spotify/techdocs:latest

But I haven't found any docs to override the image 

## Current Behavior
Error
``` json
2021-04-27T15:45:24.000Z Error: (HTTP code 500) server error - Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.20.204.104:53: no such host 
    at /code/junk/backstage/nexus/node_modules/docker-modem/lib/modem.js:315:17
    at IncomingMessage.<anonymous> (/code/junk/backstage/nexus/node_modules/docker-modem/lib/modem.js:342:9)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

## Possible Solution

Allow techdocs config to override docker image

## Steps to Reproduce

1. Run backstage with no access to https://registry-1.docker.io/v2/ 

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 20.04):
- Browser Information:

**Comment by OrkoHunter** [comment]
In that case I'll recommend not using `techdocs-container` since it's a very lightweight docker image available to give you an out-of-the-box experience. You can install the underlying dependencies (mkdocs-techdocs-core, etc.) in your environment, and techdocs should be able to work.

Read more here https://backstage.io/docs/features/techdocs/getting-started#disabling-docker-in-docker-situation-optional

**Comment by OrkoHunter** [comment]
I think this issue will be closed by @andrewthauer's PR https://github.com/backstage/backstage/pull/6071
