### ISSUE TITLE
BitbucketPublisher ignores apiBaseUrl when communicating with Bitbucket API

### ISSUE THREAD

**Issue by mrjerzy** [backstage/backstage#5577]
In our company, we are running a self-hosted Bitbucket repository. It can be accessed via https://code.mycompany.com/bitbucket/ 
Therefore the base path for APIs is at `https://code.mycompany.com/bitbucket/rest/api/1.0/` (note the /bitbucket/ in the path)

The Scaffolder Backend plugin communicates during execution via HTTP with our Bitbucket instance. Unfortunately, the plugin assumes that the API base path is `https://code.mycompany.com/rest/api/1.0/`, (without a possibility to add /bitbucket in its path). This leads to HTTP 404 during the creation of a new repository

The behaviour is cased by `backstage/plugins/scaffolder-backend/src/scaffolder/stages/publish/bitbucket.ts` inside createBitbucketServerRepository, which injects the `host` variable from the config file in below line: 
https://github.com/backstage/backstage/blob/cbfa75bf69da90961daae517f28a106327ceb5d0/plugins/scaffolder-backend/src/scaffolder/stages/publish/bitbucket.ts#L185

Changing the host variable in the config file to mycompany.com/bitbucket does not work either. It will result in a `Backend failed to start up, Error: Invalid Bitbucket integration config, 'code.mycompany.com/bitbucket' is not a valid host`  

## Expected Behavior

During communication with Bitbucket, `integrations.bitbucket.apiBaseUrl` is pulled from the configuration

## Current Behavior

`integrations.bitbucket.host` is pulled to determine the path to bitbucket's REST APIs. It results in a HTTP 404  

## Possible Solution

change 
https://github.com/backstage/backstage/blob/cbfa75bf69da90961daae517f28a106327ceb5d0/plugins/scaffolder-backend/src/scaffolder/stages/publish/bitbucket.ts#L185 
to ```https://${this.config.apiBaseUrl}/projects/${project}/repos```

## Steps to Reproduce

- run a self hosted instance of Bitbucket server which has a customized REST API path 
- configure config.yaml with `integrations.bitbucket.host: code.mycompany.com` and `integrations.bitbucket.apiBaseUrl: https://code.mycompany.com/bitbucket/rest/api/1.0/` 
- in Backstage start scaffolder with preconfigured "Documentation Template" and fill in with any values 

## Context
I am not able to instanciate templates inside a self-hosted Bitbucket server with a customized api-base-path 

```
2021-05-04T14:54:49.323Z Error: Not a valid response code <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Not found</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /></body></html>
    at BitbucketPublisher.createBitbucketServerRepository (/app/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:434:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async BitbucketPublisher.publish (/app/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:338:20)
    at async Object.handler (/app/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:1932:45)
    at async TaskWorker.runOneTask (/app/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2484:11)
    at async /app/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2417:9```

This is caused, as the apiBasePath configuration is ignored in this step. 

## Your Environment

Docker container, based on node:14

**Comment by benjdlambert** [comment]
@mrjerzy is this something you want to contribute?
