### ISSUE TITLE
Generating techdocs from a provided example within docker container doesn't work

### ISSUE THREAD

**Issue by nadworny** [backstage/backstage#5712]
## Expected Behavior

When clicking on the `READ DOCS` link that is generated using this [example](https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/catalog-info.yaml) in the `Documentation`, the techdocs are properly displayed.

## Current Behavior

```
│ 2021-05-18T09:46:09.006Z techdocs info Step 2 of 3: Generating docs for entity Component:default/documented-component type=plugin                                                                      
2021-05-18T09:46:09.688Z techdocs error Build failed with error: DEBUG   -  Loading configuration file: /tmp/backstage-rKimYx/mkdocs.yml,DEBUG   -  Loaded theme configuration for 'mkdocs' from '/usr 
/local/lib/python3.7/dist-packages/mkdocs/themes/mkdocs/mkdocs_theme.yml': {'static_templates': ['404.html'], 'include_search_page': False, 'search_index_only': False, 'highlightjs': True, 'hljs_lan 
guages': [], 'hljs_style': 'github', 'navigation_depth': 2, 'nav_style': 'primary', 'shortcuts': {'help': 191, 'next': 78, 'previous': 80, 'search': 83}},DEBUG   -  Config value: 'config_file_path'  
= '/tmp/backstage-rKimYx/mkdocs.yml'                                                                                                                                                                   
DEBUG   -  Config value: 'site_name' = 'Example Documentation'                                                                                                                                         
DEBUG   -  Config value: 'nav' = [{'Home': 'index.md'}, {'Subpage': 'sub-page.md'}, {'Code Sample': 'code/code-sample.md'}, {'Extensions': 'extensions.md'}]                                           
DEBUG   -  Config value: 'pages' = None,DEBUG   -  Config value: 'site_url' = '',DEBUG   -  Config value: 'site_description' = None                                                                    
DEBUG   -  Config value: 'site_author' = None,DEBUG   -  Config value: 'theme' = Theme(name='mkdocs', dirs=['/usr/local/lib/python3.7/dist-packages/mkdocs/themes/mkdocs', '/usr/local/lib/python3.7/d 
ist-packages/mkdocs/templates'], static_templates=['sitemap.xml', '404.html'], include_search_page=False, search_index_only=False, highlightjs=True, hljs_languages=[], hljs_style='github', navigatio 
n_depth=2, nav_style='primary', shortcuts={'help': 191, 'next': 78, 'previous': 80, 'search': 83}),DEBUG   -  Config value: 'docs_dir' = '/tmp/backstage-rKimYx/docs',DEBUG   -  Config value: 'site_d 
ir' = '/tmp/techdocs-tmp-lYizwR'                                                                                                                                                                       
DEBUG   -  Config value: 'copyright' = None,DEBUG   -  Config value: 'google_analytics' = None                                                                                                         
DEBUG   -  Config value: 'dev_addr' = Address(host='127.0.0.1', port=8000),DEBUG   -  Config value: 'use_directory_urls' = True,DEBUG   -  Config value: 'repo_url' = '',DEBUG   -  Config value: 'rep 
o_name' = '',DEBUG   -  Config value: 'edit_uri' = '',DEBUG   -  Config value: 'extra_css' = [],DEBUG   -  Config value: 'extra_javascript' = [],DEBUG   -  Config value: 'extra_templates' = [],DEBUG 
   -  Config value: 'markdown_extensions' = ['toc', 'tables', 'fenced_code']                                                                                                                           
DEBUG   -  Config value: 'mdx_configs' = {},DEBUG   -  Config value: 'strict' = False,DEBUG   -  Config value: 'remote_branch' = 'gh-pages',DEBUG   -  Config value: 'remote_name' = 'origin',DEBUG    
-  Config value: 'extra' = {},DEBUG   -  Config value: 'plugins' = PluginCollection([('techdocs-core', <src.core.TechDocsCore object at 0x7f099dfe5278>)]),DEBUG   -  Loaded theme configuration for ' 
material' from '/usr/local/lib/python3.7/dist-packages/material/mkdocs_theme.yml': {'language': 'en', 'direction': None, 'features': [], 'palette': {'primary': None, 'accent': None}, 'font': {'text' 
: 'Roboto', 'code': 'Roboto Mono'}, 'icon': None, 'favicon': 'assets/images/favicon.png', 'include_search_page': False, 'search_index_only': True, 'static_templates': ['404.html']},INFO    -  Cleani 
ng site directory,INFO    -  Building documentation to directory: /tmp/techdocs-tmp-lYizwR,DEBUG   -  Reading markdown pages.                                                                          
DEBUG   -  Reading: index.md,DEBUG   -  Reading: extensions.md,ERROR   -  Error reading page 'extensions.md': Failed to run plantuml: [Errno 2] No such file or directory: 'plantuml': 'plantuml',Trac 
eback (most recent call last):                                                                                                                                                                         
  File "/usr/local/lib/python3.7/dist-packages/plantuml_markdown.py", line 268, in _render_local_uml_image                                                                                             
    p = Popen(cmdline, stdin=PIPE, stdout=PIPE, stderr=PIPE, shell=(os.name == 'nt'))                                                                                                                  
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__                                                                                                                                       
    restore_signals, start_new_session)                                                                                                                                                                
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child                                                                                                                                
    raise child_exception_type(errno_num, err_msg, err_filename)                                                                                                                                       
FileNotFoundError: [Errno 2] No such file or directory: 'plantuml': 'plantuml'                                                                                                                         
During handling of the above exception, another exception occurred:                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                     
  File "/usr/local/bin/mkdocs", line 10, in <module>                                                                                                                                                   
    sys.exit(cli())                                                                                                                                                                                    
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1134, in __call__                                                                                                                  
    return self.main(*args, **kwargs)
│     return self.main(*args, **kwargs)                                                                                                                                                                  
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1059, in main                                                                                                                      
    rv = self.invoke(ctx)                                                                                                                                                                              
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1665, in invoke                                                                                                                    
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                            
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1401, in invoke                                                                                                                    
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                     
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 767, in invoke                                                                                                                     
    return __callback(*args, **kwargs)                                                                                                                                                                 
  File "/usr/local/lib/python3.7/dist-packages/mkdocs/__main__.py", line 152, in build_command                                                                                                         
    build.build(config.load_config(**kwargs), dirty=not clean)                                                                                                                                         
  File "/usr/local/lib/python3.7/dist-packages/mkdocs/commands/build.py", line 271, in build                                                                                                           
    _populate_page(file.page, config, files, dirty)                                                                                                                                                    
  File "/usr/local/lib/python3.7/dist-packages/mkdocs/commands/build.py", line 171, in _populate_page                                                                                                  
    page.render(config, files)                                                                                                                                                                         
  File "/usr/local/lib/python3.7/dist-packages/mkdocs/structure/pages.py", line 175, in render                                                                                                         
    self.content = md.convert(self.markdown)                                                                                                                                                           
  File "/usr/local/lib/python3.7/dist-packages/markdown/core.py", line 260, in convert                                                                                                                 
    self.lines = prep.run(self.lines)                                                                                                                                                                  
  File "/usr/local/lib/python3.7/dist-packages/plantuml_markdown.py", line 124, in run                                                                                                                 
    text1, idx1 = self._replace_block(text[idx:])                                                                                                                                                      
  File "/usr/local/lib/python3.7/dist-packages/plantuml_markdown.py", line 181, in _replace_block                                                                                                      
    diagram = self._render_diagram(code, requested_format)                                                                                                                                             
  File "/usr/local/lib/python3.7/dist-packages/plantuml_markdown.py", line 253, in _render_diagram                                                                                                     
    diagram = self._render_local_uml_image(code, requested_format)                                                                                                                                     
  File "/usr/local/lib/python3.7/dist-packages/plantuml_markdown.py", line 271, in _render_local_uml_image                                                                                             
    raise Exception('Failed to run plantuml: %s' % exc)                                                                                                                                                
Exception: Failed to run plantuml: [Errno 2] No such file or directory: 'plantuml': 'plantuml' type=plugin                                                                                             
2021-05-18T09:46:09.689Z backstage error Failed to generate docs from /tmp/backstage-rKimYx into /tmp/techdocs-tmp-lYizwR with error undefined type=errorHandler stack=Error: Failed to generate docs  
from /tmp/backstage-rKimYx into /tmp/techdocs-tmp-lYizwR with error undefined                                                                                                                          
    at TechdocsGenerator.run (/app/node_modules/@backstage/techdocs-common/dist/index.cjs.js:213:13)                                                                                                   
    at runMicrotasks (<anonymous>)                                                                                                                                                                     
    at processTicksAndRejections (internal/process/task_queues.js:95:5)                                                                                                                                
    at async DocsBuilder.build (/app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:99:5)                                                                                           
    at async /app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:214:9
```

Content from mentioned directorie `/tmp/backstage-rKimYx`
```
|-- catalog-info.yaml
|-- docs
|   |-- code
|   |   `-- code-sample.md
|   |-- extensions.md
|   |-- images
|   |   `-- backstage-logo-cncf.svg
|   |-- index.md
|   `-- sub-page.md
`-- mkdocs.yml
```

## Steps to Reproduce

1. Create the app using `yarn backstage-create-app`
2. Add default example to the locations in `app-config.yaml`:
```
    - type: url
      target: https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/catalog-info.yaml
```
3. Use local setup:
```
techdocs:
  builder: 'local' # Alternatives - 'external'
  generators:
    techdocs: 'local' # Alternatives - 'docker'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3' or 'azureBlobStorage' or 'openStackSwift'. Read documentation for using alternatives.
```
4. Build docker image with mkdocs-techdocs-core==0.0.16 and start it. Alternatevily, start the backend locally with the mkdocs-techdocs-core==0.0.16 installed using pip.

## Context

See above.

## Your Environment
- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): using default Dockerfile, image running on AKS
- Used master branch for building, latest commit https://github.com/backstage/backstage/commit/f3f09dda341ff21fc1d55d088ee6698a638feb93

**Comment by OrkoHunter** [comment]
```
Exception: Failed to run plantuml: [Errno 2] No such file or directory: 'plantuml': 'plantuml' type=plugin                                                                                             
```

Looks like your Docker container doesn't have plantuml installed. You can use the [`techdocs-container`](https://github.com/backstage/techdocs-container/blob/main/Dockerfile) to see how to install that. (I'd recommend installing everything that's in the techdocs-container)

**Comment by nadworny** [comment]
Thanks @OrkoHunter . I've tried to install plantuml in the default Dockerfile generated by `yarn backstage-cli backend:bundle `. This is how it looks:
```Dockerfile
# This dockerfile builds an image for the backend package.
# It should be executed with the root of the repo as docker context.
#
# Before building this image, be sure to have run the following commands in the repo root:
#
# yarn install
# yarn tsc
# yarn build
#
# Once the commands have been run, you can build the image using `yarn build-image`

FROM node:14-buster-slim

WORKDIR /app

# Customization
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2

RUN apt-get update \
    && apt-get install -y python3 python3-pip gcc musl-dev openjdk-11-jdk curl graphviz ttf-dejavu fontconfig \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install cookiecutter==1.7.3 mkdocs-techdocs-core==0.0.16

# Download plantuml file, Validate checksum & Move plantuml file
RUN curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.4.jar/download && echo "be498123d20eaea95a94b174d770ef94adfdca18  plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar

# Create script to call plantuml.jar from a location in path
RUN echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
ADD yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./

RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)"

# Then copy the rest of the backend bundle, along with any other files we might want.
ADD packages/backend/dist/bundle.tar.gz app-config.yaml ./

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

Unfortunately, I'm getting now a different error:
```
│ 2021-05-18T16:04:11.854Z techdocs error Build failed with error: DEBUG   -  Loading configuration file: /tmp/backstage-seHBK1/mkdocs.yml,DEBUG   -  Loaded theme configuration for 'mkdocs' from '/usr │
│ DEBUG   -  Config value: 'site_name' = 'Example Documentation'                                                                                                                                         │
│ DEBUG   -  Config value: 'nav' = [{'Home': 'index.md'}, {'Subpage': 'sub-page.md'}, {'Code Sample': 'code/code-sample.md'}, {'Extensions': 'extensions.md'}]                                           │
│ DEBUG   -  Config value: 'pages' = None                                                                                                                                                                │
│ DEBUG   -  Config value: 'site_url' = ''                                                                                                                                                               │
│ DEBUG   -  Config value: 'site_description' = None                                                                                                                                                     │
│ DEBUG   -  Config value: 'site_author' = None,DEBUG   -  Config value: 'theme' = Theme(name='mkdocs', dirs=['/usr/local/lib/python3.7/dist-packages/mkdocs/themes/mkdocs', '/usr/local/lib/python3.7/d │
│ DEBUG   -  Config value: 'site_dir' = '/tmp/techdocs-tmp-fT9p59',DEBUG   -  Config value: 'copyright' = None,DEBUG   -  Config value: 'google_analytics' = None,DEBUG   -  Config value: 'dev_addr' =  │
│ DEBUG   -  Config value: 'use_directory_urls' = True,DEBUG   -  Config value: 'repo_url' = ''                                                                                                          │
│ DEBUG   -  Config value: 'repo_name' = '',DEBUG   -  Config value: 'edit_uri' = '',DEBUG   -  Config value: 'extra_css' = []                                                                           │
│ DEBUG   -  Config value: 'extra_javascript' = [],DEBUG   -  Config value: 'extra_templates' = []                                                                                                       │
│ DEBUG   -  Config value: 'markdown_extensions' = ['toc', 'tables', 'fenced_code'],DEBUG   -  Config value: 'mdx_configs' = {},DEBUG   -  Config value: 'strict' = False,DEBUG   -  Config value: 'remo │
│ DEBUG   -  Config value: 'remote_name' = 'origin',DEBUG   -  Config value: 'extra' = {},DEBUG   -  Config value: 'plugins' = PluginCollection([('techdocs-core', <src.core.TechDocsCore object at 0x7f │
│   File "/usr/local/lib/python3.7/dist-packages/plantuml_markdown.py", line 268, in _render_local_uml_image                                                                                             │
│     p = Popen(cmdline, stdin=PIPE, stdout=PIPE, stderr=PIPE, shell=(os.name == 'nt'))                                                                                                                  │
│   File "/usr/lib/python3.7/subprocess.py", line 775, in __init__                                                                                                                                       │
│     restore_signals, start_new_session)                                                                                                                                                                │
│   File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child                                                                                                                                │
│     raise child_exception_type(errno_num, err_msg, err_filename)                                                                                                                                       │
│ OSError: [Errno 8] Exec format error: 'plantuml'                                                                                                                                                       │
│ During handling of the above exception, another exception occurred:                                                                                                                                    │
│ Traceback (most recent call last):                                                                                                                                                                     │
│   File "/usr/local/bin/mkdocs", line 10, in <module>                                                                                                                                                   │
│     sys.exit(cli())                                                                                                                                                                                    │
│   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1134, in __call__                                                                                                                  │
│     return self.main(*args, **kwargs)                                                                                                                                                                  │
│   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1059, in main                                                                                                                      │
│     rv = self.invoke(ctx)                                                                                                                                                                              │
│   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1665, in invoke                                                                                                                    │
│     return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                            │
│   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1401, in invoke                                                                                                                    │
│     return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                     │
│   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 767, in invoke                                                                                                                     │
│     return __callback(*args, **kwargs)                                                                                                                                                                 │
│   File "/usr/local/lib/python3.7/dist-packages/mkdocs/__main__.py", line 152, in build_command                                                                                                         │
│     build.build(config.load_config(**kwargs), dirty=not clean)
│   File "/usr/local/lib/python3.7/dist-packages/mkdocs/commands/build.py", line 271, in build                                                                                                           │
│     _populate_page(file.page, config, files, dirty)                                                                                                                                                    │
│   File "/usr/local/lib/python3.7/dist-packages/mkdocs/commands/build.py", line 171, in _populate_page                                                                                                  │
│     page.render(config, files)                                                                                                                                                                         │
│   File "/usr/local/lib/python3.7/dist-packages/mkdocs/structure/pages.py", line 175, in render                                                                                                         │
│     self.content = md.convert(self.markdown)                                                                                                                                                           │
│   File "/usr/local/lib/python3.7/dist-packages/markdown/core.py", line 260, in convert                                                                                                                 │
│     self.lines = prep.run(self.lines)                                                                                                                                                                  │
│   File "/usr/local/lib/python3.7/dist-packages/plantuml_markdown.py", line 124, in run                                                                                                                 │
│     text1, idx1 = self._replace_block(text[idx:])                                                                                                                                                      │
│   File "/usr/local/lib/python3.7/dist-packages/plantuml_markdown.py", line 181, in _replace_block                                                                                                      │
│     diagram = self._render_diagram(code, requested_format)                                                                                                                                             │
│   File "/usr/local/lib/python3.7/dist-packages/plantuml_markdown.py", line 253, in _render_diagram                                                                                                     │
│     diagram = self._render_local_uml_image(code, requested_format)                                                                                                                                     │
│   File "/usr/local/lib/python3.7/dist-packages/plantuml_markdown.py", line 271, in _render_local_uml_image                                                                                             │
│     raise Exception('Failed to run plantuml: %s' % exc)                                                                                                                                                │
│ Exception: Failed to run plantuml: [Errno 8] Exec format error: 'plantuml' type=plugin                                                                                                                 │
│ 2021-05-18T16:04:11.855Z backstage error Failed to generate docs from /tmp/backstage-seHBK1 into /tmp/techdocs-tmp-fT9p59 with error undefined type=errorHandler stack=Error: Failed to generate docs  │
│     at TechdocsGenerator.run (/app/node_modules/@backstage/techdocs-common/dist/index.cjs.js:213:13)                                                                                                   │
│     at runMicrotasks (<anonymous>)                                                                                                                                                                     │
│     at processTicksAndRejections (internal/process/task_queues.js:95:5)                                                                                                                                │
│     at async DocsBuilder.build (/app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:99:5)
```

Would you recommend using the techdocs-container as basis image and add node and yarn stuff to it? Maybe you have an example of such a Dockerfile?

**Comment by OrkoHunter** [comment]
IMO you shouldn't be using techdocs-container as a base image to deploy your Backstage app. Here is [an example Dockerfile](https://github.com/backstage/backstage/blob/master/contrib/docker/kubernetes-example-backend/Dockerfile) for the app which also installs TechDocs related stuff (but misses out plantuml).

Could you investigate the container to see if `plantuml` is available in the PATH? We copy the executable over to `/usr/local/bin/` but maybe it's still not available at runtime.

**Comment by nadworny** [comment]
This is what I get when executing plantuml:
```bash
root@backstage-58d884fb65-7z5mr:/app# plantuml
/usr/local/bin/plantuml: line 1: 0!/bin/sh: No such file or directory
May 19, 2021 9:08:53 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
There is an issue with your server. You will find some tips here:
https://forum.plantuml.net/3399/problem-with-x11-and-headless-exception
https://plantuml.com/en/faq#239d64f675c3e515
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
	at java.desktop/java.awt.Window.<init>(Window.java:548)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at net.sourceforge.plantuml.swing.MainWindow2.<init>(MainWindow2.java:159)
	at net.sourceforge.plantuml.Run.main(Run.java:175)
```

**Comment by adrianke77** [comment]
I'm getting a similar error as that from @nadworny three messages above, `OSError: [Errno 8] Exec format error: 'plantuml'`

This is after adding the following lines from techdocs-container to my dockerfile:

```
RUN curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.4.jar/download && echo "be498123d20eaea95a94b174d770ef94adfdca18  plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar
RUN echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' &gt;&gt; /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml

**Comment by emmaindal** [comment]
Hey @adrianke77 re-opening this issue again. Just a follow-up question, are you able to run the techdocs-container and get it to successfully work? and this error happens when you add the plantuml related commans to your own dockerfile?

**Comment by nadworny** [comment]
@emmaindal you mean if I take the dockerfile for techdocs referenced by @OrkoHunter if the techdocs generation works locally? I haven't tried that...

**Comment by emmaindal** [comment]
yes @nadworny, just trying to investigate in what is missing compared with the Dockerfile in our techdocs container (which is working for me)

**Comment by adrianke77** [comment]
i take it running in backstage default uses `techdocs-container`? that seem to run the plantuml builds fine for me. I'm a little confused as i've pretty much copied the installs and setup from `techdocs-container` to our docker container and it's unclear why there's `Exec format error: 'plantuml' ` in the docker container case.

**Comment by adrianke77** [comment]
the dockerfile for our development container, in case it's a useful reference
```
FROM node:14-buster-slim

ARG TARGETPLATFORM="${TARGETPLATFORM:-linux/amd64}"
ARG TARGETOS="${TARGETOS:-linux}"
ARG TARGETARCH="${TARGETARCH:-amd64}"
ARG SHELLCHECK_VERSION="v0.7.1"
ARG YAMLLINT_VERSION="v1.24.2"

# needed for openjdk-11-jdk install (for PlantUML) as directory is not present on slim images
RUN mkdir -p /usr/share/man/man1

RUN apt-get update -y && \
  apt-get install -y \
    # For Backstage.
    git \
    # For shellcheck, yamllint, and the CI script.
    curl jq python3-distutils xz-utils \
    # Cypress dependencies
    libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 \
    procps xauth xvfb \
    # Chromium
    chromium \
    # TechDocs dependencies (GraphViz and PlantUML)
    openjdk-11-jdk \
    python-pydot \
    python-pydot-ng \
    gcc musl-dev curl ttf-dejavu fontconfig \
    graphviz \
    && \
  rm -rf /var/cache/apt/* /var/lib/apt/ßlists/* && \
  apt-get clean -y

RUN mkdir /tmp/shellcheck && \
  SHELLCHECK_ARCH=$([ "${TARGETARCH}" = "amd64" ] && echo x86_64 || echo ${TARGETARCH}) && \
  curl --silent --location --output /tmp/shellcheck/shellcheck.tar.xz "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.${TARGETOS}.${SHELLCHECK_ARCH}.tar.xz" && \
  tar -xJvf /tmp/shellcheck/shellcheck.tar.xz -C /tmp/shellcheck && \
  cp "/tmp/shellcheck/shellcheck-${SHELLCHECK_VERSION}/shellcheck" /usr/bin/ && \
  rm -rf /tmp/shellcheck

# Opt-out of sending Cypress exceptions.
ENV CYPRESS_CRASH_REPORTS=0

# Fake a dbus address to prevent errors. See
# https://github.com/cypress-io/cypress-docker-images/blob/b5a707e8f0977eabdba02dda2e455b8c64d94d71/browsers/node12.18.0-chrome83-ff77/Dockerfile#L22
ENV DBUS_SESSION_BUS_ADDRESS=/dev/null

RUN mkdir /tmp/pip && \
  curl --silent https://bootstrap.pypa.io/get-pip.py --output /tmp/pip/get-pip.py && \
  python3 /tmp/pip/get-pip.py && \
  rm -rf /tmp/pip && \
  pip3 install "yamllint==${YAMLLINT_VERSION}"

# TechDocs dependencies
RUN pip3 install \
    cookiecutter \
    mkdocs \
    mkdocs-techdocs-core \
    Markdown==3.2.2

# TechDocs - Download plantuml file, Validate checksum & Move plantuml file
RUN curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.4.jar/download && echo "be498123d20eaea95a94b174d770ef94adfdca18  plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar
RUN echo $'#!/bin/sh\n\njava -Djava.awt.headless=true -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml
```

**Comment by nadworny** [comment]
@adrianke77 @emmaindal I'm just guessing but there have to be some differences in regards to libraries between the base images that are being used by default backstage Dockerfile and the techdocs one...

**Comment by adrianke77** [comment]
@OrkoHunter I've been looking at this off and on the last week or so and have had no headway, partially also from not being sure how to debug python modules in this situation. Could you take a look at this again? My best effort at the docker container we use for development is below:
```
FROM node:14-buster-slim

ARG TARGETPLATFORM="${TARGETPLATFORM:-linux/amd64}"
ARG TARGETOS="${TARGETOS:-linux}"
ARG TARGETARCH="${TARGETARCH:-amd64}"
ARG SHELLCHECK_VERSION="v0.7.1"
ARG YAMLLINT_VERSION="v1.24.2"

# directory expected by openjdk-11-jdk install, missing in slim images
RUN mkdir /usr/share/man/man1/

RUN apt-get update -y && \
  apt-get install -y \
    # For Backstage.
    git \
    # For shellcheck, yamllint, and the CI script.
    curl jq python3-distutils xz-utils \
    # Cypress dependencies
    libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 \
    procps xauth xvfb \
    # Chromium∂
    chromium \
    # Graphviz
    python-pydot \
    python-pydot-ng \
    graphviz \
    # PlantUML
    openjdk-11-jdk \
    && \ldap

  rm -rf /var/cache/apt/* /var/lib/apt/lists/* && \
  apt-get clean -y

RUN mkdir /tmp/shellcheck && \
  SHELLCHECK_ARCH=$([ "${TARGETARCH}" = "amd64" ] && echo x86_64 || echo ${TARGETARCH}) && \
  curl --silent --location --output /tmp/shellcheck/shellcheck.tar.xz "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.${TARGETOS}.${SHELLCHECK_ARCH}.tar.xz" && \
  tar -xJvf /tmp/shellcheck/shellcheck.tar.xz -C /tmp/shellcheck && \
  cp "/tmp/shellcheck/shellcheck-${SHELLCHECK_VERSION}/shellcheck" /usr/bin/ && \
  rm -rf /tmp/shellcheck

# Cypress: opt-out of sending exceptions.
ENV CYPRESS_CRASH_REPORTS=0

# Cypress: fake a dbus address to prevent errors. See
# https://github.com/cypress-io/cypress-docker-images/blob/b5a707e8f0977eabdba02dda2e455b8c64d94d71/browsers/node12.18.0-chrome83-ff77/Dockerfile#L22
ENV DBUS_SESSION_BUS_ADDRESS=/dev/null

RUN mkdir /tmp/pip && \
  curl --silent https://bootstrap.pypa.io/get-pip.py --output /tmp/pip/get-pip.py && \
  python3 /tmp/pip/get-pip.py && \
  rm -rf /tmp/pip && \
  pip3 install "yamllint==${YAMLLINT_VERSION}"

# TechDocs dependencies
RUN pip3 install \
    cookiecutter \
    mkdocs \
    mkdocs-techdocs-core \
    Markdown==3.2.2

# Download plantuml file, Validate checksum & Move plantuml file
RUN curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.4.jar/download && echo "be498123d20eaea95a94b174d770ef94adfdca18  plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar

# Create script to call plantuml.jar from a location in path
RUN echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml
```

**Comment by nadworny** [comment]
@OrkoHunter @adrianke77 you won't believe but it's a one-liner 😮 
Before:
`RUN echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml`
After:
`RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml`

Just remove the first `$`. It seems that these different base images are interpreting this line differently.

**Comment by OrkoHunter** [comment]
Wow @nadworny ! I think the $ came from here https://github.com/backstage/techdocs-container/blob/7b7308f35b7e798928e83a00f27d651c4268737d/Dockerfile#L26

Perhaps update that dockerfile to say that in some cases $ is not required?

**Comment by adrianke77** [comment]
Confirmed to work. Thanks!
