### ISSUE TITLE
Cant run on raspberry Pi

### ISSUE THREAD

**Issue by AG-Labs** [backstage/backstage#5785]
I am trying to install on a Raspberry Pi following the instructions but cannot get it to work. I have tried both ubuntu and raspbian

## Expected Behavior

Should be able to run the backstage application on a Raspberry Pi
## Current Behavior

The install fails with the following error

## Possible Solution

Are there some prerequisites missing?

## Steps to Reproduce

1. Install Raspbian or Ubuntu on a Raspberry Pi 3
2. Install nvm and node --lts
3. Install yarn globally
4. Ensure sqlite is installed
5. Alias python to python3  
6. run npx @backstage/create-app with sqlite
```
error /home/ubuntu/spotify/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/ubuntu/spotify/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.17.0 | linux | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/home/ubuntu/spotify/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.2 and node@14.17.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.17.0 | linux | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.17.0 | linux | arm64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/ubuntu/spotify/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/ubuntu/spotify/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/ubuntu/spotify/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/ubuntu/spotify/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/ubuntu/spotify/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/ubuntu/spotify/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/ubuntu/spotify/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Linux 5.11.0-1007-raspi
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v14.17.0/bin/node" "/home/ubuntu/spotify/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/ubuntu/spotify/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/ubuntu/spotify/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /home/ubuntu/spotify/node_modules/sqlite3
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/ubuntu/.nvm/versions/node/v14.17.0/bin/node /home/ubuntu/spotify/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ubuntu/spotify/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/ubuntu/spotify/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/spotify/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.11.0-1007-raspi
node-pre-gyp ERR! command "/home/ubuntu/.nvm/versions/node/v14.17.0/bin/node" "/home/ubuntu/spotify/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/spotify/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.17.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/ubuntu/.nvm/versions/node/v14.17.0/bin/node /home/ubuntu/spotify/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ubuntu/spotify/node_modules/sql
```

## Your Environment

- NodeJS Version (v14):
- Operating System and Version: Ubuntu 14.04 & Raspbian
- 16Gb storage 
- 1GB Ram
- Raspberry Pi 3b

**Comment by freben** [comment]
The message says it can't find python and suggests a remediation - could you try that and try again and see if it helps?

**Comment by AG-Labs** [comment]
The python Env variable has been set in ~/.bashrc
Could my aliasing of it all to python3 have cause problems?
```
ubuntu@ubuntu:~/dev-portal$ echo $PYTHON
/usr/bin/python3
```

**Comment by jhaals** [comment]
Sounds from the error that node can't find python in the path, do you get the executable path to python by running `which python`?

**Comment by AG-Labs** [comment]
when I run which python I get nothing 
I guess I overestimated the ability of aliasing it to python3, ill sort this first.

**Comment by OrkoHunter** [comment]
@AG-Labs closing this issue due to the problem being missing Python. But please feel free to re-open if you find more errors !
