### ISSUE TITLE
TESTERS WANTED: Updated catalog processing engine

### ISSUE THREAD

**Issue by jhaals** [backstage/backstage#5869]
The next iteration of the software catalog has been in development for the last few months and is reaching a state where we want to do some pre-testing before doing the switchover.

We are therefore asking daring catalog users to help us test the catalog before it becomes the new default.

## How Do I Get Started?

First of all, **do NOT run against your production database**. The bootstrap location will be removed from the locations table and new tables will be created for storing the processed entities.

- Bump to the latest Backstage release, typically using `yarn backstage-cli versions:bump`.
- Run `EXPERIMENTAL_CATALOG=1 yarn start-backend` after you triple checked that you’re running against a copy or backup of your current catalog database.

## What Should I Expect?

We are 🤞 expecting it to “just work”, meaning you should be able to update entities and see entities appear in your catalog. Custom processors should continue to function as the processing API remains the same.

If you encounter anything out of the ordinary, just comment in this thread and we’ll promote it to a separate issue if needed. Also make sure to comment if you help out testing the new catalog as we don't have any way of knowing otherwise.

## What Has Changed Under The Hood?

The entire processing loop has been rewritten so that locations aren’t updated all at once. Instead each entity is refreshed individually every 100s. This is the same refresh time as the current catalog but we plan to make this configurable based on the requirements in the future.

You should also be able to run multiple instances of the catalog without multiplying the requests to your VSC provider as each entity is refreshed individually, in a collaborative fashion among the catalog service instances. Because of this new processing architecture, it is now also possible to scale the catalog processing horizontally by adding additional backend instances.

Entity deletion is also implemented, and entities that are no longer referenced by a location will be flagged as orphans, which is clearly visible in the UI.

**Comment by n2ygk** [comment]
Saw this FK constraint violation. My version of backstage is essentially the demo app (do a `git pull master` and merge onto my branch containing api-config.local.yaml ).
```
[1] 2021-06-02T16:18:13.669Z backstage info Loaded config from app-config.yaml, app-config.local.yaml 
[1] 2021-06-02T16:18:13.678Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucket{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.cc.columbia.edu,authed=false},gitlab{host=gitlab.com,authed=false},fetch{} 
[1] migration file "20210302150147_refresh_state.js" failed
[1] migration failed with error: delete from "locations" where "type" = $1 and "target" = $2 - update or delete on table "locations" violates foreign key constraint "entities_location_id_foreign" on table "entities"
[1] Backend failed to start up error: delete from "locations" where "type" = $1 and "target" = $2 - update or delete on table "locations" violates foreign key constraint "entities_location_id_foreign" on table "entities"
[1]     at Parser.parseErrorMessage (/Users/ac45/src/backstage/node_modules/pg-protocol/dist/parser.js:278:15)
[1]     at Parser.handlePacket (/Users/ac45/src/backstage/node_modules/pg-protocol/dist/parser.js:126:29)
[1]     at Parser.parse (/Users/ac45/src/backstage/node_modules/pg-protocol/dist/parser.js:39:38)
[1]     at Socket.<anonymous> (/Users/ac45/src/backstage/node_modules/pg-protocol/dist/index.js:10:42)
[1]     at Socket.emit (events.js:315:20)
[1]     at Socket.EventEmitter.emit (domain.js:467:12)
[1]     at addChunk (internal/streams/readable.js:309:12)
[1]     at readableAddChunk (internal/streams/readable.js:284:9)
[1]     at Socket.Readable.push (internal/streams/readable.js:223:10)
[1]     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
[1]   length: 329,
[1]   severity: 'ERROR',
[1]   code: '23503',
[1]   detail: 'Key (id)=(5ea722f5-f129-42fb-a842-a7d3be228976) is still referenced from table "entities".',
[1]   hint: undefined,
[1]   position: undefined,
[1]   internalPosition: undefined,
[1]   internalQuery: undefined,
[1]   where: undefined,
[1]   schema: 'public',
[1]   table: 'entities',
[1]   column: undefined,
[1]   dataType: undefined,
[1]   constraint: 'entities_location_id_foreign',
[1]   file: 'ri_triggers.c',
[1]   line: '2490',
[1]   routine: 'ri_ReportViolation'
[1] }
[0] ℹ ｢wdm｣: Compiled successfully.
```

**Comment by freben** [comment]
@n2ygk Oh this is when it already contained some data beforehand right? We'd better remove that constraint before deleting the so called `bootstrap` location. Thanks for reporting!

**Comment by freben** [comment]
Chose to empty the entities table instead; this is safer in a rollback scenario, since it would just be repopulated at next startup.

**Comment by jhaals** [comment]
Thanks for testing @n2ygk! 

@freben I did some tests this afternoon and I think we should keep the bootstrap location in order to easily roll between catalogs. It seems to work well in my tests.

**Comment by Fox32** [comment]
Haven't tested it yet, but I asking myself how big the impact of the refresh rate is. In our instance we have reduced the refresh rate to stay in the GitHub quota. Is the quota still that relevant as before? I remember that you planend to add more E-Tag based caching to calls to the GitHub API.

**Comment by jhaals** [comment]
@Fox32 the refresh rate is currently the same as today(100s), however if you run multiple catalog instances the new engine does not multiply the requests to GitHub. Cachable processing will be addressed separately as it will require some reworks of the processing API.

**Comment by jhaals** [comment]
@Fox32 I added a configurable refresh to the builder in #6007

**Comment by Rugvip** [comment]
Tasking period is over and the new catalog is going out in the next release, thanks!

**Comment by dehamzah** [comment]
I tested to rename the entity name from uppercase to lowercase and it works.

but what is the expected behavior if I rename the entity name to a different name? 
I tried this and the old entity name is still listed in the catalog. Is the old entity name is considered an orphan? If yes, should the expected behavior is showing the banner orphan in the catalog detail page?

**Comment by freben** [comment]
You mean if you rename the entity in the yaml file and wait for the catalog to refresh from it?

Yes, that will lead to the old one staying around and being marked (and shown in the GUI) as orphaned, and the new one appearing separately. This is intentional, since there is no safe way for us to know what you actually intended.

**Comment by dehamzah** [comment]
Yes, I am changing the entity name in the YAML file and wait for the catalog to refresh it.

Thank you for the answer, I now realized from this PR https://github.com/backstage/backstage/pull/5707, I need to implement the banner component manually in my backstage app. The response API returning extra annotation `'backstage.io/orphan': 'true'` as expected. Thank you 👍🏼

**Comment by benlangfeld** [comment]
@freben When the catalog is in read-only mode, can auto-deletion of orphaned entities be considered safe? Would backstage accept an implementation of auto-deletion that is disabled by default?
