### ISSUE TITLE
Unable to build new app in docker

### ISSUE THREAD

**Issue by mafrosis** [backstage/backstage#5947]
Using the [recommended docker install guidance](https://backstage.io/docs/deployment/docker) I am unable to get a working instance of Backstage.

## Expected Behavior

Backstage should come up.

## Current Behavior

Following exception is thrown at start up:

```
Attaching to backstage_1
backstage_1  | internal/modules/cjs/loader.js:316
backstage_1  |       throw err;
backstage_1  |       ^
backstage_1  |
backstage_1  | Error: Cannot find module '/app/node_modules/@gitbeaker/node/dist/index.js'. Please verify that the package.json has a valid "main" entry
backstage_1  |     at tryPackage (internal/modules/cjs/loader.js:308:19)
backstage_1  |     at Function.Module._findPath (internal/modules/cjs/loader.js:521:18)
backstage_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
backstage_1  |     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
backstage_1  |     at Module.require (internal/modules/cjs/loader.js:957:19)
backstage_1  |     at require (internal/modules/cjs/helpers.js:88:18)
backstage_1  |     at Object.<anonymous> (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:16:12)
backstage_1  |     at Module._compile (internal/modules/cjs/loader.js:1068:30)
backstage_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
backstage_1  |     at Module.load (internal/modules/cjs/loader.js:933:32)
backstage_1  |     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
backstage_1  |     at Module.require (internal/modules/cjs/loader.js:957:19)
backstage_1  |     at require (internal/modules/cjs/helpers.js:88:18)
backstage_1  |     at Object.<anonymous> (/app/packages/backend/dist/index.cjs.js:9:31)
backstage_1  |     at Module._compile (internal/modules/cjs/loader.js:1068:30)
backstage_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
backstage_1  |   code: 'MODULE_NOT_FOUND',
backstage_1  |   path: '/app/node_modules/@gitbeaker/node/package.json',
backstage_1  |   requestPath: '@gitbeaker/node'
backstage_1  | }
backstage_1 exited with code 1
```

## Steps to Reproduce

Full shell log here follows:

```
> npx @backstage/create-app
npx: installed 70 in 8.904s
? Enter a name for the app [required] test
? Select database for the backend [required] SQLite

Creating the app...

 Checking if the directory is available:
  checking      test ✔

 Creating a temporary app directory:
  creating      temporary directory ✔

 Preparing files:
  copying       .eslintrc.js ✔
  copying       README.md ✔
  copying       .dockerignore ✔
  copying       app-config.production.yaml ✔
  templating    .gitignore.hbs ✔
  templating    app-config.yaml.hbs ✔
  copying       lerna.json ✔
  templating    catalog-info.yaml.hbs ✔
  copying       tsconfig.json ✔
  templating    package.json.hbs ✔
  copying       README.md ✔
  copying       Dockerfile ✔
  copying       .eslintrc.js ✔
  templating    package.json.hbs ✔
  copying       index.test.ts ✔
  copying       index.ts ✔
  copying       types.ts ✔
  copying       app.ts ✔
  copying       catalog.ts ✔
  copying       auth.ts ✔
  copying       scaffolder.ts ✔
  copying       techdocs.ts ✔
  copying       proxy.ts ✔
  copying       .eslintrc.js ✔
  copying       cypress.json ✔
  templating    package.json.hbs ✔
  copying       apple-touch-icon.png ✔
  copying       android-chrome-192x192.png ✔
  copying       favicon-16x16.png ✔
  copying       favicon-32x32.png ✔
  copying       favicon.ico ✔
  copying       index.html ✔
  copying       manifest.json ✔
  copying       robots.txt ✔
  copying       safari-pinned-tab.svg ✔
  copying       .eslintrc.json ✔
  copying       app.js ✔
  copying       App.test.tsx ✔
  copying       App.tsx ✔
  copying       apis.ts ✔
  copying       index.tsx ✔
  copying       setupTests.ts ✔
  copying       EntityPage.tsx ✔
  copying       LogoFull.tsx ✔
  copying       LogoIcon.tsx ✔
  copying       index.ts ✔
  copying       Root.tsx ✔

 Moving to final location:
  moving        test ✔

 Building the app:
  executing     yarn install ✔
  executing     yarn tsc ✔

🥇  Successfully created test


 All set! Now you might want to:
  Run the app: cd test && yarn dev
  Set up the software catalog: https://backstage.io/docs/features/software-catalog/configuration
  Add authentication: https://backstage.io/docs/auth/

> cd test

/test > yarn install --frozen-lockfile
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.31s.

/test > yarn tsc
yarn run v1.22.10
$ tsc
✨  Done in 8.22s.

/test > yarn build
yarn run v1.22.10
$ lerna run build
lerna notice cli v4.0.0
lerna info Executing command in 2 packages: "yarn run build"
lerna info run Ran npm script 'build' in 'app' in 74.3s:
$ backstage-cli app:build
  309.59 KB  dist/static/vendor.f83ff6c7.chunk.js
  269.93 KB  dist/static/module-highlight.js.8c153aff.js
  173.25 KB  dist/static/module-refractor.708e2d4b.js
  163.04 KB  dist/static/40.30961237.chunk.js
  141.92 KB  dist/static/module-swagger-ui-react.6716130b.js
  139.78 KB  dist/static/module-backstage.e5c35566.js
  112.8 KB   dist/static/module-jspdf.005cfd8e.js
  105.41 KB  dist/static/module-material-ui.891d9484.js
  70.15 KB   dist/static/module-moment.eadbb464.js
  56.38 KB   dist/static/module-asyncapi.b90faa71.js
  56.11 KB   dist/static/38.f6ae6fb0.chunk.js
  52.92 KB   dist/static/3.7f89cb10.chunk.js
  46.14 KB   dist/static/39.3aba64a4.chunk.js
  41.63 KB   dist/static/module-material-table.85f97b32.js
  39.68 KB   dist/static/56.bcc72d54.chunk.js
  37.16 KB   dist/static/module-graphql.4aa51fc3.js
  36.12 KB   dist/static/module-lodash.0adc492d.js
  35.78 KB   dist/static/module-hot-loader.2a42eef4.js
  28.74 KB   dist/static/module-esprima.71997d3d.js
  28.33 KB   dist/static/module-yaml.0e7c91c2.js
  27.87 KB   dist/static/module-react-beautiful-dnd.655311b4.js
  26.67 KB   dist/static/module-react-syntax-highlighter.6c9aa4a3.js
  21.98 KB   dist/static/module-ajv.704ac17b.js
  21.53 KB   dist/static/swagger-ui-react.34.d61cb0bd.css
  20.98 KB   dist/static/module-luxon.5aa2a5a6.js
  19.81 KB   dist/static/module-apidevtools.a009f449.js
  18.66 KB   dist/static/module-autolinker.eb947b63.js
  17.37 KB   dist/static/module-octokit.d2593ba3.js
  16.92 KB   dist/static/module-sanitize-html.e55f567c.js
  15.31 KB   dist/static/module-immutable.9e0b2d22.js
  13.51 KB   dist/static/module-remarkable.2908ec84.js
  13.3 KB    dist/static/module-yaml-ast-parser.bac340f9.js
  12.31 KB   dist/static/module-js-yaml.aa1cc95b.js
  12.2 KB    dist/static/module-micromark.f03cd307.js
  10.23 KB   dist/static/module-json-to-ast.1e325eea.js
  10.18 KB   dist/static/module-date-fns.b6573e0b.js
  9.25 KB    dist/static/module-lodash-es.19efe9e5.js
  7.9 KB     dist/static/main.e93ed839.chunk.js
  7.59 KB    dist/static/vendor.35.8c496d5a.css
  4.71 KB    dist/static/asyncapi.7.a98603d5.css
  4.4 KB     dist/static/57.22619912.chunk.js
  1.83 KB    dist/static/48.6dd2fabf.chunk.js
  1.39 KB    dist/static/46.8df1f785.chunk.js
  1.39 KB    dist/static/runtime.e3e2bdac.js
  860 B      dist/static/42.d34bf149.chunk.js
  846 B      dist/static/47.c14cd939.chunk.js
  845 B      dist/static/41.6aa08ccf.chunk.js
  838 B      dist/static/43.fbcf7415.chunk.js
  838 B      dist/static/44.eb376229.chunk.js
  838 B      dist/static/45.9b3506cb.chunk.js
  268 B      dist/static/51.e5dc35b2.chunk.js
  262 B      dist/static/49.91c0e686.chunk.js
  249 B      dist/static/0.0a0d21a4.chunk.js
  247 B      dist/static/1.8691d779.chunk.js
  245 B      dist/static/4.53222838.chunk.js
  244 B      dist/static/2.70d192e4.chunk.js
  228 B      dist/static/50.e6bec5fb.chunk.js
  222 B      dist/static/52.ae30293b.chunk.js
  220 B      dist/static/53.919c01ae.chunk.js
  214 B      dist/static/55.a0dd9bfe.chunk.js
  211 B      dist/static/54.659fc740.chunk.js
lerna info run Ran npm script 'build' in 'backend' in 5.5s:
$ backstage-cli backend:bundle
Repacking backend into dist workspace
Repacking app into dist workspace
success Wrote tarball to "/var/folders/9x/9fkh7ppx14b6qn2xdmd6zz900000gp/T/backstage-bundleNCNhB2/temp-package-0.tgz".
success Wrote tarball to "/var/folders/9x/9fkh7ppx14b6qn2xdmd6zz900000gp/T/backstage-bundleNCNhB2/temp-package-1.tgz".
lerna success run Ran npm script 'build' in 2 packages in 79.8s:
lerna success - app
lerna success - backend
✨  Done in 80.35s.

/test > DOCKER_BUILDKIT=0 docker image build . -f packages/backend/Dockerfile --tag backstage-test
Sending build context to Docker daemon  10.33MB
Step 1/8 : FROM node:14-buster-slim
 ---> d4c353c8e216
Step 2/8 : WORKDIR /app
 ---> Running in 6e4f94ee8303
Removing intermediate container 6e4f94ee8303
 ---> 1464e2cbc0ac
Step 3/8 : COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
 ---> 47b44af988ef
Step 4/8 : RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz
 ---> Running in 3665338d7ce0
Removing intermediate container 3665338d7ce0
 ---> d5646ed8de5d
Step 5/8 : RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)"
 ---> Running in 4905741091d9
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > graphql-language-service-interface@2.8.2" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "graphql-language-service-interface > graphql-language-service-types@1.8.2" has unmet peer dependency "graphql@>= v14.5.0 <= 15.5.0".
warning "graphql-language-service-interface > graphql-language-service-utils@2.5.3" has unmet peer dependency "graphql@>= v14.5.0 <= 15.5.0".
warning " > graphql-language-service-parser@1.9.0" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@backstage/cli > react-hot-loader@4.13.0" has unmet peer dependency "react-dom@^15.0.0 || ^16.0.0 || ^17.0.0 ".
warning "@backstage/cli > rollup-plugin-dts@2.0.1" has incorrect peer dependency "rollup@^2.34.2".
warning " > @spotify/prettier-config@7.0.0" has incorrect peer dependency "prettier@2.x".
warning "workspace-aggregator-4e061e73-463e-46ad-a528-be37ec9dfa70 > backend > @backstage/plugin-auth-backend > @backstage/test-utils > @testing-library/user-event@13.1.9" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "workspace-aggregator-4e061e73-463e-46ad-a528-be37ec9dfa70 > backend > @backstage/plugin-auth-backend > @backstage/test-utils > react-router@6.0.0-beta.0" has unmet peer dependency "history@>=5".
warning "workspace-aggregator-4e061e73-463e-46ad-a528-be37ec9dfa70 > backend > @backstage/plugin-auth-backend > @backstage/test-utils > react-router-dom@6.0.0-beta.0" has unmet peer dependency "history@>=5".
[5/5] Building fresh packages...
Done in 94.92s.
Removing intermediate container 4905741091d9
 ---> 26e0f901115a
Step 6/8 : COPY packages/backend/dist/bundle.tar.gz app-config.yaml ./
 ---> fb4e1b04cf0e
Step 7/8 : RUN tar xzf bundle.tar.gz && rm bundle.tar.gz
 ---> Running in 1bebcc61b5f4
Removing intermediate container 1bebcc61b5f4
 ---> d992c48d6b99
Step 8/8 : CMD ["node", "packages/backend", "--config", "app-config.yaml"]
 ---> Running in da9612c272c1
Removing intermediate container da9612c272c1
 ---> 2425bffded46
Successfully built 2425bffded46
Successfully tagged backstage-test:latest
 
/test > docker run -it -p 7000:7000 backstage-test
internal/modules/cjs/loader.js:316
      throw err;
      ^

Error: Cannot find module '/app/node_modules/@gitbeaker/node/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:308:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:521:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:16:12)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/packages/backend/dist/index.cjs.js:9:31)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
  code: 'MODULE_NOT_FOUND',
  path: '/app/node_modules/@gitbeaker/node/package.json',
  requestPath: '@gitbeaker/node'
}
```

## Context

A new user trying the software.

Very experienced software/devops engineer, with little useful node experience.

## Your Environment

macOS Big Sur
node v14.17.0

**Comment by chicoribas** [comment]
A possible workaround is fixing the resolution in the package.json to the last version without this issue:

```
"resolutions": {
    "@gitbeaker/node": "29.2.4",
    "@gitbeaker/core": "29.2.4",
    "@gitbeaker/requester-utils": "29.2.4"
  }
```
