### ISSUE TITLE
create-app generates an error and does not complete

### ISSUE THREAD

**Issue by yonimoses** [backstage/backstage#6125]
using node 14 and yarn 2 (rc4) 
create-app generates the following

`Building the app:
  executing     yarn install ◠ ➤ YN0000: ┌ Resolution step
➤ YN0032: │ node-addon-api@npm:3.2.1: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ keytar@npm:7.7.0: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ nan@npm:2.14.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ @backstage/cli@npm:0.7.1 doesn't provide react-dom@^15.0.0 || ^16.0.0 || ^17.0.0  requested by react-hot-loader@npm:4.13.0
➤ YN0060: │ @backstage/cli@npm:0.7.1 provides rollup@npm:2.44.0 with version 2.44.0 which doesn't satisfy ^2.48.0 requested by rollup-plugin-dts@npm:3.0.2
➤ YN0002: │ rollup-plugin-esbuild@npm:2.6.1 [31d89] doesn't provide rollup@^1.20.0||^2.0.0 requested by @rollup/pluginutils@npm:4.1.0
➤ YN0060: │ root@workspace:. provides prettier@npm:1.19.1 with version 1.19.1 which doesn't satisfy 2.x requested by @spotify/prettier-config@npm:7.0.0
➤ YN0002: │ @backstage/theme@npm:0.2.8 doesn't provide react@^16.8.0 || ^17.0.0 requested by @material-ui/core@npm:4.11.4
➤ YN0002: │ @backstage/theme@npm:0.2.8 doesn't provide react-dom@^16.8.0 || ^17.0.0 requested by @material-ui/core@npm:4.11.4
➤ YN0002: │ @backstage/core-plugin-api@npm:0.1.2 doesn't provide react-dom@^16.8.0 || ^17.0.0 requested by @material-ui/core@npm:4.11.4
➤ YN0002: │ @backstage/core-plugin-api@npm:0.1.2 doesn't provide react-dom@>=16.8 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/core-plugin-api@npm:0.1.2 doesn't provide react-dom@^16.8.0  || ^17.0.0 requested by react-use@npm:17.2.4
➤ YN0002: │ @backstage/core-api@npm:0.2.22 doesn't provide react-dom@^16.8.0 || ^17.0.0 requested by @material-ui/core@npm:4.11.4
➤ YN0002: │ @backstage/core-api@npm:0.2.22 doesn't provide react-dom@^16.8.0 || ^17.0.0 requested by @material-ui/icons@npm:4.11.2
➤ YN0002: │ @backstage/core-api@npm:0.2.22 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/core-api@npm:0.2.22 doesn't provide react-dom@>=16.8 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/core-api@npm:0.2.22 doesn't provide react-dom@^16.8.0  || ^17.0.0 requested by react-use@npm:17.2.4
➤ YN0002: │ @backstage/core@npm:0.7.13 doesn't provide @date-io/core@^1.3.6 requested by material-table@npm:1.69.3
➤ YN0002: │ @backstage/core@npm:0.7.13 doesn't provide react-test-renderer@>=16.9.0 requested by @testing-library/react-hooks@npm:3.7.0
➤ YN0002: │ cypress@npm:7.5.0 doesn't provide enquirer@>= 2.3.0 < 3 requested by listr2@npm:3.10.0
➤ YN0002: │ @backstage/plugin-catalog-react@npm:0.2.3 doesn't provide react-dom@^16.8.0 || ^17.0.0 requested by @material-ui/core@npm:4.11.4
➤ YN0002: │ @backstage/plugin-catalog-react@npm:0.2.3 doesn't provide react-dom@^16.8.0 || ^17.0.0 requested by @material-ui/icons@npm:4.11.2
➤ YN0002: │ @backstage/plugin-catalog-react@npm:0.2.3 doesn't provide react-dom@^16.8.0 requested by @material-ui/lab@npm:4.0.0-alpha.45
➤ YN0002: │ @backstage/plugin-catalog-react@npm:0.2.3 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-catalog-react@npm:0.2.3 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-catalog-react@npm:0.2.3 doesn't provide react-dom@>=16.8 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-catalog-react@npm:0.2.3 doesn't provide react-dom@^16.8.0  || ^17.0.0 requested by react-use@npm:17.2.4
➤ YN0002: │ @backstage/plugin-catalog@npm:0.6.3 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-catalog@npm:0.6.3 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @asyncapi/react-component@npm:0.23.1 doesn't provide react@^16.8.0 requested by constate@npm:1.3.2
➤ YN0002: │ @asyncapi/react-component@npm:0.23.1 doesn't provide react@^16.8.0 requested by react-use@npm:12.13.0
➤ YN0002: │ @asyncapi/react-component@npm:0.23.1 doesn't provide react-dom@^16.8.0 requested by react-use@npm:12.13.0
➤ YN0002: │ @backstage/plugin-api-docs@npm:0.5.0 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-api-docs@npm:0.5.0 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-catalog-import@npm:0.5.10 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-catalog-import@npm:0.5.10 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-github-actions@npm:0.4.9 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-github-actions@npm:0.4.9 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ react-lazylog@npm:4.5.3 [3de39] doesn't provide react-dom@^15.3.0 || ^16.0.0-alpha requested by react-virtualized@npm:9.22.3
➤ YN0002: │ @backstage/plugin-org@npm:0.3.14 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-org@npm:0.3.14 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-scaffolder@npm:0.9.8 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-scaffolder@npm:0.9.8 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ react-lazylog@npm:4.5.3 [09223] doesn't provide react-dom@^15.3.0 || ^16.0.0-alpha requested by react-virtualized@npm:9.22.3
➤ YN0002: │ @backstage/plugin-search@npm:0.4.0 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-search@npm:0.4.0 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-techdocs@npm:0.9.6 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-techdocs@npm:0.9.6 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/plugin-user-settings@npm:0.2.11 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/test-utils@npm:0.1.13 doesn't provide history@>=5 requested by react-router@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/test-utils@npm:0.1.13 doesn't provide history@>=5 requested by react-router-dom@npm:6.0.0-beta.0
➤ YN0002: │ @backstage/test-utils@npm:0.1.13 doesn't provide @testing-library/dom@>=7.21.4 requested by @testing-library/user-event@npm:13.1.9
➤ YN0002: │ app@workspace:packages/app doesn't provide eslint@>= 3.2.1 requested by eslint-plugin-cypress@npm:2.11.3
➤ YN0002: │ app@workspace:packages/app doesn't provide @testing-library/dom@>=7.21.4 requested by @testing-library/user-event@npm:12.8.3
➤ YN0000: └ Completed in 2.62m
➤ YN0000: ┌ Fetch step
➤ YN0013: │ @backstage/plugin-search-backend@npm:0.2.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ @microsoft/microsoft-graph-types@npm:1.41.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ fork-ts-checker-webpack-plugin@npm:6.2.12 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=e8cd9e can't be found in the cache and will be fetched from the disk
➤ YN0001: │ Error: fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=e8cd9e: Cannot apply hunk #1
    at c (/usr/local/lib/node_modules/yarn/bin/yarn.js:111:195461)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/local/lib/node_modules/yarn/bin/yarn.js:111:197592
    at async o (/usr/local/lib/node_modules/yarn/bin/yarn.js:111:194744)
    at async Object.t.applyPatchFile (/usr/local/lib/node_modules/yarn/bin/yarn.js:111:197565)
    at async t.PatchFetcher.patchPackage (/usr/local/lib/node_modules/yarn/bin/yarn.js:111:194499)
    at async /usr/local/lib/node_modules/yarn/bin/yarn.js:111:193805
    at async /usr/local/lib/node_modules/yarn/bin/yarn.js:51:278366
    at async /usr/local/lib/node_modules/yarn/bin/yarn.js:51:278309
➤ YN0013: │ typescript@patch:typescript@npm%3A4.3.4#builtin<compat/typescript>::version=4.3.4&hash=226bd1 can't be found in the cache and will be fetched from the disk
➤ YN0001: │ Error: typescript@patch:typescript@npm%3A4.3.4#builtin<compat/typescript>::version=4.3.4&hash=226bd1: Cannot apply hunk #1
    at c (/usr/local/lib/node_modules/yarn/bin/yarn.js:111:195461)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/local/lib/node_modules/yarn/bin/yarn.js:111:197592
    at async o (/usr/local/lib/node_modules/yarn/bin/yarn.js:111:194744)
    at async Object.t.applyPatchFile (/usr/local/lib/node_modules/yarn/bin/yarn.js:111:197565)
    at async t.PatchFetcher.patchPackage (/usr/local/lib/node_modules/yarn/bin/yarn.js:111:194499)
    at async /usr/local/lib/node_modules/yarn/bin/yarn.js:111:193805
    at async /usr/local/lib/node_modules/yarn/bin/yarn.js:51:278366
    at async /usr/local/lib/node_modules/yarn/bin/yarn.js:51:278309
➤ YN0000: └ Completed in 15.47s
➤ YN0000: Failed with errors in 2.88m
`

any suggestions?

**Comment by yonimoses** [comment]
downgraded to yarn 1.* and the problem went away.

**Comment by yonimoses** [comment]
downgraded yarn to 1.* ..
