### ISSUE TITLE
"Failed to load entity types" after upgrade to release-2021-06-24

### ISSUE THREAD

**Issue by axdotl** [backstage/backstage#6215]
After upgrading from [release-2021-06-17.1](https://github.com/backstage/backstage/releases/tag/release-2021-06-17.1) to [release-2021-06-24](https://github.com/backstage/backstage/releases/tag/release-2021-06-24) an error occurs on catalog page (`/catalog`) and the entity type picker is not shown.

## Expected Behavior

Loading catalog page should work w/o errors.

## Current Behavior

An error occurs on catalog page (`/catalog`) and the entity type picker is not shown, after import entity of type `Location`.

In the console following message is shown:
```
Cannot update a component (`AlertDisplay`) while rendering a different component (`EntityTypePicker`). To locate the bad setState() call inside `EntityTypePicker`, follow the stack trace as described in https://fb.me/setstate-in-render
    in EntityTypePicker (created by CatalogPage)
    in div (created by CatalogPage)
    in EntityListProvider (created by CatalogPage)
    in div (created by CatalogPage)
    in article (created by Content)
    in Content (created by CatalogPage)
    in div (created by Page)
    in ThemeProvider (created by Page)
    in Page (created by CatalogLayout)
    in CatalogLayout (created by CatalogPage)
    in CatalogPage (created by RoutableExtension(CatalogPage))
    in RoutableExtension(CatalogPage) (created by Extension(Component))
    in PluginErrorBoundary (created by Extension(Component))
    in Suspense (created by Extension(Component))
    in Extension(Component) (at App.tsx:80)
    in Route (at App.tsx:80)
    in FlatRoutes (at App.tsx:78)
    in div (created by SidebarPage)
    in SidebarPage (at Root.tsx:74)
    in Root (at App.tsx:107)
    in Route (created by AppRouter)
    in Routes (created by AppRouter)
    in SignInPageWrapper (created by AppRouter)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by AppRouter)
    in AppRouter (at App.tsx:106)
    in RoutingProvider (created by Provider)
    in CssBaseline (created by WithStyles(CssBaseline))
    in WithStyles(CssBaseline) (created by AppThemeProvider)
    in ThemeProvider (created by AppThemeProvider)
    in AppThemeProvider (created by Provider)
    in AppContextProvider (created by Provider)
    in ApiProvider (created by Provider)
    in Provider (at App.tsx:103)
    in App (at src/index.tsx:6)
```

## Possible Solution

-

## Steps to Reproduce

1. Upgrade standalone app from `release-2021-06-17.1` to `release-2021-06-24`
2. Import entity of type `Location`
3. Navigate to `/catalog`

## Your Environment

- NodeJS Version (v12): 14.17.0
- Operating System and Version (e.g. Ubuntu 14.04): PopOS 20.10
- Browser Information: Opera v76.0.4017.123

**Comment by axdotl** [comment]
Closed, because I missed the necessary changes for @backstage/plugin-catalog-backend@0.10.3 from release (release-2021-06-17)https://github.com/backstage/backstage/releases/tag/release-2021-06-17.

After made changes to `catalog.ts` everything works as expected.

**Comment by dhenneke** [comment]
I'm getting the same issue using the old catalog backend and I don't think it is actually fixed yet.

The problem is that the code that was added in https://github.com/backstage/backstage/pull/6093 (sort the entities in the catalog client) can break if field filters are involved, as done in the `EntityTypeFilter`:
https://github.com/backstage/backstage/blob/1d1b197a65660d7a4e7a9ffed9dfaac3152b62ff/plugins/catalog-react/src/hooks/useEntityTypeFilter.tsx#L53-L57

We then get the following exception:
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at stringifyEntityRef (index.esm.js:908)
    at refCompare (index.esm.js:33)
    at Array.sort (<anonymous>)
    at CatalogClient.getEntities (index.esm.js:43)
    at async CatalogClientWrapper.getEntities (index-de361881.esm.js:1249)
    at async eval (index.esm.js:329) "\n    at EntityTypePicker (webpack-internal:///../../node_modules/@backstage/plugin-catalog-react/dist/index.esm.js:855:93)\n    at div\n    at EntityListProvider (webpack-internal:///../../node_modules/@backstage/plugin-catalog-react/dist/index.esm.js:200:3)\n    at div\n    at article\n    at Content (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:2918:3)\n    at div\n    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:42:24)\n    at Page (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4474:16)\n    at CatalogLayout (webpack-internal:///../../node_modules/@backstage/plugin-catalog/dist/esm/index-de361881.esm.js:294:25)\n    at CatalogPage (webpack-internal:///../../node_modules/@backstage/plugin-catalog/dist/esm/index-de361881.esm.js:545:3)\n    at RoutableExtensionWrapper (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:422:13)\n    at PluginErrorBoundary (eval at ES6ProxyComponentFactory (webpack-internal:///../../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)\n    at Suspense\n    at Result (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:470:21)\n    at D (webpack-internal:///../../node_modules/react-router/index.js:34:673)\n    at FlatRoutes (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2623:88)\n    at div\n    at SidebarPage (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4541:89)\n    at Root (webpack-internal:///./src/components/Root/Root.tsx:92:17)\n    at D (webpack-internal:///../../node_modules/react-router/index.js:34:673)\n    at E (webpack-internal:///../../node_modules/react-router/index.js:37:804)\n    at SignInPageWrapper (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2240:18)\n    at x (webpack-internal:///../../node_modules/react-router/index.js:36:23)\n    at w (webpack-internal:///../../node_modules/react-router-dom/index.js:63:23)\n    at AppRouter (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2252:25)\n    at RoutingProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:1933:3)\n    at CssBaseline (webpack-internal:///../../node_modules/@material-ui/core/esm/CssBaseline/CssBaseline.js:65:31)\n    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)\n    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:42:24)\n    at AppThemeProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2070:28)\n    at AppContextProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:1978:3)\n    at ApiProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:145:3)\n    at Provider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2166:24)\n    at App"
```

The reason why it works with the new catalog backend is that the `fields` functionality is not implemented there and the new catalog backend always returns all fields. But I'm not sure if this is this a bug or a feature? @freben @Rugvip @benjdlambert
