### ISSUE TITLE
OKTA auth provider not found error

### ISSUE THREAD

**Issue by ravargs** [backstage/backstage#6284]
I tried configuring OKTA authentication as per the documentation. But when try to login through OKTA getting the message	"Unknown auth provider 'okta'"

## Expected Behavior

Application should present with the OKTA credentials pop-up page and login workflow should happen

## Current Behavior

On clicking the Okta login getting the below error.
```name:	"NotFoundError"

message:	"Unknown auth provider 'okta'"

stack:	"NotFoundError: Unknown auth provider 'okta'\n    
at eval (webpack-internal:///../../plugins/auth-backend/src/service/router.ts:165:11)\n    at handleReturn
 (/backstage/backstage-master/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at
 /backstage/backstage-master/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle
 [as handle_request] (/backstage/backstage-master/node_modules/express/lib/router/layer.js:95:5)\n    
 at trim_prefix (/backstage/backstage-master/node_modules/express/lib/router/index.js:317:13)\n    at
 /backstage/backstage-master/node_modules/express/lib/router/index.js:284:7\n    at param
 (/backstage/backstage-master/node_modules/express/lib/router/index.js:354:14)\n    at param
 (/backstage/backstage-master/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params
 (/backstage/backstage-master/node_modules/express/lib/router/index.js:410:3)\n    at next
 (/backstage/backstage-master/node_modules/express/lib/router/index.js:275:10)\n    at
 /backstage/backstage-master/node_modules/express/lib/router/index.js:635:15\n    at next
 (/backstage/backstage-master/node_modules/express/lib/router/index.js:260:14)\n    at Function.handle 
 (/backstage/backstage-master/node_modules/express/lib/router/index.js:174:3)\n    at router
 (/backstage/backstage-master/node_modules/express/lib/router/index.js:47:12)\n    at handleReturn
 (/backstage/backstage-master/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at router
 (/backstage/backstage-master/node_modules/express-promise-router/lib/express-promise-router.js:64:7)"
 
request	
  method:	"GET"
  url	"/api/auth/okta/xxxx.okta.com/oauth2/v1/authorize?response_type=code&redirect_uri=http%3A%2F%2F192.168.1.119%3A7000%2Fapi%2Fauth%2Fokta%2Fhandler%2Fframe&scope=openid%20email%20profile%20offline_access&state=6e6f6e63653d3547655550253246565070556e35626d5142434d3241576725334425334426656e763d646576656c6f706d656e74&client_id=xxxxxx"
response	
   statusCode:	404
```   

## Steps to Reproduce

1. Step 1
Clone the repo
```
git clone --depth 1 git@github.com:backstage/backstage.git
cd backstage
```
2. Step 2
Configure the app-config.yaml for OKTA 
```
app-config.yaml
    okta:
      development:
        clientId: xxxxxxx
        clientSecret: xxxxxxx
        audience: dev-xxxxx.okta.com
```
3. Step 3
Fetch dependencies, run an initial build and start backend and front-end
```
# yarn install
# yarn tsc
# yarn build
# yarn start
# cd packages/backend
# yarn start
```
3. Step 3 
Verify the Okta login

## Your Environment

- NodeJS Version (v14.16.0):
- Operating System and Version (e.g. Ubuntu 20.04):
- Browser Information: Firefox

**Comment by OrkoHunter** [comment]
That request URL does not look good.

```
/api/auth/okta/xxxx.okta.com/oauth2/v1/authorize?response_type=code&redirect_uri=http%3A%2F%2F192.168.1.119%3A7000%2Fapi%2Fauth%2Fokta%2Fhandler%2Fframe&scope=openid%20email%20profile%20offline_access&state=6e6f6e63653d3547655550253246565070556e35626d5142434d3241576725334425334426656e763d646576656c6f706d656e74&client_id=xxxxxx
```

There is no route to handle this request. In fact, this request should directly go the OKTA audience URL. Since it contains a `redirect_url`, when the user logs in, the response will be resolved by auth-backend in Backstage.

Is this problem solved if you add a `https://` as prefix in `okta.development.audience`?

**Comment by ravargs** [comment]
That fixed he issue.

**Comment by OrkoHunter** [comment]
Sorry! I want to re-open this issue since it seems like we can handle this bug in the backend. Some kind of check to see if the OKTA audience starts with `https` or even append automatically if it doesn't.
