### ISSUE TITLE
Issue with parseGitUrl during register step of scaffolder

### ISSUE THREAD

**Issue by cjconrad2** [backstage/backstage#6588]
I've been setting up a backstage instance for my company and I've run into an issue when trying to use a software template. Specifically, when I get to the register step, I get the following error:

`2021-07-22T21:27:53.000Z TypeError: Cannot read property 'length' of undefined
    at defaultScmResolveUrl (/scratch/backstage2/backstage/node_modules/@backstage/integration/dist/index.cjs.js:60:91)
    at _BitbucketIntegration.resolveUrl (/scratch/backstage2/backstage/node_modules/@backstage/integration/dist/index.cjs.js:281:22)
    at Object.handler (/scratch/backstage2/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:125:38)
    at TaskWorker.runOneTask (/scratch/backstage2/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:1985:24)
    at async /scratch/backstage2/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:1887:9
`

Interestingly, if I modify 
https://github.com/backstage/backstage/blob/afeffa74921880b3a0e8fb7b4c3833a0c0878d6f/packages/integration/src/helpers.ts#L84 by removing the braces: 
`const filepath = parseGitUrl(base);`
I can get past that error (though the url that is used for registration is wrong - looks like https://bitbucket.my.company.com/catalog-info.yaml, leaving out the project and repo). That line of code hasn't been touched in months though, so I feel like that can't really be the root issue. It seems like parseGitUrl is returning a string instead of an object, at least in my case. 

Curious if you all have any thoughts. If it is helpful, I am up to date on all backstage packages, and I am using an integration with bitbucket server. I've debugged a bit and I know that the url being passed to parseGitUrl is of the form https://bitbucket.my.company.com/projects/PROJ/repos/testrepo/browse. Also running node version 14.15.1. Please let me know what other info would be helpful to provide.

**Comment by cjconrad2** [comment]
I ended up needing to configure my template a little differently and was able to make it work. Initially I tried using the RepoUrlPicker field type, but instead I switched to separate project and repo fields and then constructed the input url in my publish and register steps. It seems unfortunate that I can't use the RepoUrlPicker, but what I have now works fine.
