### ISSUE TITLE
file path with path parts containing same value causes FileExplorer.tsx to exhaust call stack in browser

### ISSUE THREAD

**Issue by jeremyguarini** [backstage/backstage#7440]
When viewing a code coverage report which contains a file whose path contains path parts that contain the same word will result in the browser having a stack trace indicating the maximum call stack size was exceeded. 

## Expected Behavior

Viewing the code coverage report in the browser should not result in stack trace.

## Current Behavior

Viewing a code coverage report may result in call stack to be exhausted.

## Possible Solution

Seems the split logic in  buildFileStructure() in FileExporter.tsx  needs to be reworked a bit.

## Steps to Reproduce

git clone of the repo
add service to catalog
generate code coverage report or use the sample below
push coverage report to BS
view coverage report in browser

sample coverage report that triggers the bug
`<?xml version="1.0" ?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage lines-valid="3313" lines-covered="2586" line-rate="0.7806000000000001" branches-valid="1995" branches-covered="1322" branch-rate="0.6627" timestamp="1633034471432" complexity="0" version="0.1">
  <sources>
    <source>/tmp/backstage_github_clone</source>
  </sources>
  <packages>
    <package name="core-components.src.components.Avatar" line-rate="1" branch-rate="1">
      <classes>
        <class name="utils.ts" filename="packages/core-components/src/components/Avatar/utils.ts" line-rate="1" branch-rate="1">
          <methods>
            <method name="stringToColor" hits="1" signature="()V">
              <lines>
                <line number="17" hits="1"/>
              </lines>
            </method>
          </methods>
          <lines>
            <line number="17" hits="1" branch="false"/>
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
`
After some investigation it appears that in plugins/code-coverage/src/components/FileExplorer/FileExplorer.tsx in the buildFileStructure() the split function may not work as expected. In the sample coverage report the file path is `packages/core-components/src/components/Avatar/utils.ts`
We can see that path will be set to `path = path?.split(`${row.path}/`)[1];` when row.path is valid. 
Breaking down the file path we should expect when:
 row.path == core-components that path will be set to src/components/Avatar/utils.ts and pathArray will be ['src', 'components', 'Avatar', 'utils.ts']
 row.path == src then path should be components/Avatar/utils.ts and pathArray will be ['components', 'Avatar', 'utils.ts']
 row.path == components then we should expect path to be Avatar/utils.ts and pathArray to be ['Avatar', 'utils.ts'] but instead path is set to src/ and pathArray ends up being set to ['src', ''] this in-turn causes a loop
 

## Context

I wanted to showcase the code coverage feature using a code coverage report generated off the backstage code base. After submitting the coverage report via API I then proceeded to view the report. After navigating to the service then clicking on the  code coverage tab  the browser resulted in 
`Error
RangeError

Message
Maximum call stack size exceeded

Stack Trace
RangeError: Maximum call stack size exceeded
    at https://localhost:7000/static/main.b893f162.js:1:374955
    at Array.map (<anonymous>)
    at $ (https://localhost:7000/static/main.b893f162.js:1:374947)
    at https://localhost:7000/static/main.b893f162.js:1:374955
    at Array.map (<anonymous>)
    at $ (https://localhost:7000/static/main.b893f162.js:1:374947)
    at https://localhost:7000/static/main.b893f162.js:1:374955
    at Array.map (<anonymous>)
    at $ (https://localhost:7000/static/main.b893f162.js:1:374947)
    at https://localhost:7000/static/main.b893f162.js:1:374955`

## Your Environment

- NodeJS Version (v14): v16.9.1
- Operating System and Version (e.g. Ubuntu 14.04): OSX 11.6, Debian 10.10
- Browser Information: Version 94.0.4606.54 (Official Build) (x86_64)

**Comment by N-Shar-ma** [comment]
I'd like to fix this bug!
