### ISSUE TITLE
Backstage ElasticSearch Plugin Doesn't Work With AWS

### ISSUE THREAD

**Issue by ChetanBhasin** [backstage/backstage#7839]
Recently, all Elasticsearch official plugins have been modified to not work with any third-party Elasticsearch distributions. It appears that Backstage's Elasticsearch plugin uses one of those clients.

Even though in the documentation, it is pointed out that Backstage search supports AWS managed Elasticsearch, this is no longer true. If we try to do that 

## Expected Behaviour

Backstage can read/write to AWS managed Elasticsearch when configured to do so.

## Current Behaviour

When Backstage is configured to use AWS provided Elasticsearch, this is the error we get:

```
search error Failed to index documents for type software-catalog The client noticed that the server is not a supported distribution of Elasticsearch type=plugin name=ProductNotSupportedError meta=[object Object] stack=ProductNotSupportedError: The client noticed that the server is not a supported distribution of Elasticsearch
    at EventEmitter.<anonymous> (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:466:34)
    at Object.onceWrapper (events.js:520:26)
    at EventEmitter.emit (events.js:400:28)
    at EventEmitter.emit (domain.js:475:12)
    at /app/node_modules/@elastic/elasticsearch/lib/Transport.js:599:40
    at onBody (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:364:9)
    at IncomingMessage.onEnd (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:279:11)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
2021-10-29T11:20:57.960Z catalog warn Policy check failed; caused by Error:
```

## Possible Solution

I see two possible solutions:
- Develop a new plugin for Backstage that specifically works with Elasticsearch managed by AWS and add it to plugins directory.
- Modify the current plugin to use the official ES plugin for regular Elasticsearch and the ES client from AWS SDK for AWS managed ES.

The first one sounds nicer because otherwise our ES plugin will contain two clients and that's just increasing the code size included in the final build.

**Comment by freben** [comment]
Update - #7878 has been merged. We'll leave this issue open, because we probably want to eventually try to find a way that doesn't require pinning. But given the state of the world, it's not an option right now.

**Comment by benjdlambert** [comment]
Can we close this now as it's pinned and hopefully later releases have a fix for it?
