### ISSUE TITLE
No API factory available for dependency apiRef{core.scmauth} of dependent apiRef{plugin.catalog-import.service}

### ISSUE THREAD

**Issue by ssang4** [backstage/backstage#7879]
When trying to load the catalog import page, I am faced with "No API factory available for dependency apiRef{core.scmauth} of dependent apiRef{plugin.catalog-import.service}" error.

## Expected Behavior

The catalog import page should load for me to import catalog entities.

## Current Behavior

![Screenshot from 2021-11-03 16-42-26](https://user-images.githubusercontent.com/13478935/140094101-2e8bee18-1f8e-4ae0-ba2c-68937829e2a9.png)

## Steps to Reproduce

Output of `yarn dev`:

```
sang@TB-L161:~/Codes/backstage$ yarn dev
yarn run v1.22.17
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli backend:dev
$ backstage-cli app:serve
[1] Build succeeded
[0] Loaded config from app-config.yaml, app-config.local.yaml
[0] <w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.
[0] (node:88996) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.
[0] (Use `node --trace-deprecation ...` to show where the warning was created)
[0] (node:88996) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use async 'start' or 'startCallback' methods.
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/home/sang/Codes/backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] 2021-11-03T15:49:38.629Z backstage info Loaded config from app-config.yaml, app-config.local.yaml 
[1] 2021-11-03T15:49:38.642Z backstage info 0 secrets found in the config which will be redacted 
[1] 2021-11-03T15:49:38.657Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucket{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.tradebyte.org,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{} 
[1] 2021-11-03T15:49:38.907Z auth info Configuring "database" as KeyStore provider type=plugin
[1] 2021-11-03T15:49:38.920Z techdocs warn The 'techdocs.generators.techdocs' configuration key is deprecated and will be removed in the future. Please use 'techdocs.generator' instead. See here https://backstage.io/docs/features/techdocs/configuration type=plugin
[1] 2021-11-03T15:49:38.921Z techdocs info Creating AWS S3 Bucket publisher for TechDocs type=plugin
[1] 2021-11-03T15:49:40.027Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec should have required property 'memberOf' - missingProperty: memberOf type=plugin entity=user:default/chris.slarke
[1] 2021-11-03T15:49:40.029Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity; caused by TypeError: /spec should have required property 'memberOf' - missingProperty: memberOf type=plugin entity=user:default/chris.williams
[1] 2021-11-03T15:49:46.424Z techdocs error Could not retrieve metadata about the AWS S3 bucket com-tradebyte-cps-backstage-techdocs. Make sure the bucket exists. Also make sure that authentication is setup either by explicitly defining credentials and region in techdocs.publisher.awsS3 in app config or by using environment variables. Refer to https://backstage.io/docs/features/techdocs/using-cloud-storage type=plugin
[1] 2021-11-03T15:49:46.425Z techdocs error from AWS client library Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1 type=plugin code=CredentialsError time=Wed Nov 03 2021 16:49:46 GMT+0100 (Central European Standard Time) retryable=true originalError=[object Object] stack=CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
[1]     at Timeout.connectTimeout [as _onTimeout] (/home/sang/Codes/backstage/node_modules/aws-sdk/lib/http/node.js:69:15)
[1]     at listOnTimeout (internal/timers.js:557:17)
[1]     at processTimers (internal/timers.js:500:7)
[1] 2021-11-03T15:49:46.430Z proxy info [HPM] Proxy created: /test  -> https://example.com type=plugin
[1] 2021-11-03T15:49:46.431Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/test/?" ~> "/" type=plugin
[1] 2021-11-03T15:49:46.432Z search info Added DefaultCatalogCollator collator for type software-catalog type=plugin
[1] 2021-11-03T15:49:46.434Z app warn Can't serve static app content from /home/sang/Codes/backstage/packages/app/dist/static, directory doesn't exist type=plugin
[1] 2021-11-03T15:49:46.437Z backstage info Initializing http server 
[1] 2021-11-03T15:49:46.441Z backstage info Listening on :7000 
```

Please ignore the S3 credentials not found error, they are intentional when developing locally.

## Your Environment

Output of `yarn backstage-cli info`:
```
sang@TB-L161:~/Codes/backstage$ yarn backstage-cli info
yarn run v1.22.17
$ /home/sang/Codes/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.11.0-38-generic - linux/x64
node: v14.18.1
yarn: 1.22.17
cli:  0.8.1 (installed)

Dependencies:
  @backstage/backend-common                                0.9.8
  @backstage/catalog-client                                0.5.0
  @backstage/catalog-model                                 0.9.6
  @backstage/cli-common                                    0.1.5
  @backstage/cli                                           0.8.1
  @backstage/config-loader                                 0.7.1
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.1.19
  @backstage/core-components                               0.7.2
  @backstage/core-plugin-api                               0.1.12
  @backstage/errors                                        0.1.4
  @backstage/integration-react                             0.1.13
  @backstage/integration                                   0.6.9
  @backstage/plugin-api-docs                               0.6.12
  @backstage/plugin-app-backend                            0.3.18
  @backstage/plugin-auth-backend                           0.4.6
  @backstage/plugin-catalog-backend                        0.17.2
  @backstage/plugin-catalog-import                         0.7.3
  @backstage/plugin-catalog-react                          0.6.2
  @backstage/plugin-catalog                                0.7.2
  @backstage/plugin-github-actions                         0.4.22
  @backstage/plugin-org                                    0.3.27
  @backstage/plugin-proxy-backend                          0.2.13
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.3
  @backstage/plugin-scaffolder-backend                     0.15.11
  @backstage/plugin-scaffolder-common                      0.1.1
  @backstage/plugin-scaffolder                             0.11.9
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.2.6
  @backstage/plugin-search                                 0.4.16
  @backstage/plugin-tech-radar                             0.4.11
  @backstage/plugin-techdocs-backend                       0.10.7
  @backstage/plugin-techdocs                               0.12.4
  @backstage/plugin-user-settings                          0.3.10
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.10.5
  @backstage/test-utils                                    0.1.20
  @backstage/theme                                         0.2.12
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.0
Done in 0.38s.
```

- NodeJS Version (v14): 14.18.1
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 20.04
- Browser Information: Agnostic

**Comment by awanlin** [comment]
We are seeing the same issue as well. The error is not there if I run this from the Backstage repo itself but out created app version displays this issue. I'll do some more investigating from my side of things

**Comment by awanlin** [comment]
Did not get anywhere with my investigation but here are the results of `yarn backstage-cli info`:

```shell
OS:   Windows_NT 10.0.19043 - win32/x64
node: v14.17.6
yarn: 1.22.5
cli:  0.8.1 (installed)

Dependencies:
  @backstage/backend-common                                0.9.8
  @backstage/catalog-client                                0.5.0
  @backstage/catalog-model                                 0.9.6
  @backstage/cli-common                                    0.1.5
  @backstage/cli                                           0.8.1
  @backstage/config-loader                                 0.7.1
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.1.19
  @backstage/core-components                               0.7.2
  @backstage/core-plugin-api                               0.1.12
  @backstage/dev-utils                                     0.2.12
  @backstage/errors                                        0.1.4
  @backstage/integration-react                             0.1.13
  @backstage/integration                                   0.6.9
  @backstage/plugin-api-docs                               0.6.12
  @backstage/plugin-app-backend                            0.3.18
  @backstage/plugin-auth-backend                           0.4.6
  @backstage/plugin-azure-devops-backend                   0.1.4
  @backstage/plugin-azure-devops                           0.1.2
  @backstage/plugin-badges-backend                         0.1.11
  @backstage/plugin-badges                                 0.2.13
  @backstage/plugin-catalog-backend                        0.17.2
  @backstage/plugin-catalog-graph                          0.2.1
  @backstage/plugin-catalog-import                         0.7.3
  @backstage/plugin-catalog-react                          0.6.2
  @backstage/plugin-catalog                                0.7.2
  @backstage/plugin-cost-insights                          0.11.10
  @backstage/plugin-explore-react                          0.0.6
  @backstage/plugin-explore                                0.3.20
  @backstage/plugin-home                                   0.4.4
  @backstage/plugin-jenkins                                0.5.11
  @backstage/plugin-kubernetes-backend                     0.3.18
  @backstage/plugin-kubernetes-common                      0.1.5
  @backstage/plugin-kubernetes                             0.4.18
  @backstage/plugin-lighthouse                             0.2.29
  @backstage/plugin-org                                    0.3.27
  @backstage/plugin-pagerduty                              0.3.17
  @backstage/plugin-proxy-backend                          0.2.13
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.3
  @backstage/plugin-scaffolder-backend                     0.15.11
  @backstage/plugin-scaffolder-common                      0.1.1
  @backstage/plugin-scaffolder                             0.11.9
  @backstage/plugin-search-backend-module-elasticsearch    0.0.4
  @backstage/plugin-search-backend-module-pg               0.2.1
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.2.6
  @backstage/plugin-search                                 0.4.16
  @backstage/plugin-sentry                                 0.3.27
  @backstage/plugin-shortcuts                              0.1.13
  @backstage/plugin-tech-radar                             0.4.11
  @backstage/plugin-techdocs-backend                       0.10.6
  @backstage/plugin-techdocs                               0.12.4
  @backstage/plugin-user-settings                          0.3.10
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.10.5
  @backstage/test-utils                                    0.1.20
  @backstage/theme                                         0.2.12
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.0
```

**Comment by dhenneke** [comment]
Did you apply this change to your instance after updating the backstage packages? https://github.com/backstage/backstage/blob/master/plugins/catalog-import/CHANGELOG.md#minor-changes

**Comment by Alastair-Pandelus** [comment]
I saw this when bumping versions and not applying the change in the changelog referenced above. Applying the change fixed it.

**Comment by ssang4** [comment]
Yes I can confirm that the solution works for me too, thanks very much @dhenneke

**Comment by awanlin** [comment]
Thanks @dhenneke that was the fix for us as well, I need to remember to always check the changelog!

**Comment by roh85** [comment]
I have updated all the dependencies with the backstage-cli version bump command and added the ScmAuth.CreateDefaultApiFactory() to the AnyApiFactory[] array as suggested in the changelog but I am still receive the reported error above. 

**Contents of packages/app/apis.ts**

```
import { DynaTechRadar } from './lib/DynaTechRadar';
import { techRadarApiRef } from '@backstage/plugin-tech-radar'
import { AnyApiFactory, createApiFactory } from '@backstage/core-plugin-api';
import { ScmAuth } from '@backstage/integration-react';

export const apis: AnyApiFactory[] = [
  createApiFactory(techRadarApiRef, new DynaTechRadar()), ScmAuth.createDefaultApiFactory()
];
```

**Exception page:**

![image](https://github.com/backstage/backstage/assets/3336504/e33704be-e2f4-49aa-88d6-6a24fa20b958)

**Here are the results of yarn backstage-cli info:**

```
OS:   Windows_NT 10.0.19045 - win32/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.8 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                          1.4.0
  @backstage/backend-app-api                       0.4.4
  @backstage/backend-common                        0.19.0
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.3
  @backstage/backend-tasks                         0.5.3
  @backstage/catalog-client                        1.4.2
  @backstage/catalog-model                         1.4.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.1
  @backstage/cli                                   0.22.8
  @backstage/config-loader                         1.3.1
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.8.1
  @backstage/core-components                       0.13.2
  @backstage/core-plugin-api                       1.5.2
  @backstage/errors                                1.2.0
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.4
  @backstage/integration-react                     1.1.14
  @backstage/integration                           1.5.0
  @backstage/plugin-api-docs                       0.9.5
  @backstage/plugin-app-backend                    0.3.46
  @backstage/plugin-auth-backend                   0.18.4
  @backstage/plugin-auth-node                      0.2.15
  @backstage/plugin-catalog-backend-module-github  0.3.1
  @backstage/plugin-catalog-backend                1.10.0
  @backstage/plugin-catalog-common                 1.0.14
  @backstage/plugin-catalog-graph                  0.2.31
  @backstage/plugin-catalog-import                 0.9.9
  @backstage/plugin-catalog-node                   1.3.7
  @backstage/plugin-catalog-react                  1.7.0
  @backstage/plugin-catalog                        1.11.2
  @backstage/plugin-events-node                    0.2.7
  @backstage/plugin-github-actions                 0.6.0
  @backstage/plugin-org                            0.6.9
  @backstage/plugin-permission-common              0.7.6
  @backstage/plugin-permission-node                0.7.9
  @backstage/plugin-permission-react               0.4.13
  @backstage/plugin-proxy-backend                  0.2.40
  @backstage/plugin-scaffolder-backend             1.15.0
  @backstage/plugin-scaffolder-common              1.3.1
  @backstage/plugin-scaffolder-node                0.1.4
  @backstage/plugin-scaffolder-react               1.5.0
  @backstage/plugin-scaffolder                     1.14.0
  @backstage/plugin-search-backend-module-catalog  0.1.2
  @backstage/plugin-search-backend-module-pg       0.5.7
  @backstage/plugin-search-backend-module-techdocs 0.1.2
  @backstage/plugin-search-backend-node            1.2.2
  @backstage/plugin-search-backend                 1.3.2
  @backstage/plugin-search-common                  1.2.4
  @backstage/plugin-search-react                   1.6.2
  @backstage/plugin-search                         1.3.2
  @backstage/plugin-tech-radar                     0.6.5
  @backstage/plugin-techdocs-backend               1.6.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.14
  @backstage/plugin-techdocs-node                  1.7.2
  @backstage/plugin-techdocs-react                 1.1.7
  @backstage/plugin-techdocs                       1.6.4
  @backstage/plugin-user-settings                  0.7.4
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.0
  @backstage/theme                                 0.4.0
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
```

Any help would be appreciated.
