### ISSUE TITLE
Docker image fails after adding a backend plugin

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#8022]
## Expected Behavior

Bundled package should work

## Current Behavior

Bundled package does not work, throwing the following error:

```
/app/plugins/iiq-backend/dist/index.cjs.js:33426
var memoizedProperty$3 = util_1.memoizedProperty;
                                ^

TypeError: Cannot read property 'memoizedProperty' of undefined
    at Object.<anonymous> (/app/plugins/iiq-backend/dist/index.cjs.js:33426:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/packages/backend/dist/index.cjs.js:8:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

## Steps to Reproduce

- Create a backend plugin
- Remove service folder and route related files
- Integrate with backend package
- Build the bundle
- Run docker image

NOTE: The application works fine outside of the docker image when running `yarn dev`

## Context

I'm trying to add a catalog processor, external integration as a separate plugin. I  do not need any routing at the moment. The setup is like this one, for example:

https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-ldap

**Comment by ProticM** [comment]
As it turned out, some packages were missing. It is working fine after modifying installed packages. We can close ATM

**Comment by jbadeau** [comment]
I am having the same error with a custom plugin. What packages were you missing?

**Comment by jbadeau** [comment]
But how is this situation possible?
