### ISSUE TITLE
Unable to create component using template

### ISSUE THREAD

**Issue by nishantmalviya** [backstage/backstage#8036]
## Expected Behavior

Component should be created in gitlab using template

## Current Behavior

Exception while creating the component in gitlab.

Exception trace as below: 
2021-11-12T20:24:36.000Z Beginning step Fetch Skeleton + Template
2021-11-12T20:24:36.000Z info: Fetching template content from remote URL {"timestamp":"2021-11-12T20:24:36.571Z"}
2021-11-12T20:24:37.000Z TypeError: Cannot read property 'id' of undefined
    at _GitlabUrlReader.readTree (C:\svb\setup\backstageapp\node_modules\@backstage\backend-common\dist\index.cjs.js:1753:63)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UrlReaderPredicateMux.readTree (C:\svb\setup\backstageapp\node_modules\@backstage\backend-common\dist\index.cjs.js:1994:16)
    at async fetchContents (C:\svb\setup\backstageapp\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:271:17)
    at async Object.handler (C:\svb\setup\backstageapp\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:383:7)
    at async HandlebarsWorkflowRunner.execute (C:\svb\setup\backstageapp\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:2178:11)
    at async TaskWorker.runOneTask (C:\svb\setup\backstageapp\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:2433:143)
    at async C:\svb\setup\backstageapp\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:2427:9

## Possible Solution

Component should be created using template

## Steps to Reproduce

Step 1: Created a template for Springboot microservice targeting gitlab repository.
Step 2: Creating a component using #1 template
Step 3: Exception is generated as above

Template used: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/springboot-grpc-template/template.yaml

except it uses our gitlab host in allowedHosts section

## Context

I want to create templates specific to our needs and need to create components using these templates in gitlab

## Your Environment

- NodeJS Version (v14): node-v14.17.0-win-x64
- Operating System and Version (e.g. Ubuntu 14.04): windows
- Browser Information: chrome

Installed backstage in windows using the instructions in the backstage website.
app-config.yaml has integration section for my gitlab with token.
and a template is specified in this file under catalog.locations.

**Comment by benjdlambert** [comment]
Re-opening as it looks like this is still happening. 

Could be this line being thrown? https://github.com/backstage/backstage/blob/1379080c92b0d22c7df15cf71095b35fe0f89865/packages/backend-common/src/reading/GitlabUrlReader.ts#L191

Ideally I need someone who is facing this issue to do some more debugging, by logging what `await commitsGitlabResponse.json()` is. Could be something to do with `@gitbeaker` bumps or something.

**Comment by ranjeet-programmer** [comment]
I am also facing the same issue.

**Comment by benjdlambert** [comment]
Can you help debug by adding some logging to the file in question? And running backstage from the repo with your `app-config.yaml` to try and work out what is going on?

**Comment by freben** [comment]
See PR above for fix.
