### ISSUE TITLE
Pagerduty Plugin - Change Events Unable to be Listed

### ISSUE THREAD

**Issue by ryanaross** [backstage/backstage#8409]
Hello! We have recently adopted the PagerDuty plugin. Ongoing Incidents can be listed no problem, however a Change Events tab was added in https://github.com/backstage/backstage/pull/6623 and these result in an error _whenever there are items to list_.

## Expected Behavior

It expect it should work similar to the Incidents tab, which looks like this:

![image](https://user-images.githubusercontent.com/7442411/145121091-d0fff9d2-47bd-4b49-9059-dd69c94605f5.png)

## Current Behavior

Getting an error, but only when there are Change Events to list:
![image](https://user-images.githubusercontent.com/7442411/145121187-54d4ef53-ba10-4b95-bc60-5cdd41ede38e.png)

Change Event in PagerDuty:
![image](https://user-images.githubusercontent.com/7442411/145121418-01591016-f196-42ef-9089-4d353bc4d074.png)

Transcript:
```
Error
TypeError

Message
Cannot read properties of undefined (reading 'pathname')

Stack Trace
TypeError: Cannot read properties of undefined (reading 'pathname')
    at J (webpack-internal:///../../node_modules/react-router/index.js:50:123)
    at eval (webpack-internal:///../../node_modules/react-router/index.js:41:245)
    at mountMemo (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:15465:19)
    at Object.useMemo (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:15761:16)
    at useMemo (webpack-internal:///../../node_modules/react/cjs/react.development.js:1521:21)
    at wrappedHook (webpack-internal:///../../node_modules/react-hot-loader/dist/react-hot-loader.development.js:2798:14)
    at K (webpack-internal:///../../node_modules/react-router/index.js:41:226)
    at useHref (webpack-internal:///../../node_modules/react-router/index.js:53:186)
    at eval (webpack-internal:///../../node_modules/react-router-dom/index.js:44:251)
    at renderWithHooks (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs
```

## Possible Solution

I would love general suggestions, happy to try them out.

## Steps to Reproduce

Setup PagerDuty plugin according to docs. Add integration key to catalog-info.yaml. Create a change event with `curl`:

```
curl --request POST \
 --url https://events.pagerduty.com/v2/change/enqueue \
 --header 'Content-Type: application/json' \
 --data '{
 "routing_key": "2352not-a-real-routing-key1246",
 "payload": {
   "summary": "TEST - Change event"
 },
 "links": [
   {
     "href": "https://notareallink.com/pipeline",
     "text": "View in Build Pipeline"
   }
 ]
}'
```

## Context

We would like to display recent changes to a service for quick incident resolution.

## Your Environment

I cloned the master branch of backstage/backstage and imported our development app-config.yaml so as to test this cleanly.

**Comment by jhaals** [comment]
Thanks for the detailed description and sorry to hear that you're having trouble with the plugin! 
Perhaps @douglasread that last contributed to the pd plugin would be willing to help out.
