### ISSUE TITLE
Scaffolder failed to fetch in gitlab

### ISSUE THREAD

**Issue by mateuslima90** [backstage/backstage#9072]
## Expected Behavior
Using a scaffolder plugin to create file through template and commit the result in gitlab.

## Current Behavior
The resources of scaffolder are loaded with success. In backstage home is show my custom template and I can filled all the fields (for tests I am using a simple template that it just have one field). After that, I clicked to create and an error is happening on the next screen.

Fetch Base step occur this error:
```bash
2022-01-21T00:01:59.000Z Beginning step Fetch Base
2022-01-21T00:01:59.000Z info: Fetching template content from remote URL {"timestamp":"2022-01-21T00:01:59.006Z"}
2022-01-21T00:02:00.000Z FetchError: invalid json response body at https://gitlab.luizalabs.com/users/sign_in reason: Unexpected token < in JSON at position 0
    at /home/makingthehand/Projects/backstage/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async _GitlabUrlReader.readTree (/home/makingthehand/Projects/backstage/node_modules/@backstage/backend-common/dist/index.cjs.js:1738:39)
    at async UrlReaderPredicateMux.readTree (/home/makingthehand/Projects/backstage/node_modules/@backstage/backend-common/dist/index.cjs.js:1994:16)
    at async fetchContents (/home/makingthehand/Projects/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:271:17)
    at async Object.handler (/home/makingthehand/Projects/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:383:7)
    at async NunjucksWorkflowRunner.execute (/home/makingthehand/Projects/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2353:11)
    at async TaskWorker.runOneTask (/home/makingthehand/Projects/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2433:85)
    at async /home/makingthehand/Projects/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2427:9
```

## Steps to Reproduce

Step 1: bootstrap configuration
-> Configure app-config.yaml
```yaml
integrations:
  gitlab:
    - host: {{gitlab-host}} #gitlab.com
      token: {{token}}
      apiBaseUrl: {{gitlab-api}} # https://gitlab.com/api


scaffolder:
  defaultAuthor:
    name: Mateus Lima Fonseca
    email: mateuslima90@gmail.com
  defaultCommitMessage: "Testing"
  gitlab:
    api:
      baseUrl: {{https-gitlab-host}} #https://gitlab.com
      token: {{token}}
    visibility: internal # or 'internal' or 'private'

catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  locations:
    - type: url
      target: https://gitlab.com/templates/my-template.yaml
      rules:
        - allow: [ Template ]
```
step 2: Starting backstage
In backstage left menu click in "create..." and choose my-template. In my-template It is needed to fill all the fields and click in create.

**Comment by Rugvip** [comment]
Looks like your GitLab instance is redirecting to the sign-in page, seeing `https://gitlab.luizalabs.com/users/sign_in` in the logs. I'd say double check the `host`, `token`, and `apiBaseUrl` configuration, and make sure they're set correctly. I think in this case particularly the `apiBaseUrl` might be at fault

**Comment by mateuslima90** [comment]
@Rugvip I checked the configurations and I made a mistake in apiBaseUrl. Thanks. It is working but I need to use backstage.io/v1beta2 to create a template.
