### ISSUE TITLE
Cannot read property 'Transaction' of undefined

### ISSUE THREAD

**Issue by rpete3** [backstage/backstage#9074]
Trying to start backstage after a new build in a container and it errors on startup
## Expected Behavior
backstage should start 

## Current Behavior

/app/plugins/tech-insights-backend/dist/index.cjs.js:205
knex.Knex.Transaction;
          ^

TypeError: Cannot read property 'Transaction' of undefined
    at Object.<anonymous> (/app/plugins/tech-insights-backend/dist/index.cjs.js:205:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/packages/backend/dist/index.cjs.js:25:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

## Possible Solution

no idea at this time

## Steps to Reproduce
build from latest release branch and run in a kubernetes pod

## Context

Unable to run backstage.

## Your Environment

- NodeJS Version (v14): FROM node:14-buster-slim
- Operating System and Version (e.g. Ubuntu 14.04): FROM node:14-buster-slim
- Browser Information:

**Comment by awanlin** [comment]
@rpete3 this should be fixed by the latest release: https://github.com/backstage/backstage/releases/tag/release-2022-01-20.1

**Comment by rpete3** [comment]
Yep, all fixed!
