### ISSUE TITLE
Error using template Dockerfile (missing python)

### ISSUE THREAD

**Issue by maxknee** [backstage/backstage#9622]
## Expected Behavior

building the backstage backend dockerfile *should* work

## Actual Behavior

failed - 

## Steps to Reproduce

1. run create-backstage-app
2. run `docker image build . -f packages/backend/Dockerfile --tag backstage`

## Context

```
=> ERROR [5/7] RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(  152.9s
------
 > [5/7] RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)":
#7 0.986 yarn install v1.22.17
#7 1.548 [1/5] Validating package.json...
#7 1.564 [2/5] Resolving packages...
#7 3.214 [3/5] Fetching packages...
#7 3.247 warning Pattern ["app@link:packages/app"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-app-0.0.0/node_modules/app" as pattern ["app@0.0.0","app@0.0.0"]. This could result in non-deterministic behavior, skipping.
#7 130.7 [4/5] Linking dependencies...
#7 130.7 warning "@backstage/cli > @hot-loader/react-dom@16.14.0" has unmet peer dependency "react@^16.14.0".
#7 130.8 warning "@backstage/cli > @svgr/plugin-jsx@6.2.1" has unmet peer dependency "@svgr/core@^6.0.0".
#7 130.8 warning "@backstage/cli > @svgr/plugin-svgo@6.2.0" has unmet peer dependency "@svgr/core@^6.0.0".
#7 130.8 warning "@backstage/cli > react-hot-loader@4.13.0" has unmet peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0 ".
#7 130.8 warning "@backstage/cli > react-hot-loader@4.13.0" has unmet peer dependency "react-dom@^15.0.0 || ^16.0.0 || ^17.0.0 ".
#7 148.2 [5/5] Building fresh packages...
#7 151.7 warning Error running install script for optional dependency: "/app/node_modules/cpu-features: Command failed.
#7 151.7 Exit code: 1
#7 151.7 Command: node-gyp rebuild
#7 151.7 Arguments:
#7 151.7 Directory: /app/node_modules/cpu-features
#7 151.7 Output:
#7 151.7 gyp info it worked if it ends with ok
#7 151.7 gyp info using node-gyp@5.1.0
#7 151.7 gyp info using node@14.19.0 | linux | x64
#7 151.7 gyp ERR! find Python
#7 151.7 gyp ERR! find Python Python is not set from command line or npm configuration
#7 151.7 gyp ERR! find Python Python is not set from environment variable PYTHON
#7 151.7 gyp ERR! find Python checking if \"python\" can be used
#7 151.7 gyp ERR! find Python - \"python\" is not in PATH or produced an error
#7 151.7 gyp ERR! find Python checking if \"python2\" can be used
#7 151.7 gyp ERR! find Python - \"python2\" is not in PATH or produced an error
#7 151.7 gyp ERR! find Python checking if \"python3\" can be used
#7 151.7 gyp ERR! find Python - \"python3\" is not in PATH or produced an error
#7 151.7 gyp ERR! find Python
#7 151.7 gyp ERR! find Python **********************************************************
#7 151.7 gyp ERR! find Python You need to install the latest version of Python.
#7 151.7 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#7 151.7 gyp ERR! find Python you can try one of the following options:
#7 151.7 gyp ERR! find Python - Use the switch --python=\"/path/to/pythonexecutable\"
#7 151.7 gyp ERR! find Python   (accepted by both node-gyp and npm)
#7 151.7 gyp ERR! find Python - Set the environment variable PYTHON
#7 151.7 gyp ERR! find Python - Set the npm configuration variable python:
#7 151.7 gyp ERR! find Python   npm config set python \"/path/to/pythonexecutable\"
#7 151.7 gyp ERR! find Python For more information consult the documentation at:
#7 151.7 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#7 151.7 gyp ERR! find Python **********************************************************
#7 151.7 gyp ERR! find Python
#7 151.7 gyp ERR! configure error
#7 151.7 gyp ERR! stack Error: Could not find any Python installation to use
#7 151.7 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
#7 151.7 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
#7 151.7 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
#7 151.7 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
#7 151.7 gyp ERR! stack     at exithandler (child_process.js:390:5)
#7 151.7 gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
#7 151.7 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#7 151.7 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
#7 151.7 gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
#7 151.7 gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
#7 151.7 gyp ERR! System Linux 5.10.25-linuxkit
#7 151.7 gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
#7 151.7 gyp ERR! cwd /app/node_modules/cpu-features
#7 151.7 gyp ERR! node -v v14.19.0
#7 151.7 gyp ERR! node-gyp -v v5.1.0
#7 151.7 gyp ERR! not ok"
#7 151.7 info This module is OPTIONAL, you can safely ignore this error
#7 151.7 error /app/node_modules/@vscode/sqlite3: Command failed.
#7 151.7 Exit code: 1
#7 151.7 Command: node-gyp rebuild
#7 151.7 Arguments:
#7 151.7 Directory: /app/node_modules/@vscode/sqlite3
#7 151.7 Output:
#7 151.7 gyp info it worked if it ends with ok
#7 151.7 gyp info using node-gyp@5.1.0
#7 151.7 gyp info using node@14.19.0 | linux | x64
#7 151.7 gyp ERR! find Python
#7 151.7 gyp ERR! find Python Python is not set from command line or npm configuration
#7 151.7 gyp ERR! find Python Python is not set from environment variable PYTHON
#7 151.7 gyp ERR! find Python checking if "python" can be used
#7 151.7 gyp ERR! find Python - "python" is not in PATH or produced an error
#7 151.7 gyp ERR! find Python checking if "python2" can be used
#7 151.7 gyp ERR! find Python - "python2" is not in PATH or produced an error
#7 151.7 gyp ERR! find Python checking if "python3" can be used
#7 151.7 gyp ERR! find Python - "python3" is not in PATH or produced an error
#7 151.7 gyp ERR! find Python
#7 151.7 gyp ERR! find Python **********************************************************
#7 151.7 gyp ERR! find Python You need to install the latest version of Python.
#7 151.7 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#7 151.7 gyp ERR! find Python you can try one of the following options:
#7 151.7 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#7 151.7 gyp ERR! find Python   (accepted by both node-gyp and npm)
#7 151.7 gyp ERR! find Python - Set the environment variable PYTHON
#7 151.7 gyp ERR! find Python - Set the npm configuration variable python:
#7 151.7 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#7 151.7 gyp ERR! find Python For more information consult the documentation at:
#7 151.7 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#7 151.7 gyp ERR! find Python **********************************************************
#7 151.7 gyp ERR! find Python
#7 151.7 gyp ERR! configure error
#7 151.7 gyp ERR! stack Error: Could not find any Python installation to use
#7 151.7 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
#7 151.7 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
#7 151.7 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
#7 151.7 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
#7 151.7 gyp ERR! stack     at exithandler (child_process.js:390:5)
#7 151.7 gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
#7 151.7 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#7 151.7 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
#7 151.7 gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
#7 151.7 gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
#7 151.7 gyp ERR! System Linux 5.10.25-linuxkit
#7 151.7 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#7 151.7 gyp ERR! cwd /app/node_modules/@vscode/sqlite3
#7 151.7 gyp ERR! node -v v14.19.0
#7 151.7 gyp ERR! node-gyp -v v5.1.0
#7 151.7 gyp ERR! not ok
#7 151.7 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)"]: exit code: 1
```

Swapping for `node:14-buster-slim` to `node:14-buster` it builds succesfully.

## Your Environment

osx 12.1
Docker version 20.10.7, build f0df350
- Browser Information: na/

- Output of `yarn backstage-cli info`: 

```text
❯ yarn backstage-cli info
yarn run v1.22.5
$ /Users/maxknee/projects/test/node_modules/.bin/backstage-cli info
OS:   Darwin 21.2.0 - darwin/x64
node: v16.6.1
yarn: 1.22.5
cli:  0.14.0 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.8
  @backstage/backend-common                                0.10.8
  @backstage/backend-tasks                                 0.1.7
  @backstage/catalog-client                                0.7.0
  @backstage/catalog-model                                 0.10.0
  @backstage/cli-common                                    0.1.7
  @backstage/cli                                           0.14.0
  @backstage/config-loader                                 0.9.4
  @backstage/config                                        0.1.14
  @backstage/core-app-api                                  0.5.3
  @backstage/core-components                               0.8.9
  @backstage/core-plugin-api                               0.6.1
  @backstage/errors                                        0.2.1
  @backstage/integration-react                             0.1.22
  @backstage/integration                                   0.7.3
  @backstage/plugin-api-docs                               0.7.3
  @backstage/plugin-app-backend                            0.3.25
  @backstage/plugin-auth-backend                           0.10.1
  @backstage/plugin-auth-node                              0.1.1
  @backstage/plugin-catalog-backend                        0.21.4
  @backstage/plugin-catalog-common                         0.1.3
  @backstage/plugin-catalog-graph                          0.2.11
  @backstage/plugin-catalog-import                         0.8.2
  @backstage/plugin-catalog-react                          0.6.15
  @backstage/plugin-catalog                                0.8.0
  @backstage/plugin-github-actions                         0.4.36
  @backstage/plugin-org                                    0.4.3
  @backstage/plugin-permission-common                      0.5.0
  @backstage/plugin-permission-node                        0.5.0
  @backstage/plugin-permission-react                       0.3.1
  @backstage/plugin-proxy-backend                          0.2.19
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.2.0
  @backstage/plugin-scaffolder-backend                     0.16.0
  @backstage/plugin-scaffolder-common                      0.2.0
  @backstage/plugin-scaffolder                             0.12.3
  @backstage/plugin-search-backend-node                    0.4.6
  @backstage/plugin-search-backend                         0.4.3
  @backstage/plugin-search                                 0.7.0
  @backstage/plugin-tech-radar                             0.5.6
  @backstage/plugin-techdocs-backend                       0.13.4
  @backstage/plugin-techdocs                               0.13.4
  @backstage/plugin-user-settings                          0.3.20
  @backstage/release-manifests                             0.0.2
  @backstage/search-common                                 0.2.3
  @backstage/techdocs-common                               0.11.8
  @backstage/test-utils                                    0.2.5
  @backstage/theme                                         0.2.15
  @backstage/types                                         0.1.2
  @backstage/version-bridge                                0.1.2
✨  Done in 1.66s.

```

**Comment by hari2192** [comment]
Using `node:14-buster` instead of `node:14-buster-slim` solved issue for me.

**Comment by bassco** [comment]
@hari2192 and @maxknee 

What does your Dockerfile look like? 

Does it have the python3 reference like this?

https://github.com/backstage/backstage/blob/master/packages/backend/Dockerfile#L26

**Comment by maxknee** [comment]
ah looks like #9583 was merged and solves it!
