### ISSUE TITLE
Minified React error when upgrading to 0.69.2

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#9836]
I am getting the follow error after upgrading to the latest version (0.69.2) - 

```
Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.le.findDOMNode (http://localhost:7000/static/module-hot-loader.04d3f3f7.js:11:19348)
    at y.w.performEnter (http://localhost:7000/static/vendor.b71b63cc.js:103:33528)
    at y.w.updateStatus (http://localhost:7000/static/vendor.b71b63cc.js:103:33290)
    at y.w.componentDidMount (http://localhost:7000/static/vendor.b71b63cc.js:103:32751)
    at Aa (http://localhost:7000/static/module-hot-loader.04d3f3f7.js:24:1673)
    at Gt (http://localhost:7000/static/module-hot-loader.04d3f3f7.js:26:5039)
    at R.unstable_runWithPriority (http://localhost:7000/static/vendor.b71b63cc.js:154:3911)
    at It (http://localhost:7000/static/module-hot-loader.04d3f3f7.js:22:38506)
    at jr (http://localhost:7000/static/module-hot-loader.04d3f3f7.js:26:1813)
    at Ii (http://localhost:7000/static/module-hot-loader.04d3f3f7.js:24:11094)
```

![image](https://user-images.githubusercontent.com/6157895/155851495-b29a408c-7a36-4d84-b993-851cbc1f334c.png)

**Comment by JP-Dhabolt** [comment]
I am also running into the same issue.  I managed to get the unminified frontend (which is more difficult than it should be when serving the frontend directly from the backend).

```
Stack Trace
TypeError: init is not a function
    at mountLazyComponent (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17663:19)
    at beginWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:19056:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:3946:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:3995:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:4057:31)
    at beginWork$1 (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:23960:7)
    at performUnitOfWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22772:12)
    at workLoopSync (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22703:5)
    at renderRootSync (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22666:7)
    at performSyncWorkOnRoot (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22289:18)
```

It seems that the version bump of `@hot-loader/react-dom` from `@backstage/cli` to `17.0.2` is the cause of this.  I was able to workaround by adding a resolution to the root `package.json` to force it to use the old version.

```json
  "resolutions": {
    "**/@hot-loader/react-dom": "^16.14.0"
  },
```

**Comment by regicsolutions** [comment]
Thanks @JP-Dhabolt for the tip, I'll give that a try!

**Comment by Rugvip** [comment]
Looking into this. I believe that anyone that is on React 16 and upgrades to the most recent release will run into this issue. Trying to figure out whether we just want to roll back `@hot-loader/react-dom` in the CLI, or whether there's some other fix.

I would like to avoid having this warning show up when using React 17 as well:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/4984472/156150317-8408ad2f-ccc0-4466-b028-97fe56af20bf.png">

**Comment by Rugvip** [comment]
Ended up with #9879 as the fix. If anyone is able to try that out in an app that is currently having issues that'd help us make sure this issue is actually fixed 🙏

**Comment by JP-Dhabolt** [comment]
@Rugvip I was able to install this locally and verify that it resolved the issue with `init is not a function`.  Thanks for the quick turnaround on this!

On a side note, is there an easy way you would recommend to testing an unpublished package from this repo locally?  The only way I could get this to work was by cloning your branch, and then copying over the `packages/cli` directory to my Backstage installation's `packages` directory.  It worked, but seemed to be a bit clunky.

**Comment by satrox28** [comment]
@Rugvip I am still facing this issue on 0.70.1 release. Any thoughts?.

**Comment by Rugvip** [comment]
@satrox28 are you upgraded to the most recent release (0.70.1)? If so, could you post the error you're seeing?

**Comment by satrox28** [comment]
Hi @Rugvip 

Yes am on latest release, please find the error below. I can see few of the plugins, which has this error like Jira, Grafana, Gitlab and Prometheus
```
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Te (https://abc.com/static/vendor.f5c8ac4d.js:12:3937)
    at A.useContext (https://abc.com/static/vendor.f5c8ac4d.js:12:5805)
    at i (https://abc.com/static/vendor.f5c8ac4d.js:5:9544)
    at s (https://abc.com/static/vendor.f5c8ac4d.js:5:9774)
    at xi (https://abc.com/static/module-hot-loader.65268d13.js:19:52897)
    at _s (https://abc.com/static/module-hot-loader.65268d13.js:23:8729)
    at Es (https://abc.com/static/module-hot-loader.65268d13.js:23:947)
    at Za (https://abc.com/static/module-hot-loader.65268d13.js:23:875)
    at Nr (https://abc.com/static/module-hot-loader.65268d13.js:23:730)
    at bi (https://abc.com/static/module-hot-loader.65268d13.js:21:10884) ```

**Comment by satrox28** [comment]
I deleted yarn.lock and reinstall the packages, its working fine now, please ignore. @Rugvip
