### ISSUE TITLE
Wrong dist used for universal-github-app-jwt with Github App configuration

### ISSUE THREAD

**Issue by jrusso1020** [backstage/backstage#9959]
## Expected Behavior

Would expect the [universal-github-app-jwt](https://github.com/gr2m/universal-github-app-jwt) module to use the node distribution in the backend instead of the web distribution

## Actual Behavior

When swapping from Github PAT to the Github APP for programmatic access we encountered an error in production 
```
/app/packages/backend/dist/index.cjs.js:20537
        throw new Error("[universal-github-app-jwt] Private Key is in PKCS#1 format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#readme");
              ^

Error: [universal-github-app-jwt] Private Key is in PKCS#1 format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#readme
    at getToken (/app/packages/backend/dist/index.cjs.js:20537:15)
    at githubAppJwt (/app/packages/backend/dist/index.cjs.js:20565:25)
    at getAppAuthentication (/app/packages/backend/dist/index.cjs.js:21337:41)
    at hook (/app/packages/backend/dist/index.cjs.js:21614:33)
    at /app/node_modules/@octokit/plugin-request-log/dist-node/index.js:18:12
    at /app/node_modules/before-after-hook/lib/register.js:25:15
    at async Object.next (/app/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:124:28)
    at async GithubAppManager.getInstallationData (/app/packages/backend/dist/index.cjs.js:29158:30)
    at async GithubAppManager.getInstallationCredentials (/app/packages/backend/dist/index.cjs.js:29120:43)
    at async Promise.all (index 0)
    at async GithubAppCredentialsMux.getAppToken (/app/packages/backend/dist/index.cjs.js:29190:21)
    at async _SingleInstanceGithubCredentialsProvider.getCredentials (/app/packages/backend/dist/index.cjs.js:29213:17)
```

So following it's guidance we ensured to use the PKCS#8 format for the Github app privateKey

```
const importedKey = await crypto.subtle.importKey("pkcs8", privateKeyDER, algorithm, false, ["sign"]);
                        ^

ReferenceError: crypto is not defined
    at getToken (/app/packages/backend/dist/index.cjs.js:20545:25)
    at githubAppJwt (/app/packages/backend/dist/index.cjs.js:20565:25)
    at getAppAuthentication (/app/packages/backend/dist/index.cjs.js:21337:41)
    at hook (/app/packages/backend/dist/index.cjs.js:21614:33)
    at /app/node_modules/@octokit/plugin-request-log/dist-node/index.js:18:12
    at /app/node_modules/before-after-hook/lib/register.js:25:15
    at async Object.next (/app/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:124:28)
    at async GithubAppManager.getInstallationData (/app/packages/backend/dist/index.cjs.js:29158:30)
    at async GithubAppManager.getInstallationCredentials (/app/packages/backend/dist/index.cjs.js:29120:43)
    at async Promise.all (index 0)
    at async GithubAppCredentialsMux.getAppToken (/app/packages/backend/dist/index.cjs.js:29190:21)
    at async _SingleInstanceGithubCredentialsProvider.getCredentials (/app/packages/backend/dist/index.cjs.js:29213:17)
```

Upon further investigation we noticed that this appears to be using the web distribution and failing because it thinks it's in a browser as opposed to in a server. https://unpkg.com/browse/universal-github-app-jwt@1.1.0/dist-web/index.js.map

There is an open issue https://github.com/gr2m/universal-github-app-jwt/issues/38 for this in the npm package, which explains a solution by re ordering the mainFields in your webpack config, but we do not have the ability to override the config which is set here https://github.com/backstage/backstage/blame/master/packages/cli/src/lib/bundler/config.ts#L165

It's odd in that the Github App worked locally but does not work in production, could this be due to how we are building the app?

## Steps to Reproduce

1. Setup a Github App
2. Add the credentials to your app-config.yaml
3. Build backend using `yarn build`
4. build docker container
5. test running the backend 

## Context

Mentioned up above

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.17
OS:   Darwin 21.3.0 - darwin/arm64
node: v16.12.0
yarn: 1.22.17
cli:  0.14.1 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.9
  @backstage/backend-common                                0.11.0
  @backstage/backend-tasks                                 0.1.9
  @backstage/catalog-client                                0.7.2
  @backstage/catalog-model                                 0.11.0
  @backstage/cli-common                                    0.1.8
  @backstage/cli                                           0.14.1
  @backstage/config-loader                                 0.9.6
  @backstage/config                                        0.1.15
  @backstage/core-app-api                                  0.5.4
  @backstage/core-components                               0.8.10
  @backstage/core-plugin-api                               0.7.0
  @backstage/dev-utils                                     0.2.23
  @backstage/errors                                        0.2.2
  @backstage/integration-react                             0.1.23
  @backstage/integration                                   0.7.5
  @backstage/plugin-api-docs                               0.8.0
  @backstage/plugin-auth-backend                           0.11.0
  @backstage/plugin-auth-node                              0.1.3
  @backstage/plugin-catalog-backend                        0.22.0
  @backstage/plugin-catalog-common                         0.1.4
  @backstage/plugin-catalog-graph                          0.2.12
  @backstage/plugin-catalog-import                         0.8.3
  @backstage/plugin-catalog-react                          0.7.0
  @backstage/plugin-catalog                                0.9.0
  @backstage/plugin-explore-react                          0.0.13
  @backstage/plugin-explore                                0.3.31
  @backstage/plugin-github-actions                         0.5.0
  @backstage/plugin-kubernetes-backend                     0.4.10
  @backstage/plugin-kubernetes-common                      0.2.5
  @backstage/plugin-kubernetes                             0.6.0
  @backstage/plugin-org                                    0.5.0
  @backstage/plugin-pagerduty                              0.3.27
  @backstage/plugin-permission-backend                     0.5.2
  @backstage/plugin-permission-common                      0.5.1
  @backstage/plugin-permission-node                        0.5.2
  @backstage/plugin-permission-react                       0.3.2
  @backstage/plugin-proxy-backend                          0.2.21
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.2.2
  @backstage/plugin-scaffolder-backend                     0.17.2
  @backstage/plugin-scaffolder-common                      0.2.2
  @backstage/plugin-scaffolder                             0.13.0
  @backstage/plugin-search-backend-module-elasticsearch    0.0.10
  @backstage/plugin-search-backend-module-pg               0.2.9
  @backstage/plugin-search-backend-node                    0.4.7
  @backstage/plugin-search-backend                         0.4.5
  @backstage/plugin-search                                 0.7.1
  @backstage/plugin-tech-radar                             0.5.7
  @backstage/plugin-techdocs-backend                       0.14.0
  @backstage/plugin-techdocs                               0.14.0
  @backstage/plugin-user-settings                          0.3.21
  @backstage/release-manifests                             0.0.2
  @backstage/search-common                                 0.2.4
  @backstage/techdocs-common                               0.11.10
  @backstage/test-utils                                    0.2.6
  @backstage/theme                                         0.2.15
  @backstage/types                                         0.1.3
  @backstage/version-bridge                                0.1.2
✨  Done in 0.63s.
```

**Comment by jrusso1020** [comment]
I wonder if this issue https://github.com/backstage/backstage/issues/6288 is also related?

**Comment by jrusso1020** [comment]
I may have been able to get past this by adding [universal-github-app-jwt](https://github.com/gr2m/universal-github-app-jwt) directly to the backend package.json

**Comment by Rugvip** [comment]
Thank you for reporting! I think our config is just straight up wrong, so proposing #9965 :grin:
